### ISSUE TITLE
Agent not connecting after update meshcentral

### ISSUE THREAD

**Issue by alyatis85** [Ylianst/MeshCentral#1004]
Hi and thank you for your great job.
I'm testing your solution from several weeks, and it is great.
During the last update from 0.4.9-o to 0.4.9-z, after restarting the service i can't see any of the agent connecting to the server .... i tried delete certificates and regenerate them but it doesnot work. I can see all of my agent in the web console but the icon is grey ... no connexion.
what can i do ?

Thanks for your answer
Ben

**Comment by vyacheslav25** [comment]
Are new ones added?

**Comment by OutbackMatt** [comment]
You can roll back to an earlier version, but specifically detailing the version when you install MeshCentral

What OS are you running the MeshCentral Server on?

**Comment by alyatis85** [comment]
> Are new ones added?

Yes new one are properly added

**Comment by vyacheslav25** [comment]
Perhaps you have something changed in the config and the old agents have a different config.
If you have devices on mac or linux, then you can check the agent config.
If I'm not mistaken, then be on the path /usr/local/mesh_service/meshagent/meshagentx64.msh.
Try to see what's in the config.
Also try restarting the agent
linux: sudo systemclt restart meshagent
mac os: sudo launchctl stop meshagent
sudo launchctl start meshagent

**Comment by Ylianst** [comment]
Sorry for the delay, lots going on. A few things on this...

If you reset the MeshCentral "agentserver-cert" certificate, the agents will not connect anymore. This is because these two files:

```
agentserver-cert-public.crt
agentserver-cert-private.key
```

Located in the "meshcentral-data" folder uniquely identify the server to agents.  Agents will request that the server authenticate itself using that certificate. If you install the agent, you will see a meshagent.msh file you can edit with a text editor. In it, you will see:

```
ServerID=D99362D5ED8BAEA8BF9E743B34B242256...
```

This line contains the hash of the "agentserver-cert". So, if you install a new agent and this line is different from the old agent, it's probably because the server certificate is different.

One thing to look for is cases where the server is running at two different places on the same server, of was using a different "meshcentral-data" folder before the update. You can search your server to see if a different "meshcentral-data" is located somewhere else. If so, just move it to the right location and all should be fine.

I would just guess something happened that caused the server to generate a new "meshcentral-data" folder at a different location, but that is just a guess.

Hope that helps.
Ylian

**Comment by alyatis85** [comment]
Thank Ylian for your quick answer 
As it seem i've deleted the original agent certificates, is that mean i need to redeploy manually all my agents ?

**Comment by Ylianst** [comment]
Yes. If you deleted the original "agentserver-cert" certificate, you are (by design) toast. This is for security, you don't want someone else impersonating your server and taking control of all your devices.

Note that by default, MeshCentral will try to backup the "meshcentral-data" folder into "meshcentral-backups" as zip files. Take a look to see if by luck you have an older backup in that folder.

**Comment by alyatis85** [comment]
That's the case and i've no backup . It's my fault. No problem with that as i was testing the solution. It's doing some errors that we can improve. So i activated the option for backup for the future and it works but too late for this time. Thank you so much Ylian. 
Benjamin

**Comment by Ylianst** [comment]
Arg. Sorry about that. Security had to come first this time. Please keep a backup of "meshcentral-data", at anytime in the future you can wipe everything, reinstall MeshCentral and place the "meshcentral-data" folder back and you are set. If you are using MongoDB or another database, you also need to backup the database.
