### ISSUE TITLE
MeshCentral.com 1.0 vs 2.0

### ISSUE THREAD

**Issue by FilGov** [Ylianst/MeshCentral#1010]
MeshCentral 1.0 was extremely useful to us as a small company. Unfortunately, MeshCentral 2.0 crippled everything we use to the point it became virtually useless to us (worse desktop connection quality, unusable alerts, forced notifications when remotely connecting...) and we don't have resources to run our own server. Any way to (still) use MeshCentral 1.0 via the Web?

**Comment by jsastriawan** [comment]
Again, feel free to self host Meshcentral 2.0 on your own and configure to your liking. Additionally you could use Intel Endpoint Management Assistance if you wish to have Meshcentral 1.0-like experience. The team cannot satisfy every request from the community, we do our best to address the request.

**Comment by petervanv** [comment]
when money is a problem, I have another idea. buy a raspberry pi with a micro sd card with housing and of course good nutrition. this costs around € 75. Of course, the amount may differ slightly in different countries. on this you can determine the wishes that you have. cheaper is almost impossible. success.

ps if you have a nas or an old computer with ubuntu linux on it, you will also come a long way

**Comment by ryanblenis** [comment]
MeshCentral.com is updated when Ylian feels there is a stable release to get people the new / best features. I can't comment on how that decision is made, or the decisions to limit users' features / decisions when using the service. It's great that he offers it free to everyone. I don't believe there is an older version available as a free, hosted solution.

For anyone else finding this in the future, a $5/month VPS from Linode/Digital Ocean/AWS/etc. can handle a good amount of clients (not to mention an old server / desktop computer laying around, or even a Raspberry Pi). If that's out of a company's budget to have remote access capabilities, I'd argue their budget's need adjustment.

**Comment by Ylianst** [comment]
The post is probably about [https://meshcentral.com](https://meshcentral.com), which is the public free server. As the terms of use indicate, it's a great way to be initiated to MeshCentral, but if you want full control over the server and want to do anything important with it, you should really run your own.

In order to prevent people miss-using the public server, the privacy bar and connection notification are always enabled on that server and cant' be turned off. This will not change going forward. As for remote desktop quality, if you own your own server you can set this using this line in the domain section of config.json:

```
"allowhighqualitydesktop": true
```

The value is true by default but on [meshcentral.com](https://meshcentral.com), it's set to false because it's a free server and remote desktop generates a lot of network traffic.

As for alerts, adding the messagebox with ok with MeshCentral1 is on the TODO list for MeshCentral2.

I do welcome feedback, however, I don't want meshcentral.com to be a free service people depend on for anything critical. Hope that makes sense. I agree with suggestions above for low cost hosting.

**Comment by PathfinderNetworks** [comment]
I'm one of the early MeshCentral adopters.  I ran MeshCentral1 (self hosted) for years.  I've only been migrated from it to MeshCentral2 for about a year now.  MeshCentral2 is leaps and bounds better than MeshCentral1.  In pretty much all aspects.  So I'm a little confused about what FilGov is saying about their experience with it? Granted, I've never used the MeshCentral.com site so maybe it's just something to do with that particular instance?

**Comment by Ylianst** [comment]
Yes, it's about that instance. MeshCentral.com (the free public server) policy is setup to stop abusive use, of course it does not make some happy. However, with self-hosting you can setup the server any way you like. Even if MeshCentral v1 was still on running on that server, the same policies would have eventually been applied. I don't want people using the public server to take over computers without user indication, etc.

**Comment by Ylianst** [comment]
@PathfinderNetworks By the way, nice to hear from you. Your certainly one of the originals and part of the very exclusive club of people sufficiently brave to try MeshCentral v1 a long time ago. We are certainly grad we did the switch, so much easier to built and run now.
