### ISSUE TITLE
Release notes for updates?

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1012]
I just updated my server from 0.4.9-v to 0.5.0-e. After the server came back up I ran in to a LetsEncrypt certificate issue- or rather my LetsEncrypt cert was no longer being used by the server.
Fortunately I found this thread and implemented the change easily enough.  https://github.com/Ylianst/MeshCentral/issues/986

But it got me to thinking- is there a release notes repository or anything like that for the updates?  Or, even better, is there some way to have release notes be available on the 'Check server version' popup?  It would be nice to have a link on that popup to view the release notes for the current installed version as well as the latest available version. This way, before we do an update (at least an update via the web GUI) we could review the release notes so we can be ready to implement any changes that may be necessary- such as this simple config.json change to use the new acme-client.

**Comment by ryanblenis** [comment]
Also got the same issue when upgrading. A quick "lecheck" at the server console and all good!

**Comment by petervanv** [comment]
commits log: https://github.com/Ylianst/MeshCentral/commits/master

**Comment by ryanblenis** [comment]
Well, yeah, but that's not exactly the same. Some people can't read code and sometimes the commit messages may not fully match the actual changes. Case in point: the "lecheck" command that was added to the server console I had to use after upgrading today to get my cert working again.  I follow the issues and code here pretty often, but I wouldn't expect a normal user to be able to find that easily- whereas a changelog could highlight the new functionality.

Actually we do have a semi-changelog: Ylian's twitter!

**Comment by Ylianst** [comment]
I do agree with this request. I probably want to merge this idea with another idea. I would like at some point to tag some of the releases as "stable" and allow someone to jump from stable to the next stable release instead of each intermediate one. Most likely I would test the version of MeshCentral.com first before marking it as release and writing up a change log. This way, the change log would really be for each and between each stable release.

This said, there is so much work to be done, so many things I would like to work on. It's a bit crazy.

Indeed, I try to keep the [twitter channel updated](https://twitter.com/MeshCentral), I find the twitter format quite fun, and I get to put nice pictures.

**Comment by PathfinderNetworks** [comment]
I also regularly look at the Twitter feed for updates.  Maybe also post critical changes like this LetsEncrypt change to that as well?
