### ISSUE TITLE
Apache Reverse Proxy, No TLSOffload, and incorrect IP addresses

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#1022]
Mesh Server sitting behind an Apache Reverse Proxy (configs can be seen here: https://github.com/Ylianst/MeshCentral/issues/317#issuecomment-569991844), but TLS Offload is disabled. All IPs show as the reverse proxy internal IP address.

(note I don't use TLSOffload because something breaks and Mesh dies. Behind an NGINX server, works fine, behind Apache it fails to start. I don't really care to offload TLS one way or the other, I can just add resources to the correct server to deal with the load. Apache is not on same machine.)

How can I fix this?

**Comment by Ylianst** [comment]
So, in your setup, is Apache just forwarding the TLS connections from port 443 as-is? Obviously, MeshCentral will see all connections coming from the Apache IP address in this case.

When you have Apache perform TLS and forward the connection to MeshCentral, Apache (like NGINX and others) will add a HTTP header (X-Forwarded-Host) with the real source IP address of the connection. So, MeshCentral knows that is need to use that IP address for logs, etc.

I am not sure there are any solutions for fixing the IP address with pass-thru forwarding of the TLS connection. I would have Apache offload the TLS and forward the connection with X-Forwarded-Host header added. I would then add the following to the settings section of config.json:

`"tlsoffload": "127.0.0.1"`

Note that "127.0.0.1" must be the IP address of the Apache reverse-proxy. When the connection comes from that IP address and contains a X-Forwarded-Host header, MeshCentral will know to use it, otherwise it's ignored.

Hope that helps.
Ylian

**Comment by MordyT** [comment]
@Ylianst 

So my Apache Reverse Proxy is on another machine (not the MC server).

When I enable "tlsoffload": "10.0.1.50" MC crashes and won't start. This shows in the log:
```
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.5.0-h, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on mesh.domain.tld:4433.
MeshCentral HTTP server running on port 443.
Failed to load web certificate at: "https://mesh.tigunia.com/", host: "mesh.domain.tld"
Failed to load web certificate at: "https://mesh.tigunia.com/", host: "mesh.domain.tld"
```
What additional logging can I review to find out why?

**Comment by Ylianst** [comment]
Can you look in "meshcentral-data/mesherrors.txt" to see if there is any other details there?

**Comment by MordyT** [comment]
Unfortunately there is no mesherrors.txt created.

I've updated the certurl to the IP (can you remove my domain from your comment above?) and it does start, but now I get proxy errors on the webpage. 

`ERR_SSL_PROTOCOL_ERROR`

**Comment by Ylianst** [comment]
So, you need to configure Apache to perform TLS on port 443 and forward the connection to MeshCentral without TLS. It looks like your just forwarding the TCP connection as-is in Apache which you should not be doing. You need to take a look at your Apache configuration.

**Comment by MordyT** [comment]
So I got it all working... But I think there is room for improvement here.

Once I understand that tlsoffloading basically means MC shuts down all forms of HTTPS, I was able to modify Apache to http:// passthrough (on port 443), wss to ws passthough (on port 443), etc.

Then I had to change my internal DNS to route all traffic to the proxy, which means all internal traffic goes out the WAN and comes back in (not great from a bandwidth perspective)

I get that TLSOffload means MC shouldn't do anything TLS related. My proposed change/enhancement is what spawned this... MC should have better proxy support where it can use x-forward or similar to get real IP instead of having to offload TLS completely.

**Comment by Ylianst** [comment]
If Apache adds the "X-Forwarded-Host" header and the request comes from the IP address in "tlsoffload", then MeshCentral should use the IP address specified in X-Forwarded-Host.

**Comment by MordyT** [comment]
> 
> 
> If Apache adds the "X-Forwarded-Host" header and the request comes from the IP address in "tlsoffload", then MeshCentral should use the IP address specified in X-Forwarded-Host.

Correct, it does that today. I'm proposing that if Apache adds the X-Forwarded-For and tlsoffload isn't used that mesh still uses that IP.

Perhaps a variable "trustedipprovider" could be added and MC, without TLS Offload, will trust the IPs provided from that.

I'll draw this up in a few minutes and send it to you.

**Comment by Ylianst** [comment]
Well, I can add that, it would not be difficult. I want to make it super clear that the reverse proxy would have to terminate TLS, add the header and re-encrypt using TLS to send the traffic to MeshCentral. I will add it because, maybe there is a need for this, but generally you don't need to re-apply TLS between the reverse proxy and MeshCentral.

If the TLS connection is directly forwarded to MeshCentral, then there is no way for Apache to add the "X-Forwarded-Host" header. Even worst, a bad agent could insert a "X-Forwarded-Host" header and foul the server into thinking it's coming from a different IP address.

I imagine one would not generally undo TLS, process and redo-TLS in the reverse proxy?

**Comment by Ylianst** [comment]
Ha. I just looked at the code and I already have it. Instead of:

"tlsoffload": "127.0.0.1"

do this:

`"trustedproxy": "127.0.0.1"`

That will cause `x-forwarded-for` to be trusted. Let me know if that works.

**Comment by MailYouLater** [comment]
> Once I understand that tlsoffloading basically means MC shuts down all forms of HTTPS, I was able to modify Apache to http:// passthrough (on port 443), wss to ws passthough (on port 443), etc.
> Then I had to change my internal DNS to route all traffic to the proxy, which means all internal traffic goes out the WAN and comes back in (not great from a bandwidth perspective)

Wait a second, from your description it sounds like the reverse proxy is out on the internet somewhere rather than being on the same LAN as your server.  If I'm not misunderstanding what your setup is like, dropping to http between the reverse proxy and the server could also be a huge security issue and you should definitely be using `"trustedproxy": "<ip address>"` instead of `"tlsoffload": "<ip address>"`.

**Comment by MordyT** [comment]
@Ylianst I will have to try this and get back tomorrow to you on it. I had disabled the proxy because of CIRA not working (It wasn't the proxy, I have other CIRA issues) and will have to schedule time to bring it back behind the proxy.

@MailYouLater 
2 things:
1) I try to go as secure as possible. ZeroTrust means I don't even trust the LAN. So yes, Proxy is on same LAN as MC server, but I don't want unencrypted traffic from proxy to MC just in case someone else on LAN is malicious.
2) If you run a hybrid setup (agents on both LAN and WAN), and TLS is on proxy, then agents need to go through proxy. So it increases traffic as the agents need to exit LAN and re-enter on WAN side.

**Comment by OutbackMatt** [comment]
Trusted proxy works for me, using Apache reverse proxy and SSL - thanks

**Comment by MordyT** [comment]
I'm going to close this based on OutbackMatt's feedback and will open a new request if I have issues. I won't be able to test for some time for unrelated reasons.
