### ISSUE TITLE
"Special" Folders File Upload Nuance

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#1034]
Just saw this while trying to upload a file to a user, I just figured I'd drop it in their documents somewhere, so I chose the C:\Users\USERNAME\Documents\My Pictures\ folder. Of course, looking at it in explorer on their computer, the My Pictures folder does not actually exist. Uploading the file yielded a complete upload, but the uploaded file never appears in that path on the "Files" tab. The folder always appears to be empty.

It does however show up if you then navigate to C:\Users\USERNAME\Pictures. Your uploaded file will appear there as expected. While I am aware these are "Special" folders to Windows systems, for usability of the Files tab (and the benefit of users who may not know the special nature of these folders) I think either:

1. The C:\Users\USERNAME\Documents\My Pictures\  (etc.) paths should redirect or show the content from C:\Users\USERNAME\Pictures

2. The Junctioned / symlinked / shortcut folders for "My Pictures" / "My Videos" / etc. should not appear in the folder listings in the Files tab.

**Comment by Ylianst** [comment]
Since the agent is running as a "system" process, it's not logged in a any specific users. Also, from 0 to many users can be logged into a Windows OS at any given time (1 locally and many more in theory using RDP on Windows Server). So, it's not super easy to fix this, but we can look at something in the future.

**Comment by ryanblenis** [comment]
I just gave it a quick look. I believe the command we're looking for in node/JS is fs.lstatSync(), but I see that isn't implemented in the agent JS code. Not high (or even medium) priority, just figured I'd make it a known issue in case anyone comes across it. Thank you!

**Comment by krayon007** [comment]
Ok, I fixed it in the agent, and pushed it to the Agent Repo. It will be picked up in the next agent update.

The fix was pretty simple. I modified fs.readdirSync, so that it correctly handles Windows Junctions. The fix is transparent. When you navigate the Files tab, the folders that are junctions, will no longer appear empty. It will actually resolve them correctly.

**Comment by Ylianst** [comment]
Note that agent updates are less frequent than server updates. Will try to start testing the new agent in the coming days.

**Comment by ryanblenis** [comment]
Looks like the fix is now in place (v0.5.1-c). Thank you!
