### ISSUE TITLE
RDS Server Session Selection on Windows

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1040]
This isn't an issue- more a comment and a big thank you!  
I just connected to a Windows Server 2012 box that is also a RDS server with active connections.  I'm on version 0.5.0-i of MeshCentral.  When I went to the desktop connection I saw something I had never seen before- a listing of all the active RDS sessions.  I was able to choose one and then connected to the desktop view for that RDS sessions.
Just wanted to say thank you for this!  That is a pretty awesome new feature- one I didn't know had been implemented (nor when it was implemented).  For those of us with RDS servers we administer that's a very nice and very usable feature.  
What version of MeshCentral was that implemented in?

**Comment by OutbackMatt** [comment]
Apparently it's been there a while, but you had to SHIFT + connect to see that list
I remember seeing it occasionally, but not really understanding when / why.

Very recently that has been made the default view, and I agree, it is awesome

**Comment by vitko-bg** [comment]
One more big THANK YOU!!! Saw this today only. Do not know from which version it is implemented.

**Comment by Ylianst** [comment]
Matt is exactly right, it was implemented late last year and was a hidden feature you had to hit "SHIFT" to get. Since it seems that the feature worked well, the SHIFT is now switched. If you hold shift now and hit the connect button, you immediately get the local console (like it used to be).

Thanks for the feedback. Glad that this is useful. Bryan (krayon007) did most of the hard work on the agent side to make this happen, I just built the web application selector UI.
