### ISSUE TITLE
Enabling WebRTC

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1064]
on which os webrtc for remote desktop will work?
i'm using windows 7 as a target pc to connect to via agent
MC is on w10 v1909 with webrtc=true
i have tried with the latest chrome or firefox on w7 to connect to that office pc but i don't get connected,webrtc like in one of your screenshot
on w10 target v1909 and w10 v1909 pc with chrome or firefox in a lan connection i was able to to get connected,webrtc

**Comment by krayon007** [comment]
It's not is specific. I've tested it on Windows, Linux, macOS, and FreeBSD. It's more dependent on browser (Chrome and Firefox) and network topology. If you can't send/receive UDP traffic between the two endpoints, the. Webrtc won't work. (ie, if there is a proxy in between, or a restrictive NAT on both sides, it won't work)

**Comment by Ylianst** [comment]
In the settings section of config.json, add this line:

`"WebRTC": true`

This should enable WebRTC on your server. Right now, WebRTC is off by default, but I will be turning it on as it seems to be pretty solid. Feedback appreciated.

**Comment by tradexsrl** [comment]
already setup that parameters.
in my test seems only chrome use webrtc 
thank's

**Comment by krayon007** [comment]
By any chance is the machine you are running firefox on Multi-homed? I verified that webrtc works on both Chrome and Firefox, but there is a known bug with FireFox, where if the machine is multihomed, Firefox may not choose the correct interface, such that none of the RTC candidates in Firefox's offer are routable from the other endpoint.

**Comment by tradexsrl** [comment]
no is a lenovo w10 pro laptop connected via wifi.
when used with lan , automatically wifi shutdown
for your info on this laptop i have install hyper-v role to use virtual machine , maybe this role could cause the problem you told me?

**Comment by Ylianst** [comment]
I have seen this many times on my computers, FireFox will only select one network interface to advertise for WebRTC. I had situations where if I disable and enable the right interface, WebRTC starts to work because FireFox switched to advertising the correct interface. It may be that HyperV creates many more network interfaces and causes this. I know Chrome always advertises all interfaces and never has this problem.

**Comment by krayon007** [comment]
@tradexsrl , so are you saying the agent you are trying to connect to, is running inside a hypervisor? I ask, because I also filed a separate bug against FireFox for a similar scenario. I found that after one of the FireFox updates, WebRTC stopped working in my environment, if the agent was running inside a VMWare VM. I traced the problem to DTLS. Everything about WebRTC worked, until DTLS was trying to connect. FireFox would just shutdown the DTLS connection. But I found this only happened if one side was inside a VM. I only saw this issue with FireFox, and only the newer versions..  Perhaps this scenario is the same as yours?

**Comment by tradexsrl** [comment]
no no , i'm saying that my computer run hyper-v role and from my computer i was trying to connect to a remote desktop via MC and related to the question of multi-homed i was thinking maybe hyper-v install multiple virtual network that cause the problem of not using webrtc like Ylian said
Just for your information, all of our desktop run openxt as main OS which run a windows 7 vm and agent work well.

**Comment by krayon007** [comment]
Ok, got it. Yeah, that could be. On my system, the VM host computer has several virtual interfaces, so webrtc could fail if Firefox is run on the VM host, and you try to connect to an agent on the network because Firefox could choose a candidate from one of the virtual interfaces which wouldn't be routable on the local lan.
