### ISSUE TITLE
[Question] Agent Directory & Default Terminal Directory

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#1134]
Typically when starting a terminal on an agent and running `pwd` you are in the MeshAgent directory. This seems to still be the case with Windows / macOS clients, however somewhere in a recent update Linux clients now default to root `/` instead of /usr/local/mesh. 

Just wondering why the change, and why only on Linux agents?

**Comment by krayon007** [comment]
Which Linux Distro are your clients running? I did a quick check on my machines, with the current agent. They are all still defaulting to usr/local/xxxx

I didn't make any changes. As far as I know, when you connect a root terminal, it defaults to whatever the current working directory is.  Does one of your plugins change the current directory? I've never tested to see what happens if a javascript runs that changes the current working directory. I'll look into that when my kids go to sleep...

**Comment by ryanblenis** [comment]
The original report I got was for Ubuntu 18.04. I then jumped on a couple of my servers, which are Ubuntu 16.04 and 18.04, and confirmed it there as well.

**Comment by krayon007** [comment]
That's wierd... I just tested it on Ubuntu 19.10, Ubuntu 18.04 LTS, and Ubuntu 16 LTS, and it goes to /usr/local on all three of them....

When you spawn a terminal, all it does is vfork /bin/bash, so it should go to the current working directory. Very strange if the current working directory is / 

I don't suppose the .db and .msh files are in the / folder? if they are in /usr/local/.... something changed the working folder.... But I'm at a loss to explain how...

Just for giggles can you show me the contents of your: /lib/systemd/system/meshagent.service? That should define the working folder when the agent starts

**Comment by ryanblenis** [comment]
Nope, they're all in /usr/local/mesh

Here's the meshagent.service
```
[Unit]
Description=MeshCentral Agent
[Service]
ExecStart=/usr/local/mesh/meshagent
StandardOutput=null
Restart=always
RestartSec=3
[Install]
WantedBy=multi-user.target
Alias=meshagent.service
```

I'll try to start without plugins and see if that has any effect.

**Comment by uldiseihenbergs** [comment]
i see the same behavior. when staring Terminal on Ubuntu 18.04, it opens / directory.
side question - are there a way MC asks me user/password when i open Terminal? on Ubuntu you should not connect with root, but with regular user and then use sudo to run root commands..

**Comment by ryanblenis** [comment]
It connects as the user the executable is running as by default, which is root because the MeshAgent needs to control the computer.

**Comment by krayon007** [comment]
If you right click the connect button, you can choose between root, logged in user, and login shell. If you choose login shell, it will spawn an actual login shell, where you have to login. I think ylian made a configuration on the server side, where you can specify which is available and which if any is the default, such that you can make it so login shell is the only option. Login shell is not available in windows tho.

**Comment by uldiseihenbergs** [comment]
thank you, Login shell is what i'm looking for.
can you point me to that configuration? 
and with Login Shell when i login with standard user, it defaults to user home directory.
so problem is with root shell and user shell - they both default to root directory.

**Comment by krayon007** [comment]
@ryanblenis , I figured it out... Sorry I didn't take a closer look at your meshagent.service file...
But I noticed it when I setup Ubuntu on a laptop using the install script on the server, rather than the installer built into the binary...
Edit your meshagent.service file, and add the following line right before ExecStart:
WorkingDirectory=/usr/local/mesh

then save your changes, and run the command:
systemctl daemon-reload
systemctl restart meshagent

I will modify the install script to put that in the config, but it will only fix new installs. I can write some JS to fix it and have it part of the meshcore, so that when the agent connects, it can detect if this problem exists...

**Comment by ryanblenis** [comment]
Fantastic! Thank you! I saw the commit so I'll close this out now. Thank you.
