### ISSUE TITLE
Enhancement - Add Last seen in List view.

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1137]
Hi,

I know that you are very busy with all big and small request. Sorry for adding additional work on the top of all. However, I think it will be very useful to have Last Seen information in the List View.

In this case will be easier to diagnose network problems in certain departments or remote offices - if all computers in one group are offline and all are went offline at the same time, that means that internet or network went down. Otherwise I have to click on every single computer to see Last Seen information.

See below:
![image](https://user-images.githubusercontent.com/59362521/78978344-81c42f80-7b11-11ea-8ef6-b362c8bff8e8.png)

I added Date and Time all the same - but it is for example only :)

Thanks!

**Comment by ryanblenis** [comment]
Oddly enough the other night I just started an initial test-run of modifying the device page to have a "custom columns" format, where users could choose the columns to be displayed.

<img width="1646" alt="Screen Shot 2020-04-10 at 5 55 19 PM" src="https://user-images.githubusercontent.com/1929277/79025807-d76dfb80-7b54-11ea-8a51-8d30137dbe81.png">

It's early in the inception, and I need to find a way to load the associated/requested data in a sane manner without either a) grabbing everything possible; or b) making a ridiculous amount of individual queries for separate pieces of data. So I'll definitely be watching to see if @Ylianst implements your request and his preferred method of going about it.

Along with this concept, I also want to make the headers clickable for re-ordering versus the current dropdown of pre-defined sort options.

**Comment by Ylianst** [comment]
I am hesitant to implement changes that are more preferences because the real ask is really to allow more customization of the user interface. Even if I change things in the UI, it will never make everyone happy and best to allow users to setup the UI the way they want it. @ryanblenis is exactly on the right track in my view. There are a lot of things on my todo list, but I would want a "devices" page that is a lot more customizable. Different people use MeshCentral is different ways, for IoT usages, current logged in user is not important at all, but for remote support, it is.

**Comment by Ylianst** [comment]
Ok, not going to do this. However, future work on better customization of the device page would be interesting.

**Comment by si458** [comment]
this has already been implemented, you click the COG on right hand side and select 'Last Seen'
