### ISSUE TITLE
Versioning using semver? 

### ISSUE THREAD

**Issue by rgl** [Ylianst/MeshCentral#1154]
Can you version this project using semantic versioning (https://semver.org/)? 

This would make it easier for reasoning about the version number. 

Can you also make the github releases/tags more consistent and normalize them to vX.Y.Z?

**Comment by Ylianst** [comment]
Any justification for doing this? If I had to start over, I would probably change it, but now that we are using 1.2.3-a format, I am not doing to change this unless it's really important.

**Comment by rgl** [comment]
The justification is to just better reasoning about the version number (e.g. what it means, compare them).

May I ask why this started to use a letter suffix? A suffix for some packaging systems (like chocolatey) means this software version is considered a pre-release version, which doesn't seem to be the case for MeshCentral.

**Comment by Ylianst** [comment]
The current version system was just random luck. At the time, it was my first ever project on GitHub/NPM and had no idea it was going to be released so frequently. At the time the letter was like, a super minor version.

I could start using multi-digit. But one would have to know that 0.5.3 is lower than 0.5.246. or I start using 0.5.003? Seems like the current system is better.

**Comment by Ylianst** [comment]
After looking at the doc, seems like 1.2.3+a would work.

**Comment by rgl** [comment]
Please just use a version string in the form of `major`.`minor`.`build`.`patch` (the `.patch` part is optional if it does not apply to the release you are making). IMHO, any more than this should be carefully evaluated.

All of those are positive numbers (without extra leading zeros).

Please note that you are not supposed to apply a lexicographical order over the entire version string. You are supposed to convert each part to a number and compare each corresponding parts as numbers, so there is no doubt that `0.5.3` is lower than `0.5.246`.

**Comment by Ylianst** [comment]
Ok, I am sold on this. I need to check that is does not break anything.

**Comment by Ylianst** [comment]
Switched to v0.5.xxx version and dropped the letters. I expect to get to v0.5.999 before going to v0.6.0.

**Comment by Ylianst** [comment]
Closing this one since I see a thumbs up. In the future, feel free to close the issue when it's fixed.

**Comment by mwllgr** [comment]
Opening this issue again because of the recent switch to 1.1.0. Maybe future releases could follow the semver convention in the future?

The explanation from semver.org:

- `MAJOR` version when you make incompatible API changes
- `MINOR` version when you add functionality in a backwards compatible manner
- `PATCH` version when you make backwards compatible bug fixes

So, the version shouldn't really just have switched from 1.0.99 to 1.1.0, but rather to 1.0.100. I think this project would really benefit from a better versioning system @Ylianst (instead of only incrementing the `PATCH` number). So, for new features, you'd increment the MINOR number and "reset" the PATCH to 0.
