### ISSUE TITLE
[Question] RDP with MC much slower

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#1156]
may i ask, why connection to RDP with MC is much slower than plain RDP to the same server? i'm connecting to RDP with reverse connection - to localhost:port. and i see some 15-25% CPU usage on meshagent.exe on RDP side too - is this normal?
thanks for explaining.

**Comment by Ylianst** [comment]
When you say "RDP with MC", you are talking about the remote desktop protocol that is built into MeshCentral? MeshCentral does not support "RDP". In any case, yes, the built-in remote desktop is quite CPU intensive since it's capturing the screen, checking what changes and doing JPEG encoding of the changes to send it to the server. It's not as efficient as RDP that is built into Windows.

Note that you can use MeshCentral Router to perform a real RDP connection if both sides are Windows computers. Hope that helps.

**Comment by uldiseihenbergs** [comment]
i think i'm using Meshcentral router - in MC Web UI i'm using Routeplus plugin for port forwarding and then connect to localhost:<port>. i think, is this case RDP protocol is in use?
BTW, MC Web UI Desktop connection are working much smoother to the same server. that's a cause, why i'm asking..

**Comment by Ylianst** [comment]
MeshCentral Router looks like this:

![x](https://user-images.githubusercontent.com/1319013/79202332-4fa31e00-7dee-11ea-9446-d178893eb2c9.png)

If you are not sure, send a screen shot of what you are using.

**Comment by uldiseihenbergs** [comment]
i on Ubuntu desktop, so i can't use Meshcentral router. instead i'm using Routeplus plugin:
![image](https://user-images.githubusercontent.com/60253253/79205389-8c9aff00-7e46-11ea-9300-5a1345790986.png)

now i have one active mapping, so next i'm connecting to localhost:39933 with remmina.
![image](https://user-images.githubusercontent.com/60253253/79205739-ff0bdf00-7e46-11ea-8dc7-abe1c3244fa6.png)

**Comment by Ylianst** [comment]
You will have to ask @ryanblenis about this since I don't build the plugin's.

**Comment by uldiseihenbergs** [comment]
ok, will do, but i don't think it's about plugin. plugin only forwards port - i think it's the same as with your Meshrouter.exe. i would use that, but it won't work on Ubuntu.

**Comment by uldiseihenbergs** [comment]
ok, i just found a Windows laptop, and tested my case with meshcentralrouter - and then it works much better - picture are much smoother, and no noticeable CPU usage on meshagent.exe. so, looks like Linux implementation is something affected. @Ylianst how i can test RDP from Linux without using RoutePlus plugin?

**Comment by krayon007** [comment]
So if I'm understanding the scenario, the we browser is on Linux... And on the Linux machine, you browse the mesh webpage, and are connecting s Linux rdp client to local host which uses routeplus to tunnel to a windows machine, where rdp connects to windows via the tunnel?

If I'm understanding this correctly, I can try to help write something to work on Linux to test...

Which RDP client are you using? That way I can install the same one for my testing...

**Comment by uldiseihenbergs** [comment]
@krayon007 yes, you described my scenario correctly.
and i'm using Remmina (on Ubuntu 18.04) for RDP Client.

**Comment by Ylianst** [comment]
Plugin's are wonderful for flexibility and innovation, but they change a lot of the server and agent's behavior and so, they sort of "void the warranty" so to speak. Not always bad thing.

**Comment by uldiseihenbergs** [comment]
That's why i ask - how i can use MC to achieve my goal without plugins? :)

**Comment by ryanblenis** [comment]
Hi @uldiseihenbergs ,

I believe the "native" way you're looking for is to use MeshCmd on Linux to forward the port. That should get you a test-case scenario that is entirely vanilla "MeshCentral" without the use of any plugins.

With that said, you are correct in that the RoutePlus plugin merely mimics the agent code already used for TCP/UDP forwarding, and I don't imagine there will be much of a difference in your end result.

I haven't used Linux GUI RDP clients recently, but if I recall correctly, they're all a "reverse-engineered" approach. Assuming that's the case, off the top of my head, I'd imagine the "RDP" functionality of Remmina may be the culprit here, but I'm interested in the results you'd get with MeshCmd.

**Comment by uldiseihenbergs** [comment]
@ryanblenis I'm using Remmina every day to connect to various remote location and it works just fine - i can't notice any difference with Windows builtin RDP client, when i connect to the same location from my Windows laptop. 
i will try to test meshcmd again. i tried it some time ago, but it did not work for me, and then i discovered Routeplus which worked out of the box.

**Comment by ryanblenis** [comment]
In that case I'm very interested to see the results of the test with MeshCmd, because they shouldn't be much different! Thank you.

**Comment by uldiseihenbergs** [comment]
Huh, just did a bunch of tests on my side with two Windows10 remote agents - and this time looks like it worked as expected - there were very similar results with both meshcmd and routeplus. and i'm not observed any CPU spikes on agent side..
not sure what was changed - maybe MC version, i'm now on 0.5.1-r.

one thing to note to @ryanblenis - when i click on RoutePlus RDP on devices page, download starts, but web page says Disconected:
![image](https://user-images.githubusercontent.com/60253253/79419557-b3307580-7fbf-11ea-8a37-bd1810d8a620.png)
![image](https://user-images.githubusercontent.com/60253253/79419717-06a2c380-7fc0-11ea-9e60-1d818f0cb719.png)

**Comment by uldiseihenbergs** [comment]
and one more thing - when you remove port mapping, and then open up a device, "RoutePlus RDP" is still in place - when you do a full page refresh with Ctrl+Shift+R, then it disappears. i think, it should work without full refresh.

**Comment by uldiseihenbergs** [comment]
@krayon007 one more question according cpu usage. i'm connected to MC Windows 10 Desktop, it's almost idle, nothing happening, but MeshAgent is using about 10-15% CPU. is this expected behaviour?
![image](https://user-images.githubusercontent.com/60253253/79643930-37485000-81ae-11ea-92fc-ddb531d61f47.png)

**Comment by uldiseihenbergs** [comment]
@ryanblenis should i report issues about RoutePlus plugin i wrote just few posts above somewhere else ?

**Comment by ryanblenis** [comment]
Hi @uldiseihenbergs,

Ylian has said he doesn't mind if issues are open for plugins here, but I prefer on the project page so I can track them appropriately (there's a lot going on here and they could get lost, I can't close them when they're complete, etc.) - but I also check here and since Ylian doesn't mind we can keep this one here. 

That said- I can't seem to replicate your issue. What browser are you using so I can test more appropriately? And does the disconnect message pop up every time, or only in certain circumstances? Thank you.

**Comment by uldiseihenbergs** [comment]
i just created a new issues in separate threads, so closing this one.
