### ISSUE TITLE
Terminal consent misbehavior

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1164]
- Windows agent allows access and operate regardless of consent

![ACaPOI2MSs](https://user-images.githubusercontent.com/29974944/79397240-ed792300-7f7d-11ea-8299-39d6e1bc7cf5.gif)

- Linux agent allows access regardless of consent and keeps buffering the keystrokes until possible consent has been given, which seems to me abnormal in any case

![UXnK6eaWNi](https://user-images.githubusercontent.com/29974944/79398069-ff5bc580-7f7f-11ea-9568-b3135b04f05d.gif)

**MC v0.5.1-v**

Both occurrences are terminal "type" and terminal "privileges" independent.
Can't test MacOS but...if the pattern follows...

Thanks

**Comment by krayon007** [comment]
I'll look into the windows issue.. However, the buffering behavior is by design. (Or at least, it is currently a limitation by the way the server facilitates the connection with the agent)

When you click connect in the web browser, it connects to a relay server, telling the server which agent to connect to, along with what it's trying to do. By the time the agent knows the browser wants to do terminal, the browser already has a pipe setup, because it already has an active connection with the relay server. The agent connects to the relay server separately, once the tunnel is established, that's when it knows the browser wants to do terminal. So the agent simply does not connect the inbound pipe, until after consent is acquired, that's when any data that was buffered in the pipe flows thru.... To change this behavior, we'd have to change the way the tunnels are established. In this case, I didn't think it would be a problem, becuase if consent is denied, the pipe is disconnected, and the buffered keystrokes never make it to the terminal. @Ylianst can correct me if I'm wrong, but from a high level, that is my understanding...

The windows issue is separate... I'll look into that.

**Comment by krayon007** [comment]
OK, I see the bug on windows... It was a bug that was introduced when I had to add a dispatcher to workaround a bug in the ConPTY API.... I'll fix that... The fix will not require an agent update, it's just an issue in meshcore.js

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.1-w that includes Bryan's fixes. Feedback appreciated.

**Comment by amenolo** [comment]
Now fixed! :+1: 

What an amazing team you are, always a pleasure when developers can be such as good in coding as in responsiveness and explanation.
