### ISSUE TITLE
Wildcard Certificate Support

### ISSUE THREAD

**Issue by rightvision** [Ylianst/MeshCentral#118]
We tried to use our valid wildcard certificate, but then the connection url in the client tries to connect to *.domain.de. How can we setup the valid hostname....

**Comment by Ylianst** [comment]
Oh, interesting. Can you mail me the public portion of your certificate? I will get that fixed.

**Comment by rightvision** [comment]
Just send it.

We think it will be great to have the ability to

main connect mesh.domain.com
customer1 connect cust1.domain.com
...

with the one wildcard certificate *.domain.com

**Comment by whalehub** [comment]
@rightvision An alternative solution would be to use a reverse proxy in front of MeshCentral and have it use your wildcard certificate. That's the way I have it set up and it's working great.

**Comment by Ylianst** [comment]
Almost done adding wildcard certificate support. It will be in the next version.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.0-a with wildcard certificate support. Let me know if it works for you. You place your wildcard cert instead of webserver-cert* files and set the name of the server in config.json, settings, cert. If there is a problem, the server will not run and show the error. Let me know if it works for you.

**Comment by rightvision** [comment]
Up and running with the new version :-) Thanks for great support and speed.

**Comment by Ylianst** [comment]
Thanks. I had never seen what a wildcard certificate looked like before. This was a good addition.
