### ISSUE TITLE
Changes to login.handlebars not kept when updating

### ISSUE THREAD

**Issue by FDrebin** [Ylianst/MeshCentral#1187]
Just did my first update since installing and modifying Mesh Central and had set some custom test on the landing page for my instance and I noticed after the update it displays the default welcome text.

Is this intentional or a bug that the changes to the login.handlebars file was not kept during the update?

**Comment by Ylianst** [comment]
If you want to make custom changes, create a folder called "meshcentral-web" next to the "meshcentral-data" folder. Then, create a "views" folder within it and put your custom "login.handlebars" in that folder. MeshCentral will use the copy in "meshcentral-web" instead of the default one and it will be kept when upgrading. Hope that helps.

**Comment by FDrebin** [comment]
Awesome! Thank you.
