### ISSUE TITLE
Connection problem when on VPN

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1252]
It is a bit strange issue, and possibly not related to MC - but I am not sure... Could you advise please how to fix.
**My setup:**
Router with redirected port 444 to MC linux server(192.168.0.55)
Router is configured as VPN L2TP Ipsec server(providing addresses 192.168.77.0/24) - some additional vLans are configured also.
If VPN connection is not established - all clients are fine, can connect to them.
**Creating the problem:**
1. In MC - connection to one of the clients via Desktop->Connect- connection fine. - > Disconnecting.
2. Connecting client windows machine to VPN server on my router( No default Gateway option is setup, routes are added manually - so clients are still using their own internet connection. MeshAgent should use default internet connection also ). On MC when trying to connect via Desktop -> connect error on the screen "Invalid KVM command 31522 of size 24931"
on terminal connection error is: {"action":"close","cause":"noauth","msg":"noauth-2"}
3. Once VPN connection is disconnected - can connect again to clients straight away.

While client PC stay connected to VPN - agents console is working fine - but no Desktop connection can be established.

Any ideas?

**Comment by Ylianst** [comment]
I am not sure I can debug this, but here is information that may help. When you install an agent, there will be a .msh file next to "meshagent.exe", this is a text file that looks like this:

```
MeshName=MyGroup
MeshType=2
MeshID=0x5F70A4AC00B1...
ServerID=DC393B51...
MeshServer=wss://alt.meshcentral.com:443/agent.ashx
```

The "MeshServer" line is the URL the agent will try to connect to. If the "MeshServer" line stay "local" than the agent will multicast on the local network to find the server. You can replace "wss://" with "https://" and try the url from any browser to see if you can reach the server.

Otherwise, I am not sure why having a VPN would cause KVM data corruption, that is a mystery to me.

**Comment by vitko-bg** [comment]
Further update - on console i have the error in regards to this agent:
ERROR: Unable to connect relay tunnel to: wss://remote.mydomain.com:444/meshrelay.ashx?p=5&nodeid=node//****************************************************, {"message":"TLS Handshake Error"}

**Comment by vitko-bg** [comment]
Issue is solved by adding a static route to internal IP of MC server.
