### ISSUE TITLE
TLS Offloading and IP blocking

### ISSUE THREAD

**Issue by Zveroloff** [Ylianst/MeshCentral#1259]
In my scenario, I'm using MeshCentral with TLS offloading behind the IIS reverse proxy. Possibly I misconfigured something or maybe it's by design. When user attempts to log in with wrong password several times, client IP address gets blocked for a short time. It's a good practice for security reasons, but with TLS offloading it blocks reverse proxy IP (127.0.0.1 in my case) for every user, instead of real client's IP address

**Comment by ryanblenis** [comment]
Typically you'll wan't to ensure that your proxy is applying an X-Forwarded-For header with the clients real IP. A quick look a the source code shows that MeshCentral is currently looking for this header. Do you have this header forwarded?

**Comment by Ylianst** [comment]
If you take a look at the [MeshCentral User's Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.7.pdf), there are sections of NGINX, Traefik and HAProxy along with sample configurations.

As @ryanblenis mentioned, your reverse proxy should be adding the `X-Forward-For` header in the request to MeshCentral so that MeshCentral knows from that IP address this request is really coming from. Note that in addition to including this header, you should specify your TLS offload like this in the config.json file:

```
"tlsoffload" : "1.2.3.4"
```

Where 1.2.3.4 is the IP address of the reverse proxy. MeshCentral will only consider the `X-Forward-For` header if it comes from a trusted IP address.

Hope that helps,
Ylian

**Comment by Zveroloff** [comment]
Just checked my config, as I can see in Apllication Request Routing (reverse proxy in IIS) config, **X-Forwarded-For** is being passed to MeshCentral. But, in MeshCentral auth.log I see **::1** (ipv6 loopback) address logged. Is it possible that MeshCentral is not accepting X-Forwarded-For because TlsOffloading is set to **127.0.0.1** (ipv4 loppback), but in fact it gets requests by ipv6 protocol from **::1**? Is it possible to disable ipv6 for MeshCentral? It's useless if it is just a single server

**Comment by Fred1984** [comment]
hi @Zveroloff 

maybe it is too late reply, but i'm facing similar issue also with IIS and meshcentral, but i can successfully login. My problem concern only the agents as for somehow reason i cannot add agent with TLSoffload enabled.

basic config on ARR should allow you to login normally. 

my problem also concern the ipv6 protocol (::1) , all my agent is detected as : 
AGENT: New agent at ::1:55656
WEBREQUEST: (::1) /agent.ashx/.websocket
AGENT: New agent at ::1:55657
WEBREQUEST: (::1) /agent.ashx/.websocket
AGENT: New agent at ::1:55658
WEBREQUEST: (::1) /agent.ashx/.websocket
AGENT: New agent at ::1:55660
WEBREQUEST: (::1) /agent.ashx/.websocket
AGENT: New agent at ::1:55662
WEBREQUEST: (::1) /agent.ashx/.websocket
AGENT: New agent at ::1:55664
WEBREQUEST: (::1) /agent.ashx/.websocket
AGENT: New agent at ::1:55671
WEBREQUEST: (::1) /agent.ashx/.websocket
AGENT: New agent at ::1:55672
WEBREQUEST: (::1) /agent.ashx/.websocket
AGENT: New agent at ::1:55678

if you found the solution since let me know.

Best regards
frederic

**Comment by Zveroloff** [comment]
No, you're not too late. I still facing my issue and addes some details in #1315 @Ylianst made some recommedations, possibly it helps

**Comment by Fred1984** [comment]
i will continue my message on #1315 seems the very last version (not the latest stable) show something interesting to share.
