### ISSUE TITLE
Images don't fitting on Details page

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#1260]
Hi all,
Testing an Installation on Raspberry PI 4 with raspbian Buster
Latest version 0.5.15
Images in Details page are too big, see above screenshot: 

![image](https://user-images.githubusercontent.com/48550288/80598689-05df4800-8a2a-11ea-8d67-0c1d0f89c3c1.png)

Don't know if is only a Rpi/linux issue or global

Thanks

Merlinweb

**Comment by merlinweb** [comment]
updating to 0.5.17
same situation

Thanks

Merlinweb

**Comment by ryanblenis** [comment]
I always just assumed this was a design decision.

**Comment by merlinweb** [comment]
uhm, toggling left bar don't adjust images view:
![image](https://user-images.githubusercontent.com/48550288/80605521-80609580-8a33-11ea-94fe-219cd720b2a0.png)

guessing is wrong image size/resize on page...

Cheers

Merlinweb

**Comment by vitko-bg** [comment]
> I always just assumed this was a design decision.

My thought are same as yours :)

**Comment by merlinweb** [comment]
so, is it the same for every installation, despite OS used?
Not Rpi only 
It's good to know...
thanks

Merlinweb

**Comment by asasin114** [comment]
I've got the same issue with my instance running on Server 2019. It's such a minor issue that I don't even care though.

**Comment by Ylianst** [comment]
So, this is by design. I build the user interface, so really, I just made the decision to do this since it looked cool. If you look in the `node_modules/meshcentral/public/images/details` folder, you will see the images are like this.

![image](https://user-images.githubusercontent.com/1319013/80624593-bdf7fb00-8a00-11ea-8b93-63bf2c4b7e16.png)

Feedback appreciated. The it feels odd, I can take a look at something different.

**Comment by merlinweb** [comment]
It's more than ok :)
"De gustibus non est disputandum"
there is no functional issue, keep this way 

Thanks all

Merlinweb
