### ISSUE TITLE
Any option to disable keyboard and mouse access and provide only view only mode during remote connection

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1266]
Any option to disable keyboard and mouse access and provide only view only mode during remote connection

**Comment by krayon007** [comment]
There currently a checkbox at the bottom of the Desktop Tab, that says, "Remote Input". If that checkbox is not checked, then remote input (keyboard/mouse) will be disabled...

Are you referring to something like this, or do you mean a server option, to force that mode, so the user cannot enable it?

**Comment by Ylianst** [comment]
Two solutions for this. Depending on the situation, you can use the "Input" checkbox, or assign "Remote View Only" permission to a user. Let me know if this helps.

![x1](https://user-images.githubusercontent.com/1319013/80742237-e4d13280-8acf-11ea-8ae2-f464a8d4338a.png)
![x2](https://user-images.githubusercontent.com/1319013/80742247-e7338c80-8acf-11ea-8e37-0d63b2493889.png)

**Comment by OutbackMatt** [comment]
If understand these these options correctly, they stop someone who is connecting to the remote machine from providing input.

What I'd like to see, is a feature that exists in team viewer, where I as a remote admin, could take over a remote computer, black out the screen at that end (because it may be in a public place, and we like to show a black screen to whomever is physically near the remote machine), and limit input from anyone sitting physically at the machine, until I am done being admin.

If we RDP to the remote machine, that's effectively what happens.

**Comment by Ylianst** [comment]
@OutbackMatt That is a different ask than the issue above also, it's unlikely it's possible for us to both capture the screen and blank it out. RDP can do it because it's a separate virtual desktop, they can blank out the main desktop and start up a different virtual session. I am going to close this one, but please open again if needed.
