### ISSUE TITLE
Can't download agent from Chrome/win10 [Raspberry]

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#1283]
Hi,

I am in trouble with exe downloading from MC2 portal:

Server: MC2 0.5.20 on Raspberry pi 4 with Raspbian Buster
Client: Windows 10 Pro - 1903 [Version 10.0.18362.778]
Chrome Version 81.0.4044.129 Official

Trying to downloads any software in "My Devices":
- Agent (32/64)
- Router
- MeshCmd
Server answer with  a generic file meshagents:
![image](https://user-images.githubusercontent.com/48550288/80872711-fd9a3d80-8cb3-11ea-800d-919d0117e47a.png)

Chrome can't download File, network error:
![image](https://user-images.githubusercontent.com/48550288/80872905-3555b500-8cb5-11ea-854f-9c9143dd74e4.png)

But at the end, if I click on long url in Download section of chrome, I can download selected exe file:
![image](https://user-images.githubusercontent.com/48550288/80872953-8ebde400-8cb5-11ea-86f3-5149a9fd1b50.png)
 
In Firefox same operations are completed without any trouble

Another useful info, I guess:
On my primary production installation, Winserver 2016, same computer works well:
![image](https://user-images.githubusercontent.com/48550288/80873153-dc871c00-8cb6-11ea-8ab3-78a9edbf7a8c.png)

Seems something related to raspberry....

Fresh installation, no plugin, no Rev Proxy

Hope this help

Cheers

Merlinweb

**Comment by Ylianst** [comment]
Wow, that is interesting. I have a Raspberry Pi 3, I will try it!

**Comment by ryanblenis** [comment]
I see this from time to time in my dev environment- Chrome simply blocks the download because it is a file from a site with an untrusted (self-signed) cert with a "Failed - Network Error" (FYI server in this case is a Docker container, not a Pi). 

If you go to the downloads page in Chrome after the failed download and click directly on the https://192.168.0.2/...... link it should download. I think this is more of a Chrome protection than an MC bug.

**Comment by merlinweb** [comment]
ok, I can live with it, until I will include a certificate in MC.
Firefox don't have this extreme protection, and it's a bit faster than Chrome in MC, keep using it
Thanks for support
Merlinweb
