### ISSUE TITLE
desktop not working on ubuntu 18.04 client

### ISSUE THREAD

**Issue by changchichung** [Ylianst/MeshCentral#129]
Server: Ubuntu 18.04 Server
Meshcentral : 0.3.0-J
Client: Ubuntu 18.04 Desktop

I install a new meshcentral server this morning , but remote desktop still in black with nothing and there`s a error message

![](https://i.imgur.com/Lzh6MN4.png)

I read the issue here https://github.com/Ylianst/MeshCentral/issues/37
that problem should already been fixed couple months ago , and there`s no error messages like what I had.

is there any suggestions ?

**Comment by krayon007** [comment]
if you phyically log in on the client machine, and type the following in a terminal window:
echo "$XAUTHORITY"
echo "$DISPLAY"

do you get the two values in your error message?

**Comment by changchichung** [comment]
> if you phyically log in on the client machine, and type the following in a terminal window:
> echo "$XAUTHORITY"
> echo "$DISPLAY"
> 
> do you get the two values in your error message?

both return nothing 

![](https://i.imgur.com/SiCaYrP.png)

**Comment by krayon007** [comment]
Did you change the DesktopManager? I just tested it on my clean insteall of Ubuntu 18.04 LTS, and it works... I ask, because it is not normal for $XAUTHORITY and $DISPLAY to not be defined inside a user session. That usually only happens if the DM is not configured to use X.

Can you show me the output of: 
ps -ax | grep X

Here's a note I added to the makefile a while ago, describing this issue that I saw. I can't remember which distro I saw it on, I think it was openSUSE, but I can't remember off the top of me head.

Special Note about KVM Support on Linux:
If you get an error stating that an Xauthority cannot be found, and asking if your DM is configured to use X, you may need to:

    1. Open /etc/gdm/custom.conf and uncomment WaylandEnable=false.
    2. Add the following line to the [daemon] section:
       DefaultSession=gnome-xorg.desktop

**Comment by changchichung** [comment]
```
Did you change the DesktopManager?
```
No , although I run ansible to manage the client , but there`s no task about change DesktopManager. it`s still the default setting ( gdm? )

```
Can you show me the output of: 
ps -ax | grep X
```
2019-03-18 08:57:49 [mini@hqpc074 ~]$ ps -ax |grep X
  818 tty1     Sl+    0:00 /usr/lib/xorg/Xorg vt1 -displayfd 3 -auth /run/user/120/gdm/Xauthority -background none -noreset -keeptty -verbose 3
 1211 tty2     Sl+    0:00 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/20230/gdm/Xauthority -background none -noreset -keeptty -verbose 3
 2099 pts/2    S+     0:00 grep --color=auto X
2019-03-18 08:58:07 [mini@hqpc074 ~]$

**Comment by jsastriawan** [comment]
This potential due to gdm.service and gdm3.service in systemd services folders. Disable and remove one of those may help resolving the problem.

**Comment by changchichung** [comment]
I think the problem was related to the Xauthority and $DISPLAY

![](http://i.imgur.com/jXgbFiD.png)

those error messages was in the meshcentral log , I do not know why those varaible was "undefined".

and somehow , I reboot that client couple times , the remote desktop works !
I will try to reinstall a fresh new OS , try before/after ansible managerment to see if the ansible cause the problem.

**Comment by changchichung** [comment]
I`m wondering if this problem related to vm or not ?
after couple weeks trial , I found out that I could not get remote desktop running on virtual machine.
the physical machine will not accept connection before I reboot the target , but after reboot , everything works.
the vm is another story , I can get the XAUTHORITY and DISPLAY 
![](http://i.imgur.com/3JjhT8N.png)

But remote desktop shows 
```
Error trying to determine XAUTHORITY/DISPLAY: TypeError: undefined not callable 
```
I don't know if it's a coincidence or not , but all the vms I tried , failed with  desktop sharing.
I used Proxmox VE as hypervisor , and any more informations should I provide ?

**Comment by krayon007** [comment]
What version of the server are you running? I pushed a change that fixed an issue there if there were multiple xauth found, and previously is esd always choosing the first one. I have since fixed it to use the one that was spawned by the same uid.

I'll have to check which server version included this change.

**Comment by changchichung** [comment]
0.3.0-n , upgrading now

**Comment by changchichung** [comment]
geez , you are amazing !
after upgrade to 0.3.2-n , the problem solved !
