### ISSUE TITLE
Desktop / Terminal / Files / Events / Console options are missing!?

### ISSUE THREAD

**Issue by Armando817** [Ylianst/MeshCentral#13]
This software is great. I am just getting started and have created a mesh with two devices. Both devices are very similar; Windows 10 - 64bit, etc. Both devices connect and display: My Devices / My Account / My Events / General, but one of them does not display the Desktop / Terminal / Files / Events / Console options. I can't figure out what option on that device is turned on or off that may be causing this to happen. Any suggestions? TIA!

**Comment by Armando817** [comment]
jsastriawan, thank you for your response. I need to get over to that machine to check...as I can't remote in quite yet.  ; ) I will post the contents as soon as I can. Thank you very much.

**Comment by Armando817** [comment]
hrmm...no log file there. 

Only:  .exe,  .msh, .db

???

**Comment by nicrame** [comment]
I've got similar problem, but with Windows 7 PC.  I'll check system logs, if there is similar info.

**Comment by lee3521** [comment]
I have the same problem, however, it only seems to be related to the Windows computers in my mesh.  I get all of the proper menu options at the top of the screen when viewing details of a Linux computer.

When I click on the computer device in the mesh list, viewing the details of the Windows computer, my menu options in the menu bar at the top of the screen are:
My Devices, My Account, My Events, My Files, My Users

General, Events, Console

If I right click on the Windows computer in the list of computers instead of left clicking on the computer, I get a menu with the following options:
Information, Terminal, Desktop, Files, Events, Console

Is there a reason that the menu options Information, Terminal, Desktop, and Files do not appear at the top of the screen when I left click to display the individual computer?

I also have some Linux computers in my mesh.  When I left click on a Linux computer, I am able to see all of the proper menu options at the top of the screen in the menu bar.

I wonder if this has something to do with me running the mesh-central server on a Linux box as all of the options show up when connecting to a Linux box, but not when connecting to a Windows box.

**Comment by nicrame** [comment]
Well, for me, the one Windows 7 box still do not have options, even i know there were work done for Windows 7 compatibility.
The only thing i found on that PC was this inside MeshAgent.log, but i'm not sure if it will help: 
[2018-09-06 05:06:59 PM] FATAL EXCEPTION [MeshAgent_9795C7C9AA9F6985.exe] @ [FuncAddr: 0x000000013fa92006 / BaseAddr: 0x000000013fa8ea00 / Delta: -13830].

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.0-u on NPM with a critical fix for Windows7. After you update the server, you may need to stop the agent on the Windows7 machine and delete the "meshagent.db" file (in program files/meshagent") and start the agent again. The bug caused the MeshAgent to lockup on Win7 and not work at all.

**Comment by nicrame** [comment]
So i updated central (server), then stopped service (agent) on PC box, deleted .db file, and started again. The result is that i still do not have more options in the upper menu in central gui, but also do not have options to connect with right mouse button. I think, it would better to leave those options to stay when they did work :) It's worse now (and of course, no .log file again).

![zrzut ekranu 99](https://user-images.githubusercontent.com/5872054/45818181-410f8600-bce1-11e8-9a42-0a6c8defad93.png)
![zrzut ekranu 100](https://user-images.githubusercontent.com/5872054/45818182-41a81c80-bce1-11e8-85c1-f2379bf76ed2.png)

**Comment by Ylianst** [comment]
We finally got to the bottom of this problem. On some computers with the Intel Management Engine but that don't have Intel AMT the MeshAgent is waiting forever to get the information about Intel AMT and never sends any capabilities to the server. We also have another threading issue on Windows to fix. So, I just published "MeshCentral v0.2.0-x" on NPM, you can go in the device's "console" tab and enter "**sendcaps 15**" to work around the issue for now. This will enable all menus for the device immediately.

This problem will only occur on some specific computers, hope to get a permanent fix in the next few days.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.0-z on NPM with a fix for this problem.

**Comment by jsastriawan** [comment]
Ouch... Yes I saw that issue if AMT probe failed on non AMT capable MEI. I didn't realize this come out again.

**Comment by Ylianst** [comment]
This problem is completely fixed in latest version of MeshCentral. Even if there is a problem detecting Intel AMT, the tabs will still show up correctly.
