### ISSUE TITLE
How to update Server IP dynamically in the MeshAgent post instalaltion

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1304]
Hi ,

i have installed MeshAgent with one server, but after that my server IP i have modified. in that case i hope the Mesh Agent will not communicate ? How to achieve this with connect only mode (not running as service or installation)

**Comment by ryanblenis** [comment]
The server connection info is in the meshagent.msh file in the MeshAgent directory. If it is one-time instead of persistent you'll get the new information upon downloading a new agent from MC.

Highly recommend using an FQDN so you can update DNS remotely and have all the clients reconnect rather than via IP address, where you have to touch each device or re-deploy in order to update that setting.

**Comment by Ylianst** [comment]
If you look at MeshAgent in one of the managed computers, you will find a meshagent.msh file that is a text file that looks like this:

```
MeshName=Home Computers
MeshType=2
MeshID=0xEDBE1BE3771D69...
ServerID=D99362D5ED8BAEA8BF9E7...
MeshServer=wss://central.mesh.meshcentral.com:443/agent.ashx
```

You can edit the "MeshServer" to connect your IP address and restart the agent. There is no automated way to do this, as @ryanblenis indicated above, you should be using a FQDN. Hope that helps.
