### ISSUE TITLE
Desktop connect broken when 2nd user connected via RDP 

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1310]
Do not remember in which version of MC - it was working fine.
Now with current latest version 0.5.24 it is not working anymore.

BEFORE - Once user connected via RDP to host from MC on Desktop connection it was showing which local session I would like to connect to:
![image](https://user-images.githubusercontent.com/59362521/81163893-581eec80-8f87-11ea-80bf-7a24f6b45136.png)
and once active RDP connection is selected can interact with RDP logged in user together. RDP user and MC operator can see and work together.

NOW - same situation, BUT does not matter which session is selected - RDP or Console - it shows lock screen to enter the password. So looks like Active, RDP-TCP connection link is redirecting to console session.

**Comment by krayon007** [comment]
By any chance do you know what is really being displayed in the RDP session? I just tried it just now, and it correctly connected to the RDP session. But there is a known issue where if the RDP session is displaying a UAC prompt, you will not be able to connect to the session because Windows denies my request to capture the screen. This only happens with UAC prompts in the RDP session, not the console session.

**Comment by vitko-bg** [comment]
Really in RDP session was couple of open windows - explorer, Outlook, etc. No UAC warnings. 
Before from MC when selecting Active, RDP-Tcp session - MC was connection to same session as RDP user, so both sides are able to see the screen. Now via MC it shows password screen to login to windows.

**Comment by vitko-bg** [comment]
Confirmed working after reinstall!
Have no idea what went wrong ......
Thanks all!

**Comment by vitko-bg** [comment]
Still same - tested today on working environment.
One of stuff is working on VM at the moment and need help - before was able to login and help him.
No when clicking on Connect..... and selective Active RDP Session it shows me locked screen.
