### ISSUE TITLE
Monitor number

### ISSUE THREAD

**Issue by eu4you** [Ylianst/MeshCentral#1368]
And one more suggestion,

When selecting Screen menu, I want the monitor number to appear in the divided position.
I`m using 8 monitors to do the job of viewing a lot of documents on a computer,
but I'm not sure what number of monitors it is.

**Comment by Ylianst** [comment]
Is this on the mobile web site? That is a good idea, I am running out of space but will see that I can do.

**Comment by eu4you** [comment]
Thank you. But I wish it were on the desktop too. After setting the monitor position, many people may do not memorize the monitor number.

**Comment by si458** [comment]
im trying to figure out what you need exactually?
do you mean you want numbers to be displayed on top each of the little monitor icons next to the time at the bottom?

**Comment by si458** [comment]
sadly this isnt going to be possible, as the order we list the monitors is based on the X and Y
but if i take my quad monitor setup for example (in a square combo)
windows lists the monitor as
3 - 4
1 - 2

but meshcentral will list them as 3, 1, 4, 2 because we start at the top left and work down then over
