### ISSUE TITLE
Question: MongoDB, failover,  Mesh, and Multiple Geo Locations

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1370]
Hi All,

We two offices connected by site to site VPN.   Let's call them Main office and Remote office, each with their own internet connection.  The remote office houses the Mesh server.  People in the Main office sometimes lose connection to the mesh server (at the remote office) because internet drops, or vpn drops on one side or the other for any number of reasons.

I want to use MongoDB to put a Mesh server at both locations.  That all makes sense enough with replica sets, replicating across the VPN and failover, but what I can't see is how to route the connecting agents.  Is there some way to route the connecting agents to both locations?  Round robin DNS or something?  In short, if one location disconnects for any reason, I'd like employees to be able to connect to the alternate mesh server at the Main Office.  Is this possible?  Thanks

**Comment by ryanblenis** [comment]
MeshCentral's server peering guide indicates that both servers need to be behind a central load balancer, so I don't think you're going to be able to accomplish this with 2 geographically distinct locations / IPs. You could utilize a load balancer in the cloud to facilitate it, but at that point it would make more sense to use the cloud resource as a central server (MC doesn't require much for resources, so even a $5/mo VPS @ DO/Linode would handle a large amount of connections). 
Round Robin DNS isn't a failover, it just serves the DNS blindly whether or not the back end server is available or not, unless you're using something else to inform DNS of healthy backends, in which case you're in for headaches anyway because DNS is often cached for a set amount of time, hence the usual route of a load balancer.

**Comment by Ylianst** [comment]
I have never been in this situation, but some of my thinking on this. Obviously, my preferred option would be to just host MeshCentral in the cloud and not have to worry about which sites are up or down and you can also manage mobile computers as they move around the Internet. It's easy to setup and you get maximum flexibility.

This said, if you have an Intranet MeshCentral server, you can just copy your server at both sites and as long as the DNS points to the correct server, it's going to work. Your going to have two separate databases, but as long as the same "agent" server cert is in "meshcentral-data" at both places, the agents should connect just fine. Of course, if you create a new account or device group on one server, you need to copy the mongodb/netdb database to the other.

I would not try to do MeshCentral peering in this situation since if your internet goes does your going to have issues. I am not familiar with what services MongoDB provides in that situation, also, I have been testing MeshCentral peering in a long time, I think I would have to debug and fix things.

**Comment by southeasterntech** [comment]
That's quite an excellent pair of answers.  Thanks @Ylianst and @ryanblenis.  I'd feared that was the case, as I couldn't see how to deal with sending the agent connections to one place or the other.   I'll give Linode a look.  Thanks Ryan.
