### ISSUE TITLE
Scrolling from Mac

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1387]
I'm sure more details will be required so let me know what I can provide to make this more clear.

When controlling a computer remotely, Mac or PC, from a Mac, scrolling does not seem to work consistently. It works fine when initiating the connection from a PC but on Mac, scrolling with the scroll wheel on my mouse or gestures on the trackpad, position jumps around a bit erratically.

**Comment by Ylianst** [comment]
I don't do any testing on Mac, I should start. What Browser are you using and does the browser make a difference?

**Comment by PetieM** [comment]
I primarily use Chrome but tested it in Safari and Firefox as well - all three browsers exhibit the same behavior. It seems at times that scrolling down specifically is an issue though even that is inconsistent as sometimes, it just jumps suddenly and others, it briefly scrolls in reverse (which I suspect might be related to the Mac's handling of "natural" scroll direction.

**Comment by Ylianst** [comment]
Not sure if I will be able to do anything about it, within a web page, your limited to what events the browser sends you. But I should take a look at it.

**Comment by ryanblenis** [comment]
I can replicate this on Mac as well as Windows (both from Mac and from Windows admin sessions). Seems that the direction is not respected and you are only able to scroll upward (when the admin controlling session is a touchpad - e.g. scrolling with 2 finger touch).

Modifying [this](https://github.com/Ylianst/MeshCentral/blob/master/public/scripts/agent-desktop-0.0.2.js#L462) line allows the scroll to work, albeit scrolling VERY quickly by changing 

`((Delta / 256) & 0xFF)`
to 
`((Delta) & 0xFF)`

Presumably because the former always equates to a very small value of 0 (e.g. 0.001342), which eventually equates to 0 with the binary, whereas the latter produces actual binary values. @Ylianst  can probably do something with that info, as I'm not entirely sure of compatibility with actual scroll wheels or the expected values of those calls- but it certainly CAN work!

**Comment by Ylianst** [comment]
Yes, I see what is going on! Just fixed it, will be in MeshCentral v0.5.38 when I publish it. Thanks for the report. The problem happens on all platforms and browsers, but you see it most when your mouse wheel was set to be as slow as possible.

**Comment by PetieM** [comment]
Confirmed that this seems to be working correctly in 0.5.38. Thanks!
