### ISSUE TITLE
Question: Group functions

### ISSUE THREAD

**Issue by orion88-admin** [Ylianst/MeshCentral#1424]
Hi,

I found a function in the device group settings. This option is called:.
**Sync server device name to hostname**
How does it work ? Because as I marked it in my reasoning for this option, the host name after the change should also change in the main meshcentral window on the My Devices tab. But this did not happen, only a new option appeared with the name of the operating system and assigned a new host name. 
Shouldn't it sync automatically?

![MC_SYNC1](https://user-images.githubusercontent.com/65662158/83116074-95305780-a0cb-11ea-9b72-8b1f49fd9a32.JPG)
![MC_SYNC2](https://user-images.githubusercontent.com/65662158/83116099-9bbecf00-a0cb-11ea-82b4-cabb9191c83e.JPG)
![MC_SYNC3](https://user-images.githubusercontent.com/65662158/83116107-9d889280-a0cb-11ea-8111-4c2fada9ad6f.JPG)

**Comment by dinger1986** [comment]
@si458 I think you can close

**Comment by si458** [comment]
this happens BECAUSE when the device is added,
it sets the name as a 'nickname' so it thinks the computers 'nickname' is 'WIN7-BRUCE-LEE'
but the OS name is oversally 'WIN7-BRUCE-LEE-TEST'
so one way to fix this is simpy set the 'nickname' (pencil at top) to the SAME NAME as the OS NAME,
then afterwards it should clear the 'nickname' and it should sync the OS NAME on next change correctly
