### ISSUE TITLE
[Feature Request] Multi-tenancy

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#1428]
I'm not sure if this is much more involved than initially perceived, but I feel that multi-tenancy would be a good addition to the project. I think many RMM's have this so multiple different administrators (MSP / Internal IT personnel / etc.) can control the same device without overwriting the others configs / taking full control while utilizing the same product on [potentially] their own server infrastructure, and could also be used as a backup server connection while upgrading a server (in those wierd / rare instances where servers seem to lose access to clients during an upgrade that there have been a few issues about).

I bring this about right now as I know @krayon007 just modified the installer to be via javascript and work on all systems, as well as changed the install directory so thought this may complement it well.

Suggested implementation:

Folder structure:
C:\Program Files\Mesh\Agent\[First 10 of the ServerID]\MeshAgent.exe/db/msh

Service name: 
MeshAgent[First 10 of the ServerID]

Each service would simply run its own instance, and would also make local/remote testing pretty handy. Thoughts?

**Comment by krayon007** [comment]
That's an interesting idea... Off the top of my head, the main issue we'd have to work through, is how to identify the agent... Currently, on Windows, the agent's name (according to the Windows Service Manager), is "Mesh Agent". So whenever anything in the agent (mostly the self-update part) queries the status of the agent, whether its running, what it's PID is, etc, will ask windows for "Mesh Agent". This is also true, when the agent goes to ask the Windows Crypto API to sign something, as it the certificate was saved into the Crypto Store as "Mesh Agent".

An easy work around, I think, would be to modify it, so that instead of "Mesh Agent", it would be "Mesh Agent" plus whatever unique server identifier. This would be the simplest approach, but is a bit complicated, because the self-update aspect of the agent is compiled in C, and I don't think you want to be recompiling agents all the time on the server. 

Again, thinking outloud, I would think to solve this problem is to fetch the identifier from the MSH file, then store it in the db.

Another option, would be to take advantage of command line parameters... I added the ability to specify command line parameters in the installer, so that when the service manager starts the service, it passes those parameters to the agent. (Supported on all platforms)... I can imagine a scenario where we use the same agent binary, but then you can add multiple entries in the Service Manager, that point to the same binary, but with different parameters, so the different instances of the agent can be started with different personas... Altho this assumes it's ok that the different instances are using the same binary... But again, I'm just thinking out loud...

I'll defer to @Ylianst

**Comment by ryanblenis** [comment]
I'm not too familiar with the self-update code, but wouldn't it just be a path fix from %ProgramFiles%\Mesh\Agent\ to %ProgramFiles%\Mesh\Agent[ServerID], and the executable being updated would be queried from the agent-to-be-updated's current working directory?

I think using the same agent with command line parameters would cause too many issues due to different providers being on different server versions (either via an "update-fight" trying to update the agent to the version that matches the server is is talking to, or simply being incompatible with the server such as not having a feature on server version 0.5.50 versus 0.5.60) hence the different directory recommendation.

**Comment by krayon007** [comment]
> I'm not too familiar with the self-update code, but wouldn't it just be a path fix from %ProgramFiles%\Mesh\Agent\ to %ProgramFiles%\Mesh\Agent[ServerID], and the executable being updated would be queried from the agent-to-be-updated's current working directory?
> 

The update mechanism needs to be able to tell the Windows Service Manager to stop/start the service, otherwise it can't update the binary, because the file will be locked. So it needs to be able to use the correct identifier with the Service Manager, to start/stop the correct service instance.

**Comment by ryanblenis** [comment]
Ah, gotcha. So it sounds like it could just use the ServerID in the msh file to inform that action. Looking forward to Ylian's thoughts!

**Comment by si458** [comment]
this feature exists and its called `domains` inside your `config.json`
https://ylianst.github.io/MeshCentral/meshcentral/#domains

**Comment by MordyT** [comment]
While the server is multi-tenant, the client installers are not unless you customize them as described here: https://meshcentral-community.com/doku.php?id=howto:customization

**Comment by si458** [comment]
@MordyT the client installers are multi-tenant as they are built based on your url `https://MYMAINDOMAIN.com/DOMAIN` OR `https://MYCUSTOMDOMAIN.com` if you use the DNS option instead of just a SUBDOMAIN option
then you can go further and customise each installer with images/icons etc for a true multi-tentant setup
