### ISSUE TITLE
How can I move to stable release from beta release.

### ISSUE THREAD

**Issue by AnjaniKumar15** [Ylianst/MeshCentral#1453]
Currently I am on your beta version 0.5.50. How can I move to stable version 0.5.11 release. Whenever I choose stable release and apply. It only restart Meshcentral server but after this, It is not changed version. How to do this.

**Comment by Ylianst** [comment]
Not sure what is going on, but you can install any version of MeshCentral by using for example:

```
npm intall meshcentral@0.5.11
```

This will install that specific version, otherwise the latest is always installed. For why the update does not work, it's possible MeshCentral is unable to find or run "npm". One way to fix this is to specify the NPM path in the settings section of config.json like this:

```
"NpmPath": "c:\...\npm.exe"
```

Also, MeshCentral needs to have sufficient rights to overwrite itself for self-update to work.

**Comment by canove** [comment]
Same here. I can update to last beta version from the "Check server version" page, but i can't downgrade to stable.

**Comment by Ylianst** [comment]
Ok, I will check this.

**Comment by Ylianst** [comment]
I just tested it on the development server and it works for me, I was able to move back to v0.5.11 and forward again to v0.5.63. If you can detail what you mean by "i can't downgrade to stable" more precisely, that would be great.

**Comment by AnjaniKumar15** [comment]
Its working. Now I am also able to switch to both beta and stable version. Thank you.
