### ISSUE TITLE
How to embed a REST web service in meshcentral server 

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1466]
I have written a Web service js to get the few information from the Meshcentral in way easy to retrive the node id of the device. 

How to add this web service (REST) add part of the meshcentral?

**Comment by Ylianst** [comment]
There is no way to add REST calls right now, there is a way to add a static web site by adding a domain with a "share" key like this:

```
  "domains": {
    "": {
      "Title": "MyServer",
      "Title2": "Servername",
    },
    "info": {
      "share": "C:\\ExtraWebSite"
    }
  }
```

This will serve what is in the "C:\\ExtraWebSite" folder when you call the server with `/info/...`

Also, another trick you can try is to add `?trace=1` or `&trace=1` at the end of the URL and open the browser console. You will see all of the commands the are sent between the browser and the server, for example:

![image](https://user-images.githubusercontent.com/1319013/84354372-9e163400-ab75-11ea-9728-a685b3aab9f2.png)

You can then write an application that makes the same WebSocket connection and makes the same calls. You can get the list of devices, users, etc.

Lastly and probably most interestingly for you, you can use "meshctrl.js", this is a command line tool that allows you to script MeshCentral. On the MeshCentral server try:

```
node node_modules/meshcentral/meshctrl.js
```

You should get something like this:

![image](https://user-images.githubusercontent.com/1319013/84354669-20065d00-ab76-11ea-95ce-6fa5026626fb.png)

You can then use this to list devices, create accounts, etc. You should probably use this first, it's also possible to copy "meshctrl.js" to a different computer and run it from a different computer, not just on the server itself. This command is useful because it authenticates with the server using your username/password/2FA.

In general, you can always edit the MeshCentral code and add a REST API, but you need to make sure it's authenticated correctly and secure. Best to use meshctrl.js if you can, or let me know if something is missing.
