### ISSUE TITLE
windows defender smarscreen unknown publisher

### ISSUE THREAD

**Issue by Fred1984** [Ylianst/MeshCentral#1470]
hello @Ylianst, 
i know this topic already discussed several times here before, but seems windows consider the certificate as not trusted and i don't really understand how to self signed the exe automatically.
![image](https://user-images.githubusercontent.com/62277469/84223740-45ab4c00-ab0d-11ea-82c0-674a68fea4b1.png)

![image](https://user-images.githubusercontent.com/62277469/84223986-ff0a2180-ab0d-11ea-8ecb-7113431dc4b3.png)

![image](https://user-images.githubusercontent.com/62277469/84223860-9a4ec700-ab0d-11ea-8a71-42fb0673f79a.png)

I'm not an expert in certificates yet (even if i learnt a lot here), but is there any way to automatically sign with the certificate from the domain name i use? or by an chain/intermediate certificate. because I guess if i sign by myself the certificate, on the next agent update it will wipe of the signature?

i'm using 0.5.54 server, with tlsoffload and external let's encrypt software (certify the web)

**Comment by Ylianst** [comment]
Hi. So, a long time ago, I used to sign the MeshAgent.exe with a real code-signing certificate, but since people are not always using the MeshAgent for good, I got my certificate auto-revoked one morning, I never even got notified that this happened. There are previous threads on GitHub about this story.

In any case, if you go in `\node_modules\meshcentral\agents` and you will see the following five files:

```
codesign.cer
MeshService.exe
MeshService64.exe
MeshService-signed.exe
MeshService64-signed.exe
```

Two of the files are signed using my own self-signing certificate and the public part of that certificate is the "codesign.cer" file. So, if you add that certificate as a trusted cert in Windows, that two signed files will be recognized as ok. Alternatively, you can sign the two unsigned agents with your own code signing certificate and replace the "-signed" files, that will also work.

Note that you can't use a TLS certificate for a domain name to sign an executable, you need a code-signing certificate from a trusted Certificate Authority and that is in the 200$/year (or something like that). You need to file some paperwork with the CA, send proof of who you are, etc. Once you get your code-signing certificate you will need to re-sign the agent each time you update MeshCentral, but that should not be difficult, you can make a script with do that.

Hope that helps,
Ylian

**Comment by Fred1984** [comment]
hi @Ylianst thank you , i understand better, now, i will review this and see later if i purchase a certificate,

thank you for the explanations!
