### ISSUE TITLE
Agents show regularly disconnected for few seconds on the console

### ISSUE THREAD

**Issue by Fred1984** [Ylianst/MeshCentral#1471]
hello, 

i may made a mistake in my reverse proxy or meshcentral settings, but the console randomly show the device disconnected, then come back without any actions. i normally setup nginx reverse proxy with TLS offload to keep the SSL connection for 15m, and on meshcentral the only things i activated regarding agents are "AgentPong: 60, "AgentNoProxy": true, and "AliasPort": 443, i don't know if it is related.

Consequence is when emoting or transferring something it disconnected suddenly

Did someone already experienced this? it may be a network server but before i setup a reverse proxy, i didn't notice it.

If someone can help to understand?
using the server version 0.5.54

**Comment by uldiseihenbergs** [comment]
try increase `AgentPong: 300`..

**Comment by Ylianst** [comment]
Hi. When looking at "AgentPong", the number is the number of seconds between each "pong" packet. So, you want to keep this low for debugging and increase it when things start to work and you don't want to generate too much traffic. Start with:

```
"AgentPong": 10
```

So that all agents will get a data packet sent to them each 10 seconds. In addition to this, it's not clear to me if it's the agent or the browser and is dropping the connection. When you make a browser-to-agent connection, if one drops, the other will also get dropped. Try this:

```
"BrowserPong": 10
```

This will send traffic to the browser every 10 seconds. Let me know if that helps. If it fixes it, start increasing the values to 60 or 240 and see when it starts to break.

If it still fails, try `"BrowserPing": 10` instead, this will cause data to be sent to the browser and the browser will respond and send a "pong" back, so you get traffic going both ways every 10 seconds.

Hope that helps,
Ylian

**Comment by Fred1984** [comment]
hi, seems i cannot go more than agentpong 59 else the problem appear, problem is targeted to the NGinx who close the connection after 1 min. so i will try to figure out and reconfigure it.

thanks
