### ISSUE TITLE
Bug? RDP link redirect to the wrong address 

### ISSUE THREAD

**Issue by Fred1984** [Ylianst/MeshCentral#1472]
Hello, 
when i click on the RDP link from a computer details area, it open a new page: http://meshcentraldomain.com:81/.... and without http**S**. is it a normal behavior?

if i keep the same address without :81 my browser ask me to download a software "meshminirouter.application" (My nginx reverse proxy redirected to http**S** just before) which says after few seconds : cannot be connected. 

is it a bug or a normal behavior and i miss something again?

**Comment by Ylianst** [comment]
This is not a bug, is your server is using a non-trusted TLS certificate, there is no way to make ClickOnce connect to the server. That is, even if you go in your browser and say it's ok to connect to this server with invalid certificate, ClickOnce will still not work. So, the current workaround is to load the click once app from the HTTP server. After it's loaded, the ClickOnce app will connect to HTTPS for traffic. Hope that explains it.

**Comment by Fred1984** [comment]
hello, @Ylianst ,

my certificate is well trusted by let's encrypt. But maybe i wasn't clear enough about this, below is the link pointing to a secure address

![image](https://user-images.githubusercontent.com/62277469/84364293-7ae59600-ac02-11ea-851b-ff28959be65c.png)

 but after clicking the final page is which i cannot connect as the port 81 is not open , or should I? 
![image](https://user-images.githubusercontent.com/62277469/84364657-f6dfde00-ac02-11ea-886e-43b9c793d3fe.png)

**Comment by Ylianst** [comment]
Oh, that is not right. By the way, I was sort of considering dropping support for ClickOnce because you can how register the MeshCentral Router with the "mcrouter://" protocol and launch it from the web site on all browsers without the need for ClickOnce.

If you have not tried it, check it out. Let me know if this would be a better option for you.

![image](https://user-images.githubusercontent.com/1319013/84450644-9bfbb600-ac05-11ea-9884-31a0c56d0979.png)

**Comment by Fred1984** [comment]
hello no problem for me then with Meshcentral Router!
