### ISSUE TITLE
Tags and Description set from the GUI are lost on device/agent restart

### ISSUE THREAD

**Issue by rdodeja** [Ylianst/MeshCentral#1474]
Not sure if this is how it is supposed to work, but if i add new strings to tags and Description
the are good only till the node or the agent are restarted. 
 could be a bug

**Comment by Ylianst** [comment]
Are you talking about this tags...

![image](https://user-images.githubusercontent.com/1319013/84330605-b3bb3780-ab3c-11ea-8e66-61ed75ff1385.png)

I just tested it and it works for me. I can set a tab, restart the server and see the tag again. What database are you using?

**Comment by rdodeja** [comment]
We are using the standard Linux install, if I do a reset device or reboot the device the tag and description are both reset to empty

________________________________

**Comment by Ylianst** [comment]
So, what database are you using? Also, if you do any other changes, like checking a device name and/or icon. Does the change stay?

**Comment by rdodeja** [comment]
There is no customization we have done and you have access to one of my groups as admin  this is on meshcentral.com your free public portal of Meshcentral2  http://meshcentral.com in the internet

There is a device
General - sdo_demo [cid:image001.png@01D63FCC.801534C0]
Description
Manage SDO devices [cid:image001.png@01D63FCC.801534C0]

Type
Managed using a software agent

Features
Auto-Remove [cid:image001.png@01D63FCC.801534C0]

User Consent
Desktop Toolbar, Terminal Notify, Files Notify [cid:image001.png@01D63FCC.801534C0]

Notifications
None [cid:image001.png@01D63FCC.801534C0]

Intel® AMT
No Policy [cid:image001.png@01D63FCC.801534C0]



[cid:image002.png@01D63FCC.801534C0] Add Users<https://meshcentral.com/?viewmode=20&gotomesh=n4FpEIarbDyMLBY5qWTSS6jVFxJstgyQjx1FmBxVO8ABITJoSW0WVqj82jNz21Rc>[cid:image002.png@01D63FCC.801534C0] Add Agent<https://meshcentral.com/?viewmode=20&gotomesh=n4FpEIarbDyMLBY5qWTSS6jVFxJstgyQjx1FmBxVO8ABITJoSW0WVqj82jNz21Rc>[cid:image002.png@01D63FCC.801534C0] Invite<https://meshcentral.com/?viewmode=20&gotomesh=n4FpEIarbDyMLBY5qWTSS6jVFxJstgyQjx1FmBxVO8ABITJoSW0WVqj82jNz21Rc>
User Authorizations
 admin
[cid:image003.png@01D63FCC.801534C0]<https://meshcentral.com/?viewmode=20&gotomesh=n4FpEIarbDyMLBY5qWTSS6jVFxJstgyQjx1FmBxVO8ABITJoSW0WVqj82jNz21Rc>
Full Rights [cid:image001.png@01D63FCC.801534C0]

Try updating Tag,  Description  etc on this device

**Comment by rdodeja** [comment]
Ok looks like I found the condition under which I see the tags being deleted

If I set the  Remove device on disconnect  in the Edit Device Group Features then those settings are lost. Is it expected to work this way?
I guess these tags are really useful if they are preserved if the same device reconnects. , so in some way these tags should be stored on the device too using the meshagent

Specially the disconnected devices are removed and only online devices are visible and when there are a large number of device I want to search using the tags

Hopefully  you can help..

Thanks
Rakesh

**Comment by krayon007** [comment]
That is intended behavior. Remove on disconnect, means remove from database. That is intended for devices that only connect once. It sounds like what you want is for only online devices to show in the UI? If that is the case, there is a checkbox that says "online" next to the filter text box at the top of the web ui. If you check that box, only online devices will appear in the UI.

**Comment by Ylianst** [comment]
There is a new "Online" filter on the user interface to only display devices that are online. With this, you don't need to set removal of devices on disconnect.

![image](https://user-images.githubusercontent.com/1319013/85609298-c89ecd00-b60a-11ea-9f18-f716283ce2b5.png)

**Comment by rdodeja** [comment]
What I really need to know if the IP address of the network port on the device which is connected.
But we want to use the feature of remove the device from database on disconnect
What are the ways to get additional information displayed somewhere like the IP address.  And use in search
What you display today is the IP address of the  internet IP address of my home and that is useless as I have tons of devices inside my home lab and I keep installing new OS’s automatically onboarding to meshcentral and rebooting and restart from fresh. So the previous hostname, and the device information is useless and needs to be removed from the database
This is to develop a Scalable infrastructure

See the devices in the attached image:
[A screenshot of a cell phone  Description automatically generated]

**Comment by rdodeja** [comment]
That’s good but I also need to get the actual ip address of the device  when there are large number of devices

**Comment by Ylianst** [comment]
Ok, I think I have a solution that will fix most of the issues you are having. Once an agent is installed, you can create a "MeshAgent.tag" file. This file must have the same name agent the agent executable, but with .tag at the end (on Windows, remove .exe and replace with .tag, on Linux add .tag to executable name).

![image](https://user-images.githubusercontent.com/1319013/85633268-c732cc00-b62d-11ea-9192-67aeeb25cc35.png)

This is a small text file, you can put up to 1k of data in it. Put some unique tag for your device and restart the agent. For my example, I used Notepad and created a text file with the word "BlueTop" in MeshAgent.tag. Once you restart the agent, it will show on the server as an "Agent Tag". For me, it looks like this:

![image](https://user-images.githubusercontent.com/1319013/85633389-03fec300-b62e-11ea-8026-08ceb7e849fd.png)

Now, I just added a new filter option that is going to be in MeshCentral v0.5.72 that allows you to filter on Agent tags. You have to type `atag:<string>` or just `a:<string>`. For example:

![image](https://user-images.githubusercontent.com/1319013/85633549-4922f500-b62e-11ea-976b-54c7ff7cc2d6.png)

This will filter everything except devices that have the word "blue" in the agent tag. The search is not case sensitive.

Because the agent tag is sent by the agent on each connection form the agent, you should be able to use it even for temporary agents and if you re-format a computer, you are free to put the same tag on that computer. Let me know if that helps.

**Comment by rdodeja** [comment]
You are Just Amazing!!
Thanks
This will be a great help..
Will test it out and let you know
Thanks
Rakesh

**Comment by Ylianst** [comment]
MeshCentral v0.5.72 is published, update and give it a try. Let me know how it works.
