### ISSUE TITLE
Terminal 'Up arrow' fails to return the previous command in Windows embeded 32bit

### ISSUE THREAD

**Issue by songunsw** [Ylianst/MeshCentral#1483]
Hi guys,

I am struggling with the terminal command history. Up or down arrow usually allows the choose among the previous commands. But in the Windows embeded 32bit PCs, It seems return the exact code we sent to the remote agent via websocket. Maybe the mesh agent side fix is required?

https://www.reddit.com/r/MeshCentral/comments/h0sz2a/terminal_up_arrow_fails_to_return_the_previous/

I was informed by Ylianst from reddit that it is a known problem with these old windows versions. With the latest versions of Windows, Microsoft changed how the terminal works to make it more like Linux. Not sure if it's a easy fix if it was working on MESH1.

Really appreciate if it can be fixed.

![gjsyij0qv7451](https://user-images.githubusercontent.com/9344308/84453015-c6e41980-ac9a-11ea-8383-cef6d408774c.png)
![dzpk18yow7451](https://user-images.githubusercontent.com/9344308/84453044-d7948f80-ac9a-11ea-8b38-852c0b30dd38.png)

**Comment by krayon007** [comment]
If you type "osinfo" on the console tab, without quotes, it will tell you if your platform has support for Microsoft's PseudoConsole API. It's called ConPTY. It will say true or false. Judging by your build and version number, it looks to be based on Windows 7, so it's unlikely this can be fixed for that platform.

**Comment by songunsw** [comment]
It shows
OS: Windows Embedded Standard [Version 6.1.7601] [ConPTY: NO]

If it was working in the old MESH, any chance we can let agent to fallback to the old way doing so?
Any other main features in the terminal may be affacted?

**Comment by krayon007** [comment]
That actually is how it works. I implemented the new terminal support in a separate module so the first thing it does is it checks to see if the new APIs are supported and it will load either the old module or the new module. if it used to work in the past and it no longer works now do you know the server version of when  it used to work? I can take a look at it if you do

**Comment by songunsw** [comment]
That's great!
I found following log mentioning the version number in MeshLog-RelayServer.txt
6/5/2020 10:48:10 AM - EVENT: ServerStart, 0, 1.0.6104.24041
and I connected to the old MESH1 server from the same device, and confirmed it was working.
![MESH1](https://user-images.githubusercontent.com/9344308/84460882-66f76e00-acae-11ea-90d2-bc4f4b0c530e.png)
and the version showing on the meshagent is 0.2.0.3
really appriciate the help. Brayon.

**Comment by songunsw** [comment]
Hi @krayon007 , just check have you got a chance to have a look at the issue?

**Comment by krayon007** [comment]
I haven't had a chance to look at it yet... So are you saying this only worked on Mesh1 and not Mesh2? I ask because the codebase for Mesh1 and Mesh2 is completely different.

**Comment by songunsw** [comment]
Yes Byran, it works well when using MESH1 agent. I am upgrading our network from version 1 to 2, from the same remote device, only MESH1 up arrow works in the terminal. The screenshot and version number was attached in the previouse comments.

**Comment by songunsw** [comment]
@krayon007 Hi Byran, was the server version I provided helpful? any further information you need?

**Comment by songunsw** [comment]
Hi @krayon007, any update is appreciated.

**Comment by krayon007** [comment]
I looked into this, it looks like this was never supported on Mesh2, only in Mesh1. It was supported by the agent intercepting the up arrow, and manually keeping a stack of commands, that it manually parsed out of the stream. (This is prone to errors). This would not be something that can easily be shimmed into Mesh2, because the code base for the terminal is completely different from each other. Retooling the terminal to simulate this behavior would be limited to older Windows Systems, as newer Windows Systems implement a Pseudo Console API (ConPTY) with proper terminal support, which we already currently support, falling back to legacy/simulated terminal if ConPTY isn't detected on the platform.

However, @Ylianst had mentioned this could be something that is easier to implement server side, so that you can select recent commands directly in the browser interface, for these situations.

**Comment by songunsw** [comment]
Great to hear from you, @krayon007 ,  I was thinking server side implementation may be error prone, because it seems like the command data was sent via web socket for each key press, rather than the command string. Stacking the commands from the agent side may be more reliable?

However, I think doing from the browser UI is also fine as long as user has a way of retrieving their previously used commands. At the moment, the users in my newly upgraded MESH network complain why this feature is broken and used to work in MESH1. Do we have any estimated time for fixing this issue on server or agent side, so I can inform them? Many thanks guys!

**Comment by krayon007** [comment]
> Great to hear from you, @krayon007 , I was thinking server side implementation may be error prone, because it seems like the command data is sent via web socket for each key press, rather than the whole command string. Stacking the commands from the agent side may be more reliable?
> 
> However, if it is a much easier approach, I think doing from the browser UI is also fine as long as user has a way of retrieving their previously used commands. At the moment, the users in my newly upgraded MESH network complain why this feature is broken and used to work in MESH1. Do we have any estimated time for fixing this issue on server or agent side, so I can inform them? Many thanks guys!

I think what Ylian had in mind, was a mode where you type the whole command and it doesn't get sent until you press enter, sort of like those old word processors... In this fashion, the browser side java script could save the commands at the same time...  Doing things the Mesh1 was is actually complicated because the data is received as individual keycodes. As far as the agent is concerned, when you intercept these keycodes, it actually doesn't know what is currently running, so it doesn't know if it's saving actual commands, or just keypresses for the currently running application/session/script/etc. Plus, when it selected a previous command, it had to manually render the thing as VT-100 because Windows didn't have an actual pseudo console interface, so the whole thing had to be faked by screen scraping the physical console, which was problematic for other reasons...

**Comment by songunsw** [comment]
Yeh, that is indeed a very good idea, offer user another option to send the whole command instead. And let javascript stack the commands. And meanwhile, UI is listerning the arrow up/down, so the user can still navigate among the previouse commands stacked.

This mode can even work well for both old and new terminal versions.

**Comment by si458** [comment]
this is partly implemented already
on linux, pressing up arrow will show previously run commands.
on windows, pressing up arrow will show previously run commands BUT ONLY WITH POWERSHELL
