### ISSUE TITLE
Hide/Remove Root certificate from login page...

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1507]
Is there an option to hide/remove root certificate from the login page?
A Let's Encrypt certificate is in use - so I cannot see any reason of having a link and ability to download a Root certificate.
What is it for? Any other reason?
Thanks.

**Comment by Ylianst** [comment]
The root link is for people that use the self-signed HTTPS certificate and want to add it to their browser so that they don't get the warning. It's only useful on private networks or for private servers where the owner will only access it from a few browsers.

This said, the link should be auto-removed when a different HTTPS certificate is in use. Are you using "tlsoffload" or "certurl" in your config.json?

**Comment by vitko-bg** [comment]
No, none of them.
BTW, my full config is in #1503 
Please advise if something is wrong and how I can improve it..... Thanks @Ylianst

**Comment by Ylianst** [comment]
How are you using a Let's Encrypt certificate? Do you have a reverse proxy in front? It does not look like you are using Let's Encrypt support that is built into MeshCentral?

**Comment by vitko-bg** [comment]
No, I am not using built in Let's Encrypt functionality. And yes, it is behind a reverse proxy on NGINX

**Comment by vitko-bg** [comment]
After playing with config,json, Let's Encrypt certificates and NGINX, "Root Certificate" is not on the screen anymore. Would like to share more info what exactly I have done - but to be honest have no idea at what point it disappeared.
Thanks for help.
