### ISSUE TITLE
Blackening remote display using mesh central

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1520]
Is there any option to disable "Blackening remote display" in the target mesh agent during the remote session.

**Comment by Ylianst** [comment]
No support for this now. Not sure how we would go about doing it.

**Comment by SomeGuru** [comment]
Traditionally RDP does this, but that is because it allows a single user session on Consumer Windows versions... This would not benefit those that need multi-user connections. Albiet maybe something to try via MeshRouter to get your black/blank screen on the remote system. This would solve the issue you want without changing the greater good of the rest of the MeshCentral folks. 

Give it a shot!
-SomeGuru

**Comment by SomeGuru** [comment]
MeshRouter to make the pseudo network, then rdp to the agent system and enjoy the RDP session that is wholistically just your connection.

-SomeGuru
