### ISSUE TITLE
How can I avoid that WINDOWS detect the mesh central agent like a virus

### ISSUE THREAD

**Issue by CLAVERATOR** [Ylianst/MeshCentral#1529]
We all know that when you download the mesh...agent.exe in you computer, windows show you an alert like a there is something wrong with the program that you have downloaded, How could we avoid that, maybe with a trusted certificate? I don't know

**Comment by vitko-bg** [comment]
There are previous requests about this issue. Usually I adding meshagent into AV exceptions

**Comment by CLAVERATOR** [comment]
thank you for your answer but, but imagine that you want to take the control of an external computer, this computer have an user that he don't know nothing about computers and the user see this alert, My question is if there is any way to avoidthat message.

**Comment by vitko-bg** [comment]
To be honest it is a pain, as even with invitation link when downloading MeshAgent it is with download alert on Chrome, Edge, IE and more.... Not sure if some certifica can be applied to EXE file itself.... @krayon007 i think should know more, I think he is more involved in Agent.

**Comment by CLAVERATOR** [comment]
ok, thank you so much

**Comment by krayon007** [comment]
Honestly, I have no idea how to fix it. Signing it won't help, because whatever AI they are using to detect malware, is defective. Compounding the issue is their reporting mechanism... Rather than having a valid/trusted signing certificate preventing them from flagging it as a virus, they report the virus to the signing authority, causing our certificate to get revoked for "signing malware", which is why the agents are now signed with a self signed certificate, rather than an actual cert that we paid for.

Some AV vendors are better than others it seems, as some don't give us any problems.

**Comment by vitko-bg** [comment]
I am just wondering if that issue is somehow related to passwords or IDs for the remote connections.
Let's say LogMeIn Agent have a password configuration, TeamViewer - password and ID, AnyDesk - connection ID..... so what if MeshAgent installation will be just like and generic app(not sure if can be named that way :) ), and only after installing on the PC **and** configuring some password for remote sessions - then only MeshAgent to establish connection to MeshCentral. 
From the other side - on MeshCentral, when connecting to device, password configured on MeshAgent installation to be required(with option for saving it)
Not sure if that is good idea, and if that will work, just thinking about it :)
And 100% I do not know if that is easy to rich task .......

**Comment by krayon007** [comment]
> I am just wondering if that issue is somehow related to passwords or IDs for the remote connections.
> Let's say LogMeIn Agent have a password configuration, TeamViewer - password and ID, AnyDesk - connection ID..... so what if MeshAgent installation will be just like and generic app(not sure if can be named that way :) ), and only after installing on the PC **and** configuring some password for remote sessions - then only MeshAgent to establish connection to MeshCentral.
> From the other side - on MeshCentral, when connecting to device, password configured on MeshAgent installation to be required(with option for saving it)
> Not sure if that is good idea, and if that will work, just thinking about it :)
> And 100% I do not know if that is easy to rich task .......

It already works this way tho... The agent will not attempt to connect to a remote server, unless some fields are configured on the agent, via the msh file, or command line parameters.
