### ISSUE TITLE
File download/upload - file type restriction

### ISSUE THREAD

**Issue by HLneoh** [Ylianst/MeshCentral#1556]
Hi, is there a way to dynamically set a specific list of file types that allow to download/upload. 

For example,
Set only .txt is allowed.
1. Only able to upload .txt file.
2. Only able to download .txt file.

Thanks.

**Comment by SomeGuru** [comment]
HLneoh,

Are you saying that you want to control the file choice that is installed? This may hamper the server capabilities if others need to transfer a file like a WIM and yet the only allowed on the server was set to .txt ending... I mean there is nothing to keep a user from just renaming the larger file from .wim to .txt. So this could be easy to bypass in that way... Otherwise if they implament where the agent would seek the header information of the file, this could have a potential of being to much snooping on systems due to having to check the file header... 

I get the premise, I just don't see where the benefit lays if there isn't deeper file inspection. Please give me a little more detail as to how you see this from your perspective?

Thank you,
SomeGuru

**Comment by HLneoh** [comment]
Hi SomeGuru,

From my perspective, I am thinking to add protection to the files for both remote and host pc. This is to prevent the user misuse the remote and host pc. For example, the user can only see and download specific type of files that are restricted by the remote pc. Yes, you are right. That's why I am planning to disable the rename function. 

Thanks!

**Comment by si458** [comment]
this wont be added as it defeats the purchase of a remote support software, u might need to copy any type of files
