### ISSUE TITLE
version 0.3.1-p otplib install failed

### ISSUE THREAD

**Issue by billymoox** [Ylianst/MeshCentral#157]
Hi,
After updated to 0.3.1-p system try to install otplib when starting. 
![meshcentral](https://user-images.githubusercontent.com/40301062/55152548-81e0cf80-5148-11e9-99ef-b601e048778b.jpg)

**Comment by Ylianst** [comment]
Hi. You can install the package manually using "npm install otplib". I am going to guess that you installed MeshCentral as "sudo" or that your "mesh" account does not have rights to make any changes to the node_modules folder. If this is the case, run "sudo npm install otplib" and it will install correctly. Repeat for any other missing libraries.

**Comment by Ylianst** [comment]
One more note on this. I realize there is a bit of an issue here because often, people install MeshCentral using a normal account and then use an account with lower privileges to run the MeshCentral server. Problem is, MeshCentral is trying to install modules that require the normal account and that is not going to work.

**Comment by Ylianst** [comment]
In new versions of MeshCentral released today, the call to NPM now sets the working directory correctly which could help with this type of problems. I am going to close this issue since it's likely fixed. However, feel free to re-open if needed.
