### ISSUE TITLE
Update Window

### ISSUE THREAD

**Issue by CCWTech** [Ylianst/MeshCentral#1591]
Feature request:

Mesh seems to update frequently (which is awesome that so many bug fixes and features are coming out). But when it updates it kicks everyone out for a few minutes. From what I understand you can turn off updates but that's not desirable. Is there a way to restrict updates to non production time?

**Comment by Ylianst** [comment]
So, I don't generally recommend turning on the MeshCentral self update feature, especially in production servers because you get updates in the middle the night, people get kicked off for 20 seconds and if something goes badly, there is no admin present. To turn this off, edit "meshcentral-data/config.json" and remove the following line:

```
"selfUpdate": true
```

Once you restart the server, it will no longer update automatically. You can still update the server anytime manually in the "My Server" tab when logged in as administrator. Hope this helps.

**Comment by CCWTech** [comment]
Thanks!
