### ISSUE TITLE
Unknown command "showconfig", type "help" for list of available commands

### ISSUE THREAD

**Issue by Tomatoschewps** [Ylianst/MeshCentral#1635]
Hi,
In my search of ldap logs on meshcentral server I've tried the "My Server" "Console" view and figured that "showconfig" isn't recognized but listed in the "help" list.
My2cts :)
D.

**Comment by Ylianst** [comment]
Your right, I just removed the "showconfig" command from the help. I removed this command as part of a security sweep because it discloses too many secrets. This said, if you really want to command back, I can make it so that your would need to specifically opt to have the command added back in the config.json if you like. Hope that makes sense.

**Comment by Tomatoschewps** [comment]
I just mention it to report the bug, no need for me.
IMO we need it only for the installation so we can directly read the config file ^^

**Comment by Ylianst** [comment]
Thanks. That was a good report.
