### ISSUE TITLE
Option to disable user input on remote host

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1645]
I'd like to second OutbackMatt's request in issue #1266, i.e. disable keyboard and mouse input and lock the screen, with the option to display a message like one can do with Apple Remote Desktop.

**Comment by Ylianst** [comment]
We would have to do some exploring in this space.

**Comment by PetieM** [comment]
I appreciate the desire and potential utility for a feature like this but consider that disabling remote input is frequently used to facilitate tech support and similar scams. Given that this software is free, open-source, and easily installed with minimal hardware requirements, I'm not sure including such a feature is a good idea. It's potential for abuse would seem to outweigh its utility for those using it correctly.

If this is implemented, an override from the user side that can't be disabled by the admin and that is clearly shown on screen should be included with it.

**Comment by Ylianst** [comment]
Interesting comment on this feature. The potential for abuse of MeshCentral or any other remote management software is already pretty high, you may be right that this is a step too far.

**Comment by vitko-bg** [comment]
> Interesting comment on this feature. The potential for abuse of MeshCentral or any other remote management software is already pretty high, you may be right that this is a step too far.
Unless full administrator password MUST be typed in on MC in order to use this feature ......

**Comment by wh1te909** [comment]
Meshcentral gives you access to a full on shell running as SYSTEM so you can already take complete control over a pc, including blocking keyboard/mouse input from the command line with a simple win32 api call. So don't see why you would not add it to the web interface.

The lack of this feature is what is preventing us from completely switching to mesh, we still are paying thousands of dollars a year for LogMeIn simply because we are able to disable remote input / blank the screen which we use heavily at our MSP and I am sure most MSP's do too. Feature comes in handy especially when terminating employees and management asks us to take over and prevent employee from doing any harm, or simply just not having to fight for keyboard/mouse control with the end user when we are trying to help them with computer support.

**Comment by southeasterntech** [comment]
I agree with @wh1te909 here.  At our MSP, we often have to fight users who don't "get it", the fact that we are remote connected and trying to help them.  Disabling them temporarily allows us to effectively do our jobs, since they usually continue to drive their computer even after we're connected.  Same for the terminated employee.  They don't understand that they're interfering with us getting them fixed, or complying with management.  We want MC to be the best product possible, and there are a 1000 other ways already for scammers are already connecting and do their damage (Logmein, GTMPC), adding the currently more obscure MC to that list won't change this.  At the end of the day, if the end user is gullible and lets a scammer in to their computer, (I defer to Phishing as an example) then the scam is going to happen anyway.  I'd rather have an increasingly functional tool.

My appreciation to the whole team at MC...  You guys are changing the industry, especially for us in IT Support.

**Comment by vitko-bg** [comment]
I am in also. If that will be possible, it would be another great option in MC.
Thanks for all hard work!!!

**Comment by robclay** [comment]
+1 on this

@wh1te909 , Are you familiar if there is a win32 call to blank the screen?

**Comment by wh1te909** [comment]
@robclay not familiar with one, did some googling found this to turn off the screen but pretty useless since it turns back on as soon as you move mouse/keyboard. I guess right after you could also block keyboard/mouse input, although you'll effectively just lock yourself out at that point xD. good for preventing someone from using the computer though and then maybe just log them out from meshcentral's terminal so you can just RDP in? which will show the lock screen anyway while you're logged in.

```
import win32gui
import win32con
import ctypes

SC_MONITORPOWER = 0xF170
win32gui.SendMessage(win32con.HWND_BROADCAST, win32con.WM_SYSCOMMAND, SC_MONITORPOWER, 2) # turn off monitor
ctypes.windll.user32.BlockInput(True) # block keyboard/mouse input
```

**Comment by VINISHVV** [comment]
Awaiting for this feature in meshCentral.

**Comment by Kuuchuu** [comment]
This is a must need feature for when we are dealing with credit card data remotely.

**Comment by krayon007** [comment]
This feature is almost done, just working on a few issues on linux..

**Comment by imennodenis** [comment]
+1 for this feature, especially blanking remote screen! We sometimes have to do some admin tasks on remote kiosk/digital signage PCs which are installed in public places so we do not want people see what we are configuring there :)

**Comment by si458** [comment]
This is partly completed already now,
You can make the monitor sleep by using the console and sending `display sleep|awake` 
You can disable the mouse/keyboard input with the keyboard icon that's on the bottom right hand side
Sadly I haven't found a way to yet use the pc remotely with the monitor turned off

But as the issue was about disabling input, I'm going to close this issue now :)
