### ISSUE TITLE
0.3.1-v won't install

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#166]
getting following error on 0.3.1-v
0.3.1-u is working

![0 3 1-v](https://user-images.githubusercontent.com/7434746/55600128-96583580-570f-11e9-96ea-de302b02a838.JPG)

**Comment by PathfinderNetworks** [comment]
I just updated mine from 0.3.1-p to 0.3.1-v.  But I'm running it on a Windows Server 2019 box and also used the Windows Installer v1.6 tool.  No issues on this end.

**Comment by wh1te909** [comment]
on ubuntu 18.04

**Comment by jneuff** [comment]
I get the same error on Debian Stretch and Node.js 7, 8, 10.

**Comment by Ylianst** [comment]
Working on it now!!!

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.1-w with a fix for this. Let me know if it works.

**Comment by wh1te909** [comment]
Awesome! Working for me

**Comment by dagors** [comment]
I have the same problem

Update to the latest version with sudo npm install meshcentral, apparently work but I can not access through the browser.
● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-04-05 11:08:42 CST; 2min 20s ago
 Main PID: 808 (node)
    Tasks: 23 (limit: 2304)
   CGroup: /system.slice/meshcentral.service
           ├─ 808 /usr/bin/node /home/dagors/node_modules/meshcentral
           ├─1009 /bin/sh -c /usr/bin/node /home/dagors/node_modules/meshcentral --launch
           └─1012 /usr/bin/node /home/dagors/node_modules/meshcentral --launch

abr 05 11:08:42 vps204243 systemd[1]: Started MeshCentral Server.
abr 05 11:08:50 vps204243 node[808]: MeshCentral HTTP redirection server running on port 1024.
abr 05 11:08:50 vps204243 node[808]: ERROR: Redirection web server must be active on port 80 for Let's Encrypt to work.
abr 05 11:08:50 vps204243 node[808]: MeshCentral v0.3.1-w, WAN mode.
abr 05 11:08:51 vps204243 node[808]: MeshCentral Intel(R) AMT server running on dominio.com:4433.
abr 05 11:08:51 vps204243 node[808]: Server _customer1 has no users, next new account will be site administrator.
abr 05 11:08:51 vps204243 node[808]: Server info has no users, next new account will be site administrator.
abr 05 11:08:51 vps204243 node[808]: MeshCentral HTTPS server running on dominio.com:1025.

**Comment by Ylianst** [comment]
You got a different issue. Your are running MeshCentral as a user that does not have permissions to use ports below 1024. So, as you see above, HTTP is on port 1024 and HTTPS on port 1025. There is a line in the installation guide to give node permission to use port 80 and 443 that you will need run.

**Comment by dagors** [comment]
You're right that solved the problem.

> sudo setcap cap_net_bind_service=+ep /usr/bin/node

Thank you

**Comment by Ylianst** [comment]
Ok, closing this issue since I am pretty sure it's solved. Please re-open if needed.
