### ISSUE TITLE
Question:  What is the effect of setting ignoreagenthashcheck to true?

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#1662]
# Use Case:
In our case, some of our customers in very high security networks are replacing our cert with theirs, presumably to be able to see inside the TLS traffic to verify/process it's payload with their chosen security software. In our case, we have to modify the `meshinstall.sh` file to add `--no-check-certificate` to allow the download to complete for the binary and configuration .msh files, however, upon doing this, the agent is still not able to connect.

Anecdotally I have worked at very large vendors who replace the cert (A kind of ethical MITM attack, where, in these companies there is no expectation of privacy), so it's not something specific to this customer, or (IMO) unheard of.

# Troubleshooting
We have dissected the `meshinstall.sh` script to be able to troubleshoot this a bit further:

When they try and download the binary file `/usr/local/mesh/meshagent` (same thing happens for the .msh config file) they get the following output:
```shell
# wget https://ourcompany.com/subdomain1/meshagents?id=6 --output-document /usr/local/mesh/meshagent
--2020-07-28 08:15:52--  https://ourcompany.com/subdomain1/meshagents?id=6
Resolving ourcompany.com (ourcompany.com)... [REDACTED_IP]
Connecting to ourcompany.com (ourcompany.com)|[REDACTED_IP]|:443... connected.
ERROR: cannot verify ourcompany.com's certificate, issued by ‘CN=[REDACTED_CN],OU=[REDACTED_OU],O=[REDACTED_O],C=US’:
  Unable to locally verify the issuer's authority.
To connect to ourcompany.com insecurely, use `--no-check-certificate'.
```

When they use `--no-check-certificate` the binary and config .msh files download as expected:
```shell
# wget https://ourcompany.com/subdomain1/meshagents?id=6 --output-document /usr/local/mesh/meshagent --no-check-certificate
--2020-07-28 08:16:03--  https://ourcompany.com/subdomain1/meshagents?id=6
Resolving ourcompany.com (ourcompany.com)... [REDACTED_IP]
Connecting to ourcompany.com (ourcompany.com)|[REDACTED_IP]|:443... connected.
WARNING: cannot verify ourcompany.com's certificate, issued by ‘CN=[REDACTED_CN],OU=[REDACTED_OU],O=[REDACTED_O],C=US’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 3534800 (3.4M) [application/octet-stream]
Saving to: ‘/usr/local/mesh/meshagent’

/usr/local/mesh/meshagent                 100%[===================================================================================>]   3.37M  3.01MB/s    in 1.1s    

2020-07-28 08:16:05 (3.01 MB/s) - ‘/usr/local/mesh/meshagent’ saved [3534800/3534800]
```

Now the agent is downloaded, and appears to start as expected, but, does not connect to the server, and we get the `Agent bad web cert hash` and `Agent bad web cert hash` in the logs as demonstrated here:

```shell
Jul 28 14:58:09 [REDACTED_HOSTNAME] node[5782]: Agent bad web cert hash (Agent:[REDACTED_SHORTHASH1] != Server:[REDACTED_SHORTHASH2] or [REDACTED_SHORTHASH3]), holding connection ([REDACTED_IP]:47390).
Jul 28 14:58:09 [REDACTED_HOSTNAME] node[5782]: Agent bad web cert hash:[REDACTED_LONGHASH].
```

In our case, to work around the problem, we have added `"ignoreagenthashcheck": true` in the `settings` section  of the file `/opt/meshcentral/meshcentral-data/config.json` and the agent is now able to connect, but before setting this, I want to be sure I understand the full risks, and ideally, ensure there are no MITM attacks for all customers, including this one.

# Ask
1) What is the goal of setting `"ignoreagenthashcheck"` to `true`?

In report https://github.com/Ylianst/MeshCentral/issues/146 you state:
> in the settings section of config.json. Of course, the is super bad because someone can man-in-the-middle the agent connection.

In report https://github.com/Ylianst/MeshCentral/issues/1221 you state: 
> The ServerID is the hash of the agentserver-cert-public.crt certificate that is located in meshcentral-data. So when the agent connects, it will see the certificate of the reverse proxy, then continue to connect to MeshCentral and ask MeshCentral for a proof that it's the right server. MeshCentral will use the agentserver-cert-public.crt to validate itself and will also tell the agent what TLS certificate it should have seen.

I want to ensure that I grok setting `ignoreagenthashcheck` to `true` before I do so. As I understand it, it prevents a man in the middle attack, which is to guarantee the encrypted traffic between the agent and the server, **or** are there other benefits or implications to setting this? For example to somehow protect the agent itself from connecting to an untrusted (hijacked DNS?) MeshCentral server? 

If the goal is to only guarantee the security of the connection between the agent and the server, then this all makes sense, but if the goal is to guarantee that the agent will only connect to the original server (or something else?), then I'm confused because if the bad actor can add `"ignoreagenthashcheck": true` on the malicious server, and it will allow the connection

I've drawn what I understand is happening when the agent gets installed, as well as when it connects, which is specific to the configuration .msh file, I'm not sure if this helps articulate my question:
![MeshAgent IgnoreAgentHashCheck](https://user-images.githubusercontent.com/26114097/88717718-f1751f00-d0ee-11ea-89aa-2c0765d074d8.jpg)

2) Just to be clear, setting `ignoreagenthashcheck` to `true` does NOT make the connection insecure (To draw a bad parallel, downgrade HTTPS to HTTP), just makes it able to be observed, correct?

3) In report https://github.com/Ylianst/MeshCentral/issues/1536 you state:
> One thing I am adding is that you can now add the following line in the domain section:
> "ignoreagenthashcheck":true

Do you have any idea approximately what version this will be implemented? As a work around, we would feel more comfortable using this to reduce the attack surface while we test a solution.

4) Ideally we want to have as secure a connection as possible, in our use case, if we set the `CertUrl` to be the same TLS cert as what the customer is replacing ours with, will that work? Right now the `CertURL` is pointed to ourcompany.com's cert, which is being replaced by the customer, assuming that they are replacing our cert, with a cert that's also publicly available at something like www.clientcompany.com. 

5) Assuming the answer to 4 is yes, and assuming that they do not have this cert pubically available, can this location refer to a local file as well?

I may be overthinking this...

**As always, thanks for all your hard work!**

**Comment by Ylianst** [comment]
Well, first, I want to repeat myself and say that your issue report are by far the most researched I have even seen. Always a pleasure to help. Before I got into the details, the [MeshCentral Design and Architecture Guide](MeshCentral2DesignArchitecture) section 8 goes into how the agent and server authenticate with each other. Basically, the agent connect and sees the TLS certificate. It then does a special signing exchange with the server. As part of the second exchange the server will indicate to the agent when TLS certificate that agent should have seen.

![image](https://user-images.githubusercontent.com/1319013/88755800-c7375780-d116-11ea-8850-c6575d38abe7.png)

So, if you happen to be running a reverse proxy in from the MeshCentral, you need MeshCentral to know what certificate the agent will see so that the authenticate can be fully secure.

One more thing, as we are moving towards TLS 1.3, prefect forward secrecy is increasingly being used and so, you can no longer decrypt traffic by having the TLS certificate private key anymore. The alternative is really to have the reverse proxy also perform all of the audit you need. It's also perfectly normal for your reverse proxy to be a security check on MeshCentral and to block/disconnect any traffic that does not look right.

Anyway, on to the questions:

#1 What is the goal of setting "ignoreagenthashcheck" to true?

- When set to true, the server will ignore secondary check performed by the agent and always assume it's ok. This means that the agent could connect to a bad TLS server (say Eve's server that is acting as a man-in-the-middle), the agent will see Eve's certificate. Eve's forward's the connection to the real MeshCentral server that will notice that the agent is talking to Eve but will accept the connection anyway. So, ignoreagenthashcheck is not a good thing.

#2 Just to be clear, setting ignoreagenthashcheck to true does NOT make the connection insecure (To draw a bad parallel, downgrade HTTPS to HTTP), just makes it able to be observed, correct?

- Right, the connection is still TLS encrypted. However, it removes the TLS server authentication check so, the agent could be doing a TLS to an invalid server that is then forwarding the traffic. It's still TLS but encryption is not sufficient, you want to authenticate the end-points, but this authentication will no longer be made.

#3 Do you have any idea approximately what version this will be implemented?

- It's implemented now and has been for over a year.

#4 Ideally we want to have as secure a connection as possible, in our use case, if we set the CertUrl to be the same TLS cert as what the customer is replacing ours with, will that work? Right now the CertURL is pointed to ourcompany.com's cert, which is being replaced by the customer, assuming that they are replacing our cert, with a cert that's also publicly available at something like www.clientcompany.com.

- This is the best and most secure option. If agents are going to see a customer certificate when connecting, then have MeshCentral make sure that agents are only allowed to connect if they see the customer cert and no other. This is certainly the right path. CertURL will load the customer cert and the secondary check will be enforced correctly.

#5 Assuming the answer to 4 is yes, and assuming that they do not have this cert publicly available, can this location refer to a local file as well?

- Well, since the answer to #4 is yes... You could setup a dummy HTTPS server with the customer cert, but I implemented a trick, if the "CertUrl" starts with "file://" then the certificate will be loaded from a file. Note that you only need to public part of the certificate. One thing to note about this, if the customer changes it's certificate, MeshCentral right now will notice that agents are reporting seeing a different certificate and MeshCentral will re-pull the "CertURL" to see if an update occurs. This is nice because if you customer changed it's certificate, MeshCentral will also update automatically. This will happen in a split second and no service interruption will occur. If you go with "file://", you will need to manually update the file when the customer updates their certificate.

Ok, I dropped many details. I hope it all makes sense.

**Comment by darryl-h** [comment]
> Well, first, I want to repeat myself and say that your issue report are by far the most researched I have even seen. Always a pleasure to help.

Thank you! In a previous life one of my functions was to file PRs. I'm glad those skills have not gotten too rusty :) likewise, thank you and your team for the quality and responsiveness, this was a large part of my recommendation to use this software in our organization.

> Before I got into the details, the MeshCentral Design and Architecture Guide section 8 goes into how the agent and server authenticate with each other. Basically, the agent connect and sees the TLS certificate. It then does a special signing exchange with the server. As part of the second exchange the server will indicate to the agent when TLS certificate that agent should have seen.

Thank you! I was looking for this image while working through this issue, but wasn't able to find it in the install guide

> So, if you happen to be running a reverse proxy in from the MeshCentral, you need MeshCentral to know what certificate the agent will see so that the authenticate can be fully secure.

We have run into this challenge before, where our .crt file expired and then all our agents were unable to connect. In our case, the TLS cert was available on the internet, and thus, we were able to use these commands to update it:

```shell
# echo -n \| openssl s_client -connect yourdomain.com:443 2> /dev/null\| sed -ne '/-BEGIN   CERTIFICATE-/,/-END CERTIFICATE-/p' > /opt/meshcentral/meshcentral-data/webserver-cert-public.crt   
# service meshcentral restart
```
> One more thing, as we are moving towards TLS 1.3, prefect forward secrecy is increasingly being used and so, you can no longer decrypt traffic by having the TLS certificate private key anymore. The alternative is really to have the reverse proxy also perform all of the audit you need. It's also perfectly normal for your reverse proxy to be a security check on MeshCentral and to block/disconnect any traffic that does not look right.

I'll be honest, I don't fully grok this, but will try to get a better handle on this in the future. Thank you for this heads up!

> When set to true, the server will ignore secondary check performed by the agent and always assume it's ok. This means that the agent could connect to a bad TLS server (say Eve's server that is acting as a man-in-the-middle), the agent will see Eve's certificate. Eve's forward's the connection to the real MeshCentral server that will notice that the agent is talking to Eve but will accept the connection anyway. So, ignoreagenthashcheck is not a good thing.

Understood, thank you!

> Right, the connection is still TLS encrypted. However, it removes the TLS server authentication check so, the agent could be doing a TLS to an invalid server that is then forwarding the traffic. It's still TLS but encryption is not sufficient, you want to authenticate the end-points, but this authentication will no longer be made.

Understood, thank you!

> It's implemented now and has been for over a year.

Awesome! We are currently in the process of upgrading from 0.4.3-w to version 0.5.75 in production.

> This is the best and most secure option. If agents are going to see a customer certificate when connecting, then have MeshCentral make sure that agents are only allowed to connect if they see the customer cert and no other. This is certainly the right path. CertURL will load the customer cert and the secondary check will be enforced correctly.

Understood, thank you!

> Well, since the answer to (4) is yes... You could setup a dummy HTTPS server with the customer cert, but I implemented a trick, if the "CertUrl" starts with "file://" then the certificate will be loaded from a file. Note that you only need to public part of the certificate. One thing to note about this, if the customer changes it's certificate, MeshCentral right now will notice that agents are reporting seeing a different certificate and MeshCentral will re-pull the "CertURL" to see if an update occured. This is nice because if your customer changed it's certificate, MeshCentral will also update automatically. This will happen in a split second without service interruption. If you go with "file://", you will need to manually update the file when the customer updates their certificate.

Understood, thank you!

> Ok, I got into many details. I hope it all makes sense.

Awesome! Thank you so much for your quality and timely responses!

**Comment by Ylianst** [comment]
Glad I could help.

I see what you are doing with the openssl command, but if you can use `certurl` instead, the process it fully automatic.

If you need any help with TLS Perfect Forward Secrecy, let me know. For the purpose of this discussion, when Perfect Forward Secrecy is enabled in a TLS session, the encryption key used for the TLS session can't be recovered by just having the private key of the server certificate.

**Comment by pleirb** [comment]
@Ylianst First of all, thank you very much for this fantastic tool. I think my case is related, I have activated the "IgnoreAgentHashCheck": true option in my config.json and I get a warning in the general panel of my meshcentral server saying that the agent hash check has been skipped and that this may be insecure. 
Currently my certificate is correct but it is managed by Traefik, could it be that this is the reason why meshcentral cannot control the authenticity of the certificate?
Thank you so much !
