### ISSUE TITLE
Adding new agent not showing

### ISSUE THREAD

**Issue by pczolee** [Ylianst/MeshCentral#1663]
Hello.

This problem I have a relative long time ago. If I add a new agent it is not showing on the list. I have to restart the server and than it is ok.
The system is Ubuntu 12.04.5 LTS x64, node-v10.22.0-linux-x64, mesh 0.5.96

How can I help to debug and fix the issue.

Thanks

**Comment by krayon007** [comment]
What version of the mesh server are you using? Are you using local mode? I know there was a bug that was fixed in the server a little bit ago where the multicast responder wasn't working correctly, so the agent couldn't discover the server unless the server sent the discovery packet.

@Ylianst can chime in with what versions this was an issue...

**Comment by krayon007** [comment]
Sorry, I just noticed you posted the server version...

**Comment by si458** [comment]
closing as stale
