### ISSUE TITLE
Feature Request/Question: Shared Clipboard

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1692]
The manual set/get clipboard feature seems to be working very well so far but can be a little user-unfriendly at times. Are there any plans to implement a more transparent "shared" clipboard mode? Is this even feasible through a browser or would the method to poll and replace the clipboard need to be repeated so frequently for this to work that it just wouldn't be efficient?

**Comment by Ylianst** [comment]
It's not possible to do this thru the browser as having a web application grab the clipboard automatically would be a security issue. This said, I am going to leave this one open since I had some related work I wanted to do.

**Comment by PetieM** [comment]
Makes sense. I had a feeling there was something preventing this from happening transparently. Thanks for the clarification regardless.

**Comment by southeasterntech** [comment]
+1

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.6. The new MeshCentral Router has a built-in remote desktop viewer. It's not great yet, plenty of things are not right, but since this viewer is not web based, there are more options for clipboard sync, etc.

![MC2-RemoteDesktopInRouter](https://user-images.githubusercontent.com/1319013/90067642-3fb81f80-dca4-11ea-9d11-3e379aa31b24.png)

**Comment by vitko-bg** [comment]
Have tried it - looks a great option, but still no clipboard transfer between client and my PC - both directions .....

**Comment by whalehub** [comment]
> It's not possible to do this thru the browser as having a web application grab the clipboard automatically would be a security issue. This said, I am going to leave this one open since I had some related work I wanted to do.

@Ylianst I have to offer a correction here. It is possible and has been for some time. This is the browser API that makes it possible, which is supported by virtually all modern browsers: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

An example of an open-source web application which uses this API for real-time two-way clipboard synchronization is Neko: https://github.com/nurdism/neko

I recorded a little clip to show what it looks like in action: https://xbb.datahoarder.dev/VUSu3/cEnAXEri49.webm

**Comment by Ylianst** [comment]
Oh my!!! I have to check this out. Thank you for the information.

**Comment by whalehub** [comment]
@Ylianst You're welcome. 👍

**Comment by vitko-bg** [comment]
Hi @Ylianst , when you say ` the multi-display selector on the MeshCentral Router Desktop Viewer should work now, it's been fixed in a later version.` what did you meant? 
Just tried it now with the latest MC version 0.6.13, redownloaded MC Router - and it is still the same - no clipboard is captured both directions ......
BTW - shall I open another enhancement issue in regards to Split Screen view? Thanks.

**Comment by Ylianst** [comment]
@vitko-bg I don't understand your comment. There is no clipboard sync yet in MeshCentral Router, this is normal, I did not build that yet. Does the multi-display selector work?

**Comment by vitko-bg** [comment]
Sorry @Ylianst  - I thought it is releasead :) because in your comment about viewer you mentioned `there are more options for clipboard sync, etc.` Did not know that it is not implemented yet.
In regards to multi-display - yes, it is working fine, but only when MC Router is started as administrator. Possibly it is related to file location, in my case it is in Program Files/ Mesh Agent
When MC Router is started as normal user(let's say from MC webUI-> Lauch Router) - cannot connect to any of the devices ....
![image](https://user-images.githubusercontent.com/59362521/90660391-c12c2680-e23d-11ea-8aa4-4ed4df918ff4.png)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.14 with new quick clipboard buttons. I will need to look at more automation, but for now, buttons a good improvement.

![MC2-Clipboard](https://user-images.githubusercontent.com/1319013/90700489-d784b300-e23a-11ea-8d1f-be1febf60482.png)

**Comment by PetieM** [comment]
Working great so far, thank you! This way is significantly more efficient than the older clipboard button (which now seems a bit redundant).

Also, double thanks for including this for Mac hosts as well - I just tested and it's working well with them too!
