### ISSUE TITLE
Run mesagent.exe WITHOUT admin permissions

### ISSUE THREAD

**Issue by Artamerh** [Ylianst/MeshCentral#17]
Hi @Ylianst, 
thank you for your software, it's great.
I was wondering if there would be possibilities to run an agent on remote PC without admin permissions?

Thank you.

**Comment by Ylianst** [comment]
That is a good idea. You can do "meshagent.exe run", this will run the agent in console mode and you don't need admin. Obviously you can't remote desktop the login screen, etc. There is a button on the agent to run it temporary (without install), but it still requires admin rights, that is something I should fix.

**Comment by techno-express** [comment]
What am noticing in the recent https://github.com/Ylianst/MeshCentral/commit/251168b554eb7ca13650dbb2685bcf35c82377e7 commit, is that the created binary needs right click to run as admin to work, otherwise gives run error. 
The binary was created without elevated privileges. And where is the source to the new meshagent changes? It seems https://github.com/Ylianst/MeshAgent not updated nor here.

**Comment by Ylianst** [comment]
The meshagent always did the admin check and did not request elevation. However, I am going to change that right now. It's especially important is you want to give temporary access without administrator rights.

I will update the MeshAgent right now...

**Comment by Ylianst** [comment]
Just updated: https://github.com/Ylianst/MeshAgent

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.0-e on NPM with improved MeshAgent installation privilege escalation. You no longer need to right click the agent and hit "Run as administrator...".

**Comment by Artamerh** [comment]
Hi @Ylianst , works just awesome.
Thank you for hand, it's now very useful for my cases.

**Comment by Ylianst** [comment]
Thanks!
