### ISSUE TITLE
Keyboard mapping if not QWERTY

### ISSUE THREAD

**Issue by Tomatoschewps** [Ylianst/MeshCentral#1701]
Hi,

I've finally find time to test in multiple condition our keyboard issues with MeshCentral agent when using desktop sharing.

We are using AZERTY keyboard disposition so are our users and when we connect to there desktop with MeshCental we have some strokes who doesn't work and some others who are inverted.
For example :
- ^ ¨ ù % : / ! § ° ) ] < > produce nothing
- $ or £ send SHIFT
- \* send F3
- ; or . send respectively $ and £

If we configure the agent in QWERTY and our computer stay in AZERTY it's the same
If we configure the agent in AZERTY and our computer in QWERTY it's the same.

If we configure the agent in QWERTY and our computer in QWERTY all is fine.

Does someone else have the issue ?
D.

**Comment by Bamoka** [comment]
I've been using MC in production since February 2019 and we have it deployed on roughly 300 client PCs in France.
I would like to add some information for debugging purposes:
- special characters not working from Firefox (Windows)
- Chrome on Windows working as expected, but Chrome or Firefox on Linux (OpenSUSE 15.2 x64, Gnome3) make it impossible to type special characters even if using AZERTY on both sides

Possible solution would be to add a user defined "keyboard mapping" option which could be set to a default "automatic" setting but also allow the user to choose his/her setting (eg: Automatic, FR-FR, FR-CA, EN-GB, EN-US, DE-DE, etc...).
Correct me if I'm wrong, but I think MC tries to guess the keyboard mapping based on what the web browser tells it.
This can be a problem when the user chooses to use Firefox (EN-GB) on Windows (EN-GB) with a french AZERTY keyboard.

In any case, big thanks to the devs as MC has been invaluable to our team and clients during the COVID-19 pandemic.

**Comment by master-itermar** [comment]
HI !
I have the same issue.
I have an ita keyboard qwerty.
When try to use @ symbol returned is dot (.).
So i try other keyboard char to test, and all char near alphabetic char are strange, return every time dor or other.
Try testing with standard Logitech.
Thanks

**Comment by laboiteajb** [comment]
Hello,

I have the same concern at home.

AZERTY keyboard on Linux

0.6.53

Thank you

**Comment by Tomatoschewps** [comment]
Hi @Ylianst ,

It's becoming really hard to work with meshcentral because of this ...
To type password, url, ...

Can you please look at it ?

Thanks
D.

**Comment by krayon007** [comment]
I have a working prototype where I resolved these keyboard issues. I'm creating a new agent command for the server to use, becuase I don't want to accidentally break multi-key sequences, because of the underlying windows syscall I'm using is slightly different. We're thinking of having the UI have a selectable option for keyboard layout, which the agent will use to translate the virtual keycodes.  We trying to see if we can have the browse report what the keyboard layout is on the browser side, so that we can make it more seamless. So far I tested with fr-be, and verified the translation works when I specify the layout in my syscall to inject the keypress... Just a few browser side kinks to work out... But it should be relatively soon... (So far it will be windows only, as I haven't looked at keyboard layouts for xorg yet.)

**Comment by Bamoka** [comment]
This is great news krayon007. Thank you for the effort you put into this issue. I'd be happy to help you beta test if need be.

Our installed OS ranges from Windows server 2003 (non production) to 2019. And clients from Win7 SP1 to Win10 v2004. Some QWERTY (EN-US) and most AZERTY (FR-FR).

**Comment by Tomatoschewps** [comment]
Hi @krayon007 
Really great news !
As Bamoka, we can beta test it if you need 👍 

We have mainly w10 and w2012r2 to 2019 and we use exclusively fr-fr on both sides.

**Comment by Ylianst** [comment]
MeshCentral v0.6.93 was published with correct keyboard handling on Windows. Bryan is working on doing the same for other platforms (Linux, macOS, FreeBSD). Let us know if it works.

![MC-MultiKeyboards](https://user-images.githubusercontent.com/1319013/99596139-a6875c00-29aa-11eb-9433-f6013469ca53.png)

**Comment by Bamoka** [comment]
This is brilliant! We even have a shiny new diagram to show our technicians.

I'll update the server tomorrow and run a few tests. Merci beaucoup!

**Comment by krayon007** [comment]
We just published v0.6.95. This version supports international keyboards on all the remaining platforms, macOS, Linux, and FreeBSD.

**Comment by Ylianst** [comment]
Exactly! Now all platforms.

![MC2-MultiKeyboard2](https://user-images.githubusercontent.com/1319013/99629390-c5a6dd80-29ec-11eb-99a3-39eba604c534.png)

**Comment by Tomatoschewps** [comment]
That's ... Amazing !!
My collegues are pleased 👍 

I'm the owner of this issue so i'm going to close it. Feel free to add comments if you need ^^
