### ISSUE TITLE
Mouse pointer is flickering .......

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1705]
There are three ( possibly more ) issues in regards to this problem, and all of them are closed (#1400 , #968 , #357 357) but mouse flickering problem is still there .......

MC version 0.6.5 running on Debian behind reverse proxy on Nginx
Agent OS: Windows 10 Pro x64
Agbent version: Latest with MC version
Mouse pointer on client PC is still flickering when operator is connected ........

Is that proxy problem, Server OS problem or agent problem? How I can help in regards to resolving this issue?

**Comment by krayon007** [comment]
This is an issue with how the screen image is captured, using GDI. There doesn't appear to be much I can do with this approach. But I did find some samples for a new way to do this, using new APIs, that were introduced in Windows 8 and Windows Server 2012 R2.. This approach may resolve this issue, but will take quite a bit of time to implement, because it would require a complete rewrite of the Remote Desktop functionality. I'm looking into it, but it may be a while before I have something working.

**Comment by si458** [comment]
DUPLICATE #1705
