### ISSUE TITLE
Nested Computer Groups - Enhancement

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#1708]
Perhaps a customer has serveral locations, it would be nice to add groups inside of groups to indicate something like this:
 - Customer
   - Location
     - Servers
     - Workstations
   - Location 2
etc...

**Comment by Ylianst** [comment]
So, I am not going to have a device be within many different device groups because I want an easy way to apply device policies. It gets complicates if you have to deal with a device policy in a tree. This said, I just added a feature so if you add a tag to a device with a pipe in it, it will show with an arrow on the UI.

For example, if I add "org|abc" tag to a few devices and sort by tags, I get this below. It will be in MeshCentral v0.6.7 when it's next published. I can then work on more UI improvements in the future around nested tags.

![image](https://user-images.githubusercontent.com/1319013/90280608-0c9a9b00-de20-11ea-8958-aecde5e74319.png)

**Comment by Ylianst** [comment]
MeshCentral v0.6.8 just published, let me know what you think.

**Comment by frankmcc** [comment]
This works.
