### ISSUE TITLE
Can't stop ping...

### ISSUE THREAD

**Issue by CCWTech** [Ylianst/MeshCentral#1719]
If I use the MC terminal and ping another device with the -t option, there is no way to stop pinging.

CTRL-C doesn't stop it, and even disconnecting and reconnecting stops it from pinging.

Any way to get it to stop pinging?!?

(Other than a reboot of the device that's pinging the other host)?

**Comment by krayon007** [comment]
You must be connecting to a windows machine that doesn't support ConPTY?

If so that is because those versions of windows don't have a real console interface. The windows console object does not pass certain signals to the child. This is a windows issue, and is the reason I switched to using ConPTY when i detect support

**Comment by CCWTech** [comment]
Yes, It's a Windows box. So no way to stop it?

**Comment by jsastriawan** [comment]
Can you kill the ping process remotely using built-in task manager of Desktop?

**Comment by CCWTech** [comment]
@jsastriawan That did it, thank you!!!

**Comment by Ylianst** [comment]
What version of Windows where you using? As Bryan stated, I you must have been using an older version?

**Comment by CCWTech** [comment]
Windows Server 2016 STD

**Comment by Ylianst** [comment]
Yep. Sadly, on older Windows version there terminal is not great and causes a bunch of issues. This is no longer a problem on later versions of Windows. I will close this because there is nothing we can do on older version except process kill workaround.
