### ISSUE TITLE
Ability to do server IP filtering through reverse proxy rather than config file?

### ISSUE THREAD

**Issue by RandomGHUser** [Ylianst/MeshCentral#1731]
I'm using haproxy in front of meshcentral - I know that I can do a "userallowedip" per the Server IP filtering section (12) in the manual, but I would rather all web-traffic acls be handled by my reverse proxy.    I know that the agent should connect via /agent.ashx, so I tried setting connection acls through haproxy like so:

```
  frontend http-in
       bind *:443 ssl crt /usr/local/etc/haproxy/certs 
       bind *:80
       acl allow_clients path_beg /agent.ashx
       http-request allow if allow_clients
       acl network_allowed src [MY NETWORK IP ADDRESSES] 
       acl restricted_page path_beg /
       http-request deny if restricted_page !network_allowed
       http-request redirect scheme https unless { ssl_fc }
       option forwardfor
       redirect scheme https if !{ ssl_fc }
       #hosts
       acl meshcentral hdr(host) -i meshcentral.[MYDOMAIN]
       acl meshcentral hdr(host) -i meshcentral.[MYDOMAIN]:443
       #routing
       use_backend meshcentral_nodes if meshcentral
       use_backend meshcentral_nodes if allow_clients
```

With the above, this will successfully lock down any / urls to the network_allowed, AND will let me connect the clients from anywhere to /agent.ashx (so meshcentral will show them as connected and responding), BUT actual activities (connecting to the desktop / files, etc.) does not work.  

Are there alternate URLs to open up for the agent that can be supported in a reverse-proxy configuration to control ACLs there?  Or am I required to have these configured in meshcentral per Server IP filtering?

**Comment by Ylianst** [comment]
In addition to `/agent.ashx`, also unblock `/meshrelay.ashx` and you should have remote desktop/files/terminal work.

In the future to debug this, you can go in "My Server" / "Trace" tab and enable "Web Requests". You will see all HTTP requests in real time and see what you need to unblock.

Also note that, for example, the chat feature will not work with your block because a browser will open on the remote machines and try to access the chat webpage, same for agent invitations, etc. So, depending on the features you use, you may need to unblock a few more things.

Hope that helps,
Ylian

**Comment by RandomGHUser** [comment]
Fantastic, thank you for the information!
