### ISSUE TITLE
Enable remote system TCP/IP Isolation 

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1733]
Hi Ylianst and team,

Can we get a way that systems running the agent can stay connected, however the outbound traffic can be blocked if an option is chosen to do so. Reason I am asking about this is based off of applications that would call home after running. (Benchmarks, Games, Applications), however having connection to the agent/router for access to do those items into the machine and gain access during trail runs would be excellent...

Thanks,
SomeGuru

**Comment by krayon007** [comment]
How hardened would the solution need to be? Thinking outloud, there are a couple ways to do this...

1. We could remove the default route from the routing table, and add a route for the mesh server.... 
2. If running on windows, we could add a default rule on the Windows firewall to block outbound traffic that isn't for the server. I'm sure linux has an equivalent.
3. If you are running vPro, I think AMT has a similar function to do the same think underneath the OS, so that you can't undo it, unless you have AMT access.

**Comment by Ylianst** [comment]
This seems a bit unrelated to MeshCentral. There are different ways to setup outbound traffic filters. You would need to find such a solution and specifically allow MeshAgent/MeshCentral communication, but not anything else. This should be simple since you know the IP of your server. I think the Windows firewall has outbound rules.

**Comment by SomeGuru** [comment]
I agree this might seem out of scope of MeshCentral, however if it was a feature that could be utilized this would help during a potential threat vector because the MeshAgent would already be present and could force the ruleset... Additionally it has the enhanced feature to block during testing of systems when Administrators don't want specific machines getting outside the localized network, but still need the remote administration aspect of it...

Thinking out loud here also, If you isolate a lab within a lab (enclave) then you can protect all systems externally while investigation of the system be it test running scripts, channeling malware exploits, or similar activities.

The problem, is that the users don't know they are on the external network segment and they would expose the bad code to the outside world. Where if MeshCentral could handle the changes then its a click of a button, or maybe even later an automated script that invokes to prevent the action from getting outside the "virtual 4 walls".

Thanks,
SomeGuru
