### ISSUE TITLE
No plan for WinXP support?

### ISSUE THREAD

**Issue by billymoox** [Ylianst/MeshCentral#175]
_Originally posted by @Ylianst in https://github.com/Ylianst/MeshCentral/issues/18#issuecomment-443399723_

I understand from your previous thread that you're not planning to support Win XP. I wish you'll reconsider because I've lots of 2003 servers still in production and I beliieve many more are still in production around the world. VNC is the only reasonable alternative available nowaday for these servers. Maybe a scaled down agents with limited functionalities?

Regards
Billy

**Comment by whalehub** [comment]
Why bother spending time on implementing support for an OS that isn't even supported my Microsoft anymore? If you're still running Windows XP/Server 2003, it's time to upgrade to something modern...

**Comment by krayon007** [comment]
We have no plans to support Windows XP, not because of resourcing or anything like that. We don't have plans on supporting Windows XP, because of technical limitations.  For example, on Windows XP when you create a socket descriptor, it is not possible to flag the descriptor as not inheritable. That was not introduced until a later version of Windows. That means if you do something that spawns a child process, like a terminal, a remote desktop, or any other myriad of tasks that result in spawning a process, that descriptor will be inherited even when you don't intend to, and will most likely result in a resource leak and/or resource locking issues.

Trying to work around this issue is extremely difficult, and not always possible. Not only will you run into race conditions if you try to close leaked handles, but you won't even always have access to said handles, because it could have been spawned by something completely orthogonal, like a script, etc. These scripts may know absolutely nothing about each other, etc. The correct solution, is to flag the descriptor as not-inheritable, but that capability was introduced in a later version of Windows.

**Comment by Ylianst** [comment]
Going to close this one since I don't see this happening from a technical point of view. In case anyone asks, WinCE, iOS is also out. Android is technically possible but no one on the team is an Android expert so not likely anytime soon unless someone wants to step up and do it. FreeBSD is on the todo list, but still a ways away.
