### ISSUE TITLE
Agent is getting disconnect after some time even though the agent machine is in local

### ISSUE THREAD

**Issue by radha402** [Ylianst/MeshCentral#1755]
The agent is getting disconnect after some time even though the agent machine is in local

Initially, it started with a black screen while connecting to agent form server with desktop option and after some time the agent went offline

**Comment by drnikcuk** [comment]
I see similar behaviour with a WIndows 7 Client i have ... service is running fine, but unable to connect after a while.

**Comment by steuck13** [comment]
Greetings, 

@radha402  on which operating system is your agent running?
Also, which server version are you running?

@drnikcuk is this happening only on this single W7 client?

thx

**Comment by drnikcuk** [comment]
@Ylianst yup - just this one ... and sadly i dont have any other W7 clients to compare with.

**Comment by krayon007** [comment]
What version of windows 7 are you running? SP1, SP2, etc... 32 or 64 bit...

**Comment by drnikcuk** [comment]
OS: Windows 7 Professional [7601].
Modules: amt-lme, amt-manage, amt-mei, amt-scanner, amt-wsman-duk, amt-wsman, amt-xml, amt, apfclient, monitor-border, smbios, sysinfo, wifi-scanner-windows, wifi-scanner, win-console, win-info, win-terminal, win-virtual-terminal. Server Connection: true, State: 1. lastMeInfo: null.

{
  "openssl": "1.1.1g",
  "duktape": "v2.3.0",
  "meshAgent": "2020-08-12T19:33:58.000Z"
}

**Comment by radha402** [comment]
I'm using windows 10 Pro agent is getting disconnect after some time and again if I reinstall the agent then it is working fine for some time. this issue is repetitive for only one system and I'm using 20 systems with the same os and hardware configuration those are working fine

**Comment by krayon007** [comment]
So you are saying the one system is on the same local network as the other systems?

**Comment by krayon007** [comment]
I'm specifically asking about the network topology of your systems...

**Comment by drnikcuk** [comment]
For me the client I have the issue with is remote, so connecting over the internet.

**Comment by krayon007** [comment]
Do you have a reverse proxy between the internet and your server? If so, which reverse proxy do you use?

**Comment by drnikcuk** [comment]
> Do you have a reverse proxy between the internet and your server? If so, which reverse proxy do you use?

In my instance, there is no proxy.

**Comment by krayon007** [comment]
Is there a NAT router between the client and the internet? For example, by default, DDWRT has a 5 minute timeout for TCP port mappings. Also by default, the idle timeout keep alive on the agent is 2 minutes... If the TCP Port Mapping timeout is set for less than 2 minutes, the agent control channel will get force closed by the NAT router.

**Comment by radha402** [comment]
No, there is only one router which connected to all 20 system, and as I said earlier every system is on the same network and the server is also on the same network and connected to the same router of all 20 systems.

**Comment by krayon007** [comment]
Sorry, I just realized there are two different people describing this problem in this thread..

**Comment by radha402** [comment]
yes, even now also that all the 20 systems and 1 server is on the same network and connect to the same router. 

I have installed the agent on every system and from 20 systems only one system agent is going online after some time of installing/re-installing.

**Comment by radha402** [comment]
*sorry not online its offline only one system is going offline after some time of installing/re-installing.

**Comment by krayon007** [comment]
Does is appear the system is consistently disappearing after a specific time period, or does it appear random? The system isn't going to sleep is it?

Instead of reinstalling the agent, does it come back if you simply restart the agent service?

You can restart either with the service manager, or by executing the following commands from an elevated cmd prompt:

wmic service "Mesh Agent" call stopservice
wmic service "Mesh Agent" call startservice

**Comment by krayon007** [comment]
I think I figured this one out... In issue #1955 I had mentioned that I had been using a flag: `LOAD_LIBRARY_SEARCH_SYSTEM32` on my call to GetLoadLibraryEx(), that is not supported on Windows 7 SP1 and Windows Server 2008 R2 without a MSFT patch installed:

> Windows 7, Windows Server 2008 R2, Windows Vista and Windows Server 2008:  This value requires KB2533623 to be installed.

I am working around this issue on the next agent update, as this specific code path was only needed for backwards support of Windows XP, however XP is no longer supported for other reasons, so I can just remove this code and make it call the Windows 7 supported method directly.

In the current version of the agent, without this KBB installed on Windows 7 SP1, the timeout doesn't get set correctly because the underlying call failed, so the agent will not correctly send keep alives to the server, which is why the agent disconnects after a while.

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
