### ISSUE TITLE
Possible connection though Cloudflare?

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#1766]
Hi
i was wondering if its possible to mask the IP though Cloudflare? I tried before but wouldn't work as i think the agent needs to see the real IP

Thank you

**Comment by Ylianst** [comment]
I imagine your asking about masking the server's IP address? I am pretty sure people have done this before. If I understand correctly, Cloudflare will be your reverse proxy. I am not sure if this is a big benefit since most of the MeshCentral traffic is websocket. You will need to have Cloudflare forward websocket connections, you point your DNS name to Cloudflare. Your also are going to have to use the "certurl" option to have MeshCentral load the externally visible TLS certificate from Cloudflare.

**Comment by killmasta93** [comment]
thanks for the reply, meaning that if i also run NGINX on my server as reverse proxy it might not work with cloudflare?

**Comment by Ylianst** [comment]
You can have both, just set "certurl" to fetch the same TLS certificate the agents will see.

**Comment by killmasta93** [comment]
Thanks for the quick reply, 
on the config i have the certurl 
`  "CertUrl": "https://remote.mydomain.com:443/",`
and the TLS offload 

`"TlsOffload": "127.0.0.1",`

i checked the logs

```

Agent bad web cert hash (Agent:c96ea4130d != Server:06b37d7ff6 or 06b37d7ff6), holding connection (192.168.3.254:49840).
Agent reported web cert hash:c96ea4130d5c6374b44be181aa3fb5f89e403fadd398cd37a6ce331eabc6b06c89076142f555f2143a89864a7904bfa5.
Agent bad web cert hash (Agent:c96ea4130d != Server:06b37d7ff6 or 06b37d7ff6), holding connection (192.168.3.254:49896).
Agent reported web cert hash:c96ea4130d5c6374b44be181aa3fb5f89e403fadd398cd37a6ce331eabc6b06c89076142f555f2143a89864a7904bfa5.
```
what i do see when proxying though Cloudflare it does change my SSL which i see that the agents wont go though because its another web cert. but would i change the cert url to cloudflare?

![image](https://user-images.githubusercontent.com/13953629/91649158-6f9e4b80-ea36-11ea-8954-b3294d8e56d1.png)


Thank you

**Comment by Ylianst** [comment]
So yes, you should be any HTTPS:// URL in "certurl" that would allow MeshCentral to retrieve the same certificate that the agents would see. I imagine you saw some messages indicating the MeshCentral did load a certificate due to the "certurl" you setup? If not, there is something wrong. But if the "CertUrl" is triggering the certificate load, now the trick is to make it load the same cert the agent would see.

**Comment by killmasta93** [comment]
Thank you i had to match the same cert as for the agents

**Comment by eldadh** [comment]
Hey,
I am having the same problem,
My setup is:
Mesh server on VPS ( Oracle Cloud )
NgineX Reverse Proxy on another VPS ( Oracle Cloud )
And CloudFlare Proxy

I am receiving a The fallowing Logging Event Which seem to supposed to work since the agents does report the correct SHA:

Loaded web certificate from "https://remotely.XXXXXXX.com:443", host: "remotely.XXXXXXX.com"
  SHA384 cert hash: 5db18c385542eab661f678a66fddf1251dd01c4d347a1a38252a335b1785e098bb424d79aa9f745f253bd8ac46296a64

MeshCentral v0.7.72, WAN mode, Production mode.
Agent bad web cert hash (Agent:5db18c3855 != Server:51f549f2cc or 6368d24cc2), holding connection (XXX.XXX.XXX.XXX:34110).
Agent reported web cert hash:5db18c385542eab661f678a66fddf1251dd01c4d347a1a38252a335b1785e098bb424d79aa9f745f253bd8ac46296a64.

relevent lines from config:
    "cert": "remotely.XXXXXXX.com",
     "certUrl": "https://remotely.XXXXXX.com:443",
    "TlsOffload": "172.16.1.9",
    "trustedproxy": "CloudFlare",


Thnx In Advance
I am using version 0.7.72
