### ISSUE TITLE
MeshCommander AMT SOL(Serial Over Lan) Black Screen Problem 

### ISSUE THREAD

**Issue by JunHyunPark1210** [Ylianst/MeshCentral#1769]
Hi Yilan,

We want to bring up the BIOS screen through SOL in MeshCommander, but I've faced with SOL(Serial Over Lan) Black Screen Problem.
We already checked #604 issue and comments, but my problem is not solved.

We tried to use SOL feature via meshcommander tool on v0.7.9-a, v0.7.9-b, v0.8.0-b, v0.8.0-c, v0.8.8-a.
But the problem occurred the same in all versions.

Please let me know if which part should be checked in detail.
We would like to find the cause of the failure and solve it, so please support. Thank you.

* Remote target PC setting
Intel 5th Gen. vPro
Set ACM
SOL, Storage Redirection, KVM are all enabled
Network setting is Default (DHCP)
![sol test](https://user-images.githubusercontent.com/29420499/91786761-4acaf380-ec43-11ea-99e3-4f536f62fd9d.png)

* In the reference Image, the red progress bar no longer progressing.

**Comment by Ylianst** [comment]
Hi. So, maybe the problem is a misunderstanding of that Serial-over-LAN does. When you connect, it will just make anything you type be sent to the Intel AMT Serial Port (Often time it's COM3) as shown here:

![image](https://user-images.githubusercontent.com/1319013/92039934-c5227300-ed2a-11ea-84a1-481c6c46da8b.png)

So, if there is no software listening to COM3, you will not see anything. One thing you can do is run PUTTY on COM3 at 115200 bauds, like shown below and you should see that everything you type in MeshCommander will be displayed in PUTTY and the other way around too.

![image](https://user-images.githubusercontent.com/1319013/92040047-f69b3e80-ed2a-11ea-8735-072cdc7aa3a1.png)

Another thing you can do is connect SOL in MeshCommander and cause a "Reboot to BIOS". In this case, the BIOS will start sending VT100 codes and you should see something like this:

![image](https://user-images.githubusercontent.com/1319013/92040786-d9b33b00-ed2b-11ea-8577-5d0d79bb11f9.png)

Let me know if that helps,
Ylian

**Comment by JunHyunPark1210** [comment]
Hi, thank you for your support.
These are the results we tested according to the advice you gave me.

1) The Intel AMT serial port (COM3) shown here is listening normally.
![soltest_result1](https://user-images.githubusercontent.com/29420499/92052024-23516380-edc8-11ea-9c3e-f9c1d97bafbc.png)


2) And, the connection to the COM3 in PUTTY was successful, but nothing was displayed on the Putty screen.
![soltest_result2](https://user-images.githubusercontent.com/29420499/92053312-99ee6100-edc8-11ea-9be9-3f62e004f4cf.png)


3) Lastly, displaying the BIOS Screen through "Reboot to BIOS" in SOL MeshCommander was successful shown here.
But, the shape of display shown is a little different from yours.
![soltest_result3](https://user-images.githubusercontent.com/29420499/92057801-028a0d80-edca-11ea-82b0-076cb9030373.png)


In my opinion, the connection to port3 (SOL) is fine, but there seems to be a problem with displaying the screen. 
I don't know if this is simply a computer spec problem. 

If you know anything, please let me know why the 3) screen is displayed in that form, and any additional helpful information. 

Thank you.
