### ISSUE TITLE
Login page text

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#178]
Request : place text shown on the login page within a data/config file. When the server gets updated, that text isn't replaced (much like the logos etc)

**Comment by Ylianst** [comment]
Hold my beer...

**Comment by D4V3M0NK** [comment]
Careful ... I'm from England, once someone passes me their ... oops, there you go ... all gone!

**Comment by Ylianst** [comment]
Actually, I just noticed that feature is already present. Add this to the domain section of config.json:

```
      "welcomePicture": "mainwelcome.jpg",
      "welcomeText": "This is a sample welcome."
```

Then put a "mainwelcome.jpg" file in your meshcentral-data. That should do it. Let me know if that works.

**Comment by D4V3M0NK** [comment]
:O) yup works perfectly. Apologies, must've missed that in the admin guide. 

For those searching for the future:
- "WelcomeText" and "welcomeText" appear to work
- "WelcomeText" and "WelcomePicture" are mutually exclusive.

**Comment by Ylianst** [comment]
So, in config.json, all of the key names should be case insensitive. so "WelcomeText" and "welcomeText" and "welcometext" should be the same. However, you can't use two or more of these, only one will win out.

"WelcomeText" and "WelcomePicture" should not be exclusive. You can set both your text and picture. I use the on meshcentral.com. If it does not work, let me know... but it should since I use it.

**Comment by D4V3M0NK** [comment]
Ylian, you're correct - in my testing I think I had some cached browser files ... I'll mark that comment as incorrect above, but will leave the message for clarity.

**Comment by Ylianst** [comment]
Closing this one. Please re-open if needed.
