### ISSUE TITLE
Cannot interact with AVG AV

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1810]
Running on the last MC on Debian with NGINX reverse proxy.
Agent is installed on Win10 x64 and added to Exceptions on AVG AV.

When double click on AVG icon in the tray to show AVG UI, all connection becoming frozen, cannot interact with the system at all.
When send CTRL+ALT+DEL can interact again to start let's say a Task Manager
![image](https://user-images.githubusercontent.com/59362521/92930693-520bb180-f43a-11ea-9477-d29a7a7928b1.png)

Once Task Manager is on the screen, can move Task manager window, can select other windows, can start on start menu, etc - BUT as soon as AVG window is clicked, freezing again. To unfreeze it sending again CTRL+ALT+DEL, and doing the same. So there is no option to close AVG window or somehow to interact with it.

**Comment by Ylianst** [comment]
This is a bit of a problem because I suspect these software are purposefully trying to get around having other software disable them. This said, longer term Bryan may work on an improved way of capturing the remote display on Windows to boost speed and the new technique may fix this. This is not something we can fix quickly.

**Comment by vitko-bg** [comment]
It is strange as TeamViewer and AnyDesk can interact, disable and click anywhere on the same client PC.

**Comment by krayon007** [comment]
> It is strange as TeamViewer and AnyDesk can interact, disable and click anywhere on the same client PC. At least to have an option to close the AVG window, otherwise cannot interact with all client PC, unless follow the steps with CTRL+AlT+DEL

I think that's because TeamViewer uses a mirror driver when not using the Desktop Duplication API. However I'm looking into adding support for Desktop Duplication API (which is on Windows 8 and newer), but that won't be ready for a while because it requires a complete rewrite of KVM.

**Comment by Ylianst** [comment]
Not just a KVM re-write. The it would also break the desktop recording and desktop multiplexer features that needs to be improved. Currently these two features assume 32x32 times and no "move" commands. This said, I already started working on alternative code for this.

**Comment by PathfinderNetworks** [comment]
This has been an issue for quite a while now.  There was another discussion about it a while back in regards to Avast (which is the same as AVG since Avast bought them out).  When the Windows focus is on the antivirus app (be it when opening the system tray or the full GUI) it won't allow any input from MeshCentral.  But you can send a Ctrl-Alt-Del and, as long as you don't click the antivirus interface (meaning don't put the focus back on to that app) then you can continue to interface with the remote desktop through MeshCentral.  In my case, when I need to do any work with Avast (I use Avast CloudCare for all of my clients and their devices) I just remote in to the device using the Premium Remote app that is included with CloudCare.  As has been mentioned, most all the other remote apps don't have this particular issue (including Premium Remote).

**Comment by chriscarpenter12** [comment]
Is there any change with this issue? I just started testing MeshCentral and was hit by this on and endpoint using Avast. When it's in the foreground nothing is clickable.

**Comment by krayon007** [comment]
Not yet. But one thing I found, is that the Microsoft Desktop Duplication API only deals with viewing the desktop, it doesn't deal with remote injection. (At least I didn't see anything along those lines). Which means, I would still be using SendInput() for the remote injection, which means if it doesn't work with Avast, it still wouldn't work even after I rewrite the KVM. I need to see if I can find out what other projects are using for remote injection.

**Comment by brunolabozzetta** [comment]
Any updates on this issue? Having this issue on a friend infrastructure with Avast AV. Any workarround either? thks!

**Comment by silversword411** [comment]
Contact Avast, and ask them where the option is to disable this feature they've implemented.

> with Avast AV

**Comment by kromekej** [comment]
This also happens when you run the Windows health check program and some other Windows functionality.

**Comment by si458** [comment]
the isnt much we can do, as AVs do this for security, you would have to allow the exe to intertact with the AV
