### ISSUE TITLE
Thanks to all on the Mesh Central Team....we all owe you a huge debt of gratitude.

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1830]
I've felt kind of guilty lately for some reason.  We use Mesh Central every day.  It's become our number 1 RMM software.  It's so flexible from Linux, to Windows, to Mac and has quickly become the core of our daily business.  Every now and again I come up here and vomit up yet one more bug, or feature request.  Ylian and team jump on it with enthusiasm, and sometimes same day or next day you guys produce some solution like magic.  It's truly incredible and even legendary.  And always with an incredible attitude.  

The requests are seemingly endless.  I want this, I want that... from everyone around the globe.  And you guys keep stuffing features into the product with this incredibly willing attitude and great design to boot, and MC keeps getting better and better.

I, for one...and I'm sure there are many others, am beyond thankful for everything you guys put into this.  I want to repay you somehow.  This kind of product is just so sorely needed.  

Thanks for all you do, for how fast, and for how well it all gets done.  Let us know how we can continue to support you.  If this ever becomes a paid product, I'll support you guys all the way. (As much as I love Open Source!)

Shane@SoutheasternTechnical.

**Comment by PathfinderNetworks** [comment]
Well said.  I feel exactly the same way.  I've been using MeshCentral for over 6 years now.  It is, absolutely (without anything else even close second), the most important tool for my business.  I was happy with the MeshCentral v1 development. But the MeshCentral 2 development is unbelievably far above and beyond what I was happy with in MeshCentral 1.

**Comment by PetieM** [comment]
100% agreed, well said. I've had those same feelings of occasional guilt coming here to ask for more on a free product that is way better than I could have possibly hoped for already. I've somewhat alleviated those thoughts with the hope that the bug reports and feature requests I've submitted will benefit far more than just me in the long run but I still completely get where you're coming from so thanks for posting this!

And seriously, @Ylianst and anyone else working on this, thank you!

**Comment by Ylianst** [comment]
Thank you guys! Glad you hear and your comments are much appreciated.

@PathfinderNetworks You are one of the very few that started with MeshCentral1. I am so glad we switched to the new architecture, it's much better. The new architecture is much easier to work on and it's been a big boost in how fast we can code. Also, I really like the real-time user interface of MeshCentral2.

@southeasterntech Thanks. Your right that the requests are more than we can handle, but we do are best and it's wonderful that there is such a supportive community. MeshCentral will not became a paid product since we have an amazing sponsor. If your looking to manage computers regardless of OS state, [consider Intel vPro](https://www.youtube.com/watch?v=2gSdrPEo8ZI) 👍.

@PetieM No need for guilt, I rather people post issues than not. There is no way Bryan and I could test all the different situations that you guys are running into, so your reports are very useful. Apologies in advance that I can't fix everything even faster.

By the way, there is a way to thumbs up issues. If you guys ever see issues you would like Bryan and I to focus on, make sure to up vote. I will try to work on these a bit more. Otherwise, I split my time between issues on GitHub and other features that Bryan and I want. I also have MeshCommander to keep me busy, so no shortage of work.

**Comment by cgb** [comment]
Agree with above - I'm a recent user of the product in my small-time MSP and have been a strong advocate in customer networks to recommend Meshcentral over their existing RMM tools.  I can't say enough positive about this software & it's been the first tool in a long time that I've been 100% impressed & happy to use every day.  Thanks again :+1:

**Comment by LFM8787** [comment]
I'm actually pretty new, I've just found MeshCentral a couple of weeks ago, but it's a master piece of software, I wish I could code better to give a handy help but I'm not so well, anymway, thanks to all of the ones involved in the development of MeshCentral. Thank you!

**Comment by mschubeck** [comment]
I agree with everyone's comments.  MeshCentral has gone from being a backup RMM to our primary platform.  We still need our other RMM for tasks and procedures that MC2 doesn't do, but we prefer the remote desktop to any VNC variant that most other RMM platforms use.

Originally I used the v1 in two modes - the self-hosted and the cloud variant.  But when v2 came out, I started testing it and found it to be so lightweight compared to v1 that we found no reason to use the cloud version any longer.  When the LetsEncrypt integration was added, we added all clients to our MC2 server rather than just a select testing group.  And with MeshCommander running as well, every workstation we order for ourselves or for resale comes with AMT & vPro from Intel.  Ylian has definitely been the catalyst for this.  The way he personally addresses any issues I've had is great, but I've also felt guilty as well, and so I've switched over to GitHub rather than continue to bother him individually.  Ylian, stay awesome my friend!

**Comment by MordyT** [comment]
It's been a hot minute since I commented in this project. But I want to echo what was said above about how the team goes above and beyond and produces this incredible software. It's very appreciated and it's become a core part of the tech stack where I work because of how flexible it is.

I first dabbled with MeshCentral in 2014 (clicked the wrong button looking for MeshCommander, because that was the only way I knew how to configure some vPro settings at the time), and although I didn't use it much then, it's amazing to see how the project has progressed.

Please do let us know if/how we can support the team (obviously we can submit pull requests, but if other items come up, let us know).

**Comment by SomeGuru** [comment]
@Ylianst @krayon007,

Know that your impact is greater and longer reaching than the absolute great work that is put forth in this effort... 

You have seen numbers balloon since the beginning of this Covid-19 pandemic I am sure, and I can only imagine the influences that drive you to implement some of these exceptional abilities with MeshCentral...  

A couple of the really awesome features as of lately I have been wanting to follow up on and give gratitude, have been the collapse groups features,  group run action, and honestly the ability to execute a command across the whole domain as well...

This made patching and verification checking several hundred man hours shorter, and removed the need for 15 people to sneakernet around to multiple hundreds of nodes for a simple check. 

I was able to make a script for Windows and Linux and based systems to utilize on the run command, and I was able to see in real time the results of the pass/fail of systems, and quickly I was able to reverse issues on those machines that did not take the update correctly... 

So Thank you, Thank you, Thank you for that ability... I am impressed with the features over the last two years being of such high caliber for such a great price (FREE!!!)...

Bravo on a job well done gentlemen.

SomeGuru

**Comment by D4V3M0NK** [comment]
I've only just seen this posting and felt (like so many others) that it wouldn't be right to not make a comment...

The commitment that @Ylianst , @krayon007 and others dedicate to MC2 is without equal. I'm a firm believer in open source software and yet, with very little reward, this particular team continues to build excellent software and first rate support. I've often thought (and asked once or twice) what we, as a community, could do for the them: the only response that I received was perhaps an email written to the team's management, but even that feels not enough.

I've been working on a particular project for coming up for 5 years now and one of the major hurdles that I knew I had to overcome was to find an RMM for a specific market sector that is incredibly difficult to not only get into, but to please too. About 4 years ago I came back to MC(1) only to find that it had transformed itself into the MC2 product that it was then ... and of course, it continues to evolve into an amazing product. As of today I'm (finally) looking at rolling this great product out and using it heavily to manage deployed systems that I simply could not have done otherwise.

I've asked more than my fair share of questions and suggestions from Ylian and Brian in particular (forgive me, I'm not sure how big the team is) and yet time and time again they make me feel as if I'm contributing to the project just as much as they are: and nothing could be further from the truth, but typically responses are within 24 hours of being asked and on two occasions I know of, Ylian was actually on vacation and still responding.

Chaps - merely saying "thank you" just doesn't seem to be enough and hopefully in time there'll be the opportunity to thank you all in a more appropriate manner, but for the time being ... beers are on me. :beers: 


Thank you guys, sincerely, you're a rare breed.
