### ISSUE TITLE
Add loginkey for MeshCentralRouter 

### ISSUE THREAD

**Issue by vyacheslav25** [Ylianst/MeshCentral#1832]
Hey. It will be very cool if you add the key for the server to meshcentralrouter. In our network, each employee has access to his computer through it. And there are a couple of admins. I would like to be able to hide all admins if they quit. Otherwise, each employee will have to change the password in router. I would be glad if this is possible. thank

![image](https://user-images.githubusercontent.com/46028241/93561959-c6d87180-f98d-11ea-9caa-a56968b60d82.png)

**Comment by Ylianst** [comment]
OMG. Excellent idea. I will add that tomorrow. Totally makes sense.

**Comment by Ylianst** [comment]
I just check in all the changes for this, it will be in MeshCentral v0.6.42. This adds some level of added security as the websocket connection to "control.ashx" is now blocked by the loginkey. You will need to update MeshCentral Router because starting with v0.6.42, you can't connect anymore unless you have the login key.

![image](https://user-images.githubusercontent.com/1319013/93633609-12961580-f9a4-11ea-9c53-aa65960decc0.png)

I also added login key support to MeshCtrl.js and MeshCmd since both of these are also impacted.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.42 with updated MeshCentral Router that includes LoginKey support and new file manager. Let me know if it works.

![MC2-MeshCentralRouterFileManager](https://user-images.githubusercontent.com/1319013/93690538-49485a80-fa8e-11ea-9751-054e717ff6db.png)

**Comment by vyacheslav25** [comment]
The key works. But the program itself doesn't work. I can not connect via rdp and other protocols. The new menu opens, but does not connect.

**Comment by Ylianst** [comment]
Ok, checking this.

**Comment by Ylianst** [comment]
Just tried it and the port mapping works for me. Can you run MeshCentral Router with `-debug`, try again and send me the resulting `debug.log` file privately? [My contact is here](https://www.meshcommander.com/contact-information). Thanks.

**Comment by vyacheslav25** [comment]
Sorry. We rolled back meshcentral to stable release. The new version of the router fully works with the stable release.
I can run it in debug if necessary

**Comment by Ylianst** [comment]
Yes, please send over the `debug.log` when you can. Please clear the file, run `-debug`, make the error happen and then send me the file. Thanks.
