### ISSUE TITLE
Set tags during install

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#1835]
Hi

I am aware you can set agent tags using .tag file in the same location as the agent. However I'm after the ability to set multiple tags for machines, and the only method I found works is doing this from the UI manually using the tags, which I know can be done by bulk. However as machines are reimaged and agent is auto deployed back to the server, having to find the machines and place multiple tags becomes a bit of a chore. 

Setting the tags from the servers console allows you to use the sort by tags, which is not possible by the agent tag.  Setting tags from the server works well in my case, as I have vPRO machines (which you cannot apply agent tags too) and Agent machines which are split into there own groups, but by applying tags, I can easily sort by tags, which gives me the view I need. 

Possible ideas on how to do this. 

1. During the meshagent install, allow a switch which sets a tag(s) 
2. If you can add tags using meshctrl, I think I would be able to figure out script during the OS deployment to edit the device and assign the tags. Not seen the ability to edit a device. 

Thanks

**Comment by Ylianst** [comment]
Good request. I don't generally trust the agent to edit tags since currently tags are server side. I could allow this as an optional feature, but you would need to turn it on. One idea is that if this feature is enabled on the server, the agent tag with a special format would be converted into server tags. So a meshagent.tag the contains:

```
ServerTags: "home", "2nd Floor"
```

Would be converted into two server tags. Would this work? Also, would this be something that is only at device creation time or the tags would be reset each time the device connects?

**Comment by vish84** [comment]
That sounds like a potential method. 
Slightly confused by what you refer to if tags would be reset each time? 

With the optional feature would you be able to add a servertag to a device group for vPro machines only, as these are not deployed with .tag files and are added from the console

**Comment by Ylianst** [comment]
Ok, working on this one now....

**Comment by Ylianst** [comment]
![MC2-AdvancedAgentTags](https://user-images.githubusercontent.com/1319013/94082736-765e7b00-fdb6-11ea-89e3-44fec1bd392e.png)

Just published MeshCentral v0.6.48, once you update change the config.json to add this section in the domain section of the config.json and restart the server.

```
"agenttag": {
  "ServerName": 1,
  "ServerDesc": 1,
  "ServerTags": 1
}
```

When create a "meshagent.tag" file in the same folder as the "meshagent.exe" and put this in it:

```
~ServerName:SampleDeviceName
~ServerDesc:This is a sample description
~ServerTags:Tag1,Tag2,Tag3
This is the agent tag
```

Then restart the agent. You should see the values in the meshagent.tag be set on the server. Let me know if this works.

**Comment by yomono** [comment]
Hi @Ylianst . Can I ask you a question? This feature is perfect to me because im building a installer wrapping the original Agent installer, and i can use this.
I would like to know: After the agent is started once with the .tag file, and the server already set them, is a good practice to delete this file? Because, if i leave it there, any user can go and change the Tags freely

**Comment by Ylianst** [comment]
It's up to you. The MeshAgent will send the content of this file each time it connects to the server. You are free to remove the file once the agent connected to the server the first time.

**Comment by yomono** [comment]
I realized that it's also added on the registry. Had to delete from there too.
Brief explanation: I'm using the tag to generate a random access ID (Like teamviewer, something like 351-454-8754), and use that as a reference to access to the computers (my intermediate program will show this ID). 
That's why I want to generate this tag just ONCE, and delete all trace of it from the client side (I will store it on my program, but on an encrypted file). That way, that tag is assigned to that PC and there is nothing the client can do to change it. muahaha.

The original idea was to add a password to the process, but that would mean I have to do an extension to interact with the server side, and I don't have the necessary time these days.

Anyway, I just want to add this info in case anyone else could find it useful.

PS: I know all this is actually something you could do before this change, with the "old" tag functionality. This post was just a good excuse to do this tests for me. Thanks

**Comment by vish84** [comment]
Hi @Ylianst 

Thanks for the work. However i'm struggling to make this work. When I set the config as stated above. 
The .tag data only seems to be sent to the the Agent Tag section, it does not seem to set the sections as highlighted in red in your screenshots. Attached some screen shots, which hopefully explain what i'm seeing
<img width="716" alt="Config1" src="https://user-images.githubusercontent.com/51713320/94135764-d0fde280-fe5b-11ea-974b-9862a9f31409.PNG">
<img width="705" alt="Config3" src="https://user-images.githubusercontent.com/51713320/94135767-d1967900-fe5b-11ea-9b9c-be80f7314319.PNG">
<img width="665" alt="Config2" src="https://user-images.githubusercontent.com/51713320/94135771-d3f8d300-fe5b-11ea-9ffe-64946acd10f5.PNG">
<img width="705" alt="Config3" src="https://user-images.githubusercontent.com/51713320/94135775-d5c29680-fe5b-11ea-9f32-82a925ffaa38.PNG">

**Comment by Ylianst** [comment]
@vish84 I see the problem, your config.json is not right, replace it with this:

```
{
  "settings": {
    "cert": "192.168.1.9",
    "_minify": true
  },
  "domains": {
    "": {
      "agenttag": {
        "ServerName": 1,
        "ServerDesc": 1,
        "ServerTags": 1
      }
    }
  }
}
```

So, in the domain section, there is a list of domains with "" being the default domain. You need to put the "agenttag" without the default domain for it to work. Sorry I was not clear about that.

**Comment by Ylianst** [comment]
@yomono, thanks for the information. If course, we use the NodeID which is the SHA2-384 hash of the agent certificate public key. That identifier is unique and the agent can prove that it's that identifier (it can't be spoofed). This said, that ID is way to long to type so I understand having an alternative identifier.

**Comment by vish84** [comment]
@Ylianst no need to be sorry, works perfectly fine. just me not paying attention to the syntax, more coffee needed. once again thank you for being so responsive and creative in finding solutions.
