### ISSUE TITLE
Mesh Router unable to connect to server

### ISSUE THREAD

**Issue by jmcmanus26** [Ylianst/MeshCentral#1838]
I am able to connect to the web interface but not with mesh router.  I am getting the following error.

---------------------------
MeshRouter
---------------------------
The handshake failed due to an unexpected packet format.
---------------------------
OK   
---------------------------

Server Version: 0.6.42
running on: Debian Linux 
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

npm@6.14.6

**Comment by Ylianst** [comment]
Are you using a "LoginKey" on your server? If so, add "?key=xxxx" to the hostname in MeshCentral Router and try again. If not, let me know.

**Comment by jmcmanus26** [comment]
I'm not sure what a "LognKey" is.  Is that something I would set in the config?

**Comment by Ylianst** [comment]
Ok, can you run MeshCentral Router with `-debug` and send me the log you get? [My contact info is here](https://www.meshcommander.com/contact-information). Thanks.

**Comment by Ylianst** [comment]
When getting the following error:

![image](https://user-images.githubusercontent.com/1319013/93914540-89d8eb80-fcbb-11ea-8817-e66a7dbb5524.png)

The problem is likely that your trying to connect to a non-TLS port. For example, if you try to connect to port 80 of Google.com, you get this error. If your MeshCentral server is on non-standard ports, make sure you specify the TLS (HTTPS) port in MeshCentral Router.

Let me know if that works.

**Comment by jmcmanus26** [comment]
Ok I understand now.  Thanks!

Here is what I get when I connect to my TLS port.

MY TLs setup is using nginx revere proxy.

[image: image.png]

**Comment by Ylianst** [comment]
I can't see your image above, so I have no idea what error you are getting. As a guess, if you are getting this error:

![image](https://user-images.githubusercontent.com/1319013/93917024-44b6b880-fcbf-11ea-8c93-0d8d3a0aab40.png)

Then the problem could be that your MeshCentral server only supports TLS 1.3, but MeshCentral Router only supports TLS 1.2. In that case, you need to turn on TLS 1.2 in your reverse proxy.

Ylian
