### ISSUE TITLE
MAC Agent uninstall incomplete - How to remove?

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#1858]
We are trying to reinstall the meshagent on a MAC.  We tried removing the existing agent and it appears to be gone, until we go to install the agent, then the installer shows that we are trying to upgrade.  I'm assuming that there is a remnant but I have had no luck finding it.  What is the installation path fr the meshagent on a MAC?  Perhaps then we can finally remove any left over files and be able to reinstall.

**Comment by krayon007** [comment]
How did you remove the agent?

**Comment by frankmcc** [comment]
Using the Uninstall.command inside of the MeshAgent.mpkg because there was no other way as far as we can tell.

**Comment by krayon007** [comment]
OK I'll take a look at that uninstall command, and see if it leaves anything behind... In the mean time, you can also uninstall by running the agent binary directly, using the command:
`./meshagent -fulluninstall`

You can try the above. If the agent thinks it is doing an update install of an install, it is because the .plist file is still there for some reason... But the above command, should clean everything.

You can also download the binary installer version of the agent... That will give you an uninstall button. (which will basically call the above command internally)

**Comment by krayon007** [comment]
Running some tests, it seems the mpkg installer always seems to say "Update", even when the agent is not actually installed. Other then that, it seems to function correctly. I even ran the other installer method, and it correctly reports when the agent is installed or not.

**Comment by frankmcc** [comment]
You are correct.  We got hung up on the upgrade and never completed the installation.
