### ISSUE TITLE
MC 0.6.55 - Desktop button 'upload local clipboard to device' for Mac OS X 10.15.7 not working

### ISSUE THREAD

**Issue by zaggynl** [Ylianst/MeshCentral#1875]
Download seems to work but upload does not, anyone else running into this?

**Comment by Ylianst** [comment]
This is one for Bryan, not sure if the clipboard is implemented on MacOS.

**Comment by PetieM** [comment]
Confirming that I'm seeing this behavior as well. The old clipboard button was never implemented for macOS but the new upload/download buttons on the bottom right are available and currently half-work as described. I actually seem to remember that both directions worked when the feature was initially released but I could be mistaken.

**Comment by krayon007** [comment]
do the `getclip` and `setclip`  console commands still work for you?
I just tested both getclip and setlip, as well as the upload and download clipboard button with macOS 10.15, and it seems to work fine using server version 0.6.60... I don't think anything changed for that between 0.6.55 and 0.6.60... Unless something broke between macOS 10.15 and 10.15.7

**Comment by krayon007** [comment]
I just tested with macOS 10.15.7, and it still appears to work... I tested with Chrome and Firefox. Are you guys using a different browser?

**Comment by zaggynl** [comment]
getclip and setclip work, thank you!

Appears to be browser related, on my Linux desktop, in Chrome 87.0.4278.0 and Chromium 85.0.4183.121 the upload clipboard work.

Firefox 81.01 does not change the Mac clipboard when using Desktop tab and upload clipboard button when connecting to Mac client

Additionally: Firefox doesn't show the download clipboard button anymore for me.

**Comment by krayon007** [comment]
Interesting. I was testing from Chrome 83 on Linux... @Ylianst, I wonder if the Chrome API changed. Sounds like the mechanism to get/set the local clipboard in the browser broke.

**Comment by krayon007** [comment]
I was also testing from Firefox 79... Upload worked, but I noticed the download button was missing...

**Comment by PetieM** [comment]
I just completed testing between various Macs and PCs from multiple browsers on Mesh server v0.6.62. Here are my results:

**Mac (v10.15.7) Client, PC (Win10 2004) Host:**
_Chrome (v86.0.4240.80)_
Clipboard Button Set: Worked
Clipboard Button Get: Worked
Clipboard Upload: Worked
Clipboard Download: Worked
_Firefox (v81.0.2)_
Clipboard Button Set: Worked
Clipboard Button Get: Worked
Clipboard Upload: Failed, no console output
Clipboard Download: Button missing
_Safari 14 (v15610.1.28.1.9)_
Clipboard Button Set: Worked
Clipboard Button Get: Worked
Clipboard Upload: Failed, no console output
Clipboard Download: Failed, Console error - NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

**PC (Win10 2004) Client, Mac (v10.15.7) Host:**
_Chrome (v86.0.4240.75)_
Clipboard Button Set: Button missing
Clipboard Button Get: Button missing
Clipboard Upload: Worked
Clipboard Download: Worked
_Firefox (v81.0.2)_
Clipboard Button Set: Button missing
Clipboard Button Get: Button missing
Clipboard Upload: Failed, no console output
Clipboard Download: Button missing

**PC (Win10 2004) Client, PC (Win10 2004) Host:
_Chrome (v86.0.4240.75)_
Clipboard Button Set: Worked
Clipboard Button Get: Worked
Clipboard Upload: Worked
Clipboard Download: Worked
_Firefox (v81.0.2)_
Clipboard Button Set: Worked
Clipboard Button Get: Worked
Clipboard Upload: Failed, no console output
Clipboard Download: Button missing

**Mac (v10.15.7) Client, Mac (v10.13.6) Host:**
_Chrome (v86.0.4240.80)_
Clipboard Button Set: Button missing
Clipboard Button Get: Button missing
Clipboard Upload: Worked
Clipboard Download: Worked
_Firefox (v81.0.2)_
Clipboard Button Set: Button missing
Clipboard Button Get: Button missing
Clipboard Upload: Failed, no console output
Clipboard Download: Button missing
_Safari 14 (v15610.1.28.1.9)_
Clipboard Button Set: Button missing
Clipboard Button Get: Button missing
Clipboard Upload: Failed, no console output
Clipboard Download: Failed, Console error - NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

To clarify, "Clipboard Button" refers to the button at the bottom left of the Desktop screen whereas "Clipboard Upload" and "Clipboard Download" refer to the two newer buttons at the bottom right. As for the console errors in Safari, I think this might be a new security feature but the preferences window does not currently expose any way to allow clipboard write (or read, for that matter) access.

**Comment by si458** [comment]
clipboard works on mac, both get and set,
just be aware of #5273 where its missing the last 2 things of your clipboard for some reason!
fix has been merged, just need new agent releases!
