### ISSUE TITLE
After update to 0.5.81 some agents change from online to offline status continuously

### ISSUE THREAD

**Issue by edorbike** [Ylianst/MeshCentral#1878]
Some agents continously change from online to offline. This agents access to internet form 3g router. When are offline i can enter from teamviewer but not from mesh. If I restart the mesh client agent service on a remote pc change status to online but after some minutes later change to offline again. One hour later the devices are permanently offline.

Thanks for your help.

**Comment by edorbike** [comment]
Some agents continously change from online to offline. This agents access to internet form 3g router. When are offline i can enter from teamviewer but not from mesh. If I restart the mesh client agent service on a remote pc change status to online but after some minutes later change to offline again.

Thanks for your help.

**Comment by Ylianst** [comment]
It's possible you have some unique networking situation because of the 3g router, try adding the following to the settings section of the config.json:

```
    "AgentPong": 60
```

This will cause the server to send data to the agent every 60 seconds, but there will not be a response from the agent. You can adjust the time as you like. If that does not work, try this:

```
    "AgentPing": 60
```

This will send data to all agents every 60 seconds and the agent will respond with data back.

Obviously, you could put a very short timeout, but that increases the about of data you send/receive on 3G. Let me know if that helps.

**Comment by edorbike** [comment]
I have done different tests. With either of the two settings ("AgentPong": 60 or "AgentPing": 60), it is necessary to restart the client agent on all remote computers to bring them online. Besides, when the ubuntu server is restarted (mesh server is instaled on ubuntu 18.04.5) all the computers set offline again. This behavior occurs not only on computers with 3g connection but also on computers connected to a LAN.
Thanks for help
