### ISSUE TITLE
Device share with guest - enhancement request

### ISSUE THREAD

**Issue by sheruvs** [Ylianst/MeshCentral#1891]
Hi, 

I'm using MeshCentral 0.6.54 on Ubuntu 18.04 Server LTS - 64b. Thanks for this piece of art ! 

I have multiple requests, all relating to sharing of a device with a guest.

**Use case 1**: Need to allow a guest to take remote control of a device starting at a specific date and time. 
- Along with duration, it would be nice if the start time can be specified.

**Use case 2**: During remote support by a vendor, the session sometimes gets extended for quite a few hours. I'm also looking at using this wonderful software for a remote training session next week which is expected to go on for the whole day.
- It would be nice if the duration of sharing can be extended from present 60 mins and to be available for 4, 6 or 8 hours.

**Use case-3**: We have a need where 2-3 staff members are required to be in front of a device for collaborating. For eg. hardware designers reviewing their PCB designs with E-CAD group members viewing their design on the CAD workstation. Complex projects go on for weeks and even months. We are presently exporting the CAD workstation display using RDP, but I would like to try out MC as it is far elegant. 
- For both Use Cases 2 & 3, if the share duration is made user configurable, it would be awesome. Don't know how complex it would be to implement, but I'm wishing for it, all the same :-)

Also, would it be possible to list the active shares for a device and provide a mechanism to revoke any share already created? If the Share icon is clicked, a pop-up with a listing (based on Guest name and duration of share) with an option to cancel any share before it expires would be great.

Thanks again & best regards

**Comment by vitko-bg** [comment]
@sheruvs not sure about option 1 and 3, but for option 2 please follow https://github.com/Ylianst/MeshCentral/issues/1806#issuecomment-691356354
Hope that will help.

**Comment by sheruvs** [comment]
Thanks for the info @vitko-bg. 
Yes, just checked. #1806 addresses Use case 2 perfectly !

**Comment by Ylianst** [comment]
This is a good request. I think that if the link is made to work longer (weeks) or at exact times (start-end), the system need to be improved to make the link revocable. That is, you create a sharing link for a device but it's stored in the MeshCentral database and you can remove it in the future. That way, you could even have an unlimited sharing link, but can be removed at any time.

I am currently working on improved security and Intel AMT stuff, but I will get around to doing this since it seems like a very popular feature.

**Comment by sheruvs** [comment]
Thanks! That would be great.. looking forward to it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.72 where you can see that device sharing links you have and remove them to immediately disconnect any user that is using them. This is the first step before I can create unlimited sharing links and links that start at a delayed time. Please let me know if this works so far.

![MC2-RemoveSharingLinks](https://user-images.githubusercontent.com/1319013/97766833-819f7780-1ad5-11eb-9133-e0158c51f97c.png)

**Comment by Ylianst** [comment]
You can now create a remote desktop sharing link using a start and end time range and status messages for links have been improved for guests. Since you can now revoke sharing links, there is no longer tight time limits. Feedback appreciated.

![MC2-DesktopGuestSharingRange](https://user-images.githubusercontent.com/1319013/97915304-20aab600-1d06-11eb-81e8-5cde5ddd9992.png)

**Comment by sheruvs** [comment]
My apologies for not being able to respond earlier.

Tested out all features above and all work great!  The time range and display about links being valid / expired are very useful. Thanks a lot for your efforts.  Really appreciate it :-)

**Comment by hellofaduck** [comment]
Sorry for posting in closed thread, i think creating a new thread for this questions is too much, but where i can see all remote links on my server in one place? and second, how i can disable this option for ordinary users or may be disable it on whole server?
