### ISSUE TITLE
Desktop blank until refreshed

### ISSUE THREAD

**Issue by map7** [Ylianst/MeshCentral#1898]
I'm using the latest 0.6.63 MeshCentral on Debian Buster and I've installed the client on many different linux, windows and Raspberry Pis. When trying to connect to some  of the Debian and older Linux Mint machines the screen doesn't refresh until I move my mouse around and then only the parts of the screen in which the mouse has activated something is displayed. When I say activated I mean that section has refreshed because of a hover over function, for instance if I hover over an icon on the desktop then that one icon and it's text is displayed whilst the rest of the screen is still blank.

If I open up any window full screen and then close it I can then see the whole desktop. It's like the agent needs to do a full screen fresh when a connection has been made.

**Comment by map7** [comment]
If I enable the "Notify User" in the User Consent area for the affected machine then the whole desktop shows up when I connect. This problem only seems to happen when no check boxes are selected in the 'User Consent' area.

**Comment by Ylianst** [comment]
I had a machine that did this and found have a workaround for it now. I would hit "Connect" and get a black screen on the Raspberry Pi below, workaround works but Bryan is working on the root cause. Should be fixed in MeshCentral v0.6.80.

![image](https://user-images.githubusercontent.com/1319013/98425879-a9e62380-204b-11eb-8ca5-dd9160ae3253.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.80 that should fix it. Let me know if it works.

**Comment by map7** [comment]
Yes that worked, thank you.
