### ISSUE TITLE
MeshAgent Win64 don't close descriptor

### ISSUE THREAD

**Issue by evgeniysevost** [Ylianst/MeshCentral#1915]
Hi Meshcentral team!

I found that MeshAgent.exe v.2.1.3 x64 (and possibly x32 too) periodically runs WMIC.exe and opens its descriptor (handle), after the WMIC.exe process died, descriptor does not close, and continue hang in memory (RAM). This causes the process memory of WMIC.exe not to be free. If the agent is running for a short time (a month maximum) it will not cause problems but after a year of uptime it can become an issue. It is like a temporary solution to restart the agent once a month.

Thx!

![image](https://user-images.githubusercontent.com/19427305/97161709-3c0a4400-178f-11eb-8bdc-aeba9f0efca5.png)

**Comment by jrdalrymple** [comment]
Turns out this issue is creating some grief for me at some clients locations (not all). For me the symptom is basically all memory eventually (about 3-4 days on 16GB systems) being exhausted on the Win10 64 systems causing the users to have to reboot to make them usable. I was a bit at a loss because the "missing" memory wasn't showing up in task manager, but definitely visible when I use sysinternals rammap. There are literally thousands of terminated wmic.exe processes that aren't releasing their memory.

I'm going to have to hack a fix (occasional scheduled restart of mesh agent) for this as it's a big enough interruption for the users. For me it's very repeatable though and I'd be elated to help resolve the issue by any means I'm capable.

Thanks for the otherwise great software.

**Comment by krayon007** [comment]
> Turns out this issue is creating some grief for me at some clients locations (not all). For me the symptom is basically all memory eventually (about 3-4 days on 16GB systems) being exhausted on the Win10 64 systems causing the users to have to reboot to make them usable. I was a bit at a loss because the "missing" memory wasn't showing up in task manager, but definitely visible when I use sysinternals rammap. There are literally thousands of terminated wmic.exe processes that aren't releasing their memory.


What server version are you running? I recently fixed a bug where I wasn't correctly calling closehandle() on process HANDLEs when spawning a child process.

**Comment by jrdalrymple** [comment]
> 
> 
> 
> What server version are you running? I recently fixed a bug where I wasn't correctly calling closehandle() on process HANDLEs when spawning a child process.

Windows version 0.5.47. So this is a server issue and not a client issue? Certainly I'm happy to upgrade and report back. What version should I be targeting?

Thanks!

**Comment by jrdalrymple** [comment]
Upgrading to 0.7.24 does seem to have fixed this issue for me.
