### ISSUE TITLE
AMT is online but no CIRA connection

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#1926]
In the amtconnection.log the lines look like the following line:

```
{"time":"2020-10-28T19:01:20.350Z","action":"ccmactivate","domain":"","amtUuid":"ea8baead-ca9a-3b8c-ddd7-9e5c43e50b61","amtRealm":"Digest:A00722865C76B553C163AF56369B5D16","user":"admin","password":"J@aGlF+7Uegn","ipport":"213.247.12.211:53927","nodeid":"node//jVHj62gy5o0Y6NS6Kkf8Qv8Ty80QHZ8vAM6M3xunbca4fgfyIaYd$WcZBIEGiTyG","meshid":"mesh//o62nt95tYjpujQJdgHIv8ag35ggeOgvr8bZXTLbD2PNuWS9qZP62oWx0eAMyA$WRu","computerName":"ZBook Dirk"}
```

I'm worried over the part "domain":""; ..... why is that empty?

**Comment by jdvmanen** [comment]
I've corrupted all the uids, realms, passwords and ids above :-)

**Comment by Ylianst** [comment]
Hi. I presume your talking about the "amtactivation.log" file. The empty domain is normal, this is the default domain. It will have a value that is not empty if you setup many MeshCentral domains in the config.json, this is not typical.

For the CIRA connection to connect to your server, the remote computer's Intel AMT needs to be able to connect port 4433 on your server. This is a bit tricky because Intel AMT is under the OS and only have access to some network interfaces and does not have information about HTTP proxies (yet).

I will write a document on Intel AMT and MeshCentral in the coming weeks. For now, you can try connecting the remote computer using the main Ethernet port the computer has if possible. If the computer only has WIFI, I will be documenting this in the coming weeks. You will need to give MeshCentral your WIFI profile so it can setup Intel AMT to connect to WIFI.
