### ISSUE TITLE
NGINX Reverse Proxy

### ISSUE THREAD

**Issue by kikaida** [Ylianst/MeshCentral#1937]
I gotta say MeshCentral is one awesome piece of software. I currently have MeshCentral on an Ubuntu Server 20.04 VM and NGINX reverse proxy running on another VM on the same subnet. For some reason I cannot figure out why NGINX is not forwarding the real ip addresses to MeshCentral. Below are the configs for MeshCentral and NGINX. Any help would be greatly appreciated. Thanks!

```
{
  "settings": {
    "AllowHighQualityDesktop": true,
    "Cert": "mesh.company.com",
    "Minify": 1,
    "MpsTlsOffload": true,
    "Port": 443,
    "RedirPort": 80,
    "SelfUpdate": true,
    "Ignoreagenthashcheck": true,
    "TlsOffload": true
  },
  "domains": {
    "": {
      "certUrl": "mesh.company.com:443",
      "newAccounts": 0
    }
  }
}
```
```
#MeshCentral
server {
       listen 443 ssl http2;
       listen [::]:443 ssl http2;

       root /config/www;
       index index.html index.htm index.php;

       server_name mesh.*;

       include /config/nginx/ssl.conf;

       client_max_body_size 0;
       proxy_send_timeout 330s;
       proxy_read_timeout 330s;

       location / {
               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
               proxy_set_header Host $host;
               proxy_set_header X-Forwarded-Host $host:$server_port;
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header X-Forwarded-Proto $scheme;
               set $upstream_app 192.168.1.6;
               set $upstream_port 443;
               set $upstream_proto http;
               proxy_pass $upstream_proto://$upstream_app:$upstream_port;
       }
}
```

**Comment by Ylianst** [comment]
Hi. You probably already know this, but to help everyone, section 16 of the [MeshCentral User's Guide has a section on NGINX setup](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.9.pdf). In your case the problem is likely your `tlsoffload` line in config.json, change it to this:

```
"tlsoffload": "127.0.0.1"
```

Put 127.0.0.1 or whatever is the private IP address of NGINX. MeshCentral will only consider the "X-Forwarded-Host" header if it comes from the trusted IP address you specify. This is done as a security measure as you don't want to use a fake "X-Forwarded-Host" header. Hope that makes sense.

Ylian

**Comment by kikaida** [comment]
That was it! Thanks Ylianst. I put the private ip of NGINX and started seeing the real ip addresses.

```"tlsoffload": "192.168.1.5"```

**Comment by miroslavjaros** [comment]
> That was it! Thanks Ylianst. I put the private ip of NGINX and started seeing the real ip addresses.
> 
> `"tlsoffload": "192.168.1.5"`

Hello can you share config for Nginx and for Meshcentral. I tried config about Ubuntu server 18.04 but I am not successful.
I would like share setup. 

Thanks Miroslav
