### ISSUE TITLE
Intel AMT MPSCMD Channel_Open_Failure?

### ISSUE THREAD

**Issue by 82280zx** [Ylianst/MeshCentral#1940]
Trying to setup Intel AMT on my stuff here and I'm setting it try to open a channel in tracing but they are failing? Do I need to open ports on firewalls or my router for this to work? It looks like mine is in ACM / Activated mode? I think I did this using Meshcommander? Is there a way to deactivate it so I can try the new feature you have listed here? https://github.com/Ylianst/MeshCentral/issues/1917 . Sorry to keep bugging you!

**Comment by Ylianst** [comment]
So, your not giving me sufficient information to debug the problem. This said, pot 4433 is the default MPS port for Intel AMT. For debugging purposes it also acts as a small HTTPS server. So, from the Intel AMT machine, open a browser to https://server:4433, you will see a cert warning, if you accept it will text indicating Intel AMT should be connecting on this port. This is a easy test to see that the MPS port works.

**Comment by 82280zx** [comment]
> 
> 
> So, your not giving me sufficient information to debug the problem. This said, pot 4433 is the default MPS port for Intel AMT. For debugging purposes it also acts as a small HTTPS server. So, from the Intel AMT machine, open a browser to https://server:4433, you will see a cert warning, if you accept it will text indicating Intel AMT should be connecting on this port. This is a easy test to see that the MPS port works.

I followed your guide here http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf setting it up with NGINX just changed ip / ports to match mine. Doesn't look like it's pulling anything up on that port, ports are all opened and should be forwarded correctly, I'll double check my configs again.

**Comment by 82280zx** [comment]
Ok Now i have the page pulling up but during the trace I'm seeing a CIRA Timeout, it sees my machine, trys to open channels to it but ultimately times out with channel open failure?

**Comment by Ylianst** [comment]
In looking at your trace, I am not sure your realizing this, but this was not a trace of a CIRA connection at all. The MeshAgent is capable of connecting a "CIRA like" connection to the server over websocket, the server then uses this to attempt to connect to Intel AMT thru the agent and thru LMS to configure AMT. In the case of your trace, the server is initiating connections and it's not working, probably because LMS is not running and the MeshAgent's built-in LMS is also not working.

So, to say that again, what your trace is showing is a MeshAgent connection to the server, not a real CIRA connection coming from Intel AMT firmware. A good indication of this is the username is `**MeshAgentApfTunnel**` and the password is a long Base64 time limited cookie. Because Intel AMT CIRA configuration limits the username and password to 16 characters, that password can't be from AMT firmware.

So, not sure what you are trying to do. I will be writing up documentation on MeshCentral and Intel AMT and need to cover these topics in more depth.

**Comment by 82280zx** [comment]
It should have Intel AMT, I have the mesh commander firmware loaded onto it right now, but it’s in ACM mode and is activated? I think I did this using mesh commander, shouldn’t this work with your new automatic AMT configuration? I do remember reading it won’t work if it’s in ACM mode, is there a way I can deactivate / reset my intel amt using mesh commander or do I need to clear it in my bios? I’ll take a screenshot when I get a moment the server is a Dell T40.

Sent from my iPhone

On Nov 3, 2020, at 1:25 AM, Ylian Saint-Hilaire <notifications@github.com> wrote:

﻿

In looking at your trace, I am not sure your realizing this, but this was not a trace of a CIRA connection at all. The MeshAgent is capable of connecting a "CIRA like" connection to the server over websocket, the server then uses this to attempt to connect to Intel AMT thru the agent and thru LMS to configure AMT. In the case of your trace, the server is initiating connections and it's not working, probably because LMS is not running and the MeshAgent's built-in LMS is also not working.

So, to say that again, what your trace is showing is a MeshAgent connection to the server, not a real CIRA connection coming from Intel AMT firmware. A good indication of this is the username is **MeshAgentApfTunnel** and the password is a long Base64 time limited cookie. Because Intel AMT CIRA configuration limits the username and password to 16 characters, that password can't be from AMT firmware.

So, not sure what you are trying to do. I will be writing up documentation on MeshCentral and Intel AMT and need to cover these topics in more depth.

**Comment by 82280zx** [comment]
I think I might have found one area I'm having problems in, I followed your guide here http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf on page 37, the issue I'm having is my NGINX is inside of a container, but the container is stored locally, when nginx starts up I'm gettin certificate errors loading

```
ssl_certificate mpsserver-cert-public.crt;
ssl_certificate_key mpsserver-cert-private.key;
```
I corrected the path I assume it's where you installed it? /home/username/meshcentral-data/ and it's still throwing the error's, I'm still looking into it for now I just comment them out so nginx can start up.

**Comment by Ylianst** [comment]
Update to the latest MeshCentral and try again. I did some fixed in the last week that should make the MeshAgent built-in LMS work now. On the Intel AMT computer, try accessing "http://127.0.0.1:16992" in the browser, if you see the Intel AMT page, the LMS is working. If it's not, update MeshCentral and try again.

**Comment by 82280zx** [comment]
Awesome that did it! Thank you!

**Comment by Ylianst** [comment]
Nice!!! Thanks for reporting back.
