### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#1952]
Ylianst, I would like to support you're great job in another way than adding useful ideas onto your 'todo-list' 😀. Is there a way I can donate your work via paypal or so?

I (and probably others) would love to buy you a pizza or cup of coffee now and then.

**Comment by Ylianst** [comment]
Thanks for the issue report 👍 We are doing just fine and not taking any donations. Bryan and I work for a large company that sells computers with built-in hardware management (Intel AMT) and MeshCentral supports this technology so that is out sponsoring angle. This said, I am quick to note that MeshCentral is a open source community project not official supported by any company and anyone can contribute code, ideas, translation, etc. Thank for the feedback, it's super appreciated.
