### ISSUE TITLE
I don't have the web server backup and copy options

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#1956]
Hello, I have updated the application to version 0.6.78 but I have noticed that now I do not have the server copy and backup options from the web manager. This is normal?

**Comment by Ylianst** [comment]
This has been a frequent question. The backup and restore options in the "My Server" tab are only available when using NeDB. If you switch to using MongoDB, these options are no longer present. This is because these options never backed up the database with MongoDB and so, would give a sense that you did a compete backup when you did not. So, false sense of security.

You can still pull the daily backup from "meshcentral-backups" folder, these include the MongoDB dump. You can also use the WebDAV or Google Drive auto-backup options to auto-push backups offsite.

Hope that helps,
Ylian

**Comment by desarrollocdb** [comment]
Indeed it is what has happened. Thank you! Happy week
