### ISSUE TITLE
Add support for alt-tabbing and Shift+Del on the remote desktop

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#196]
At the moment, when you try to Alt-Tab on the remote desktop, you end up switching windows on your local machine instead. When you press Shift+Del, the Shift is ignored and only the Del key is processed. It would be cool if both of those actions could be forwarded to the remote desktop.

**Comment by Ylianst** [comment]
There are limitations because the Web Application is in the browser, but I will check what is possible or provide an alternative.

**Comment by UnP1u9** [comment]
When we Alt+Tab on the remote desktop, it seems to break some settings and we are unable to type in remote desktop. Reconnecting is required to make it work again.

**Comment by Ylianst** [comment]
I don't think I get intercept ALT-TAB, but I just added it to the list of special keys in the remote desktop drop down. That seems to work. Added in MeshCentral v0.3.5-v.

![MC2-AltTab](https://user-images.githubusercontent.com/1319013/58738934-b24d2000-83bc-11e9-9828-9badf53ba0ae.png)

**Comment by MailYouLater** [comment]
I'd like to suggest that <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Tab</kbd> be added to the list too.

<kbd>Alt</kbd>+<kbd>Tab</kbd> directly switches to the next window listed in the task switcher (because <kbd>Alt</kbd> gets released without giving the option to press tab a few more times to choose a window) whereas <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Tab</kbd> leaves the task switcher UI open, allowing the user to select which window to switch to with their mouse.

**Comment by MailYouLater** [comment]
Regarding the second issue (<kbd>Shift</kbd>+<kbd>Del</kbd> not working correctly), it looks like that's going to be addressed in issue #169.

**Comment by Ylianst** [comment]
Good idea, I will add Ctrl+Alt+Tab. However, the shift, ctrl and alt keys work for me. What browser is being used? I just tested Shift + Del and I can force delete a file correctly on FireFox.

**Comment by MailYouLater** [comment]
`<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Tab</kbd>`

My comment about <kbd>Shift</kbd>+<kbd>Del</kbd> was simply to point out to anyone who comes here with that issue, that that's actually a separate issue, and it should be discussed in issue #169, where that issue is being discussed, not here.

**Comment by UnP1u9** [comment]
Hi, My issue still exists, if i take remote access to a machine and press Alt+tab on my machine, it send Alt Key to the remote machine so if i press any key in remote machine it behaves like i have pressed Alt key, like if i press F it behaves like Alt+F.  😵

**Comment by MailYouLater** [comment]
@UnP1u9: That's a different problem than what this issue is about.  I recommend that you open a new issue describing your issue, and title it something like "Alt gets stuck after Alt+Tab during remote access".

This issue is about adding <kbd>Alt</kbd>+<kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Del</kbd> to the send keys menu.

At this point <kbd>Alt</kbd>+<kbd>Tab</kbd> has been added, but <kbd>Shift</kbd>+<kbd>Del</kbd> has not.  It would be nice if either #169 could be fixed, or <kbd>Shift</kbd>+<kbd>Del</kbd> could be added too.

Thank you.

**Comment by MailYouLater** [comment]
Just an update since #330 is fixed.  <kbd>Shift</kbd>+<kbd>Del</kbd> still doesn't work for me.
