### ISSUE TITLE
RPi4-Desktop Mode blank screen on Raspbian GNU/Linux 10 (Buster)

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1973]
Hi MeshCentral team,

So this issue seems to have cropped up since last stable release. Only security updates have been done to the device. What is happening is the user starts a Desktop session, and only sees a connected status, the count down of time, and then the black screen. However same is seen again on another RPi4 device. So could this be configuration of the desktop or issue with how MeshAgent is handling the screen population control?

Thanks,
SomeGuru

**Comment by SomeGuru** [comment]
Issue seen on 0.6.80 and 0.6.83, but not see similarly on 0.5.81.

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.84, let me know if that fixes it.

**Comment by laboiteajb** [comment]
Hello

I have a similar problem since the last update with my PI4

The remote desktop works for a few minutes then after the image freezes
http://e.pc.cd/l6botalK
(at 1"10)

if I reconnect, I have a black screen.
http://e.pc.cd/TtbotalK

Restarting the PI4 solves the problem
Restarting the x11 service solves the problem (systemctl restart display-manager)
Restarting the merch service does not solve the problem
