### ISSUE TITLE
Computers Disconnected from Console, 0.6.8.6

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1985]
Guys, this is going to sound like a complaint...apologies... thought I'd toss this in.  Apologies if this was previously discussed.  I remember some comment from the MC Team about increasing the reliability of the agent, with some auto updater, assistant thing, but not sure where that stands.  So not sure how that plays in here or not.

1.  We have regular issues with agents and connecting or disconnecting.  In this case we have a computer (Allied-BD).  It's clearly online as I can connect to it remotely in our other RMM, and the agent is showing running, but the computer is disconnected.  If I reinstall mesh agent it works again, but this seems to repeatedly happen. (see screen)  Why is this? (see screen)

2.  Regularly, for some reason, we get duplicate computers and one is greyed out and the other is showing online, so we're constantly going to delete the old one.  Is there any way we can stabilize these two issues? 

![image](https://user-images.githubusercontent.com/45638572/99092984-e7910200-259f-11eb-9bb9-c8380ef646e5.png)
![image](https://user-images.githubusercontent.com/45638572/99093189-27f08000-25a0-11eb-86ad-d3297e246655.png)

**Comment by krayon007** [comment]
By any chance is this agent running windows 7 SP1?

**Comment by southeasterntech** [comment]
hmmm close 2008 R2

**Comment by krayon007** [comment]
Perfect, Windows Server 2008 R2 and Windows 7 SP1 are actually both covered by this:

I found the issue was because I found one of the flags I was using in a win32 system call was not supported on this version of windows, unless a particular MSFT security patch was installed (KB2533623). Here is a [link](https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot) to the patch.

What the issue is that is causing this, is that I was using LoadLibraryEx, specifying to only look in system32. I was doing this so I could check if GetTickCount64 was supported. I did this, becuase originally we supported Windows XP, which did not support GetTickCount64().  I used the flag 'LOAD_LIBRARY_SEARCH_SYSTEM32' to prevent dll hijack vulnerabilities by only using sytem32, but this flag is not supported on Windows 7 SP1 or Windows Server 2008 R2 without this patch. 

You can either install the patch mentioned above, or you can update the server to the latest, as I updated the agent to not use LoadLibrary for GetTickCount64(), becuase we actually don't support Windows XP anymore (for other reasons), so that made this method call unnecessary.

GetTickCount64() is used in our timers, which is in turn used by things such as setting timeouts and such... So with this issue, on Windows 7 SP1 / Windows Server 2008 R2, it made it so our timeout logic failed, causing 2 conditions:

1. Timeouts would never trigger, which made it so things such as Keep Alives are never sent, making the agent periodically disconnect
2. Timeout values were always set to 0, causing the main execution thread to always think it has work to do, which would cause it to spin, resulting in the CPU going to 100% if a failed timeout was set, until it is cleared.

**Comment by southeasterntech** [comment]
hmmm.. unfortunately this patch is no longer avail
![image](https://user-images.githubusercontent.com/45638572/99098579-2d04fd80-25a7-11eb-8087-c788915a4e88.png)

**Comment by Ylianst** [comment]
As indicated by Bryan, you can update the MeshCentral server to 0.6.86 or 0.6.87 to fix this problem. Once you update the server, the MeshAgent will get updated to a new version that fixes this.
