### ISSUE TITLE
-nodeidhex flag in latest agent binary broken

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#1998]
Hi so it seems any version starting with 0.6.85 which is when the agent binaries were updated (not sure how to check agent version but the build date on the digital cert is Nov 10, 0.6.84 and before the date is Oct 20), the registry entry on windows agent where mesh stores stuff changed from `HKLM\SOFTWARE\Open Source\MeshAgent2` to `HKLM\SOFTWARE\Open Source\Mesh Agent` but looks like the code here https://github.com/Ylianst/MeshAgent/blob/5ae400231dadc63157054b0d96172a6bfaa48a50/meshservice/ServiceMain.c#L784
is still trying to get info from the older reg entry, which on a new install is empty. 

So calling the new agent on a fresh install with `-nodeidhex` flag gives error `"Not defined, start the mesh service to create a nodeid."`

Also seems uninstalling the agent doesn't cleanup the registry and leaves both keys and all their values, I noticed this because I use the `-nodeidhex` flag from the agent to get the id to pass to an iframe for embedding meshcentral, and after updating the iframe was blank cuz wrong nodeid, so I opened mongodb console and checked agents nodeid, and nodeid was different from that in the `MeshAgent2` registry key, and since that key still existed because it wasn't cleaned up by the uninstaller or during the agent update, i was not getting any errors calling the `-nodeidhex` flag but it was getting the old id rather than the correct one from the new `Mesh Agent` registry key

Anyway not a huge deal just wanted to know if going forward the nodeid will be stored in `Mesh Agent` instead of `MeshAgent2` registry key if so i'll just check the `NodeId` string value in case the `-nodeidhex` flag doesn't work. Got some screenshots below of a fresh install of the agent from 0.6.85, seems it still creates the old `MeshAgent2` key even tho nothing stored there.

![reg2](https://user-images.githubusercontent.com/7434746/99488472-d2f49700-291c-11eb-8fca-79107ed11027.PNG)

![reg1](https://user-images.githubusercontent.com/7434746/99488538-d720b480-291c-11eb-8ab5-11ac23a80054.PNG)

**Comment by krayon007** [comment]
Instead of using -nodeidhex, try -nodeid
Is this value sufficient? I was trying to deprecate -nodeidhex because it was problematic, which is why I added -nodeid a long time ago. (-nodeid also works on all platforms)

The reason why the registry key changed tho, was we are adding support for concurrent installations of the agent, so that you can install multiple agents with different configurations. That's why the registry key was changed.. "MeshAgent2" isn't bound to anything, we just added a "2" to the Mesh1 version.... The registry  key is now actually tied to the service name on windows. So whatever the agent's service name is, is what the key is... (You can fetch the service name, with the -name parameter)

If the format of the output is different, I can modify -nodeidhex to just call -nodeid, and transform the output if necessary.

**Comment by krayon007** [comment]
On a side node, if you use the -info parameter, it will tell you the Agent's build date/time, the commit hash it was built from, and the commit date/time, among other things...

**Comment by wh1te909** [comment]
@krayon007 perfect thanks, I did actually try `-nodeid` but since it was not matching what was showing up in mongodb for the agent's nodeid (which is what shows up in the url) i assumed it would not work, but just tried it and it appears to convert it to the hex form or whatever on the fly and the iframe loads. The flag doesn't matter for me I will just upgrade my wrapper to called nodeid instead of nodeidhex. thank you!
