### ISSUE TITLE
Remote desktop on smartphones

### ISSUE THREAD

**Issue by FilGov** [Ylianst/MeshCentral#2005]
The remote desktop functionality on MeshCentral.com is virtually unusable on smartphones (small remote display/screen, can't maximize, can't scroll, can't write (keyboard doesn't work), no mouse cursor/pointer). Any chance this can be improved? Would greatly appreciate. Thank you.

**Comment by PathfinderNetworks** [comment]
Agreed, I would LOVE to see improvements made here- even if just so that the phone (I use Android myself) keyboard would be presented as an input option so I can type in logon passwords, etc in to the remote device.  if I just had that one option it would dramatically improve how I can use MeshCentral.

**Comment by SomeGuru** [comment]
I am able to use the system once I switch my browser over to desktop mode... It pops my VK right up... I can then login with the phone and use all those functions... at least it works this way on Android currently for me...

**Comment by FilGov** [comment]
I am not. All listed issues persist in desktop mode. Also using Android.

**Comment by Ylianst** [comment]
I am working on something to solve this. More news later this week.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.0 with an improved mobile application. Corrected a few things, but most importantly, there is a new remote desktop viewer that allows pretty good remote desktop control of a remote device. Hit the new "Full Screen" button and take a look. Feedback appreciated.

![MC2-MobileDesktop1](https://user-images.githubusercontent.com/1319013/100037924-ed64bf80-2db7-11eb-914c-22e8810fc95a.png)
![MC2-MobileDesktop2](https://user-images.githubusercontent.com/1319013/100037935-ef2e8300-2db7-11eb-8d1b-459f903ba84e.png)
![MC2-MobileDesktop3](https://user-images.githubusercontent.com/1319013/100037941-f0f84680-2db7-11eb-89e1-853ff2704846.png)

**Comment by PathfinderNetworks** [comment]
Thank you!  I just updated to 0.7.0 to try this out.  Such a huge improvement!  Being able to send the key macros is a very nice, very helpful touch.  Total game changer!  
Not to look a gift horse in the mouth, but is there any way to make the full screen option use pinch to zoom of most smartphones so that we can adjust the scale of the display?  Definitely not something that is a must have- but it would make it easier to be able to scale the full screen view to a point where we can see more of the remote desktop as needed (such as when I'd like to see the contents of a window- such as say a command prompt window).  
Even if that isn't an option this is still a revolutionary change for how I will be able to use MeshCentral!  It's like Christmas has come a month early.

**Comment by petervanv** [comment]
superb update, thx Ylian

**Comment by FilGov** [comment]
I find no app in the Google Play Store and notice no difference on MeshCentral.com, everything's the same, all issues persist. Am I doing something wrong?

**Comment by Ylianst** [comment]
MeshCentral.com is currently running v0.6.70. It lags behind the latest version of MeshCentral by about a month or sometimes more. Discussions here is mostly for the latest version.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.1 with bug fixes including a fix for iOS devices. I added a new zoom button on the mobile desktop viewer. I am not sure I can do a good job with pinch-to-zoom on a web application, but hopefully this will be ok. Let me know how if it works.

![MC2-MobileDesktop2](https://user-images.githubusercontent.com/1319013/100084691-ea8dbd00-2dff-11eb-8934-f7086edf4faa.png)

**Comment by FilGov** [comment]
> @FilGov MeshCentral.com is currently running v0.6.70. It lags behind the latest version of MeshCentral by about a month or sometimes more. Discussions here is mostly for the latest version.

Oh, OK, was confused because the issues reported here were for MeshCentral.com. As long as these fixes/improvements are eventually implemented there, I'm satisfied. Looking forward to it. Thank you very much.

**Comment by PathfinderNetworks** [comment]
Thanks Ylian, I just updated to 0.7.1 and the zoom option you added is a very big improvement.  Definitely works for me as I can use it to quickly bounce back and forth between full screen and zoomed in as needed.

**Comment by Ylianst** [comment]
Thanks. Yes, it turned out pretty good. This is going to be useful.

**Comment by Ylianst** [comment]
Ok, closing this one. If there are any issue related to this, please open a use GitHub issue.
