### ISSUE TITLE
Groups duplication and unable to delete

### ISSUE THREAD

**Issue by treicadani** [Ylianst/MeshCentral#2007]
Hi Ylian,

In Mesh central version 0.6.98 it seems I am able to create same group name infinite times and unable to delete, i click the delete group button but nothing happens.

![image](https://user-images.githubusercontent.com/16573983/99875140-3ca6c680-2be5-11eb-9350-8672a7e3f415.png)

![image](https://user-images.githubusercontent.com/16573983/99875176-7c6dae00-2be5-11eb-9a80-b339f6385c01.png)

**Comment by Ylianst** [comment]
So, having multiple device groups with the same name is allowed. You can click on one of the device group and change it's name and different users can create different device groups with the same name on the server. Device groups are identified using a unique identifier value internally. Of course, for users, it's probably best not to name all the groups the same.

For deleting a device group, that should work. I just tried it and it works for me. Can you indicate the *exact* steps and any information that would be needed so that I can reproduce the problem on my computers? Thanks.

**Comment by treicadani** [comment]
Okay, so I've been testing 0.7.10 and it seems all groups works to delete, and also the other issue i had with missing groups / machines seems to be resolved.
