### ISSUE TITLE
CIRA / AMT Troubleshooting Guide

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#2019]
Hello,
Is there any troubleshooting guide for CIRA/AMT issues? I haven't been able to get AMT to work with MeshCentral - although it is activated and working with a PC on LAN using MeshCommander.

I've tried 3 PCs in 3 physical separate locations and suspect the issue is on the server side. I'm using the fully automatic connection method in ACM mode (manually turned on ACM in BIOS a long time ago) and everything in the portal says OK, but it won't connect.

Latest Mesh, no reverse proxy in the way. The URL https://mesh.domain.tld:4433/ does load and displays 

MeshCentral MPS server.
Intel® AMT computers should connect here.

The cert on this URL is MeshCentralRoot-xxxxxx and not my standard cert.

**Comment by mfroeh103** [comment]
I was working on this exact issue yesterday. Are you able to see this screenshot? I had to change to simple admin control mode and made sure Cira was set to connect to server. As soon as I changed that Cira setting, the acm enabled devices connected. 
![Screenshot_20201126-111222~2](https://user-images.githubusercontent.com/53836896/100378429-b15c7500-2fd8-11eb-86e0-6b32a500068c.png)

**Comment by MordyT** [comment]
I just make the changes shown and waited about 5 minutes, but still no connection.

**Comment by Ylianst** [comment]
I do need to create a Intel AMT guide, this is high up on my todo list. In any case...

- Intel AMT only have access to the one Ethernet wired interface and one WIFI network interface. So, if you connect the computer using a USB Ethernet or something, Intel AMT will not be able to use that interface to connect back.
- The non-standard certificate on port 4433 is correct. When setting up Intel AMT, the root of the certificate will be loaded into AMT and so, it should accept it. This is also good because you don't want to be rotating that certificate every 60 days, then may need to update the configuration of all the AMT devices each time that happens. The non-standard cert is good until 2049.
- Good that you did the test of connecting to port 4433. That port is a binary port, but I did add code to detect a HTTP request and respond exactly so you can do this test. Seems like it works for you.
- In the agent console, type "amtevents", this shows you the last AMT configuration events the server performed on this device. You can also type "amtconfig", that will force the server to take a look at your AMT device and make sure it's configured correctly.
- One thing to check. When you use a browser to connect to https://server.domain.com:4433, does the certificate you get has the common name also set to "server.domain.com"? One possible issue would be that Intel AMT CIRA is trying to connect to DNS name X but sees Y in the certificate common name.
- In the "Intel AMT" tab of the device, you can connect and go in the "Internet Settings" to see the settings that are in Intel AMT. You could take a screen shot of that (blank out any server name) and post this here. At least see if the server name is correct.

Ylian

**Comment by MordyT** [comment]
@Ylianst 
1 - Using the onboard NIC. From Commander: 
![image](https://user-images.githubusercontent.com/779947/100391952-b16d6c80-2ffa-11eb-9bfc-6c23226927ea.png)
2 - Understood
3 - Glad to hear it is working correctly
4 - ![image](https://user-images.githubusercontent.com/779947/100391800-4a4fb800-2ffa-11eb-8309-2a3d0dc08ec6.png)
5 - In the SAN section of the cert it does have the FQDN of the server
6 - That page says disconnected and won't let me hit connect. But with MeshCommander I grabbed this:
![image](https://user-images.githubusercontent.com/779947/100392198-6142da00-2ffb-11eb-8c48-a434090e4fc8.png)
I had thought in the past I saw server info there...
![image](https://user-images.githubusercontent.com/779947/100392219-6f90f600-2ffb-11eb-8733-71edd8c1c391.png)
and certs here?

**Comment by jsastriawan** [comment]
Your CIRA setup doesn't exist over there. It should have entry for the CIRA server, trigger and environment detection set.

**Comment by MordyT** [comment]
Right, but in automatic or even the simple mode, shouldn't the agent place all the settings there?

**Comment by mschubeck** [comment]
+1 request for the AMT guide.  I have a lot of AMT/vPRO-enabled machines, both in-house and at clients, and I really don't know how to configure either them or MeshCentral to take advantage of these capabilities.  Currently, all AMT is configured manually on each machine and we're using the browser-based GUI (port 16992) for changes to those machines when needed.
