### ISSUE TITLE
Machine configuration for 10k nodes

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#2037]
is there any hardware spec for 10k nodes

**Comment by Ylianst** [comment]
Make sure to use MongoDB as you database, not NeDB which is the default when you start. For hardware spec, [https://MeshCentral.com](https://meshcentral.com) runs on Amazon AWS on a t3.medium instance (4G ram, 2 virtual CPU's) with Amazon Linux 2 as the OS and can handle more than 14k+ devices. This instance will run you about 30$/mo US, on top of that you will pay some extra for traffic charges.

Let me know if that helps,
Ylian

**Comment by aimdharma1990** [comment]
> Make sure to use MongoDB as you database, not NeDB which is the default when you start. For hardware spec, [https://MeshCentral.com](https://meshcentral.com) runs on Amazon AWS on a t3.medium instance (4G ram, 2 virtual CPU's) with Amazon Linux 2 as the OS and can handle more than 14k devices. This instance will run you about 30$/mo US, on top of that you will pay some extra for traffic charges.
> 
> Let me know if that helps,
> Ylian

Do we have any data for bandwidth consumption for the Ideal mesh agent?

**Comment by Ylianst** [comment]
I do not, agents will stay connected to the server by will use very little bandwidth. This is important since people have been using MeshCentral over 3G/4G connections and so, agent idle traffic must be kept to a minimum. By far the most traffic you get will be for remote desktop, file transfers and TCP relays from yourself or your users and I don't know what that is. If you are concerned with traffic, add these lines to the settings section of your config.json:

```
"compression": true,
"wscompression": true
"agentwscompression": true
```

This will turn on web socket DEFLATE compression and attempt to compress traffic. I am guessing this will save you 5% to 15% in traffic costs. It does make the server work harder, but even to 10k+ connections, my small servers CPU's are mostly idle anyway.

You can also try this in the settings section of config.json:

```
"allowHighQualityDesktop": false
```

It will limit the quality of the remote desktop sessions and safe you traffic costs.

In the future, we need to work to re-enable WebRTC to allow direct browser-to-agent traffic. When possible, traffic does not go thru the server and so, you avoid the cost completely.

Hope that helps,
Ylian
