### ISSUE TITLE
Servers with Lag issues on multiple and various size groups.

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#2046]
Hi YlainSt,

Can you review the way the polling/fetching takes place, as it seems that when a user with a majority of over 200 plus groups of unit sizes from 1 connection to 100's of connections in the groups... This seems to cause lag on my current server.

Thank you,
SomeGuru

**Comment by Ylianst** [comment]
I need to work on doing the same trick I did with the mobile app and only render the devices that are visible on-screen. This allows a much larger amount of devices to the displayed and scrolling is fast. I also need to work on making it so that if a device changes state, only that device is updates instead of the entire list being refreshed.

**Comment by Ylianst** [comment]
Working on this. It should allows the main web page to handle a lot more devices a lot faster.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.13 with significant changes to how the devices are rendered on the MeshCentral web application. It should result in significant performance improvements when dealing with large amounts of devices. Please try it and let me know if it works.
