### ISSUE TITLE
Agents gets disconnected and reconnected about every minute.

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#2050]
After the upgrade to v0.7.x I see all the agents (windows, MacOS) disconnecting and reconnecting about every minute. When you have a notification enabled to inform agent connects/disconnects, you getting spammed of the notifications.

When I have a remote desktop session active, then it took a few minutes to loose the session.

The reverse proxy is configured to have the connections open for much longer than the minute. Before v0.7.x I did not had this issue.

In the server trace with MeshAgent traffic and update options enabled, I see the following (IP addresses removed):
```
11:07:42 AM - AGENT: Verified agent connection to 46m@$ocsVXgGQwvUXbZUpVD5FHb0IG5SmsIQAiMxAB9OpJb05iksEPolAyv3lBPY (XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:33798).
11:07:41 AM - AGENT: New agent at XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:33798
11:07:41 AM - AGENT: Agent disconnect 46m@$ocsVXgGQwvUXbZUpVD5FHb0IG5SmsIQAiMxAB9OpJb05iksEPolAyv3lBPY (XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:60854) id=4
11:07:35 AM - AGENT: Verified agent connection to uZXsJmvKlZdJoq@WEfqHY3p6MkfvUOkX4rXcJXHPXwMOyIOqT9QUboi61Ja07FMi (XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:33656).
11:07:34 AM - AGENT: New agent at XXXX:XXXX:XXXX:XXXX:ad02:b370:5606:1391:33656
11:07:34 AM - AGENT: Agent disconnect uZXsJmvKlZdJoq@WEfqHY3p6MkfvUOkX4rXcJXHPXwMOyIOqT9QUboi61Ja07FMi (XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:60832) id=4
11:07:27 AM - AGENT: Verified agent connection to Xm1i5YabnwvE0LWTpnIpXcljuEVkV@Jx@isf$22@vqbudO3jw2l3HBDBor658Pz9 (XXX.XXX.XXX.XXX:33540).
11:07:26 AM - AGENT: New agent at XXX.XXX.XXX.XXX:33540
11:07:26 AM - AGENT: Agent disconnect Xm1i5YabnwvE0LWTpnIpXcljuEVkV@Jx@isf$22@vqbudO3jw2l3HBDBor658Pz9 (XXX.XXX.XXX.XXX:60688) id=4
11:07:00 AM - AGENT: Verified agent connection to QH85APQ6PHF2cphcWaaYfZFvUql7R$ruLthsKHWKEs0TzduRcbHngNrhSg52eODY (XXXX:XXXX:XXXX:XXXX::XXXX:33064).
11:06:59 AM - AGENT: New agent at XXXX:XXXX:XXXX:XXXX::XXXX:33064
11:06:59 AM - AGENT: Agent disconnect QH85APQ6PHF2cphcWaaYfZFvUql7R$ruLthsKHWKEs0TzduRcbHngNrhSg52eODY (XXXX:XXXX:XXXX:XXXX::XXXX:60226) id=4
11:06:36 AM - AGENT: Verified agent connection to 46m@$ocsVXgGQwvUXbZUpVD5FHb0IG5SmsIQAiMxAB9OpJb05iksEPolAyv3lBPY (XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:60854).
11:06:34 AM - AGENT: New agent at XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:60854
11:06:34 AM - AGENT: Verified agent connection to uZXsJmvKlZdJoq@WEfqHY3p6MkfvUOkX4rXcJXHPXwMOyIOqT9QUboi61Ja07FMi (XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:60832).
11:06:32 AM - AGENT: New agent at XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:60832
11:06:32 AM - AGENT: Agent disconnect uZXsJmvKlZdJoq@WEfqHY3p6MkfvUOkX4rXcJXHPXwMOyIOqT9QUboi61Ja07FMi (XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:59708) id=4
11:06:26 AM - AGENT: Verified agent connection to Xm1i5YabnwvE0LWTpnIpXcljuEVkV@Jx@isf$22@vqbudO3jw2l3HBDBor658Pz9 (XXX.XXX.XXX.XXX:60688).
11:06:25 AM - AGENT: New agent at XXX.XXX.XXX.XXX:60688
11:06:24 AM - AGENT: Agent disconnect Xm1i5YabnwvE0LWTpnIpXcljuEVkV@Jx@isf$22@vqbudO3jw2l3HBDBor658Pz9 (XXX.XXX.XXX.XXX:59596) id=4
11:06:20 AM - AGENT: Agent disconnect 46m@$ocsVXgGQwvUXbZUpVD5FHb0IG5SmsIQAiMxAB9OpJb05iksEPolAyv3lBPY (XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:58986) id=4
11:05:59 AM - AGENT: Verified agent connection to QH85APQ6PHF2cphcWaaYfZFvUql7R$ruLthsKHWKEs0TzduRcbHngNrhSg52eODY (XXXX:XXXX:XXXX:XXXX::XXXX:60226).
11:05:59 AM - AGENT: New agent at XXXX:XXXX:XXXX:XXXX::XXXX:60226
11:05:59 AM - AGENT: Agent disconnect QH85APQ6PHF2cphcWaaYfZFvUql7R$ruLthsKHWKEs0TzduRcbHngNrhSg52eODY (XXXX:XXXX:XXXX:XXXX::XXXX:59160) id=4
```

**Comment by Ylianst** [comment]
Hi. This generally happens because there is something in front of the server (HTTP Proxy or Reverse Proxy) that has a 1 minute idle timeout and will disconnect the connection. One way to fix this is to add the following line in the settings section of the config.json file:

```
"agentpong" : 55
```

This will cause the server to send data to the agent every 55 seconds. You can replace "agentpong" with "agentping" if you also want the agent to respond to the ping request with a pong. That will generate traffic in both directions every 55 seconds.

This said, the better way to fix this is to find what is causing the idle disconnection and fix it. If you are running MeshCentral behind a reverse proxy like NGINX, you should change the configuration of the reverse proxy to allow to very long idle connections. If you take a look at section 16 of the [MeshCentral User's Guide]([url](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.9.pdf)), you can see an example of the NGINX configuration with lines like this:

```
proxy_send_timeout 330s;
proxy_read_timeout 330s;
```

Sometimes however, if the agent is behind a HTTP proxy you can't control the best you can do is "agentpong". Hope that helps.

**Comment by hunter-nl** [comment]
Thank you for your information. I will try with the agentping option.
