### ISSUE TITLE
Mesh agent did not come back only after update

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2059]
Unfortunately I do not have any more information than below. (no crashdump)
This is an Windows 7 Home Premium system, running in an isolated network.

After updating mesh last night some agents did not come back online.
I was able to restart an agent by hand and it downloaded and installed fine that time.

The other agent (64 bit) was not able to get back online.
Tried to start meshagent by hand and click update... 
Tried to download a fresh installer and install .. still nothing.
Tried with the commandline for debugging, the service error is my mistake. Had the services window open.
The fatal error was unexpected.. 
Tried the 32bit version, which installed fine.
Also the agent is now installed in the Download folder.. geuess because of the cmd install

![image](https://user-images.githubusercontent.com/55733884/101647859-85f67300-3a39-11eb-939a-2d003455d834.png)

Is there a way to further debug this?

**Comment by krayon007** [comment]
Well, the first thing is, that you should be using the `-fullinstall` switch, not the `-install` switch. The former does a full install into the Program Files folder. The latter does a minimal install into the current location.  I'll run some tests to see what exactly happens when you try to run -install from a different location then where it's already installed.

**Comment by Allowee** [comment]
Tried the -fulllinstall just now. The 64bit agent install in the Downloads folder just fine.
Not in the program files folder.

Will try a fresh install when  get back on-site.
Still not sure why the 64bit would not install in the first place.
Closing for now
