### ISSUE TITLE
Android agent

### ISSUE THREAD

**Issue by Patriciawa** [Ylianst/MeshCentral#209]
I've seen some video denonstrating the mesh agent on Android. But cant seem to find the option in Meshcentral2. Is there a mesh agent for Android?

**Comment by Ylianst** [comment]
Here is currently no Android agent for MeshCentral2 and no developers around to built one, so no plans in the near term for a Android agent right now. This reminds me that I have to go clean up [my YouTube channel](https://www.youtube.com/channel/UC2B142NLMQwACfTRxrHoYTQ) and remove all MeshCentral1 videos.

**Comment by Patriciawa** [comment]
Jup, I was confused since I saw in those videos that there was actually a Android agent, but figured out it was probably deprecated.

**Comment by Ylianst** [comment]
Correct. However, I just cleaned up the [YouTube channel](https://www.youtube.com/user/AAlliieennX/videos). Removed the older MeshCentral1 videos.

**Comment by Ilia1** [comment]
https://github.com/LukeCarrier/android-governor 
This application has not been updated for a long time, will it work on a new smartphone? Can it be used as a basis for an android agent?

**Comment by krayon007** [comment]
Not really. The core of the mesh2 agent is an JavaScript runtime engine. Getting that to work probably wouldn't be that difficult, since it's mostly linux. The pain, is the other features like KVM and terminal. The main reason Android development on the old mesh agent stopped, was due to API changes in Android. The way we implemented KVM was explicitly blocked by Google starting in Lollipop. Google came out with new official APIs, but remote injection was explicitly not allowed. At the same time they became more strict about background network connections. I looked into switching to using push notifications to trigger actions on Android, but because KVM wasn't supported, our main use case for Android was not in play.

**Comment by MailYouLater** [comment]
As @ryanblenis [mentioned](https://github.com/Ylianst/MeshCentral/issues/854#issuecomment-577682778), there's a new beta of Tasker which [apparently](https://www.xda-developers.com/tasker-5-9-2-beta-run-adb-shell-commands-without-tethered-pc/) has the ability to issue `adb` commands to the device it's running on.  The idea they're using seems pretty simple, so I wonder how feasible it would be to make a Mesh Agent for Android that uses this idea too.  This trick could possibly be used to either give the agent permissions to things that may otherwise be blocked, or perhaps even to do some things that may otherwise not be possible.

**Comment by krayon007** [comment]
One thing I've done in the past, is create a portmap for the adb port on my phone thru mesh, then I was able to use an adb client/debugger on my PC and connect it to my phone thru a mesh tunnel. If you did something like this, you wouldn't need to install tasker on the phone, you can do everything from the server.

**Comment by MailYouLater** [comment]
That's pretty much exactly what tasker is doing, just on the phone itself, so I thought the Android Mesh Agent could too, though after a little more research, it looks like KVM is probably doable without requiring adb, so while it could still prove useful, it may not be needed.

**Comment by krayon007** [comment]
I only mentioned doing it server side, because a lot of the IT departments I work with explicitly prohibit tasker being installed on their assets.

As far as the KVM, remote display is possible, but remote input requires OEM support, because it was disallowed by Google. The current KVM solutions I've seen on the market for Android newer than Jellybean, requires driver support from the specific OEM, making it phone/model specific.

**Comment by MailYouLater** [comment]
> I only mentioned doing it server side, because a lot of the IT departments I work with explicitly prohibit tasker being installed on their assets.

I was never suggesting installing Tasker, but rather copying their method of sending adb commands to the device from an app on the same device, in this case it would be the Mesh Agent app that sends these commands.

> As far as the KVM, remote display is possible, but remote input requires OEM support, because it was disallowed by Google. The current KVM solutions I've seen on the market for Android newer than Jellybean, requires driver support from the specific OEM, making it phone/model specific.

Ah yes, sorry.  That's why I was thinking that adb could be useful.  It can be used to send simulated touch events without OEM specific drivers.
