### ISSUE TITLE
Re-enabling the progress bar dialog for file downloads

### ISSUE THREAD

**Issue by Trivalse** [Ylianst/MeshCentral#2091]
Hi, workaround that fixed #1865 caused the progress bar for file downloads to no longer show up. I'm using MeshCentral (v0.6.97) embedded in a webpage, and it was relying on the original download functions (p13downloadfile, p13gotDownloadBinaryData, etc) to implement its own progress bar.

I found that using "p13downloadfile()" no longer causes the issue in #1865, but instead it causes binary files to get corrupted after download. However, downloaded ASCII files (e.g. *.txt) are unaffected.

Are there any plans to return to use the original file download functions? I could probably lend a hand to fix this if anyone could point me in the right direction.

**Comment by Ylianst** [comment]
Hi. So, not sure about #1865, but the original download system would download the file data to the browser and use a [FileSaver.js](https://github.com/eligrey/FileSaver.js/) to save downloaded data to a file. The problem with this technique is that there is a limit to how big the saved file can be. For very large files, this technique does not work.

The new system performs a HTTP download to the server and the server turns around and does the work of getting the data from the agent and streaming it back to the browser. To the browser, this looks like a normal file download from a HTTPS server. In this case, the progress bar should be displayed by the browser as the server is transferring the file. The web page does not display the progress bar.

I did keep the original code in because if we get WebRTC working again, I would use the original method on smaller files and use the P2P connection to perform the transfer to off-load the server. Other than that, I have no plans on using the old system.

Both systems should work perfectly with both text and binary files. I can't reproduce your issue with the information you provided and so, not something I can look at. If you have more precise info on steps to replicate, let me know.

**Comment by Trivalse** [comment]
Hi, thanks for your response. I think I'm fine with the HTTP download system as you explained. The bug might be due to my own changes as well, and thus I'll close this issue.
