### ISSUE TITLE
Backup error

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#2113]
I am running on MC2(0.7.3.1) on Debian jessie and recently moved to from NeDB to MongoDB.
All agents are back up and running, all is looking fine, but now when type 'systemctl status meshcentral' have this error:

`Dec 27 06:26:04 MCServer node[13633]: ERROR: Unable to perform database backup: Error: Command failed: "mongodump" --uri="mongodb://127.0.0.1:27017/meshcentral" --archive="/my/path/meshcentral/meshcentral-backup/mongodump-2020-12-27-06-26.archive"`
`Dec 27 06:26:04 MCServer node[13633]: 2020-12-27T06:26:03.634+0000        writing meshcentral.events to archive '/my/path/meshcentral/meshcentral-backup/mongodump-2020-12-27-06-26.archive'`
`Dec 27 06:26:04 MCServer node[13633]: 2020-12-27T06:26:03.637+0000        writing meshcentral.power to archive '/my/path/meshcentral/meshcentral-backup/mongodump-2020-12-27-06-26.archive'`
`Dec 27 06:26:04 MCServer node[13633]: 2020-12-27T06:26:03.707+0000        writing meshcentral.meshcentral to archive '/my/path/meshcentral/meshcentral-backup/mongodump-2020-12-27-06-26.archive'`
`Dec 27 06:26:04 MCServer node[13633]: 2020-12-27T06:26:03.787+0000        writing meshcentral.serverstats to archive '/my/path/meshcentral/meshcentral-backup/mongodump-2020-12-27-06-26.archive'`
`Dec 27 06:26:04 MCServer node[13633]: 2020-12-27T06:26:04.134+0000        Failed: archive writer: error writing data for collection `meshcentral.serverstats` to disk: error reading collection: Failed to parse: { find: "serverstats", skip: 0, snapshot: true, $readPreference: { mode: "secondaryPreferred" }, $db: "meshcentral" }. Unrecognized field 'snapshot'. / Mux ending but selectCases still open 4`

Is that some miss-configuration from my side?

**Comment by Ylianst** [comment]
Hi. If you have your own system for performing backups, you could disable the MeshCentral backup system. Make sure you keep a copy of "meshcentral-data" offsite along with a regular backup of your MongoDB database.

Note that the first command that failed is present above, you can login and try to run that command yourself and investigate the problem. MeshCentral will try to run MongoDump on each collection and at the end will try to zip all of the dumps. The zip may have failed because MeshCentral does not have permission to write, but not sure about that.

**Comment by vitko-bg** [comment]
Hi @Ylianst ,
When I type command manually:

`mongodump --uri=mongodb://127.0.0.1:27017/meshcentral --archive=/my/path/meshcentral/meshcentral-backup/mongodump-2020-12-29-08-26.archive`

The result is same:

`2020-12-29T10:13:26.442+0000    writing meshcentral.events to archive '/my/path/meshcentral/meshcentral-backup/mongodump-2020-12-29-08-26.archive'
2020-12-29T10:13:26.442+0000    writing meshcentral.serverstats to archive '/my/path/meshcentral/meshcentral-backup/mongodump-2020-12-29-08-26.archive'
2020-12-29T10:13:26.444+0000    writing meshcentral.power to archive '/my/path/meshcentral/meshcentral-backup/mongodump-2020-12-29-08-26.archive'
2020-12-29T10:13:26.445+0000    writing meshcentral.meshcentral to archive '/my/path/meshcentral/meshcentral-backup/mongodump-2020-12-29-08-26.archive'
2020-12-29T10:13:26.455+0000    Failed: archive writer: error writing data for collection `meshcentral.events` to disk: error reading collection: Failed to parse: { find: "events", skip: 0, snapshot: true, $readPreference: { mode: "secondaryPreferred" }, $db: "meshcentral" }. Unrecognized field 'snapshot'. / Mux ending but selectCases still open 4`

So looks like it is not MC2 error - just something in my system.
Will try to find where is the problem and will report back.

so far I managed to find that mongodump version: r3.4.24 and mongo db version v4.0.21 - looks like problem is coming from versions differences

**Comment by vitko-bg** [comment]
Managed to fix the problem. Thanks for help!

Solution is: **apt install mongodb-org-tools**

**Comment by Ylianst** [comment]
Nice. Yes, MongoDB tools don't come with MongoDB as of version 4.2 I think. So, they need to be installed separately. I updated the server to show a warning in the MyServer tab if MongoDump is not found.

![image](https://user-images.githubusercontent.com/1319013/103392235-b6c64700-4ad1-11eb-8231-e51fb3a426a0.png)

**Comment by datapharmer** [comment]
@Ylianst thanks for adding this as it got my attention (though the .exe threw me a bit at first on a linux machine). 
I'd suggest adding the need for mongodb-org-tools to the install notes for mongo.

Also, I found adding a swap file was necessary as mongo was already pushing things on a nano instance and kept getting clobbered on ec2 due to ram being over the instance limit once meshcentral tried using mongodump. I was hesitant due to ssd writes etc. but Amazon seems to not have a problem with it: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-memory-swap-file/ and it definitely improved performance.

**Comment by Ylianst** [comment]
Oh yes... the .exe is a problem. Doh! I am fix that.

On a t3.nano, I would not bother with MongoDB. I imagine you would manage less then 100 devices anyway? In that case just use NeDB and activate the offsite backup on Google Drive or WebDAV.

**Comment by Ylianst** [comment]
Ok, fixed the mongodump error message, it will only show .exe on Windows. Will be in MeshCentral v0.7.47. Pretty obvious now that you mention it.

**Comment by mikeleblank** [comment]
Hi, I ran into this error.

My solution in Ubuntu 22.4 using mongodb community, mongod

"mongoDumpPath": " ",

backup is made in the same path, within the same rar and without error
