### ISSUE TITLE
Issue with MongoDB database after update to 0.7.33 - Debian 10.6

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2124]
OS: Linux Debian 10.6
Memory: 2GB
VCPU's: 1

First of all, GREAT WORK! I have worked with a lot of projects with a lot of incomplete work in the security area. I literally didn't have to do anything on your projects security side. VERY GOOD WORK! Thank you for making my life easier!

I don't have any error messages to report. I tried to upgrade to 0.7.33. The upgrade went as expected, simple and fast. However, after the MeshCentral server came back online I'm showing connected agents but no functionality for them. There is no desktop, terminal, or the ability to re-upload the agent core. Now, here comes the part that leads me to believe it has to do with the Mongo Database. Downgrading back to the previous version of 0.7.32 works but the problem persists. Once I restore the Mongo Database that was used originally with v0.7.32 the agents options begin to reappear. This seems to be related to some recent code that was changed relating to "mtype".  Any advice on how to fix this or any other information I can pass along to you about this problem?

**Comment by asasin114** [comment]
I'm in the same boat with a Windows Server 2019 deployment of the MeshCentral Server. I also have the following warning on the My Server tab.

![image](https://user-images.githubusercontent.com/417006/103358887-55c05400-4a7c-11eb-8b54-d20d893cccb5.png)

**Comment by asasin114** [comment]
Uh oh! Rolling back does not fix! I'm broken at the moment!

**Comment by PathfinderNetworks** [comment]
I have an open issue for a similar issue where I'm trying to migrate from NeDB to MongoDB and end up with the same issues LPJon is reporting.  
In my case it appears to be a permissions issue- where my administrator account doesn't actually have admin access to most of MeshCentral after migrating to Mongo.  
One way to check that is to go to 'My Account' and look at your list of Device Groups. Does it show you have 'Full Administrator' access to them? I suspect not.  But, if you create a new group, I suspect you'll see it will give you full admin rights to the new one.  
Also, if you go to 'My Users' it will likely show your account as having 'Administrator' permissions.  But you can't actually make any changes or perform any functions that require Administrator level access.  

The connection options for your devices are missing because you no longer have the proper permissions to access those devices.

**Comment by LPJon** [comment]
@PathfinderNetworks @asasin114 It looks like you are correct PathFinderNetworks. This is a permissions issue but is still related to the database. Thanks for the tip! I was able to get things back up and running by logging into the original administrative account (The one made at initial setup) and adding/re-adding group/user rights to the device groups. Once I did that, logging back into the user accounts and going to a device produces the desktop, terminal, and files options that were missing. 

Another strange thing was that only the account that was used to upgrade the server had permission issues. The rest of the user accounts seemed to be unaffected. I would **strongly** suggest not to use the original administrative account for this upgrade because it may strip all access rights to the agents. 

I'm considering this issue closed because this is a successful work around. However, it should probably be looked at because this could be alarming and even cause a lot of work if multiple user accounts are involved and re-configuring the user account-to-device groups is required. Large scale deployments could/would suffer some downtime.

**Comment by LPJon** [comment]
Duplicate of #2128 
Duplicate of #2114

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.34 with the "mtype" change rolled back. I am investigating now why that would have caused an issue, but you should be able to update from a working MeshCentral to v0.7.34 correctly now. Let me know if that works.

Still investigating what happened.
