### ISSUE TITLE
Meshcentral server management

### ISSUE THREAD

**Issue by vithusel** [Ylianst/MeshCentral#2132]
Hi, 

Just a quick question. 

Would MeshCentral break if i was to install the client on the server running MeshCentral? 

Or is there a different way to manage updates on the server? 

Kind Regards,

Vit

PS - Absolutely love this software, works better then most paid for solutions and im so annoyed that i can give you a donation for all your hard work!

**Comment by Ylianst** [comment]
Thanks. Installing the agent on the server running MeshCentral will work. Of course, I don't recommend using such a setup to manage the MeshCentral server itself since if you have to stop the server to perform management tasks, you will also loose access. So, yes, you can do that by make sure you also have an alternative way of accessing the server.

**Comment by PathfinderNetworks** [comment]
Ylian is right.  There is no issue at all with having the agent installed on the server (I do the same myself). However, the issue is that you can't access the server via Mesh when you are needing to do maintenance on the MeshCentral server application.  So, in my case, I RDP in to the host server and then open the Hyper-V console to directly access the Server2019 VM that I'm running MeshCentral under.  That works well unless I happen to not be on my LAN and need to do some type of emergency work from a remote location.  In that case I have to VPN on to my LAN and do the same work.  
Usually none of that is an issue though.

**Comment by vithusel** [comment]
Thank you very much for the info guys! 

I've decided to just SSH into the server if i need to do any upgrades.
