### ISSUE TITLE
December Release Keyboard Problem

### ISSUE THREAD

**Issue by wcrlewis** [Ylianst/MeshCentral#2158]
Troubleshooting was completed including complete system reimaging without resolution.  As of the December version, using a remote connection and loading a VirtualBox VM results in incorrect characters.  It was not a problem for years.  What was altered and can it be corrected?  Your assistance is greatly appreciated.

**Comment by krayon007** [comment]
Some others were helping us debug a similar issue ( #469 ) and they found there was potentially a bug in VirtualBox itself, as it seemed to mess up the keyboard mapping between the host and guest OS.

The change on the agent side, was that we now correctly handle differing keyboard mappings. In your case with VirtualBox, you should be able to workaround the issue, by selecting this checkbox to enable using the remote mapping, which enables the old way of doing this. Note, this will only work if the keyboard mappings on the local and remote side are the same, otherwise it the characters will get misinterpreted. (But this is what would've happened previously as well, which is why we had to make the change to correctly handle keyboard mappings in the first place)

![remotemapping](https://user-images.githubusercontent.com/29240564/104142035-82267b00-536e-11eb-903c-d533441e7c25.png)

**Comment by jdvmanen** [comment]
Keyboard is tricky since a month or so. The checkbox 'use remote keyboard map' solves most problems, but this setting you need every time to set after making connection.

Numeric keypad doubles all output (thus typing 123 shows 112233 on the screen). Numeric row above the 'alphanumeric' characters will not double.

**Comment by Ylianst** [comment]
The "Use Remote Keyboard Map" should be saved in your account, you should not have to re-enable it each time. This is a bug for sure.

**Comment by bbrendon** [comment]
In case someone comes here looking for a solution to : "pressing space bar gives two spaces instead of one."
Enable the remote keyboard map checkbox!

**Comment by si458** [comment]
this should be fixed not in the latest version
if your having issues, please use the "Use Remote Keyboard Map" option,
it gets saved to the browser of the device in localsession
it wont sync the settings across browsers unless u want this feature
