### ISSUE TITLE
Suggestion: send email when detecting when a computer is turned off or turned on

### ISSUE THREAD

**Issue by mrkacg1** [Ylianst/MeshCentral#2167]
It would be interesting to add this equipment monitoring function. The idea would be to send an email or notification when a computer is turned off or on.

**Comment by yomono** [comment]
If you have a lot of clients that would be so annoying

**Comment by Ylianst** [comment]
This feature has been requested before. At some point I do want to build this. People are asking for notification when computer go up or down. Likely the server would group all the notifications for a period of time and send all the notifications at once.

This is not a feature for everyone, but for some sub-groups of devices, I can see how it would be useful.

**Comment by LPJon** [comment]
> 
> 
> This feature has been requested before. At some point I do want to build this. People are asking for notification when computer go up or down. Likely the server would group all the notifications for a period of time and send all the notifications at once.
> 
> This is not a feature for everyone, but for some sub-groups of devices, I can see how it would be useful.

This would be very useful if I was looking to be notified that a server went offline. I would want to select which agent being monitored would trigger the notification. Simply the agent going offline would work for me but would be very nice since it could also indicate that there was a loss in internet services for the client. I think this would be very useful for server situations.

**Comment by mrkacg1** [comment]
Well it depends on who needs this, it may seem annoying or not.

I monitor multiple servers a day and need to know if they have problems. Meshcentral could help with this. Thanks Ylian

PS: The important thing is that you can indicate which equipment is required to notify and which is not.

**Comment by yomono** [comment]
> Well it depends on who needs this, it may seem annoying or not.
> 
> I monitor multiple servers a day and need to know if they have problems. Meshcentral could help with this. Thanks Ylian
> 
> PS: The important thing is that you can indicate which equipment is required to notify and which is not.

Of course, that PS is the key on all this

**Comment by Ylianst** [comment]
Agreed. You really don't want notifications for all devices. This need to be something you can set. Then there is the question of who you notify. If many users and rights on a device, you probably don't want to notify all of them, etc. It's a bunch of work for sure :)

**Comment by LPJon** [comment]
> 
> 
> Agreed. You really don't want notifications for all devices. This need to be something you can set. Then there is the question of who you notify. If many users and rights on a device, you probably don't want to notify all of them, etc. It's a bunch of work for sure :)

Maybe, you could make it so that you could assign the notifications to a specific group then place the users you want notified in that group. Then you could also divide the notification priority by which groups you assigned the notifications to.

Example: Server Notifications Group=user1, user2, user3.  PC/Client Notifications Group=user4, user5, user6. Use the email addresses assigned to each user for notifications or add an extra field for each user for where to send notifications to.

**Comment by si458** [comment]
this feature exists as of 2023
you can now set individual devices for notifications in your browser or using ur messaging method (discord, teams, email, etc)
