### ISSUE TITLE
Questions about HashiCorp Vault

### ISSUE THREAD

**Issue by p-m-tech** [Ylianst/MeshCentral#2168]
First, I want to thank you all for making MeshCentral. It looks amazing, and I can't wait to start using it! I have a couple questions about Vault. Are there any other methods of authentication besides using the token and unseal key? If not, what is the advantage of using Vault? Is it only having the config and certs outside of the MeshCentral directory?

**Comment by Ylianst** [comment]
I built the Vault support a long time ago and I don't think anyone is using that feature. My general idea is that would could stuff the "meshcentral-data" folder in Vault and start a MeshCentral in a Docker container that just point the container to Vault for all of the configuration. This will make the container completely stateless which is how containers should operate.

I am really not an Vault expert, so if you have any specific ideas. Let me know. In general, I this Vault is low on the priority list right now because we are sort of overwhelmed with requests and Vault usage would be typically low. If someone sent out a pull request for Vault improvements, I would certainly review/accept it.

**Comment by p-m-tech** [comment]
Got it. Thank you Ylian!
