### ISSUE TITLE
Database changes not reflected because node (db.js) never re-read

### ISSUE THREAD

**Issue by Kodangi** [Ylianst/MeshCentral#217]
Database changes not reflected because node (db.js) never re-read

If changes are made to mongodb data (on the side), node does not reflect, because db.js uses exclusive access to db and not re-reading the data if changes are made, such as changeStream

**Comment by Ylianst** [comment]
Right, it's currently designed this way. I will look into this since it also should allow server peering to hopefully keep more consistent state between each other.

**Comment by Ylianst** [comment]
Looking into this, the MongoDB changeStream would solve a problem I was going to have when running many MeshCentral servers in peering mode. It can be used to sync all the nodes to the same database view. In MeshCentral v0.3.4-a that I just published, I added to code to use "MongoDB" instead of "MongoJS" as the main database driver so now, I can start using changeStream.

This said, my MongoDB database does not have a replica set and this is required for changeStream to work. Are you planning to use MongoDB with a replica set?

**Comment by Kodangi** [comment]
Thanks Ylian, No plan to use replica; This helps us to update DB off the side; so Mesh can show the changes.
About backup/replication: We do hourly backup, so we can always restore to any point.

**Comment by Ylianst** [comment]
Without setting up replica, the changeStream feature does not work in MongoDB. If you [look here](https://www.mongodb.com/blog/post/an-introduction-to-change-streams) it says:

> To use change streams, we must first create a replica set.

This is because changeStream depends on oplog which is enabled when a replica set is setup. So, not sure if that would work for you.

**Comment by Kodangi** [comment]
Thanks again, I will follow your link here.

**Comment by Ylianst** [comment]
Note that I have not implemented MongoDB changeStream yet. Just wanted to point out that in order to use changeStream, you need MongoDB to be setup with replica set.

**Comment by Kodangi** [comment]
Yes and sure Ylian. I would work on get mongodb repl set running.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.5-k with MongoDB Change Stream support.

- First, enable replication in your MongoDB, [take a look here](https://pusher.com/tutorials/mongodb-change-streams) for an example.
- Then, set add this to the "settings" section of your config.json

       "MongoDbChangeStream": true,

Once you launch MeshCentral again, it should work as normal, however if you go in the "My Server" tab, "Console" sub tab and type "info" you will see:

![MC2-ChangeStream](https://user-images.githubusercontent.com/1319013/58522015-6ce9e200-8173-11e9-8dd6-a55156ade69f.png)

This indicates that change stream is active. You can than change the database node, mesh or user entries that it will be immediately updated on the screen of all browsers as appropriate. Testing on this appreciated.

**Comment by Kodangi** [comment]
super, thanks a lot. I will go try out first.

**Comment by Kodangi** [comment]
Verified. The changes made in mongo outside meshcentral is shown instantly on meshcentral. Thanks.

**Comment by Ylianst** [comment]
FYI. Next version of MeshCentral will have a fix for MongoDB change stream. The server in memory copies of device groups and users will be updated correctly. Before this fix, the update would change the value on the web pages, but the server did not update. Does not affect device information which is correct now.

**Comment by Kodangi** [comment]
Thanks Ylian, updated.
