### ISSUE TITLE
Server Warning: "WARNING: Unable to find mongodump, MongoDB database auto-backup will not be performed."

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#2170]
I'm running MeshCentral v0.7.47 with NodeJS v12.20.1 on Debian 10 and I'm using MongoDB v4.4.3 as the database backend.

I've verified that the package `mongodb-org-tools` is installed and that the `mongodump` binary exists on my system.

```
whalehub@pdh:~# sudo apt list --installed | grep mongodb-org-tools
mongodb-org-tools/buster,now 4.4.3 amd64 [installed,automatic]
```
```
whalehub@pdh:~# mongodump --version
mongodump version: 100.2.1
git version: 0cb6f592fcb425ee5b3d5540341de75531d28dac
Go version: go1.12.17
   os: linux
   arch: amd64
   compiler: gc
```

The appearance of this warning appears to be a purely visual bug in my case since I can see that MeshCentral has been creating its daily database backups in the `meshcentral-backup` folder just fine.

**Comment by Ylianst** [comment]
Thanks for reporting this. Yes, this could be visual indeed. I added the warning because latest MongoDB does not come with the tools by default and don't want to give anyone a false sense of security with the backups. If you backups include the MongoDB dump, you are 100% ok. I got to get over the next big release and I will work on fixing this.

**Comment by SomeGuru** [comment]
@Ylianst 

Still a WIP? I ask because I just seen this on a server I am running and it has the tools installed also... So I am wondering if they may have changed the way the parameters are passed? Just trying to think about this from another perspective.

Thanks,
SomeGuru

**Comment by whalehub** [comment]
This issue appears to have been fixed by now.
