### ISSUE TITLE
Is there a new (updated) guide on MongoDB\Peering on Windows?

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#2171]

**Comment by Ylianst** [comment]
Look at section 7.3 of the [MeshCentral's User Guide](https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf). I do need to update the documentation because MongoDB is required and you must have ChangeStream enabled. In the setting section of the config.json, you will have something like:

```
    "MongoDb": "mongodb://127.0.0.1:27017?replicaSet=rs0",
    "MongoDbChangeStream": true,
```

In the peers section, you will have something like this:

```
  "peers": {
    "serverId": "Central1",
    "servers": {
      "Central1": {
        "url": "wss://192.168.2.147:443/"
      },
      "Central2": {
        "url": "wss://192.168.2.147:444/"
      }
    }
  }
```

The two servers will connect to each other and the database. If everything checked out, they will work together.
