### ISSUE TITLE
Not show elevation of permissions on a connection to RDP.

### ISSUE THREAD

**Issue by lergolas** [Ylianst/MeshCentral#2196]
Hi.
When I enter in a RDP session from web interface, and I try to install a program that requires elevation of permissions, the window is not displayed. I only see the main screen locked.
On the other hand, the user who is connected through RDP, does see the elevation of permissions window, but he doesn't have admin permissions to install.
Is it a limitation of the connection to an RDP session?
The test is done on Windows 10, with the latest version of the server.
Thanks a lot.

Edit: If the user cancels the permission elevation window, I cannot reconnect to their RDP session until the computer is restarted. It is not enough to restart the meshacentral service on the computer.

**Comment by krayon007** [comment]
> Hi.
> When I enter in a RDP session from web interface, and I try to install a program that requires elevation of permissions, the window is not displayed. I only see the main screen locked.
> On the other hand, the user who is connected through RDP, does see the elevation of permissions window, but he doesn't have admin permissions to install.
> Is it a limitation of the connection to an RDP session?
> The test is done on Windows 10, with the latest version of the server.
> Thanks a lot.
> 
> Edit: If the user cancels the permission elevation window, I cannot reconnect to their RDP session until the computer is restarted. It is not enough to restart the meshacentral service on the computer.

That's because of the UAC setting is by default set for secure desktop, which is not scrapable for KVM from an RDP session. When the UAC window shows, the agent KVM process is kicked, because of insufficient permission. Assuming the agent is configured to run as background service, you can remedy this by modifying the UAC setting to interactive... You can do this from the console tab on the web ui... If you type `uac get` it will tell you the current mode... If you type `uac interactive` it will modify the registry settings to configure UAC to use an interactive desktop instead of a secure desktop, which will allow the KVM to remote the UAC prompt. You can type `uac secure` to change it back.

**Comment by emersonnpe** [comment]
@krayon007 Do you have the basis for how to perform the procedure? I have the same problem.

**Comment by lergolas** [comment]
Before requesting elevation of permissions, in the Console tab, type: "uac interactive".
Then run the program that needs elevation of permissions and the window to enter the necessary credentials will come out right.
Once the desired procedure is done, simply type in the console: "uac secure" to leave everything as it was.
It works perfectly.
Thank you.
