### ISSUE TITLE
show DNS settings (feat. req.)

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2208]
Would it be possible to show the DNS settings next to the interface information on General/Interfaces and on the Details tab ?

![image](https://user-images.githubusercontent.com/5128967/105706351-b757cf00-5f11-11eb-84dc-5151511626f4.png)
![image](https://user-images.githubusercontent.com/5128967/105706420-ce96bc80-5f11-11eb-9b35-16a73d8827d6.png)

**Comment by Ylianst** [comment]
Bryan did work on this and added the DNS server's IP address. That should be coming up in a future version.

**Comment by si458** [comment]
only a few years late but it will now show you the DNS servers under the network interfaces in the Details tab
![image](https://github.com/Ylianst/MeshCentral/assets/765314/4c4ad2eb-1926-463f-a13d-14867897f0ab)
sadly i cant put the DNS into the interfaces mini pop up panel because that panel gets the data thats stored on the server and the dns doesnt get saved there only the interfaces
