### ISSUE TITLE
Desktop share link connects to console only?

### ISSUE THREAD

**Issue by jjoelc** [Ylianst/MeshCentral#2222]
MeshCentral 0.7.2 on Ubuntu 20.04 server, behind nGinX reverse Proxy

I just discovered that when I create a desktop share link, when the guest clicks the link they are only able to connect to the console and is unable to choose an RDP session to connect to. It was a bit of a surprise as I was expecting the "normal" behavior where the guest would be able to choose an RDP session.

Is this behavior intentional? (For security reasons, I would assume, especially in the case of unattended access...) Would there be some method available to allow the guest to choose an RDP session to connect to? (Even better would be some way to allow the person creating the share link the ability to choose either console or specific user RDP session to allow connection to! I'm guessing that would be considerably more difficult though.) Maybe an in-between option would be to allow console access only when no consent is required, but allow the option to choose an RDP session if consent is required?

**Comment by Ylianst** [comment]
The guest sharing system does not currently implement RDP session selection. I would not have expected this feature to be used with servers that have multiple RDP sessions and even then, the user notification and consent would be for the main desktop. Pre-selecting the RDP session may not work well because you don't know if the RDP session changed since the link was created.

I think the right think to do is only use the guest sharing for the main desktop and for advanced usages, you can give an account to someone and give them remote access rights to the device you want them to access. If there is a more specific request, I can look at it, but it looks difficult to secure a guest desktop link beyond the primary desktop console.
