### ISSUE TITLE
Can Filter have an enhanced feature

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#2252]
Hi MeshCentral Team,

I am wondering if there can be an enhanced filter/search function to add elements such as group names, machine names, IP addresses, and maybe even MAC address filtering, OS versions results. Plus it would do this across the groups that are available to the user access level given and groups assigned?

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Currently you can type in the filter box things like "ip:192.168". There is the full list:

`user:` or `u:` to filter devices with a given user logged on the remote device.
`ip:` devices at a given IP address.
`group:` or `g:` for devices within a device group.
`tag:` or `t:` filter devices with a tag.
`atag:` or `a:` filter on agent tag (meshagent.tag file).

Hope that helps. We can look at adding more if needed.

**Comment by SomeGuru** [comment]
Adding OS filter could be handy and then also adding Processor filter would be great also... Is there one for AMT call out also? Like AMT: or AM:?

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Ok, next version of MeshCentral v0.7.77, you will be able to type `amt:` to see all devices that support Intel AMT, or `amt:<state>` to filter on activation state. State being 0 for un-provisionned, 1 to in-provisioning (which is rare) and 2 for activated. So, `amt:2` will show all activated Intel AMT devices. When published, let me know if that works.

Also, `os:<string>` now works since v0.7.76 so you can search for all the Windows Home editions by typing `os:home`.
