### ISSUE TITLE
Update to 0.7.64 from 0.7.62 has dropped the agents

### ISSUE THREAD

**Issue by I2700I** [Ylianst/MeshCentral#2264]
A vast majority of the agents (Windows 10 endpoints, in case it matters) did not come back online. I waited a couple hours for them to report in - no dice.
The agents are running on the endpoints and manually updating the agent reconnects it back to the central but also requires an backup way to connect.
Getting to the console and pushing the agent update is impossible sine they report offline.

**Comment by Ylianst** [comment]
There is no agent change between 0.7.62 and 0.7.64. I am guessing something else went wrong with the update, but obviously there is nothing much I can go on to help. I have a server that updates thru every version, so I certainly tested something close to this. You can take a look [at the changes made here](https://github.com/Ylianst/MeshCentral/commits/master).

I will mention that if you delete the "meshcentral-data" folder, you will never get the agents back because that folder contains the certificate the agents use to securely authenticate the server. Always keep an off-site backup of the meshcentral-data folder.

If you have server backups in "meshcentral-backups", you can safely rollback you server. If you have access to one of your machines, you can stop the MeshAgent and on Windows, run from the command prompt "meshagent.exe -run". That will show you what the agent is going.

Hope that helps. Ylian

**Comment by I2700I** [comment]
The server upgrade was the only event that happened.  The server is running on Windows Server and I'm not sure if the "meshcentral-data" was deleted during the upgrade, can check with the backup to see the differences.
It's good that it happened on the weekend so I have applied the backup remote access application and reinstalled the agents on the endpoints.

**Comment by Ylianst** [comment]
Also note that [https://meshcentral.com](https://meshcentral.com) is running on v0.7.64 now with 8000+ agents running. I just updated today.

**Comment by Ylianst** [comment]
Since we release MeshCentral version frequently, it's always "because of the update". Do report back if you have more information.

**Comment by Ylianst** [comment]
Closing since there is no more information, but if you can report back what exact Windows OS version caused an issue, we can test that again. Thanks.
