### ISSUE TITLE
Android agent cannot connect to MC2 server

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#2271]
I just now spotted that Android Agent is released and can be installed from Play Store or from own MC2 server, or from meshcentral.com
Decided to install and test - but unfortunately, after adding my own server via QR scan or via mc://link, it cannot connect and does not appear anywhere on the server. When press "Connect" it is disconnecting straight away.
I also enabled LOGs on my router and can see that request from Android device is coming in to the server, but on Server Trace on MC2, no incoming connections are indicated. I selected all options to trace, to make sure that won't miss some.

MC2 0.7.66 behind NGINX reverse proxy
Debian 8
Android agent installed on my OnePlus 7 Pro
Agent version: 1.0.3

**Comment by Ylianst** [comment]
To debug this, I am going to need to have access to a server that has this issue. If you server is on the public internet and you don't mind creating a dummy account for me, mail me privately with your server URL and a dummy user/pass. I will test the Android app in debug mode and see what is going on. [My contact info is here](https://www.meshcommander.com/contact-information).

**Comment by vitko-bg** [comment]
@Ylianst - I have sent you an e-mail with required info, but as mentioned in the e-mail, not sure if that will be helpful, as a new subdomain has been created for you for testing purposes and "my server" rights looks like does not work as it should. Let me know, please, if I can help you with anything else.
Thanks.

**Comment by vitko-bg** [comment]
Managed to get it working by adding IP to "ignoreagenthashcheck".
Because it is mobile phone and IP is dynamic will be very difficult to manage devices.
For me it is something related to Linux Agents won't connect to MC #1536 - unknown issue - MC2 config, Nginx reverse proxy or agent ....

**Comment by Ylianst** [comment]
What version of the Android agent are you using for your latest tests? Was is v1.0.4?

**Comment by Ylianst** [comment]
Can you confirm you where testing agent v1.0.4? - Thanks.

**Comment by vitko-bg** [comment]
Confirmed. Downloaded from MeshCentral.com
Again - I think there is some issue with my server - either MC2 conf, ether NGinx reverse proxy, because all Windows agents are absolutely fine, only Linux, Mac and Android clients are with "Bad signature". In short all Unix based clients........

**Comment by vitko-bg** [comment]
Not sure what more can be done....

**Comment by Ylianst** [comment]
Oh I see. So if you add `"ignoreagenthashcheck": true`, all the agents corrects correctly? Are you using "certurl" in your config.json with the address of the reverse proxy?

When agents don't correct correctly, can you run "agentstats" on the "My Server / Console" and let me know what you see? - Thanks.

![image](https://user-images.githubusercontent.com/1319013/107568752-4b759780-6b9c-11eb-8483-d3c6308496d0.png)

**Comment by vitko-bg** [comment]
1. With "ignoreagenthashcheck": true - all agents connect fine, Windows and Unix. With "ignoreagenthashcheck": false, only Windows agents are fine with no issues - so that is correct.
2.  "CertUrl": "https://127.0.0.1:443" - so here answer is yes also.
3. here is the pictures before attempting to connect using Android client, and after
**Before:**
![image](https://user-images.githubusercontent.com/59362521/107573097-ff9b1080-6be4-11eb-8213-583a9c2a6d7e.png)

**After:**
![image](https://user-images.githubusercontent.com/59362521/107573143-10e41d00-6be5-11eb-9c8a-95962aa6f462.png)

P.S. Same result will be with Linux and Mac Agents - tested lots of times ....

**Comment by Ylianst** [comment]
Ok. I will need to find a way to replicate this to fix it. There is no way to debug this otherwise. If you don't mind and can post your public server URL and a dummy account with no privileges for me [in a private email](https://www.meshcommander.com/contact-information), I can take a look at this. I am going slowing down for the next two days, so no rush. Bryan and I have been coding like crazy.

**Comment by vitko-bg** [comment]
@Ylianst - you should have an e-mail from yesterday with details provided.
Bear in mind that the link and user name is for additional domain in config.json, not the main one, however you still will be able to see the problem between Windows and other agents. Thanks for all help! If you need some config files - nginx, MC2, etc - let me know.

**Comment by vitko-bg** [comment]
Managed to replicate issue on different server, different OS and using a different domain name.
In short - I just got rid of "CertUrl": "https://127.0.0.1:443", for each domain in config.json and all Windows, Linux, Android, MAC based agents age connecting fine now. I am really happy that problem is finally resolved now on my server.
Any information required to replicate the issue or any info about my config files - feel free to contact me.

**Comment by Ylianst** [comment]
Just to report back of private debugging that has been happening. Thank you to @vitko-bg for setting up a test environment and allowing me to see what is going on.

The server is behind a NGINX reverse proxy and has 3 domains, the default one and two extra. Each domain is on a separate DNS name and the reverse proxy has a different Let's Encrypt certificate for each DNS name. The configuration has the following line in each domain:

```
"CertUrl": "https://127.0.0.1:443"
```

This is a problem because if you have 3 domains with 3 different certificates, you need the "certurl" of each domain to point to a URL that load the certificate for that domain. Now, this was incorrectly configured, but that was not the problem since the config.json also specified an "agentport". So, agents for all 3 domains are not connecting to port 443 of each domain, but a separate port on the server. In this case, "CertURL" was not needed at all.

It turn out that the certificate validation in MeshCentral when multiple domains are setup and you have "agentport" is not done correctly. I send out a fix to @vitko-bg and did not get a response yet.

**Comment by vitko-bg** [comment]
@Ylianst - I have made suggested by you changes, restarted the server - result is the same as before.
I sent you an email with rest of the details.
Thanks!

**Comment by Ylianst** [comment]
Update on this. @vitko-bg got me access to a test server and I was able to debug and fix the issue. Fix will be in v0.7.69.

**Comment by vitko-bg** [comment]
@Ylianst - I sent you an e-mail with confirmation that after all changes you made all is working as expected.
Looking forward for the v0.7.69 with fixes.
Thanks you for all tests done and for fixing the issue!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.69 with the latest fixes. That should solve it. Please close this issue if it works and thank you so much for all the help.

**Comment by vitko-bg** [comment]
Confirmed! All working fine in 0.7.69!
You are welcome :) will keep testing and reporting if there any issues. Thanks!
