### ISSUE TITLE
[Not a issue, just a question] Creating new groups

### ISSUE THREAD

**Issue by GraphicDepo** [Ylianst/MeshCentral#2272]
Hello Ylianst ! 

i Have one question about creating new groups. 

When i started to use MeshCentral [ about 4-5 months ago ] i had Full Rights as "root user". I made a user for someone also with Full Rights to the server, when he created a group i was able to see without being added to that group , now if he create a new group i'm not able to see it. How i can make this possible again? 

Also if i dont remember wrong, at that time he will Rull RIghts on server was unable to edit my "root user".

**Comment by GraphicDepo** [comment]
I fogot to tell you what version i use. 

Current Version: 0.6.87

**Comment by robclay** [comment]
This helped me with that same issue:
https://www.reddit.com/r/MeshCentral/comments/gfrzu6/how_administrator_admin_can_access_all_the_device/

**Comment by GraphicDepo** [comment]
Well...i tryed and nothing... https://prnt.sc/yv0t8r

Also i tryed: 

`"ManageAllDeviceGroups": [ "admin","admin2" ]`
`"_ManageAllDeviceGroups": [ "admin","admin2" ]`

**Comment by Ylianst** [comment]
By default, users with full administrator rights on the server can't see other user's device groups. You can see all groups if you are both full site admin and use `ManageAllDeviceGroups`. Note that `ManageAllDeviceGroups` takes a list of userid and these generally don't have capital letters. Try:

"ManageAllDeviceGroups": [ "stepfan", "bogdam" ]

Also placing a _ will make the server ignore that option in the config.json, so "_ManageAllDeviceGroups" would not work by design.

**Comment by GraphicDepo** [comment]
> 
> 
> By default, users with full administrator rights on the server can't see other user's device groups. You can see all groups if you are both full site admin and use `ManageAllDeviceGroups`. Note that `ManageAllDeviceGroups` takes a list of userid and these generally don't have capital letters. Try:
> 
> ```
> "ManageAllDeviceGroups": [ "stepfan", "bogdam" ]
> ```
> 
> Also placing a _ will make the server ignore that option in the config.json, so "_ManageAllDeviceGroups" would not work by design. Let me know if that works.

Everything fine :D thank you seems the problem was because of capital letters. 👍
