### ISSUE TITLE
MeshCentral Android - Expected Behaviour? 

### ISSUE THREAD

**Issue by jordanhandy** [Ylianst/MeshCentral#2298]
Hello, I've added two of my Android devices to MeshCentral.

I've noticed that after I connect the device to the server, the connection will live for approximately 20-30 minutes, and the device will become disconnected from the server.

Is this expected? How do we make the connections to the server persistent?

I turned off Doze and battery optimization for the app to prevent it from closing.

I also thought that a network change might be the cause of the connection drop, so I stayed on my carrier connection entirely and remained off of WiFi 

Is this normal behaviour?
Thanks

**Comment by Ylianst** [comment]
So, there is no timer in the MeshCentral Agent for Android to disconnect after some time, however, it seems like Android policy to disconnect the agent after some time to save power. The agent does ping the server every 2 minutes now to make the connection last longer, but looks like if there is no user interaction, the agent will disconnect.

I am still learning how Android works and so, it's all a bit experimental. However, it may be that the way this is going to work is that the agent will have to be woken up using a push notification message when it needs to do something, otherwise, the agent and server will have to communicate using push notifications. This is why I put a lot of priority on adding push notification support. You can turn it on by adding:

```
"PublicPushNotifications": true
```

In the settings section of the config.json. I am going to experiment with sending a push notification to have the agent wake up and connect back. We will see how this goes. In general, if you are managing phones, this is probably a better path forward as the agent will only be activated when needed.

If you are using some a Android device that is not power limited and it's still doing that, I would have to look. Plenty to experiment with going forward.
