### ISSUE TITLE
Clickonce is not working properly

### ISSUE THREAD

**Issue by Josephclb** [Ylianst/MeshCentral#23]
There's something wrong with clickonce functions. I can't use RDP, SSH or SCP.

**Comment by Ylianst** [comment]
Fixed this yesterday. Should be working as of the current version (MeshCentral v0.2.2-l on NPM). As a bonus, the new ClickOnce application should work on Windows 7 (used to work on Win8 and higher only). Because MeshCentral2 runs on TLS 1.2, you will need .NET 4.5.

Just a reminder for everyone. The "RDP" link works in IE, but you need a ClickOnce add-in installed for Chrome and Firefox.
