### ISSUE TITLE
Question : Agent In Trouble 

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2305]
Hi,

I've switched on MC2 v.0.7.68 and the command "agentstats" give me a certain numbers of agents in trouble.
What does it mean please ? If I run the "agentissues" command, I've got only the duplicates agent.
If it can help, I had to modify the order of my certificate chain yesterday.

Thank you.

![2021-02-17 14_14_46-SiRi](https://user-images.githubusercontent.com/76168733/108209767-f8b35700-712a-11eb-97ea-6def6f8f9533.png)

**Comment by Ylianst** [comment]
"Agent in trouble" happens when an agent disconnects and reconnects over and over. At some point, the server detects this behavior and just holds the agent connection. One possibility for this is that some of the agents have been "cloned" and have the same identity. That is, two or more agents have the same certificate and so, they all report back to the server as being the same agent. The server will drop the previous agent connection by the same identity and accept the new one, but since many agents have the same identity it causes a re-connection storm. When that happens, you see "duplicates" go up and "agentInTrouble" go up.

In the latest version of MeshCentral, type "agentissues" in the same server console and it should give you the last 50 time, IP address and issue in a list. This way, you can hopefully see what is going on.

**Comment by elpibedeoro** [comment]
Hi,
Thank you for your explication, I will try to find out who is the guilty !
Have a nice day
