### ISSUE TITLE
AMT ACM Certificates and Setup.bin Questions

### ISSUE THREAD

**Issue by SurrounDTech** [Ylianst/MeshCentral#2320]
Hi,

I know this question has been asked before but I am still unsure if I have the the final setup correct when using AMT ACM and have few questions. 

My current environment is running:
Windows Server 2019 Standard
nodeVersion: v14.15.1
meshVersion: 0.7.72

I have updated the config.json to include the vPro certificates purchased from Go Daddy.

`"amtAcmActivation": {
                "log": "amtactivation.log",
                "certs": {
                    "MeshCentralCert": {
                        "certfiles": [
                            "domain.crt",
                            "GDSC.crt",
                            "GDRC.crt",
                            "GDCC.crt"
                        ],
                        "keyfile": "meshcentralcert.key"
                    }
                }
            }`

I have restarted MeshCentral for the changes to take affect and gone into the console tab to run amtacm and can see two certificates. The first certificate being linked our domain (eg. domain.com) and the second * seems to be generate by meshcentral? Is that correct? Or should the second certificate be also linked our domain as well?
 
![image](https://user-images.githubusercontent.com/65645186/108953338-c4094780-76b6-11eb-98b5-f6540288baaf.png)

I then create the setup.bin file by clicking on ACM link and have Intel AMT set to Fully Automatic.
![image](https://user-images.githubusercontent.com/65645186/108953902-ae485200-76b7-11eb-886f-8588738d505a.png)

Upon checked the setup.bin file in MeshCommander I noticed that it sets the PKI DNS Suffix to rootcert.meshcentral.com and the User Defined Certificate Addition certificate to the second certificate in shown in the console when running amtacm. Once again should these be linked to our domain and not the certificates generated by meshcentral?
![image](https://user-images.githubusercontent.com/65645186/108954741-003da780-76b9-11eb-9428-ba4f8d123d5c.png)

Also when going to mysite.domain.com:4433 the site is loading but receives a message that the connection is not secure as it is using another meshcentral certificate. Is this correct as the rest of the site loads using out domain certificate?
![image](https://user-images.githubusercontent.com/65645186/108964386-22d6bd00-76c7-11eb-83c7-dbbc35363bd7.png)

![image](https://user-images.githubusercontent.com/65645186/108964689-8660ea80-76c7-11eb-84c1-5d6bfb5d2954.png)

I understand there are a lot of questions wrapped into one but would like to get the configuration of our out of band device correct as they will be in remote locations. I hope that all makes sense.

I appreciate the time you have spent creating and supporting this amazing software.

Thank you for your time.

**Comment by Ylianst** [comment]
Hi. All good questions. Let me take a first short at it and don't hesitate to ask more questions.

- On the "star" certificate. By default, MeshCentral will create a ACM activation root certificate, you see it as the * certificate when you type "amtacm". If that certificate root hash is found to be in any AMT device, MeshCentral will generate a leaf activation certificate to match any DNS name and attempt to activate. So, when you create a setup.bin file, it will put that root hash with some random DNS name. When you setup that USB key into any AMT device, the root and DNS name will be added and MeshCentral will perform ACM activation on it. You do not need to buy any certificate for this to work.

- On your purchase of a AMT activation certificate. Ok, given the point above, why ever buy a certificate? Well, if you buy an official activation certificate for a given DNS name, you can load the certificate into MeshCentral like you did and put that DNS name in your DHCP server (option 15, the local network DNS name). Then, plug the local Ethernet port that is managed by AMT to the DHCP server and MeshCentral should see that AMT detected it's connected on a local network with your DNS name and it has a certificate that matches this. It should perform ACM activation automatically. So, you buy a certificate so you don't have to use the USB key (setup.bin). This said, the DHCP activation does not work with WIFI, only local Ethernet.

- On the topic of the CIRA (MPS) server on port 4433. Your MeshCentral server will generate a TLS certificate for the MPS server that is long standing. In this case, valid until year 2049. This is important since, unlike the TLS certificate on port 443 that you change every year, the CIRA certificate should be more long term. MeshCentral will take the private root of the MPS TLS cert and load that up in all Intel AMT devices. So, AMT will connect back to the server on port 4433 and trust it's connected to the correct server. It's much safer this way, you can update your TLS certificate on port 443 as you want without having to worry about Intel AMT. This said, it's normal the browser will not trust the TLS cert on port 4433.

Hope that made sense. If not, let me know.
Ylian

**Comment by SurrounDTech** [comment]
Thanks for your reply Ylian, this has definitely helped with understanding the process.

**Comment by aggietallboy** [comment]
My apolgies for necro'ing this thread.
I also am setting this up for the first time, and for clarification.
On my DNS option 15, do I do "mydomain.com", or do I do the full "myserver.mydomain.com"
The cert I have is not a wildcard, and set to the myserver.mydomain.com.

**Comment by si458** [comment]
> My apolgies for necro'ing this thread. I also am setting this up for the first time, and for clarification. On my DNS option 15, do I do "mydomain.com", or do I do the full "myserver.mydomain.com" The cert I have is not a wildcard, and set to the myserver.mydomain.com.

You set the dns suffix to the full meshcentral cert name, so ie meshcentral.mydomain.com

**Comment by aggietallboy** [comment]
> > My apolgies for necro'ing this thread. I also am setting this up for the first time, and for clarification. On my DNS option 15, do I do "mydomain.com", or do I do the full "myserver.mydomain.com" The cert I have is not a wildcard, and set to the myserver.mydomain.com.
> 
> You set the dns suffix to the full meshcentral cert name, so ie meshcentral.mydomain.com

Thank you so much for the quick reply!!

**Comment by aggietallboy** [comment]
Welp... it's sooooo close.
I have been through all the variants I can think of... here's my sanitized config file

{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "ManageCrossDomain":["user//adminuser"],
    "cert": "myserver.mydomain.com",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "SooperSekritSessionKey!",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "webrtc": true,
    "WsCompression": true,
    "AllowHighQualityDesktop": true
  },
  "domains": {
    "": {
      "title": "My MeshCentral",
      "title2": "myserver.mydomain.com",
      "_minify": true,
      "newAccounts": true,
      "userNameIsEmail": true,
      "mstsc": true,
      "ssh": true,
      "AmtAcmActivation": {
        "log": "amtactivation.log",
        "certs": {
          "MySectigoCert": {
            "certpfx": "mycert.pfx",
            "certpfxpass": "mysekret!"
          }
        }
      },
      "amtManager": {
        "adminAccounts": [
          {
            "user": "admin",
            "pass": "mysekret!"
          }
        ],
        "environmentDetection": [
          "mydomain.com"
        ],
        "wifiProfiles": [
          {
            "name": "MyHiddenSSID",
            "ssid": "MyHiddenSSID",
            "authentication": "wpa2-psk",
            "encryption": "ccmp-aes",
            "password": "myssidsekretpass!"
          }
        ]
      },
        "agentCustomization": {
        "displayName": "AMT Agent",
        "description": "IT uses this agent for remote monitoring, management and assistance",
        "companyName": "MyCompany",
        "_serviceName": "",
        "fileName": "amtAgent",
        "image": "logo.png",
        "_installText": "",
        "_foregroundColor": "",
        "backgroundColor": "139,0,0"
      }
    },
    "testdomain": {
      "dns": "server.testdomain.com",
      "title": "my test server",
      "title2": "server.testdomain.com",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "mstsc": true,
      "ssh": true
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com,myserver.shortdomain.com,myserver.testdomain.com",
    "skipChallengeVerification": true,
    "production": true
  }
}

**Comment by aggietallboy** [comment]
Ugggggh... 4433 not 4443

All of a sudden i have at least manual join working

**Comment by aggietallboy** [comment]
well...
almost working
![image](https://github.com/Ylianst/MeshCentral/assets/10222174/cffeac60-282f-48fd-be7f-6c709866d1fb)

**Comment by aggietallboy** [comment]
Confirmed that I can connect to the local web browser -- http://localmachineip:16992 and https on 16993.
Desktop, Terminal and Intel AMT are all hanging loading/setting up to connect

**Comment by aggietallboy** [comment]
after a server restart, the buttons are back to grayed out.

**Comment by si458** [comment]
@aggietallboy plz open a separate issue and also include all the information the bug report asks you for
