### ISSUE TITLE
Print Screen not being sent

### ISSUE THREAD

**Issue by ClickLeft** [Ylianst/MeshCentral#2343]
Since updating from 0.7.78 to 0.7.79, I have noticed that the PrtScr button doesn't seem to work as expected, the remote machine is no longer taking a screenshot.

**Comment by Ylianst** [comment]
Can you give more details? Are you on the remote desktop tab? Remote device is Windows? Did the print screen button ever got remoted? It's unlikely that version change did anything to affect the print screen button.

**Comment by ClickLeft** [comment]
Yes, I'm on the Desktop tab. Remote device is Windows 10 and the Print Screen button was previously sent as expected. I have tried from several different computers, tried restarting (both sides), etc. It's now behaving like the Windows key, where it has priority on the local machine vs. remote.

**Comment by Ylianst** [comment]
What browser are you using? It should be that the change was the browser... not MeshCentral.

**Comment by ClickLeft** [comment]
I'm using Google Chrome. It did recently update too and I didn't correlate it. I will test on another system with an older version of Chrome tomorrow.

**Comment by Ylianst** [comment]
I need to do some testing on this. By the way, you probably know this already but there is a small camera icon on the bottom right to take a screenshot of the remote desktop.

**Comment by Ylianst** [comment]
Ok, I just added the "Print Screen" key to shortcut customization and it works for me. So you can add "shift-printsc" and "alt-print-sc" and send them using the send button on the bottom right. This is nice because it will work no matter the browser used. This will be in MeshCentral v0.7.81. Once published, let me know if it works.

![image](https://user-images.githubusercontent.com/1319013/110018179-e36a2b00-7cdb-11eb-9e52-67d803789b42.png)

![image](https://user-images.githubusercontent.com/1319013/110018106-d3524b80-7cdb-11eb-9f51-3b19098af826.png)
