### ISSUE TITLE
When i am accessing the Mesh server UI following issue getting in chrome browser

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#2353]
When i am accessing the Mesh server UI following issue getting in chrome browser

![image](https://user-images.githubusercontent.com/9078295/110110945-91a5cb80-7dd5-11eb-8500-4f9be506b629.png)

**Comment by LPJon** [comment]
@aimdharma1990 That is because the "cert authority is invalid". Have you tried using a different browser? If so and you have the same issue then you will need to renew your ssl certificate.

NOTE: The place that issued you your certificate....their certificate is now expired and that is why you are getting that message.

**Comment by aimdharma1990** [comment]
Hi,


But it's working in another browser. Only in chrome I am getting the same
error. The certificate is generated today only by mesh cental.

**Comment by LPJon** [comment]
@aimdharma1990 Then the issue is with Chrome. Unfortunately there isnt anything that the developers of MeshCentral can do to fix that. Purchasing a cert from somewhere else would fix it but most likely its because the cert is by Letsencrypt. Chrome is known for randomly not liking Letsencrypt Certs. You may try making sure MeshCentral is using the "fullchain" cert. Sometimes thats also a problem for Chrome.

**Comment by Ylianst** [comment]
@LPJon is correct. This error depends on how you configured your MeshCentral server. If your using the default TLS certificate, this is normal. If your server is on the Internet, your can use MeshCentral's support for Let's Encrypt to get a trusted TLS certificate. There is plenty of tutorials on how certificates work online, if your not familiar with TLS cert, I suggest starting there.
