### ISSUE TITLE
Type Function isn't always sending repetitive characters

### ISSUE THREAD

**Issue by zackrspv** [Ylianst/MeshCentral#2417]
**MeshCentral2 Version**: 0.7.95
**Windows Version**: Windows 10 Pro - 2009 [19042.867] (20H2)

When using the 'Type' button function, to send data over to the client, it strips all repeat characters. 

**NOTE**: This doesn't happen ALL the time, but it is VERY common in most web browsers, such as chrome, edge, firefox, and sometimes in notepad. 

**Screenshot**: 
![image](https://user-images.githubusercontent.com/1069198/112258241-628bb880-8c23-11eb-8140-6256a465f6d0.png)
In the image above, you can see the missing letters as highlighted and replaced with **_**, you can see the URL in the address bar showing that when pressing 'type' and pasting in the url, it still doesn't type it correctly. 

**NOTE**: This does appear to be a LENGTH issue, smaller links tend to paste better.

**Comment by rylangrant** [comment]
I've had a similar issue even entering passwords for login using the Type. If the password is abc1123 it will send abc123 and strip out the 2nd character.

**Comment by unguzov** [comment]
I just reverted to 0.6.70 and "Type" function works just fine.

**Comment by Ylianst** [comment]
This problem should have been fixed as of last week. Latest version should work now. A temporary solution is to go in remote desktop "Settings" and check "Use Remote Key Map". This will fix it on any of the versions released in 2021.

Version 0.6.70 and other really old versions will not have this problem since they only use "Remote Key Map" and don't use the new keyboard system.
