### ISSUE TITLE
One server: Agent connected with bad signature, holding connection.

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2436]
Good day.
I've been struggling with the problem for several days. Installation on one of the servers ends successfully and the agent starts. But it doesn't appear in MeshCentral. When starting the agent manually via cmd, I get the Connected status. On the server, the trace shows the error "Agent connected with bad signature, holding connection". I tried to reinstall the agent, re-download from the server.
The server certificate was checked. When opened via the web interface from the problem server, the serial number of the received certificate matches the real one.
At the moment of an attempt to connect the problematic agent, the Invalid PKCS8 signature and Bad key counters grow
The neighboring virtual machine was added normally, i.e. there shouldn't be any problems at the network level. We see this error only on one terminal server based on Windows Server 2019.
Maybe you need somewhere to clean the cache or the registry. I would be glad to any advice.

**Comment by elpibedeoro** [comment]
Hi,

I had a similar problem but it was not on a Windows Server. I quote the reply that Ylian wrote me, hope this will help. 

"Hi. So, the agent does connect to the server, but then the agent reports what TLS certificate it saw and the server needs to confirm this is correct. This error may be caused by an incorrectly configures reverse proxy or TLS offloader - If this is the case, all your devices will have this problem.

Now, if your devices generally work but your seeing this for one device only, one possibility is that one device is behind a corporate proxy that is a bit evil and acting as a man-in-the-middle for TLS connections. That is, the agent connects to the corporate proxy which will present a dummy corporate TLS certificate and decrypt the connection to inspect what is going on. If this is the case, the agent will tell the server it's seeing the corporate TLS cert and the server will not approve this.

From a security perspective, the server is doing the right thing and holding the connection. This will prevent the agent from trying the reconnect over and over again. You can set the config.json to ignore this and allow the connection anyway, but that would not be great for security.

Let me know if this helps. This is probably not someone trying to do anything bad, but rather a man-in-the-middle corporate proxy. I know these also exists on public WIFI on airplanes."

**Comment by Ylianst** [comment]
Two things you can try. One if to delete the "meshagent.db" and restart the agent. The other is to add the following line to the settings section and config.json:

```
"ignoreAgentHashCheck": true
```

This will lower the server security, but would be interesting to see if it makes a difference.

**Comment by AntonAndreevichMoroz** [comment]
Good day.  I went back to this problem again.  We tried to delete the meshagent.db file, it does not solve the problem.  "ignoreAgentHashCheck": true temporarily resolves the problem, agents can connect.  and in our installation we found 2 servers with this problem.  both of them act as a Windows terminal server, maybe it has some kind of connection.

**Comment by AntonAndreevichMoroz** [comment]
We checked it again after another massive addition of agents. There is some regularity in this problem. At the moment we have 7 such servers, 5 of which are definitely Windows terminal servers (2016 and 2019 versions). 2 more later we will clarify whether the role of RDS is raised there. Problem servers are located in different companies and different IT environments, the only thing that basically unites them is terminal services. Can I provide you with some kind of log or dump from these servers for diagnostics? What needs to be done for this?
Also, on some servers, I tried to update agents through the agent console. But that didn't help either. Agents have a signature error after disabling ignoreAgentHashCheck.
![image](https://user-images.githubusercontent.com/51225180/113502461-1c90f780-9535-11eb-8178-3855c129aba1.png)

**Comment by vitko-bg** [comment]
Just to confirm, you mentioned that you tried to delete meshagent.db and that did not help. Have you tried to delete meshagent.db and restart meshagent service on the problematic hosts?

**Comment by AntonAndreevichMoroz** [comment]
> Just to confirm, you mentioned that you tried to delete meshagent.db and that did not help. Have you tried to delete meshagent.db and restart meshagent service on the problematic hosts?

Oh sure. We even tried reinstalling the agent more than once, which also led to the deletion of meshagent.db

**Comment by si458** [comment]
closing as stale,
please try updating to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
