### ISSUE TITLE
Sub folders

### ISSUE THREAD

**Issue by Fredoberti11** [Ylianst/MeshCentral#2447]
Hello,
would there be the possibility of being able to create sub-groups?

**Comment by Ylianst** [comment]
Yes, you can add tags to devices and sort by "Group-Tags".

**Comment by yomono** [comment]
Hi, Ylian. Can I add a little comment about this Group-Tags option? (That was added by my request, btw 😄 )

The only problem I find with it is that if an Agent doesn't have an assigned TAG, it will not be show at all.
I think it should be shown anyway, in the group as it normally would be showed.
Because, if the idea is to "simulate" subfolders with this function, I'm forced to tag EVERY single agent, even if I want it to be in the "root" folder, instead of the "sub" (tag) folder.

I hope I was clear

**Comment by Ylianst** [comment]
Ok, just pushed the change into GitHub... if a device has no tags, it will be displays in the group when "Group-Tags" sorting is selected. This will be in MeshCentral v0.8.5 when it next comes out.

![image](https://user-images.githubusercontent.com/1319013/113804173-e1e4b600-9712-11eb-9107-a26041d0e496.png)

**Comment by yomono** [comment]
quick and great, as allways.
thank you
