### ISSUE TITLE
proposal HDD health through meshcentral

### ISSUE THREAD

**Issue by s-monzon** [Ylianst/MeshCentral#2460]
Good morning, I wanted to thank you for the professional commitment you give to the project, the truth is that it is a success, you have an immediate response to all problems.

In the institution where I work we are very satisfied with the solution, we use it in several of our areas, both as IT support department, department of networks and networks.

Today I wanted to propose the implementation of a web module that reports the health of the disk (hours on; amount of power, disk speed, reallocated sectors) as if it were a report of the crystal disk solution.
I am making an effort to understand the code and analyze the way to carry out this proposal.

Thank you very much for all the development and contribution to the community.

**Comment by smartekIT** [comment]
actually we could have this also in really handy view, for example looking at the "My Devices" page and while it's in thumb view, currently we are able to quickly identify which device has active connection because of that blue marker appear. how about we have another mark or call it sign or icon which refer to the HDD and it's always there but with different colours where each colour means different state of the hard drive:
Green colour: HDD is 40% free space
Yellow colour: HDD is 20% free space
Red colour: HDD is in low space state (10% free) and need attention.

of course referring to the partition where the agent installed on so it always refer to the C drive where the OS.

**Comment by smartekIT** [comment]
here is a screenshot from other system we use for different purposes but the RMM page looks like this:
![System Capture](https://user-images.githubusercontent.com/70715469/113575982-151b3c80-9662-11eb-96b3-6e12436e0d8f.PNG)

**Comment by smartekIT** [comment]
@Ylianst have you seen the screenshot? any interest?

**Comment by smartekIT** [comment]
I believe in the screenshot the code used was Angular.

**Comment by s-monzon** [comment]
What I would be referring to in addition to having information of the space of the hdd, would be to implement the health of it, this is useful being that by having a large computer park we can anticipate future failures, something like when running cristadisk info locally.

**Comment by si458** [comment]
sadly we cant get that type of information, but i can pull the status that windows uses to see if the drive is OK or not
![image](https://github.com/Ylianst/MeshCentral/assets/765314/1325bf99-ae16-4941-a8a1-bb58f2fea0a1)
