### ISSUE TITLE
Cannot upgrade to v. 0.8.5

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2493]
Hi,

I've tried to upgrade to v. 0.8.5 without success from v. 0.7.99
I'm on Debian 10, no proxy reverse.
 
Here is how I use to do it : 
- systemctl stop meshcentral
- cd /opt/meshcentral
- npm install meshcentral
- chown -R meshcentral:meshcentral /opt/meshcentral
- chmod -R 755 /opt/meshcentral/meshcentral-*
- systemctl start meshcentral

I've also tried to rename the _node_modules_ folder but I've got the same problem, MC2 still keep on v. 0.7.99.

First time I see that, older upgrades always passed with no problems.

Thanks for you help.

**Comment by yomono** [comment]
Why not use the in-built upgrade option from the web panel?

**Comment by elpibedeoro** [comment]
I have installed it with higher security so the server can't write it's own files. I have to update manually.

**Comment by Ylianst** [comment]
It's not in the original message, but I imagine that `npm install meshcentral` is showing that MeshCentral is correctly downloaded, but the older version is downloaded. So everything works, but `npm install` got an older version.

I have seen this before and has to do with the npm infrastructure. It usually fixes itself after a while, but you can also do this:

```
npm install meshcentral@0.8.5
```

This will force the download of a specific version. When you update using the web interface I changed the code last year to specifically add the version to download exactly because of this. Let me know if it works.

**Comment by elpibedeoro** [comment]
That's right, npm download the older version.
Thanks for your suggestion, I will do that when I go back to work.

Have a nice week-end.

**Comment by elpibedeoro** [comment]
Hi Ylian,

I use npm v.7.10.0. and I had to upgrade MC2 with `npm install meshcentral@0.8.16` as you suggested because `npm install meshcentral` still keeps the older version (7.99).

Thank you for your help, I think this can be closed.

Have a nice day.
