### ISSUE TITLE
Feature Request - Direct RDP / SSH connection (Agentless)

### ISSUE THREAD

**Issue by eldadh** [Ylianst/MeshCentral#2516]
First of all great software,

I would like to know if it is possible/planned in LAN/Hybrid Mode,
For the Server to make direct connection to agent less servers.
for instance over secure form of communication (VPN / LAN ) direct SSH / RDP / VNC Connection.
for example to Type 1 Hypervisors servers ( Proxmox / Esxi ). which dont allow agent installation

I would imagine adding a server in the devices tab, with ip / port / credentials, 
and use local novnc/webrdp/console to achieve the connection over LAN/VPN .  
Most important for me at least would be SSH (From the Meshcentral server to the device) 

Hope i have detailed the request , would be happy to elaborate if needed
eldadh

**Comment by AntonAndreevichMoroz** [comment]
That would be cool. We are also looking for an analogue that could work without agents via SSH or RDP. If such functionality is in MeshCentral, then you will not have to keep several systems and it will be possible to store all connections centrally.

**Comment by Ylianst** [comment]
I am working on this now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.8.21 with a new device group type for local devices. The server needs to be in LAN mode or Hybrid mode. Allows you to add devices manually and connect to them thru the server with Web-RDP and noVNC of the new version of the MeshCentral Router for Windows. Feedback appreciated.

![image](https://user-images.githubusercontent.com/1319013/116369005-c292f300-a7bd-11eb-9d6c-7e3825accb82.png)

![image](https://user-images.githubusercontent.com/1319013/116369218-fa9a3600-a7bd-11eb-8579-7a12322a03ce.png)

![image](https://user-images.githubusercontent.com/1319013/116369236-fe2dbd00-a7bd-11eb-85b7-4b6f802f7d3e.png)

**Comment by AntonAndreevichMoroz** [comment]
Good day. Thank you so much for your work. Through MeshRouter, communication works after updating. It does not connect via web-RDP, we see such an error in the logs on the server. I suspect this is due to a self-signed certificate. Could there be a checkmark allowing to make an exception for the certificate?
ERR: {"name": "node-rdpjs", "hostname": "debian", "pid": 13755, "level": 40, "msg": "NODE_RDP_PROTOCOL_X224_NEG_FAILURE (Failure code: 5 (see https: // msdn.microsoft.com/en-us/library/cc240507.aspx))\nError: Failure code: 5 (see https://msdn.microsoft.com/en-us/library/cc240507.aspx)\n at new ProtocolError (/root/node_modules/node-rdpjs-2/lib/core/error.js:40:8)\n at Client.recvConnectionConfirm (/root/node_modules/node-rdpjs-2/lib/protocol/x224.js : 221: 9) \ n at TPKT. <anonymous> (/root/node_modules/node-rdpjs-2/lib/protocol/x224.js:202:8 )\n at Object.onceWrapper (events.js: 286: 20) \ n at TPKT.emit (events.js: 198: 13) \ n at TPKT.recvData (/root/node_modules/node-rdpjs-2/lib/protocol/tpkt.js:110:7)\n at BufferLayer. <anonymous> (/root/node_modules/node-rdpjs-2/lib/protocol/tpkt.js:101:8 )\n at Object.onceWrapper (events.js: 286: 20) \ n at BufferLayer.emit (events.js: 198: 13) \ n at BufferLayer.recv (/root/node_modules/node-rdpjs-2/lib/core/layer.js:91:8)","time":"2021-04- 28T09: 39: 20.4 45Z "," v ": 0}

And is it possible to also add SSH through the browser, and not through the Router? So how is the Terminal tab on the other nodes? noVNC hasn't been prototype yet.

**Comment by Ylianst** [comment]
For Web-RDP, current you need to disable the "Network Level Authentication" on the remote machine. On Windows 10 you need to go in Remote Desktop Advanced Settings to disable it. I could look into fixing that as a separate issue.

![image](https://user-images.githubusercontent.com/1319013/116455782-555f7c00-a816-11eb-985b-89849ec28e7d.png)

![image](https://user-images.githubusercontent.com/1319013/116455827-601a1100-a816-11eb-9707-06a1235c5fdd.png)

For supporting SSH in the browser, that looks possible. That would also be a separate GitHub issue.

**Comment by eldadh** [comment]
RDP works, Should I Open a new issue?

**Comment by Ylianst** [comment]
Just added SSH file access in the "Files" tab when using the new "local devices" group type.

![MC2-SSH-Files](https://user-images.githubusercontent.com/1319013/119438419-000f7100-bcd5-11eb-996f-2e8fccac3f6d.png)

I am going to close this issue since the original feature requested is done. For other problems or requests, open a new issue.
