### ISSUE TITLE
Mesh Assistant not connecting

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#2518]
Hi Sir,

Thanks for this beautiful & Powerful  project, I value your efforts.

i am new to this project, 

The mesh assistant application is not connecting, But showing running status, 

I tried the same in approx 100+ systems.

Is there any functions/code in config.js to activate the assistant / its a new issue ?

**Comment by VINISHVV** [comment]
Dear @pggsadmin 
It's an open issue... Still not resolved. 

I think it's little complicated else @Ylianst / @krayon007  will resolve this in couple of days...

**Comment by Ylianst** [comment]
I need to work on this. It looks like on some computers, Mesh Assistant can see the Mesh Agent service is running, but it can't connect the named pipe. It may have to do with computers connected to a domain controller or something like that.

**Comment by krayon007** [comment]
On the machines where the assistant is not working, from an elevated command prompt,  can you navigate to the `Program Files` folder and navigate to where the agent is installed and run the command: `MeshAgent -state`

The above command connects to the same IPC that the MeshAssistant does. This will provide a starting point for us to figure out what is going on.

**Comment by VINISHVV** [comment]
@krayon007 - I am little confused, Because i am getting different type of response  while querying   MeshAgent -status

Please find the below screenshot of windows-10 64bit.

![image](https://user-images.githubusercontent.com/65057910/115120923-aa58f200-9fcd-11eb-92e7-b12230d82065.png)


Please find the below screenshot of windows server 2012 64 bit.

![image](https://user-images.githubusercontent.com/65057910/115120932-b5138700-9fcd-11eb-8ed0-2c74ea9319d6.png)

**Comment by krayon007** [comment]
This is a good start, that means the IPC is working correctly. It means the Mesh Assistant application is not using the correct NodeID. @Ylianst

**Comment by krayon007** [comment]
Sorry, I looked at the wrong screenshot... On the one that isn't responding, what does it say if you do:
`MeshAgent -name`

**Comment by krayon007** [comment]
On the meshagent that didn't respond to the -state parameter, I assume it is connected to the server? If so, can you type `fdsnaphot` on the console tab, and let me know if you see the net.ipcServer object in it.

**Comment by VINISHVV** [comment]
@krayon007 

Sorry since the first computer (windows 10) having some antivirus block. Now i am getting same response for both PC's. 

tried few other system its also showing same response,

![image](https://user-images.githubusercontent.com/65057910/115122339-0c692580-9fd5-11eb-87ee-83db4ca1c046.png)

**Comment by krayon007** [comment]
So you are saying now all your machines are responsive to `MeshAgent -state` but not the MeshAssistant? I assume you are not using any customizations, since -name returned `Mesh Agent`? @Ylianst will need to take a look at the MeshAssistant to verify it is using the correct NodeID to talk to the Agent's IPC.

**Comment by krayon007** [comment]
On a side note, what AntiVirus are you using, and how was it configured to block the IPC? I ask, because MeshAssistant is using the same IPC that the `MeshAgent -state` command was using.

**Comment by VINISHVV** [comment]
> So you are saying now all your machines are responsive to `MeshAgent -state` but not the MeshAssistant? I assume you are not using any customizations, since -name returned `Mesh Agent`? @Ylianst will need to take a look at the MeshAssistant to verify it is using the correct NodeID to talk to the Agent's IPC.

@krayon007 - i am not using any agent customization. 
 all the agents are responsive to   'MeshAgent -state'


> On a side note, what AntiVirus are you using, and how was it configured to block the IPC? I ask, because MeshAssistant is using the same IPC that the `MeshAgent -state` command was using.

I am using Symantec end point security.

**Comment by Ylianst** [comment]
I think I just fixed MeshCentral Assistant. New version is [available here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralAssistant.exe). I also just published MeshCentral v0.8.16 with the updated version in the "node_modules/meshcentral/agents" folder.

Let me know if this works.

**Comment by VINISHVV** [comment]
@Ylianst 
Thanks for quick fix.
Assistant application working fine.

**Comment by pggsadmin** [comment]
Upgraded to latest version and everything working fine now. 

Thanks to @Ylianst / @krayon007 for quick resolution.
