### ISSUE TITLE
Black Screen at Login Screen on Debian 9 Stretch

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#253]
Much like the mac osx login screen\black issue, we are seeing this on Debian 9

**Comment by Ylianst** [comment]
Bryan is the one working on remote desktop for Linux, Windows and MacOS. My understanding is that we can't capture the login screen on many Linux distributions, however MeshCentral should display the error when this happens.

**Comment by krayon007** [comment]
I'll build a Debian 9 image to test to make sure this is indeed what is happening... But to explain, what it might be:

I've found that on some newer Linux Distros that use XWayLand instead of XOrg, that they are sometimes configured to not use an xauthority when a user is not logged in. When this is the case, I'm unable to connect/authenticate to the XServer to scrape the login screen.

When I get the Debian 9 image up and running, I can verify if this is the case for this distro, and make sure that an error dialog is displayed on the browser trying to connect.

**Comment by krayon007** [comment]
Which desktop manager are you using? Debian Desktop Environment, GNome, KDE, Cinnamon, etc?

**Comment by dinger1986** [comment]
never replied to suggest closing @si458
