### ISSUE TITLE
Info regarding Webrtc - status

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#2540]
Dear Ylian, 

I have enabled webrtc in my server. Since I don't find any difference. Please suggest Is there any mechanism to check whether it's working / not  ?.

**Comment by VINISHVV** [comment]
@Mfinadmin -I think WebRtc is enabled by default. 

I dont understand your actual issue, but If it's related to  bandwidth/ latency then please add below command in config.js  -> settings section.

 "compression": true, 
 "wscompression": true, 
  "agentwscompression": true,

**Comment by Mfinadmin** [comment]
@VINISHVV - Yes my issue is related to bandwidth / slowness /agent non responsive during more than 7 users sessions,

 I will modify the config as per your suggesion and share my findings

**Comment by Ylianst** [comment]
Hi. If you are having many users look at the same remote desktop at the same time, take a look at this [YouTube video on the desktop multiplexor](https://www.youtube.com/watch?v=r0IfzuZgf3s&t=31s). Once you turn that one, the performance will be a lot better as the server will "split" the desktop stream and adjust the stream to match the speed of each user's connection. You can enable it be adding the following line in the settings section of the config.json:

```
"DesktopMultiplex": true
```

As for WebRTC, that will not help if you have lots of users watching the same desktop at the same time. It will save bandwidth for most normal sessions but we did disable it because there are a few stability bugs with it. To enable it, you need to add the following line in the settings section of the config.json:

```
"WebRTC": true
```

At the same time, you need to add "&webrtc=1" in the URL. WebRTC will not work for remote desktop if the desktop multiplexor is enabled. In general, I don't recommend enabling WebRTC right now until Bryan fixes it.

Let me know if this helps,
Ylian

**Comment by Mfinadmin** [comment]
@VINISHVV - after implementing compression, getting better performance. Thanks. 

@Ylianst - Thanks desktopmultplex works awesome.
