### ISSUE TITLE
Connecting to remote MySQL database with enforced TLS

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2557]
Can MC2 connect to a remote database with enforced TLS? 

(When I connect using the mysql client, I can use the `--defaults-extra-file` option to contain my connection parameters, including the path to the certificate I have to present, along with the SSL mode, which I've provided for context in the hope that it's useful:

<details>
<summary>mysql.params</summary>

```
[client]
host = name-of-my-remote-mysql-host
user = mc2
password = "mc2_user_password"
ssl-ca = /location/of/certificate.bundle.pem
ssl-mode = VERIFY_IDENTITY
```
</details>

I then invoke `mysql --defaults-extra-file=mysql.params` to connect.)

From the complete `config.json` [options available](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json) the MySQL section doesn't contain anything regarding connecting securely, but I seem to remember it being mentioned in prior discussions here, that it could be posisble?

**Comment by D4V3M0NK** [comment]
Update : found the complete JSON options available can be found [here](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json)

**Comment by nzalev** [comment]
> Can MC2 connect to a remote database with enforced TLS?
> 
> (When I connect using the mysql client, I can use the `--defaults-extra-file` option to contain my connection parameters, including the path to the certificate I have to present, along with the SSL mode, which I've provided for context in the hope that it's useful:
> 
> mysql.params
> ```
> [client]
> host = name-of-my-remote-mysql-host
> user = mc2
> password = "mc2_user_password"
> ssl-ca = /location/of/certificate.bundle.pem
> ssl-mode = VERIFY_IDENTITY
> ```
> 
> I then invoke `mysql --defaults-extra-file=mysql.params` to connect.)
> 
> From the complete `config.json` [options available](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json) the MySQL section doesn't contain anything regarding connecting securely, but I seem to remember it being mentioned in prior discussions here, that it could be posisble?

The MySql and MariaDB options were passed in directly to the sql connectors. In a recent change, I began creating a new options object because including something like a `database` (name) option would cause the connection to fail during the automatic db creation feature.

I have a solution to this that should fix the above and allow passing arbitrary options in, but I am unavailable until late tonight or this weeked. Then, you should be able to specify the rest of the connection options in `config.json` as described in https://mariadb.com/kb/en/nodejs-connection-options/ or the MySQL equivalent

**Comment by D4V3M0NK** [comment]
@nzalev I'm *very* interested in this as it's the only hurdle that I see now in being able to deploy MC2 into a production environment.  Please do keep me up to date with your progress!  (and perhaps @Ylianst could/would be able to include it into the MC2 mainstream?)

**Comment by nzalev** [comment]
> @nzalev I'm _very_ interested in this as it's the only hurdle that I see now in being able to deploy MC2 into a production environment. Please do keep me up to date with your progress! (and perhaps @Ylianst could/would be able to include it into the MC2 mainstream?)

#2561 is enough to use ssl if you have a trusted CA signed certificate (this includes letsencrypt), but it will not work for self-signed certificates without disabling verification
If you have a proper certificate at MySQL/MariaDB, you can enable ssl by adding in your mariadb/mysql section of `config.json`
```javascript
 "ssl": true
```

I am still in the process of implementing the use of self-signed certificates.


---

Some additional notes:
- The minimum TLS version required by NodeJS is TLS1.2
- If you are using TLS1.1, you are out of luck :). I cannot get the connectors to work, even trying to override it for TLS1.1
- If you are using MariaDB 10.3 (latest ubuntu 20.04 for example), you are probably using TLS1.1
  - Upgrade to 10.5 (https://downloads.mariadb.org/mariadb/repositories/#mirror=globotech&version=10.5)

I have not looked into the TLS versions used in MySQL yet

**Comment by Ylianst** [comment]
Big thank you to @nzalev. MeshCentral v0.8.25 was just published with this fix. (Version v0.8.25 also includes an all new web-based SSH client).

**Comment by D4V3M0NK** [comment]
@Ylianst - is there a way of updating MC2 using the command line only and not the web GUI?

**Comment by D4V3M0NK** [comment]
It does, considerably, thanks @Ylianst 
@nzalev feedback coming soon!

**Comment by Ylianst** [comment]
@D4V3M0NK For the new web based SSH client, look at the image in #2558.

**Comment by nzalev** [comment]
> It does, considerably, thanks @Ylianst (web based client? Are there details published anywhere?)
> @nzalev feedback coming soon!

If you are using a self-signed certificate (from your mysql client config, it looks like you may be, since you are specifying a particular CA), the update in #2572 will add support for it.

A self-signed cert requires the sql connector to have the CA. The config.json looks like
```javascript
 "mariaDB": { 
      "host": "tts.zalev.ca",
      "user": "meshcentral", 
      "port": 3306,
      "password": "secretpass",
      "database": "_meshcentral",
      "ssl": {
        "caCertPath": "/etc/ssl/mysql/ca.pem"
      } 
    },
```

This also adds support for two-way ssl authentication. The options for the client cert and key are `clientCertPath` and `clientKeyPath`

Note that mysqldumps for the autobackups have not been updated for ssl, so make sure you have `require ssl` or `require x509` set at the database. This will be fixed by tomorrow.

**Comment by nzalev** [comment]
@D4V3M0NK The 0.8.28 update just released contains the completed MySQL/MariaDB TLS updates, as well as some version/compatability fixes. You can check the [meshcentral-config-schema.json](https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json) file for the config options.

I test with both MySQL and MariaDB on multiple versions, but mainly MariaDB.  Please let me know if there are any issues.

**Comment by D4V3M0NK** [comment]
@nzalev looks awesome - am hoping to get to test it out later on today, will let you know how I get on

**Comment by D4V3M0NK** [comment]
@nzalev thank you so much - it's all working perfectly!!

**Comment by D4V3M0NK** [comment]
@nzalev / @Ylianst as a follow up to this, does MC2 honor the same options as [the nodejs connection options page](https://mariadb.com/kb/en/nodejs-connection-options)? It appears (for example) that `ciphers` and `secureProtocol` are options in the connector, but I don't see either listed in the [meshcentral-config-schema.json](https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json) file. Does anything needs to be added to MC2 in order to make it work?

**Comment by nzalev** [comment]
Not all of them, but some of them. When MeshCentral processes the config.json file, it lowercases all the keys. If you included the `ciphers` option, it would work out of the box, but not `secureProtocol`. This is because `secureProtocol` gets transformed into `secureprotocol`, which is invalid for the database connector.

There is a method for adding exceptions to this process, ie, keep case sensitivity for a group of options. However, I avoided doing this for two main reasons
1. Users who use the incorrect casing will not be able to connect
2. JS is case sensitive and it would require a lot of changes in the code

Including the raw keys and calling it a day is also not a very suitable solution, because many options should have data loaded from a file. For example, if you need to load a ca certificate chain, it would not be very ideal to copy and paste it into config.json. This is why I included `caCertPath`, which will load the certificate/cert chain from a file, instead of just `ca`, which can still accept a cert in string form and work properly.

I can add additional options to the connector if you want.

PS: If you are trying to use `secureProtocol` to connect to an older release of MariaDB/Mysql (if I remember off-hand, MariaDB 10.3, standard release in Ubuntu 20.04, only supports TLS1.1), this will not work. NodeJS has a minimum TLS version which the connector cannot get around.


On Thu, 10 Jun 2021 08:00:22 -0700
Dave Monk ***@***.***> wrote:

> @nzalev / @Ylianst as a follow up to this, does MC2 honor the same options as [the nodejs connection options page](https://mariadb.com/kb/en/nodejs-connection-options)? It appears (for example) that `ciphers` and `secureProtocol` are options in the connector, but I don't see either listed in the [meshcentral-config-schema.json](https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json) file. Does anything needs to be added to MC2 in order to make it work?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Ylianst/MeshCentral/issues/2557#issuecomment-858697724


-- 
Noah Zalev ***@***.***>

**Comment by D4V3M0NK** [comment]
@nzalev Thanks for the detailed explanation. This is what happened for me - for some reason MC2 wasn't connecting to my remote database (which had been updated with additional security constraints, so it was kinda expected that I needed to enhance my connection parameters) - what I hadn't realized was that the MySQL (5.7) client also needed an update. For ease of use, I used an option file and had to add the following to the [client] section:
```
tls-version = TLSv1.2
ssl-cipher = AES256-SHA
```
As long as the cipher wasn't using short block sizes, I would be OK so went with an approved, but simpler one just for the time being.  Once I added those additional features to the option file, the MySQL client connected without issue.

Therefore, I added the following into the `settings > MySQL > ssl` section of the MC2 `config.json` file:
```
...
"secureProtocol": "TLSv1_2_method",
"ciphers": "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256"
...
```
After that - MC2 logged into the database without issue.

I mention all of this as I'm *sure* that the `secureProtocol` setting was critical and yet, you point out that it's likely not to be used as it inherrently becomes `secureprotocol` when parsed?

**Comment by nzalev** [comment]
> @nzalev Thanks for the detailed explanation. This is what happened for me - for some reason MC2 wasn't connecting to my remote database (which had been updated with additional security constraints, so it was kinda expected that I needed to enhance my connection parameters) - what I hadn't realized was that the MySQL (5.7) client also needed an update. For ease of use, I used an option file and had to add the following to the [client] section:
> 
> ```
> tls-version = TLSv1.2
> ssl-cipher = AES256-SHA
> ```
> 
> As long as the cipher wasn't using short block sizes, I would be OK so went with an approved, but simpler one just for the time being. Once I added those additional features to the option file, the MySQL client connected without issue.
> 
> Therefore, I added the following into the `settings > MySQL > ssl` section of the MC2 `config.json` file:
> 
> ```
> ...
> "secureProtocol": "TLSv1_2_method",
> "ciphers": "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256"
> ...
> ```
> 
> After that - MC2 logged into the database without issue.
> 
> I mention all of this as I'm _sure_ that the `secureProtocol` setting was critical and yet, you point out that it's likely not to be used as it inherrently becomes `secureprotocol` when parsed?

You have given me an idea: I need to check if the db connectors can take an options file.

I would recommend taking out `secureProtocol` and check if it works. The default minimum TLS version of the nodejs connector is TLS1.2 by default already.
