### ISSUE TITLE
web-SSH, web-RDP, noVNC gets access without MeshCentral authorization

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2563]
We found that noVNC, web-ssh and web-rdp links are available even without Mesh login. Checked in Incognito mode.
Links of the form:
https: //mc.server.ru/novnc/vnc.html?ws=wss...
https: //mc.server.ru/ssh.html?ws=E4...
https: //mc.server.ru/mstsc.html?ws=fAA...
Was this planned? In general, we even know how to use it for our own purposes, the only concern is the issue of security. Can these links be regenerated, do they have an expiration date, etc.?

**Comment by Ylianst** [comment]
This is normal, but may change this in the future. The URL includes a time limited cookie that is only valid for a few minutes. So, if you open the Web-SSH window and wait a few minutes and try to connect, it will tell you the session is expired. Because the time limited cookie is in the URL, switching to incognito mode will still work.

I may change this in the future to have it be cookie session based since it's a bit annoying that the cookie expires so quickly. Hope that makes sense.
