### ISSUE TITLE
Question: Web-SSH how to

### ISSUE THREAD

**Issue by baikal** [Ylianst/MeshCentral#2589]
Hi
I have seen the new Web-SSH feature. Added the "ssh":true in config.json, but no 'Web-SSH' links show up. The ssh2 node module got installed, though (is in node_modules now). Any hints on what to look for/troubleshoot to get it working.

**Comment by Ylianst** [comment]
Weird. It should show up here:

![image](https://user-images.githubusercontent.com/1319013/117199150-af27ef00-ad9e-11eb-9fe9-8816933c3b1e.png)

Note that if you have many domains, you need to put:

```
"ssh": true
```

In each domain you want this option to show up. Another possibility is that your using older web pages with a new server, this is not common but happens if you did your own HTML customization and have your own copy of the pages.

**Comment by Ylianst** [comment]
Oh, I think I found the bug... try adding this:

```
"ssh": true
"mstsc": true
```

Let me know if it works. The SSH option currently only show up if "mstsc" is also enabled... I will fix that.

**Comment by Ylianst** [comment]
Just put in a fix for this. Will be in MeshCentral v0.8.29. For now, you have to also enable "mstsc".

**Comment by baikal** [comment]
Hi Ylian
Thank you. Yes, adding mstsc:true fixes it on my server.

**Comment by baikal** [comment]
and on 0.8.29, also works without mstsc (but ssh:true of course). thanks.
