### ISSUE TITLE
One of the recent updates has issues with "agent bad web cert hash"

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2626]
I recently updated MeshCentral and I had to change "IgnoreAgentHashCheck" to true otherwise none of the 147 agents would connect anymore. 

I have a Caddy v2.3.0 proxy in front handling certificates. It must have been between version v0.8.23 and v0.8.25. 

In my logs I still have a valid certificate in version 23 but not anymore since 25. I am currently on v0.8.35 and it is still not working with "IgnoreAgentHashCheck" on false.

Any idea what might be causing this ? 

![image](https://user-images.githubusercontent.com/5128967/117939750-adaf7700-b308-11eb-8254-b629d40e0ab7.png)
![image](https://user-images.githubusercontent.com/5128967/117939931-d33c8080-b308-11eb-8a96-3c898d307612.png)

**Comment by Ylianst** [comment]
Hi. This is likely not caused by the update. This is a bit of a problem with frequent updates, everyone blames the update.

In any case, MeshCentral is trying to load the TLS certificate from Caddy, you can see the "Failed to load web certificate at:" line with a URL. Take a look at the URL and make sure it's correct. If not, edit the "certurl" in the config.json to a URL that will see the same certificate that agents see when they connect.
