### ISSUE TITLE
Easy Copy and paste feature

### ISSUE THREAD

**Issue by abraham990201** [Ylianst/MeshCentral#2637]
We know that if we want to copy or paste text, document, file we have to click in the "type" button in the bottom (in case of text) but, is there a way so you guys make this option straight forward? just typing CTRL+C and CTRL+V to paste whatever we want? such as TeamViewer does.

**Comment by Ylianst** [comment]
Yes, I need to work on that. Right now, you can use the clipboard push/pull options on the bottom right.

![image](https://user-images.githubusercontent.com/1319013/118197866-a8375700-b404-11eb-8fb9-ed4ec6acdfcd.png)

This said, it seems like if configured to do so, I should try to poll the clipboard and if it changes, send it to the remote device. This will be an option since there are security implications.

**Comment by VINISHVV** [comment]
@Ylianst - We understand the security issues, But if it is possible pls implement.

**Comment by Ylianst** [comment]
Automatic clipboard feature was added to MeshCentral v0.8.63 in both the main web site and MeshCentral Router.

![image](https://user-images.githubusercontent.com/1319013/122061066-060fe380-cda3-11eb-8f65-e25845197d60.png)

![image](https://user-images.githubusercontent.com/1319013/122061037-fee8d580-cda2-11eb-8256-77aab8cf47d1.png)
