### ISSUE TITLE
Mesh Commander not displaying the Desktop

### ISSUE THREAD

**Issue by MCJohnB** [Ylianst/MeshCentral#2643]
I have a lot of Dell OptiPlex's with vPro and finding out no matter the model example (7040, 7050) they randomly will not display the desktop, however all other functions work fine to my knowledge.  Any ideas of how to get the desktop display back up and running.   Using MeshCommander 0.9.0 and MeshCentral in AMT mode.

**Comment by Ylianst** [comment]
Three possible causes.

- The computer is not using Intel graphics. Intel AMT KVM will grab the frame buffer from the on-board graphic card only. Any add-on cards will stop KVM from functioning.
- There is no monitor plugged into the remote device. This may be fixed with BIOS update, or you can go on eBay and get a HDMI null adapter. It's a small dongle that makes is look like a screen is connected.
- The connected display is very high resolution (4k+). Intel AMT KVM has a 8M buffer for the screen. If the screen is larger, it will not be able to grab it. You can switch to 8 bit color and see if that fixes it.

**Comment by MCJohnB** [comment]
Thank you for the quick response is there any other ideas?
The systems are purchased with onboard Intel graphics cards with vPro and know other video cards on them.  We also have Dell Precision's 3040 with Nvida cards and the onboard intel graphics card with vPro and work with a few with the same issues.  It is more random.

**Comment by MCJohnB** [comment]
Could it be the Dell's version of AMT driver?

**Comment by jsastriawan** [comment]
It could be Standard Manageability.. which is a lower version of AMT without KVM.

**Comment by MCJohnB** [comment]
I would like to use Intel's Manageability.  Could you provide me of the URL to download?

**Comment by Ylianst** [comment]
If the system is "Standard Manageability", the desktop tab will not show up in MeshCommander.

**Comment by MCJohnB** [comment]
thank you for your help.  I will research it.
