### ISSUE TITLE
Windows Agent update failed after upgrade from 0.6.98 to 0.8.38

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#2649]
Hi, looks like it's similar to #2489 and #2291 but a bit different..
after MC upgrade to newest version, all my Windows agents fails to upgrade. all Linux agents works just fine.
![image](https://user-images.githubusercontent.com/60253253/118402695-ba6afc80-b673-11eb-8307-a1480a1e8f91.png)
i have a proxy server in between, and for security reasons, agents are allowed wss protocol only. so, the URL is correct, but protocol used is not. with previous versions there was not such a problem. How should i proceed? i heard of two different upgrade ways - when a server pushes it. if so, how can enable it?
Thanks,
Uldis

**Comment by Ylianst** [comment]
There are two different ways for the agent to update. The regular one uses the agent's websocket channel, the secondary update method uses a download URL. We had to do this because some of the older agents have a bug in the regular self-update code and so, the server knows what method to use depending on the agent.

If you roll back your server to 0.6.98, things should go back to normal... but sadly, to update to newer versions, you will have to unblock /meshagents?id=3 (32 bit windows) and /meshagents?id=4 (64 bit windows). Once unblocked, restart the server and agents should update normally.

**Comment by uldiseihenbergs** [comment]
Thanks for that! i can unblock for sure, but will it be one time action? and will any further updates work with websockets?

**Comment by Ylianst** [comment]
Further updates are back to websockets which is the normal update method. Obviously, you will need to unblock until all your agents are updated, so, if some agents come back online in a few days, they may need the link.

The two update methods are going to be in code going forward, but if all goes well, the HTTPS update method should not be used anymore going forward.

**Comment by uldiseihenbergs** [comment]
Thanks as usual. i have a small server with not so many agents - updated all online ones with Agentupdate command after unblocking https. 
BTW, just updated my Meshcentral docker too, it have >1M pulls already. crazy amounts, so just keep you project going :)

**Comment by Ylianst** [comment]
Oh nice! Thank for doing Docker and updating it. Yes, it's crazy, I can't keep up with all the requests.
