### ISSUE TITLE
Unable to run stateless

### ISSUE THREAD

**Issue by ken-lctech** [Ylianst/MeshCentral#2669]
I have just completed an installation of MeshCentral 0.8.40 (since updated to 0.8.43) on Ubuntu server 20.04 and would like to move to a stateless configuration. I am using MongoDB. I am able to push the configuration files into the database, and I can list the files to make sure they are there. Once I delete the data directory and launch with the --loadconfigfromdb option, I am not able to log in again. (Invalid password error.) It appears to be creating a new NeDB in the meshcentral-data directory rather than loading the config.json and existing database from MongoDB.

The settings portion of my config.json:
```
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "DbRecordsEncryptKey": "mykeyishere",
    "cert": "meshcentral01.mydomain",
    "WANonly": true,
    "port": 443,
    "redirPort": 80
  },
```

Launching with the following command:
node ./node_modules/meshcentral --loadconfigfromdb myconfigkey --mongodb "mongodb://127.0.0.1:27017/meshcentral"

**Comment by MailYouLater** [comment]
Are you sure about your launch command?  Looks like you're missing the `--configkey` before your `myconfigkey`.

**Comment by ken-lctech** [comment]
I've tried it both with and without. It's not there in the PDF documentation. I will try again this weekend. Thanks

Ken Ellefson | Director of Technology
Lake County Tech Campus
19525 W. Washington St. | Grayslake, IL 60030
Office: 847-543-6016

________________________________

**Comment by Ylianst** [comment]
I will need to give this a try. I have not tested stateless configuration in a long time and probably needs some fixing.

**Comment by MailYouLater** [comment]
I have also been experimenting with a stateless server recently, and I'm not having the issue that ken-lctech is.

@ken-lctech Can you post the full, exact text of the messages you're getting when you try to start up your MeshCentral server?  Also, is there anything more you can tell us about the server you're running it on that might help?

**Comment by ken-lctech** [comment]
It appears that MeshCentral is not loading any part of my config.json once it has been copied to the database. I can see it is there, and I can see a hex dump of it with `--dbshowconfigfile "config.json"`

Normal startup, before moving to stateless:
`./node_modules/meshcentral
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.8.40, WAN mode.
MeshCentral Intel(R) AMT server running on meshcentral01.mydomain:4433.
MeshCentral HTTPS server running on meshcentral01.mydomain:443.`

Startup after stateless:
`node ./node_modules/meshcentral --loadconfigfromdb --configkey myconfigkey --mongodb "mongodb://127.0.0.1:27017/meshcentral"
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.8.43, LAN mode.
WARNING: Unable to find mongodump, MongoDB database auto-backup will not be performed.
MeshCentral HTTPS server running on port 443.`

**Comment by MailYouLater** [comment]
> It appears that MeshCentral is not loading any part of my config.json once it has been copied to the database.

Well, I know it's reading some parts from the DB for me, because I can change some parts of the config locally, push the config to the DB, log in to MC and run `resetserver`, and my changes take effect without having to modify the actual config file sitting on the server.  I've used this method to add a `redirects` section after getting the server up and running.

> Normal startup, before moving to stateless:
> ```
> MeshCentral v0.8.40, WAN mode.
> ```
> Startup after stateless:
> ```
> MeshCentral v0.8.43, LAN mode.
> ```

If it's switching to LAN mode, that may be caused by not using part of the config from the DB, but if it's getting the correct certs from the DB, then it should switch to WAN or Hybrid mode anyway.  Are your certs not in the DB?  
Can you post the output of `node node_modules/meshcentral --dblistconfigfiles`?

> Also, since I didn't mention it earlier, the command to push the config files into the database doesn't seem to work without specifying the actual path.
> `node ./node_modules/meshcentral --dbpushconfigfiles * --configkey myconfigkey`
> 
> Results in the following:
> `ERROR: No config.json in folder meshcentral-backup`
> 
> No files are copied to the database. Instead, I used:
> `node ./node_modules/meshcentral --dbpushconfigfiles ./meshcentral-data --configkey myconfigkey`

I've been using `node node_modules/meshcentral ---dbpushconfigfiles --configkey <configkey>`.  Without supplying any string to tell it which directory to push, it pushes the `meshcentral-data` folder.

As a temporary workaround to this issue (now that I'm deploying without any `meshcentral-data` folder) I have my startup script run two commands.
First it downloads the config (as it is when the server starts) with `--dbpullconfigfiles`
```
node node_modules/meshcentral --mongodb $MONGODB --configkey $CONFIGKEY --dbpullconfigfiles meshcentral-data
```
Next it runs the server as if `--loadconfigfromdb` was working correctly.
```
node node_modules/meshcentral --mongodb $MONGODB --configkey $CONFIGKEY --loadconfigfromdb
```

Since it was launched with the `--loadconfigfromdb` parameter, restarting the server via the server console will cause it to use a new config if I push one, and I can get away with using `--loadconfigfromdb` now because the parts that it won't read from the DB are now also in the (now appropriately placed) `config.json` file.

It's not a fix, just a workaround, but it works for me for now.  Looking forward to seeing a proper fix in the future though.

**Comment by ken-lctech** [comment]
The output of `node ./node_modules/meshcentral --dblistconfigfiles` lists my config.json, as well as four certificates and matching private keys. I am still using a self-signed certificate at the moment. I will probably not be able to revisit this until later unfortunately. I have rolled back my changes to prior to setting up as stateless in order to move forward with the deployment.

**Comment by MailYouLater** [comment]
> It seems that some settings still get loaded from the `config.json` instead of the database when using `--loadconfigfromdb`. IDK if there are others or not, but at the very least, `TLSoffload` and `DBrecordsEncryptKey` have this issue.

Add `cookieEncoding` to the list of settings that are not loading from DB.

I removed `"cookieEncoding": "hex"` on a local device, pushed the new config to the DB, then ran `resetserver` on my server and saw no change, but after the server had performed a more complete reboot from scratch (at which point I have it set up to run once with `--dbpullconfigfiles` before it launches for real with `--loadconfigfromdb`, my workaround to be able to run semi-stateless) my existing `/agentinvite` links stopped working.  After adding `"cookieEncoding": "hex"` back to my config, pushing it to the DB, then running `resetserver` on the server, my existing `/agentinvite` links continued to fail until I rebooted the server to trigger it to 're-pull' the config files on the server, after which they started working as expected again.

**Comment by MailYouLater** [comment]
Bump!

Hello, I have reason to ~play with~ *test* MeshCentral again, and I was just wondering if there had been any improvement in the handling of stateless configurations in the last year?  Do I still need to use the semi-stateless workaround (launch with `--dbpullconfig` first so the server has a local copy of the config it can read from) or can I get away with just launching it a single time with the `--loadconfigfromdb` parameter?

**Comment by si458** [comment]
closing as stale, if still an issue, try latest version and latest lts of node, then report back
