### ISSUE TITLE
Ability to Uninstall from Dashboard

### ISSUE THREAD

**Issue by penguinthingie** [Ylianst/MeshCentral#268]
Hi Ylianst,

Thank you so much for an awesome solution! I was wondering if there is any plan to allow for the agent to be remotely uninstalled via the actions option so the next time the agent checks in with the server, it processes the command to uninstall itself and removes it from the dashboard as well.

Thanks!

**Comment by krayon007** [comment]
This capability is actually present in the upcoming Agent Release. I needed to add this capability specifically for the MacOS agent, because the way you do user-consent on MacOS is rather tedious. I had to dynamically install/spawn a user launchagent, to be able to popup interactive dialogs on the user's desktop, and then have it auto-cleanup and uninstall itself, etc.

The capability should work on all 3 supported platforms, I just need to have Ylian add the UI elements to the webpage to be able to instruct the agent to be able to uninstall itself. If it doesn't make it into the upcoming release, a simple patch will be able to add it, as all the needed native stuff is in the upcoming release, just an update to the JS is all that would be necessary to complete the feature as described in this thread.

**Comment by penguinthingie** [comment]
That's great to hear! When you say upcoming release, are we talking within 0.3.5 branch or much more in the future? Thanks!

**Comment by Ylianst** [comment]
Once Bryan releases the new MeshAgent, I should be able to add this feature to the server fairly quickly. I am always hesitant to give timelines... hopefully this week or next.

**Comment by MailYouLater** [comment]
Duplicate #449, #581

**Comment by Ylianst** [comment]
Correct, this is duplicate. Closing, please use #581.
