### ISSUE TITLE
Larger Linux Terminal

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#269]
Would it be possible to increase the size of the Linux terminal screen, from it's default 80 characters to something wider? It would be a perfect companion to the now completed #258. Perhaps even have this as a configurable option: if it's not defined, use the standard 80 characters, otherwise set to the defined value.

**Comment by Ylianst** [comment]
I expected this one to be requested :) I will see what I can do.

**Comment by D4V3M0NK** [comment]
You can just call me Mr Linux ... ;o)

**Comment by Ylianst** [comment]
MeshCentral v0.3.5-z :) It's not perfect. I can't dynamically change the terminal size, xterm does not allow it so, I have to set it upon connect.

![MC2-TerminalSize](https://user-images.githubusercontent.com/1319013/58988228-088fd980-8796-11e9-9284-c32e69c5ae88.png)

**Comment by D4V3M0NK** [comment]
Ylian,
Certainly a move in the right direction. I see that the "Auto" can't be altered - that's what you were referring to?  Are you attempting to set it upon connect or have it adjustable once the user connects? All told, it's potentially going to be more flexible to have it user adjustable once connected so that the user can select one resolution if on a PC, another if on a mobile device...

**Comment by Ylianst** [comment]
The terminal size selection drop down is can only be changed when the terminal is disconnected. This is because right now, I can only set the terminal geometry when starting the terminal. Just hit the disconnect button, change it and connect again. If you leave it on auto, you can disconnect, resize the browser and hit connect again. I would like it to be dynamic size in the future, but I will probably need some MeshAgent tricks.

**Comment by D4V3M0NK** [comment]
Ah yes, I see that now. Auto gives what appears to be the biggest screen size.  Although ideally the font could be smaller (or adjustable?), this totally resolves the original issue, so I'll close. Thank you sir.
