### ISSUE TITLE
dupagents and agentissues console commands

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#2702]
Hi,
sorry i was check the commands available on the console tab of the server so i issues a (dupagents) command. i'm pretty sure it did something, so now when i issue (agentissues) command i get a list of agents with issues:
3:56:33 PM, xxx.xxx.xxx.xxx:xxxxx, duplicateAgent,

so what i've done and what that means?
sorry again for my stupidity.

**Comment by Ylianst** [comment]
No worries. If you are talking about the "Console" tab in "My Server" like this:

![image](https://user-images.githubusercontent.com/1319013/119887424-fb230b00-bee8-11eb-8a0b-93e5557aee24.png)

The "dupagents" only shows that duplicate agents have been detected. It does not do anything and not a dangerous command, use it anytime you like.

Duplicate agent event happens when the server is connected to "Agent A" and received another connection from "Agent A". This can happen in rare cases if you clone a computer and so, both computers have the same agent certificate and so, they both think they are "Agent A" and both try to connect to the server. But we have code to detect and avoid this, so this is not often the problem.

In most cases, "Agent A" is on a WIFI laptop for example and when WIFI is dropped and reconnected, that agent will reconnect to the server. The server had connection to agent A and did not receive any notification that the connection is closed and Agent A connects again. So, the server will drop the old connect and take the new one. This is normal and will cause a duplicate agent event.

So, if this happen occasionally, it's completely normal. If this happens often because of a computer was cloned, then you may need to uninstall and re-install the agent on the cloned computer, but this should not happen.

Hope that helps,
Ylian

**Comment by smartekIT** [comment]
thanks alot. by the way none of the commands in that console has help available, so when you go (help dupagents) you get nothing and so on for the rest of commands !

**Comment by Ylianst** [comment]
Ha yes, having help for each command could be a nice request.
