### ISSUE TITLE
Guide how to sign MeshService64.exe MeshService.exe

### ISSUE THREAD

**Issue by uniuuu** [Ylianst/MeshCentral#2733]
Hi @Ylianst 

Please confirm the steps to sign agents.
I've tried to use [Let's Encrypt](https://letsencrypt.org/) key generated by [ACME provider in Traefik](https://doc.traefik.io/traefik/https/acme/) and signed with [osslsigncode ](https://packages.debian.org/search?keywords=osslsigncode) tool.
(_**Unfortunately during writing this post realised that they only issue certificates only for TLS server authentication**_) 
**[Signing with LetsEncrypt.org](https://stackoverflow.com/questions/35184264/signing-a-visual-studio-app-with-letsencrypt-org-ssl-certificate)**

`
osslsigncode sign -certs meshcentral.crt  -key meshcentral.key -n "Meshcentral" -i https://mywebsite.org  -t http://timestamp.digicert.com -in MeshService64.exe -out MeshService64-newsigned.exe
`

The I've replaced `node_modules/meshcentral/agents/MeshService64-signed.exe` with MeshService64-newsigned.exe.

I've downloaded file with `signtool`and it show that the file is signed.
```

c:\Program Files (x86)\Windows Kits\10\App Certification Kit>signtool.exe verify /v "D:\Downloads\meshagent64-Mygroup.exe"

Verifying: D:\Downloads\meshagent64-Mygroup.exe

Signature Index: 0 (Primary Signature)
Hash of file (sha1): 8303CFD6FEHHHHHHE39100224F24B84FFD523BC

Signing Certificate Chain:
    Issued to: DST Root CA X3
    Issued by: DST Root CA X3
    Expires:   Thu Sep 30 22:01:15 2021
    SHA1 hash: DAC9024F54D8HHHHHH35FB1732638CA6AD77C13

        Issued to: R3
        Issued by: DST Root CA X3
        Expires:   Thu Sep 30 03:21:40 2021
        SHA1 hash: 48504E974C0DHHHHHH476C8202274B24C8C7172

            Issued to: mydomain.org
            Issued by: R3
            Expires:   Fri Aug 20 14:23:24 2021
            SHA1 hash: 63990910D60HHHHHHB1A1664296AC77B2DFE095

The signature is timestamped: Sat Jun 05 16:49:21 2021
Timestamp Verified by:
    Issued to: DigiCert Assured ID Root CA
    Issued by: DigiCert Assured ID Root CA
    Expires:   Mon Nov 10 08:00:00 2031
    SHA1 hash: 0563B8630D62HHHHHH8AB1E4BDFB5A899B24D43

        Issued to: DigiCert SHA2 Assured ID Timestamping CA
        Issued by: DigiCert Assured ID Root CA
        Expires:   Tue Jan 07 20:00:00 2031
        SHA1 hash: 3BA63A6E4841HHHHHHEBEF9CDCF4D5AF353A297

            Issued to: DigiCert Timestamp 2021
            Issued by: DigiCert SHA2 Assured ID Timestamping CA
            Expires:   Mon Jan 06 08:00:00 2031
            SHA1 hash: E1D782A8E19HHHHHHCA1691B5AAB494A6249BF3

SignTool Error: A certificate chain processed, but terminated in a root
        certificate which is not trusted by the trust provider.

Number of files successfully Verified: 0
Number of warnings: 0
Number of errors: 1

c:\Program Files (x86)\Windows Kits\10\App Certification Kit>
```

As per `SignTool Error: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.`
the downloaded file still shows below message 
![image](https://user-images.githubusercontent.com/26146469/120887252-4c877480-c624-11eb-881e-52997a0dbeb6.png)

Since it was unfortunate to get around with Let's encrypt taking this opportunity I want ask to whether it's possible to sign agent in your source code and register it with Microsoft for example via https://www.microsoft.com/en-us/wdsi/filesubmission due to be incorrectly classified as malware? 
Reference: https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/developer-faq

**Comment by PathfinderNetworks** [comment]
I would also love to know how to sign the agent so that Windows SmartScreen and other antivirus apps, etc would play well (or better) with it.

**Comment by Ylianst** [comment]
So, you did sign the executable correctly... however, you can't use a Let's Encrypt certificate or any TLS certificate to sign a binary. Certificates have "usage" flags and there is one such usage flag for code signing. Windows will see that the binary is signed by a certificate that does not have the binary usage flag and fail the check.

Getting a code signing certificate is much more difficult than getting a TLS cert. You generally need to send some personal or company ID, certainly not free and in some cases you need to see a notary. I recently for a [open source code signing certificate from Certum](https://www.certum.eu/en/). I use it to sign the MeshCentral Router, MeshCentral Assistant, MeshCentral Installer and MeshCommander. Since the MeshCentral Assistant has a built-in agent, in some cases for report support, you can use that.

The problem with signing the MeshAgent is that it's often reported as a virus and in the past I got a code signing certificate and signed the agent only to get my certificate revoked without notice. Turns out, Google make a list of 150 certificates that where signing suspicious malware and the CA just revoked the cert. What was really bad is Windows stopped running that executable and all signed MeshAgents dropped off the network in one go. So, I will not be signing the MeshAgent anymore.

Hope that helps,
Ylian

**Comment by uniuuu** [comment]
Hi @Ylianst 

Thank you for the information.
I've done some research and here just a quick update in case you might change mind and try get through this one.
The **[EV Code Signing](https://docs.microsoft.com/en-gb/archive/blogs/ie/microsoft-smartscreen-extended-validation-ev-code-signing-certificates)** can fix it I believe. Here is quote:

```
Programs signed by an EV code signing certificate can immediately establish reputation
with SmartScreen reputation services even if no prior reputation exists for that
file or publisher. 
```

Alexander

**Comment by Ylianst** [comment]
Yes, EV certificates are expensive and Certificate Authorities will have more requirements before issuing them.
