### ISSUE TITLE
MeshCentral Windows Service

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#276]
So here's a very strange thing I just noticed (not sure if it started with 0.3.6-c or some other version as I just am now noticing it).  
I'm running MeshCentral on Server 2019 as a Windows service.  Normally, when I need to make changes to something in the backend (or just want to copy the entire MeshCentral folder as a backup before I do a server update) I will stop the MeshCentral Windows service.  In the past that completely shut down MeshCentral- as one would expect.
Well, not any longer.  When I stop the MeshCentral service I am now noticing that the Node.js: Server-side JavasScript processes don't stop.  The result of this is that MeshCentral keeps on running- even though the MeshCentral service has been stopped.  The only way I can now force MeshCentral to shut down is to forcefully kill all of those (three of them) Node.js processes.  To start it back up I just start the MeshCentral service.  
I realize there may be some other way to stop the MeshCentral service (such as through the console) but there is still something very strange going on in relation to the MeshCentral service and Node.js. In the past stopping the MeshCentral service would cause the Node.js processes to terminate.

**Comment by mschubeck** [comment]
I'm on 0.3.6-r and stopping the service makes the system inaccessible.  I don't see any separate Node.js services, and all 3 Node.js processes stop properly, as expected.  Restarting the MeshCentral service loads them all again.  Try to upgrade to the latest revision and see if ti was a temporary bug.

**Comment by Ylianst** [comment]
Oh dear. This is not good. I use "[node-windows](https://www.npmjs.com/package/node-windows)" module to make MeshCentral runs as a Windows service. I have noticed that after an upgrade, I have to run "node ./node_modules/meshcentral -install" again to get the service running again.

**Comment by Ylianst** [comment]
FYI. I fixed this one a while back by no longer allowing MeshCentral to self-update when running as a Windows Service. You will need to use the MeshCentral Installer to perform the update or manually using "npm install meshcentral" and "node ./node_moudles/meshcentral --install".

I had to do this as performing self-update when running as a Windows Service is not possible.

**Comment by MailYouLater** [comment]
I was just thinking about this, and I think the only way to get around this would be to install a 'meshupdater' service, which would stop the meshcentral service, perform the update, then start the meshcentral service again.  I don't know if you want to do something like that, but I do believe it would make it possible to at least trigger an update remotely, even if you probably still don't want fully automatic updates on a server (which should also be possible this way, even if not desired).
Also, this second service could be set to only start when triggered, so that it's not running all the time, or even only get installed when you trigger an update, you could potentially even automatically uninstall it after the update was completed if that was desired, though perhaps that's going too far.

**Comment by Ylianst** [comment]
So yes, there are a few ways to get around this problem and make the MeshCentral Windows Service self-upgrading. I would need to spend time on it but of course, there is plenty to do. I will see what I can do, but it will take a while.

**Comment by MailYouLater** [comment]
I don't know if it's even worth it, but I just had an idea and thought I should post it, in case you were wanting this feature, and unsure how to approach it.

**Comment by Ylianst** [comment]
Well, I published "[MeshCentral Installer 1.8](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralInstaller-1.8.exe )" and "MeshCentral v0.3.9-n". If you use the new MeshCentral installer to update your server to 0.3.9-n or higher, the server will became capable of self-upgrading after this.

I create a new "winservice" folder outside the "node_modules" and put an updated "winservice.js" file in it. Because it's outside the "node_modules" folder, I can how update using NPM without breaking the windows service.
