### ISSUE TITLE
Intel AMT - How to use IDER to reimage a remote device

### ISSUE THREAD

**Issue by sysadmin-us** [Ylianst/MeshCentral#2766]
How to use the IDE-R & SIDE-R (serial over lan) option for AMT machine via MeshCentral portal to re-image OS in case of OS crashes or enter bsod loop.

**Comment by jsastriawan** [comment]
IDE-R is basically you are mapping a remote ISO file as a virtual CD drive and a blank floppy image as a virtual floppy disk. 

Once you map those two resources, you can invoke custom AMT power command to reboot to IDE-R CDROM.

The system should then reboot using iso file that is streamed by MeshCentral.

Alternatively, if you have Bootp recovery, you can always force boot to Pxe and use your bootp menu to recover.

There is a newcapability to perform HTTPS boot on iso hosted over HTTPS webserver like netboot.xyz. But it will be available only on 12 generation Core.

**Comment by sysadmin-us** [comment]
@jsastriawan How much size of windows OS image file supported for IDE-R?

**Comment by jsastriawan** [comment]
I am guessing it was designed for CD ROM iso size (650M). I guess the best way is to use a WinPE iso to boot and then you map the recovery resources over local network. In this way you will have better performance.

Alternatively you can use ipxe.iso which in turn performs sanboot to local http server hosted ISO. You will have a much better performance because IO traffic is handled by CPU rather than CSME.

**Comment by sysadmin-us** [comment]
Hey @jsastriawan thanks for the info, 

Can you plz tell me how to ipxe.iso to install the OS over the network or from other drive partition ISO file?

**Comment by jsastriawan** [comment]
There are few examples here:

https://ipxe.org/howto/winpe
https://ipxe.org/howto/rh_san

For manual method, you can download ipxe.iso from here:
http://boot.ipxe.org/ipxe.iso
Then you can execute the following command on ipxe command prompt in sequence:
```
dhcp
sanboot https://boot.netboot.xyz/ipxe/netboot.xyz.iso
```

For further detail on sanboot command, see [sanboot](https://ipxe.org/cmd/sanboot)

If you are adventurous enough, you can rebuild ipxe.iso combining this as single sequence by modifying ISOLINUX.CFG
The step is:
1. Unpack the iso in a folder, let say ipxe-tpl
2. Modify ISOLINUX.CFG
```
SAY iPXE ISO boot image
TIMEOUT 30
DEFAULT ipxe.lkrn
LABEL ipxe.lkrn
 KERNEL ipxe.krn
 APPEND dhcp && sanboot https://boot.netboot.xyz/ipxe/netboot.xyz.iso
```
3. Rebuild ISO using the following command:
```
mkisofs.exe -quiet -o myipxe.iso -b ISOLINUX.BIN -c BOOT.CAT --no-emul-boot -boot-load-size 4 -boot-info-table -J -V "SANBOOT" -R ipxe-tpl
```
I hope this help, I just tried to copy my personal notes here. If you need further help, send me private email to joko dot sastriawan at intel.com or gmail.com. I will link you up to the right team.

**Comment by MailYouLater** [comment]
@jsastriawan Did you choose to IDE-R boot to ipxe.iso, then chainload netboot.xyz.iso instead of directly IDE-R booting to netboot.xyz.iso for a reason?  Is the size difference between them enough to make a notable difference in IDE-R boot time? or is there another reason to choose to IDE-R boot one over the other?

Just asking for future reference.  Thanks.

**Comment by jsastriawan** [comment]
The netboot.xyz.iso is just an illustration. You can change it to Ubuntu installation iso hosted on your local network.

Ipxe.iso size can be squeezed to 1MB so it will be significantly faster. Once ipxe.iso jumps to sanboot, the limit is your network speed.

Most Linux installer iso will work but apparently Windows iso does not work reliably because the Windows installer may not know that the iso resource is cached on ramdisk. The Wimboot method is prefered.

**Comment by sysadmin-us** [comment]
@jsastriawan What type of ISO files can be used with IDE-R to re-image remote device, like in a real case scenario, if OS corrupt so in this case should it be correct to boot with DOS OS ISO like we get command line interface, then install the Windows OS from the local network or the other partition drive on that same machine?

**Comment by jsastriawan** [comment]
DOS iso will do but typically on Windows environment Win PE image loaded with key drivers is used. For Linux environment, you can use standard Linux iso installer.
