### ISSUE TITLE
Does Meshcentral support MongoDB 2.6.12-6?

### ISSUE THREAD

**Issue by aztlanla** [Ylianst/MeshCentral#2776]
Hi, we are running CentOS 7.9. I'm not able to install MongoDB-org 4.0 due to a GLIBC 2.18 dependency. CentOS 7.9 goes up to GLIBC 2.17. We are not ready to use Cent 8/RHEL8 yet. 

CentOS 7 has MongoDB 2.6.12-6 will that work?

Thanks

**Comment by Ylianst** [comment]
I only tested MeshCentral on MongoDB 3.6 and higher. I may work for versions before that, but I have never tested it.

**Comment by aztlanla** [comment]
Thank, I'll setup a test server to test.

**Comment by Ylianst** [comment]
I would not be surprised if it worked, MeshCentral uses only basic MongoDB operations. Let us know if it works.

**Comment by aztlanla** [comment]
Looks like it works, but I got these warnings under "My Server"

> WARNING: Current version of MongoDB (2.6.12) is too old, please upgrade to MongoDB 3.6 or better.
> WARNING: Unable to find mongodump, MongoDB database auto-backup will not be performed.

I'm going to try 3.6, see if that works.

**Comment by aztlanla** [comment]
After adding the repo file for mongodb-org 3.6, I was able to install 3.6 and this version seems to work fine on CentOS 7.9.

**Comment by nzalev** [comment]
I know this is closed, but I want to add some clarification because I have used older versions of mongodb with newer versions of meshcentral.

There are some keys that will not work in the newer versions of meshcentral because the keys contain the period character, which is allowed in newer versions of mongodb but not older. These are not critical keys though and don't impact overall usability.

The more major issue is that the older versions of mongodump do not support the URI option, so automatic backups will fail. You can go into db.js and modify the mongodump command, but you will have to do this on each update to meshcentral (I wrote a script which updated meshcentral and performed the modifications I want).
