### ISSUE TITLE
File Browser [Question / Possible Feature Request]

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#2780]
This is more a question than anything else right now but it may lead to a request depending on the answer. When using the file browser for an agent-connected device, I'm assuming files uploaded to the remote machine are sent through the MeshCentral server first. Is that correct? If that is indeed how it works, is it possible to have the connection made directly between the local and remote devices if they're on the same network? This would make transferring large files far more feasible though I'm a little out of my element here so I don't know if this is something relatively easy to accomplish or even possible.

**Comment by Ylianst** [comment]
You are correct that files currently are transferred thru the MeshCentral server. This is the same for remote desktop and terminal.

There is a way to have direct browser-to-agent communication, it's called WebRTC. It's disabled by default because of a bug Bryan needs to fix in the agent's implementation of WebRTC. Once fixed and enabled, you can connect to a remote device and if possible, WebRTC will automatically be setup and then traffic can flow directly between browser and agent, bypassing the server.

So yes, if you want to open a bug asking for WebRTC to be fixed, you can do that. There are some odd things with WebRTC and I still not sure how to address. If you download a very large file over WebRTC, there may be issues... also not sure how I will handle desktop multiplexor when WebRTC is possible.

**Comment by PetieM** [comment]
Okay, that’s about what I expected and makes sense. Thanks for clarifying!
