### ISSUE TITLE
Question related to WebRTC and Task Schedule

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#2787]
Dear Ylian,

I have added  webRtc : true in my server to reduce the server bandwidth also I have deactivated multiplex functions.  Still my server showing same bandwidth utalization in stats.

Is there any options to check whether webRtc is functional or not ?

One more issue I noticed recently the meshcental services gets hang for few minutes. If I try some console commands like help the response getting delayed.the server memory and Cpu usage is below 20% only. I think it's related to some background tasks execution. Is it possible to view to task running in background /queue ?.

**Comment by Ylianst** [comment]
For WebRTC, we currently has this feature turned off because of a bug in the MeshAgent WebRTC. To turn it on, put `"webrtc":true` in the settings section of the config.json, also "DesktopMultiplex" must not be enabled. Then, you also need to add "&webrtc=1" on the web page URL.

Then, when you connect remote desktop, you will see "WebRTC" on the page. When enabled, the traffic goes directly between the browser and the agent. The server does not relay the traffic.

![image](https://user-images.githubusercontent.com/1319013/122266319-86f7d980-ce8e-11eb-9797-637146c5e196.png)

For command delay, this is not normal, I have not seen this on my servers. However, I don't have sufficient information to debug.

**Comment by Mfinadmin** [comment]
Dear Ylian,

is it possible to fix the issues related to webRTC ?
Also is there any possibility to skip the url modifications like add "&webrtc=1"

**Comment by Mfinadmin** [comment]
Dear Ylian,

I have disabled multIplex, enabled the webRtc : true in config.js also I have added the &webRtc=1 at the end of url.

But still the webRTC is not enabled ( webRTC icon not showing near to connect button )

**Comment by Ylianst** [comment]
You can open an issue about WebRTC if you like.

WebRTC can't always be enabled, MeshCentral will try to enable it. WebRTC is a UDP stream and will not work thru HTTP proxies.
