### ISSUE TITLE
MeshCentral ChromeOS support

### ISSUE THREAD

**Issue by sysadmin-us** [Ylianst/MeshCentral#2788]
How to install meshagent on Chrome OS ? Is there any option in meshcentral for chrome OS, Let me know about that.

**Comment by Ylianst** [comment]
I have not tested it, but I am told the MeshCentral Android Agent should work on ChromeOS. You can get it on the [Google Play store](https://play.google.com/store/apps/details?id=com.meshcentral.agent2) or as APK on the [MeshCentral.com download page](https://meshcentral.com/info/downloads.html).

Video about that agent on [YouTube here](https://www.youtube.com/watch?v=wi1HYdW00Bk).

**Comment by sysadmin-us** [comment]
@Ylianst  Like in android agent we cannot have remote desktop controls, so if we install in Chrome OS do we have an agent capability to take remote desktop & management device as in band functionality?

**Comment by Ylianst** [comment]
Right, remote input support is not supported on Android or ChromeOS due to OS limitations.

**Comment by MailYouLater** [comment]
I don't have a ChromeOS device to confirm, but as I recall, recent versions of ChromeOS have some variety of Linux app support that can be enabled.  You could try using the Linux agent through that.

@sysadmin-us: If you do try it, please let us know how it goes.

**Comment by krayon007** [comment]
I tried that before. The Linux agent works in that mode. The only problem is that the Linux partition is sandboxed from the rest of the OS, so files tab is useless. Also, because it's a separate partition, auto-start doesn't work.

I did manage to get the Linux agent working on the main ChromeOS (sans remote desktop), but it requires debug mode to be enabled.
