### ISSUE TITLE
Upgrade to meshcentral 0.8.64 but fail with  Error: Command failed: "mongodump"

### ISSUE THREAD

**Issue by yuling3086** [Ylianst/MeshCentral#2791]
Hi,

I try to upgrade my meshcentral from 0.6.97 to 0.8.64 but it fail with the below error :

```
 Error: Command failed: "mongodump" --uri="mongodb://127.0.0.1:27017/keysightedulab" --archive="nul"
[0] '"mongodump"' is not recognized as an internal or external command,
[0] operable program or batch file.
[0]
[0]     at ChildProcess.exithandler (node:child_process:309:12)
[0]     at ChildProcess.emit (node:events:327:20)
[0]     at maybeClose (node:internal/child_process:1055:16)
[0]     at Socket.<anonymous> (node:internal/child_process:441:11)
[0]     at Socket.emit (node:events:327:20)
[0]     at Pipe.<anonymous> (node:net:655:12) {
[0]   killed: false,
[0]   code: 1,
[0]   signal: null,
[0]   cmd: '"mongodump" --uri="mongodb://127.0.0.1:27017/keysightedulab" --archive="nul"'
[0] }
```

Please kindly advise anyone face the same issue and how to solve it?

Thanks

Yu Ling

**Comment by nzalev** [comment]
> Hi,
> 
> I try to upgrade my meshcentral from 0.6.97 to 0.8.64 but it fail with the below error :
> 
> Error: Command failed: "mongodump" --uri="mongodb://127.0.0.1:27017/keysightedulab" --archive="nul"
> [0] '"mongodump"' is not recognized as an internal or external command,
> [0] operable program or batch file.
> [0]
> [0] at ChildProcess.exithandler (node:child_process:309:12)
> [0] at ChildProcess.emit (node:events:327:20)
> [0] at maybeClose (node:internal/child_process:1055:16)
> [0] at Socket. (node:internal/child_process:441:11)
> [0] at Socket.emit (node:events:327:20)
> [0] at Pipe. (node:net:655:12) {
> [0] killed: false,
> [0] code: 1,
> [0] signal: null,
> [0] cmd: '"mongodump" --uri="mongodb://127.0.0.1:27017/keysightedulab" --archive="nul"'
> [0] }
> 
> Please kindly advise anyone face the same issue and how to solve it?
> 
> Thanks
> 
> Yu Ling

I am wondering if it was not working before, but just did not give the error in the older version. This occurs when meshcentral cannot find Mongodump because its path is not in the OSs path environment variable (or it is not installed).

Make sure you have mongodump installed. You may need to specify its path directly in your config.json as follows (for windows)
```
   "AutoBackup": {
      "mongodumppath": "C:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe"
    },
```
Be sure to specify the path to where it is on your system.

If you are using linux/unix, you may need to install mongotools separately from mongodb.

**Comment by yuling3086** [comment]
I try to change the mongodumppath but it still same error.

**Comment by VINISHVV** [comment]
@yuling3086 
Before upgrade are you getting any error / warning message in My Server page like 
 **"Unable to find mongodump.exe, MongoDB database auto-bckup will not be performed. "** .

When you need to fix, Install MongoDB Tools and specifying the correct path to mongodump in the config.json like this and then try upgrade to latest version.
______________________________________________________________________________________________________________________________
    "AutoBackup": {
      "mongodumppath": "C:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",     <------
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 3,
      "zipPassword": "test",
      "backupPath": "C:\\temp"
    },

__________________________________________________________________________________________________________________________________

If there is no such error Please follow below steps once.

1) Please take full backup before upgrade.
2) Install Nodejs Version 10+ since latest version of meshcentral require Nodejs 10+
3) Run meshcentral and try to upgrade.

**Comment by yuling3086** [comment]
Hi,
Before upgrade I don;t have this error.
While under my config.json file I didn't see any AutoBackup there.
I do install the mongoDB tools and create an environment variable for the mongodump as well.

**Comment by nzalev** [comment]
> Hi,
> Before upgrade I don;t have this error.
> While under my config.json file I didn't see any AutoBackup there.
> I do install the mongoDB tools and create an environment variable for the mongodump as well.

If you are on Windows, can you open command prompt (cmd) or powershell and run the command and give the output
```mongodump```

If you are on Linux/Unix, can you run `which mongodump` in your terminal and give the output.

**Comment by yuling3086** [comment]
![image](https://user-images.githubusercontent.com/38518937/122487589-34ddc200-d00e-11eb-88ab-1836d1962411.png)
I had done the check,the mongodump should be able to run.

**Comment by nzalev** [comment]
> I had done the check,the mongodump should be able to run and do the dump.

You had `cd`d into the directory. This doesn't guarantee that it will run, without specifying the full path, from meshcentral's directory. But the screenshot is good nonetheless.


Can you copy/paste into in your config.json file the lines
```
   "AutoBackup": {
      "mongodumppath": "C:\\Program Files\\MongoDB\\Server\\4.4\\bin\\mongodump.exe"
    },
```

If there is an autobackup section in your config.json already, replace it with the above.

It would be useful to post the relevant sections of your config.json file as well (mongodb and autobackup keys).

---

Further, when meshcentral runs mongodump to create the backup, it builds the command out of the mongodumppath key. 

From the original post, we see that the full command being created is
```
"mongodump" --uri="mongodb://127.0.0.1:27017/keysightedulab" --archive="nul"
```

Of course this will not run. The default MongoDumpPath in the code is just `mongodump`. I may improve this to include the `.exe` if on the windows platform (however, with how the Windows environment variables work, this does not guarantee that it will find it correctly either).

When combined with the screenshot, we see the problem: meshcentral cannot find mongodump. This error you are seeing started being dispalyed, along with "Unable to find mongodump.exe..." warning on the server page to specifically notify users when automatic backups would not be possible.

I don't believe that the *error* is new, just the fact that you are being notified there is an error.

**Comment by si458** [comment]
closing as stale, if still having issue please reply
