### ISSUE TITLE
MeshCentral 0.8.63~0.8.65 . [Usage Problem] [Many Antivirus software detected a virus]

### ISSUE THREAD

**Issue by Jacky0400143** [Ylianst/MeshCentral#2798]
Hi, 
Separate issue From #2793 

> [Many Antivirus software detected a virus] 

example Using Kaspersky Anti-Virus 21.2.16.590 , 

The agent will always be notified that the file is virus.
Is there any solution, because sometimes the computer belonging to the customer will cause some troubles in the installation.
;

**Comment by PathfinderNetworks** [comment]
The only thing you can do is submit false positive reports and hope they remove it from their definition files.  That said, Avast is no longer removing it.  I submitted a false positive earlier this week because they are, once again, detecting the 32bit MeshAgent as a rootkit (or, more specifically, the MeshAgent service under Windows).  In the past they would remove it from their definition files. But now they are no longer doing that.  It took them a few days to even respond this time and they said their analysis of the file confirmed it was a virus.  
So not sure what other options there are- apart from the MeshAgent itself being re-written or signed?  Signing it is something Ylian won't do due to reasons he's mentioned before. We can sign it ourselves but it's not simple nor inexpensive to do so.  Even then, I don't know that it would really make much difference as the underlying operation of the agent would still be the same.

**Comment by Jacky0400143** [comment]
@PathfinderNetworks 
I think in the process of agent operation, some transmission information and processing methods will indeed be misidentified, but Good things is , it is open source, so there is no need to worry about someone hiding in the dark.

But Anti-Virus notified is really a Huge obstacle , Customers may be misunderstood due to such false alarms, and worry about it.

Also  I’m like to know . If the installed agent will be blocked and deleted by the anti-virus software or not?

, for example, the user replaces a new anti-virus software.

**Comment by PathfinderNetworks** [comment]
Yes, unfortunately I have had antivirus delete the MeshAgent from systems.  All of my customers run Avast CloudCare- which I manage.  I have exceptions in place for all of my end points to ignore the MeshAgent.  Even so, it will still send me alerts that it sees an infection as a result of Mesh being installed on the device.  But, so far at least, the exception rules have prevented it from removing the mesh agent.  But this is absolutely a pretty huge problem.

**Comment by VINISHVV** [comment]
Meshcentral Assistant is signed application.
Latest Assistant is powerful application, I hope this  will resolve this issue.

**Comment by Ylianst** [comment]
MeshAgent.exe is not signed because it can be used to do bad things. I use to sign it a long time ago, but I got my certificate revoked because it looked like I was signing malware, so I will not be signing it now or in the future. MeshCentral Assistant is signed and you can take a look at that.
