### ISSUE TITLE
MeshCentral 0.8.63~0.8.65 . [issue] [New Install Agent Sometimes not found ]

### ISSUE THREAD

**Issue by Jacky0400143** [Ylianst/MeshCentral#2800]
Hi,
Separate issue From #2793 

> [Agent]

Sometimes the newly installed agent will not be discovered by the server after installation. The existing agent will not be affected. After restarting MC, some newly installed agents will appear, but some must be reinstalled.
The error message at that time can be seen below.

```
    [Error Logs]
    -------- 2021/6/17 下午9:17:16 ---- 0.8.65 --------

ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.

2021/6/17 下午9:25:40: Watchdog timer timeout, 1301ms.
2021/6/17 下午9:31:19: Watchdog timer timeout, 1082ms.
2021/6/17 下午9:35:51: Watchdog timer timeout, 1110ms.
2021/6/17 下午9:50:44: Watchdog timer timeout, 471ms.
2021/6/17 下午9:54:33: Watchdog timer timeout, 1558ms.
2021/6/17 下午10:30:05: Watchdog timer timeout, 3394ms.
2021/6/17 下午10:31:57: Watchdog timer timeout, 1117ms.
2021/6/17 下午10:32:32: Watchdog timer timeout, 2000ms.
2021/6/17 下午10:33:50: Watchdog timer timeout, 857ms.
2021/6/17 下午10:34:25: Watchdog timer timeout, 1284ms.
2021/6/18 上午9:49:30: Watchdog timer timeout, 805ms.
```

**Comment by Jacky0400143** [comment]
Same issue again,The server work normal about two or three days without restart service ,

But .The newly installed agent added today did not appear on the server in time, and it was not connected until the server service was restarted.

**Comment by Ylianst** [comment]
First, note that "Watchdog timer timeout" events mean that your server is overloaded and not capable of handling timer requests in time. If you have the CPU running at 100% because of some other process, that could be the cause. When this happens, the server will not be stable and will have a difficult time doing work correctly. Would be interesting to know how many agents your connecting to a Raspberry Pi server.

For new agents not connecting, this is often because there is some limit on the number of sockets or connections to your server. In that cause, new agents can't connect because there is already too many connections to the server. When you restart, the new agents connect, but some of the old agents can't connect so it's not a real fix. In the MeshCentral install guide, I use:

```
LimitNOFILE=1000000
```

To increase the number of connection handles, but you have to figure out what is causing the connection limit in your case. It could be a firewall, a reverse proxy, etc.

**Comment by VINISHVV** [comment]
> ```
> LimitNOFILE=1000000
> ```

Dear Ylian,

How to activate LimitNOFILE=1000000 in windows server ?
