### ISSUE TITLE
Unknown agent installed on my Mesh Central

### ISSUE THREAD

**Issue by myim123** [Ylianst/MeshCentral#2821]
Hello.

I've been testing Mesh Central for possible use for my help desk work. I've installed Mesh Central on Digital Ocean with 3 agents. All seems to work well. I noticed 4th agent in "My Devices". It's offline and the IP location is somewhere in Isreal nowhere close to where I live. Could this be a bug in Mesh Central or could this be a hack?

Thank you

Mike

**Comment by Ylianst** [comment]
This has been a commonly reported occurrence. It's because one or many of your remote devices have anti-virus software installed and they will download the meshagent.exe for your server to the AV company and they will start a VM that run the executable to see what it does. Your meshagent.exe has instructions embedded within the executable to connect back to your server and so, you will see it connect for a few minutes.

This is totally normal and nothing to worry about. They can't do anything to your server and for a short moment, you could have controlled their virtual machine. You will just have to delete that device when it happens. When you update MeshCentral in the future with a new version of the Agent, this may happen again.

Hope that helps,
Ylian

**Comment by myim123** [comment]
Hi Ylian,

Thank you for getting back to me so quickly. Good to know that you are very
active with this awesome project. If it's not too much trouble I will
continually reporting issues and possibly suggestions.  I'm a Windows
desktop developer always looking for easy-to-use free RDMs. MeshCentral is
far superior than others I've tested. Is there a future plans for remote
printing?

Best regards,

Mike

**Comment by Ylianst** [comment]
Thanks. I have not looked into remote printing yet, not sure how I would do that from the browser. One option you have is to use MeshCentral Router to RDP into remote Windows machines and use the RDP remote print feature. You can see a [video demonstration here](https://www.youtube.com/watch?v=BubeVRmbCRM).

Yes, certainly continue to report issues. I have a lot of requests already and doing my best to get thru as many as I can.
