### ISSUE TITLE
AMT activation issue in meshcentral 

### ISSUE THREAD

**Issue by sysadmin-us** [Ylianst/MeshCentral#2827]
What is the solution of this issue, there is an error showing trying credentials, when re entering the credentials nothing updated and still same error & no CIRA connectivity established. ME version v15.0.10,

![ses](https://user-images.githubusercontent.com/84929681/123844660-ba297680-d92c-11eb-9e5c-3c87952f25b2.png)

**Comment by sysadmin-us** [comment]
Hello @Ylianst ?

**Comment by Ylianst** [comment]
Hi. When you enter new Intel AMT credentials, MeshCentral will keep the credentials and try them next time there is an opportunity to do so.

If this is a Mesh Agent device group, the next time the agent connects, MeshCentral will try the credentials and if it works, complete the configuration of Intel AMT.

If this is a Intel AMT only, agent-less device group. Looking to the picture above, there is no "Hostname" for this device, so your server must be in WAN mode. In that case, next time you run the "meshcmd amtconfig" command on that device, MeshCMD will connect to the server and allow the server to try the credentials.

If your server was in LAN or Hybrid mode and the Intel AMT device was on the same network as the MeshCentral server, the server would try to connect to AMT... since it's in WAN mode, it must want to the Agent or MeshCMD to initiate the connect.

Hope that helps. For details on LAN and WAN modes, you can look at my [YouTube video on this](https://www.youtube.com/watch?v=gx5Fh3pQOns).
