### ISSUE TITLE
meshagent uses the wrong port

### ISSUE THREAD

**Issue by schanir** [Ylianst/MeshCentral#2835]
My setup: (V 0.8.69)
Meshcentral is runnung on a Linux (Ubuntu) server. Meshcentral is running on port 1025 on this pc. In the config.json file is set the parameter "cert" to my DNSName and the parameter "port" to 444.
From WAN I can contact the server via port 444 (my router make a portforward to port 1025). But when I download the setupfile for the agent it has the port 1025 in it. Not the port from the config.json file! 
Manually I change (via hex editor) the port in the Agent-setup file. But after an update he uses the worg port again... please help!!!

**Comment by nzalev** [comment]
What is actually happening: meshcentral cannot bind to port 444, likely because it does not have permission. On Linux, by default, only root can bind to ports less than 1024. Meshcentral responds by binding to the next highest available port, in your case, 1025. Now, when the settings are generated for the meshagent, the variable which was originally set with `port` has since been overwritten with 1025.

When meshcentral is generating settings for the meshagent, it uses the configuration options from `config.json` in the following order:

1. agentAliasPort
2. agentPort
3. aliasPort
4. port

The `aliasPort` option exists for this kind of NAT/reverse proxy situation, where the outside world will be accessing meshcentral from a different port than what its internally bound to.

In your config.json, change port to be `"port": 1025` and add `"aliasPort": 444`

**Comment by Ylianst** [comment]
I will close this issue since @nzalev is exactly correct. You can set the server port to any free port you like and use the "alias" configuration to indicate that port is really going to be used externally.
