### ISSUE TITLE
Server doesnt create customized exe and cannot remote connect to Windows

### ISSUE THREAD

**Issue by gituserchris** [Ylianst/MeshCentral#2838]
Hi. Sorry to bother you with user support questions but I spent time looking and couldn't find an answer to my problems. If you could answer my questions or redirect me to some other source of information please? I did try the guides and the initial videos from your page.
So, I installed the server on Ubuntu. After launching it, I downloaded the agent for windows and installed it (Windows 10 Education). It did not work and I realized it was saying "Local". So, I went back to the server, stopped it (Ctrl-C) and relaunched it, this time with --cert myip: isn't that the way to tell the server it should serve the WAN and not lust LAN? Anyway, I thought that was the only thing I needed. I reconnected through the web interface and re-downloaded the agent, expecting it would be modified to point to the new address (and not being in Local mode). It did not work. I even check the crc of the exe file, it's the same. With or without --cert the server is giving me the same windows executable. What did I miss?
Now my other problem. I edited manually the .msh file (as instructed here: https://github.com/Ylianst/MeshCentral/issues/478) and input my ip address, not in the form wss://myip:443/agent.ashx as indicated but https://myip:443/agent.ashx, otherwise it did not work (I don't know what this wws is). Then, I got connectivity. I could see the device in the web interface, could click on it, could send an instant message to the target Windows but could not remote connect. I tried the web-vnc (using chrome - with firefox it doesn't do anything) and the one indicated in your video, Desktop>Connect. But this did not work. It says it's starting the connection but after some time, a minute or less, it gives up. What I am missing here? Thanks.

**Comment by Ylianst** [comment]
About the server configuring the agent as "Local", this is because your server is in LAN mode. In this mode, agents will attempt to multicast on the network to find the server. You can take a look [at this video](https://www.youtube.com/watch?v=gx5Fh3pQOns) on the difference between LAN and WAN modes. You will need to specify a well know DNS name for your server so that your server can configure the agents to use the DNS name to connect back to the server. In the config.json, you do this:

```
{
  "settings": {
    "Cert": "myserver.com",
    "WanOnly": true,
...
  }
}
```

Set the DNS name on your server, restart the server and reinstall the agent. It should work.

**Comment by gituserchris** [comment]
Thanks a lot. Following your instructions solved both problems.

**Comment by Ylianst** [comment]
Nice! Thanks for reporting back and closing the issue. Much appreciated.
