### ISSUE TITLE
Not detected if systems are powered off

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#286]
After many hours it still thinks Agents are powered on. But the remote systems are powered off or in power sleep modes.

**Comment by Ylianst** [comment]
Can you explain what is your server setup? Windows or Linux server? Are you using NeDB or MongoDB? If MongoDB, are you setup to use event streams? After many hours if you hit refresh on the web page, does it show correctly? Or still shows as powered on?

Any additional information that could help is appreciated. I tried connecting a MeshAgent and disconnecting the Ethernet cable, it did show disconnected after a few minutes.

**Comment by hunter-nl** [comment]
Linux CentOS 7.6, MongoDB 4.0.10.
Agent are on Windows 10, OSX 10.14.5, Windows Server 2012/2016
"_MongoDbChangeStream":true  This is default right?
After hours a refresh would not change the state. Only a restart of MeshCentral Service will see the systems as "offline".

**Comment by Floche87** [comment]
Hi,
I encountered the same issue on several laptops (Debian Jessie & Buster).
Today i have upgraded from 0.3.6.-n to 0.3.6-r. The issue seems to be solved.

My server :
- Rock64 armv8 4GB
- Debian Buster with npm and nodejs from repositories
- NeDB
- Nginx with let's encrypt

Thanks

F

PS : sorry for my english, i rarely practice it

**Comment by hunter-nl** [comment]
It seams to be solved.
