### ISSUE TITLE
No cert created when extra domain is added in config

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#287]
When I add an extra domain in the config.json. Then at starting MeshCentral the following warning appears:
WARNING: File "webserver-extradomainname-cert-public.crt" missing, domain "extradomainname" will not work correctly.
Added config part into domains section.
```
"extradomainname": {
        "Title":"Extra domain",
        "Title2":"Beta",
        "_UserQuota":1048576,
        "_MeshQuota": 248576,
        "NewAccounts": true,
        "DNS":"extra.domain.com",
        "_CertUrl":"https://extra.domain.com:443/"
    }
```

**Comment by Ylianst** [comment]
I just tested this. Generally the certificate for "extra.domain.com" is correctly auto-generated unless "TlsOffload" is set, then it displays a warning instead. This is because generating a certificate does not seems to be a good idea in that situation, the reverse proxy likely has a TLS cert for that domain that should be present as a file or loaded using CertUrl.

So, this does not seems to be a problem. However, I am open to suggestions.

**Comment by hunter-nl** [comment]
I've send you a PM.
If it is related to CertUrl then the other issue is related to this.
MC will check first CertUrl at my HAproxy But when webserver of MC (port 443) is not available yet. HAproxy will return HTML code 503 (Service Unavailable). Then it can not fetch the public key with CertUrl and waiting forever.
So when disabling CertUrl then this issue appears.

**Comment by Ylianst** [comment]
I have never tried HAproxy. If you are saying that there is a startup issue where you have to start one before the other, I can see how this could be a problem. One thing you can do is remove "TlsOffload" and relaunch MeshCentral. That will generate the missing domain certificate, then reactivate "TlsOffload". However, would not solve the problem, because MeshCentral will have the incorrect certificate for this domain.

A real solution would be to take the TLS certificate served by HAproxy and save it at "webserver-extradomainname-cert-public.crt". That will fix it. Of course, each time the HAproxy cert changes, you have to update the .crt file.

Lastly, you could file a different issue and ask that the "CertUrl" be requested after the server on port 443 is launched. Additionally, that if it looks like the HAproxy cert has changed, to auto-reload it.

**Comment by hunter-nl** [comment]
If CertUrl config line is only collecting public key and write it webserver-(extra)domain-cert-public.crt. Then I can create a script for HAproxy to do this whenever the cert is renewed by LetsEncrypt (on HAproxy server) and restart MeshCentral service.

**Comment by Ylianst** [comment]
Yes, when "TlsOffload" is enabled, only the public key file is loaded (.crt). The .key file is not loaded and is not needed in that situation.

**Comment by Ylianst** [comment]
Changing this one to fixed since I don't think it makes sense to create a new certificate when in "tlsoffload" mode. This said, feedback appreciated.

**Comment by hunter-nl** [comment]
Then I will create a script to add the public key(s) from HAproxy to MC when they going to be updated.

**Comment by hunter-nl** [comment]
When I only copy over the wildcard public key from HAproxy to webserver-extradomain-cert-public.crt, then I get still hash errors when agent will connect on main FQDN or extra domain(s).
Or do I also have to replace webserver-cert-public.crt, agentserver-cert-public.crt and mpsserver-cert-public.crt including the private keys of them? Root certificate is not used then anymore I guess, but it is still generate if deleted.

**Comment by openncomp** [comment]
i have the same problem with nginx

**Comment by risturiz** [comment]
Hi, im having same issue with NPM... I had to disable tlsoffload first for webserver-extradomain-cert-public.crt generation ( if i dont do this, any domain go to default domain and not extra domain ).

**Comment by cfoellmann** [comment]
I know this very old we might have a similar setup to @hunter-nl .
We run a HAproxy on our pfsense appliance, generate multi-domain SAN certificates from letsencrypt that we use for the reverse proxy with SSL offload.

I just ran into the same issue described here.
For now I just added a symlink for the missing file since in our case the public crt is the same for all domains we run on meshcentral.

I need to have an eye on renewal and if the the new public.crt will be loaded by meshcentral from  our HAproxy
