### ISSUE TITLE
Append to the existing computer list instead of over writing for Intel AMT.

### ISSUE THREAD

**Issue by MCJohnB** [Ylianst/MeshCentral#2875]

**Comment by MCJohnB** [comment]
why?

**Comment by MCJohnB** [comment]
when you already have the list on MeshCentral and then you transfer to Meshcommander, which already a computer list and you would like append not over write the list.

**Comment by Ylianst** [comment]
There was no description and the issue was not clear. No idea what tools you talking about, that menu option you want changed. Always best to submit a screen shot to be clear that feature you want changed. I will note that code changes can take many hours, so best for me to focus on higher quality issue requests.

**Comment by MCJohnB** [comment]
No problem, i understand that my request is not a high priority.  In addition to the group level of saving the computer list and loading the computer list, could you setup one that would allow you to save a all of the computer groups and load all the computer  groups at a higher level for Intel AMT like you did at the group level.  Sorry for the inconvenience, my requests are low level, however helpful a technician level.

**Comment by Ylianst** [comment]
Ok, I still don't understand your request and have no idea what you want done. When you get a change, open a new request and provide correct details.

**Comment by MCJohnB** [comment]
will do and thank you!
