### ISSUE TITLE
Meshcentral Assistant hangs frequently

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#2879]
The meshagent application is detected as malware in many AV's. So i have installed assistant applications for our clients. 
But while accessing Remote session the system hangs frequently and some times getting message like unable to load the display.

**Comment by Ylianst** [comment]
What version of the server are you using?

**Comment by Mfinadmin** [comment]
@Ylianst 
I am using Meshcentral v0.8.75. With latest version of assistant.
Facing hang issue during desktop access only. For Files and terminal i don't find any issues.
Also this issue is showing on MeshAssistant always connected version only. Normal assistant (based on user request) working fine.

Please refer below screenshot for your reference.

![image](https://user-images.githubusercontent.com/80849522/125150993-9e5e7580-e161-11eb-9980-a9a36d11c2d6.png)

![image](https://user-images.githubusercontent.com/80849522/125151002-a9b1a100-e161-11eb-9843-b427415322b6.png)

**Comment by VINISHVV** [comment]
looks like #2826

**Comment by JOSEPHDEVASSIA** [comment]
Noticed same issue in always connected versions.

**Comment by AJITHMUT** [comment]
@Ylianst - Hope you also noticed this issue in your testing environment.

If you need any logs from our side  then pls let me know

**Comment by Ylianst** [comment]
Oh dear. Looking into this.

**Comment by VINISHVV** [comment]
@Ylianst
Can you fix this issue on priority. Since i have uninstalled meshagent in approximate 2000+ systems. If its time consuming for resolution then we will install meshagent in all the systems.

**Comment by Ylianst** [comment]
Oh dear. I am out for the next few days and I have not been able to reproduce this issue. Maybe one thing that would help is to record a 1 minute clip of the remote desktop not working correctly. I can then take a look at the recording file and hope to see what is going wrong. If you can record at the server side and the browser side, that would be great. Hopefully I can figure out exactly what the problem is.

**Comment by VINISHVV** [comment]
@Ylian
Thanks for your replay. we will share the screen recording asap.
Please enjoy your holidays

**Comment by VINISHVV** [comment]
Dear Ylian,

Please find the attached recording file.

[Recordings.zip](https://github.com/Ylianst/MeshCentral/files/6855993/Recordings.zip)

**Comment by VINISHVV** [comment]
@Ylianst - The same issue is showing in all windows systems.

**Comment by VINISHVV** [comment]
> > Dear Ylian,
> > Please find the attached recording file.
> > [Recordings.zip](https://github.com/Ylianst/MeshCentral/files/6855993/Recordings.zip)
> 
> @Ylianst - Hope you see the videos.
> If you need any logs from our side then pls let me know.

@Ylianst
Since somany people reported this issues but its not recreatable from your end.

Please refer the recordings for your reference

I tried to recreate the same function in meshcentral public server since its easy to showcase to you. Unfortunately this feature (always connected assistant) not available in the public server. So we are stuck with this reported case.

The reasons behind using assistant is given below.

1. The application is self signed and no worry about the  antivirus applications.
2. Easy to run without any extra installations
3. Many other features like profile image available


I hope this issue will resolved at the earliest

**Comment by VINISHVV** [comment]
> I have the same problem, on MeshCentral 0.9.12 on Ubuntu 20.04.3 LTS, with an external MongoDB v4.0.22 server, with nginx acting as reverse proxy.
> Strangely, the issue occurs both on the always connected AND user request version of the assistant. MeshCentral agent works fine, on the same machines (all of them Windows 10 Pro).
> 
> Let me know if I can provide more debug information.

Hope this will fix soon [reference](https://github.com/Ylianst/MeshCentral/issues/3018#issuecomment-899097926)

**Comment by Ylianst** [comment]
Hopefully I just fixed this in MeshCentral v0.9.45. #3212
