### ISSUE TITLE
meshcmd amtconfig when amt network port is not on the same subnet as host subnet

### ISSUE THREAD

**Issue by aztlanla** [Ylianst/MeshCentral#2908]
Hi again, I have question. I have about 10 hosts that have different network setup than the rest of our hosts.

These 10 hosts are in the datacenter and have both NIC ports wired.

Port 1 is the main network port and is on the production subnet  win.test.com
Port 2 labeled as AMT is on the OOBM subnet  oobm.test.net

So when I run the meshcmd amtconfig cmdline, it tries to add it to MeshCentral as hostname.win.test.com and fails, because the amt port is oobm.test.net. So it should be adding it as hostname.oobm.test.net. Is there a way to specify a different hostname? 

Thanks

**Comment by Ylianst** [comment]
Hi. If you are running `meshcmd amtconfig` to perform Intel AMT ACM activation, MeshCMD should try to figure out what is the DNS suffix on the Intel AMT wired adapter and send that to the server since this is the DNS suffix that Intel AMT will see from the DHCP server.

If you are sure MeshCMD is detecting the wrong DNS suffix, update your MeshCentral and MeshCMD to the latest version and add `--dnssuffix oobm.test.net`

Now, if this is not related to Intel AMT ACM activation, but rather it's just that the name of the device is not what you want, you can of course change it on the server. Click on the device and click on the name.

![image](https://user-images.githubusercontent.com/1319013/125913468-5c35574d-91e2-4b85-91d0-ed2018efe250.png)

This said, if you want me to add another option in "meshcmd amtconfig" to specify the device that that will show up on the server, I can look into that.

**Comment by aztlanla** [comment]
Hi again, yes we are using meshcmd amtconfig to perform and ACM activation on these hosts. That interface on oobm.test.net is down. It's only for AMT purposes. Also I forgot to mention, the hostnames differ as well. They have appended a -amt to the hostname.

For example, 
Active port in Linux host9.lin.test.net = Real hostname
Port that is down in Linux host9-amt.oobm.test.net = AMT hostname

I have confirmed it works since I was able to manually activate ACM mode using a USB drive method and I am able to access those hosts via MeshCentral.

Below is one I added manually.
![2021_07_16_capture_01b](https://user-images.githubusercontent.com/16996175/125986996-9e3ef06b-3504-4f44-84c7-d5c7ca19b3be.jpg)

So when I added it manually to MeshCentral, in Meshcentral I used 
Device name: host9.lin.test.net
Hostname: host9-amt.oobm.test.net

When I tried using --dnssuffix oobm.test.net, I got this error, "Failed to complete ACM activation (ERR/5)."
~~~
APF: JSON_CONTROL
Failed to complete ACM activation (ERR/5).
APF: CHANNEL_CLOSE: 5
Socket ends.
APF: Send ChannelClose 
APF: JSON_CONTROL
~~~

It's sending the request to host9.lin.test.net, I want it to send it to host9-amt.test.net
~~~
APF: Send tcpip-forward host9.lin.test.net:16992
APF: Request to port forward 16992 successful.
APF: Send tcpip-forward host9.lin.test.net:16993
APF: Request to port forward 16993 successful.
~~~

Thanks

**Comment by Ylianst** [comment]
Ha. I see. In order to activate Intel AMT into ACM, the physical wired network interface needs to see the DHCP packet with option 15 with the DNS suffix "oobm.test.net". You can't "fake" this by having another network interface have this DNS suffix you want. If you plug is a router with a DHCP server that has "oobm.test.net" as the local network suffix and try again, this should work.

Intel AMT has network filters in the Ethernet chip that look for the DHCP UDP packets and parse out the DNS suffix. So, MeshCMD is correct that the Intel AMT wired NIC does not have that DNS suffix. Also, even if you force the activation, Intel AMT rejected it because the ACM activation cert did not match the DNS suffix it found using Ethernet filters.

Hope that makes sense,
Ylian

**Comment by aztlanla** [comment]
Ok, if there is no way around this. When we purchase our next batch of HP Z4R hosts I will tell our Date Center team to wire them only to the AMT port and not use the other port. The AMT Activation cert should not reject the ACM activation, since oobm.test.net still falls under the wildcard  *.test.net cert we have.  Thanks again.

**Comment by Ylianst** [comment]
Exactly!
