### ISSUE TITLE
Add sub groups?

### ISSUE THREAD

**Issue by soapster** [Ylianst/MeshCentral#2922]
Would it be possible to add groups within groups? For example... A group with a location name, then within that department names.

**Comment by VINISHVV** [comment]
@soapster - Please refer the previous case related to same request [here](https://github.com/Ylianst/MeshCentral/issues/1850#issuecomment-699033475)

**Comment by soapster** [comment]
> @soapster - Please refer the previous case related to same request [here](https://github.com/Ylianst/MeshCentral/issues/1850#issuecomment-699033475)


Thank you. I can see how that can be used to accomplish the task.

**Comment by VINISHVV** [comment]
You just add all devices into main group ( In your case it will be location name) and then select the required Departments computer either one by one /  using filter options and just add the Tags ( In your case Tags should be updated as Department name)

**Comment by Ylianst** [comment]
Yes, adding device tags is probably the way to go. Devices need to be in a single device group because that controls what policy they have, but you can tag them any way you like.

**Comment by AntonAndreevichMoroz** [comment]
Greetings.
This request is quite in demand, as we can see from the number of requests.
I want to offer a solution that does not violate the technical content of MeshCentral. I spied on him on another system, which is also strongly tied to rights. This can be a compromise solution.

If you create separate groups in a certain format, which will then allow ONLY VISUAL to unite the groups. Otherwise, they will remain the same separate entities in the system.

Here's an example of what I mean. We create groups according to the principle
![image](https://user-images.githubusercontent.com/51225180/126261909-3008fa06-2ea4-46f0-8c50-17e84916dbaa.png)
In this case, the levels have the same spelling, so they are grouped in the visual display.
![image](https://user-images.githubusercontent.com/51225180/126261965-7b9f1fba-6ecc-4543-9555-5e619f78c6c6.png)
However, none of their other characteristics are affected. The ideology of finding devices in groups and the assignment of rights remains unchanged. Yes, in the administrative part it may not look very nice, but in daily use it will give convenience.

**Comment by Ylianst** [comment]
When adding a tag, try `tag1|tag2|tag3` using a pipe character as a separator. It will not show exactly like you describe, but it will show as tag1 -> tag2 -> tag3 and certainly something to work on.
