### ISSUE TITLE
AMT Issues again?

### ISSUE THREAD

**Issue by 82280zx** [Ylianst/MeshCentral#2924]
I'm sure I've asked this before but I know I had this working once before... So I have a Intel AMT based Dell that I had working at one point until I moved my mesh central server to a raspberry pi setup, I'm pretty sure I have everything setup and working right, Intel AMT activates and it shows Activated CCM, v12.0.40, TLS when I click on my server in the list, however the problem is the connect button is greyed out on the IntelAMT tab and the HW Connect button is greyed out on the Desktop tab. Before they would be lit and I could use amt and the software client? Thanks!

**Comment by Ylianst** [comment]
There are lots of details needed to properly answer the question. In general, Intel AMT KVM/Terminal buttons will only be enabled if MeshCentral has access to Intel AMT out-of-band channel.

- If you server in LAN, WAN or Hybrid mode?
- Is the Intel AMT computer on the same local network as the MeshCentral server?
- Are you intending on using Client Initiated Remote Access (CIRA) to have AMT connect to the server? Or is the server going to connect to the AMT machine on the local network?
- Is the AMT machine using WIFI? Is it connected using Ethernet? Is it connected using a network adapter managed by Intel AMT?
- Are you using a "Agent" device group, or a "Agent-less, Intel AMT only" device group?

In general, Intel AMT is a little more difficult to debug since it has it's own combination of software and hardware requirements.

**Comment by 82280zx** [comment]
Hybrid Mode, the one AMT computer is in my local network others are outside the lan, I assume they need to resolve to a valid hostname? Where does Mesh Central 2 read this from? I'm running behind NGINX and my situation is a little different where my nginx is in a docker and mesh is outside of it but I do have it to where you can go to www.yoursdomain.com:4433 and I can see "Intel AMT devices should connect here" . Amt machine is wired in my LAN, not sure on which mode I was intending to use I have both the software client and at one point I had Intel AMT working on it as well so I could access both modes from mesh central. I reset my amt on my server hardware wise, AMT installs with Auto on the group but it wouldn't remove it when I changed the policy to deactivate. Hope that answers some of the questions.
