### ISSUE TITLE
Certificate renew problem

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#2925]
Suddenly certificate does not renew. Here is a console output. Installation is on Windows server. Port 80 is open. You can check. There is also IP down in LOG.

```
{
    "configOk": true,
    "leDomains": [
        "rdp.hsi.si"
    ],
    "challenges": {
        "*******************************J0QjVAx8vs": "*********************************eX2uxl7WUG6Pa2XrlWnU"
    },
    "production": true,
    "webServer": true,
    "certPath": "C:\\Program Files\\Open Source\\MeshCentral\\meshcentral-data\\letsencrypt-certs",
    "cert": "Present",
    "daysLeft": 12
}
> lecheck
undefined
> leevents
19. 7. 2021 11:02:33 - Getting certs from local store (Production)
19. 7. 2021 11:02:33 - Reading certificate files
19. 7. 2021 11:02:33 - Setting LE cert for default domain.
19. 7. 2021 11:02:38 - Certificate has 13 day(s) left.
19. 7. 2021 11:02:38 - Asking for new certificate because of expire time.
19. 7. 2021 11:02:38 - Generating private key...
19. 7. 2021 11:02:38 - Setting up ACME client...
19. 7. 2021 11:02:38 - Creating certificate request...
19. 7. 2021 11:02:39 - Requesting certificate from Let's Encrypt...
19. 7. 2021 11:05:31 - Request for certificate is in process.
19. 7. 2021 11:05:34 - Failed to obtain certificate: connect ETIMEDOUT 195.78.83.22:80
19. 7. 2021 11:06:29 - Certificate has 13 day(s) left.
19. 7. 2021 11:06:29 - Asking for new certificate because of expire time.
19. 7. 2021 11:06:29 - Generating private key...
19. 7. 2021 11:06:29 - Setting up ACME client...
19. 7. 2021 11:06:29 - Creating certificate request...
19. 7. 2021 11:06:30 - Requesting certificate from Let's Encrypt...
19. 7. 2021 11:09:25 - Failed to obtain certificate: connect ETIMEDOUT 195.78.83.22:80
19. 7. 2021 11:13:43 - Certificate has 13 day(s) left.
19. 7. 2021 11:13:43 - Asking for new certificate because of expire time.
19. 7. 2021 11:13:43 - Generating private key...
19. 7. 2021 11:13:43 - Setting up ACME client...
19. 7. 2021 11:13:43 - Creating certificate request...
19. 7. 2021 11:13:43 - Requesting certificate from Let's Encrypt...
19. 7. 2021 11:15:09 - Request for certificate is in process.
19. 7. 2021 11:15:17 - Request for certificate is in process.
19. 7. 2021 11:16:38 - Failed to obtain certificate: connect ETIMEDOUT 195.78.83.22:80
20. 7. 2021 11:02:33 - Certificate has 12 day(s) left.
20. 7. 2021 11:02:33 - Asking for new certificate because of expire time.
20. 7. 2021 11:02:33 - Generating private key...
20. 7. 2021 11:02:33 - Setting up ACME client...
20. 7. 2021 11:02:33 - Creating certificate request...
20. 7. 2021 11:02:34 - Requesting certificate from Let's Encrypt...
20. 7. 2021 11:05:29 - Failed to obtain certificate: connect ETIMEDOUT 195.78.83.22:80
20. 7. 2021 11:27:42 - Certificate has 12 day(s) left.
20. 7. 2021 11:27:42 - Asking for new certificate because of expire time.
20. 7. 2021 11:27:42 - Generating private key...
20. 7. 2021 11:27:42 - Setting up ACME client...
20. 7. 2021 11:27:42 - Creating certificate request...
20. 7. 2021 11:27:43 - Requesting certificate from Let's Encrypt...
20. 7. 2021 11:28:08 - Request for certificate is in process.
```

**Comment by Ylianst** [comment]
Weird. It looks like Let's Encrypt validated your server, but MeshCentral is enable to connect to Let's Encrypt to get the certificate? From your server, can you connect to 195.78.83.22:80? Or are you blocking outbound connections to that address?

**Comment by nzalev** [comment]
You can find a lot of information in #2864 

Meshcentral does not generate this error message (`connect ETIMEDOUT 195.78.83.22:80`). This comes from within the 'acme-client' module. Similarly to #2864, it is not quite clear if the issue is your machine connecting to Lets Encrypt, or an issue occuring during the challenge, where LE will send a request to you.

Just like in #2864, you can run the internal debugging the the acme-client by running meshcentral interactively from within the meshcentral directory.

Using cmd
```
set DEBUG=acme-client & node node_modules\meshcentral\ --debug webrequest,cert
```

Using powershell
```
$env:DEBUG='acme-client';node node_modules\meshcentral\ --debug webrequest,cert
```

This should give enough information to figure out if the issue is in the request going to LE or the request coming back.

Here is a sample of the kind of output you will see:
<pre><font color="#4CE64C"><b>noah@tts01</b></font>:<font color="#295FCC"><b>~/meshcentral</b></font>$ sudo DEBUG=acme-client node node_modules/meshcentral/ --debug webrequest,cert
MeshCentral HTTP redirection server running on port 80.
CERT: LE: Getting certs from local store (Staging)
CERT: LE: No certificate files found
MeshCentral v0.8.80, WAN mode.
MeshCentral Intel(R) AMT server running on tts.zalev.ca:4433.
MeshCentral HTTPS server running on tts.zalev.ca:443.
CERT: LE: Got no certificates, asking for one now.
CERT: LE: Generating private key...
CERT: LE: Setting up ACME client...
CERT: LE: Creating certificate request...
CERT: LE: Requesting certificate from Let&apos;s Encrypt...<b>
ERR: 2021-07-20T20:19:45.228Z acme-client [auto] Checking account
ERR: 2021-07-20T20:19:45.228Z acme-client [auto] Registering account
2021-07-20T20:19:45.229Z acme-client HTTP request: get https://acme-staging-v02.api.letsencrypt.org/directory
ERR: 2021-07-20T20:19:45.539Z acme-client RESP 200 get https://acme-staging-v02.api.letsencrypt.org/directory
2021-07-20T20:19:45.540Z acme-client HTTP request: head https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce
ERR: 2021-07-20T20:19:45.812Z acme-client RESP 200 head https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce</b>
</pre>

**Comment by alesribic73** [comment]
@Ylianst from the server where Meshcentral is installed, i can not load page of meshcentral. Router does not allow loop connections over WAN address. If this is issue let me know. But we are not blocking any outside addresses, so LE servers can connect to port 80

**Comment by Ylianst** [comment]
Ok, I did not realize that 195.78.83.22:80 was your own server. Looks like Let's Encrypt can't access your server then. @nzalev is giving correct recommendations here.

**Comment by alesribic73** [comment]
I have checked site from different pagres around the world, and it is availible. Is there anything more i can do? It is 9 days before certificate exipired.

**Comment by Ylianst** [comment]
I am running out of ideas. Backup the "meshcentral-data" folder and try to `"production": false` to see if your going to get a certificate that way.

Another way to go would be to use certbot to manually get a Let's Encrypt certificate, turn off Let's Encrypt support in MeshCentral and replace `webserver-cert-private.key` and `webserver-cert-public.crt` files with you cert. This is obvious not very convenient but could help debug the issue.

You could also put a reverse proxy in front of MeshCentral that gets the Let's Encrypt cert instead of MeshCentral and does all of the TLS instead of MeshCentral, but that is a bunch of work.

**Comment by alesribic73** [comment]
I try to backup foler and disable production. Nothing. I got MescCentral certificate valid to 2046.
I till enable reverse proxy, as on new production enviroment it is quite easy. If you need any more LOG's let me know.

Thanks

**Comment by alesribic73** [comment]
I founf the cause of the problem. My router does not support loopback from internal server to outside WAN ip address of my router. When i add loopback rule, certificate was generated and renewed.
