### ISSUE TITLE
Question: Signing Agents with EV Code Certificate, Automatic?

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2947]
Finally got an EV code signing certificate and was about to download and sign MeshService.exe and MeshService64.exe, however I saw some intriguing files in `/node_modules/meshcentral/agents` that made me wonder if MeshCentral might already have some capability for this.

I see some files have a -signed version, and there are some .cer files in there too. Is there an easier way to do this than downloading, signing, and replacing everything every time the agent is updated?

**Comment by Ylianst** [comment]
Hi. So the current Windows agents are signed using a self-signed certificate. The public part of the self-signing certificate is the file "node_modules\meshcentral\agents\codesign.cer". I sometimes change the self-signing certificate and so, if that happens the old cert will be called "node_modules\meshcentral\agents\codesign-old.cer", but that certificate was used to sign the agent for previous versions. The current MeshCentral "-signed" files will be signed with "codesign.cer". Hope that makes sense.

There is no automated way to sign the agent when MeshCentral is updated. I am not sure that would be possible, especially if your EV code signing cert has a private key that is hardware backed using a smart card or something else. In that case, manual signing is required. Personally, I would first deploy to a preproduction server, sign the agent, make sure everything works and copy that to the production server. You will have to update the "MeshService64-signed.exe" and "MeshService-signed.exe" file in the agent folder each time you update the MeshCentral server from NPM.

We have not changed the agent is a while, but I am looking at doing an update this week because we have lots of bug fixes that really need to be fixed. Also, the WebSocket masking is not right on the current agent and so, I really was to be websocket spec compliant with the new agent. Bryan and I have to do a lot of testing before a new agent is released.

If you have any specific ask or questions, let me know.

**Comment by MatinatorX** [comment]
Makes sense, just wanted to be sure. Thanks for the clarification.
