### ISSUE TITLE
Fresh Windows install, port not correct in firewall

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2968]
I just installed Mesh Central on our new server (auto selected port 444), copied the meshcentral-data folder and restarted... (still port 444)
But I could not connect.

Turns out I had to add port 444 to the windows firewall, yet other ports were added automaticly.
I would have expected the installer to add port 444 as well, or is this by design?

![image](https://user-images.githubusercontent.com/55733884/127625820-b4459103-ca8d-4851-a2fd-697692b45332.png)

**Comment by Ylianst** [comment]
By default, MeshCentral uses ports 80, 443 and 4433. However, if the port is busy, MeshCentral will use the next available port. So, the installer configured port 80, 443 and 4433.... but once MeshCentral got started, it could not use 443 and used the next available port.

Not sure I can fix this well since busy ports can happen at any time.

**Comment by Allowee** [comment]
Ah that makes sense.

Maybe the installer can check port 443, if it is in use it will ask to install on port 444 and set firewall rules correctly.
