### ISSUE TITLE
Moving meshcentral installation to a new domain

### ISSUE THREAD

**Issue by lheckemann** [Ylianst/MeshCentral#2987]
#### What I want to achieve

I have meshcentral installed at meshcentral.example.com, behind an nginx reverse proxy. I want to move this installation to meshcentral.example.org, while preserving all the registered devices.

#### What I tried

- replaced the nginx `server` with one that just redirects (`return 301 https://meshcentral.example.org$request_uri;`) to the new site, and transferring the reverse-proxy config for just meshcentral, changing only `server_name` and the HTTPS certificates.
- In `config.json`, changed "meshcentral.example.com" to "meshcentral.example.org" in `settings["cert"]` and `domains[""]["certurl"]`

#### What I hoped for
Everything would follow the redirect, and the old installation would be accessible more or less unmodified at the new location.

#### What I got
Logging in at the new location showed the device groups and everything else as expected, but none of the devices were online.

#### Further musings

I'm guessing that first and foremost, the agent is not following the redirect, as I can see from the nginx access log. I can imagine this wouldn't be trivial since the agent expects the certificate it shipped with to be used. Even if it followed the redirect, it would encounter a new (unknown) certificate and reject it.

Is there a way to configure the agent to (a) follow a redirect and (b) accept multiple certificates? And if so, can this configuration be pushed from the meshcentral server to all registered agents?

**Comment by Ylianst** [comment]
You are correct that the agent will not follow HTTP redirect. You will have to point both domain names to your MeshCentral server so that both old and new agents will be able to connect. Before setting up a reverse proxy, I suggest watching the [MeshCentral YouTube video on this topic](https://www.youtube.com/watch?v=YSmiLyKSX2I). I go cover the theory and practice of how it works, you can use any TLS certificate you want in the reverse proxy, but you have to tell MeshCentral when you load that certificate using "certurl".

Also, agents will connect to your server using a URL in the "meshagent.msh" file. You can edit that file in the client and restart the agent and it will connect to the new address.

As usual, make sure to keep an off-site backup of your "meshcentral-data" folder as it contains the certificate that agents will need to see to be able to connect to your server. The way this server authentication certificate is used is explained in the video.

Let me know if that helps,
Ylian
