### ISSUE TITLE
Reconnect Polling

### ISSUE THREAD

**Issue by theredkoala21** [Ylianst/MeshCentral#301]
For some reason the meshcentral app has crashed about two days ago and i did not realize.

I have booted it back up about 1 hour ago, but no devices have come online.
Just wondering if the devices will reconnect by themselves. 

What happens if the server is unavailable for an extended period of time (12 hrs or so). Will devices reconnect, if so how often will they check.

My device OS's are a range of Linux/Windows.

**Comment by Ylianst** [comment]
Hi. Currently, devices will retry after a few seconds and increase the time between polling each time it fails. After a few days of the server being down, the polling time will be about 1 hour. In the next version of the agent, I want to continue increasing the time between polling but put a maximum of 10 minutes.

Any suggestions or opinions around this is appreciated.

**Comment by theredkoala21** [comment]
So its been around 17 hours and most of the agents have not reconnected.
The only agents that have reconnected are devices that are restarted regularly (personal laptops).
Where as the servers/AWS/Google Cloud/Azure devices which stay online all the time are not coming back online.

Where is the best place to check the error log for windows and linux. To see what has happened?

Thanks

**Comment by Ylianst** [comment]
Are your computers running the 32bit version of the MeshAgent? If so, in the last few days, that agent has gotten removed by Microsoft Defender causing significant problems. I just published MeshCentral v0.3.6-m that has a new agent that fixes this.

If you go in "C:\program files\meshagent" (on 32 bit windows) or "C:\program files (x86)\meshagent" on 64bit windows an see a "MeshAgent" folder with files but no meshagent.exe file, that is because it was removed. Just install the new 32bit or 64bit agent and you should be fine.

For anything else, you can look at the "meshagent.log" file, or run the agent manually on Windows by typing "meshagent.exe run". It will show you what it's doing.

**Comment by theredkoala21** [comment]
I got impatient and updated the server to 0.3.6-k (thus restarting it).
After about 30 minutes all of the servers came online without any interaction.

So resolved. But yes, max 10min timeout would be ideal for the Agent. As waiting for 16+ hours is not good.

**Comment by Ylianst** [comment]
Thanks for the report. Yes, that 16 hours thing is not right, the MeshCentral server must have has a problem that the reset solved. Current agents should never take more than a bit over an hour in the worst case.
