### ISSUE TITLE
Desktop option disappeared after 0.90 update

### ISSUE THREAD

**Issue by sharpec** [Ylianst/MeshCentral#3025]
After update to 0.90, Desktop option disappeared.
In CSS i have found "display:none" for all menu.
Im a super admin with Full right.

Have you any idea?
Thank you

![Schermata 2021-08-12 alle 13 59 00](https://user-images.githubusercontent.com/5232619/129193131-cd0bd3c2-0395-4482-8eb9-e33067e067c7.png)
![Schermata 2021-08-12 alle 13 59 21](https://user-images.githubusercontent.com/5232619/129193134-4d34665f-0e43-401d-8ad5-d9d892e71c10.png)
![Schermata 2021-08-12 alle 13 59 55](https://user-images.githubusercontent.com/5232619/129193137-e5fbb319-dd4d-43b7-b979-bc8c50eb8fe2.png)

**Comment by rodrigolzd** [comment]
Take a quick look here to fix it. #2994

**Comment by Ylianst** [comment]
This happens when the MeshAgent does not have any JavaScript to run because the agent update ran into a problem. The next version of MeshCentral v0.9.2 will update Windows 32bit agents in a different way to fix this. I am not surprised this is happening for Windows 7 agents.

Go in the device's console tab and look at the agent version. If it says "Aug 5 2021", the agent is already updated.

![image](https://user-images.githubusercontent.com/1319013/129248659-f5c8b547-913f-47e7-a4f7-6c162fdfe4bc.png)

If already updated, hit "Agent Action" and upload the default core. The tabs should come back.

![image](https://user-images.githubusercontent.com/1319013/129248794-1124ceb6-a068-4611-b810-527e2aa5d6d8.png)

If not updated, hit "Agent Action" button, upload the recovery core and type "Agent Update", that should fix it.

![image](https://user-images.githubusercontent.com/1319013/129248973-d5ed5d3d-d3c7-47b3-b638-876569f37bc4.png)

I will have a fix for this in v0.9.2.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.2 that hopefully should fix this.

**Comment by sharpec** [comment]
Fix worked perfectly. Agents updated automatically after server update to v0.9.2 
Thank you
![Schermata 2021-08-12 alle 23 46 57](https://user-images.githubusercontent.com/5232619/129274396-b92e314a-bdfe-485d-bd27-42ed5074884a.png)
