### ISSUE TITLE
SSL renewal issues

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#3038]
Dear Ylian,

I am facing some issues related to SSL certificate renewal. I've purchased the new certificate and updated the same in the below files.

webserver-cert-public.crt
root-cert-public.crt

root-cert-private.key
webserver-cert-private.key

when I run my server with this new server few agents are not connecting properly and its showing "**Server certificate mismatch**" in console.

Can you help me with how to replace the existing mesh central certificate with a new one?

**Comment by Ylianst** [comment]
Oh, you can't change these two files:

```
root-cert-public.crt
root-cert-private.key
```

The root cert for your MeshCentral server is supposed to be a private self-signed certificate that is unique to your server.

You can replace these files with your own TLS certificate:

```
webserver-cert-public.crt
webserver-cert-private.key
```

If you want to specify the intermediate and root certificate for the TLS cert. Create these files:

```
webserver-cert-chain1.crt
webserver-cert-chain2.crt
webserver-cert-chain3.crt
```

Create as many as you need and put one intermediate cert in each.

Hope that helps,
Ylian

**Comment by pggsadmin** [comment]
@Ylianst
Unfortunately i changed the root-cert-public.crt file in my existing installation. Is there any option to resolve this issues?

**Comment by nzalev** [comment]
If you have autobackups enabled and you did not make this change too long ago, you will find the previous certificates+keys zipped in the `meshcentral-backup` directory.

**Comment by pggsadmin** [comment]
@nzalev 

I have replaced the certificate before one year. Now this certificate going to expire.

Is there any provision to continue with new certificate in this case ?

**Comment by nzalev** [comment]
Do you mean that you changed `root-cert-public.crt` 1 year ago?

 By default, this certificate was valid until about the year 2050.

**Comment by pggsadmin** [comment]
> Do you mean that you changed `root-cert-public.crt` 1 year ago?
Yes, unfortunately i changed the certificate with my own Digicert cert.

**Comment by nzalev** [comment]
I believe the agents store the cert in their DB, which is not human editable (it is a binary DB). Likely, you will have to reinstall the agents which do not connect. Ylian may have a better solution than that.

You can re-generate the self-signed root certificate by stopping meshcentral, removing the files, and re-running meshcentral.
```
root-cert-public.crt
root-cert-private.key
```
This will generate a new root cert which will not expire until 2049. 

You could also try letting the certificate expire and see what happens.

**Comment by pggsadmin** [comment]
Thanks @nzalev 

I tried the above method ( Delete existing certificate and restart server ). But only a few systems are connecting. Rest of the agents showing a cert mismatch.

 I think its due to the AgentHash value in the registry. I tried to change the registry value but had no luck. since the number of agents is more than 9000 so reinstallation is not easy...

The existing cert will expire after 10 days so I just wait for @Ylianst  suggessions.

**Comment by Ylianst** [comment]
As a temporary solution, add this line to the "settings" section of the config.json:

```
"ignoreAgentHashCheck": true
```

Let me know if all agents connect now.

**Comment by pggsadmin** [comment]
> First, please backup your "meshcentral-data" folder offsite. This is always critical. Then, as a temporary solution, add this line to the "settings" section of the config.json:
> 
> ```
> "ignoreAgentHashCheck": true
> ```
> 
> Let me know if all agents connect now.

@Ylianst - Tried the same but agents not connecting.

**Comment by Ylianst** [comment]
Ok. I am going to take a guess at what happened and how to fix this.

When you replaced these 4 files:

```
root-cert-public.crt
root-cert-private.key
webserver-cert-public.crt
webserver-cert-private.key
```

Replacing the two "root-cert" files has broken your server. Once you replaced the root files, the next time you ran the server, MeshCentral noticed that the root cert was invalid and that the other two certificate "agentserver" and "mpsserver" where not signed by the root cert.

So, the MeshCentral server regenerate the root, agentserver and mpsserver certs. Since none of them made any sense anymore. All these files where re-generated.

```
root-cert-public.crt
root-cert-private.key
agentserver-cert-public.crt
agentserver-cert-private.key
mpsserver-cert-public.crt
mpsserver-cert-private.key
```

Now, agents will not connect because the server needs the "agentserver" certificate to prove it's the right server. That cert is not matching anymore and no agents will connect.

The only way out of this is to get a backup from just before you replaced the "root" cert and get these 6 files restored. You need to recover the "root" and "agentserver" certs at a minimum. The "mpsserver" cert can be re-generated from the correct root and will not be a problem.

Make sure to backup your current situation and go in a previous backup and get the certs back. Also, please backup your "meshcentral-data" folder offsite. If you loose your "root" and "agentserver" certificates, you are toast. You need to re-install all agents and there is no workaround. This is to insure that agent only connect to your server and not a hacker.

One last note. When you get a certificate from a CA, they don't give you their root certificate.

Let me know if that helps,
Ylian

**Comment by Ylianst** [comment]
A few more notes on the above conversation. If you remove the root certificate and re-run MeshCentral, it will re-generate certificates but that will make is a "new" server. Existing agents will no be able to connect since you will have a different "agentserver" cert. You must restore your original "root" and "agentserver" certificate at a minimum.

Also, I understand the web certificate was changed a year ago with a DIgiCert certificate, that is not a problem. However, you must restore your "root" and "agentserver" certificate to the last valid one.

Now that you reset your "agentserver" certificate, new agents being installed will look for the new cert. So, once you revert, the agents that are connecting now will no longer be able to connect, but all your old agents will connect.

**Comment by Bobberty** [comment]
Fun question...  Might be off topic and a bit of my learning curve.
I am using a proxy in front of my instance and providing a client cert to specific users.  Does the TLSOffload option reduce the security for the Agent cert?

**Comment by Ylianst** [comment]
@Bobberty Good question. If you have a reverse proxy on from of MeshCentral, the answer is no, it does not reduce security. The exact details are covered in section 8 of the [MeshCentral Design and Architecture Guide](https://meshcentral.com/info/docs/MeshCentral2DesignArchitecture.pdf). Basically, your reverse proxy is acting as a man-in-the-middle, but as long as you indicate to the server what certificate the agent is expecting, the server will check that.

You use the "certurl" configuration to tell MeshCentral when you get the TLS certificate the agent will see when connecting. When an agent connects, it will send to the server the hash of the TLS cert is got when connecting. It will expect the server to sign that cert hash with the "agentserver" cert and return the response.

The server will check that the agent saw the correct TLS cert and sign the agent authentication request.

Hope that helps. Basically, if an attacker tries to put a fake proxy between the agent and your server, the server will detect it.

**Comment by pggsadmin** [comment]
Dear @Ylianst & @nzalev 

Thanks for your support. I have managed the issue through the below method.
___________________________________________________________________________________________________________
Ih've created temporary server for this migration purpose and run the batch command from the existing server for installing the new agents. This will consume approximately 1hour to install 9000+agents.

Once all the agents are connected to new server I run the batch command to uninstall old server agents and removed the all devices from server. Removed the root certificate and install new SSL in old server. Now it's showing root cert validity 2049.

Then I just run the batch command from the temporarily created server for installing the agents in my old server.

___________________________________________________________________________________________________________
