### ISSUE TITLE
Optional URL Segmentation/Windows Terminal -- Suggestion

### ISSUE THREAD

**Issue by Bobberty** [Ylianst/MeshCentral#3040]
I'm starting to depend on this tool.  And as a whole, it's very impressive.
I do have a few suggestions or ideas.

1)  Allow an option for a different FQDN for different tasks.
As an example, the Mesh Agent will be downloaded from "https://agent.domain.tld" with an appropriate cert.  The chat will have a domain of "https://chat.domain.tld" with an appropriate cert.  And invites/guests will have a domain of "https://guests.domain.tld" again with an appropriate cert.  This would greatly help people who wish to offer a client cert to "power users" on a proxy.  And may allow an admin to restrict certain aspects without restricting the whole.
My particular itch is to keep using a self-signed root cert with server and client certs to allow for access to the web interface for specific users while using "Lets Encrypt" for downloading the agents, assistant, chat and invites.

2)  Allow for a Windows Terminal interface for AMT/CIRA.  This one may be in the Too Much Fun Box.  Or a quick guide to set something up.  Even just a quick tweak to the OS to provide Windows Terminal on COM3 would be good.  I have discovered that CIRA scratches a pretty big itch, but doesn't provide for much productivity/troubleshooting due to the slow GUI.  I do see installing an agent as a somewhat obvious step, but that may restrict access to the BIOS/AMT settings.

**Comment by Ylianst** [comment]
Hi and thanks.

1. You can use the folling options in the settings section of the config.json to create a different HTTP port that will only accept MeshAgent connections:

```
    "agentPort": 1234,
    "agentPortBind": "127.0.0.1",
    "agentAliasPort": 1234,
    "agentAliasDNS": "agents.myserver.mydomain.com",
    "agentPortTls": true,
```

The nice thing about this is that you can now expose that port externally for agent to connect, and put additional restrictions on the user portal. I know some have put Azure authentication, etc. Then, for specific links like "invite", you can setup reverse proxy routing rules to do this. I imagine reverse proxies could also perform client certificate authentication, but I have not looked into this.

Another option you can try is the loginkey. You put this in the domain section of your config.json:

```
"loginKey": [ "abc", "123" ],
```

Agents will still correct correctly, but for users, you need to add ?key=abc or ?key=123 to the URL in order to see the portal. This is not strong security, but it hides the user portal easily.

2. So yes, anything you bind to COM3: will show up in the Intel AMT Serial-over-LAN terminal. This is commonly done in Linux and I think if you search around there are scripts to bind a Linux TTY shell to COM3:, I am sure there are some of the same thing for Windows. I know some kernel developers will bind their debug session to COM3: to see what is going on, so it has all sorts of usages. Not sure if your request would have the MeshAgent bind to COM3: and expose a shell. Of course, if the agent is running, you get the terminal session anyway thru the OS in-band channel.

**Comment by Bobberty** [comment]
Is it possible to simply use "agentAliasDNS" and allow the Agent to simply use a different URL with an SNI to validate a specific cert?

**Comment by Ylianst** [comment]
You can use the "agentAliasDNS" to tell the agents to use an alternate DNS name to connect to your server. That DNS name can point to a web server with any TLS certificate, including a self-signed one as agents do their own validation of the server. When connecting, MeshAgents will correctly specify the SNI in their requests. Hope that answers your question.
