### ISSUE TITLE
Windows 10 Full Agent Digital Signature is out of date.

### ISSUE THREAD

**Issue by Bobberty** [Ylianst/MeshCentral#3043]
It looks like the Windows 10 Full agent digital signature is self signed by MeshCommander.com

**Comment by Ylianst** [comment]
MeshAgents are signed using a self-signed certificate. It's not that it's out of date, it's a purposefully not trusted certificate. MeshCentral Assistant, Router and Installer are signed using a correct certificate, but agent is not since remote management agents are often used to do bad things and I have gotten my certificate revoked in the past because of this.

You are free to sign the agent yourself if you have a code signing certificate, the files are in `/node_modules/meshcentral/agents/meshagent-signed.exe"`

**Comment by Bobberty** [comment]
Thanks for the info....
