### ISSUE TITLE
Avast, once again, flagging MeshCentral as a rootkit

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#3046]
I don't know if there is anything the developers can do to help with this- maybe by reaching out to Avast support you can help to convince them this is a valid tool?  
Avast Business is flagging the meshagent.exe service as a rootkit and prompting the user to delete it.  I've submitted false positive reports to them but they won't change it.  It used to be this only affected the 32bit version. But now it's happening with the 64bit version.  
![Avast3](https://user-images.githubusercontent.com/48607498/130273801-0e0bbb48-168b-4fbc-9b90-08a162a55a91.jpg)

**Comment by VINISHVV** [comment]
Symantec also flagged the meshagent. Now windows 7 with Symantec installed system forcefully stop / restart meshagent service in every 5 minute.

**Comment by Ylianst** [comment]
I just published MeshCentral v0.9.8 and I feel a bit dirty each time I do this, but I changed the self-signed root certificate that I used to sign the meshagent. Let me know if that works.

**Comment by PathfinderNetworks** [comment]
I just updated my server and am also working with Avast support.  We'll see what happens.  I'm also considering biting the bullet and buying a code signing certificate. Looks like they are less than $200 per year from Sectigo.  But, before I do that, I'm waiting to see what Avast says in regards to if signing it would help or not.  
If I do want to sign the agent, how much work is involved with that?  I know I've seen mention of it here on Github once or twice.  Do you have documentation about how that works and what steps to take?  I assume it would need to be re-signed every time the agent is updated?

**Comment by Ylianst** [comment]
One you have the certificate, it's not difficult to sign an executable. Generally you use "signtool.exe" from Microsoft. The CA generally gives you instructions that changes a little depending on their process. You will likely want to sign the following files:

```
node_modules\meshcentral\agents\MeshService-signed.exe
node_modules\meshcentral\agents\MeshService64-signed.exe
node_modules\meshcentral\agents\MeshCmd-signed.exe
node_modules\meshcentral\agents\MeshCmd64-signed.exe
```

**Comment by Ylianst** [comment]
Also, one you update to the latest server, you can go in the agent console and type "agentupdate" to force the agent to update to the latest executable. MeshCentral does not consider the signature change to be a change in the agent, so there is no automatic update.

**Comment by VINISHVV** [comment]
> I just published MeshCentral v0.9.8 and I feel a bit dirty each time I do this, but I changed the self-signed root certificate that I used to sign the meshagent. Let me know if that works.

@Ylianst
Symantec still flag the meshagent. I think you can revoke the code sign

**Comment by PathfinderNetworks** [comment]
Ylian,
Is there any command/method of doing a mass agent update?  I don't want to have to go to each device and run the agentupdate command on each on manually.

**Comment by VINISHVV** [comment]
> Ylian,
> Is there any command/method of doing a mass agent update? I don't want to have to go to each device and run the agentupdate command on each on manually.

Please refer

**Comment by Ylianst** [comment]
@PathfinderNetworks Yes, there is a way to mass force update. You first turn off automatic update on the server. In the settings section of the config.json, add: 

```
"noAgentUpdate": 1
```

Once you start the server again, select all your devices, hit "Group Actions..." and there will be an option to force agent update. That will update to the agent with the latest self-signed cert.

Also, let me know if the new agent passes the AV test. If it does, I will probably change the self-signing cert on each agent release.

**Comment by PathfinderNetworks** [comment]
Thanks Ylian, I'm still testing this.  But, so far, it appears that isn't going to help.  
I also received this response from Avast support today when I asked if signing the executable with a verified code signing cert would help. 
"I spoke with my t3 support. They are not certain that changing the cert will resolve the issue"

So they must be flagging it based on the behavior.

**Comment by Ylianst** [comment]
Did the latest version of MeshCentral with agents signed with my new cert help?

**Comment by plwc** [comment]
I would have thought it would be quite simple to just whitelist meshcentral. Is there a reason you can't do this?

**Comment by VINISHVV** [comment]
> Did the latest version of MeshCentral with agents signed with my new cert help?

Symantec team does not whitelist mesh agents. Please refer to the below communication. Due to this Meshagent restart in every 5 minutes and we need to reconnect the sessions.

But in the same machine Meshcentral assistant works for more than 5 minutes without any disconnections. But its working too slow.

_______________________________________________________________________________________________
Hello,

Hope you are doing well. 

Our engineering team found that there are no Broadcom modules loaded in the process. Since this is an internal application, could you please get your developer to analyze the dump as well.

We suspect that SEP driver component is changing the behavior of the process and the application is not handling this reliably.

Below is our dump analysis, you can share it with your Developer of MeshAgent.exe:

0:009> !analyze -v********************************************************************************                                                                             **                        Exception Analysis                                   **                                                                             ********************************************************************************Cannot find frame 0x9, previous scope unchangedKEY_VALUES_STRING: 1    Key  : AV.Fault    Value: Execute    Key  : Timeline.OS.Boot.DeltaSec    Value: 31625    Key  : Timeline.Process.Start.DeltaSec    Value: 240PROCESSES_ANALYSIS: 1SERVICE_ANALYSIS: 1STACKHASH_ANALYSIS: 1TIMELINE_ANALYSIS: 1Timeline: !analyze.Start    Name: <blank>    Time: 2021-07-12T21:44:44.437Z    Diff: 293919437 mSecTimeline: Dump.Current    Name: <blank>    Time: 2021-07-09T12:06:05.0Z    Diff: 0 mSecTimeline: Process.Start    Name: <blank>    Time: 2021-07-09T12:02:05.0Z    Diff: 240000 mSecTimeline: OS.Boot    Name: <blank>    Time: 2021-07-09T03:19:00.0Z    Diff: 31625000 mSecDUMP_CLASS: 2DUMP_QUALIFIER: 400CONTEXT:  (.ecxr)eax=00000000 ebx=033c7e60 ecx=00471f60 edx=dddde2dd esi=00000000 edi=00000044eip=0460fc78 esp=0460fc0c ebp=00893c68 iopl=0         nv up ei pl zr na pe nccs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=000102460460fc78 d8fd            fdivr   st,st(5)Resetting default scopeFAULTING_IP: +00460fc78 d8fd            fdivr   st,st(5)EXCEPTION_RECORD:  (.exr -1)ExceptionAddress: 0460fc78   ExceptionCode: c0000005 (Access violation)  ExceptionFlags: 00000000NumberParameters: 2   Parameter[0]: 00000008   Parameter[1]: 0460fc78Attempt to execute non-executable address 0460fc78DEFAULT_BUCKET_ID:  SOFTWARE_NX_FAULTPROCESS_NAME:  MeshAgent.exeFOLLOWUP_IP: ntdll!RtlpTpWorkCallback+e3772dd848 803d8403fe7f00  cmp     byte ptr [SharedUserData+0x384 (7ffe0384)],0EXECUTE_ADDRESS: 460fc78FAILED_INSTRUCTION_ADDRESS: +00460fc78 d8fd            fdivr   st,st(5)ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.EXCEPTION_CODE_STR:  c0000005EXCEPTION_PARAMETER1:  00000008EXCEPTION_PARAMETER2:  0460fc78WATSON_BKT_PROCSTAMP:  605d2880WATSON_BKT_PROCVER:  0.2.1.3PROCESS_VER_PRODUCT:  Mesh Agent ServiceWATSON_BKT_MODULE:  unknownWATSON_BKT_MODVER:  0.0.0.0WATSON_BKT_MODOFFSET:  460fc78WATSON_BKT_MODSTAMP:  bbbbbbb4BUILD_VERSION_STRING:  6.1.7601.17514 (win7sp1_rtm.101119-1850)MODLIST_WITH_TSCHKSUM_HASH:  2530c47d15e9c57f23779a88bfde9dd705da1937MODLIST_SHA1_HASH:  784da9f3c3f1d9384f26a836348e608bb23aaa92COMMENT:  *** "c:\Dumps\procdump.exe" -accepteula -ma -j "c:\dumps" 2920 192 006D0000*** Just-In-Time debugger. PID: 2920 Event Handle: 192 JIT Context: .jdinfo 0x6d0000NTGLOBALFLAG:  0APPLICATION_VERIFIER_FLAGS:  0PRODUCT_TYPE:  1SUITE_MASK:  272DUMP_FLAGS:  8000c07DUMP_TYPE:  3ANALYSIS_SESSION_HOST:  RENBLD010124ANALYSIS_SESSION_TIME:  07-12-2021 17:44:44.0437ANALYSIS_VERSION: 10.0.18362.1 amd64freTHREAD_ATTRIBUTES: OS_LOCALE:  ENNBUGCHECK_STR:  APPLICATION_FAULT_SOFTWARE_NX_FAULT_INVALID_POINTER_EXECUTEPRIMARY_PROBLEM_CLASS:  APPLICATION_FAULTPROBLEM_CLASSES:     ID:     [0n313]    Type:   [@ACCESS_VIOLATION]    Class:  Addendum    Scope:  BUCKET_ID    Name:   Omit    Data:   Omit    PID:    [Unspecified]    TID:    [0x1b3c]    Frame:  [0] : unknown!unknown    ID:     [0n287]    Type:   [INVALID_POINTER_EXECUTE]    Class:  Primary    Scope:  BUCKET_ID    Name:   Add    Data:   Omit    PID:    [Unspecified]    TID:    [0x1b3c]    Frame:  [0] : unknown!unknown    ID:     [0n295]    Type:   [SOFTWARE_NX_FAULT]    Class:  Primary    Scope:  DEFAULT_BUCKET_ID (Failure Bucket ID prefix)            BUCKET_ID    Name:   Add    Data:   Omit    PID:    [0xb68]    TID:    [0x1b3c]    Frame:  [0] : unknown!unknownIP_ON_STACK: +00460fc78 d8fd            fdivr   st,st(5)LAST_CONTROL_TRANSFER:  from 772dd848 to 0460fc78STACK_TEXT:  WARNING: Frame IP not in any known module. Following frames may be wrong.0460fc38 772dd848 00000000 03d40810 00000000 0x460fc780460fca0 0082a794 00893c68 00001b3c 0082a758 ntdll!RtlpTpWorkCallback+0xe30476fd40 0460fca0 00000000 000002b0 0082a758 0x82a7940476fd44 00000000 000002b0 0082a758 00000000 0x460fca0THREAD_SHA1_HASH_MOD_FUNC:  efd150661336c07d9595267c51e0ca21b89ae592THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  d7f481fbeaced98c3b76d603bdbafb765e5b3edeTHREAD_SHA1_HASH_MOD:  4d6a592812b1f521b481ecb6f54e3789559d0477FAULT_INSTR_CODE:  3843d80SYMBOL_STACK_INDEX:  1SYMBOL_NAME:  ntdll!RtlpTpWorkCallback+e3FOLLOWUP_NAME:  MachineOwnerMODULE_NAME: ntdllIMAGE_NAME:  ntdll.dllDEBUG_FLR_IMAGE_TIMESTAMP:  4ce7b96eSTACK_COMMAND:  ~9s ; .ecxr ; kbFAILURE_BUCKET_ID:  SOFTWARE_NX_FAULT_c0000005_ntdll.dll!RtlpTpWorkCallbackBUCKET_ID:  APPLICATION_FAULT_SOFTWARE_NX_FAULT_INVALID_POINTER_EXECUTE_BAD_IP_ntdll!RtlpTpWorkCallback+e3FAILURE_EXCEPTION_CODE:  c0000005FAILURE_IMAGE_NAME:  ntdll.dllBUCKET_ID_IMAGE_STR:  ntdll.dllFAILURE_MODULE_NAME:  ntdllBUCKET_ID_MODULE_STR:  ntdllFAILURE_FUNCTION_NAME:  RtlpTpWorkCallbackBUCKET_ID_FUNCTION_STR:  RtlpTpWorkCallbackBUCKET_ID_OFFSET:  e3BUCKET_ID_MODTIMEDATESTAMP:  4ce7b96eBUCKET_ID_MODCHECKSUM:  1490d9BUCKET_ID_MODVER_STR:  6.1.7601.17514BUCKET_ID_PREFIX_STR:  APPLICATION_FAULT_SOFTWARE_NX_FAULT_INVALID_POINTER_EXECUTE_BAD_IP_FAILURE_PROBLEM_CLASS:  APPLICATION_FAULTFAILURE_SYMBOL_NAME:  ntdll.dll!RtlpTpWorkCallbackWATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/MeshAgent.exe/0.2.1.3/605d2880/unknown/0.0.0.0/bbbbbbb4/c0000005/0460fc78.htm?Retriage=1TARGET_TIME:  2021-07-09T12:06:05.000ZOSBUILD:  7601OSSERVICEPACK:  17514SERVICEPACK_NUMBER: 0OS_REVISION: 0OSPLATFORM_TYPE:  x86OSNAME:  Windows 7OSEDITION:  Windows 7 WinNt (Service Pack 1) SingleUserTSUSER_LCID:  0OSBUILD_TIMESTAMP:  2010-11-20 07:02:55BUILDDATESTAMP_STR:  101119-1850BUILDLAB_STR:  win7sp1_rtmBUILDOSVER_STR:  6.1.7601.17514ANALYSIS_SESSION_ELAPSED_TIME:  17a7ANALYSIS_SOURCE:  UMFAILURE_ID_HASH_STRING:  um:software_nx_fault_c0000005_ntdll.dll!rtlptpworkcallbackFAILURE_ID_HASH:  {4749b61a-f48e-74ef-9b35-fcd02cf88b7e}Followup:     MachineOwner---------

Best Regards,
Ashish Gharde
Sr. Tech Support Engineer - SEP
Broadcom - Symantec Enterprise Division
https://support.broadcom.com/security
Working Hours – 07.30 AM - 04.30 PM India Time
_________________________________________________________________________________________________________

**Comment by OutbackMatt** [comment]
I've added exclusion in AVAST to every single workstation that I can find, and I still get heaps of these 'rootkit infection' messages.

(Same for AVG - owned by Avast)

Doesn't seem to stop Mesh agent from running though, which is just weird.

**Comment by dinger1986** [comment]
@si458 AV can close

**Comment by si458** [comment]
sadly this is always going to happen and the isnt nothing much we can do
it now adds a certificate to the exes to hopefully help windows find it legit but even thats not always correct!
one way around is to use ur own code-sign certificate AND/OR allow the exe in the antivirus you use
