### ISSUE TITLE
meshcentral behind loadbalancer

### ISSUE THREAD

**Issue by BrunoMaggi** [Ylianst/MeshCentral#306]
Hi,
    thank you for the great work, one of the best and simple that I've tested. 
I'm trying to define a basic configuration behind the load balancer to evaluate the Meshcentral in a public environment in terms of speed, and feature.
Using the guide I've done a basic setup then I've published the Meshcentral with the Alias port. The behaviour is strange, when I setup the LB the external site don't show anything (correct behavior in the lan), if I change the Port trying to set up with a different internal configuration I cannot logon (2factor authentication with OTP). What I miss ? Does not change with the change of WAN / LAN parameter...
thank you
best regards

**Comment by Ylianst** [comment]
Hi. Your going to have to be more precise about your situation. What load-balancer are you using? Can you send a anonymized version of your config.json? Are you using the "tlsoffload" setting?

**Comment by BrunoMaggi** [comment]
Hello Ylianst
- configured inside vsphere  photon 3.0 os with node.
- the load balancer is a pound version (zevenet implementation), it's the open source version.
- the current configuration (working inside):
    "settings": {
        "launch": true,
        "cert": "**************public and internal sitename",
        **"wanonly": true,**
        **"port": 443,**
        **"aliasport": 443,**
        "redirport": 80,
        "allowframing": true,
        "selfupdate": true,
        "allowhighqualitydesktop": true,
        "tlsoffload": false,
        "autobackup": {
            "backupintervalhours": 24,
            "keeplastdaysbackup": 10
        }
    }

tested with the following parameter (for each test a change in the parameter): 

 "tlsoffload": false,
 "tlsoffload": true,
 "tlsoffload": internal-ip-of-load-balancer,
 port = 8443 
 port = 4430

- tested with two kind of users, with and without OTP.
- no filter in the ip that can access (is be present a default that limit the internal network ?)
- I've done a test following the configuration for nginx (same parameter). same result.
- question: can be some kind of link between the x-forwarded-for parameter and the tlsoffload value ? If I don't specify that I have to reset the value of the  x-forwarded client IP the appliance receive the real external IP ... 

thank you

[gihub-cfg-1806.txt](https://github.com/Ylianst/MeshCentral/files/3300383/gihub-cfg-1806.txt)

**Comment by Ylianst** [comment]
Based on the information above, I would have a difficult time figuring out what is not working. I guess I should focus on one thing: You say that once setup behind the load balancer, the login does not work with OTP? Does it work without OTP and so, OTP is causing the issue? I presume you are using the Google Authenticator App?

Yes, there is a link between "x-forwarded-for" parameter and "tlsoffload". You need to specify the local IP address of the load balancer in "tlsoffload" for the server to make use of the "x-forwarded-for" header, otherwise it is ignored. This should not be a big problem so you can fix this later, but it will show the agents connecting from the local IP address of the load balancer instead of the true IP address on the Internet.

**Comment by BrunoMaggi** [comment]
Hello, 
 I will try to define a better test instead of wasting your time. I will define a specific test with the x-forwarded-for paramter fixed as you have specified, and we see. I will try also to alter the parameters in the configuration to recover a schema of the behavior ...
I will update as soon as I can
best regards
thank you

**Comment by Ylianst** [comment]
Closing this one, but feel free to re-open if needed.
