### ISSUE TITLE
MeshCentral and vulnerable versions of dependencies

### ISSUE THREAD

**Issue by Gheppy** [Ylianst/MeshCentral#3081]
When I update and execute the 
 npm audit fix --force
 command it shows the following information.
Can it be upgraded to newer versions for the dependencies below ?

![image](https://user-images.githubusercontent.com/84496256/131458529-ef00accd-f077-4c11-aea2-a8c284e50665.png)

 Thank you

**Comment by Ylianst** [comment]
The problem is that NeDB ([GitHub](https://github.com/louischatriot/nedb)) is no longer being maintained and has not been touched in 6 years. For any production usage of MeshCentral, I recommend using MongoDB... but MariaDB and MySQL can also be used. When using any other database, NeDB will not be used anymore.

This said, I may need to look into an alternative.

**Comment by Gheppy** [comment]
I use MongoDB

Thank you

**Comment by Ylianst** [comment]
Good. MongoDB should not have any security issues.
