### ISSUE TITLE
Dashboard showing 127.0.0.1/::1 for agent connections when using a proxy

### ISSUE THREAD

**Issue by Bobberty** [Ylianst/MeshCentral#3083]
Dashboard is showing 127.0.0.1/::1 when using a proxy in front of MeshCentral server.
Thanks.....

**Comment by nzalev** [comment]
This could be one of a couple things. You should have TlsOffload set to "127.0.0.1" in your config.json. In addition, you need to include in your proxy config the original IP of the host making the connection. In Nginx, this looks like 
```
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

**Comment by Ylianst** [comment]
Two things you need to do:

- As mentionned by @nzalev , you need to make sure your reverse proxy adds the `X-Forwarded-For` HTTP header, so that it will tell MeshCentral the actual source IP address of the connection.
- You need to put one of these two lines in the "settings" section of the MeshCentral config.json:

```
"TlsOffload": "127.0.0.1,::1"
```

or

```
"trustedProxy": "127.0.0.1,::1"
```

Put the first line if your reverse proxy is going TLS, put the second if it's not. These lines will tell MeshCentral that if a `X-Forwarded-For` HTTP header is present and coming from one of the addresses mentioned, to make use of the header.

Also, I have a YouTube video on how to [configure MeshCentral with NGINX here](https://www.youtube.com/watch?v=YSmiLyKSX2I) that also talks about this topic.

Hope that helps,
Ylian

**Comment by Bobberty** [comment]
TLSOffload question:
    "TlsOffload":["127.0.0.1","[::1]"],
Seems to be configured correctly.

Proxy question  (Config from haproxy):
    backend meshcentralv4
        http-request add-header X-Forwarded-Host %[req.hdr(Host)]
        server ipv4 127.0.0.1:444


Configs and connectivity seems to work fine.

**Comment by Bobberty** [comment]
Ok...  Just noticed the "X-Forwarded-Host" vs "X-Forwarded-For".....

**Comment by Ylianst** [comment]
Did that fix it? Section 16 of the [MeshCentral User's Guide](https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf) has an example NGINX configuration that may help.

**Comment by Bobberty** [comment]
I decided to fight against the easy solution.  Must have something to do with learning how to use a tool properly.
Haproxy has a built-in feature that that provides an X-Forwarded-For automatically.

For my ability to find this solution in the future:
haproxy.conf:
...
frontend https
        option forwardfor
        bind :::443 v4v6 ssl crt /etc/haproxy/crt/ ca-file coolrootcert.pem verify optional crt-ignore-err all ca-ignore-err all
...

All IP addresses will be reported in IPv6 notation.  That meas that IPv4 addresses will show up as ::ffff:192.168.0.22:42154 for the X-Forward-For header as well as the dashboard.

Thanks for reminding me that easy is usually cowering under a chair in the corner of the room.
