### ISSUE TITLE
Ideas: Backup and restore within web interface 

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#3084]
Recently with all the issues we have encountered when updating, I thought it would be nice to have a backup and restore feature within the web interface, futhermore, I think the upgrade dialog box could be improved, by having some key information such as: Last update version, date and time, last Backup version, data and time, even if its automatic backups saved to google drive, and an option to create a local backup on the spot and specially, restore this last local backup. 

Upgrades are so simple, why not make the restore of the last version just as simple. 

It would be nice to have a small description of what version of MC is backed up, something we could read and also add notes to. Considering that we might upgrade the actual OS or dependencies outside of MC, it would be nice to have some notes in the backup description so we may restore it properly.

As for the backups, there could be a simple backup history info/log, say the last 3 backup dates and location, local or cloud, manual or automatic, just as a reference to find the backup if needed. 

This is just a bunch of ideas. I hope to get some feedback from the community to make the ideas better before turning them to actual feature requests.

**Comment by Ylianst** [comment]
Good ideas. Note that when using NeDB as a database, there are options to backup and restore on the "My Servers" tab.

![image](https://user-images.githubusercontent.com/1319013/131623689-758cf40c-c610-468e-81d6-0fe1b5d1eb35.png)

These just zip/unzip the "meshcentral-data" folder. I removed these options when using any other database as it would create the false impression that a correct backup was done... but the database backup would be missing.

I then added automatic daily backups by default. The daily backups go in "meshcentral-backups" and include MongoDB dump and ZIP compression. I also added [WebDAV](https://meshcentral2.blogspot.com/2020/09/meshcentral-agent-on-router-linux.html) and [Google Drive](https://meshcentral2.blogspot.com/2020/08/meshcentral-google-backup-auditor.html) setup so MeshCentral can automatically send the backup offsite. You can also configure auto-backups with have a ZIP password.

This said, always room for more improvements. Let me know if you tried any of these existing options.

**Comment by rodrigolzd** [comment]
I will test out a bit more this options already available just to find out how they work and perhaps improve on. Im using MongoDB, but I dont have much experience with it.  I wonde if its possible to switch my current setup to mysql for example. Not sure how and what would be effect by this change.

**Comment by Ylianst** [comment]
The web based backup/restore is only NeDB... as for auto-backup of the database, that is only supported with MongoDB. Otherwise, you can change to MySQL but it will not change much in this area. You will have to backup the database yourself. You can look in the documentation for `--dbexport` and `--dbimport` if you want to switch DB's.

**Comment by nzalev** [comment]
I actually implemented MySQL/MariaDB autobackups a while back in #2503, so both MongoDB and MariaDB/MySQL dumps are included in autobackups.

---

To further add to the above, adding a restore option actually poses some difficulties in that meshcentral relies on the db tools in the first place to create the backup files (mongodump, mysqldump). It would also rely on the db utilities to restore those backups.

There is a lot that can go wrong with a db restore in this kind of scenario, and how different modes of failure should be handled is not really obvious. This is even more true in MySQL/MariaDB where you are required to create a user and database. If you are restoring to a fresh system, you would still need to prepare the db by creating a user and its database before you can restore the data. At that point, you may as well run `mysql -u mesh -p < dump.sql` since you are already in the sql shell.
