### ISSUE TITLE
HTTPS with ECC private key does not work

### ISSUE THREAD

**Issue by multiflexi** [Ylianst/MeshCentral#3086]
Hi,
Does MeshCentral work with ECC private key, secp384r1 specifically? I am getting an error in the browser saying no common cyphers are available. I am sure the key and certificate are fine because pairs with the same parameters work well elsewhere under Apache. I used an RSA key but I renew the cert with an ECC key. I have put the files in meshcentral-data folder and named it webserver-cert-private.key, webserver-cert-public.crt and webserver-cert-chain1.crt. I am using Debian 11.

**Comment by Ylianst** [comment]
MeshCentral uses [Node-Forge](https://github.com/digitalbazaar/forge) for it's Cryptography which does not support ECC. Because of this, I may need to look for some other crypto library.

This said, if you have a reverse-proxy in front of MeshCentral that does TLS with a ECC cert, that is supported. I did a bunch of work to make sure that was supported. But replacing the web certificate files in "meshcentral-data" with ECC certs will not work.
