### ISSUE TITLE
Meshagent.exe Excluded from Symantec

### ISSUE THREAD

**Issue by johnczer** [Ylianst/MeshCentral#309]
Good news! I was trying the MeshCentral in a production environment and when trying to download and install the meshagent.exe on a remote computer the file was blocked by Symantec Endpoint Protection. I could have created an Exclusion Policy for this file but would have to do it on all of our sites.  I took the chance and submitted the request to Symantec Security and their response was this:
Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:

    File name: meshagent.exe
    MD5: B5539AD1CFD786658F7BF7D24945A337
    SHA256: 2868D3BB0B136C6C79D336D10C28FED658B9EA5FA6E76C2069B7B5906CA000D0
    Note: Whitelisting may take up to 24 hours to take effect via Live Update

**Comment by Ylianst** [comment]
Nice, that is great news. As of MeshCentral v0.3.6-m, we made changes to the 32bit Windows agent to pass all anti-virus tests, but this is still really good.

**Comment by johnczer** [comment]
I forgot to mention that this is with the 64bit meshagent.  Will the 32bit agent run on a 64bit OS?

**Comment by krayon007** [comment]
On windows, the 32 bit agent will run on 64 bit as long as you aren't talking about Windows PE (which is 64bit only). For Linux, 32 bit will run on 64 as long as you install the 32 bit libc package. Not sure about MacOS or FreeBSD.

**Comment by mschubeck** [comment]
"meshagent.exe" isn't the only one that needs to be excluded from scanning or permitted by the AV vendors.  The one that I consistently see getting quarantined is "C:\Program Files\Mesh Agent\MeshAgent.update.exe", so we've just made a habit of adding both the file and the path to our exclusions policies.

The problem we see is that when the server is updated, the agent is removed and not replaced because the updater is interrupted on systems that we haven't already applied this policy to.

**Comment by Ylianst** [comment]
"MeshAgent.update.exe" is the next version of the agent and should be removed once the agent update occurred. So that file will change at each version. Of course, the bigger problem remains that for exceptions to work, you can't update the agents anymore. So far, the new MeshAgent seems to do the trick and pass the anti-virus test. If anyone knows otherwise, let me know.

**Comment by johnczer** [comment]
I guess it depends on what AV software is installed. We use Symantec on most of our sites but there are a few rare instances where the end user has another AV software on their personal devices like the one I ran into today...Avira which I've never heard of before today but this one did flag the meshagent, scanned and let it install and run though.

**Comment by Ylianst** [comment]
Ok, I think I will close this one since I am not sure there is anything actionable. I do want to say thank you for submitting to Symantec, this is really nice.
