### ISSUE TITLE
Overview of installed agent versions and how to push new update to agent?

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#312]
Where can I see an overview which version is currently in use by the agents?
And how to push an update to the agent?

**Comment by whalehub** [comment]
You can find the version of MeshCore that's installed on a machine in the "Console" tab. Updates are pushed to agents automatically; I'm not aware of a way to do it manually.

**Comment by Ylianst** [comment]
Right now, all agents are auto-updated when the server updates. It takes about 10 seconds for an agent to update and so, it's done very quickly. When the agent connects to the server, it sends it's own executable's hash to the server and if the server notices it's not the right one, it will push an update to the agent. The current system means that if you go back to an older server, all the agents will also go backwards.

Separately, agents run a "meshcore.js", this is a JavaScript file that tells the agents what to do. It's like the agent's brain. That is also hashed and if the hash does not match, the server will send an updated "meshcore.js". The binary executable is always updated before the meshcore.

MeshCore.js is really nice because most of the time we can update the agent's behavior on all platforms without updating or recompiling the agent. You guys are also free to take a look at that file and add features on the agent.

So, there is not agent version in use right now. For Windows, you can right click on the agent executable, select the "Digital Signatures" tab and look at the signature date. That should give you a solid indication of the agent in use.

Hope it helps,
Ylian

**Comment by hunter-nl** [comment]
Thank you for the explanation.
