### ISSUE TITLE
Question: Intel AMT port 623, 16992 scans. Can this being disabled?

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#3139]
Customer has Intel AMT devices. On these devices an MC agent has been installed for remote access. Due (firewall) restrictions and we do not want to use AMT feature. We still see a lot of tries to connect from MC server to the agents on port 623 and 16992.
Can this "scanning" being disabled?

**Comment by jsastriawan** [comment]
Try setting your config to "wanonly" to true. See if it will stop scanning local AMT devices.

**Comment by Ylianst** [comment]
Ok, you can add the following in the settings section of MeshCentral v0.9.27:

```
"amtscanner": false
```

That will disable Intel AMT port scanning on the local network.

**Comment by Ylianst** [comment]
Ok, MeshCentral v0.9.27 is out.

**Comment by hunter-nl** [comment]
@Ylianst 
> Ok, you can add the following in the settings section of MeshCentral v0.9.27:
> 
> ```
> "amtscanner": false
> ```
> 
> That will disable Intel AMT port scanning on the local network.

On local network it is not that big problem. But I see it to remotely devices on WAN. And most customers do not have ports 623 and 16992 open on their firewall. I see about 12 connection tries per minute per device. And that's useless resources being used by MC and network bandwidth, Firewall resources, etc. If it can being disabled also for WAN devices, that would be great.

**Comment by Ylianst** [comment]
So, if MeshCentral is in WAN mode, any type of scanning or outbound connections should not happen. The new "amtscanner" flag is only for LAN/Hybrid mode since in WAN mode the scanner was always disabled. Are you sure your server is in WAN mode?

You can see [the code here](https://github.com/Ylianst/MeshCentral/blob/97420ffac2366a408df8b68726e729deb4d9066e/meshcentral.js#L1571). If you set:

```
"WanOnly": true
```

The Intel AMT scanner and MeshScanner will not be created.

**Comment by hunter-nl** [comment]
I’ve running it in hybrid mode.
I need also access to local without agent devices

**Comment by hunter-nl** [comment]
@Ylianst In the meshcentral-advanced.json config file the following part mentioned:
```
"_amtScanOptions": [
        "LabNetwork 192.168.15.0/23",
        "SalesNetwork 192.168.8.0/24"
      ],
```
In the meshcentral-config-schema.json the amtScanOptions does not exist. Has amtScanOptions feature being removed?

**Comment by Ylianst** [comment]
I realized there was a problem with:

```
"amtscanner": false
```

I am putting in a fix, will be in MeshCentral v0.9.28.

I just added "amtScanOption" to the schema. It was just missing. Note that "amtScanOption" is just to add options to the user interface, it does not change anything for network scanning.

> Maybe change the scanning feature to only scan on local networks. Never on WAN, regardless of the mode MC is running.

The problem is that MeshCentral does not know what is your local network and what is not. I guess I could add a configuration so you can specify what IP address range is allowed for scanning. I am going on vacation, I can look at it when I get back.

**Comment by hunter-nl** [comment]
Have a good vacation. You deserved it for all the hard work you did with meshcentral.

**Comment by Ylianst** [comment]
Thanks. I will have MeshCentral v0.9.28 published in a few minutes :)

**Comment by Ylianst** [comment]
MeshCentral v0.9.28 is published. Let me know if it works now. Adding `"amtscanner": false` in the "settings" section of the config.json should now disable AMT scanning.

**Comment by hunter-nl** [comment]
> MeshCentral v0.9.28 is published. Let me know if it works now. Adding `"amtscanner": false` in the "settings" section of the config.json should now disable AMT scanning.

This solved it. Thanks!
