### ISSUE TITLE
Feature request/question: Mesh agent user consent popup above login screen in Windows.

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshCentral#3145]
Hi,
Is it possible to show user consent popup above login screen in Windows?
1. For Terminal access - This works when user is not logged in.
2. For remote access - This doesn't work. consent shown only inside the user login screen.

**Comment by si458** [comment]
if you have user consent switched on AND the is no user logged in, it wont connect because nobody can consent by default
HOWEVER you can set `consentTimeout` and `autoAcceptOnTimeout` now which will automatically accept consent if it times out
you set these under `consentMessages` which is under `domains`
![image](https://github.com/Ylianst/MeshCentral/assets/765314/e7a88124-3b1c-4a19-b470-0da433933bf5)
