### ISSUE TITLE
ERR: ERROR: MeshCentral HTTP server port 80 not available.

### ISSUE THREAD

**Issue by MalteKiefer** [Ylianst/MeshCentral#3173]
Hello,

I tried to use MeshCentral in production.
So I use this config:

```json
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "tv.example.de",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "kBbqtksZdekKBp7T9t5nvgeeyxBdwdiBnCaB9Zh8YJAu5",
    "minify": 1,
    "Port": 8989,
    "AliasPort": 443,
    "ExactPorts": true,
    "TlsOffload": "127.0.0.1",
    "CertUrl": "https://tv.example.de/",
    "AllowHighQualityDesktop": true,
    "SelfUpdate": true
  },
  "domains": {
    "": {
      "title": "Remote Controll",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

On the same server, an Apache is running with different websites.
When I start the server, I get this error:

>ERR: ERROR: MeshCentral HTTP server port 80 not available.

**Comment by nzalev** [comment]
This happens because the default redirection port is port 80, combined with the fact that you have "ExactPorts" set to true in your config. 

When you add "ExactPorts", meshcentral will exit with an error in the case that it cannot bind to a port. As a result, when the redir server cannot bind to its default port 80, meshcentral exits. 

You need to either add `"RedirPort": 0,` which disables the redirection server or remove `"ExactPorts": true,`

**Comment by MalteKiefer** [comment]
Thanks, that fixed it
