### ISSUE TITLE
Unable to send CTL-ALT-DEL to a 2008 standard server VM

### ISSUE THREAD

**Issue by lokasoft** [Ylianst/MeshCentral#3182]
Noting happens when trying to send CTL-ALT-DEL to a 2008 standard server (32 bit). Sending any of the other special keys works fine. Using ScreenConnect to the same server works fine.
On 2008 R2 servers and higher it works fine.

In another issue I read about the SAS policy but this policy is not available on 2008.

Is there any workaround to send CTL-ALT-DEL to a 2008 server?

**Comment by jftitan** [comment]
I've used the On-Screen Keyboard as a work around for Server 2008.    But I too can confirm this problem, however once logged/signed in, the remote keyboard function works.   So it's like the agent's ability to use the keyboard is disabled at the login prompt.

**Comment by lokasoft** [comment]
On-Screen keyboard works for me, thanks.

**Comment by krayon007** [comment]
> It is funny, because i wanted to start new issue with almost similar problem. Sending CTRL+ALT+DEL do not work on Hyper-V Server 2019 (64-bit) (it is like Core Windows 2019 Server, but without GUI/Explorer used as Hyper-V host).

For your case, is that OS using Windows Core? I ask, because in my notes when I looked up how I inject CTRL-ALT-DEL, it says that the SAS API does NOT exist on Windows Core.

**Comment by krayon007** [comment]
As far as Windows Server 2008 goes, I found the MSDN documentation says that the SAS.dll that I'm using is not shipped with Windows Server 2008. The MSDN documentation says to work around it, to copy the .dll from another version of Windows. I tried the older way of sending CTL-ALT-DEL on Windows Server 2008, and it does NOT work, so that means in order to get it to work, you would need to copy the .dll from another machine.

I must also point out, that Windows Server 2008 does not implement LOAD_LIBRARY_SEARCH_SYSTEM32, which means you would be vulnerable to dll injection. Windows Server 2008 R2 requires [KB2533623](rt.microsoft.com/en-us/topic/microsoft-security-advisory-insecure-library-loading-could-allow-remote-code-execution-486ea436-2d47-27e5-6cb9-26ab7230c704) to be installed, for that flag to be supported.

**Comment by nicrame** [comment]
> 
> 
> > It is funny, because i wanted to start new issue with almost similar problem. Sending CTRL+ALT+DEL do not work on Hyper-V Server 2019 (64-bit) (it is like Core Windows 2019 Server, but without GUI/Explorer used as Hyper-V host).
> 
> For your case, is that OS using Windows Core? I ask, because in my notes when I looked up how I inject CTRL-ALT-DEL, it says that the SAS API does NOT exist on Windows Core.

Well, i'm not sure, but i believe that it is like Windows Server Core. Hyper-V Server is just another product, but it looks like Windows Server Core with some Hyper-V functions installed and configured by default. But there is no GUI. Just command line windows to login and configure it after that.

**Comment by si458** [comment]
please follow #3452 as this is the same issue but newer versions of windows server
server 2008 is now EOL so not really supported
