### ISSUE TITLE
AMT devices activation/provisioning

### ISSUE THREAD

**Issue by sysadmin-us** [Ylianst/MeshCentral#3188]
Hi Ylian,

I just want to know how to activate bulk amt devices like 500-1000 devices in a single go with meshcentral, Is there any possibility or any system available in meshcentral except from USB activation method?

**Comment by Ylianst** [comment]
I have a [YouTube video on that topic premiering tomorrow](https://www.youtube.com/watch?v=naWKE3rT6e8). In general, you can go in the device group and set your Intel AMT activation policy. MeshCentral will try to match that policy for all existing and new devices.

In general, you can't just activate into Admin Control Mode (ACM) without going in the BIOS, using a USB key or buying a activation certificate and using the Ethernet port to a DHCP server with the same name as your activation cert.

You can setup MeshCentral to activate your devices into Client Control Mode (CCM) and keep watching for opportunities for activate to ACM when you have a cert or use USB.

I do want to point out that the ACM activation rules are not something MeshCentral controls. It's rules Intel AMT has that can't be bypassed so that people don't abuse AMT.

Let me know if that makes sense and if you have any additional questions.

**Comment by sysadmin-us** [comment]
Hi Yilian, 

Thanks for the reply got it.
