### ISSUE TITLE
Agent won't connect after reboot

### ISSUE THREAD

**Issue by maxscc** [Ylianst/MeshCentral#3239]
I think it stayed connected through the meshcentral backup/restore, but broke after it's first reboot after the server was restored. The log shows this error when trying to connect:

[2021-11-03 10:25:18 AM] [80645B8D669A2A74] ..\microstack\ILibParsers.c:10746 (0,0) Certificate loaded from DB was not signed by our root cert in the Cert Store

When doing meshagent run it just tries to connect and times out.  I have other machines on this network that work fine.

I'm using letsencrypt .  This server config also was backed up/restored to a new VPS.  No other agents have an issue (I only have 7 agents). Reinstalling the agent doesn't work.  msh file has the proper FQDN.  Agent version from 2021-Aug-30

Meshcentral version 0.9.40

**Comment by Ylianst** [comment]
A few things could be going on. If your server is running in LAN mode, the agents will multicast on the network to find the server. If you have the latest versions of MeshCentral, you can see in what mode you are running by typing `info` in the server console:

![image](https://user-images.githubusercontent.com/1319013/140166952-296e5e41-1a86-419a-8ca2-a72a0ff505ab.png)

One way to see what is going on is to go on a computer that can't connect, go in the `C:\program files\mesh agent` folder and edit the `meshagent.msh` file with notepad. It should have the following lines:

```
MeshName=Lab Computers
MeshType=2
MeshID=0xEDBE1BE3771D69DF39D35DF97F7E9A6F7D75DB86F9D9EE3B735EBB7DB6B4E7971EF34D36EBB6B875CF3D7DED1EE7CD5C
ServerID=D99362D5ED8BAEA8BF9E743B34B242256370C460FD66CB62373C6CFCB204D6D707403E396CF0EF6DC2B3A42F735135FD
MeshServer=wss://central.mesh.meshcentral.com:443/agent.ashx
```

If `MeshServer` is set to `local`, the agent will multicast to find the server. You can compare the values here with the values of a computer that can connect.

When, stop the "MeshAgent" service, open an administrator command prompt, to go `C:\program files\mesh agent` and type:

```
meshagent.exe run
```

You will see exactly what the agent is doing to try to connect. Hopefully you we see what the problem is.

**Comment by maxscc** [comment]
Hi.
My server is in Wan Mode.  

When I run 'meshagent run' it just times out trying to connect to the server.  It's resolving correctly.

My meshagent.msh is correct.

**Comment by maxscc** [comment]
I updated to 0.9.46 and now it suddenly started working.

**Comment by kpetrow** [comment]
In my case the certify the web auto renewed the certificate but the generated mesh agent installer didn't use the new cert.  Needed to restart mesh central server, and then the installer was generated using new cert

**Comment by kpetrow** [comment]
Had this issue again. Rebooting machine that was running mesh agent resolved.  This occurred after multiple installs and re-installs by tech
