### ISSUE TITLE
User Consent Popup Real User Name

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3257]
Hi,

The Mesh Agent Consent Message personalization options are amazing:
```
"ConsentMessages": {
			"title": "MeshAgent",
			"desktop": "{0} message for desktop session",
			"terminal": "{0} message for desktop session",
			"files": "{0} message for desktop session"
			},
```
I believe that the { 0 } means to grab the name of the user that's starting the session, but I think it would be better that we would be able to choose between some of the other user profile data, for example, { 0 } for the UserName (or in some cases the email if `"UserNameIsEmail": true,`), { 1 } for the **Real Name**, { 2 } for the email of the user (in case `"UserNameIsEmail": false,`)

![image](https://user-images.githubusercontent.com/25281984/140582895-076b917c-fdc4-459a-8dde-4d6ec2e5e5d1.png)

Thanks!

**Comment by Ylianst** [comment]
Right now, {0} will display the real name if set, otherwise the username. {1} will display the username.

You can set the user's real name in the "My Users" tab.

![image](https://user-images.githubusercontent.com/1319013/140589953-3a83ce30-e76f-412b-a295-039cda750a54.png)

Let me know if that works.

**Comment by K-O-K** [comment]
Thanks, that worked! The `{ 0 }` does show the **Real Name** of the user.
