### ISSUE TITLE
Godaddy Certificate

### ISSUE THREAD

**Issue by nobby83** [Ylianst/MeshCentral#326]
Would it be possible for someone to give me detailed instructions of how to use our Godaddy certificate as the root certificate please? I cant find anything in the documentation about using any other certificate other than letsencrypt. thanks

**Comment by merlinweb** [comment]
Same request here, I've a wildcard godaddy certificate for my domain, It would be great to install as root certificate
Thanks for help

Merlinweb

**Comment by Ylianst** [comment]
You should be able to replace the "webserver-cert-public.crt" and "webserver-cert-private.key" files in "meshcentral-data" with your GoDaddy certificate and wildcard should work, but keep "cert":"servername" in the settings section of your server, so that MeshCentral knows what is it's own name.

It's possible you will need to specify intermediate certificates, in that case create files "webserver-cert-chain1.crt", "webserver-cert-chain2.crt", "webserver-cert-chain3.crt"... in the "meshcentral-data" folder with the intermediate certs.

You will need to restart the server to make the changes effective. For the wider audience reading this, MeshCentral also has Let's Encrypt support built-in, so that is another option.

Hope it helps,
Ylian

**Comment by nobby83** [comment]
![certs](https://user-images.githubusercontent.com/52241145/60255039-e6860480-98c6-11e9-8778-40a8391ac25f.JPG)
I tried replacing the existing certificates and when I came to restart the server it would not restart. I then switched back to the old certificates and it wouldn't start then either. I had to reinstall it before it would work again which lost all the config I had set up. I looked at the Lets Encrypt option, it seems to be way over complicated and as we already have a domain certificate not necessary to go down that route. I reckon most larger organisations who implement this wonderful product will require the ability to use their own imported certificate and IMHO there needs to be an easy way to do that.
Above is a pic of the certificate download from Godaddy, it would be helpful to get a step by step walk through of how to make these certs work with MeshCentral, I'm sure its going to be a frequently asked question. thanks Ian

**Comment by Ylianst** [comment]
In the past I have setup MeshCentral with a GoDaddy certificate, so I know it's possible. If there is a "mesherrors.txt" in your "meshcentral-data" folder, send it over (feel free to email privately). That should show me why the server was not starting.

When doing this type of setup, it's probably best to run the server manually. In a command prompt, got in the folder above "node_modules" and type "node ./node_modules/meshcentral". This way, you see what is going on.

For "webserver-cert-public.crt" and "webserver-cert-private.key", you can edit these files with notepad and it will just cut & paste the certificate in the right place. For more detailed instructions, you should send me your files privately, but please XXXXX out the RSA private key that is probably in the .pem file.

**Comment by nobby83** [comment]
I emailed you Ylianst

**Comment by nobby83** [comment]
I sent you the mesherrors.txt file. When I try to run the server manually from a command prompt I get the following error, 

C:\Program Files\Open Source\MeshCentral>node ./node_modules/meshcentral
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11

C:\Program Files\Open Source\MeshCentral>

It looks like the folder/file structure is different. Beneath the /node_modules/meshcentral there is only a folder called daemon.
I guess in order to make this work i will need to re-key the certificate at Godaddy and to do that i will need a CSR request generating from Meshcentral somehow. The private key in the Godaddy cert is no longer in use because the server has been decommissioned.

Can you help?

**Comment by Ylianst** [comment]
Sorry for the delay, I will try to find your email and help today.

**Comment by Ylianst** [comment]
Ok, took a look at the mesherror.txt log. There are two issues, one if that there is an error because the certificate and key files don't match. The other is the missing "winservice.js" file.

If you going to run MeshCentral in any important way, I really recommend going to the command prompt and doing:

```
mkdir c:\meshcentral
cd c:\meshcentral
npm install meshcentral
node c:\meshcentral\node_modules\meshcentral
```

Once running, hit ctrl-c, copy your meshcentral-data and meshcentral-files folders instead of the created ones. Then you can run meshcentral like this:

`node c:\meshcentral\node_modules\meshcentral`

or 

`node c:\meshcentral\node_modules\meshcentral --install`

The second one will run as a background service. You can also do --start / --stop / --uninstall. I think it's important to run from the command line because you can try to run MeshCentral without having it in the background, so it's easier to see what is going wrong. If the certificate files are not right, running MeshCentral from the command line makes it easy to see what is going on.

Hope it helps,
Ylian

**Comment by Ylianst** [comment]
Ok, going to close this one as I don't think it was a server problem. However, please feel free to re-open if needed.
