### ISSUE TITLE
User consent Override for Meshcentral Assistant ( Always Connected)

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3267]
Dear Ylianst,
We are using Meshcentral Assistant (Always connected) versions in approximately 4000+ agent PCs. The main reason behind using Assistant instead of the agent is that Agent crash working in every 5minute due to Symantec AV.Due to security reasons, we can't disable the Symantec AV, and this 5-minute disconnection is annoying the users. 

While using Assistant we can't see such frequent disconnections. Please refer [here for Symantec issues](https://github.com/Ylianst/MeshCentral/issues/3046#issuecomment-904626042)
Since the Always connected assistant require user consent so we are unable to perform the bulk actions like ( File upload, Run commands, etc....). I understand the assistant is self-signed but if possible please enable override options for assistant user consents at least for Admin users / through config.js / for bulk actions.

**Comment by Ylianst** [comment]
Hi. MeshCentral Assistant is signed with a real trusted certificate and MeshAgent is signed with an un-trusted self-signed certificate. Because Assistant is signed with a real certificate, I have to require user consent so that Assistant can't be used for bad uses like malware. If I removed the user consent, it would make it possible to use Assistant to do bad things and open the possibility that my certificate would be revoked. As a result, I can't remove user consent from Assistant.

Another way to put it, if I remove user consent, my certificate will be revoked and Symantec AV will do the same as MeshAgent.

Hope that makes sense. I will not be removing user consent from Assistant.

**Comment by VINISHVV** [comment]
@Ylianst - Thanks, But the Symantec issue i have noticed in Windows 7 agents only. Rest of the OS it's working fine.

Can you please look into this once  ?

**Comment by Ylianst** [comment]
Maybe the problem is that only with 32bit Agent, in that case you need to use 64bit Agent. If this is the issue, I can't do anything. You need to white list 32bit Mesh Agent with Symantec. There is nothing I can do.
