### ISSUE TITLE
adddeviceuser in meshuser.js has inconsistent/unuseful return states

### ISSUE THREAD

**Issue by HuFlungDu** [Ylianst/MeshCentral#3274]
Call `adddeviceuser` with a nodeid that does not exist and it will simply return, but will not send any data back on the calling websocket, so the user will not know if their command failed or succeeded.

Also, if you try to add users that don't exist, it will just send back `{result: 'ok'}`, even on failure state. Would be useful if it acted like `addusertousergroup` and sent back what the result was for each user.

**Comment by HuFlungDu** [comment]
Looks like the same problem occurs in `editmesh` if you send a mesh that doesn't exist. I'm going to  document any I find in this bug, since they are essentially the same issue.

**Comment by Ylianst** [comment]
Thanks for the report. Indeed, when the command are called by the web page, they don't need a response since the change even will change the state if needed. When MeshCMD was built, I have to start adding responses for all of the commands and have not done all of them. So your completely right, I will add them. Your also free to submit pull requests to add responses if you like, I will gladly accept them.

**Comment by si458** [comment]
this should now be fixed as meshctrl.js now includes a responseid which tells meshcentral to return data if errors etc
