### ISSUE TITLE
Auto Update Enabled, server seems to crash

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#328]
I have noticed that when I have auto update enabled, when a new release is pushed my server seems to crash. I need to manually go to check for updates, running the meshcentral installer. Performing a server restart does not load the site again as the service fails to start.

in the mesherrors.txt I can see the following error

-------- 6/27/2019, 12:46:42 AM ---- 0.3.6-w --------

internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\winservice.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11

When I manually run the installer it says the current version is unknown, and can upgrade to the latest. Once I perform this update, it completes the update and server is operational again. 

<img width="249" alt="Error" src="https://user-images.githubusercontent.com/51713320/60248023-af5d2680-98b9-11e9-88dc-6fa47f5e55a7.png">

**Comment by Ylianst** [comment]
I just published a new MeshCentral Installer and removed the auto-update check box completely. It was never a good idea to perform auto-update because at any time the server is at much higher risk of having issues with no one around. The auto-update can still be set in the "config.json" (I use it on my test servers).

I will need to see that is going on with the current version indicator. That is weird.

**Comment by vish84** [comment]
I should have mentioned, i had set the auto update in the config file and not from UI. I only run the UI again as the server services failed to start. This is when i noticed the unknown value. However i have also tested with  auto update not set, and checked when a new version has been released the current version and latest available were both shown correctly. I believe this is a corner case where the server is trying to perform an auto update, but fails which results in the UI showing the version as unknown.

**Comment by Ylianst** [comment]
Thanks for the details. I don't have auto-update set to true on my own servers so, probably why I would not come across this. Auto-update is really a bad idea as you can be away and the server stops working because the update failed. Best to have a administrator present when the update is done. I am thinking of just making that switch undocumented.

**Comment by Ylianst** [comment]
So, there is no way auto-update is going to work when MeshCentral is running as a Windows Service. Because of this, I disabled auto-update when this situation is detected. You have to use the MeshCentral Installer to perform the update or do it manually and run "node meshcentral --install" again after the update.

**Comment by vish84** [comment]
Thanks performing a manual update will be fine
