### ISSUE TITLE
Meshagent install option request

### ISSUE THREAD

**Issue by baclaeys** [Ylianst/MeshCentral#3286]
I've noticed that after I install the meshagent on a Windows device it will not reconnect after a reboot.  Sometimes it will reconnect if I restart the agent, but this should not be necessary.  What I have done for a workaround is to modify the meshagent.msh file by changing "MeshServer=localhost" to "MeshServer=wss://IP.address.of.server:443/agent.ashx".  This has allowed my Windows devices to automatically reconnect to the meshcentral server after a reboot.

What I would like to be able to do is have the option to specify a different configuration for the MeshServer line in agent.msh during the install.

Example:  meshagent64-Default.exe -fullinstall --MeshServer="wss://IP.address.of.server:443/agent.ashx"

**Comment by Ylianst** [comment]
Hi. What is going on is that your MeshCentral server is in LAN mode and so, it was not given a static DNS name or IP address. In this mode, the agents will multicast on the network to find the server, but understandably, the multicast will not always work depending on network conditions, especially over WIFI. You can find [a video on LAN, WAN and Hybrid mode here](https://www.youtube.com/watch?v=gx5Fh3pQOns).

To fix this, add the following line in your `meshcentral-data/config.json` file.

```
{
  "settings": {
    "cert": "myserver.sample.com",
    "wanonly": true
  }
}
```

The first line will indicate that IP address or DNS name the server is assigned, the second line is optional and indicates that you don't want to do local network management from your server. The second line will put the server in WAN mode.

You can use an IP address in "cert", but I recommend using a DNS name, that was you can change the DNS name IP address later without having to reconfigure all your agents.

Once you set the "cert" value, restart your server and each agent you install will connect to your server correctly.

Hope that helps,
Ylian

**Comment by baclaeys** [comment]
Thank you for such a prompt response.  I will have to test that out today.  If I put the server in hybrid mode will it still have access to Intel AMT devices?  Also, do you know if there is any documentation for configuring Intel AMT to connect to a server in WAN mode?

**Comment by Ylianst** [comment]
For Intel AMT, if you are in Hybrid Mode, MeshCentral can access Intel AMT on your local network (port 16992/3). You also have the option to go into WAN mode and setup Intel AMT CIRA so that Intel AMT will connect to the MeshCentral server. Both will work, it's up to you to decide what is best in your situation. If your managing computers on a local network, Hybrid Mode is certainly a good option.

I have a [YouTube video on Intel AMT and CIRA here](https://www.youtube.com/watch?v=naWKE3rT6e8). It covers setting the Intel AMT policy which should be simple.

There are a lot of settings in the config.json for Intel AMT that I don't have documentation on, I should get on that. For example to set WIFI profiles, set Intel AMT password that MeshCentral should automatically try, ACM activation certificate, etc.

**Comment by Ylianst** [comment]
No replay, closing.
