### ISSUE TITLE
Stable Branch not updating on my latest update

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#3298]
Hi MeshCentral team,

I seem to have a broken updater on my server, because my version shows a 0.7.x stable release... Is this something you have seen or is this expected behavior? 

SomeGuru![image](https://user-images.githubusercontent.com/48393851/143354644-92b134ac-1544-4553-8f41-c1fc3f94550f.jpeg)

**Comment by nzalev** [comment]
```
noah@L460:~$ npm dist-tag meshcentral
latest: 0.9.52
stable: 0.7.89
```

These are the current values. I don't know what the stable version used to be if it was different. Maybe Ylian rolled the stable version back if it is different.

**Comment by Ylianst** [comment]
These are the correct values.

"Latest" is always the very latest published version, and "stable" is a version that has run for at least a week or more on [https://meshcentral.com](https://meshcentral.com) without reported issues. Note that I recently updated MeshCentral.com to v0.9.52 and I expect to change "stable" to v0.9.52 in a week or so. This is a good time to do this since we are about to update the MeshAgent on all platforms with one that has better COM support on Windows and finally fixes WebRTC (so WebRTC should be always enabled in future versions).

@SomeGuru: In your case, you have always used the "latest" version on all your servers :) No need to concern yourself with "stable".
