### ISSUE TITLE
Incorrect device IP with reverse proxy after update

### ISSUE THREAD

**Issue by luckybruce** [Ylianst/MeshCentral#331]
I have a set up with meshcentral behind nginx as reverse proxy, after updated to 0.3.7-a the device ip is no longer displaying the remote ip but 127.0.0.1, i have my nginx set up in a unusual way since I also have a SSL VPN running with the same reverse proxy on 443. I have stream 443 traffic base on name into two locations, one for my VPN server, and another one through another internal port back to the revers proxy to split again for other web services including meshcentral, but I believe I had it set up correctly as it was working fine before the update and my other servers reads remote ip from nginx just fine.

**Comment by Ylianst** [comment]
Hi. I don't think I changed anything recently that would cause the IP address to not show correctly. For the IP address to show correctly, NGINX needs to add the "X-Forwarded" headers into the HTTP request to MeshCentral with the correct real source IP address. Then, you need to set "TlsOffload": "127.0.0.1" in MeshCommander since in your case, NGINX is running on the same computer. Section 16 of the user guide has the [NGINX configuration example](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.4.pdf).

It would be nice to know if the NGINX "X-Forwarded" headers are present or not when MeshCentral receives the HTTP request.

**Comment by luckybruce** [comment]
thanks for the fast response, the strange thing is my reverse proxy is not on the same machine as meshcentral. the traffic is just making a few rounds in the proxy server to be first split by tcp stream and then a more traditional reverse proxy set up, if anything it should have picked up the 127 ip from inside the proxy server loop, but it was working properly before.
anyhow, i tried to mess around a little bit, and found out that if I have Tlsoffload set to simply true, without the ip address from the reverse proxy server, then the remote ip will be captured correctly, so i guest I have I can call it a fix for now.

**Comment by Ylianst** [comment]
As soon as I saw that your reverse proxy was not on the same computer, I had the solution immediately. The best fix is to set the TlsOffload value to the internal IP address of the reverse proxy.

When a request comes to MeshCentral, anyone could just add the "X-Forwarded" header and fool MeshCentral into thinking they are at a different IP address. So, without any TLS offload "X-Forwarded" headers are normally ignored. If you set "TlsOffload" to true, the headers are used. However, if you put a IP address in "TlsOffload", the "X-Forwarded" headers are ignored except for the IP address given.

So, for best security, use the internal IP address of the reverse-proxy in "TlsOffload". Hope that made sense.

**Comment by luckybruce** [comment]
yes, I did have it set to the reverse proxy's internal ip before i made the initial post, which is in the 10.x.x.x range, and because of the convoluted reverse proxy configuration i have here, some thing must must have been lost in the chain. essentially my reverse proxy work like this.
nginx at 10.x.x.x
stream{
for web services ---> 127.0.0.1:10443
for SSL vpn ---> 10.y.y.y:443
server listen external 443
}
then
server{
listen 127.0.0.1:10443;
server_name meshcentral.example.com;
proxy_pass 10.z.z.z:443
}
i have also put the required X-Forwarded header mention in the user guide, in fact i have more than that as i choose to put those parameter together with some required by my other web services in a config file and include in each of my server instance in nginx to simplify things a bit.

**Comment by Ylianst** [comment]
Ha! I am not an expert in reverse proxies so, I am glad you figured it out and posted the solution here. Very much appreciated. I will close this issue, however, if you are doing anything interesting with MeshCentral or can give some feedback as to why you like it and want could be improved, I would certainly welcome this this, especially since you seem to have a more advanced setup.
