### ISSUE TITLE
Feature request-  WebRTC status indicator

### ISSUE THREAD

**Issue by JReally** [Ylianst/MeshCentral#3317]
I understand that WebRTC is on by default. I'm not sure that it can always be activated successfully?

If that is the case, perhaps some sort of indicator could display the current status?

If direct connection is not successful, I would want to limit traffic through the server.

**Comment by Ylianst** [comment]
So, there is a WebRTC indicator, you can see if in the picture below. However, WebRTC is not currently enabled by default because of a long standing bug in the MeshAgent that would cause data corruption. Luckily ,  

![image](https://user-images.githubusercontent.com/1319013/144677143-690d8c9e-614c-4937-aa8b-f956ce8d7657.png)

**Comment by JReally** [comment]
Look forward to the new releases.
Thanks,
  Jon

**Comment by Ylianst** [comment]
FYI. With MeshCentral v0.9.66, WebRTC to MeshAgents should work. Update the server and add `"webrtc": true` in the settings section of the config.json. That should enable it. WebRTC will only activate when network conditions allow (it's a UDP protocol).

![MC2-WebRTCWorks](https://user-images.githubusercontent.com/1319013/148847948-2498624a-c57a-4723-ae26-ff9d162f9e64.png)
