### ISSUE TITLE
Connected, n watching ghost sessions

### ISSUE THREAD

**Issue by tyler71** [Ylianst/MeshCentral#3318]
On a windows 10 device, using meshcentral v0.9.16

Over time, the Desktop connection shows `n watching`
Clicking on it shows all the sessions are mine.

![CopyQ BSXwlp](https://user-images.githubusercontent.com/4926565/144527136-e5943e5c-876b-47ef-86c5-3297da07fa3c.png)

Once it reaches 3-4 and after a few days, it will show as "Disconnected". I won't be able to connect anymore and have to reboot the device. Trying to restart the meshagent service directly doesn't work, it will say it failed to stop.

**Comment by Ylianst** [comment]
I may have fixed this in latest versions of MeshCentral. If I recall correctly, if you have an active remote desktop session and your reset the server, the agent will connect back and still show the ghost session. If that is the problem, it should be fixed in later versions, if not, that is a new issue.

Restarting the agent should reset the sessions, but if you have any way to make this happen on new versions of MeshCentral, that would be great.

**Comment by tyler71** [comment]
I have installed 0.9.56, I will see if I can recreate the issue, thank you

**Comment by Ylianst** [comment]
Thanks! Let me know.

**Comment by tyler71** [comment]
I have been unable to recreate this, so I believe it to be fixed.
Sorry for the disruption!
