### ISSUE TITLE
Redundancy

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3329]
Hello,

I find the MeshCentral software great and I think we will install it in our hospital.
We have several geographic sites with computers distributed over each of its sites.
The people (IT specialists) who will use MeshCentral will be able to connect to all the computers regardless of the site where the computer is located. The IT specialists are also present on the various sites.
We have only one samba4 / Active Directory, we want to use the same agent on all our computers and therefore use the same server which will be at the central site.
Some of our computers move from site to site.
The only problem is that in the event of a network cut between a remote site and the central site, the IT specialist who will be on the remote site will no longer be able to connect to the computers present on the same site as him.
I noticed that it is possible to have several MeshCentral servers managing the same domain but that the servers had to share the same mongoDB database.
Is it possible to create a MeshCentral server on each site with each a mogoDB database and that its mogoDB databases are replicated between them?
We also have one DNS server per site.
At the DNS level, we would use the same DNS name for all the agents to access the MeshCentral server which is on the same site.
This DNS name would be part of a zone managed by each of the dns servers. This zone would be the same on all sites Example: meshcentral.company.site.local.
For site 1: meshcentral.company.site.local -> 192.168.1.240 meshSrv1
For site 2: meshcentral.company.site.local -> 192.168.2.240 MersSrv2
For site 3: meshcentral.company.site.local -> 192.168.3.240 meshSrv3
And so on.

Is it possible to set up this architecture?

**Comment by Ylianst** [comment]
Good question. Your right that you can run multiple MeshCentral servers at the same time, but you do need a single database. Generally you run MongoDB in a cluster so that there is replication within the database cluster. I have a video on [MeshCentral Peering here.](https://www.youtube.com/watch?v=j8xIRGScju0)

I have not tested this, but if you have your 3 servers share the same `meshcentral-data` folder, they will have the same authentication certificates and so, agents will happily connect to any of the 3 servers. The problem is going to be device group and user management. If you started out with all 3 servers having a single device group and user account, yes, it would work.

The problem is that if you create a new device group, user group or user account... it would not be automatically replicated to other servers right now. If you copied the database you would also need to restart the server to update the server's state.

One trick would be to use `meshctrl.js` to manually replicate the new device groups / user group / account on the other servers... however, `meshctrl.js` does not currently let you select the identifier for these groups, something you need to replicate these correctly.

All this said, if you use a MongoDB cluster that does replication and has a change stream, it will still look like a single database and so, MeshCentral in peering mode should work.

**Comment by pascal-chag** [comment]
thanks
