### ISSUE TITLE
connect disconnect 

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3341]
![изображение](https://user-images.githubusercontent.com/95762246/145410889-07e9ab15-1b56-4148-b5b3-86b1bad5ba5d.png)

![изображение](https://user-images.githubusercontent.com/95762246/145413793-6ea1f116-8a36-41ee-8ea8-dfd9cfdee27a.png)

 constant connection and disconnection of agents .   every two minutes 

what to do ?

**Comment by Ylianst** [comment]
In `settings` section of config.json, add this line:

```
"agentpong": 90
```

This will send traffic to the agent every 90 seconds. If that does not work, change it to:

```
"agentping": 90
```

This disconnect is probably due to an HTTP proxy disconnecting if the connection is idle for more than 2 minutes. The best is to find what is causing the disconnection on the network and change the configuration. Let me know if that works.

**Comment by gosteras** [comment]
Thanks Ylianst
