### ISSUE TITLE
VNC credentials

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3346]
Hello,
Regarding agentless devices, is it possible to add a VNC tab for Linux and Window devices?
Would it be possible to register the VNC password and give the possibility to other users to connect to this computer with VNC without having to know the password?

**Comment by Ylianst** [comment]
This is certainly something I want to add. It's not trivial work, 2 to 3 days, not sure when I can slot that in. It would bring VNC to the same level as SSH and RDP and have the server remember the credentials. Because of how noVNC is built, I need to build code to intercept the VNC traffic on the server and "inject" the credentials, no a simple task.

**Comment by pascal-chag** [comment]
ok i can't wait to get this up and running. I trust you.

**Comment by si458** [comment]
closing in favor of https://github.com/Ylianst/MeshCentral/issues/2857
