### ISSUE TITLE
Mesh  Assistant 

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3352]
Hey !! I have a problem when Mesh Assistant is connected to a remote computer, the mouse buttons do not work well, they just freeze, if I swap the buttons through the menu, they work fine.

**Comment by astromediaonly** [comment]
We have similar issues - mouse buttons works weird sometimes (we cant click on taskbar or click popup windows/dialogs but other parts are clickable. I wonder what is causing it. When trying to setup it on my end for tesing it works fine but when connecting to clients Im fighting with it almost every time.

**Comment by si458** [comment]
i think this might be due to certain parts of windows have UAC enabled, so the meshAssistant cant interact with them
for example you can open AVG/Mcafee antivirus, but then suddenly cant interact with the computer until the remote person, closes that window for you

work around: install the meshagent in the background instead OR try running the meshassistant as admin
