### ISSUE TITLE
Issue with nginx.conf websocket connection

### ISSUE THREAD

**Issue by aindina056** [Ylianst/MeshCentral#3357]
Hi, 
Previously we already implement our project using meshcentral in AWS. Right now we are having an issue to connect bench/remote desktop from meshcentral using  onpremise with nginx server. 

here is our nginx.config file

```
server {
        listen       10080 ssl http2;
        server_name  _;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

        ssl_certificate ".....";
        ssl_certificate_key "......";
	ssl_session_timeout 1d;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers .......;
	ssl_session_cache shared:SSL:10m;
	


        location / {
            proxy_pass "http://backend:80" ;
            proxy_set_header Connection Keep-alive;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme; 
            proxy_buffers 4 256k;
            proxy_buffer_size 128k; 
            proxy_busy_buffers_size 256k;
        }
		location /ws {
		  proxy_set_header X-Real-IP $remote_addr;
		  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		  proxy_set_header Host $http_host;
		  proxy_set_header X-NginX-Proxy true;
		  proxy_set_header X-NginX-Proxy true;

		  proxy_pass http://backend:80;
		  proxy_redirect off;

		  proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
		}
}
```

As u can see from previous nginx, we already implement the "Connection upgrade" to let websocket handle the nginx.conf

Here is our meshcentral.config file

```
{
  "settings": {
    "mongodb": "..........",
    "mongodbcol": "remoteagents",
    "mongoDbName": ".....",
    "sessionTime": 240,
    "port": 31443,
    "redirPort": 31080,
    "allowLoginToken": true,
    "allowFraming": true,
    "cookieEncoding": "hex",
    "cookieIpCheck": false,
    "browserPong": 30,
    "agentPong": 30,
    "wscompression": false,
    "agentwscompression": false,
    "desktopMultiplex": true
  },
  "domains": {
  "httpHeaders": {
    "Strict-Transport-Security": "max-age=360000",
    "x-frame-options": "SAMEORIGIN",
    "Content-Security-Policy": "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-src 'self'; media-src 'self'"
  }
 }
}
```

From our case, seems like there is no websocket connection detect to our server/ websocket connection failed with nginx. 

I have tried multiple configs options for upgrade connection but it seems didnt works. Thanks in advance for any help or direction.

Regards, 
Nurul

**Comment by Ylianst** [comment]
Looking at the configuration, you have MeshCentral's HTTP port on 31080 and HTTPS on 31443. The NGINX configuration seems to forward port 10080 to backend port 80.

Should you not be forwarding external port 80 and 443 to 31080 and 31443? Also, use `"aliasredir":80` and `"aliasport":443` so that MeshCentral will know it's actually using port 80 and 443 (even if privately it's not).

Lastly, in the NGINX config, you are forwarding `/` and `/ws`. Not sure where that `/ws` came from, it's not a URL used by MeshCentral.

Look at page 32 of the [MeshCentral user's guide](https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf) for a sample NGINX config. I also have a [YouTube video on NGINX and MeshCentral here](https://www.youtube.com/watch?v=YSmiLyKSX2I).

Let me know if that helps.
