### ISSUE TITLE
Unknown computers on list in two computers groups

### ISSUE THREAD

**Issue by tiikej** [Ylianst/MeshCentral#3377]
Today I was found unknown computers in two groups of computers. This computers was connect from TOR network and Korean and Romanian IP. We didn't connect this computers.
I think that is a try to hack my system, but a don't know that this is posiible from this position.
How can I protect my system against such actions?

P.S. A few days ago, a customer had 4 laptops with instaled meshagent stolen.

**Comment by Ylianst** [comment]
This has been a commonly reported occurrence. It's because one or many of your remote devices have anti-virus software installed and they will download the meshagent.exe for your server to the AV company and they will start a VM that run the executable to see what it does. Your meshagent.exe has instructions embedded within the executable to connect back to your server and so, you will see it connect for a few minutes.

This is totally normal and nothing to worry about. They can't do anything to your server and for a short moment, you could have controlled their virtual machine. You will just have to delete that device when it happens. When you update MeshCentral in the future with a new version of the Agent, this may happen again.

Hope that helps,
Ylian
