### ISSUE TITLE
Website Root Certificate Expired

### ISSUE THREAD

**Issue by frakman1** [Ylianst/MeshCentral#3396]
When connecting to `https://meshcentral.com`, my browser complains that the connection is not secure due to expired root certificate. It expired in September 2021.

![image](https://user-images.githubusercontent.com/5826484/147941525-eaf3b7d6-25a3-40a9-8215-943fbd60c251.png)

![image](https://user-images.githubusercontent.com/5826484/147941449-0dc92134-051f-4753-98c0-dad1d5776746.png)

FYI, The `meshcentral.com` certificate, however, is still unexpired (but only just)

![image](https://user-images.githubusercontent.com/5826484/147941670-fdc5e009-b1ab-4b13-8c88-093c958039ce.png)

Is this something you can update on your end?

Thanks

**Comment by AntonAndreevichMoroz** [comment]
What OS do you have?  Have the latest system updates been installed?  I check with myself and see normal expiration dates.  Most likely this is due to recent changes in Letsencrypt, old systems and without up-to-date updates do not have new root certificates installed on them.
![Screenshot_20220103_173621_com android chrome](https://user-images.githubusercontent.com/51225180/147943387-6db25fe6-34a3-43ff-828a-ae52f0b5522d.jpg)
![Screenshot_20220103_173625_com android chrome](https://user-images.githubusercontent.com/51225180/147943406-27063546-80fb-4448-b4bd-f122dda6ac39.jpg)
![Screenshot_20220103_173630_com android chrome](https://user-images.githubusercontent.com/51225180/147943421-b5e3006a-6748-41bc-a13f-ee7dca1941a8.jpg)

**Comment by frakman1** [comment]
Ahh yes, the root certificate is installed on the machine I am using. 
It's an old El Capitain MacOS (latest chrome browser)
I'll take care of it on my end. 
Thank you for the insight.

**Comment by frakman1** [comment]
I was able to update the root certs of my old Mac using [this](https://apple.stackexchange.com/a/422333) method.

Now, the root certificate is valid again.

![image](https://user-images.githubusercontent.com/5826484/147948636-467065c1-549c-45a9-9fb9-4e2fbf99c720.png)


![image](https://user-images.githubusercontent.com/5826484/147948362-66bc28f9-41c4-4c3d-8362-83259214b64b.png)
