### ISSUE TITLE
WebRTC & Version 0.9.66 & video

### ISSUE THREAD

**Issue by JReally** [Ylianst/MeshCentral#3439]
WebRTC seems to be working OK
Reducing the traffic through my Pi 4 is certainly welcome.

I had hoped that direct connection would have improved the video rate tho'
Watching any video  is extremely choppy.
I have experimented with MC installations on other hardware (under Linux Mint) so the video issue is not just the Pi hardware.
I'm not sure if I have missed some optimization.

Jon

**Comment by Ylianst** [comment]
By "Video Rate", what do you mean? MeshCentral Remote desktop? Video in MeshMessenger? Is the browser running on the RPi?

**Comment by JReally** [comment]
I'm running MeshCentral desktop on a Win 10 pro (latest updates) connecting via a RPI to another Win 10 pro (MeshCentral agent).

So if I startup a video intensive app (an example would be Stellarium- an astronomy planetarium app)  and try to control it the response time is very poor.
I can see on the monitor attached to the remote that it is responding to mouse controls sent from the MeshCentral desktop but the images received are not current.

I hope that makes sense?

Jon

**Comment by Ylianst** [comment]
The MeshAgent's WebRTC stack is data only. That is, it's only capable of opening a WebRTC data channel and so, when setup, it will act as an alternative transport instead of websocket. So yes, you bypass the server and you may get better latency since your not going thru the server, however the remote desktop code is the same as before, it's tiled JPEG.

In can go in the remote desktop settings dialog and boost framerate, adjust JPEG quality and change scaling. Of course, it's not the same as RDP's system of streaming the video across the session.

![image](https://user-images.githubusercontent.com/1319013/148873445-447c39c7-05dd-4232-9145-dfbbaf26f08f.png)

So yes, apologies if the exceptions where not correct. WebRTC in the MeshAgent is only used as a WebStocket alternative.

Bryan did start work on a different way of capturing the screen using DirectX on Windows, but not sure when that will ever be released.

**Comment by JReally** [comment]
Yes I have the framerate at "fast"

Unfortunately, manipulating a remote device with significant video becomes an issue when the mouse position no longer matches the locally displayed video.

Everything else works very well

Jon

**Comment by JReally** [comment]
Yes I have the framerate at "fast"

Unfortunately, manipulating a remote device with significant video becomes an issue when the mouse position no longer matches the locally displayed video.

Everything else works very well

Using the noVNC option provides a good work around

Jon
