### ISSUE TITLE
Question on agent certificate

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshCentral#3495]
Hi,

In our environment, we have installed 100s of end points with mesh agent and it is communicating fine. This was done earlier using the self signed certificate itself.

Now we wanted to go with a certificate change. So we have .crt file and .key file, which needs to be renamed as below and placed in meshcentral-data folder, so that mesh agent as well as web servers will use the communication with latest certificate.

```
webserver-cert-public.crt
webserver-cert-private.key
agentserver-cert-public.crt
agentserver-cert-private.key
```

Now the question is, if I replace above 4 files with newly generated, it is cause agent communication to stop. Is it expected? 
Upon analysis it is found that ServerID parameter is changing when we install new agent with the updated certificate. Is there any way to make the existing agents to communicate and use the latest certificate?

Thanks in advance.

**Comment by Ylianst** [comment]
Hi. First, always backup your "meshcentral-data" folder offsite.

MeshCentral is designed so that you can change the TLS certificate and agents will still connect. The security details of how this is done is documented in [Section 8 of the Design & Architecture Guide](https://meshcentral.com/info/docs/MeshCentral2DesignArchitecture.pdf). Basically, the agent will connect to the server and use the second "agentserver" certificate to authenticate the server. For example, you can turn on Let's Encrypt support in MeshCentral and the HTTPS certificate will be updated every 40 days or so, and agent have no problem with that.

The following two files is the ones you want to change:

```
webserver-cert-public.crt
webserver-cert-private.key
```

Keep a backup of the old ones of course, but you can change these, restart the server and agents will still connect.

However, the two files are used to authenticate the server to the agents:

```
agentserver-cert-public.crt
agentserver-cert-private.key
```

Changing or loosing these two files will cause all agents to never be able to connect again. So, keep these in a safe place.

Hope that helps,
Ylian

**Comment by knkumar93** [comment]
Thanks @Ylianst , So basically the agentserveer-cert files are used only for server authentication not for TLS encryption. TLS encryption is done only with webserver-cert files and agents have no problem communicating even if webserver-cert files are changes. Is it right?

**Comment by Ylianst** [comment]
Right.
