### ISSUE TITLE
RDP settings

### ISSUE THREAD

**Issue by walterzilla** [Ylianst/MeshCentral#35]
I was wondering if there's a way to set quality value above 50% ...
thanks

(BTW keep up the good work!)

**Comment by jsastriawan** [comment]
Try to add "allowhighqualitydesktop" : true in config.json settings section.

**Comment by amenolo** [comment]
Bingo!
Now I'm able to select value up to 90%: to be honest I expected 100% as top value, anyway much better :-)

As far as you know is a full screen mode/switch planned-to-release?

**Comment by Ylianst** [comment]
I put the default limiter at 50% since anything above that does increase network traffic quite a bit. If that is not an issue than yes, removing the limit is perfect. For full screen, there is a 4 arrow button on the top right of the desktop screen to go full screen within the browser. Is that ok, you are you looking for a real full screen?

**Comment by amenolo** [comment]
I perfectly understand your choice, but in my case scenario I don't have to worry about bitrate so I'd rather choose best visual quality.

As for full screen, yes I'm looking for the "real thing": in my opinion that would be an useful GUI enhancement :-)

**Comment by Ylianst** [comment]
Not that bad idea. Just published MeshCentral v0.2.3-k. Now you can hold the shift key and hit the full screen button to get browser full screen in remote desktop.

**Comment by amenolo** [comment]
Well, scaling isn't that optimal due to fixed bottom/up command bars, but hey...now it's really such comfortable, thanks mate!

That said, looking forward to next releases ;-)
