### ISSUE TITLE
MeshRouter unable to connect to HTTPS

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#351]
MeshCentral Server : 0.3.7-p; MeshCentral Router : v.1.0.7083
(Apologies, only just getting to grips with MCR so I'm sure most of my issues are going to be related to that ... so Bryan's going to be my new best friend...) :smile: 

I have an HTTPS server on my Linux host, under VirtualBox, that's connected to Mesh Central. From a Windows host, I install MCR, log into the MC server and set up a map as follows:

- Protocol : TCP
- Local Port : 0
- Device Group : Local VMs
- Remote Device : HTTPS Server
- Application : HTTPS
- Remote Port : 443

When I select Open, my (Chrome) browser opens but ends up showing me "This site can't be reached. localhost unexpectedly closed the connection ... ERR_CONNECTION_CLOSED".  

**Note** - the HTTPS server does have a self-assigned SSL certificate which I'm suspicious of being the culprit...?

**Comment by theredkoala21** [comment]
Just tested this with v1.0.7.25 MeshCentral Router + Self Signed Cert to OutlookWebAccess (OWA)
Worked fine.

![image](https://user-images.githubusercontent.com/37466255/61178682-15290c80-a635-11e9-9c5e-11f473cdf2c2.png)

**Comment by Ylianst** [comment]
Hi. I think the problem is not with HTTPS. When your application connects to localhost:randomport, MeshCentral Router accepts the TCP connection and places it on hold as it tries to establish the relay connection. If the remote MeshAgent can't connect to the target, it will tell MeshCentral Router which is going to close the TCP connection. That is why you see the "unexpected close", MeshCentral router accepted than immediately closed the connection to your app.

So, the problem is likely that the remote agent can't connect to "127.0.0.1:443" to open the relay connection and so, the TCP connection has to be dropped. You should check that port 443 is accessible on the MeshAgent computer using 127.0.0.1.

I don't think there is a way for me to be notified that a TCP connection request is pending and not accept it until the relay connection is setup. If I could do that, I could handle this case more gracefully.

Hope it helps,
Ylian

**Comment by D4V3M0NK** [comment]
I agree - I've now tested this with another self-signed server and it works just fine - apologies, I will look into this from my end. Closing issue.
