### ISSUE TITLE
Options when launching Assistant

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3521]
Hello,
I will very soon be using the MeshCentral Assistant for several hundred computers.
I use the Assistant with automatic connection.
Would it be possible to pass parameters to the .exe file when it is launched, in order for example, to automatically send a request for assistance.
I would like the assistant to be launched by another application present on the computers. Parameters should also be sent to the assistant so that it connects and automatically makes a request for help by having filled in the details of the request in order to provide information on the context of the request for help.

**Comment by Ylianst** [comment]
Good idea. Working on it now.

**Comment by Ylianst** [comment]
Good idea. Working on it now.

**Comment by Ylianst** [comment]
Just updated MeshCentral Assistant in GitHub. You can now do this:

```
MeshCentralAssistant.exe -help:"This is a sample help request"
```

The new Assistant will be in MeshCentral v0.9.74 but you don't need to wait. You can [get it here](https://github.com/Ylianst/MeshCentral/tree/master/agents) and place it in the `node_modules/meshcentral/agents` folder and give it a try. Let me know if it works.

**Comment by DevOps-88** [comment]
I will connect to the topic :)

Does the Meshcentral Assistant application verify the way it connects to the server after it is launched? For example, trying to connect through a proxy server because it is defined in the system settings and if he fails, then he tries without a proxy server?
Because after my tests, it turns out that this is not the case and if I had a defined system proxy in the system, the application tried to connect through this proxy and the assistant did not report to me on the server.

**Comment by pascal-chag** [comment]
The help option works perfectly.
Thanks a lot.
