### ISSUE TITLE
[Question] Meshcentral Assistant with/without proxy

### ISSUE THREAD

**Issue by DevOps-88** [Ylianst/MeshCentral#3543]
Hi,

Does the Meshcentral Assistant application verify the way it connects to the server after launching it? For example, trying to connect through a proxy server because it is defined in the system settings and if he fails, then he tries without a proxy server ?

Because after my tests, it turns out that this is not the case and if I had a defined system proxy in the system, the application tried to connect through this proxy and the assistant did not report to me on the server.

Regards

**Comment by Ylianst** [comment]
Currently, MeshCentral Assistant will check if a proxy is needed for the DNS name of the server, if so, it will use it. The MeshAgent will try with and without a proxy, but MeshCentral Assistant will only try with a proxy if a proxy is setup for the server's DNS.

Ideally, you want to setup your proxy configuration to exclude internal network addresses.

Since your title is just a question, I take it your not asking for any code changes.

**Comment by Ylianst** [comment]
Updated MeshCentral Assistant to support no proxy. This will be in MeshCentral v0.9.76.

You can run `MeshCentralAssistant.exe -noproxy` or you can add this in the domain section of the config.json to disable proxy support for all downloads of MeshCentral Assistant:

```
      "assistantConfig": [
        "ignoreProxyFile=1"
      ]
```

Once released, let me know if it works.

**Comment by DevOps-88** [comment]
Thank you, it took a while, but I finally found time to test it. Of course, it all worked out as it should.
