### ISSUE TITLE
AMT device certs don't have root cert in chain

### ISSUE THREAD

**Issue by aztlanla** [Ylianst/MeshCentral#3559]
Hi, while troubleshooting another issue we noticed that the AMT device certs don't have the root cert in the certificate chain. We are using "Server-auth with TLS and non-TLS"  and Meshcentral is working fine. We are able to connect to AMT devices without issue using TLS. I downloaded the AMT device's cert and under "Certificate Path" tab it  says, "The issuer of this certificate could not be found.." The root cert says In the general tab of the AMT device issued by MeshCentralRoot-111111. The root-cert-public.cer cert does says issued to MeshCentralRoot-111111.

Thanks

**Comment by Ylianst** [comment]
The TLS specification specifically indicates that the server sends the entire chain except for the root cert. The idea being that if a browser or console thrusts the certificate, it would already have a copy of it.

You can go in your "meshcentral-data" folder and look for "root-cert-public.crt", that should be your root.

Let me know if that works.

**Comment by aztlanla** [comment]
I see, we are trying to get AMT working in HP ZCentral Connect Manager. They require we copy the MeshcCentral root cert into the Trusted  Root store on the server hosting HP ZCentral Connect Manager. I have done this (added root-cert-public.crt to the trusted root store), but I get this error when trying to get AMT to work, 

"AMT: Error The TLS certificate from AMT is not trusted by this machine. Please verify that chain of trust can be found for AMT server certificate."  

HP support is saying that whatever CA (Trusted Root) certificate is installed on the Connect Manager must be the same one that is found in the chain of the AMT device individual certificates. In this manner, the Connect Manager will know to trust connections with the AMT devices whose certificates are signed by the certificate it knows to trust.

Thanks

**Comment by Ylianst** [comment]
It should work. To make sure, check that the common name of the MeshCentral root cert is the same as the "Issuer Name" of the Intel AMT TLS certificate. It should match. The common name includes a short random hex so that all MeshCentral roots don't look alike. Otherwise, it seems like if you load the root, you should be ok.

Browsers will also check that the Intel AMT cert common name has the same DNS name at the URL of the AMT device. This will not be the case here, so if the validation includes checking the AMT TLS common name, that will not work. I am not sure if that is what ZCentral does, but hopefully not.

Best you can do is to manually verify that AMT TLS cert is really signed by that specific root you imported... but it should work.

**Comment by aztlanla** [comment]
The common name of the MeshCentral root cert does match the Issuer Name of the AMT TLS cert. Hopefully HP ZCentral Connect Manager is not checking that the Intel AMT cert common name has the same DNS name at the URL of the AMT device. I'll check with HP on that. Thanks for the help on this.

**Comment by JSuenram** [comment]
@aztlanla 
If your question is answered here please close.
Thank you!

**Comment by dinger1986** [comment]
@si458 fixed can close
