### ISSUE TITLE
Edge and Chrome report agent download as incesure although I've code-signed them

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3570]
Hi,

to overcome all these windows warnings I've purchased a Sertico code signing certificate and signed my MeshAgents. 

![image](https://user-images.githubusercontent.com/3321655/151788580-eb7dd118-4fd5-4d1b-b17b-1481073fc8a7.png)

Nevertheless I still wonder why Windows always show that type of security warning (The company name from my certificate is correct):
![image](https://user-images.githubusercontent.com/3321655/151788884-e3e2453c-0a6f-4a16-90db-a5753799c7b3.png)

This is quite common, so I think most customers will deal with it.

BUT:

Why does Chrome or Edge still show a warning when downloading the code signed file? I thought a code signe certificate solves this?

![image](https://user-images.githubusercontent.com/3321655/151789173-1e3b2ee2-5ce0-42b7-bbe3-d628ecf74146.png)

Any idea how to get rid of the browser download issue?

**Comment by PathfinderNetworks** [comment]
There is also a recent issue (just started this weekend) where Avast (and, very likely, other antivirus vendors) are now flagging the agent installer download as a virus. So you can't even download it without disabling the antivirus.  In the past you could download it (although you had to deal with the browser issues you mention above) and the antivirus might only act on the agent itself when you try to install it. But this new issue is much more aggressive and troublesome.  
I'd also do a code signing cert if I knew it would solve the issues- but I don't think it will as the code itself is still going to be flagged as a virus.

**Comment by jacotec** [comment]
Hmmm, why the hell is Antivirus software flagging an important company used tool as a virus which it definitely is not?

Isn't there a way to tell them that their analysis is wrong? What did they find in the code to suspect a virus?

**Comment by JSuenram** [comment]
You can report it to the vendors as false positive. Most of them flag it as "PUA" potential unwanted software. When detected as PUA it is up the configuration of the user if this is allowed or denied.

However, Certificate Signing from Globalsign CodeSign Certificates say that you get instant SmartScreen-Reputation.

We bought this a week ago and so war it works.... no complains... Download, RUN. No warning at all. But that might change.....

**Comment by jacotec** [comment]
That does not look good :-(

I guess Teamviewer and Anydesk have own departments fighting against this (as it's exactly the same kind of software)

**Comment by JSuenram** [comment]
> That does not look good :-(
> 
> I guess Teamviewer and Anydesk have own departments fighting against this (as it's exactly the same kind of software)

They simply pay for this......

**Comment by jacotec** [comment]
Good idea!
I've reported the file as false positive to Avast right now. Let's see if I can do this with Sophos and Kaspersky as well.

**Comment by JSuenram** [comment]
> Good idea!
> I've reported the file as false positive to Avast right now. Let's see if I can do this with Sophos and Kaspersky as well.

Most of them will answer that detection is correct and Enduser can decide if he wants to scan for PUA or not.
I guess it has to be explained further more to them and also escalated, which is not easy if you are not a paying customer at the AV-Vendor.... :-(

**Comment by jacotec** [comment]
If it does not help, it won't harm ... and if many are reporting this it will hopefully build up reputation.

**Comment by PathfinderNetworks** [comment]
Here's an update I received from Avast about the MeshAgent.exe as well as the agent installer itself.  They've change the classification to PUP (Potentially Unwanted Program) which helps slightly- but not much as my CloudCare installs are all configured to remove PUPs.  I'm still working with them on another related issue where the file/folder/process exclusions are sometimes ignored (especially in the case of the MeshCentral agent) and it deletes it even even though it has been specifically excluded. 
The reason they are giving for it being classified as a PUP is due to violation of their  'Avast Clean Guidelines'.  I've requested they provide more specifics about which aspect of the guidelines is causing it to fail.  
The Avast Clean Guidelines are here- maybe Ylian and the other developers can scan through it and see if anything stands out in regards to the agent installer and agent itself that would be failing any of this?
https://support.avast.com/en-us/article/Threat-Lab-clean-guideline/

**Comment by jacotec** [comment]
Feedback from Avast:

Thank you for reporting this false positive.

We have now cleared its reputation in our database based on the findings and removed the detection. This change may take up to 24 hours to take full effect. Please accept our apology for the inconvenience caused.

**Comment by PathfinderNetworks** [comment]
When I submitted the files to Avast they had just reclassified them as a PUP.  I asked them why and this is what they, finally, replied with today:

"Hello Parrish,

Thank you for your reply.

First, please note that PUP (potentially unwanted) detection is not virus detection. We detect such programs since it uses remote control of another PC that could be dangerous and could be used for potential harm. Same as miners, or any other app for shared access.

Should you have any other inquiries please don't hesitate to contact me again.

Ondrej

Avast Customer Care Team"

So your results are much better.  Hopefully that applies to all MeshCentral agents and installers.  Having it classified as a PUP doesn't help at all as the Avast client, at least with my configuration, treats it the same as a virus.  However, the bigger issue I'm needing them to resolve is the fact the Avast CloudCare client doesn't seem to always honor the exclusions that are in place.

**Comment by poiNt3D** [comment]
Maybe having an icon indicating that the agent is running cloud be enough to not consider it "potentially unwanted".

**Comment by JSuenram** [comment]
> Maybe having an icon indicating that the agent is running could be enough to not consider it "potentially unwanted".

It is a good idea at all to have a try-icon when remote-control-software is installed, but if that makes the PUA difference, no idea...

**Comment by jacotec** [comment]
@poiNt3D @JSuenram See #3594

**Comment by JSuenram** [comment]
Maybe we should close all "it is detected as Malware/PUA" etc etc issues and open a thread in "Discussion" about this, where the why, how and maybe prevention can be discussed...

**Comment by jacotec** [comment]
Just to complete it here in the tread, response of Kaspersky regarding their expectation to have an agent which is not tagged anymore @Ylianst @krayon007 

```
Hello,

Second solution sounds better for me. But of course it will be better to have both of them - so, remote user couldn't connect without passcode, and local user will be absolutely informed about remote connection and agree with it.
```

**Comment by JSuenram** [comment]
@jacotec 
Did your Signed file gain reputation or warnings still appear?
Please close if solved as this is not really an issue with MC itself.

**Comment by dinger1986** [comment]
@si458 can close
