### ISSUE TITLE
Add 'Send Custom Key' with an input box that displays keys or sequence pressed

### ISSUE THREAD

**Issue by wcrlewis** [Ylianst/MeshCentral#359]
An option to send whichever keys the user wanted would resolve the problems such as CTRL-W.
An input box could be used to show which keys were being pressed.  When the correct sequence is displayed, OK sends the commands to the system.
E. G.  The user selects to send a custom command.  A dialog box appears.  The user clicks in the text field and then holds CTRL, SHIFT and F3.  The dialog box displays "CTRL + SHIFT + F3" .  The OK button initiates the sequence on the target machine.

**Comment by D4V3M0NK** [comment]
I fell foul of this a few days ago when I was editing a file and Shift + End wasn't translating through to the client, so I had to type the entire line out myself. I mean, who'd think of doing such a thing?! ;o)

**Comment by Ylianst** [comment]
Oh dear. It's a good request, but it's going to be a bunch of work.

**Comment by MailYouLater** [comment]
Having a dialog box that listens to the keyboard state to enter custom keys would have the same issue that we currently do with things like <kbd>Ctrl</kbd>+<kbd>W</kbd> and <kbd>Alt</kbd>+<kbd>F4</kbd>, because the browser (in the case of <kbd>Ctrl</kbd>+<kbd>W</kbd>) or the OS (in the case of <kbd>Alt</kbd>+<kbd>F4</kbd>) interprets the input before the meshcentral webpage is even told about it.  A much more feasible approach would be to have either a dropdown input with checkmarks for modifier keys (<kbd>Ctrl</kbd>, <kbd>Alt</kbd>, <kbd>Win</kbd>, <kbd>Shift</kbd>)

**Comment by b8two** [comment]
Shift and arrow keys are not passed through also. I use this all the time to select text instead of using the mouse.

**Comment by b8two** [comment]
This customise option as explained in #2332 works for all but "Shift" key combintations.

**Comment by si458** [comment]
this feature exists now, right click the CTRL+ALT+DEL dropdown box at the bottom left side, then click customise
![image](https://github.com/Ylianst/MeshCentral/assets/765314/ff4cba08-46d7-4a81-a220-68bb38665ba2)
you can add custom keys combos, then once added and closed, youc an select it from the dropdown and click 'send'
