### ISSUE TITLE
Do we have option to use WebRTC as default and fall back as websocket. This helps to establish one-one connection between browser to end point and avoid the relay server(Meshcentral)

### ISSUE THREAD

**Issue by mdshoaibumer** [Ylianst/MeshCentral#3592]
Dear @Ylianst ,
Do we have option to use WebRTC as default and fall back as websocket. This helps to establish one-one connection between browser to end point and avoid the relay server(Meshcentral)

Regards.
Shoaib

**Comment by JSuenram** [comment]
This is already how it works.
If WebRTC is enabled in config settings section
`    "WebRTC": true,`
connection will first made with Websocket and in Background if both endpoints can reach each other it will switch on the fly to WebRTC and also keep this setting for future connections. When WebRTC fails it will fallback to Socket-Connections.

This happens transparent and without interruption so far....

**Comment by Ylianst** [comment]
100% this.

**Comment by jacotec** [comment]
It's a nice concept, however WebRTC is still buggy for me (i.e. #3551 ), so I need to wait for it to become more reliable. Also support of TURN servers would be nice ;-)

**Comment by Ylianst** [comment]
MeshCentral uses WebRTC in two ways:

- MeshMessenger has a audio/video chat feature that uses WebRTC and you can configure STUN / TURN. This is used for browser-to-browser communication. In this case, a TURN server may be required to make audio/video calls possible. You can configure it like this:

```
    "webrtcConfig": {
      "iceServers": [
        { "urls": "stun:stun.services.mozilla.com" },
        { "urls": "stun:stun.l.google.com:19302" },
        {
            "urls": "turn:my-turn-server.mycompany.com:19403",
            "username": "optional-username",
            "credentials": "auth-token"
        }
      ]
    }
```

- The MeshAgent has it's own built-in WebRTC data-only stack. This is quite wild that we built own very own, but limited, WebRTC stack that allows the agent to talk directly with the browser for remote desktop. In this case, we don't need to support TURN since the agent will start with websockets and switch over to UDP/WebRTC if possible. So, in effect, the MeshCentral websocket act as something of a TURN server.

Hope that makes sense.
