### ISSUE TITLE
MeshCentral agent detected as PUA (Potentially Unwanted Application) by Sophos

### ISSUE THREAD

**Issue by robina80** [Ylianst/MeshCentral#3607]
hi all,

i have no idea why my meshcentral agent is being detected as PUA by sophos as i have made my meshcentral server use lets encrypt

i know this is working as when i do LE in console i get this

```
{
    "configOk": true,
    "leDomains": [
        "xxxx.ddns.net"
    ],
    "challenges": {},
    "production": true,
    "webServer": true,
    "certPath": "/meshcentral/meshcentral-data/letsencrypt-certs",
    "skipChallengeVerification": true,
    "cert": "Present",
    "daysLeft": 83
}
```

also on the client/remote pc when i hand them the link it opens as https and its signed via lets encrypt

thanks,
rob

**Comment by Ylianst** [comment]
What does "PUA" stand for?

**Comment by rapi3** [comment]
PUA (Potentially Unwanted Application)
PUP (Potentially Unwanted Program)

**Comment by robina80** [comment]
sorry you beat me to it

**Comment by JSuenram** [comment]
> What does "PUA" stand for?

Earlier days AV-Scanners detected Ad-Ware or funny Shareware-Addons as PUA. But meanwhile all sort of useful Apps for Admins and even some Powershell-Scripts get detected as PUA.... Most AV-Scanners have not enabled this feature by default and only scan for Malware.... but when Admins change the detection to detect that, many Application often need Whitelisting....

**Comment by robina80** [comment]
cool thanks @JSuenram

**Comment by robina80** [comment]
do you think its the name that is being detected as a virus ie meshagent

**Comment by PathfinderNetworks** [comment]
It's nothing to do with your setup.  It's just that, especially recently, AV vendors have started flagging the MeshAgent.exe as well as the downloaded agent installer as malware.  A week or so ago they were flagging it as an outright virus.  But many of us filed false positive reports.  Most are no longer flagging them as a virus but now as a PUA (or PUP depending on what terminology the AV vendor uses).  They are doing it because it is a remote access application. 
I have exactly this same issue with Avast CloudCare (which is what I use on all of my clients).  Right now I have to disable Avast on the device just to get the agent installer to even copy to the device.  Once it's there and installed I can re-enable Avast and all is good (at least for the moment). But, give it a few months and Avast and the others will flag meshagent.exe and it's service as a virus and forcibly remove it again. 
It's become a HUGE issue.

**Comment by robina80** [comment]
is there a way to sign the agent and assistant with the lets encrypt crt and key files, maybe that will help?

**Comment by JSuenram** [comment]
I guess when the new Agent, let's call it vNext is released it might stop for while cause its mostly new code.

In the meantime... use it.... report false positive over and over and over again. Tell them this is comparable software like AnyDesk, TeamViewer etc etc.....

Maybe some day they will learn.... oh... and maybe hint them... Intel Staff itself it working and using and also developing this software.... ;-) You know, that tiny little chip company over there in US.... 🥇

**Comment by Ylianst** [comment]
First, the agent being flagged by an anti-virus software has nothing to do with the web site's TLS certificate. These are two completely different things. Making use of Let's Encrypt or not makes no difference to AV agent flagging.

You can't use a TLS certificate like Let's Encrypt to sign an executable. Certificates intended for web sites have a specific usage flag that only allows them to be used for that and not for code signing, so Windows will reject such a signature.

You can purchase a code signing certificate and use it to sign the agent. MeshCentral Assistant is already signed using my own open source code-singing certificate. Assistant is built in such a way that it always requires user consent or user initiation of the connection and so, it can't be used as malware. As a result, I sign it myself. MeshCentral Router is also one that I sign.

I can't sign the MeshAgent.exe since it can and is being used to do bad things.

**Comment by Ylianst** [comment]
We do have the next again almost ready. I am doing some testing on it today.

Who is developing the agent does not really matter since it can be used to do bad things. Since Assistant is designed to get user consent, it's much less likely to cause trouble and so, I can sign it.

**Comment by JSuenram** [comment]
Maybe we should close all "it is detected as Malware/PUA" etc etc issues and open a thread in "Discussion" about this, where the why, how and maybe prevention can be discussed...

**Comment by PathfinderNetworks** [comment]
I'm wondering if the agent installer used a more 'typical' installation process- one where it steps you through the setup process and has associated wording for what is being installed and has the 'Cancel' button available- if that would help?  I think part of the issue (apart from it being a remote access tool) is that the installation doesn't follow the typical process they are expecting to see.

**Comment by robina80** [comment]
I don't know if it's of any help but fog to get secure boot working with it you do this

https://forums.fogproject.org/topic/15888/imaging-with-fog-and-secure-boot-poc

**Comment by silversword411** [comment]
> Maybe we should close all "it is detected as Malware/PUA" etc etc issues and open a thread in "Discussion" about this, where the why, how and maybe prevention can be discussed...
> 

I'll be adding this to the faq in the new docs once I get there.

**Comment by silversword411** [comment]
IMHO GitHub should be used for just that: Issues
Bugs
Feature requests
Tracking code issues 
etc

Anything that isn't that should be commented/closed or converted to a discussion (which you can do - bottom right under flags and tags) when you have enough repo permissions.

If you want me to help with that process feel free to reach out! 🙂 This is what we do over in the Tactical RMM repo.

**Comment by JSuenram** [comment]
@robina80 
As this is at least no Issue in the Software itself please close if there are no more questions.
Or at least open a Discussion in Discussion-Area.
thank you.

**Comment by junleus** [comment]
got a Code Signing Certificate Token from Sectigo, after signing the exe,  the exe missed the  .msh info

signtool sign /du "https://mydomain.com" /d "Support Agent." /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /a
MeshService64-signed.exe

<img width="477" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/37057723/a474babe-1ad0-4934-93b3-58da7243bcb6">

**Comment by si458** [comment]
@junleus this is how i got it working
1. customise the application using `agentCustomization` inside `config.json` like so
```
 "domains": {
    "": {
      "title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "agentCustomization": {
        "companyName": "MyDomainCompany",
        "serviceName": "MyDomainServiceAgent",
        "filename": "MyDomainServiceAgent",
        "description": "MyDomainServiceAgentDescription",
        "displayName": "MyDomain Service Agent"
      }
    }
  }
```
2. restart meshcentral, this will generate the customized agents and also sign them with its 'fake' selfsigned certificate
3. copy all files from a new folder thats created in `signedagents` to your local machine
4. sign all the exes (however you want, i use EZSignIt)
5. create a new folder called `agents` and upload all the exes you have just signed to this new folder
6. restart meshcentral again
7. download the exes via meshcentral, it will have all your customizations and signed certificate

the issue is if you make any changes to your `config.json`, the agents inside `signedagents` will get re-signed and re-customized
so you must put them into a different folder and this tell meshcentral to NOT re-sign/re-customize and use these itself

this also prevents future agent updates, as you will have to do the steps again if the agent gets an update

also signing of the exes doesnt always help with antiviruses!

i have an issue where if i let meshcentral sign the exes with my certifictaes itself, norton still detects it as a virus
BUT if i do the steps above and sign them myselves, norton doesnt detect it as a virus, its very weird?

**Comment by junleus** [comment]
thank you for your reply, where should the folder "agents" I need to put? I put the both /home/meshcentral/meshcentral-data/agents and /home/meshcentral/node_modules/meshcentral/agents , till got the selft signed exe

/home/meshcentral/meshcentral-data/agents# ls -l

-rw-r--r-- 1 root root 3037504 Aug 19 05:38 MeshService64.exe
-rw-r--r-- 1 root root 3037504 Aug 19 05:34 MeshService64-signed.exe
-rw-r--r-- 1 root root 3037504 Aug 19 05:34 mydomainagent.exe


```
root@meshcentral:/home/meshcentral/meshcentral-data/agents# /usr/bin/node /home/meshcentral/node_modules/meshcentral
MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.1.0, WAN mode.
Code signed MeshService64.exe.
Code signed MeshCmd.exe.
Code signed MeshService.exe.
Code signed MeshCmd64.exe.
```

**Comment by si458** [comment]
The `agents` folder should be located inside ur data folder and not inside `node_modules`!

You should also run `node node_modules/meshcentral/` and not the command u ran from inside the `agents` folder!

**Comment by junleus** [comment]
My cert is usb token, after using Microsoft  signtool, the exe reset to default and no server url into when I run it

<img width="668" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/37057723/6145ef67-1a37-45b3-bb65-c43120776055">
