### ISSUE TITLE
high level description of how a few things work?

### ISSUE THREAD

**Issue by aktxyz** [Ylianst/MeshCentral#3609]
Is it possible to jot down a high level description of how the remote desktop and remote command shell work?

I am somewhat familiar with VNC from years ago, shipping jpeg encoded tiles that contain the screen changes ... but have no idea how the mc works.

**Comment by Ylianst** [comment]
About the same a VNC, but remote desktop is not compatible with VNC, it's our own thing. The original VNC protocol did not use JPEG, instead it uses RLE encoding or ZRLE. MeshCentral's remote desktop only uses JPEG (or WEBP in some cases) because browsers can decode JPEG easily.

The MeshAgent will split the desktop into 32x32 pixel tiles and see if any of the tiles have changed. If a group of tiles change since the last frame, a JPEG is sent to update the area.

For the remote terminal, we launch a shell on the remote system and pipe VT100 terminal emulation to/from the browser. On the browser, we use XTermJS to view the terminal session.

Let me know if that's what your looking for.

**Comment by JSuenram** [comment]
@aktxyz 
If your question is answered please close....

**Comment by aktxyz** [comment]
thanks !
