### ISSUE TITLE
Feature request : Connection Notification 

### ISSUE THREAD

**Issue by Floche87** [Ylianst/MeshCentral#361]
Dear Ylianst ,
Thanks for this great software that Meshcentral is.
It will be nice if meshcentral could send a notification to browser (MC admin page) when an agent is connecting.
I supervise 8 laptops and i never know when they will be connected. Of course, i don't have this problem with my servers.
For each computer and/or a group, i would like have possible to receive or not the notification.
I don't have several users in my meshcentral but i think each user should be possiblity to define his notifications.
Thx

**Comment by D4V3M0NK** [comment]
That's actually a pretty nice feature. I have some customers that simply don't approve of having open ended remote access to (our) virtual machines installed in their network, so I have to supply them with a local menu that permits them to toggle the services - they only turn them on when there's a support call, otherwise they're turned off. Having a notification system within MC would be pretty nice (email / curl call)

**Comment by openmoto** [comment]
I agree, this would be a great feature, if it can be applied per computer or per group.
If admin is logged in, would be great to be able to be notified when a client you're waiting for comes online.

**Comment by Ylianst** [comment]
Ok, I think I can do that.

**Comment by MailYouLater** [comment]
That sounds like a great feature, and since it looks like meshcentral already has a notification system in place which you can trigger manually by typing `notify "message"` in an agent's console, it should be doable to make it so it can automatically trigger that system when it connects, and tie that trigger to a setting.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-e with new "Notification Settings" in the "My Account" tab. Feedback appreciated.

![MC2-NotificationSettings](https://user-images.githubusercontent.com/1319013/61496160-2ee98d00-a970-11e9-9cd3-e27ba0dca100.png)

**Comment by MailYouLater** [comment]
Cool, though it would be nice to have the per computer or per group option too. Like @Floche87 said:
> For each computer and/or a group, i would like have possible to receive or not the notification.

**Comment by Floche87** [comment]
For a family purpose (like i do), it's just perfect.

In a more professional context, it would be interesting to define the connection notification for each computer or group. Maybe is it more complex to develop ?

Thanks a lot

**Comment by Ylianst** [comment]
Ha yes, I do agree that per-group would be best. I don't have per-group+account settings right now, so I could not quickly add this. But certainly interesting to add.

One things I notice on my servers is that when I restart the server, lots of agents connect at the same time and I get a storm of notifications. I was wondering that I can do to fix that. One option would be to group all the connections over a 3 second time interval into one notification.

**Comment by MailYouLater** [comment]
That would make sense.  Perhaps switch the display order of for connection notifications so instead of a notification like "**Computer-A:** Agent connected" for each computer it could be "**Agent Connected:** Computer-A", then you can expand it with the next few seconds worth of connecting agents into "**Agents Connected:** Computer-A, Computer-B, Computer-C".

**Comment by Floche87** [comment]
With only 11 machines (8 laptops), it's hard to have multi notifications in the same time ...
But i'm agree with the solution of @MailYouLater 

Maybe in the future, add the possibility to define the notification for each computer / group @

**Comment by Ylianst** [comment]
Ok! Just published MeshCentral v0.3.8-h with per-group notifications. The account notifications selection is still present, but if you select them, you get notified for all devices. Best is to disable these and enable only the groups you want.

![MC2-GroupNotifications](https://user-images.githubusercontent.com/1319013/61655643-d407ac80-ac73-11e9-8bd1-f26e5164f54c.png)

**Comment by Floche87** [comment]
I just tested with MC v0.3.8-j with per-group notifications and it's ok for me
Thx

**Comment by OutbackMatt** [comment]
Can I get the group name + the machine name in the notifications that show up on the right...?

I work with Medical Centres, and they all have a nurse room, reception and consult room 1 etc
If this could show groups as well, that would help me know which nurse computer just logged in

I'd guess that I can work around by making the computer name more verbose

**Comment by MailYouLater** [comment]
@OutbackMatt: That sounds like a reasonable request to me, but I don't know if @Ylianst will see this in a closed issue.  Please consider opening a [new issue](https://github.com/Ylianst/MeshCentral/issues/new) for this.

**Comment by OutbackMatt** [comment]
OK sorry
Done

**Comment by Ajilis** [comment]
Hi,
Its seems per-group notification is broken in 0.9.28 server.
- Global notification on connect active is OK
- If i disable this setting and put it only on a group and reboot a device no notifications.

Does someone get the same behaviour ?
