### ISSUE TITLE
[Feature] Use Meshcentral-router as  proxy(http/socks)

### ISSUE THREAD

**Issue by gaalos** [Ylianst/MeshCentral#3617]
Hi,
in some case using Meshcentral as http proxy or socks proxy might be usefull trough ssh tunnel.

**Comment by Ylianst** [comment]
Sadly, not sure what your requirement is. This is way to high level to build anything. I will close, if you want to open a new issue with much to detail, you can do that.

**Comment by gaalos** [comment]
Hi,
The goal here is to use meshcentral or the device as dynamic port mapping to use it as rebound. 

Use case  : 
My ssh connexion use the server 192.168.1.2 
I want use 192.168.1.2 as proxy server to get access on 192.168.1.3:443 or 192.168.1.4:443
On my computer meshcentral/meshrouter create listener on port 9000 like putty does 
![image](https://user-images.githubusercontent.com/32361668/153202397-9f54d259-8004-4aee-a147-ca93f81e1fcf.png)

After that i can use the 9000 port as proxy in web browser for exemple in my firefox 
![image](https://user-images.githubusercontent.com/32361668/153202537-a61fafd9-6b98-40c7-8566-0307b46ab355.png)


I'm using the ssh tunnel as proxy and forward all trafic through my SSH tunnel. 
Then i can connect to 192.168.1.4:443 on my web browser.

The goal here is to replace putty tunnel using meshcentral.

**Comment by jsastriawan** [comment]
Meshcentral tunneling protocol allows user to use a node to relay connection to any neighboring nodes. This is similar to jump host scenario.

Let say you are as PC A, you have a Mesh agent at Node B and you want to connect to Server C which does not have a Mesh Agent. You can request Meshcentral to establish a relay tunnel to Node B and the destination address is Server C. So, rather than connecting to localhost, Node B will attempt to connect to the address of Server C. 

See how I implement this in my mc2router-electron. If you want more information, please send email privately to joko dot sastriawan at gmail dot com.

**Comment by gaalos** [comment]
@jsastriawan ofc but you have to specify the host and port where you want relay.
The goal here is to provide sock5 proxy 
Working like tor for exemple

**Comment by jsastriawan** [comment]
I got it. Yeah, it looks like rather than listening to local port as normal socket listener, the router local listener must act as socksv5 proxy. Based on the destination IP and port acquired through socks proxy request, router will then attempt to create a relay to target host using the designated node. It has some neat advantages too by not necessarily specifying destination address but you still have to specify the jump node. Let see if I can prototype something by this week but I can't really promise.

**Comment by gaalos** [comment]
@jsastriawan  yes it's :) 
maybe meshcentral can do it directly without jump node . 
Meshcentral server will work like SSH tunnel node. 

Don't worry. 
I can also create simple node as proxy server, and forward 9000 to 4443 (proxy port like squid proxy)

Then i don't need to use ssh tunnel, but a simple http/https proxy forwarded inside 9000 to 4443

**Comment by Ciqsky** [comment]
Regarding this request, does MeshCentral now work? I'm trying to create a "switch" group to connect not only in SSH but also via web console. Is it possible from Meshcentral without going through an internal host to those managed by MeshCentral?
