### ISSUE TITLE
Way to force 2fa only to admins?

### ISSUE THREAD

**Issue by tiagogbarbosa** [Ylianst/MeshCentral#3623]
There is a way to force 2fa to admins? or to disable-force to one specific user?

**Comment by Ylianst** [comment]
There is not. In general, I don't think this makes much sense since hackers don't care if you are admin or not, all accounts are equity vulnerable and so, there should not be different security levels for different accounts. There is a setting to skip 2FA if coming from an IP address range if you want to remove 2FA from an internal network.

**Comment by JSuenram** [comment]
@tiagogbarbosa 
If your question is answered please close.
Thank you!

**Comment by tiagogbarbosa** [comment]
Sorry
