### ISSUE TITLE
Poor resolution when "thumbnail-connection" is already open v0.9.62

### ISSUE THREAD

**Issue by magic-missile** [Ylianst/MeshCentral#3644]
Hello,

we are experiencing the following behavior:
User1 already has a connection open to device1 (in device overview, low quality)
User2 opens up the desktop connection to device1 in full-screen.
User2 only receives the (streched) low quality video. When User1 disconnects, User2's Video quality adapts to his settings.

I couldn't find a related issue, should i maybe update or downgrade(to the stable version)?

Cheers
Christopher

**Comment by JSuenram** [comment]
Hi,
do you have Multiplexmode enabled?

**Comment by magic-missile** [comment]
Hi,
No except MongoDB, Agentport, Domainconfig and smtp-settings, i did not modify/extend my config yet.

**Comment by Ylianst** [comment]
Since the MeshAgent has a single screen capture system, it has to be shared between users if many are connected to the same desktop. One trick is to enable the desktop multiplexor, I have a [video on this topic here](https://www.youtube.com/watch?v=r0IfzuZgf3s).

Add this line in the "settings" section of the config.json:

```
"desktopMultiplex": true
```

Restart the server and try again. The server will handle multi-user remote desktop very differently. Let me know if it works.

**Comment by Ylianst** [comment]
By the way, when the desktop multiplexor is enabled, the multiplexor will select the highest resolution setting selected by all users as the one requested by to the agent. So, the thumbnail would stay low resolution until a 2nd user connects asking for a high resolution remote desktop. Then, the thumbnail would switch to high-res until the 2nd user disconnects.

**Comment by magic-missile** [comment]
Sry for the late reply. With the multiplexmode on, everything looks good.
Thanks for the explanation about how the sessions are being (re)used
