### ISSUE TITLE
New Account - Email Notification

### ISSUE THREAD

**Issue by MRCode010101** [Ylianst/MeshCentral#367]
Enhancement Request

When adding new users to MeshCentral, can we set the system to send an email to the address we provide, with a link to the MeshCentral sign-in page with the initial default password (forcing change upon initial login)?

This can also be expanded to include a Forgot/Reset Password feature

**Comment by Ylianst** [comment]
Yes, this is a good request.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.8-i with the new account invitation email feature. You may need delete the "mail-templates" folder in "meshcentral-data" since there is a new "account-invite" template. Check it out, feedback appreciated.

![MC2-NewAccountInvitation](https://user-images.githubusercontent.com/1319013/61670884-32478600-ac9a-11e9-9317-a069207a396e.png)

**Comment by MRCode010101** [comment]
Looking good! I did notice I had to go in and verify my already-existing users or they were not able to view any of the units they previously had access to. Other than that, seems to be working as expected once I configured my SMTP relay. Thanks for implementing this
