### ISSUE TITLE
MeshCentral-Router quality settings up to lossles compresson

### ISSUE THREAD

**Issue by schanir** [Ylianst/MeshCentral#3697]
Hi,

a feature request. It would be very helpful to set the quality paramters up to 100%. 100% meas lossles compresson. So far I understand uses MeshCentral  jpeg compression. Jpeg has a lossles mode.

At the moment the settings go up to 90% but it makes text an edges a little bit blurred. This is hard work for my eyes over the time.
![grafik](https://user-images.githubusercontent.com/86785137/155486168-188ff01b-a0bd-4137-b58e-abb804430a13.png)

Is this possible to include?

Many thanks so far!

**Comment by Ylianst** [comment]
Added fix for this, will be in MeshCentral v0.9.90.

![MC2-RouterImprovements](https://user-images.githubusercontent.com/1319013/155617701-5c5496d1-6200-4648-9688-a2f7d20f036c.png)

**Comment by schanir** [comment]
Hi,

on the new version 0.9.91 it is possible to go to 100% but the image quality is not really better then 90%. It is still a compression with loss. And so the image get blurred and specialy small text is very hard to read.
Please switch to lossless mode. So we have still a compression but no loss of image quality.
This would be very very helpful for my eyes... :-)

Bye

**Comment by silversword411** [comment]
It's very possible your blurring is coming from pixel scaling between remote and local resolutions. 

Because of the chrome (controls) around the mesh interface and everything is in the browser it's very difficult to try and "match" the remote resolution locally perfectly.

Screenconnect solves this by having a scaling control (50% 75%, 100%, 125% etc) that will size the local window based on the remote resolution.

I'll post a screenshot soon.

**Comment by Ylianst** [comment]
Probably need to add PNG support, I don't think JPEG does lossless.

**Comment by schanir** [comment]
Hi,

The blurring comes from the discrete cosine transform. You can clearly see the 8x8 pixel blocks. It has nothing to do with the resolution. I use the Mesh-Router and he has a 1:1 display option.

JPEG normaly can hadle lossless
https://en.wikipedia.org/wiki/Lossless_JPEG

But PNG is also a possibility.
