### ISSUE TITLE
Request: Bigger Team and Lunches

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#373]
Maybe we should crowdfund a bigger team and regular lunches for you guys?

Considering how fast this is evolving now and how close it is to replacing a full blown commercial RMM product with a few more features added, it would make good business sense for me to chuck a little cash at development to save on commercial closed source solutions in the long run.

I'm already saving $2.5k (AUD) per year by dumping teamviewer.

**Comment by Ylianst** [comment]
Oh my gosh. Thank you so much. No need for any money, but your feedback is really appreciated. I just forwarded it internally to my management. I am really glad the software is useful to you. We are putting a lot of work into it, but it's really fun and certainly enjoying the work and the community.

Out of curiosity, what would be your top 3 missing features?

**Comment by ghplw** [comment]
Ability to monitor any windows service and auto restart it on failure as well as notifications of the failures.

Being able to push scripts to individual computers or groups either on-demand or on a schedule and report the result back. These need to be run with the highest privileges possible so that no interaction is required.

Integration with ClamAV so that you can configure the AV engine, get alerts and start scans all from the console. Integration with Windows Defender would also be suitable but obivously not cross-platform.

Still needs some other refinements of course but it would be good enough to replace everything else I use.

**Comment by Ylianst** [comment]
Thanks for the feedback. I think Bryan has Windows Service control built-into the MeshAgent, so, I think the first one on monitoring services is certainly possible. Don't hesitate to open separate issues for these. For ClamAV, I think I remember Microsoft has a common API for anti-virus software... need to look into this. We are already swamped with requests, but these are good ones.

**Comment by solrac901** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus    
https://docs.microsoft.com/en-us/windows/win32/lwef/defender-ref-entry
For windows

**Comment by solrac901** [comment]
for claim AV is this what you are trying to achieve? https://blog.theodo.com/2017/11/implement-antivirus-api-10-min/

**Comment by PathfinderNetworks** [comment]
For me my 'big 3' wishlist of features would be (in addition to what solrac901 has already mentioned about Windows services and scripts):
1. The ability to monitor/report on the Windows Update status per device.  That includes not only showing what Updates are currently installed but also what Updates are currently available. As well as the ability to select the missing updates and initiate the installation of the selected update(s) on the device/group of devices. 
2. Being able to monitor the Event Viewer and other system resources (such as RAM, CPU load, HDD SMART status, etc) and create/receive alerts based on those events. Ideally also being able to automatically cause a script, run a program, or some other action to run based on the alert. 
3. Being able to automate certain common tasks like drive cleanup, defrag/optimize, etc (which is part of the script feature solrac901 mentioned). 

Like Solrac901- I've saved thousands of $$ over the years since I moved to Mesh.  I first found MeshCentral in 2014 when LogMeIn started pushing absolutely absurd price increases at each renewal.  If I had to stay with LogMeIn I would be looking at well over $4,000 per year for it.  Plus, I am MUCH more confident with being able to run my own server as opposed to having all these devices associated with some cloud service that I have no control over.  
Truly, MeshCentral is the most important tool for running my IT business. Hands down.

**Comment by Ylianst** [comment]
FYI. As requested above, published @MeshCentral v0.3.9-c that now displays antivirus status for Windows computers. You will see what product is used and if it's enabled and up-to-date.

![MC2-AntiVirus](https://user-images.githubusercontent.com/1319013/62392157-8f093300-b51b-11e9-8c42-c6097f58a873.png)

**Comment by PathfinderNetworks** [comment]
I just updated my server and the AV status monitoring does appear to be working.  All of my devices have Avast CloudCare (which uses the Avast Business engine).

**Comment by Ylianst** [comment]
What OS & OS version are you running? You can try typing the "av" command in the agent console let us know what it returns. It looks like Windows Server does not support the anti-virus API, but let us know what you see. Thanks.

![MC2-av](https://user-images.githubusercontent.com/1319013/62798980-7e653980-ba94-11e9-8b9e-056e37aa4589.png)

**Comment by treicadani** [comment]
Operating System | Microsoft Windows [Version 6.1.7601] (Win7 64bit machine)
AV output is : Command returned an exception error: Module: win-info (NOT FOUND)

Operating System | Microsoft Windows [Version 10.0.18362.239] (Win 10 64bit machine)
AV output is : Command returned an exception error: Module: win-info (NOT FOUND)

Operating System | Microsoft Windows [Version 10.0.17763.615] (Win 10 64bit machine)
Command returned an exception error: Module: win-info (NOT FOUND)

The agents are updated on all computers.
Thanks

**Comment by Ylianst** [comment]
Update to MeshCenral 0.3.9-q, it will fix the "win-info" (NOT FOUND) problem.

**Comment by treicadani** [comment]
It works now after update to 0.3.9-r (current at the time of update)
