### ISSUE TITLE
Add button for fast switching between monitors

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3730]
The ability to choose between the view of each monitor and the combined view of both monitors is pretty awesome. But what I really miss after transition from Teamviewer is the very quick switch between monitor 1 and 2.

Currently it's 3 clicks ... click on the display dropdown, choose the display, click again.

An additional button to just switch to the next single display (which will just change to the other monitor with a 2-display-setup) would be a relief when you usually work on remote machines with two displays. With this button the "all-displays-view" should be excluded (I can use the dropdown for this).

**Comment by rylangrant** [comment]
Agreed. I have a couple systems with up to 5x screens on them and not knowing which one i need it be comes cumbersome flipping through and back and forth. What might be nice, is instead of the dropdown, just a single monitor icon for "All" and then for each other screen an icon with the number in it so its single click.

This is totally a nice to have vs necessary though, your hard work is really appreciated Ylianst!

![monitors](https://user-images.githubusercontent.com/5093030/156436264-3e899081-f650-44d1-806f-d61eaeb330b1.jpg)

**Comment by jacotec** [comment]
@rylangrant Wow ... I was just asking for a switch button but that's the advanced version :-)

Nice idea and graphic!

**Comment by Ylianst** [comment]
Good idea, working on it now.

**Comment by vitko-bg** [comment]
May this be added to MeshRouter please, that will be useful there. Thanks

**Comment by Ylianst** [comment]
Just checked it in, will be in MeshCentral v0.9.95. Once published, let me know if it works.

![MC2-MultiDisplaySelector](https://user-images.githubusercontent.com/1319013/156468021-700dc161-0f55-49eb-9f39-f8ab5bedd31f.png)

**Comment by Ylianst** [comment]
Just updated MeshCentral Router too.

![MC2-RouterMultiDisplaySelector](https://user-images.githubusercontent.com/1319013/156474123-9167faa2-75f3-46d1-87ab-c5a726c19c1e.png)

**Comment by Ylianst** [comment]
MeshCentral v0.9.95 is released.

**Comment by nicrame** [comment]
Working great for me. It was good idea, it's more friendly now :)

**Comment by jacotec** [comment]
Awesome! Great work @Ylianst, I love your lightning fast implementation of good ideas ;-)
