### ISSUE TITLE
Feature Request: Secondary Agent

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#374]
Add a lightweight secondary agent to perform important duties such as:

- Emergency connection method is something goes wrong with an update on the primary agent.
- Watcher function to restart the primary agent if it stops functioning or is manually killed (this should be a configurable option)

**Comment by jsastriawan** [comment]
I think you should really consider AMT CIRA capabilities. If the agent or OS crash, you still can control it using KVM or Serial over LAN.

**Comment by krayon007** [comment]
This is actually already implemented, to do exactly what you requested. I called it a diagnosticAgent. It's in the current agent binary, we just haven't flipped the switch yet, so we could do more testing. But when turned on, it will auto start every 2 days to check the status of the agent. It can self heal the agent, because when the diagnostic agent is setup, it knows the correct configuration to talk to the server, and will use that to compare the settings of the primary agent. So for example, if the proxy settings are corrupt, etc, it can fix it.

Also, I modified the auto-update, so it will delay start the secondary agent when it attempts to self-update, so that the secondary agent will be able to see if the update was successful or not. It can stop/start/restart and reinstall the agent out-of-band if necessary.

I made it so  that it will push the logs to the server, which should show up on the event log of the primary agent, so you'll be able to see if the secondary agent needed to restart the agent, or whatever... We will probably flip the switch soon...

**Comment by Ylianst** [comment]
This is a wonderful request! Bryan has been working on this for months and it's a critical request to making MeshCentral reliable. Yes, absolutely needed.

**Comment by ghplw** [comment]
What behavior would be expected if the MeshCentral server was down for more than two days?

**Comment by Ylianst** [comment]
So, the idea of the secondary agent is that it will wake up periodically and check the health of the main agent. This should happen independently of the server being up or down. Many times the secondary agent will just check the agent's health on a computer that does not currently have any connectivity. So, everything should be ok.

**Comment by si458** [comment]
this is now possible as such,
create a new domain in your config.json, (or use a second meshcentral server)
use `agentCustomization` to customise and say something like SecondAgent
https://ylianst.github.io/MeshCentral/meshcentral/customization/#agent-branding
then install the agent as well as ur primary agent,
then if ur primary one goes off, u have a second backup!
