### ISSUE TITLE
Feature Request: User Action Log

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#375]
Log whenever a user connects to remote desktop, terminal, downloads a file etc.

This can be used to audit a users actions if illegitimate use is suspected.

**Comment by Ylianst** [comment]
Yes, this is a good request. I don't expect it to be a lot of work and I want to improve the event log at some point too.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-t with a much improved event logging. Many more operations are now in the log and the viewer is much improved with user/device links and details dialog box. Feedback appreciated.

![MC2-Events](https://user-images.githubusercontent.com/1319013/62089896-a5fc0c80-b21f-11e9-9f0c-8e4ef795bdd0.png)

**Comment by ghplw** [comment]
Very nice :)

The download/export option should allow us to easily process the data.

Can we get the download button on the User and Device logs?

Is it possible to also log disconnects and even better disconnect reason (e.g. User Initiated Disconnect or Connection Dropout)?

**Comment by Ylianst** [comment]
Good idea. I will add the download button on the two other screens tomorrow.

For disconnections, I have been thinking about it. Obviously the agent can't always given the disconnect reason since it could be unplugged at any time, so the server needs to emit the event which is more work / tricky. I would also like to log the number of bytes transferred (in / out) & session time upon closing. I will see what I can do.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-w with added event log download option on the device and user event screens.

**Comment by Ylianst** [comment]
Ok, closing this one was I have made even more improvements to the logs in the last 2 days and now each session start/stop is logged pretty well. Feel free to open new issues as needed.

**Comment by datapharmer** [comment]
@Ylianst I'm not seeing connection etc. events logged in MeshCentral.com can you confirm if that is a bug?
