### ISSUE TITLE
Reset password not working in latest MC - V9.97

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3753]
Dear Ylian,

Password reset option not working in latest Meshcentral.

While the login system asks for a password change but after entering a strong password it can't move to next page.

**Comment by Ylianst** [comment]
I just tested changing my password and it worked.

![image](https://user-images.githubusercontent.com/1319013/157718161-933fb761-80c4-44b0-bb0b-30cfad2577d2.png)

**Comment by VINISHVV** [comment]
It works on user profile, but not working in reset password window and mandatory password change requested by system based on config.js

**Comment by githubbiswb** [comment]
Confirming bug. 

A user I had just had this problem too
He fixed by doing this (that user writes code so new to do this):
"I fixed the other problem by submitting the form via JS: $('#resetpasswordpanelform').submit() so we're good to go. But there was/is an issue with the password reset screen that can be solved by running that snippet. "

**Comment by Ylianst** [comment]
Oh! Working on this now!!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.98 with a fix for this. Let me know if it works.

**Comment by VINISHVV** [comment]
Thanks, It's working fine now !!
