### ISSUE TITLE
1008610 - Block Object-Graph Navigation Language (OGNL) Expressions Initiation In Apache Struts HTTP Request.

### ISSUE THREAD

**Issue by mdshoaibumer** [Ylianst/MeshCentral#3754]
Dear @Ylianst,

We are facing remote desktop disconnection issue frequently and found out the there is a vulnerability blockage in MeshCentral Port(8443). Please find the attached logs and kindly help us in resolving this issue.
[Intrusion_Prevention_List.xlsx](https://github.com/Ylianst/MeshCentral/files/8229204/Intrusion_Prevention_List.xlsx)

**Comment by Ylianst** [comment]
There is not sufficient content to do anything. What software is doing the blockage? What version are you using? What version of MeshCentral? What is port 8443? If that the MeshCentral HTTPS port? What URL is being access that is causing this?

I will close this since there is not sufficient information. You can re-open a provide more info. Thanks.
