### ISSUE TITLE
OSX agent desktop screen issues

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#377]
1) Locked screen, always black screen.
2) Unlocked screen, some OSX systems will show the desktop, some will always show black screen. Terminal and File sessions are working fine.
3) On some OSX systems, I get partly desktop screens. The bottom parts are black and not refreshed at all. The size of the bottom black part difference every session. The remote mouse operates in the black part on the remote client.
4) Multiple monitors. Switching to other monitors is not possible.
5) Multiple desktop spaces, It is impossible to switch to other virtual desktops. https://support.apple.com/guide/mac-help/work-in-multiple-spaces-mh14112/mac
6) When the dock has been configured to Automatically hide and show the dock when mouse hovers at the dock region. This is not working within MeshCentral desktop session. The mouse pointer is shown on client screen, but OSX do not detect it to trigger the dock to show up.

**Comment by krayon007** [comment]
What version of OSX are you running, and which server version are you running?

**Comment by krayon007** [comment]
And when you say locked screen, do you mean lock screen or login screen? When I say lock screen, I mean, user is logged in but desktop is locked... Login screen, I mean when no user is logged in.

**Comment by hunter-nl** [comment]
OSX 10.14.5 & 10.14.6
MeshCentral 0.3.8-n
Locked screen with both situations. At user logged in and screensaver active. And when user is not logged in. I understand when user is not logged in, it is more difficult, but when screensaver is active (user must provide password to unlock screensaver) it will not come back to 'live' desktop.

**Comment by krayon007** [comment]
From my initial testing, it looks like this is a result of Mojave's Accessibility Security settings... Specifically, it looks like if you update the agent binary, the OS does not prompt you to update the security settings. It looks like the security settings are tied to the hash of the file binary, but it won't prompt you for new permissions if there is already a file with the same name in the database. The only way I found around this, was to delete the entry in the accessibility security panel, then re-connect KVM, such that it would prompt again, so I could re-add it. This almost seems like a bug with MacOS. 

I was talking to Ylian... I may have to do some re-tooling so that I can have an independent binary that does the KVM, so that it will not need to be updated with every agent update. I tried looking for a tool to reset the accessibility security setting, but it looks like that is not possible. I'll keep digging tho.

**Comment by hunter-nl** [comment]
I've also tested a bit with Accessibility Security settings. I do not see any differents. I keep the issues as mentioned in first post.
If you going to re-tooling, please remember the following and maybe already implement this also. For the next major release of OSX (released in september). All the applications (agents, daemons, etc) must be notarized signed by Apple. Else the application will not even install/start anymore!
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by hunter-nl** [comment]
@krayon007: With v0.4.1-h All the mentioned issues still exist. For item 6 with auto-hiding Dock. If the remote mouse pointer gets 1 pixel further down, then Dock appears. But the web ui desktop is 1 pixel less high, so it will never trigger "show dock" event.

**Comment by hunter-nl** [comment]
@krayon007 MacOS 10.15 Catalina has been released. The OSX meshcentral agent is not notarized by Apple and will not start anymore.
