### ISSUE TITLE
Windows 11 Powershell Keyboard Issue

### ISSUE THREAD

**Issue by bc24fl** [Ylianst/MeshCentral#3775]
Hey all!  I'm running version 0.9.67.  If you open up a powershell prompt in Windows 11 it does not allow you to type any alphabet keys except the enter key.  If you enable "Use Remote Keyboard Map" in settings then it works as expected.   Windows 10 however works fine.

Thanks,

**Comment by JSuenram** [comment]
Can confirm this issue also exists on Windows Server 2022

**Comment by bc24fl** [comment]
> 

Unfortunately, I don't have Server 22 to test with.

**Comment by krayon007** [comment]
Interesting... I can confirm that I see this behavior with Windows 11 but not Windows 10... I'll have to do some digging.

**Comment by ryanblenis** [comment]
> Interesting... I can confirm that I see this behavior with Windows 11 but not Windows 10... I'll have to do some digging.

Right  click and open up as an admin, that tends to cause it for me

**Comment by smartekIT** [comment]
> Interesting... I can confirm that I see this behavior with Windows 11 but not Windows 10... I'll have to do some digging.

it's exist in windows 10 if you upgrade to powershell v7.x or install windows terminal app (wt.exe)

**Comment by krayon007** [comment]
From what I've found so far, it showed that the new version of powershell on win11 (which apparently is terminal based), no longer supports Unicode key injection. I found some threads for other projects where they had the same problem and said the only solution was to do a direct key injection, which is exactly what "remote key map" does. I'm trying to find alternatives. Using powershell on the terminal tab still works as an alternative for now. You can right click on the connect button to directly launch powershell instead of a command shell.

**Comment by stavros-k** [comment]
Not sure if this is related, but setting in clipboard the following:

```text
line 1
line 2
line3
```

and pasting to powershell (other apps do not have this problem) results to:

```text
line3
line2
line1
```

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
