### ISSUE TITLE
Desktop session, scrolling behaviour

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#378]
When scrolling in a desktop session and  when you stop scrolling, then it scrolls back automatically where the mouse pointer was left. This happens in Windows and OSX agent desktop sessions (others not tested).

**Comment by lrq3000** [comment]
Same issue here, I'm using a Synaptics touchpad.

**Comment by krayon007** [comment]
Are you guys both using a synaptics touchpad? Just curious, as I'm unable to reproduce this issue on Windows or Linux when using a Logitech scroll wheel, or the touchpad on my Macbook (running windows).

**Comment by hunter-nl** [comment]
I use Touchpad on Macbook pro and Apple magic trackpad.

**Comment by lrq3000** [comment]
Additional info: I tried on both Chrome and Firefox to know if it might be related to the browser, but I get the exact same behavior. If I can help any further to debug this please let me know.

**Comment by hunter-nl** [comment]
It happens also when I use a virtual mouse in virtual Windows 10 with Edge browser.

**Comment by Ylianst** [comment]
I have not seen this before. It may be that a device on the remote system is constantly setting the mouse position (like a physical optical mouse on a shaking table).

**Comment by hunter-nl** [comment]
Remote system is a virtual computer or a OSX machine with a trackpad. No (optical) mouse connected.

**Comment by lrq3000** [comment]
I have an optical mouse connected but the table is certainly not shaking nor there is any vibration. For info I also have teamviewer and dwservice installed, the latter working very similarly to meshcentral (webclient connecting to a pre-configured host), and this issue is not happening with these, so I think there is something with the way meshcentral is catching input from TouchPad or trackpads that is producing this issue. In some games for example my simulated scroll wheel is not caught at all, meshcentral at least catch it but seems to misinterpret it.

**Comment by Ylianst** [comment]
Arg. This is going to be really difficult for us to track this issue unless we can make it happen on our systems. It would be interesting to see if this happens when teamviewer and/or dwservice are uninstalled. If some software or USB HID device is sending the mouse position constantly, it would be useful to know which one it is. Obviously, the software causing the problem is going to look like it's working perfectly since it not going to see the effect of it's own updates.

If you can run an experiment and eliminate different software / devices until the problem is solved and let is know, that would be super useful.

**Comment by hunter-nl** [comment]
No teamviewer or other remote software active (local/remote). I think it is not related to remote mouse pointer location.
When I "scroll" by moving the remote scrollbar by keyboard then it is just fine.
For example: When I remotely scroll a long list of folders in explorer in windows 10 by using a trackpad, and stop scrolling, it scrolls bak the opposite way. But not always completely the same number of folders scrolling back. It looks to me if MC agent is doing more scroll events but then with reversed value for some random time. For me it is reproducible on all my systems (local/remote), independent browser I use.

**Comment by MailYouLater** [comment]
OK, I just tested this out, and I'm not certain that what I'm seeing is exactly the same as everyone else here, but I have an Elan Clickpad, and it's doing weird things too.

Here's a summary of my findings:
- Using a real mouse scrolling usually works as expected, but when scrolling very fast it will scroll very slow, and very rarely in the opposite direction than intended.
- 2-finger scrolling in MS Edge doesn't work at all (tries to scroll the page instead of sending the input to the remote computer).
- Edge-scrolling in MS Edge usually works normally for scrolling up, but often scrolls the wrong direction, or not at all when scrolling down.
- Both edge-scrolling and 2-finger scrolling in all other browsers I tested (Firefox, Chrome, Opera) usually work normally for scrolling up, but are inconsistent when scrolling down, sometimes scrolling up (usually very fast), sometimes scrolling down, then back up, sometimes(rarely) scrolling down normally, and sometimes doing nothing.

I went to www.onemilescroll.com, scrolled to the bottom (with the <kbd>End</kbd> key), then watched the feet and inches in the top left corner increase and decrease to be sure of what was happening when I did my testing.

**Comment by MailYouLater** [comment]
I have a feeling that it's decision to scroll up or down is something about how fast/slow the scrolling occurs, as I've found that if I scroll down slowly, it scrolls up, down fast, it goes down then back up, but if I scroll down quickly, then immediately touch the touch pad again, it scrolls down, but doesn't scroll back up.  This is not really an acceptable workaround to tell people to use, but it seems to be pretty reliable for me.

**Comment by lrq3000** [comment]
Thank you guys for investing the issue and for the additional infos!

@Ylianst I tried to remove dwservice and TeamViewer, so only MeshCentral was running, and it didn't help, the issue was still there.

I tried the website advised by @MailYouLater to more precisely test:
* with Edge, the 2 fingers scroll works for me but same issue as with other browser
* trying the "scroll then touch" to scroll down without scrolling up works but unreliably: it still scrolls back up but less, so if I repeat the process, I might attain the bottom of the page but I cannot choose at what pace or where exactly I want to scroll down. It seems the "scroll up" events are mixed with the "scroll down" events for me.

**Comment by lrq3000** [comment]
* Edge scrolling has the same behavior as 2 fingers scrolling for me, whatever the browser (tested on Chrome and Edge).

**Comment by MailYouLater** [comment]
@lrq3000: Most modern touchpads by default don't stop scrolling when you do, they keep scrolling for a moment, but slower, this makes the scrolling animation a bit smoother in many cases.  This is called "intertial scrolling".  In this case, since scrolling slowly down is being interpreted as scrolling up, the inertial scrolling option's 'slowing down then stopping' behaviour causes it to go back up.  If you go in to your touchpad's properties and disable the "Inertial Scroll" option, you won't need to 'scroll then touch'.
Still not a permanent fix, to the underlying issue of slow downward touchpad scrolling being interpreted as upward scrolling, but it'll help till Ylianst and krayon007 can figure out what's actually causing the issue.

**Comment by lrq3000** [comment]
@MailYouLater: the unwanted scrolling up happens whether I scroll down slowly or quickly, but when I do it quickly and with a big amplitude, it scrolls up less, but it still scrolls up. I also disabled the "momentum"/inertial scrolling option as you suggested, and indeed I don't have to touch the touchpad afterward to stop the inertia, but it doesn't solve the problem either. It just seems like the weird scroll up happens with a somewhat constant amount of events and values, so if you try to scroll down just a bit, it will scroll up more than the scroll down, but if you do a large amplitude gesture, the amount of scroll down will end up being more than the weird scroll up. I don't know if what I say is clear enough but it's kinda hard to describe.
