### ISSUE TITLE
No monitor switching for Ubuntu agent

### ISSUE THREAD

**Issue by Maxwell175** [Ylianst/MeshCentral#3815]
When connecting to an agent installed on a Ubuntu 20.04 (KDE Neon) computer with 2 monitors, I see both displays shown together.

This is probably similar to #205, but that one is on Windows.

![Screenshot 2022-03-28 174114](https://user-images.githubusercontent.com/1660330/160493773-fd659360-dd82-4437-af98-d023eb5909ab.png)

Let me know if there is any more info that I can provide.

**Comment by getut** [comment]
We run lots of linux here and this problem is not just with mesh. We use a variety of remote control systems and all of them on linux do this. I think it is due to the way that linux actually creates a single desktop  that it virtually splits between two screens. I think the only way to get it to behave like windows is to run two different xorg configs to drive each monitor truly independently. But then you have to also grab different mouse and keyboard controls for each screen. At least that is my understanding from bringing this up for other remote control technologies.

**Comment by Maxwell175** [comment]
Neither Teamv***** nor Any**** nor NoMa***** have such an issue. in fact this is the first time I see this.

**Comment by si458** [comment]
closing as stale,
please update to latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
