### ISSUE TITLE
Issue with laptop lid closed

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#3848]
I have noticed an issue with a laptop running Microsoft Windows 8.1 Pro - 9600 (have not yet tested others)

When the screen is open and visible I can use meshcentral to control everything without problems.
When I close the lid the laptop keeps running as setup, but some applications are not usable anymore.
I think it is windows related, shutting down graphics for some programs.
Would be really useful if the agent can tell windows to activate everything as if the lid was open.

Current workaround is to attach a fake external display and that keeps everything running even with the lid closed.

image below is chrome when the lid is closed.
![image](https://user-images.githubusercontent.com/55733884/161930167-9154a91c-57fc-4626-809b-c0970a8ded3c.png)

**Comment by SomeGuru** [comment]
What is your Windows 8.1 Pro power control setting for lid actions? Because I noticed when not running full power at performance mode, that the laptop would still blank the screen locally, and that would then drop the same result on mesh. This tends to be an issue with MS oses, as I have not had the same result with Linux distros, but I also wouldn't want to run my mobile PC with the screen lighting the keyboard and acting as a trap for the heat that dissipates through the keyboard. Just curious to the power plan you have set for the monitor and blank screen and lid actions and other related settings.

SomeGuru

**Comment by Allowee** [comment]
Power plan was at balanced and now at high performance, no difference. Can't find any specific settings for when the lid is closed.
The backlight goes off when the lid is 6cm from closed, so that gives some breathing air. Could be in de intel graphics driver... From an os standpoint I can understand that no power should be wasted for a screen that is not visible.

**Comment by joecool1029** [comment]
I don't want to add a 'me too' to this bug. But I think this is a bug with older Intel graphics drivers. I have the issue on a Thinkpad X201 which is first generation Intel HD graphics (Ironlake).

I've attempted to restart graphics device through powershell but that still has the issue. Only opening the screen allows for the browsers and electron windows to draw. If I find another workaround that doesn't involve plugging in another output or physically opening the screen I'll update this issue.

**Comment by silversword411** [comment]
This happens with all other remote tools that I've used.

Yes I believe it is a low power mode of the graphics adapter that stops redraws from working.

**Comment by si458** [comment]
closing as stale,
please update to latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
