### ISSUE TITLE
Intel AMT ACM Provisioning doesn't work

### ISSUE THREAD

**Issue by cmnzn** [Ylianst/MeshCentral#3855]
Hi.

I have an issue with Intel AMT provisioning in ACM Mode. 

The case is I have my own amt certificate at meshcentral-data folder and .json with this section in "domain":

```
  "AmtAcmActivation": {
      "log": "amtactivation.log", 
      "certs": {
      	  "myvprocert": {
            "certcrt": "intelamt.crt", 
            "keyfile": "intelemadecrypt.key"
```

I write 'amtacm' at the server console but doesn't recognize any certificate, only its own certificate (*).
If I create a group with "Intel AMT only" and I run meshcmd.exe on a windows device, that message appears in the command prompt:

"No opportunity for ACM activation: No matching ACM activation certificate for "(domainname.es)".

I'll appreciate tips to progress on that. 

Thanks a lot, regards.

**Comment by Ylianst** [comment]
MeshCentral will only load the the ACM activation certificate if everything is ok. The certificate must be within the validity period, must have a ACM activation OID and the entire certificate chain must be provided. If everything works, you will see in the "AMTACM" command:

![image](https://user-images.githubusercontent.com/1319013/162586913-a2bd2e6c-b93b-4f08-8f86-9fb9c37e4f6c.png)

In newer versions of the MeshCentral, if it can't load the AMT ACM certificate, it should indicate why in the at the bottom of the "My Server" / "General" tab.

![image](https://user-images.githubusercontent.com/1319013/162586960-1e257f84-e5f7-4347-9c5a-c7f87cf144b7.png)

I am going to guess that your not providing the entire certificate chain including the root certificate in the config.json.

Let me know if that helps.

**Comment by cmnzn** [comment]
Hi, again @Ylianst.
We have managed to solve the problem that the server recognized the certificate.
![amt1](https://user-images.githubusercontent.com/102591057/164415208-7d361193-ac06-47d4-93d3-9b6bf21c0b08.JPG)

Now we have another problem and it is when proceeding to activate AMT in ACM mode by mshcmd.exe and the agent (both fail).

The same error appears:

"No opportunity for ACM activation: No matching ACM activation certificate for "(domainname.es)" on windows devices.

And this on Linux devices: 
"it is not reliable, it does not have a known issuer".
![amt2](https://user-images.githubusercontent.com/102591057/164415666-502d2200-6acb-462b-a889-580ee0c8badd.JPG)


Thanks for your time, regards.

**Comment by fernandofdez007** [comment]
Hi Ylian
The problem is still there.
The certificate seems to be properly loaded as the amtacm shows the activation certificate. The AMT PKI certificate has been generated by GoDaddy


> amtacm
--- Activation Log ---
File  : amtactivation.log
--- Activation Certificate 1 ---
Name  : intel-ema.xxxyyy.es
SHA1  : 47beabc922eae80e78783462a79f45c254fde68b
SHA256: 45140b3247eb9cc8c5b4f0d7b53091f73292089e6e5a63e2749dd3aca9198eda

This certificate was originally installed in an Intel EMA server. We can activate the same kind of PC in ACM mode with Intel EMA; so, the certificate seems to be OK.

If we remove any intermediate certificate at the config file, the certificate is not loaded

As we need to install meshcentral in a customer, we have created for testing a new (separated) lab environment with the same domain. DHCP option 15 is working in the DHCP server in this lab environment, The dns suffix provided by the DHCP server is the suffix of the certificate, the same used in the Intel EMA environment. Both labs are totally separated, there is no IP routing between them, the server name is not duplicated in the network

The name of the server is exactly the same for which the certificate was generated

But when we try to activate a device in ACM  mode, it fails, either using AMT automatic policy or doing it manually:

 .\meshcmd amtconfig --url wss://intel-ema.xxxyyy.es/apf.ashx --id 'eeAMIBKV182voxHnshF3crEm1Ko5XaBAtXjH7iof@9iIvNBc1EVLgZ0AHO5HrRHe' --serverhttpshash 183650EC4595AD82F252B6C1B041E846503EFD6C68E9E568D82CA5CA50A385AA119184A9561BFBA1752744C597F0D067
Setting up MEI...
Starting Intel AMT configuration...
Started APF tunnel...
Checking Intel AMT state...
No opportunity for ACM activation: **No matching ACM activation certificate for "xxxyyy.es**".

Device can be provisioned in CCM mode, although certificate is there. But the error "No matching ACM activation certificate for "xxxyyy.es" appears. It seems there is a problem in the server

Regards and thanks in advance

Fernando

**Comment by cmnzn** [comment]
Hi @Ylianst.

Is any news about this issue? We continue with the same problem and don't know what could be wrong.

Thanks, regards.

**Comment by aztlanla** [comment]
Under Linux, add the dns switch.
--dnssuffix domainname to your meshcmd line

**Comment by cmnzn** [comment]
Hi @aztlanla, we have tried to do it, and its works! thanks so much for your answer because we didn't find this tip in the guides
