### ISSUE TITLE
Change server URL?

### ISSUE THREAD

**Issue by tiagogbarbosa** [Ylianst/MeshCentral#3873]
Is possible to change server url without losing all agents?

Tried changing config urls but got this error
![image](https://user-images.githubusercontent.com/8936001/162966713-9e99c2a3-2cf6-45ec-9d2f-7c873c231fd4.png)

**Comment by VINISHVV** [comment]
> Is possible to change server url without losing all agents?
> 
> Tried changing config urls but got this error ![image](https://user-images.githubusercontent.com/8936001/162966713-9e99c2a3-2cf6-45ec-9d2f-7c873c231fd4.png)

Currently not possible. You need to reinstall new agent in bulk command to resolve the issues.

But such feature is required for smooth migrations

**Comment by Ylianst** [comment]
The error you see if not due to URL change. The specific error you are getting with "Agent bad web hash", you can temporary fix it by adding this line in the "settings" section of the config.json:

```
"ignoreagenthashcheck": true
```

This fix is NOT SECURE and allows man-in-the-middle attacks. Your getting this error because the agent is not seeing the expected TLS certificate. You should really correct this. I have a video on [installing MeshCentral with NGINX](https://www.youtube.com/watch?v=YSmiLyKSX2I) that covers this certificate configuration issue. I may make another video on this exact certificate topic.
