### ISSUE TITLE
MeshCommander Firmware Edition?

### ISSUE THREAD

**Issue by rgl** [Ylianst/MeshCentral#3928]
It seems https://www.meshcommander.com/meshcommander/firmware is no longer available in the latest `meshcmd` builds.

I think this is related to https://github.com/Ylianst/MeshCentral/issues/3125, where @Ylianst mentioned the storage was being deprecated, but I believe that Third Party Data Storage (3PDS) was replaced with [Web Application Hosting](https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/WordDocuments/webapplicationhosting.htm), which has 200KB of available space.

Can the firmware edition be brought back? Having MeshCommander is really convenient for small home labs.

**Comment by Ylianst** [comment]
Good question. You right that 3PDS was replaced with Web Storage which allowed a web application to be loaded into Intel AMT and replace the built-in web UI. I built MeshCommander from the ground up to be a replacement to the Intel AMT WebUI and hoped they would even make it the default built-in one (which I think would have been amazing!). Oddly, the .MSI and NPM versions of MeshCommander where intended to be an extra until Web UI gets replaced.

In any case, if you look at the current [Intel AMT Reference Guide Announcements](https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=WordDocuments%2FImportantannouncements.htm) (as of now, May 2th 2022), you see this:

> Deprecation of Web UI
> 
> Intel plans, in future platforms, to remove the option of connecting to Intel AMT via the Web UI application. Instead, customers will have the option of downloading a web application to the Intel CSME firmware and interacting with the web application via a browser. This will provide similar functionality to that of the Web UI, but will require the additional initial step mentioned. The date for removal of the Web UI has not yet been decided. (Document update: January 2021)

Since there is uncertainty as to where Intel AMT Web UI is going and I have plenty of work MeshCentral, I pulled the firmware version. Hopefully, there will be more indication in the future of what is going on with Web UI.

**Comment by crass** [comment]
The reason stated here for removing the firmware upload functionality doesn't make sense to me. Yes, things seem in flux as to the future of it. It sounds like its being deprecated, like 3PDS, to be replaced by something else. But this **hasn't happened yet**. Are there other reasons for removing it, like "it never worked well"?

Is it better to have the default web UI for AMT, which is less featureful and generally sucks, than this implementation? When ever intel gets around to figuring out what they want next, we can move to that. In the meantime, lets have an option for a much better web UI. Or am I misunderstanding something?

**Comment by rex-structorum** [comment]
@Ylianst Hey, I want to try this.  I understand you shelved the feature, but can you please fix the broken download link for the old 0.9.5 firmware installer
[download](https://www.meshcommander.com/meshcommander/firmware).

In open source, it's understood that products may be buggy or abandoned but generally expected that they continue to be available in previously released versions.

Thanks!
