### ISSUE TITLE
RemoteAPP functionality via WebRDP

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#3943]
I would like to be able to connect the RemoteApp functionality via WebRDP. Or at least manually the ability to specify a launcher instead of the Explorer shell.

**Comment by Ylianst** [comment]
I am not familiar with RemoteApp, but I can look into offering a way to specify a launcher for the RDP session.

**Comment by AntonAndreevichMoroz** [comment]
If you already have an idea about such an implementation option. I think specifying a launcher for the RDP session will suffice.

**Comment by Ylianst** [comment]
I just added the alternate shell and working directory option in the RDP connection dialog box. Since it's advanced options, you have to click a small triangle to show these.

![image](https://user-images.githubusercontent.com/1319013/167310951-081ca607-3659-4ace-8186-aa435a7cc73b.png)

I could not get an alternative shell to work with Windows 11 Pro, but the typed in strings do seem to be send to the RDP server correctly, so, if you can test this and let me know if it works that would be great.

Will be with MeshCentral v1.0.19.
