### ISSUE TITLE
0.3.8 and 0.3.9 not loading mongodb data

### ISSUE THREAD

**Issue by rroseselavy42** [Ylianst/MeshCentral#398]
Hey there,

I ran an update from 0.3.7-z to 0.3.9-c and it looks like I can't get it to read the mongodb data from db. It seems to just give me a blank server and not present any sort of error as well. 

I'm not even sure what to post here.

**Comment by rroseselavy42** [comment]
```
db version v3.6.3
git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
allocator: tcmalloc
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64

```

**Comment by Ylianst** [comment]
Your taking quite a step up. Try placing a "x" in front of "mongodb" in the config.json when running on MeshCentral v0.3.9-c. This is undocumented, but it will use the older "MongoJS" library instead of the new "MongoDB" library. Both should work, but maybe it will make a difference.

```
{
  "settings": {
    "xMongoDb": "mongodb://127.0.0.1:27017",
    "MongoDbName": "meshcentral",
...
```

Also, if you want to install an older version of MeshCentral, you can always do "npm install meshcentral@0.3.7-z". I also recommend you backup "node_modules" and "meshcentral-data" so that if you are stuck, you can just put these two folders back and start the old server again.

One more point, you can enter the MongoDB shell using "mongo", the type "show dbs", "use meshcentral", "show collections" and "exit" to quit.

```
rs1:PRIMARY> show dbs
admin        0.000GB
config       0.000GB
local        0.033GB
meshcentral  0.003GB
rs1:PRIMARY> use meshcentral
switched to db meshcentral
rs1:PRIMARY> show collections
events
meshcentral
power
serverstats
smbios
rs1:PRIMARY>
```

If you used a different database name, you may need to fix this using "MongoDbName" in config.json.

Hope this helps. If now, let me know any "mongodb" related values in your config.json (you can remove your server names). That may help.
Ylian

**Comment by Ylianst** [comment]
We cross posted. Thanks for the details. Your config.json looks good. I don't see any problems, you can try "xMongoDB" instead of "MongoDB" in the config.json and see what that does.

At this point the best would be to see whats is going on in MongoDB. What databases and collections are present that what they contain. That would be the easiest way debug.

I will take another wild guess: check if you have a "meshcentral.db" file in "meshcentral-data". If you do, it may be that you where not using MongoDB at all and using the built-in database. If that is the case, removing the "mongodb" and "mongodbcol" values from config.json will make MeshCentral go back to it's original built-in database and work again.

I also recommend not using "mongodbcol" anymore because I use many collections now. Use instead:

`"MongoDbName":"meshcentral"`

This will not fix anything, just small improvement.

**Comment by rroseselavy42** [comment]
> Your taking quite a step up. Try placing a "x" in front of "mongodb" in the config.json when running on MeshCentral v0.3.9-c. This is undocumented, but it will use the older "MongoJS" library instead of the new "MongoDB" library. Both should work, but maybe it will make a difference.
> 
> ```
> {
>   "settings": {
>     "xMongoDb": "mongodb://127.0.0.1:27017",
>     "MongoDbName": "meshcentral",
> ...
> ```
> 

That fixed it. obviously probably not a permanent fix, I am looking at other debugging steps I can take and see what

**Comment by Ylianst** [comment]
Oh good. Thanks for confirming it works. This is a bit of a guess but I imagine that you will need to keep the "x" until you update to MongoDB 4.x. No urgency to update however, I have no plans to remove the old MongoDB support anytime soon.
