### ISSUE TITLE
Add Authenticode Server Locking to MeshCentral Assistant/MeshCentral Router

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#4017]
I was wanting to know if the Assistant application will lock to the server the same way that the MeshAgen.exe's will when signed with the URI syntax you described in your youtube video [here](https://youtu.be/HZj9igSn-sY)?

**Comment by Ylianst** [comment]
No. The server locking feature is not currently implemented in MeshCentral Assistant or MeshCentral Router.

**Comment by LPJon** [comment]
Can I upgrade this question issue to a Feature Request or would you prefer I start a new issue?

**Comment by Ylianst** [comment]
ok, upgraded it.

**Comment by Ylianst** [comment]
I made progress on this. I can now read the URL of the Authenticode signature from within Assistant. I now have to write code to lock to the specified server. Will use the same URL syntax as the MeshAgent.

**Comment by Ylianst** [comment]
Published MeshCentral v1.0.25 with an updated MeshCentral Assistant that has Authenticode server locking. Same as the agent, once signed run "-info" to check that the executable is locked. Once installed, you can also edit the .msh file manually and try to run it, it will indicate an error if your trying to make it connect to the wrong server.

![MC2-AssistantServerLock](https://user-images.githubusercontent.com/1319013/169611443-0ebce6ed-8578-47ca-b31d-75d1ba46aa67.png)

I also did the same for MeshCentralRouter, but it's only going to lock the hostname, not the server certificate. I would need to look at that later since its a much more work and I am not sure locking MeshCentral Router is that useful.

**Comment by LPJon** [comment]
@Ylianst I just tested the assistant and it checks out.

However, I did go ahead and sign the MeshCentralRouter.exe and don't get any confirmation about the hostname lock with `-info`. Is there some way to verify it?

I should note that the hostname lock for the MeshCentralRouter.exe is sufficient for me. Locking it to only speak with that domain should be just fine. The security in it for me is just that a system user could not use the program to maliciously attempt attacks on other Mesh Servers. That at least protects my Code Signing Cert to a degree. But that could also be circumvented by overriding a DNS entry locally to attack any IP you specify. Still having it hard coded just makes it that much harder.

**Comment by Ylianst** [comment]
Double check you have the latest MeshCentral Assistant, you can get the latest one from [GitHub here](https://github.com/Ylianst/MeshCentral/blob/master/agents/MeshCentralAssistant.exe). Hit the "Download" button. It will be signed with my own trusted Authenticode cert. If you run it with -info, you should see this (also note the version):

![image](https://user-images.githubusercontent.com/1319013/169627322-8bbdd3e4-52d6-44e7-9554-0a1c6968128a.png)

Once you sign it with a lock, you should see something like this:

![image](https://user-images.githubusercontent.com/1319013/169627336-57b75c50-7fee-428c-bd08-89699a32670c.png)

I just create a shortcut to the executable and add `-info`. Let me know if it works.

So you are exactly right that locking MeshAgent, MeshCentral Assistant and MeshCentral Router is exactly to protect your certificate. The hostname lock is actually pretty good since unless the attacked has a trusted certificate for that domain, MeshCentral Router will show a certificate warning. So it's not bad at all.

**Comment by LPJon** [comment]
No MeshCentral Assistant is working fine. You did an excellent job with that feature and I am seeing exactly what you posted above. 

My question was about MeshCentralRouter.exe in regards to this statement `I also did the same for MeshCentralRouter, but it's only going to lock the hostname, not the server certificate. I would need to look at that later since its a much more work and I am not sure locking MeshCentral Router is that useful.` I am not seeing a way to tell if MeshCentralRouter.exe will in fact connect to other domains other than to attempt it through the interface. If it's locked to a hostname (Domain Name) shouldn't the dialog box in the app be greyed out where the user is unable to put a different domain name in?

**Comment by Ylianst** [comment]
With MeshCentral v1.0.26, you can now run `MeshCentralRouter.exe -info` and will see if it's locked or not. As for the UI, that is a good question. I could gray out the UI and set it to the locked hostname, but then you can't set the port `hostname:port` and can't set the login key is you use such a thing `hostname:port?key=secret`. So, right now it lets you enter whatever you want, but will block you after you hit ok. This is certainly not ideal, I could improve this. After starting down this path I got to thinking that locking MeshCentral Router may not be high value or even a requirement... but willing to take feedback on this.

**Comment by LPJon** [comment]
Okay, I think you could actually leave the UI alone (Not grey anything in it out). Instead a generic message when the "Ok" button is pressed saying something like `MeshCentral Router is locked to a specific server. Please use the correct domain` would be all we need. 

On a feedback note, the only reason we are really looking for this feature is to secure the Code Signing Cert. They really aren't that cheap lol. We want users to be able to download the program without having to deal with the Windows Smart Screen crap that its handing out. Locking it insures the only malicious use possible would be against our own server and that protects our Cert.

**Comment by LPJon** [comment]
And now after checking your new changes I'm satisfied with that. I really didn't want to give away the domain name it's locked to but it's really just a preference thing so. I'm gonna call this good. 

Thanks again for all the hard work. You really do work very hard at this and this is really turning out to be a really good piece of software. Keep up the hard work.
