### ISSUE TITLE
Future implementation  password protect?

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#4047]
Hi
I was wondering in the future possible to add password protect from users to uninstall the agent, as we have few users that are administrators 
Thank you

**Comment by Ylianst** [comment]
It's been addressed before, this is not possible. If a user has admin rights on a system, they can remove the agent. If you have a specific implementation idea, I would love to hear it.

**Comment by killmasta93** [comment]
thanks for the reply, i thinking something similar to antivirus solution  as when one tries to uninstall it asks for password Currently were using comodo and the user has admin rights but when he tries to uninstall the antivirus it asks for a password which was pre configured  on the admin console

**Comment by Ylianst** [comment]
Is this limited to computers that are part of windows domains?

**Comment by killmasta93** [comment]
no currently  the antivirus once installed on any computer home, pro, with domain or without domain always asks password to uninstall, if you want i can send you an installer

**Comment by Ylianst** [comment]
They probably do something very basic that can easily be bypassed since, if you are administrator you can just kill & delete the files. In general, I am going to pass on sch a request since this type of feature is most useful for people using the MeshAgent for malware and managing computers they don't own or should not be managing.

MeshCentral is open source and your free to change the code as you like, but not something I am interesting in working on.
