### ISSUE TITLE
On screen keyboard at login not movable and blocks a needed portion of the screen

### ISSUE THREAD

**Issue by Speedg33k** [Ylianst/MeshCentral#4094]
Some servers pop up an on screen keyboard at the login screen after sending ctrl alt del. 
I cannot see a way to disable or move the OSK. It covers the switch user button.
I don't get the keyboard on all of the servers I connect to, just a few. They are all the same build of server 2019.
Is there a way to force the OSK off? Is there a setting somewhere I am not seeing?

Thanks,

**Comment by JSuenram** [comment]
This happens mostly when Server 2019 believes it is running in touchmode. Why it does this, when MeshCentral Remoteconnection is established is currently unclear.

But I can at least confirm this issue on some Servers here too...

**Comment by bcredeur97** [comment]
I have this issue as well. Would really love a solution :(

**Comment by Speedg33k** [comment]
We did find a workaround, but I cannot say definitively what it was. I believe it involved disabling the touch keyboard and handwriting service. Good luck!

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above.
if issue still persists, please reply back

**Comment by lucbelliveau** [comment]
Ran into this today, running version 1.1.35 on Node 20.9.0...

**Comment by si458** [comment]
@lucbelliveau can you explain a little more about your setup?
like what remote device OS/version?

**Comment by lucbelliveau** [comment]
The OS is **Microsoft Windows Server 2019 Essentials - 17763**

It doesn't occur all the time, but today I had to login a few times in a row, switching users in between... but after the 4th or so login, when I signed out, or tried switch user, rather than being presented the normal login screen, the previous user was already selected, and a password prompt was displayed.  The OSK came up and was preventing me from switching users.

The following workaround worked for me, based on the suggestion from @Speedg33k:

  - disabled the "Touch Keyboard and Handwriting Panel Service"
  - The service was not stoppable, and I'd rather not reboot the production server at this hour, I killed it manually via a command prompt.

```
sc queryex TabletInputService
taskkill /F /PID <PID from above>
```

Immediately afterwards, I was able to switch users and not have the OSK show up.
