### ISSUE TITLE
Enhancement Request : Grouping within MC (GUI) Device Groups

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#414]
Similar to #352 it would be great to see grouping for Device Groups implemented on the MC2 server. As I roll out MC2 across all my systems, there are clearly defined groupings of those systems. If that were possible, especially with per group permissions being able to be allocated to specific user groups, then I could manage my deployments extremely easy as well as control the permissions accordingly.

For example, my deployments could easily be grouped as follows:
- Corporate
  - AWS / AZURE
    - Web servers
    - Mail servers
  - West Coast
    - Support Group
    - Sales Team
    - Development
- Customers
  -  Finance
  -  Aerospace
- Personal
  - Family
  - Friends

And with per-group permissions, I could assign one set of internal support users to Customers > Finance, but another different group of my support users to Customers > Aerospace (ie, those who have clearance to do so) as well as a completely different set of DevOps to Corporate > AWS / AZURE > Web servers

**Comment by ghplw** [comment]
I like the idea of being able to group but done such a traditional way is not very flexible and in large deployments requires a very strict structure that admins need to adhere to so that it stays standard within your organisation.

I think it would be better handled by:

1. Add a User Groups feature so we can assign permissions to groups instead of individual users.
2. Add a Global Tags and Device Group Tags feature with a Create Global Tag permission set at the server level and Create Group Tag and Assign Tags permissions set at the device group level.
3. Add a filter which allows you to select multiple tags to filter by.

This would allow you to easily work with very large deployments and with good planning allow you to sort by a near infinite number of other options. For example:

A tag for particular server model would allow you to quickly list all the servers from all your customers that might need a BIOS update.

Tagging by Country, State, City, Postcode or other appropriate tag for your area would make it very easy to see if all the devices in a particular area appear to be offline if you are trying to diagnose a suspected power or internet outage.

**Comment by dinger1986** [comment]
I think this is done with permissions set @si458

**Comment by si458** [comment]
this has indeed been completed for a long time, 
you have to add devices into groups, but also a new tag system was introduced too
