### ISSUE TITLE
Ansible integration in MeshCentral WAN mode !

### ISSUE THREAD

**Issue by siliconhippy** [Ylianst/MeshCentral#4145]
Been reading for a couple hours as I have looked into Cloud /WAN mode for managing multiple devices behind NAT in LANs: been trying Cloudflare tunnels (Wireguard VPN) with Cockpit (for Linux.) Of course  Windows RDP  could also work here.

But MeshCentral takes the cake with so many features and AIO setup- no LAN port forwarding or separate tunnel /VPN setup required for WAN remote management !

So, can WAN mode MeshCentral also integrate with Ansible (agentless configuration management tool)? Or, could MeshCentral Device Groups perform similar scripts automation to manage/update devices ?

**Comment by Ylianst** [comment]
I have never used Ansible so, not sure I can be of much help. One thing to note is that MeshCentral Router can forward any TCP connect to any device ([video here](https://www.youtube.com/watch?v=BubeVRmbCRM)) so, you may be able to plug Ansible to that.

**Comment by mobycloud** [comment]
Viet and Ylianst,

Thanks so much for quick responses 😜
I read somewhere that "the developer is passionate about the project...great community." True...also given updated videos.

The other question: Ansible, agentless configuration tool ( Puppet, Salt* need agents, which Ansible also will with reverse connection called Ansible-pull), like all tools requires an IP address to connect to clients.

So I am wondering - Ansible might connect Linux as above suggestion.
But how could Ansible gain access to MeshCentral tunnels for individual devices managed? Any MeshCentral configuration file here?

I would like to use MeshCentral as remote management tool on Cloud for Servers/ devices in LAN behind NAT. But I also need authentication and authorization plus Ansible automated management as a nice full FOSS package.

The alternative is using Cloudflare tunnels ( previously Argo tunnels.) And write custom code for Cloud DB authentication and authorization. Then Linux Cockpit for remote management, comparable to MeshCentral.

But MeshCentral seems ideal as it sets up auto tunnels, and does remote management; and seems to have plugs for SAML2.0 for remote authentication and authorization. 

Azure AD with OAuth2 can only do authentication, and of course costs big money like Cloudflare ( $7/user/month after first 20 free users !)

Any further insights are appreciated 👍

**Comment by veitw** [comment]
@mobycloud AFAIK forwarding ports in reverse **from** the agents/managed devices to the user machine has not yet been implemented beside the possibilities RoutePlus offers for this, although it is not intended to be used this way round and thus would be limited. But maybe you could use RoutePlus as a base to implement this feature in your own plug-in?

I am nor sure whether @Ylianst would like to implement and/or see this in MC directly, as I think this might exceed the purposes he intends MC to have, but I think you should create a feature request issue for this.

If you are fine with reverse connections from the managed device to the user machine to only be available while the managed device is being managed by a user, and TCP connections do suffice, you could simply use reverse port forwarding in SSH while you SSH to the remote machine through MC routing.

But maybe setting up a VPN server using Wireguard, OpenVPN or IPsec/L2TP via FreeS/WAN or Openswan as a true network-transparent solution could be a better fit to your intended use. Those are free and open source projects, too, so there is no need to pay horrendous per-user fees to VPN providers like Cloudflare.

**Comment by veitw** [comment]
One should add the following extra information:

- OpenVPN can work in TCP mode, so such a VPN would work in all situation where MC would work, too, without changes to firewalls.

- Even SSH is able to act as a VPN server via a regular TCP SSH connection, although configuration is usually more complex than using e.g. OpenVPN.

- If a VPN server and the corresponding firewalling to prevent the managed devices to speak to each other is too complex for the intended purpose, you could consider using reverse SSH, instead: Reverse SSH means that the managed device, which could reside behind firewalls preventing incoming connections, opens a pubkey authenticated SSH connection to a management server, opening one or more remote TCP forwardings on the management server. To connect to a managed device, the user connects to one of these remote forwarded ports on the management machine, and the connection is tunneled through the reverse SSH connection to the managed device. Other agent connections such as puppet can be forwarded through the reverse SSH connections using local port forwardings instead of remote port forwardings, too. Using reverse SSH is as simple as running the SSH client as a service on the managed devices, that automatically restarts in an infinite loop when SSH exits. The challenge on the client-side is to configure SSH to detect dead connections reliably and timely by setting keep-alives and timeouts, and on the server-side to configure permissions for the pubkeys to not execute any commands and only allow certain remote forwarding ports to be bound.

**Comment by siliconhippy** [comment]
Viet,

Really appreciate your details 🤠
Yes we have been looking at both reverse SSH setup, and also Zero Tier, plus Cloudflare tunnels ( Wireguard VPN) as I said above.

So let me think more about it and revert.
MeshCentral is a fantastic project...

**Comment by prononext** [comment]
Nice, I was also thinking about connecting ansible via meshctrl hopefully this can proceed. 🤠

**Comment by si458** [comment]
closing as stale, but also look into using the meshctrl as it has features like adding devices, moving groups, device info, etc...
