### ISSUE TITLE
Agent running but not connecting at boot (Ubuntu 22 Desktop)

### ISSUE THREAD

**Issue by bkgoodman** [Ylianst/MeshCentral#4179]
Brand new Ubuntu 22 Desktop bare metal install. Using public MeshCentral. When I reboot the system, it does not connect to MeshCentral. (Grey Icons, indicates "disconnected") . 

After reboot - Journalctl shows:

```
-- Boot 1132ca3eb675419a90813ca911a6b79e --
Jun 25 13:06:00 edge5200 systemd[1]: Started meshagent background service.
```
But MeshCentral shows grey icons and just says `Last seen 6/25/2022, 1:05:42 PM`

If I do then do:

`systemctl restart meshagent.service`

Icon on MeshCentral _immediately_ colorised, shows conneted, works properly.

Journalctl shows:
```
-- Boot 1132ca3eb675419a90813ca911a6b79e --
Jun 25 13:06:00 edge5200 systemd[1]: Started meshagent background service.
Jun 25 13:08:15 edge5200 systemd[1]: Stopping meshagent background service...
Jun 25 13:08:15 edge5200 systemd[1]: meshagent.service: Deactivated successfully.
Jun 25 13:08:15 edge5200 systemd[1]: Stopped meshagent background service.
Jun 25 13:08:15 edge5200 systemd[1]: Started meshagent background service.
```

(I have tried waiting for a connection - would otherwise never connect)

**To Reproduce**
1. Reboot machine
2. Try to connect to it via MeshCentral
3. 
This is 100% reproducable on every boot from my system.

**Expected behavior**
After reboot, MeshCentral should show as "connected".

**Screenshots**

**Server Software (please complete the following information):**
Public MeshCentral Server

**Remote Device (please complete the following information):**
 - Device: Dell Edge5200 Gateway
 - OS: Ubuntu Desktop 22
 - Version: Ubuntu 22.04 LTS
 - Current Core Version (if known): Jan 7 2022, 3236819516
 
This is a brand-new, fresh, stock, otherwise untouched system. Only possible deviation is that I have configured for auto-login. (But auto-login was germaine to other issue in Issue #4170 - thus I have turned it on and off a few times, and it doesn't seem to affect this problem.
  
```
> info
Current Core: Jan 7 2022, 3236819516
Agent Time: 2022-06-25 13:02:59.444-04:00.
User Rights: 0xffffffff.
Platform: linux.
Capabilities: 15.
Server URL: wss://meshcentral.com:443/agent.ashx.
OS: Ubuntu 22.04 LTS.
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, linux-dhcp, monitor-border, smbios, sysinfo, util-agentlog, wifi-scanner-windows, wifi-scanner.
Server Connection: true, State: 1.
X11 support: true.
```

**Comment by LPJon** [comment]
@bkgoodman This is most likely caused by the service being started before the network is ready on Ubuntu. You should try editing the service file located at `/lib/systemd/system/meshagent.service` with the following:

```
[Unit]
Description=LaptopPitstopAgent background service
Wants=network-online.target  <--------------
After=network-online.target  <---------------
[Service]
WorkingDirectory=/usr/local/mesh_services/Laptop Pitstop/LaptopPitstopAgent/
ExecStart=/usr/local/mesh_services/Laptop\x20Pitstop/LaptopPitstopAgent/meshagent --no-embedded="1" --meshServiceName="LaptopPitstopAgent" --installedByUser=0
StandardOutput=null
Restart=on-failure
RestartSec=3
[Install]
WantedBy=multi-user.target
Alias=LaptopPitstopAgent.service
```
then run `systemctl daemon-reload` to update the system with the new service file information and reboot then test.

Please Note that my example above is for a customized agent so you might need to adjust naming where ever you see "LaptopPitstopAgent". Adding those two lines under `[Unit]` should force the agent to wait to start until the network is up.

Hope this helps!

**Comment by bkgoodman** [comment]
Thanks! That worked! But I would still concider it a bug - i.e. doesn't this mean that:  
  
1\. The installation should add these lines in it  
(or better yet)  
2\. The agent should continue to attempt connections and work even if there is a lack of network connectivity (on statup) for any reason - whether  that be a local config issue, upstream connectivity, service outage, etc.   
  
??

**Comment by LPJon** [comment]
Well really the problem is that when the agent starts on Ubuntu it hangs because the network wasn't ready. The agent does actually actively try to reconnect to the server but because of this "hung" state it actually stops functioning. The best bet would be to add the lines during the meshagent installation and that should fix it.

@krayon007 Is it possible to add these two lines to the install on Linux systems using systemd?
```
[Unit]
Description=Mesh Agent Service
Wants=network-online.target  <--------------
After=network-online.target  <---------------
...
```

**Comment by bkgoodman** [comment]
I agree the lines should be added, but the agent should _always_ be able to retry its way out of any upstream _transient_ issues.

**Comment by LPJon** [comment]
@bkgoodman Unfortunately any services in Ubuntu can be a victim of this "hang". That's why they have these options in the Service files. That way the OS knows that that service depends on and needs other services to function (Such as the Network). We just really need to get those lines added to the service file on install.

**Comment by krayon007** [comment]
I'll modify the installer to add those lines. Thanka for pointing it out!

**Comment by Ylianst** [comment]
Re-opening as this needs to be verified.
