### ISSUE TITLE
Device Group Management

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#42]
Consider setup a drop down box that allows a person to select device groups individually to limit the number of systems displayed.  Drop box could have (All, DeviceGroup1, DeviceGroup2, etc) and only display those systems in that group. 

Alternatively, you could click on a device group to only see those systems
Alternatively you could simply expand and collapse the groups you didn't want to see with a +/- button
Alternatively you could autotag devices with the device group name then filter by tag (devicegroupname)

**Comment by jsastriawan** [comment]
There is a tagging mechanism that you can assign to a node. Let say I tag a node as troublemaker,win7,tricky_location. Filter will actually takes that into account and it will display only devices that match the filter.

I definitely would love to put "hint" on the filter box so that we can filter based on all possible tags that have been assigned however we think free form search should be sufficient.

Let me know if you have some snippet code to make this happen so that we could integrate this.

**Comment by Ylianst** [comment]
There is no drop down box right now to filter by groups. However, in the device view just start typing "group:mygroup" and only the computers in "mygroup" will show up. You can also do "g:mygroup" as a shorthand.
