### ISSUE TITLE
Recording playback doesn't work

### ISSUE THREAD

**Issue by ONBET** [Ylianst/MeshCentral#4302]
Meshcentral 1.0.43

When I playback the recording, it stuck at 00:00:01. The only way that I can playback the video is download the recording, and open player, drag & drop the recording from my PC to the meshcentral session player but the recording view will be very laggy. 

![image](https://user-images.githubusercontent.com/95070936/180359420-d09d5579-1013-4264-ac24-82fc1478c78f.png)

The format .mcrec can't be play by VLC or other major video player. Is that possible to be convert to mp4 or is it possible to replace mcrec to mp4 as main recording format?

**Comment by Ylianst** [comment]
I will have to look into this. The streaming system may not be working well and I have not tested this in a while.

For converting, if you are in Google Chrome (and no other browser) there will be a button on the upper right to save the file as a .webm movie. Currently, that is the only conversion that is supported. Once in .webm, you can convert to anything else you want.

.mcrec is just time stamped network traffic. It's super easy for the server to record since you just save the network data as it goes to the file, but it's a custom format.

**Comment by Ylianst** [comment]
By the way, if you get a chance to do this. Open the browser console and then, try to stream the recording. If you see any errors show up in the browser console, please post them here, that will help a lot. I am on the road until Wednesday, but will look at this issue when I get back.

**Comment by ONBET** [comment]
Hi @Ylianst 

Apologize for late response. I found this errors show up while I click the play button.
![image](https://user-images.githubusercontent.com/95070936/181155617-20636ab6-ab09-41fb-9f64-b1d1070cf694.png)

FYI, it is not every recordings not able to play, some of the recordings are able to play without issue. If the recording is not able to play, it also not able to WebM.

**Comment by Ylianst** [comment]
Thank you! This is exactly the right data I needed to work on this. Looking into it now.

**Comment by Ylianst** [comment]
Ok, I put in a possible fix for this. I can't make this problem happen on my computers, but ideally, I would need the .mcrec file that causes the problem. In any case, hopefully v1.0.61 will fix it.

**Comment by ONBET** [comment]
Ok thank you so much for the fix @Ylianst

**Comment by DaanSelen** [comment]
I can add to this, when using Brave browser. You need SHIELDS down!
