### ISSUE TITLE
Non-English characters in computers and users names

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#432]
In one of the latest MeshCentral versions the problem with displaying processes and services containing non-English characters in the name was fixed (Thank you, it helps a lot!).
Can the same method correct the incorrect display of computer names and user names in the interface?

![image](https://user-images.githubusercontent.com/11898568/63036858-8d018580-bec6-11e9-9dfc-23597a1cbcdc.png)

**Comment by Ylianst** [comment]
Yes, this is a very good request. Note that I am on vacation next week, so I expect MeshCentral releases to slow down.

**Comment by Ylianst** [comment]
Hi. Bryan just took a quick look at this. For non-English characters in the computer name and user names, you need Windows 8.1 or higher. It will not work on anything older. From the screen above, the machine is running Windows 6.1.7601 which is Windows 7. There is nothing we can do except to update your operating system.

You can still edit the computer name on the server side and enter a name with non-English characters.

Hope that helps,
Ylian

**Comment by MailYouLater** [comment]
Why? What is the technical reason why it won't work on Windows versions older than 8.1?
Perhaps if enough details are provided, someone in the community could find a workaround?

**Comment by krayon007** [comment]
The Win32 system call to fetch the unicode hostname does not exist on Windows versions prior to 8.1. In my case, I was using GetHostNameW. From my testing, not only are the APIs missing, the system dialogs to set/fetch the hostname did not support non-english characters. It would display incorrectly in the dialog, and the system would throw a warning saying that use of non-standard may not function correctly. I was going to try to use GetComputerNameExW, but I couldn't even get Windows to display the hostname properly in it's own system dialogs, on these older versions of windows.

I'd be happy to add support, if someone could figure out how to correctly set/fetch the hostname on these older versions of windows.

**Comment by krayon007** [comment]
Just to clarify, if I remember correctly, I think non-english user names worked fine, it was just the computer name that caused issues.

**Comment by Ilia1** [comment]
![Снимок экрана от 2019-12-03 12-00-57](https://user-images.githubusercontent.com/16576224/70027764-b0ab2180-15c4-11ea-9f6c-5359f67cfb3b.png)

On my version (0.4.4-s), user names are displayed normally. The hostname is displayed normally before the "\\" symbol in the active user name, but the hostname is not displayed correctly in the special field.

**Comment by TitovLab** [comment]
Checked on version 0.4.7-j:
Windows 10 and 8.1 - the username and computer name are displayed correctly everywhere.
Windows 7 - the username is displayed correctly (**including the name of the computer** before the slash). The computer name is not displayed correctly.
Such a case is rare here and Windows 7 is being removed from support.
Although Windows 7 itself and other programs show the computer name correctly.

**Comment by krayon007** [comment]
What version of Windows 7 are you running? On my test system, I'm running the US version, but I installed the foreign language packs... In my case, if I try to set the computer name to be chinese characters, the system dialog says that non english characters are not supported... If I force it to accept anyways, all the chinese characters are switched to "_" characters everywhere. So when I call the system call to fetch the user list, the portion before the username, does not show correctly. It shows as "_____\user"

**Comment by TitovLab** [comment]
Windows 7 32bit Russian SP1 with updates.
Allows you to set computer name in Russian, issues a warning, but after that the name is displayed without errors in the Windows dialogs.

**Comment by krayon007** [comment]
Interesting... I just tried with Russian, and got the same results on my windows... Maybe I'll create a VM with a different region's Windows, and try again... If I can get the system dialogs to work correctly, maybe I can get the computer name to show up correctly, by reading it from somewhere else.

**Comment by CCWTech** [comment]
![2020-06-28_14-24](https://user-images.githubusercontent.com/5482919/85957515-33257500-b94b-11ea-8473-07271bb0111e.png)
We are getting the characters when we remote into users computers. It's caused quite a issue as users are wondering about hacking.

**Comment by krayon007** [comment]
Are you saying you are getting Chinese characters on the privacy bar instead of a different language? What is it supposed to be displaying, so I can test?

**Comment by CCWTech** [comment]
Krayon - Not sure if by 'you' you mean me or not, but this is on the bar that is on the top that shows that the computer is being controlled by (Username of techs remoting in)

**Comment by krayon007** [comment]
> Krayon - Not sure if by 'you' you mean me or not, but this is on the bar that is on the top that shows that the computer is being controlled by (Username of techs remoting in)

What I meant, was in the image you posted, what is the bar supposed to display?

**Comment by CCWTech** [comment]
It displays the names of those who are remoted into the machine.



Please do not send a new request for help to this email, the response may be delayed. 

Need support? Please email mailto:support@ccwtech.com for a faster response.


Need a simple, effective & advanced Veterinary Clinical Management Platform? http://www.vetastic.com 
Paying too much for bad phone service? We now offer VOIP phone services.



Allen Crist, CEO

CCW Technology I.T. Services
Veterinary I.T. Specialists
Serving Small and Medium Business  since 2008

(801)410-0203 x5002


http://www.ccwtech.com

http://www.facebook.com/CCWTechnology




---- On Sun, 28 Jun 2020 22:26:58 -0600 Bryan Roe <notifications@github.com> wrote ----




Krayon - Not sure if by 'you' you mean me or not, but this is on the bar that is on the top that shows that the computer is being controlled by (Username of techs remoting in)


What I meant, was in the image you posted, what is the bar supposed to display?

**Comment by krayon007** [comment]
@CCWTech , your issue is the same as #1559 . It was because there was one change I hadn't commited to the repository yet. But it is fixed now, and will release the update soon.

**Comment by CCWTech** [comment]
Thanks!



Please do not send a new request for help to this email, the response may be delayed. 

Need support? Please email mailto:support@ccwtech.com for a faster response.


Need a simple, effective & advanced Veterinary Clinical Management Platform? http://www.vetastic.com 
Paying too much for bad phone service? We now offer VOIP phone services.



Allen Crist, CEO

CCW Technology I.T. Services
Veterinary I.T. Specialists
Serving Small and Medium Business  since 2008

(801)410-0203 x5002


http://www.ccwtech.com

http://www.facebook.com/CCWTechnology




---- On Mon, 29 Jun 2020 12:17:59 -0600 Bryan Roe <notifications@github.com> wrote ----




https://github.com/CCWTech , your issue is the same as https://github.com/Ylianst/MeshCentral/issues/1559 . It was because there was one change I hadn't commited to the repository yet. But it is fixed now, and will release the update soon.

**Comment by krayon007** [comment]
Update is live in MeshCentral_v0.5.76
