### ISSUE TITLE
Is setup.bin a onetime or multi use? - AMT already provisioned message...

### ISSUE THREAD

**Issue by nandox5** [Ylianst/MeshCentral#4368]
I made the setup.bin on meshcentral (through the group).
When i turn on the laptop or desktop with the usb plugged in i get the Automatic provision found, want to continue? I click yes

I then get AMT on this computer is already provisioned. Press any key to exit.

The two machines that i tested this on had AMT unprovisioned and not active.

Trying this method due to laptops not provisioning with ACM. I think it's nearly impossible to provision laptops in ACM without the USB. I just installed MeshCentral today and i have tested a wired desktop machine with a successful ACM activation. (have a valid vpro cert etc.. configured).

Any ideas on how i can get a bunch of laptops provisioned in ACM? I'd like to make this process as easy as possible for the help desk team. They will be switching a bunch of machines from the old intel SCS to CIRA/EMA/MESHCENTRAL.

Meshcentral is installed on Linux Ubuntu 18.04 if it makes any difference.

**Comment by Ylianst** [comment]
Your not the only one to ask. I get that question all the time. How to you activate Intel AMT into ACM easily? The big problem is that ACM is quite a powerful mode since you can take control of a computer remotely and so, it's not a mode that can and should be granted easily to anyone. You can do CCM easily, but ACM is difficult on purpose. I have a video on Intel AMT activation that covers [this exact topic here](https://www.youtube.com/watch?v=TaKsFEVaMpg).

For Intel AMT devices with a wired Ethernet port, the easiest by far is to get a trusted Intel AMT activation certificate (you need to play for this), setup a DHCP server with the network name of your cert (option 15) and then run "meshcmd amtconfig" and run the meshagent on the AMT machine. MeshCentral should detect it has a cert that is trusted by Intel AMT and that Intel AMT is on a wired network with option 15 that match your cert. It will then perform activation to ACM.

For "Is setup.bin a onetime or multi use?" - The setup.bin generated by MeshCentral is multi-use. It will set the trusted root hash of your MeshCentral activation cert and a random trusted FQDN into AMT. MeshCentral will then detect the match and activate. One SUPER ALLOYING thing however is that if AMT is already activated into CCM, it will not accept the USB key. This is annoying because if you opt to use CCM as a fallback when ACM is not available, you can't use the USB key.

Hope this helps.

**Comment by nandox5** [comment]
Thanks for the reply.

I have AMT setup with DHCP option 15. I am able to get some machines on ACM but others are not activating. the only difference is the AMT version (some have 16, others have 11 and 9) - 9 was the only one i was able to do with ACM. In a few words, i got all the requirements for ACM already set. (paid cert by comodo and all)

1. The problem i am running into is that - while i understand that if machine is already on CCM and usb provision will not work at this point. The machines that i am getting errors on are not AMT active/provisioned (no CCM or ACM), yet i still get a message that says it's already previsioned and will not let me provision.

2. I got multiple laptops with no Ethernet NIC - Is USB my only hope to get them on ACM? or is there a USB to ETHERNET adapter that you guys know will work to provision over "wired" connection.

**Comment by Ylianst** [comment]
1. If you have a valid cert and option 15 and the option 15 cert matches the name of your cert, it should work. Send screenshots of where you get the error and any context around the error. Do you use the agent or `meshcmd amtconfig` with an agentless device group?
2. USB setup.bin or manually in MEBx or *maybe* a thunderbolt dock depending on the vendor and Intel AMT version. Getting any other USB Ethernet adapter will not work since that would not be a Ethernet port that is managed by Intel AMT.

The activation limitation are not a limitation of MeshCentral, they are restrictions of Intel AMT.

**Comment by nandox5** [comment]
Okay, i have installed and reinstalled the agent multiple times that i probably broke something.. so for sake of troubleshooting, i have removed the Agent, Removed the mesh install folder, rebooted the machine, removed the agent from meshcentral dashboard and downloaded a brand new Agent installer.


**State before installing the agent:**
![image](https://user-images.githubusercontent.com/12242770/183155076-c7660c53-8d46-41bf-af50-52fcedbefc43.png)
![image](https://user-images.githubusercontent.com/12242770/183155592-8461c35e-5e09-479f-a89b-b3fdb63d6071.png)
![image](https://user-images.githubusercontent.com/12242770/183155834-6bb79cf2-f402-4acf-8f1a-c78d74e6e23e.png)
![image](https://user-images.githubusercontent.com/12242770/183156974-446dada7-71ee-42a5-9050-86129e6a1be5.png)

**After installing agent**
![image](https://user-images.githubusercontent.com/12242770/183156497-bc8086a9-18c1-41bd-acaa-4050082e9bba.png)
![image](https://user-images.githubusercontent.com/12242770/183156595-c6294dbe-8dce-44cf-aa87-38b46861d3ab.png)
![image](https://user-images.githubusercontent.com/12242770/183156669-9b20640d-cfd3-4613-b54e-d4af94ab8f85.png)
![image](https://user-images.githubusercontent.com/12242770/183156720-71a969de-3388-4310-bf77-995c2fa6158b.png)
![image](https://user-images.githubusercontent.com/12242770/183156826-3a62c00c-c1dd-4192-b8f0-a607525dc5da.png)

this is happening on 3 machines where AMT will not activate at all. (CCM or ACM) They are connected to the built in ethernet.

Server Console
![image](https://user-images.githubusercontent.com/12242770/183157238-8e719fff-8657-4c1c-86af-dbaeb682297b.png)

**Comment by nandox5** [comment]
Oh, a special note. This machine was provisioned through a different server before with CCM. So i did the ACUconfig unConfigure to remove provisioning. I also tried sending the Unprovision command from the server that provisioned it but that one didn't seem to work.

**Comment by Ylianst** [comment]
Nice. You seem to know what you are doing. Here is a big trick. If using an agent, go in the agent console and type "amtconfig" like this:

![image](https://user-images.githubusercontent.com/1319013/183220416-dbdf8697-540e-4e84-be70-66143404d80c.png)

It should show you exactly that is doing on.

**Comment by nandox5** [comment]
So.. it worked on 1 out of the 2 affected test machines.. opening the LMS tunnel i was able to kick start the CCM deactivation and ACM activated after a minute of waiting. nice!

However, on the second machine.. i get this error
![image](https://user-images.githubusercontent.com/12242770/183274131-c24d57bf-4271-4915-8db7-61807915b36a.png)

**Comment by Ylianst** [comment]
Nice. On the second system you are getting error 4 for for call AddNextCertInChain(), [you can see documentation here](https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/HTMLDocuments/WS-Management_Class_Reference/IPS_HostBasedSetupService.htm#AddNextCertInChain). The error is "CERT_VERIFY_FAILED".

Something went wrong when Intel AMT verified the certificate. What version of AMT is the second system?

**Comment by nandox5** [comment]
tested this on two identical machines now and both failed with same error
version is v16.0.15

**Comment by Ylianst** [comment]
Ha, sadly, I own Intel AMT v7, v8, v9, v10, v11, v12, v14, v15. I don't have a v16 to test with. I know in v16 they changed some of the certificate formats to support ECC and I added support for this in MeshCommander and it should not affect this flow, however, I have not tested a full ACM activation with v16.

One thing that is odd. For Intel AMT 14 and above, Host-based TLS ACM activation should be used by default, but you seem to have activated using the legacy system.

In the "domains" section of the config.json, do you use the "TlsAcmActivation" key? It should be true by default.

```
{
  "settings": { },
  "domains": {
    "": {
      "AmtManager": {
        "TlsAcmActivation": true
      }
    }
  }
}
```

**Comment by nandox5** [comment]
I added the to the config, it was not there, how can you tell which method (legacy or HostBased) was used?

**Comment by nandox5** [comment]
![image](https://user-images.githubusercontent.com/12242770/183991488-27f7d9e0-9db8-4237-bb35-864b26c316f1.png)

Ran into this new error message on a brand new laptop with v16. This time i tried the setup.bin method.

**Comment by Ylianst** [comment]
Try `"TlsAcmActivation": false` to see if the other activation technique works... however, it seems something else is going on such as incorrect activation certificates or option 15 FQDN is not matching. Because of security, Intel AMT will not indicate exactly what the problem is and so, I have spent some time trying to find and detect all the edge cases.

**Comment by nandox5** [comment]
`"tlsAcmActivation": false` fixed the error 408 error on laptop with v15. It's now on ACM. (done with setup.bin)
![image](https://user-images.githubusercontent.com/12242770/184015592-e22ddc53-617e-408f-99cf-5a9b8c4cd7de.png)


new laptop that is on v16 still did not work, giving me the same error as before/ ERR4
![image](https://user-images.githubusercontent.com/12242770/184015739-94548e45-2fc8-4f66-bb49-16af64265969.png)

**Comment by nandox5** [comment]
Another thing i found out that may not be related or cause any problems, but worth nothing to check.. in server console if i get the certs, I see the amt cert shows `domain.com` even though cert is `ema.domain.com` Is there anything i can do to help you debug this issue? I have a few v16 machines here that i can play with.

**Comment by Ylianst** [comment]
I just put in a request to get a Intel AMT v15 and v16 machines. So far I have Intel AMT v7,8,9,10,11,12,14 as part of my regular testing for MeshCentral, MeshCommander, MeshCMD. I need to fill in that gap.

The domain showing as "domain.com" could be a problem. Intel AMT needs to match the certificate domain with the trusted FQDN or DHCO Option 15. If you are ok with it, send me the public portion of your Intel AMT activation certificate, my [contact information is here](https://www.meshcommander.com/contact-information). Also, screen shot of where you see the "domain.com" could be great. I will take a look at the certificate parsing code to see what is going on.

So far, I only have 2 to 3 Intel AMT activation certs to test with, maybe you got yours from a different CA and so, I get a new test case.

**Comment by silversword411** [comment]
> request to get a Intel AMT v15 and v16 machines

If you get any extras, feel free to send 'em this way! :)

**Comment by nandox5** [comment]
> I just put in a request to get a Intel AMT v15 and v16 machines. So far I have Intel AMT v7,8,9,10,11,12,14 as part of my regular testing for MeshCentral, MeshCommander, MeshCMD. I need to fill in that gap.
> 
> The domain showing as "domain.com" could be a problem. Intel AMT needs to match the certificate domain with the trusted FQDN or DHCP Option 15. If you are ok with it, send me the public portion (not private key) of your Intel AMT activation certificate, my [contact information is here](https://www.meshcommander.com/contact-information). Also, screen shot of where you see the "domain.com" could be great. I will take a look at the certificate parsing code to see what is going on.
> 
> So far, I only have 2 to 3 Intel AMT activation certs to test with, maybe you got yours from a different CA and so, I get a new test case.

Email sent encrypted through microsoft 365. Let me know if you don't receive it.

thanks again
