### ISSUE TITLE
Mesh agent cannot automatically connect after restarting the OS which agent belongs

### ISSUE THREAD

**Issue by billydu1980** [Ylianst/MeshCentral#437]
Dear Ylianst

After restarting the operating system to which agent belongs, check that the agent service has been automatically restarted, but the agent disconnect status is still displayed on the meshcentral UI. 
For the linux agent system, we need to manually restart the meshagent. For windows agent system, you need to manually restart meshcentral server software.
release : 3.9-y

Best regards,
Billy

**Comment by krayon007** [comment]
Which Linux distro and version are you using? The agent should never require manual restarting.

**Comment by billydu1980** [comment]
Yes, agent services automatically restart, but the meshCentral UI interface does not automatically update the connection status. 
agent Host OS: CentOS Linux 7.6 and Window Server 2012 R2
MeshCentral Host OS: CentOS Linux 7.6

**Comment by MailYouLater** [comment]
I also have this issue on Windows 10.
If I restart the computer with the agent installed on it, the service seems to be started with the computer, but the agent doesn't appear to be connected to the server, so I run `net stop "mesh agent" & net start "mesh agent"` and then it connects normally and runs fine until the computer is restarted again.  I hadn't submitted a bug report yet because I thought I'd try to gather some diagnostic data first, but I'm not sure how to get that diagnostic data, and I haven't had the time to try digging into it yet.

**Comment by krayon007** [comment]
Is the server running in local mode, hybrid mode, etc?

**Comment by MailYouLater** [comment]
For me the server has been in LAN mode for most of my tests, and I think once it was in LAN+WAN mode, but I don't remember for certain if I tested this particular issue when I briefly had it set up that way.

**Comment by tahanjokunimi** [comment]
Here also;
- running the  master  meshcentral service on  Windows 2019 server.
- agents are on Linux servers. (Ubuntu mate 16.04)
     when I reboot the linux machines,   agents do not start automatically.
     How to setup the automatic start to agents, after linux boots up?

**Comment by tahanjokunimi** [comment]
Should this file "/etc/init/meshagent.conf"       be  generated  automatically?   when adding agent?
Or should I manually  make that  file?
---------------------------------------------------------------------
- Because seems,  that  there is no such file been generated.
- If I add the agents with that  Linux command,  it adds  the agents somewhat okay, starts it
     and newly added agents are visible at the MeshCentral webpage.  Shows up fastly.
- but then if I reboot some of the Linux agent machines,  after reboot,  can not get agent show up,
     eventought starting it with the command;  "sudo systemctl start meshagent".
- only   deleting the old  agent  from the webgui,   and adding the linux machine again,
    makes it work again.

![meshagent2](https://user-images.githubusercontent.com/28250130/63998994-1e016f00-cb0b-11e9-9b91-b981452e3410.JPG)

![meshagent](https://user-images.githubusercontent.com/28250130/63999006-248fe680-cb0b-11e9-9b99-597db10bcd28.JPG)

**Comment by krayon007** [comment]
Looks like your system is systemd, not upstart, so can you show me your:
/lib/systemd/system/meshagent.service
(it might be in /usr/lib/systemd/system/meshagent.service)

**Comment by krayon007** [comment]
Actually, nevermind, the screenshot you sent shows that it is enabled, so the .service file is probably correct. If I had to venture a guess, I think the .msh file was missing in the installation, so when the service started, it had no idea where to connect. Do you see a meshagent.msh file in the installation folder?

**Comment by tahanjokunimi** [comment]
Yes,  the  file  meshagent.msh   is been  "fetched from the Master server",  when agent is installed.

root@CS02:~# cd /usr/local/mesh/
root@CS02:/usr/local/mesh# ll
total 2948
drwxr-xr-x  2 root root    4096 maali  2  2019 ./
drwxr-xr-x 13 root root    4096 kesä  14 17:23 ../
-rwxr-xr-x  1 root root 2762304 maali  2  2019 meshagent*
-rw-r--r--  1 root root  241552 maali  2  2019 meshagent.db
-rw-r--r--  1 root root     286 helmi 27  2019 meshagent.msh
root@CS02:/usr/local/mesh#

**Comment by billydu1980** [comment]
Update the test progress:

In LAN mode，running MeshCentral Service  on CentOS Linux 7.5. After restart the MeshCentral service,   all of the agent can not visible in the MeshCentral webpage.

Look forward to your feedback.
Thanks.

**Comment by Ylianst** [comment]
Hi. Since you are in LAN mode, can you go in the computer with the MeshAgent and edit the meshagent.msh with a text editor. Does the line "MeshServer" look like this:

`MeshServer=wss://servername:443/agent.ashx`

or line this:

`MeshServer=local`

If you find the first line, check the the URL is correct. Replace "wss://" with "https://" and browse to that location and make sure the server is present and can be reached. If you have the second case with "local", the agent will try to multicast to find the server. You would have a different problem, maybe firewall.

**Comment by billydu1980** [comment]
Dear All:

The problem has been solved and the cause of the failure has been found. I created several MeshServers in the LAN,  I copied all of the meshcentral running folder instead of the normal installation，As a result, multiple MeshServerID is exactly the same.

Best regards,
Billy Du

**Comment by MailYouLater** [comment]
@billydu1980: Thanks for returning to inform us what the issue was.  My issue could not have been caused by multiple servers, as I never had more than one server running on one LAN.
I don't have everything set up right now to test if my issue has perhaps been solved with the recent release of version 0.4.1, but if not, I'll open my own issue about it.

**Comment by billydu1980** [comment]
Dear all

On github website,  It's hard to upload logs which were userful to check.. 
attached.




Best regards,
Billydudu

**Comment by MailYouLater** [comment]
This issue is closed, I you're having an issue like this again, please verify that your issue is not the same as it was previously (multiple instances of the MeshCentral server operating on the same network with the same ServerID), and open a [new issue](https://github.com/Ylianst/MeshCentral/issues/new).  Also, what you said in that post indicated that you had attached some logs.  FYI, GitHub issue comments posted by replying to a notification email don't retain attachments when they appear in the GitHub issue thread.  If you want to post attachments, you'll need to go to the GitHub issue thread you're wanting to attach them to, then drag & drop them into the text input for posting comments, wait for the 'uploading file' text to turn into a link to where GitHub just uploaded a copy of the file to, and post the comment.
