### ISSUE TITLE
unable to add new devices after a period of time

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4374]
**Describe the bug**
after a period of time (always random) i am unable to add new devices to my setup?
this included both via the add agent and downloading the exe
AND
downloading the meshcentral assistant and asking end users to run the app?
the assistant just sits there on screen saying 'Authenticating' ?

**To Reproduce**
1. keep meshcentral running for a while
2. download the windows exe or the assistant
3. try installing/running them
4. assistant sits on 'authenticating' never adds the device
5. the install, installs fine, but again never adds the device to the server? 

**Expected behavior**
it to add the device no problem

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Alpine
 - Virtualization: Docker
 - Network: Hybrid, Traefik Reverse Proxy, SSL Offload
 - Version:  1.0.63
 - Node: 16.16.0

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11
 - Network: Wan
 - Browser: Firefox
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: Computer
 - OS: ANY OS
 - Network: ANY
 - Current Core Version (if known): N/A

**Additional context**
the only way ive found to fix the issue is to restart meshcentral?

**ENABLED TRACE BELOW**
```
HTTPHEADER:
GET
/agent.ashx/.websocket
{
	"host": "meshcentral.myserver.com",
	"connection": "Upgrade",
	"sec-websocket-extensions": "permessage-deflate; client_no_context_takeover",
	"sec-websocket-key": "dGhlIHNhbXBsZSBub25jZQ==",
	"sec-websocket-version": "13",
	"upgrade": "websocket",
	"x-forwarded-for": "217.14.1.1",
	"x-forwarded-host": "meshcentral.myserver.com",
	"x-forwarded-port": "443",
	"x-forwarded-proto": "wss",
	"x-forwarded-server": "94ef1ecbf78a",
	"x-real-ip": "217.14.1.1",
	"accept-encoding": "gzip"
}

WEBREQUEST:
(217.14.1.1) /agent.ashx/.websocket

AGENT:
New agent at 217.14.1.1:58192

AGENT:
Verified agent connection to noOlpSxV7EjePE7brlf7bCjEAjDQJPFN8oM6vOBUBRXhyZ9xRaYodQZgfikaUR$W(217.14.1.1:58192).

AGENT: (after 30 seconds)
Agent disconnect noOlpSxV7EjePE7brlf7bCjEAjDQJPFN8oM6vOBUBRXhyZ9xRaYodQZgfikaUR$W(217.14.1.1:58192) id = Unknown
```

**Your config.json file**
```
{
	"$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
	"settings": {
		"cert": "meshcentral.myserver.com",
		"port": 443,
		"redirPort": 80,
		"AgentPong": 300,
		"authLog": "/opt/meshcentral/meshcentral-data/authlog.log",
		"trustedProxy": "traefik",
		"relayDNS": "relay.meshcentral.myserver.com",
		"tlsOffload": "traefik",
		"autoBackup": {
			"backupIntervalHours": 1,
			"keepLastDaysBackup": 7,
			"backupPath": "/opt/meshcentral/meshcentral-backup"
		}
	},
	"domains": {
		"": {
			"title": "MyCentral",
			"certUrl": "https://traefik:443",
			"agentCustomization": {
				"companyName": "My Ltd",
				"image": "128x128.png"
			},
			"assistantCustomization": {
				"image": "128x128.png"
			},
			"androidCustomization": {
				"image": "128x128.png"
			},
			"sessionRecording": {
				"filepath": "/opt/meshcentral/meshcentral-recordings"
			}
		}
	}
}
```

**Comment by Ylianst** [comment]
I have seen a situation like this before where people would have a firewall limiting the number of connections to a port. That would lead to people installing a new agent quickly to have it show up, but would lead to an old agent not being able to connect since the connection count was maxed out. It does not seem like this is your case since your saying the agent did connect and disconnected after a while.

Around how many agents to you have connecting? Also, confirm your using NeDB as the database?

**Comment by si458** [comment]
> I have seen a situation like this before where people would have a firewall limiting the number of connections to a port. That would lead to people installing a new agent quickly to have it show up, but would lead to an old agent not being able to connect since the connection count was maxed out. It does not seem like this is your case since your saying the agent did connect and disconnected after a while.
> 
> Around how many agents to you have connecting? Also, confirm your using NeDB as the database?

i dont believe its a firewall issue as why would it work after a restart? (i use a virtual mikrotik CHR firewall)
yes it is indeed NeDB
i have a total of 67 devices connected currently but all from different places and different ip addresses?
and currently 0 devices from the ip address where i run the assistant
also the assistant NEVER connects, it just sits on the 'authenticating' message, the disconnect is me closing the app manually (sorry should of said)
also i think its the same for installing the agent too (not sure how to debug this?)

**Comment by si458** [comment]
im not sure if its an issue or not BUT
the port meshcentral shows in the logs the assistant/agent is connecting from ISNT the same port traefik shows the computer connected from in the first place?
E.g. meshcentral shows port 12345 but traefik shows the actually port is 54321 for the 443 connection

**Comment by Ylianst** [comment]
Having 67 devices should really not be a problem. I have servers with 20k+ devices so, this should not be an issue at all. For the port number. If that is the source port number, I don't think that is an issue. It does not matter what the source port number of a connection is.

The fact that you have Traefik on front if your server is interesting since looking at the config.json above, there is no indication the server is behind a reverse-proxy. I would expect something more like this:

```
{
  "settings": {
    "cert": "myserver.mydomain.com",
    "WANonly": true,
    "sessionKey": "MyReallySecretPassword1",
    "tlsOffload": "192.168.1.100",
    "port": 8000,
    "aliasPort": 443,
    "redirPort": 8001,
    "redirAliasPort": 80
  },
  "domains": {
    "": {
      "certurl": "https://192.168.1.100:443"
    }
  }
}
```

Here the server name is set and is in WAN only mode. The HTTPS port is 8000, but will be exposed at 443 externally. HTTP is on 8001 but exposed as 80 externally. The reverse proxy will be doing TLS and forwarding non-TLS connections to port 8000 (this is why there is TLS offload) also, the TLS offload indicates the private IP address of the reverse proxy is "192.168.1.100" this is so it will consider the "X-Forward-For" header. Lastly, MeshCentral can get the external TLS cert that the agents will see at "certurl": "https://192.168.1.100:443".

Because "cert" is not currently set in your config.json, the agents will try to multicast to find the server, that will not work outside the local network where MeshCentral is located. MeshCentral is probably in LAN mode.

**Comment by si458** [comment]
@Ylianst sorry i totally forgot to give my config.json! i have updated my original issue with my config.json

**Comment by VINISHVV** [comment]
@si458 - if you turn off session recording then this issue will fixed.  I have 10k agent with similar issues in my server. Once i turned off recording this issue is fixed

**Comment by si458** [comment]
> @si458 - if you turn off session recording then this issue will fixed.  I have 10k agent with similar issues in my server. Once i turned off recording this issue is fixed

I turned it off yesterday and so far you are correct

With screen recording disabled I can add and connect but when it's enabled after a period of time you can't connect or add devices

**Comment by si458** [comment]
PLEASE FOLLOW #4449
