### ISSUE TITLE
Feature Request - Custom User Roles and Option to Set Default User Role for New Users

### ISSUE THREAD

**Issue by Philabusterer** [Ylianst/MeshCentral#4378]
**Is your feature request related to a problem? Please describe.**
When adding new users, the only options for roles are "User" and "Administrator".  Modifying user permission therefore requires making changes to each user individually.  If bulk adding users that need more than the default "User" level permission this is a lot of extra clicking through the GUI.

**Describe the solution you'd like**
Ability to create custom user roles which are assignable.
Ability to set any role as the default role for new users.
Ability to add users to role groups through a group management page as well as by directly modifying each user.

**Comment by Ylianst** [comment]
When saying "adding new users", is that new users to a device group? or use accounts to the server?

Can you provide a screenshot on this: only options for roles are "User" and "Administrator"

Do you use the import feature in "My Users" to create accounts in bulk?

I am not super clear on the request.

**Comment by Philabusterer** [comment]
@Ylianst 

Sorry for the lack of clarity.  I'm taking about when adding new accounts to the server.  I'm also planning on working to integrate with Azure AD and I think I remember reading that new accounts can be created on first login when integrating with Azure AD as an identity provider, but I only glanced at that a few days ago so I could be mistaken.  If that is case I would expect all new users would be created with standard "User" permissions.  

For further clarity, on the Users page in the server UI, under the permissions column on the far right side of the page, you can see the built in named roles "User" or "Administrator" listed.  

![image](https://user-images.githubusercontent.com/104400381/183501498-fddb63ea-ae7a-4da9-9f53-ba5704754b9d.png)

By default everyone is added as a "User" and if you add additional permissions without selecting the "Full Administrator" checkbox it shows "Partial*".  

I would ideally want to be able to create multiple named permission roles with more than basic "User" level settings, but without being a full "Administrator".  For new account creation, I would want to be able to assign a new user to a custom default role instead of the default "User" role.  It would also be great if you could specify that named permission role when importing users in bulk so you can assign new users to custom roles at the time you create accounts when bulk importing new users.  

It might be sufficient for the short term to just be able to customize the "User" role to be able to include some level of administrative permissions which would become the default for all new users.  

I also find it interesting that the default "User" role can create new devices and groups by default.  Those permissions are often considered administrative level priviledges on many other platforms.  For standard non-priviledged users I would not personally want those users to be able to adjust or add anything on the server.  

Let me know if you need further information on my request.  Thanks.

**Comment by Ylianst** [comment]
Hi. MeshCentral does support LDAP and next week, I will have a YouTube video coming out on setting up MeshCentral with LDAP. If you can do that, it's certainly the best since it's less passwords for users to deal with.

In the "My Account" panel, the "User" or "Administrator" or "Partial" is just an indicate of what permissions that user is, it's not reflective of any roles. I can't really fit all the granted permissions into that skinny columns, so the indicator is just an general idea of that permissions the user has. Since these permissions are server-wide, they are not used much. Device group permissions are used a lot more since they indicate what permissions a user has on a specific device. These server wide permissions are very occasionally used and so, I am not tempted to put a lot of efforts in creating "roles" for these.

It seems like what you want is for default users to no be able to create device groups?

**Comment by Philabusterer** [comment]
I think your final sentence sums up what I would immediately want to be able to adjust. 

I've already set up and got Azure AD authentication working and it works fine. I've tested it with a few users already. As soon as they logged in they got the default user permissions. That means that they can add groups and devices and I wouldn't want that.
