### ISSUE TITLE
Audio/Video icons are not showing on MeshCentral messenger

### ISSUE THREAD

**Issue by rajatheynetech** [Ylianst/MeshCentral#4388]
I have updated the config.json with "_webRTC": true. But Audio/Video icons are not showing on MeshCentral messenger

**Comment by Ylianst** [comment]
The `"webrtc": true` in the settings section of the config.json is for the WebRTC used within the MeshAgent, it does not impact the Messenger at all.

Messenger will always attempt to setup WebRTC between two messenger end-points and if successful, the audio and video buttons will show up. Since WebRTC is a UDP protocol, it can't go thru HTTP proxies and sometimes can't go thru some NAT routers. If this is your case, the only way to get around this is to setup a TURN server.

In researched an answer for this question I found the [Open Relay Project](https://www.metered.ca/tools/openrelay/). I have not tested it, but try adding the following in the settings section of your config.json:

```
    "webrtcConfig": {
      "iceServers": [
        {
          urls: "stun:openrelay.metered.ca:80",
        },
        {
          urls: "turn:openrelay.metered.ca:80",
          username: "openrelayproject",
          credential: "openrelayproject",
        },
        {
          urls: "turn:openrelay.metered.ca:443",
          username: "openrelayproject",
          credential: "openrelayproject",
        },
        {
          urls: "turn:openrelay.metered.ca:443?transport=tcp",
          username: "openrelayproject",
          credential: "openrelayproject",
        },
      ]
    }
````

TURN servers are not free to run, so consider making a donation or helping them out in some way.
