### ISSUE TITLE
issue with chat option

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#440]
Hi,
I was wondering if someone else has had issue with the chat, i open it but it says on waiting for user to accept but never appears a popup or nothing any ideas?
Thank you

**Comment by johnczer** [comment]
Yes
https://github.com/Ylianst/MeshCentral/issues/305

**Comment by MailYouLater** [comment]
I too have been unable to use the chat feature. #305 indicates that it works for installed mesh agents (running as LOCAL SERVICE), but not for temporary mesh agents (running as current user), but I haven't seen it work at all ... ever.

@johnczer: Is it still working for you on installed agents? If so, were there any special steps or configuration options you had to go through to get it working? If not, do you know what the last version that worked was?

**Comment by johnczer** [comment]
I have not tried it on the 0.4.0-b as of yet but on 0.3.x versions it worked on installed agents but just not the temp agent. I didn’t have to do anything special to get it to work. I believe it has to do with the way the temp agent runs under a different security context and Brian was looking into a fix.

**Comment by killmasta93** [comment]
same here as running local service or temp mesh agents neither works :(

**Comment by Ylianst** [comment]
I think this is related to the remote browser/chat window not opening in the local user context. Bryan has a fix (I think).

A note on how the chat works. The server will generate a URL and have the admin and remote machine open new browser tabs to this URL. The URL should look like: "https://server/messenger?id=meshmessenger/node....". Once both browsers open the URL, the chat session is established. So really, the MeshAgent only needs to open a browser on the remote machine with the right URL, however this is more difficult than it may seem.

So, if you see the chat box show up on your side, but not on the other side, that is the problem. If the remote machine does open the browser, but with wrong proxy settings, etc. That will also not work.

**Comment by MailYouLater** [comment]
Interesting, so I've verified that it does work if I copy the URL from the window that opened on my end, then use the remote desktop feature to open a browser on the remote computer set the remote clipboard via the clipboard set functionality, then paste the URL in the browser.

I also tried using the `openurl` mesh agent console command, as well as clicking on the globe, pasting in the "Open Page on Device" input and clicking OK, to see if these would open the chat window on the remote machine, but instead I'm asked which browser to open it with.

Why these options not open in the program I have set as my default browser?
Instead it opens this:  
![image](https://user-images.githubusercontent.com/1279475/63621741-93b88880-c5a9-11e9-9dde-87f2b0efbb89.png)  
It doesn't even list the program I have set as my default browser as an option:  
![image](https://user-images.githubusercontent.com/1279475/63622250-05450680-c5ab-11e9-9127-dacd440c297f.png)

**Comment by killmasta93** [comment]
so what i did is open the chrome or browser and then click on type and send the URL and the user gets connected to the chat. The only thing odd is that maybe around every 1min or so shows this 

Connection closed.
Waiting for other user...
Connected.
Connection closed.
Waiting for other user...
Connected.
Connection closed.
Waiting for other user...
Connected.

**Comment by Ylianst** [comment]
FYI. In the last week, there has been improvements to how the chat window is open by the MeshAgent. It used to open using the SYSTEM account which was not correct. It now opens under the currently logged in user and so, should fix a bunch of issues.

**Comment by johnczer** [comment]
Thanks for the heads up! I’ve been pretty good about staying up with the latest updates and this is one of the first things I check but I’ll check this again and let you know.

**Comment by johnczer** [comment]
I had a chance to test this on version 0.4.1-v and the chat did not work when trying on temporary connect method. I updated to the latest 0.4.2-i and same result. I thought I would try to see if chat still worked with permanent connection and it does not work anymore. When I tried to open a web address on remote PC when in permanent connection mode the remote system blue screened. This was tested on a remote Windows 7/64bit PC and everything did work before with exception to trying these things over the temporary connect method.  Thanks

**Comment by krayon007** [comment]
What Service Pack is your Win7 machine? I can probably at least get the temporary agent mode to work, because I can detect if the current session ID to check if we are running as LocalSytem or a user. Currently, it uses the Task Scheduler to have the OS spawn the default browser in the user session. Not sure why that would blue screen, but I can certainly test in on my Windows 7 SP1 test machine.

**Comment by johnczer** [comment]
Hey Brian, It is Windows 7 SP1 and tried on two different PCs.  I also went back to trying the chat on permanent connected agent and this does not work for some strange reason now.  I tried several things like rolling back to previous MeshCentral versions because I know that at least the permanent connected method with chat worked at one point-just not ever with temp connected agent. The same holds true when trying to type a url and launch the browser-no dice.

**Comment by krayon007** [comment]
Just for grins and giggles, can you run this command on your Windows 7 machine, to see if it blue screens? This is the command I use to spawn the browser into the correct session. (Just substitute USERNAME with the actual username, and make sure the System32 folder is the correct path)
(Each command should be all on a single line)

The first command will create the task, the second will forces it to launch, and the third deletes it.

SCHTASKS /CREATE /F /TN TempTask /SC ONCE /ST 00:00 /RU USERNAME  /TR "C:\windows\system32\cmd.exe /C START  http://www.google.com"

SCHTASKS /RUN /TN TempTask

SCHTASKS /DELETE /F /TN TempTask

**Comment by johnczer** [comment]
Sure thing Brian, doing that now and trying something else.  I am logged into this one PC with Domain Admin account which has local Admin privileges. I ran those commands up to the second one and looked to see if the task itself had any errors and it does. "The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist." I am wondering if this would work under local admin user account, so that's what I was going to try next. While I'm trying this here are the command outputs in general:
1st CMD: WARNING: Task may not run because /ST is earlier than current time. 
SUCCESS: The scheduled task "temtask" has successfully been created.
2nd CMD: Attempted to run the scheduled task "temptask"
...but then my discovery when looking at actual task result.  Let me know if you need me to try anything else!

**Comment by johnczer** [comment]
OK, so running the command as DOMAIN\Administrator works which is the same account I am logged in to when trying this over the agent.
I just logged off of this PC as Domain Admin and logged in to it as local admin and everything seems to be working while connected with temporary agent. Hmmmm....

**Comment by johnczer** [comment]
Just verified that it works over permanent connected agent as well; all under local admin account. Going back to logging in as domain user account, which of course has local admin privileges. This would be the scenario for most of my customer computers that i connect to and use the chat over temporary agent.

**Comment by johnczer** [comment]
I'm getting ready to head to another site Brian, just in case there was something else you wanted me to try. From what I gather so far with some quick testing is that the chat doesn't like the domain logged in account because of the way it's launched.  It's something quite simple I'm sure (it always is!) and I am sure you will have an answer.  Thanks Brian!

**Comment by johnczer** [comment]
Hey Bryan,  I was just checking to see if you had any luck with this.
