### ISSUE TITLE
Intel AMT behind Nginx Proxy Manager

### ISSUE THREAD

**Issue by JSkolnik** [Ylianst/MeshCentral#4402]
Please advice whether NPM support for Meshcentral - Intel AMT Cira connection can be set.
The manual is https://info.meshcentral.com/downloads/meshcentral2/meshcentral2useguide-0.2.9.pdf - from page 32. Can settings be implemented to NPM?
Specifically, listening proxy on port 4433 and forward "IP Meshcentral 44330".

**Comment by si458** [comment]
I'm about confused on your issue?

Meshcentral already supports Intel amt

Please make sure you have installed the latest version from npm which is 1.0.67

https://ylianst.github.io/MeshCentral/intelamt/ has some helpful stuff including videos to setup amt

**Comment by JSkolnik** [comment]
I apologize for the inaccurate description.

The problem is not with Intel AMT, but the availability in hybrid mode (WAN) for reverse proxy in the form of "Nginx Proxy Manager".
In the manager I can not set the listening -> Redirect port redirection for Intel AMT.

I added to config.json:
```
"MPSPORT": 44330,
"MPSAIASPORT": 4433,
"Mpstlsoffload": True
```

But I don't know how to set up in NPM (Nginx Proxy Manager).The question was determined who has it set and works.

Proxy Host is set - this set Meshcentral works:
![npm1](https://user-images.githubusercontent.com/56351039/184846133-814f5225-5a98-4bca-80d1-2ab9956a358f.png)
![npm2](https://user-images.githubusercontent.com/56351039/184846158-5558fb1f-d243-4b80-a485-e52a67057269.png)
![npm3](https://user-images.githubusercontent.com/56351039/184846183-e9b57d54-fef9-45e1-a81d-88a02d9bda8a.png)

**Comment by jsastriawan** [comment]
CIRA is not based on HTTP protocol. It is derived from SSH Port Forwarding Protocol. So, it could not be proxied using Nginx. What is your use case?

**Comment by si458** [comment]
> CIRA is not based on HTTP protocol. It is derived from SSH Port Forwarding Protocol. So, it could not be proxied using Nginx. What is your use case?

You need a tcp load balancer like traefik I'm not sure if the nginx supports tcp only http?

**Comment by Ylianst** [comment]
@jsastriawan  and @si458 are correct that Intel AMT CIRA is not HTTP, so you need to forward the TCP connection directly to MeshCentral. Also, I see your options:

```
"MPSPORT": 44330,
"MPSAIASPORT": 4433,
"Mpstlsoffload": True
```

I would change to this:

```
"MpsPort": 44330,
"MpsAliasPort": 4433,
"MpsTlsOffload": false
```

I would not do TLS offload for the MPS/CIRA port because it uses a special certificate that is only ok for Intel AMT. Also the correct spelling of "MPSAIASPORT" corrected to "MpsAliasPort".

If you browse to https://yourserver:4433, MeshCentral will detect the HTTP and relay with a small message, but this is for debugging, the port is TCP binary.

Hope that helps.

**Comment by smartekIT** [comment]
I had it in the past working on the server where traffic was controlled by NPM. to do that, in NPM interface under HOSTS menu click on Streams. there where you can set a TCP and UDP forwarding ports same like if you were doing it in a real modem.

Hope that helps

**Comment by JSkolnik** [comment]
In NPM I set the stream, local IP addresses work.After entering DNS names, the browser displays a certificate error - HTTP STRICT Transport Security (HSTS).

IP address NPM: 172.16.18.26
IP address Meshcentral: 172.16.18.23
![amt11](https://user-images.githubusercontent.com/56351039/185188060-b5bd118f-1bb2-4f98-aa1d-c071e77c4a57.png)
![amt22](https://user-images.githubusercontent.com/56351039/185188085-a184a264-7b80-4a52-9b97-b918390fa037.png)
![amt33](https://user-images.githubusercontent.com/56351039/185188103-5e59cc49-3cc3-40b7-a70a-34c3cac40fa7.png)

My config.json:
```
"MpsPort": 44330,
"MpsAliasPort": 4433,
"MpsTlsOffload": false
```

**Comment by smartekIT** [comment]
after you set the stream to forward in NPM, then you let your NPM create the SSL for you not the Meshcentral one.
in your config of Meshcentral should add the internal IP address of your NPM docker as trusted IP.
from the way your IP addresses I guess you have NPM as a docker container and the same with the Meshcentral as another container on the same docker subnet.

**Comment by smartekIT** [comment]
in the SSL tab of your host you should have it like this:
![image](https://user-images.githubusercontent.com/70715469/185194836-59a58b8a-9c66-467c-aa74-17e4f4d1c1b8.png)

and in the advanced it should be like this:
![image](https://user-images.githubusercontent.com/70715469/185195038-0d0338f9-6bed-4797-8012-be2606743458.png)

and in the main tab of your host it should be like this:
![image](https://user-images.githubusercontent.com/70715469/185195362-fbe622b3-1db6-4f9e-958e-ee8eb3cf3931.png)

**Comment by smartekIT** [comment]
ah in your stream it should look like this:
![image](https://user-images.githubusercontent.com/70715469/185195858-ac892d68-ea7f-41d2-91aa-bd4793102b75.png)

**Comment by smartekIT** [comment]
in the config should have it like this: (note what starts with _ means it's disabled opton)
<pre>
    "_tlsOffload": "127.0.0.1,::1",
    "trustedProxy": "127.0.0.1,::1,172.0.0.0/8",
    "mpsPort": 4433,
    "_mpsPortBind": "127.0.0.1",
    "mpsAliasPort": 4433,
    "mpsAliasHost": "mps.example.com",
    "_mpsTlsOffload": true,
</pre>

**Comment by smartekIT** [comment]
sorry i had to go to my old server and get all these settings for you, it was all working fine that way.
make sure you change the above mps.example.com to yours and yours is pointed to your server, then AMT will use your value here + :4433 to connect and that should reach your server because you already have that Port on the stream section of NPM.
note that you have that issue in Edge for HSTS which is normal as it takes time for Edge to clear and sync the new value. you can force clear the cache there which will help.

**Comment by smartekIT** [comment]
another note for you, in your host main tab, change scheme to https and do the same on the custom locations tab as well.

**Comment by Ylianst** [comment]
The potential security issue on port 4433 is OK and expected. Port 4433 will have a special TLS certificate that is signed by your MeshCentral root certificate with a common name that looks like "MeshCentralRoot-071233".

Your browser will display a warning, but Intel AMT CIRA will be setup to connect to the port and it will work. Do not try to put a different certificate on that port since, when Intel AMT connects, it will fail because it's expecting this special TLS certificate.

Hope that helps.

**Comment by smartekIT** [comment]
hi @Ylianst , NPM issue the cert for the normal https web and agent connection. the AMT will be using the meshcentral root cert the one you pointed because it see the server directly by communicating on the port 4433 which the NPM does a raw tcp traffic there without offering any cert for that.
so the screenshot the sent here was for the whole thing how i configured it in the past, https for web access and agents + the NPM stream section which is just port forwarding like any modem.

**Comment by smartekIT** [comment]
best structure i had it before was installing meshcentral on the host itself not on the docker.
exclude ports 4433 (AMT) and 444 (agent connection) from going to the docker switch and have them served on the host itself for agents and AMT.
get port 80 and 443 to go normally to the docker switch > containers > NPM
then NPM decide on the requested host name, so it sends the webaccess (port 80 and 443 for meshcentral FQDN) back to host signed with the SSL cert issues on NPM.
meshcentral config, been adjusted to trust certs from the NPM subnet 172.xxx.xxx.xxx

**Comment by JSkolnik** [comment]
> The potential security issue on port 4433 is OK and expected. Port 4433 will have a special TLS certificate that is signed by your MeshCentral root certificate with a common name that looks like "MeshCentralRoot-071233".
> 
> Your browser will display a warning, but Intel AMT CIRA will be setup to connect to the port and it will work. Do not try to put a different certificate on that port since, when Intel AMT connects, it will fail because it's expecting this special TLS certificate.
> 
> Hope that helps.

Yes it's right.After entering the URL in the browser https://mescentral.domain.com:4433, the browser displays a problem with a certificate (HSTS).
Certificate properties are:
```
Subject Name
Common Name meshcentral.domain.com

Issuer Name
Common Name MeshCentralRoot-a1e085
```
It's alright. But Meshcentral won't connect to AMT computer. Only verifies the login data.However, the Meshcommander client joins the PC without any problem.
