### ISSUE TITLE
CloudFlare trustedproxy not working

### ISSUE THREAD

**Issue by ghost** [Ylianst/MeshCentral#4411]
**Describe your issue**
Can you make a youtube video on cloudflare support. I added the "trustedproxy": "CloudFlare" to my config.json, but none of my agents will connect after I change the cloudflare dns record from dns only to proxied. 

I have reviewed https://github.com/Ylianst/MeshCentral/issues/3580 and other cloudflare tickets but nothing seems to work.

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04
 - Network: WAN, cloudflare
 - Version: 1.0.69

**Client Device (please complete the following information):**
 - Device: Laptops, Desktops, Raspberry Pi, MacBook
 - OS: Ubuntu, Windows, Mac os
 - Network: Remote over WAN
 - Browser: Google Chrome

```
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "remote.example.com",
    "trustedproxy": "CloudFlare",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "example",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "agentCustomization": {
        "displayName": "example",
        "description": "Allows example to provide full service remote support to this computer.",
        "companyName": "example",
        "serviceName": " Remote Support Agent",
        "fileName": "RemoteAgent" 
      }
    }
  }, 
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "example@gmail.com",
    "names": "remote.example.com",
    "production": true
  }
}
```

**Comment by Ylianst** [comment]
Good video suggestion. I will do that.

Placing the following line `"trustedproxy": "CloudFlare"` will cause MeshCentral to do an HTTP GET on the following two URL:

```
https://www.cloudflare.com/ips-v4
https://www.cloudflare.com/ips-v6
```

It will then trust the "x-forward-for" header from any of these addresses. This will only solve the problem of devices connecting and showing with the wrong IP address, but will do nothing else.

The problem your having is that the MeshAgent is connecting to CloudFlare and seeing an unexpected TLS cert. A bad way to fix this is to add this line to the "settings" section of the config.json file:

```
"ignoreAgentHashCheck": true
```

This may cause agent to connect, but it's not secure since it allows man-in-the-middle attacks. It is still useful for debugging to see if that is the problem.

The best way to fix this is to add the following line in the "domain" section of the config.json:

```
"certurl": "https://remote.example.com"
```

Of course, put your correct address here. This will cause MeshCentral to fetch the certificate that agents will see when connecting.

Let me know if that works.
