### ISSUE TITLE
Trusted Proxy agents keep dropping off every minute or so.

### ISSUE THREAD

**Issue by ghost** [Ylianst/MeshCentral#4425]
**Describe the bug**
I put my server behind cloudflare and added the trusted proxy settings as advised on ticket https://github.com/Ylianst/MeshCentral/issues/4411. But now the agents drop off every minute or so and come right back. Thinking its a issue with the websocket or something I messed up.

Server Software (please complete the following information):

OS: Ubuntu 22.04
Network: WAN, cloudflare
Version: 1.0.70
Client Device (please complete the following information):

Device: Laptops, Desktops, Raspberry Pi, MacBook
OS: Ubuntu, Windows, Mac os
Network: Remote over WAN
Browser: Google Chrome

```
"$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "trustedproxy": "CloudFlare",
    "cert": "remote.example.com",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "certurl": "https://remote.example.com",
      "title": "example",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "agentCustomization": {
        "displayName": "example",
        "description": "Allows example to provide full service remote support to this computer.",
        "companyName": "example",
        "serviceName": " Remote Support Agent",
        "fileName": "RemoteAgent" 
      }
    }
  }, 
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "example@gmail.com",
    "names": "remote.example.com",
    "production": true
  }
}
```

**Comment by Ylianst** [comment]
This is likely because CloudFlare or something else has a policy that drops idle connections. The agent will connect a web socket and wait for instructions. That socket is idle and gets dropped.

Add the following line in the "settings" section of your config.json:

```
"agentpong": 50
"browserpong": 50
```

This will send dummy data to browsers and agents every 50 seconds. Put the time as high as possible so to reduce traffic. If that does not work try this instead:

```
"agentping": 50
"browserping": 50
```

This will have the server send dummy traffic to the agent and browser every 50 seconds and have these respond back. Normally this is not needed, but let me know what you see.

if you have any control over the idle timeout of your proxies, make sure to raise that as high as possible since ping/pong traffic is wasted traffic.
