### ISSUE TITLE
Restarting selected domain

### ISSUE THREAD

**Issue by dxdemetriou** [Ylianst/MeshCentral#4455]
Is it possible to be restarted only a single domain instead the whole configuration?

For example, if there are multiple domains, when some change needed to not affect every domain, or whether some testing needed on dev domain to not affect the production and avoid disconnection of any connected users on the other domains.

**Comment by Ylianst** [comment]
There is currently no way to reset a single domain, you have to reset the server in order to have MeshCentral re-read the config.json. In the future I could look into a "soft" re-read of the config.json so that some options can be changed without a full server reset, but I am already flooded with requests.

**Comment by dxdemetriou** [comment]
Yes, sure, whether is possible. Thanks :)
