### ISSUE TITLE
Enhance custom branding options

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#448]
Would it be possible to implement the possibility of replacing the visual assets (images, html and css files) used in MeshCentral without having them be overridden with each update (e.g. by placing them inside the meshcentral-data folder)? As far as I can tell, that's currently only possible for the backdrop image for the site title by configuring it in the `config.json` file.

I'm currently looking to modify the following files to change the visual look of the MeshCentral login page:

```
/opt/meshcentral/node_modules/meshcentral/views/login.handlebars
/opt/meshcentral/node_modules/meshcentral/views/login-min.handlebars
/opt/meshcentral/node_modules/meshcentral/public/images/mainwelcome.jpg
```

**Comment by Ylianst** [comment]
Hi. Yes, it's already present. Create a new folder called "/opt/meshcentral/meshcentral-web" and copy the "public" and "views" folders into that one and restart the server. MeshCentral will see the "meshcentral-web" folder and grab files from that folder instead of the default.

This said, currently you have to copy the entire content of "public" and "views", you can just override some of the files, but I can work on fixing this if you like.

**Comment by whalehub** [comment]
@Ylianst Thanks, that's helpful. I suppose it'd be better if you didn't have to copy the entire folders, but it's not a high priority issue for me.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.0-h. With the new version, you can now override just the files you want in "meshcentral-web/public" and "meshcentral-web/views". No need to copy all the files anymore. Note that the "public" folder has a 1 hour cache time, so if you make changes to a file, hit the refresh button on the browser to force a re-load. Otherwise, you need to wait an hour for the change to show up.

Hope it makes sense.

**Comment by whalehub** [comment]
@Ylianst I just upgraded MeshCentral to v0.4.0-h, removed the unmodified files from `meshcentral-web/public` and `meshcentral-web/views` (leaving only the modified files), restarted MeshCentral and cleared my browser cache. Afterwards, I visited my MeshCentral page and observed that the login page is still using the original assets.

**Comment by whalehub** [comment]
@Ylianst Any update on this?

**Comment by Ylianst** [comment]
Ok, I am back and can take a look at it. I will do some testing and get back to you.

**Comment by Ylianst** [comment]
Hi. I just did some testing on this and I can't find any problems. Try this:

- Create a "meshcentral-web" at the same level as "meshcentral-data".
- In "meshcentral-web" create a "public" folder.
- In the "meshcentral-web/public" folder, create a "images" folder.
- Copy the "icons256-1-1.png" file from the "node_modules\meshcentral\public\images" into the new "images" folder.
- Edit the new "icons256-1-1.png" file with paint and scribble on it.
- Restart the server.

When you login to the website again, you may need to hit "shift-refresh" because images have a 1 hour cache time. You should see the scribbled image (my image below). I also tried this with "default.handlebars" in the "meshcentral-web/views" folder and it correctly replaces it. Can you try this and let me know if it works? Thanks.

![x](https://user-images.githubusercontent.com/1319013/64912398-7330a980-d6e3-11e9-888c-b9da59748dd3.png)

**Comment by whalehub** [comment]
@Ylianst Replacing the file `default.handlebars` works for me as well, but it doesn't work for the file `mainwelcome.jpg`, see screenshots.

![WinSCP_2019-09-15_17-36-00](https://user-images.githubusercontent.com/44198148/64924141-76aa5a80-d7e1-11e9-8f33-ef6bce949b62.png)
![WinSCP_2019-09-15_17-37-18](https://user-images.githubusercontent.com/44198148/64924144-78741e00-d7e1-11e9-8e2e-37258705824f.png)
![WinSCP_2019-09-15_17-38-41](https://user-images.githubusercontent.com/44198148/64924145-79a54b00-d7e1-11e9-92d3-79b7054b0989.png)
![vivaldi_2019-09-15_17-51-27](https://user-images.githubusercontent.com/44198148/64924146-7b6f0e80-d7e1-11e9-8008-c1ce2d1150f8.png)

**Comment by Ylianst** [comment]
Ha! "mainwelcome.jpg" and "server-256.png" are the two special ones that you can override by having a version of these files in your "meshcentral-data" folder. This pre-dates the "meshcentral-web" thing where you could override any file. Let me work on a fix for this.

In case you are curious, I wanted to make overriding the server image easy because I install MeshCentral on Raspberry Pi's and wanted to show a proper picture in the "My Server" tab like this:

![x](https://user-images.githubusercontent.com/1319013/64926452-8a8a9800-d7b2-11e9-9b4c-134d7b36b11f.png)

I do order that case and print the sticker on it, so the physical box looks just like the picture with is kinda cool. This is nice as a small management appliance for LAN's.

**Comment by Ylianst** [comment]
Ok, published MeshCentral v0.4.0-v with a fix for this. The "meshcentral-web" folder should work as expected, even for the special files: "logoback.png", "mainwelcome.jpg" and "server-256.png". Let me know if it works for you.

**Comment by whalehub** [comment]
@Ylianst Thanks for the fix, I can confirm that everything is working as expected now.

**Comment by EDIflyer** [comment]
@Ylianst I'm trying to replace some of the device icons (e.g., with an updated Pi image, or a mix (e.g., I have a Pi 4 and a Pi 400), I've replaced some of the icons256-x-1.png images as below:
![image](https://user-images.githubusercontent.com/13610277/209480507-cb6aca0a-f9a7-422d-980d-88b00aea1bd1.png)
However it still only seems to show the default:
![image](https://user-images.githubusercontent.com/13610277/209480513-af19f3ca-3588-4349-bc56-92101601af4f.png)

Do I need to copy the entire directory across or should doing some individual icons work here too?

**Comment by bravery-only** [comment]
My new face Mesh Central 
![Up6R3ra62v](https://user-images.githubusercontent.com/42680639/209875632-458747fe-a9c2-4eb0-97b2-587dff632c5f.png)

**Comment by prajwalkumarb** [comment]
> My new face Mesh Central ![Up6R3ra62v](https://user-images.githubusercontent.com/42680639/209875632-458747fe-a9c2-4eb0-97b2-587dff632c5f.png)

Great! @bravery-only 
can you provide the source code
