### ISSUE TITLE
Feature Request : Remote Agent Removal

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Ylianst/MeshCentral#449]
I understand deleting a device from the portal will not actually delete it, once the agent checks in that device will reappear.

Would it be possible to have an option to "remove the agent" button in the portal.

In the real world clients are lost overnight, with no opportunity to visit site and get the agent off the PC's, this results in many agents checking in when you no longer want them to with no way of seeing the device to remove the agent.

Many Thanks

**Comment by Ylianst** [comment]
This is a good request. At the very lease, have a uninstall command in the agent console for starters.

**Comment by johnnyq** [comment]
I was just getting ready to open up an issue with this same request until github told me one already exists I deff agree this feature would be fantastic

**Comment by MailYouLater** [comment]
Note: You can run `meshcentral.exe -fulluninstall` from the Terminal which removes the agent, but it tends to leave the `cmd.exe` and `conhost.exe` processes that the agent started running after the agent is gone, and it also doesn't remove the meshcentral listing for that computer.

It's interesting that when making a temporary connection by clicking "Connect" instead of "Install/Update", disconnecting the agent removes it from the list, but if it's installed it doesn't.  Can the agent switch this behavior when it's being uninstalled so it can (optionally) remove the listing in Mesh Central after removal.

**Comment by Sleepw4lker** [comment]
In addition, wouldn't also a bulk/remote Agent Auto-Update function be very useful?

**Comment by MailYouLater** [comment]
@Sleepw4lker: I'm pretty sure if the meshcentral server has an updated mesh agent, the mesh agent already auto-updates when it connects to the meshcentral server.

@Ylianst / @krayon007: Can you please verify?

**Comment by Ylianst** [comment]
Just to confirm, yes, the agents are all auto-updated when the MeshCentral server is updated. It takes a few minutes to do and most don't even notice.

I think Bryan was working on an agent console command to uninstall the agent, I will need to get an update on this.

**Comment by krayon007** [comment]
Actually, 'uninstallAgent' is already in the meshcore, as a console command. I just didn't add it to the 'help' because it needed updated agents to work, but since the agents have since been updated, this console command should already work.

**Comment by MailYouLater** [comment]
Duplicate: #581, #268

**Comment by Ylianst** [comment]
Correct, this is duplicate. Closing, please use #581.
