### ISSUE TITLE
Main Screen "Wallpaper" Request

### ISSUE THREAD

**Issue by Matt-CyberGuy** [Ylianst/MeshCentral#4524]
No issue, just purely an aesthetic request. Wondering if there could be a feature added to change the default blue background of the main area of MeshCentral to a jpg or png. 

I've looked through the [config scheme](https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json) file but was unable to identify any config entries relating to the main production background area. 

As always, you guys are the absolute best! Love this project!

**Comment by Ylianst** [comment]
Hi and thank you. For the top title bar, you can change the bitmap by placing a PNG bitmap in `meshcentral-data` and add the following line in the domain section of the config.json

```
  "domains": {
    "": {
      "title": "MeshCentral",
      "titlePicture": "title-sample.png"        <------
    }
  }
```

The top bar will look like this:

![image](https://user-images.githubusercontent.com/1319013/188983220-89e6a5a2-0102-45d0-b60e-2a53cbf9324e.png)

You can use Paint.net and put your logo on top of an image like this one...

![title-empty](https://user-images.githubusercontent.com/1319013/188985281-71cca2bf-03c5-4c18-a9d4-da1c7c3f9a66.png)

For the background, next to the `meshcentral-data` folder, create a folder called `meshcentral-web`, in it create a `public` folder, in `public` create a `styles` folder. Copy `node_modules\meshcentral\public\styles\style.css` to you `meshcentral-web\public\styles`. Edit the new `styles.css` and change this:

```
#masthead {
    width: auto;
    margin: 0;
    padding: 0;
    overflow: hidden;
    text-align: right;
    background-color: #636;   <----------------
    background-image: url(../logo.png);
    background-position-x: 0px;
    background-position-y: 0px;
    background-attachment: initial;
    background-repeat: no-repeat;
    /*width: 960px;*/
    height: 66px;
}
```

That will change the background color:

![image](https://user-images.githubusercontent.com/1319013/188986706-f6247487-c42d-4c75-8371-c1676bfe90fb.png)

Note that `meshcentral-web` is interesting since any files in it will override the default files serves in "public" and "views" with the one you provide. You can you change any MeshCentral images, etc. And it will keep when you update the server since it's outside the `node_modules` folder.

Let me know if that works.

**Comment by Ylianst** [comment]
Since I am at it. For the login screen, you can put a company logo and text like this:

```
  "domains": {
    "": {
      "loginPicture": "logintitle-sample.png",
      "welcomeText": "This is sample text"
    }
  }
```

To make it look like:

![image](https://user-images.githubusercontent.com/1319013/188989489-96d9152f-3b42-4cc3-af4c-0aa6c111c80c.png)

I used a 283x160 PNG image for the `logintitle-sample.png`. You can also put a background image like this:

```
  "domains": {
    "": {
      "loginPicture": "logintitle-sample.png",
      "welcomeText": "This is sample text",
      "welcomePicture": "mainwelcome-04.jpg"       <---------------
    }
  }
```

I used a big JPEG image, 5720x3346. It's going to be blended into the bottom left of the login screen:

![image](https://user-images.githubusercontent.com/1319013/188990751-1b4f02d0-5f14-4a6c-aee2-282313237eed.png)

You can then add this line:

```
  "domains": {
    "": {
      "loginPicture": "logintitle-sample.png",
      "welcomeText": "This is sample text",
      "welcomePicture": "mainwelcome-04.jpg",
      "welcomePictureFullScreen": true             <---------------
    }
  }
```

This will back the image full screen in the back of the login screen:

![image](https://user-images.githubusercontent.com/1319013/188991010-75b8bcf7-b79a-45f3-be28-f3e7baea2549.png)

Hope that helps.

**Comment by Matt-CyberGuy** [comment]
Thank you for those options. We actually use all of them and love it, but was looking for wallpaper version of background-color

**Comment by Ylianst** [comment]
Once you have your own version of `meshcentral-web\public\styles\styles.css`, you can make all the change you want to that file. It styles a lot of the web page. The left bar is here:

```
#page_leftbar {
    -ms-grid-column: 1;
    -ms-grid-row: 2;
    -ms-grid-row-span: 3;
    height: 100%;
    /* height: calc(100vh - 66px); */
    width: 90px;
    z-index: 1000;
    background: #113962;
    background: linear-gradient(to bottom, #104893 0%,#113962 100%);     <------------
    color: white;
    overflow-y: hidden;
    display: none;
}
```

If you are familiar with HTML, you should be able to do a lot of crazy things with this.

**Comment by Matt-CyberGuy** [comment]
Oh perfect! That'll work

**Comment by si458** [comment]
@silversword411 another how-to from @Ylianst for the docs!?

**Comment by silversword411** [comment]
@si458 you didn't wait long enough 😉

**Comment by silversword411** [comment]
...I knew there had to be something in there already...needs keywording and tweaking

https://ylianst.github.io/MeshCentral/meshcentral/#branding-terms-of-use

**Comment by silversword411** [comment]
https://github.com/Ylianst/MeshCentral/commit/02e4ac56785a0aadab73c21f808ab80ed378bc98
