### ISSUE TITLE
Availability of "Remove all 2FA" when LDAP is used and some suggestions about lock2factor and first/reset confirurations and their backupcodes renewals later

### ISSUE THREAD

**Issue by dxdemetriou** [Ylianst/MeshCentral#4555]
**Is your feature request related to a problem? Please describe.**

-The option "Remove all 2nd factor authentication" is not available when LDAP is used as there is no the "Change Password" option. Also, there is no some kind of security on their user's first 2FA configuration, and the "lock2factor" option is not allowing users users for setting their first 2FA.

**Describe the solution you'd like**

-Include "Remove all 2nd factor authentication" option when LDAP is used, so the administrators they'll be able to reset some user's 2FA

-Requirement of OTP for the first configuration/reset of 2FA either sent by email or manually (as some kind of security so you'll know that the 2FA configuration it's done by the same user and not by some other user because of some leak)

-When "lock2factor" is true, if not 2FA exist allow the users to configure their 2FA by an OTP given before, and if possible, allow users to renew their "Manage backup codes" by using their configured 2FA.

**Comment by ph4xo** [comment]
Hey guys,

just to add because I needed to reset 2fa for a ldap user yesterday:

You can delete the user and it will be recreated after next logon without any 2fa. It is not the cleanest way but it will work. Shouldn't be a problem if you sync all needed attributes automatically so nothing has to be edited after the first logon.

But for sure, it would be nice to just reset 2fa directly in the user administration.

Cheers,
Timo

**Comment by si458** [comment]
the was a recent fix merged 
which lets you use `node node_modules/meshcentral --resetaccount simon --pass abc123` which removes the 2fa for you
but it then had a bug which tried to change the password but thats not possible due to ldap external auth
and i did another PR to fix that issue
