### ISSUE TITLE
Update translation tool (Manageability Resource Translator Tool) to add new language (Bosnian)

### ISSUE THREAD

**Issue by adimesic** [Ylianst/MeshCentral#4572]
Hi @Ylianst,
 
I was wondering if you could update the Manageability Resource Translator Tool to add a new language, Bosnian.
Possibly also Croatian and Serbian, because the languages are very similar to Bosnian.
I will email you the translate.json file when I'm done with the translation.

Thank you for this great tool and your work, really appreciate it.

**Comment by Ylianst** [comment]
Working on this one now.

**Comment by Ylianst** [comment]
Ok, I just added there 3 languages to the translation tool:

Bosnian (bs)
Croatian (hr)
Serbian (sr)

I also did a full Google Translate of MeshCentral to Bosnian, this will be in 1.0.86. Once the new version is published, let me know if this works. The new ResourceTranslator is online now.

**Comment by Ylianst** [comment]
Just released v1.0.86 with Bosnian support. I will close this since it's done. You can help correct any issues by improving the translation.json file and sending it back to me to doing a pull request on GitHub.

![MC2-Bosnian](https://user-images.githubusercontent.com/1319013/197403028-ca2d11a4-ec09-4d8a-a202-0fa26b9e28f1.png)
