### ISSUE TITLE
MeshAgent enter password to uninstall

### ISSUE THREAD

**Issue by xanpri** [Ylianst/MeshCentral#4632]
I would like to ask for an improvement in MeshAgent.

If possible, put a password to uninstall the MeshAgent, just like when we are going to remove a corporate antivirus.

Example:

![image](https://user-images.githubusercontent.com/73598277/195663712-ffbfb852-e0bb-48fb-af83-b5a7194afd00.png)

This would make it easier to block the uninstallation of MeshAgent even if the user is the administrator of the computer.

**Comment by PetieM** [comment]
It wouldn't stop someone who knew what they were doing but it would prevent accidental removals or curious users who don't know how to bypass it so I'm for this as well.

**Comment by silversword411** [comment]
Accidental deletions?

Why are you letting users that don't know better be admins?

I admit, it can be a complicated answer...but I employ knowledgeable admins that want to restrict ignorant users uninstall access...is asking devs to create an arbitrary password prompt during an uninstall script contributing in any way to proper system security when that security only applies to a single piece of software?

Ask not what others can for your convenience, ask what you can do for your users security.

**Comment by PetieM** [comment]
I’m not. I used that as an example based on the original request. Like I said, this won’t stop a knowledgeable person with admin rights. It might stop a well-meaning “power user” trying to “clean up” what they don’t recognize which is why I can see some potential utility despite the fact that it would obviously be better to just not let users have admin rights to begin with.

**Comment by Ylianst** [comment]
This request has been made before and in the past I have not done this since as @silversword411 pointed out, if you have administrator rights on a device, you can uninstall regardless. Another issue I have with this is that MeshCentral may be used by people that are installing an agent on computers they should not be installing it on. In that case, they are trying to prevent the rightfully computer owner from cleaning up their own computer. Basically, this is starting to look a lot like malware to me. I would need a bunch of convincing that this would not harm the community at large.

**Comment by PetieM** [comment]
> Another issue I have with this is that MeshCentral may be used by people that are installing an agent on computers they should not be installing it on.

I hadn't thought about the potential for misuse here. The fact that a knowledgable user could easily bypass this protection combined with that is enough to convince me this isn't a good idea after all.

**Comment by xanpri** [comment]
I understand the question about security, the idea would not be for use as malware. But entering the password could be used as malware.

Thanks for the clarification.
