### ISSUE TITLE
Agents momentarily disconnects

### ISSUE THREAD

**Issue by exander77** [Ylianst/MeshCentral#4641]
This is hard to describe, but We experience a lot of agents going online and offline and both deskop and terminal session freezes.

I am not sure how to even debug this issue? We have around 100+ machines already in our server, I increased it's resources significantly, but it didn't change the behavior.

**Comment by krayon007** [comment]
Are you using a reverse proxy?

**Comment by exander77** [comment]
> Are you using a reverse proxy?

There is Amazon EKS ingress in front of it.

**Comment by exander77** [comment]
Should I tweak some Ingress settings?

**Comment by exander77** [comment]
I use the popular Docker image: https://hub.docker.com/r/typhonragewind/meshcentral
And it is deployed on Amazon EKS, there is standard Nginx based Ingress in front of the application.
It affects all of our devices in different locations, so it seems to be a server issue. It also affects all browsers (We definitely have Firefox, Chrome and Chromium.) Stations are mostly Ubuntu Linux, but different versions, but there are some Windows as well. Even Raspberry Pi with Raspbian. I can extract config from k8s storage.

**Comment by Ylianst** [comment]
Hi. If the agents and going offline and coming back online as regular intervals, this is likely because something in the infrastructure in front of MeshCentral is disconnecting idle TCP connections after a given amount of time. [I have a video on this exact topic here](https://www.youtube.com/watch?v=xoR3FoqUnlA).

Generally you have a reverse proxy or load balancer on your side, or a HTTP proxy on the agent side doing this. Something there is nothing you can do about that and you best solution is to have MeshCentral generate dummy traffic to keep connections alive. In the "settings" section of the config.json, add these lines:

```
"agentpong": 30,
"browserpong": 30
```

This will generate dummy web socket traffic every 30 seconds from the server to the agents/browsers. If that does not work, try this instead:

```
"agentping": 30,
"browserping": 30
```

This will generate web socket traffic every 30 seconds and have the agent/browser respond back. So, traffic will be two-way.

If one of the other work, try increasing the time like this:

```
"agentpong": 120,
"browserpong": 120
```

This is one-way traffic every 2 minutes. Since dummy traffic can be costly, you want to keep it to a minimum. Put as long a time value as possible and use "pong" if possible. Let me know if this works.

**Comment by exander77** [comment]
Seems better after setting pongs, I will watch for a while and report back.

**Comment by Ylianst** [comment]
It's been 6 days, I will close this. Feel free to re-open if needed.
