### ISSUE TITLE
command showpaths shows wrong paths

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#4699]
all functions works on the server regarding the structure of overwrite folders of view and public, BUT when doing showpaths in the console i noticed that it actually detects wrong paths for the XWebViews and XWebPublic.
you can see in the screenshot, they some how swapped, even though the overwrites function works as expected. thought of letting you know.

![image](https://user-images.githubusercontent.com/70715469/199434822-fc3a5bf9-87d0-4c55-9507-65000c601b77.png)

**Comment by Ylianst** [comment]
Arg. I don't understand the issue. Most users do not have the "meshcentral-web" customization paths, so they will see something like this:

![image](https://user-images.githubusercontent.com/1319013/199564636-a8122ff1-02c4-4d6d-837a-c8eff871f3d4.png)

Since you have the extra web override paths, you also see the "XWebPublic" and "XWebViews" values. Maybe the question I have is how would you have expected it to be displayed? I will gladly change it.

**Comment by smartekIT** [comment]
Thanks @Ylianst 
if you look at my screenshot (last 2 lines) it says:
**XWebPublic**: /home/node/meshcentral/meshcentral-web/**views**
**XWebViews**: /home/node/meshcentral/meshcentral-web/**public**

it should display the following instead:
**XWebPubli**c: /home/node/meshcentral/meshcentral-web/**public**
**XWebViews**: /home/node/meshcentral/meshcentral-web/**views**
