### ISSUE TITLE
RDP Connect in mobile view

### ISSUE THREAD

**Issue by vithusel** [Ylianst/MeshCentral#4707]
Hi,

On mobile view there seems to be no way to connect using RDP. 

Some of my servers have insanely long passwords so i have the credentials stored on the server to simplify login. 

Is there any possibility to have this added to the mobile view? 

Kind Regards,

Vit

**Comment by Ylianst** [comment]
Originally I made the remote desktop on the mobile site view-only because interacting with a desktop from a mobile site is not that great. I did get a bunch of asks to allows desktop input on the mobile app and I did, but it's never been wonderful. I am wondering if adding RDP on the mobile site would even been a good idea. Scrolling / doing keyboard input is not going to be clunky.

**Comment by vithusel** [comment]
> Originally I made the remote desktop on the mobile site view-only because interacting with a desktop from a mobile site is not that great. I did get a bunch of asks to allows desktop input on the mobile app and I did, but it's never been wonderful. I am wondering if adding RDP on the mobile site would even been a good idea. Scrolling / doing keyboard input is not going to be clunky.

True. 

A slightly different option then. Is it possible to create some form of password manager? So even in the normal desktop connect we get a option to auto enter password? Currently mesh central allows users to save rdp credentials. Extend this so you can click a button to type the password into the remote instance when in normal connect desktop. its basic but i think a lot of people would appreciate it

Perhaps also set it up so if you want to view the password a 2fa request is made for additional security. 

What do you think?

**Comment by dxdemetriou** [comment]
Actually for making it usable on mobiles are needed a way to zoom-in/out, a circle for mouse moving, tap for select, long-press for right-click, the keyboard to not resizing the screen, and a toolbar for basic functions and the keyboard enable (I know for sure that it's not easy). I'm using one very old app because of these features I cannot find on others (I'm using them as reference, I know that the request is for web-based), it's the "Jumb Desktop":

https://www.youtube.com/watch?v=GkvHs6bluo8

The second most-updated and faster, but I missed some features from the first, is the "Remotix":

https://play.google.com/store/apps/details?id=com.nulana.android.remotix&hl=en&gl=US

Probably with PWA it could be possible to be more useful instead from the browser? I know that most apps are going in this way for crossplatform compatibility too.

About passwords, it's a headacne everywhere.
