### ISSUE TITLE
Clicking SSH link generates an incorrect PuTTY request

### ISSUE THREAD

**Issue by fishter** [Ylianst/MeshCentral#4712]
(With MeshCentral 1.0.0 and 1.0.95)
Clicking the SSH link on a device to initiate an SSH connection with PuTTY results in an error message.

PuTTY gives an error dialog - "unknown option -p" and quits when OK is pressed.

**Comment by si458** [comment]
when you click SSH it should open up the meshcentral router application FIRST and then from the router application it should open up putty/command prompt

**Comment by si458** [comment]
i think the is something wrong with your default run of ssh, as on my laptop it automatically runs terminal which then runs ssh
also ssh has the option for `-p` which sets the port it needs to connect too,
```
PS C:\Users\sas_2> ssh
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]
```
how did you setup meshcentral router and specify putty?

**Comment by si458** [comment]
ive debugged it here, you have set the application for ssh to openssh instead of putty
open up the windows registry `regsvr32` then navigate to 
`HKEY_CURRENT_USER\Software\Open Source\MeshCentral Router`
delete the entries `OpenSshPath` and `PuttyPath`
then rerun router and try to ssh again, but this time make sure you change the application from openssh to putty

@Ylianst i think the needs to be an option in the meshcentral router to allow the end user to change the ssh application if they selected the wrong one by mistake!

**Comment by fishter** [comment]
I looked in my registry and the path for OpenSshPath was pointing to PuTTY and PuttyPath was empty.  I corrected that by making OpenSshPath empty and PuttyPath correct.
Now, it works as intended.
I'm not sure how it got muddled; that was most likely me.

**Comment by si458** [comment]
@fishter please can you re-open this issue? 
@Ylianst should implement an option to change thesein the GUI as the currently isnt one
