### ISSUE TITLE
Blank Screen on MAC OS X Mojave

### ISSUE THREAD

**Issue by penguinthingie** [Ylianst/MeshCentral#473]
Hi Guys,

All the new MACs with Mojave seems to now only show blank screen when attempting to connect to the "Desktop". Nothing happens on the device end either. Terminal and Files windows are all working though. "Interface" Information is also missing. Any ideas on what could be happening and if there is a fix for it?

Thanks for the continued great work! Cheers!

**Comment by krayon007** [comment]
From a terminal window on the Mojave, type the following command:
tccutil reset Accessibility

This will reset accessibility permissions on the OS... Then try to connect KVM again... It should popup a permissions dialog on Mojave saying the MeshAgent would like accessibility access... After you it takes you to the settings dialog, where you can add/enable the permission, you should be able to disconnect and reconnect KVM, and it should work.... Let me know if this works for you.

The underlying issue is that headless apps don't really work too well with the way Apple implemented these permissions when it comes to updating the binary, because it supposed to be keyed by the Bundle ID, which doesn't really exist for headless apps, so it gets keyed by the binary hash. Which is fine, except the UX for the permissions is not keyed this way, so if the binary updates, it still shows the binary as having permissions, even tho it doesn't, and doesn't appear to be a way to fix it without removing the old entry, and having it update when the app tries to connect the first time.

I'm working to add this as one of the console commands, so it can be done from the web ux.

**Comment by penguinthingie** [comment]
Thanks for the detailed explanation. Unfortunately, even after getting the prompt and disconnecting and reconnecting, still blank screen. Manually adding the osx file to Accessibility and attempting to connect yields same results as well.. any specific logs i should be looking at that could help us to troubleshoot this. Thanks!

**Comment by hunter-nl** [comment]
I did the procedure as described by @krayon007. Some OSX systems can been taken over with Desktop. Some of them always produce a black screen (with connected status and remote mouse is not moving at all). The Terminal, Files, Console are working fine.

**Comment by penguinthingie** [comment]
@hunter-nl, when you say some OSX Systems, are they running the latest Mojave or an older version?

**Comment by hunter-nl** [comment]
All run the same latest version. 10.14.6.
I've reported this and more OSX issues in issue #377

**Comment by penguinthingie** [comment]
ah.. ok.. definitely seems like its the new Mojave security restrictions where Applications need to be "certified" or "notarized as you put it" to run. Fingers crossed that there is a resolution on this. Thanks to the team for all their hard work as always!

**Comment by infineonnetworks** [comment]
There seems to be a security issue with a few versions of OSX. I have tried the agent on El Capitan, and the errors I am getting when connecting to the desktop (while it loads for a split second, then drops and disconnects) is 

`tccd sectaskloadentitlements failed error=22`

After looking this up I tried in vain to add the meshagent_os64 to the Security -> Privacy -> Accessibility panel. However even finding the agent installed in /usr/local/meshagent (a hidden directory on OS X), the application is greyed out and isn't allowed to be added. 
I have tried the `tccutil reset Accessibility` as well, with no luck.

**Comment by penguinthingie** [comment]
Any update on this? Anyone know how other RMM tools have been able to skirt pass Apple's Security gatekeeper on this?

**Comment by ryanblenis** [comment]
Not sure if this is entirely helpful, but I did run across [this](https://github.com/codebytere/node-mac-permissions) project for Mac permissions that may help the devs with this.

**Comment by MailYouLater** [comment]
At first glance that looks like it would be helpful, but a slightly deeper look doesn't show any references to the required Screen Recording permissions, and while I may be wrong, it also doesn't look like it can actually _request_ Accessibility access, just show the current status of it.  That being as it may, even if it is able to fully and properly manage all necessary permissions, @krayon007 has stated before that he wants to keep the reliance on other projects to a minimum for the agent, both to keep it small and to make sure it's maintainable.

Anyway, whether it actually ends up being useful or not, thanks for mentioning it, as even if it can't be used there's a chance that it could be used as a reference for possible changes to the existing agent code.

**Comment by audiolion** [comment]
Also ran into this issue on Mojave. Likely due to the new Gatekeeper restrictions regarding app notarization.

**Comment by jonrupell** [comment]
Has this been figured out yet, I am having the same issue

**Comment by rebootcs** [comment]
This is still an issue, with the exact same black screen and desktop control issues on OS 12.6.1

**Comment by silversword411** [comment]
You're having black screens after you've granted permissions in Security for mesh to Record Screen?

**Comment by rebootcs** [comment]
> You're having black screens after you've granted permissions in Security for mesh to Record Screen?

Yes and Actually these machines were working fine for a while and a user just reported they could not see anything but a black screen.  We had recently updated to 1.1.11 and now moved it back to 1.1.0 with no change on those machines.

**Comment by silversword411** [comment]
Mac permissions do get lost, and have to be set again.

**Comment by rebootcs** [comment]
We'll have to check again - Since these machines are remote. we have to retry when someone can control locally. If this is the recurring fix, it can't be sustainable for systems that are always remote.  Is there another method that might be more consistent - Like Web-VNC?

**Comment by silversword411** [comment]
Contact Apple, tell them to stop resetting permissions once you've set it on an app. 

From what I've seen it breaks when an Apple update is installed, so something in the apple update is undoing permissions you've set on an app.

**Comment by rebootcs** [comment]
I was on the apple account team for 15+ years as the Leading Xsan Engineer as their main service provider since 2002 for Enterprise, education and retail.. I know all too well about permissions and issues with permissions it is actually one of the things I was incharge of on deployments.. But that being the consistency in apple's normal operating process. Having a work around should be the norm and not the call. Since we all know that call will produce no results, til the next update.  Been the same since 10.0... not going to be any different with them tomorrow. I was thinking I would get more information for us to actually troubleshoot this further than what we already know.

**Comment by AymanAnsari** [comment]
I am continuing the thread from rebootcs.

Can anyone know how should we troubleshoot this issue. As after I login to the respective Mac, on Mesh the screen will be back. So it is only happening when we restart the Mac, it will again give us the black screen.

**Comment by silversword411** [comment]
> Can anyone know how should we troubleshoot this issue

Show a screenshot of what you see when starting connection. Show screenshot of your security > screen recording settings. Mesh will be unchecked/switch off. Fix the permission.

I'm betting you see the menu bar at the top.

That means you have to fix screen recording permissions.

**Comment by NiceGuyIT** [comment]
There's an existing PR to request the necessary permissions on agent startup.

- https://github.com/Ylianst/MeshAgent/pull/181

**Comment by dinger1986** [comment]
fix was merged @si458

**Comment by si458** [comment]
need to keep open until a new agent is released and users can CONFIRM its working as expected

**Comment by si458** [comment]
DUPLICATE ALSO, please follow #249
