### ISSUE TITLE
AMT Webserver supports TLS 1.0/1.1

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#4756]
Hello,
The "AMT Webserver" (example.fqdn.com:4433) supports TLS1.0 and TLS1.1
Is there a way to disable that support?

**Comment by Ylianst** [comment]
Yes, add the following line in the "settings" section of the config.json:

```
{
  "settings": {
    "mpshighsecurity": true
  }
}
```

Note that if you do that, older versions of Intel AMT may not be able to connect to the MPS server anymore. You can try updating the BIOS to the latest version of Intel AMT computers, but if the computer is old, it will not connect and it will not show any errors that CIRA fails to connect due to unsupported TLS version.

Hope this helps

**Comment by MordyT** [comment]
This solves the issue. I didn't see it in docs or the sample config, but it's likely I just missed it.
