### ISSUE TITLE
Update meshagent.msh after "Force agent update"

### ISSUE THREAD

**Issue by TerAnYu** [Ylianst/MeshCentral#4791]
How to update the parameters in meshagent.msh if I clicked to update the agent through the GUI, but the changes were not applied.

On the server side, I made changes, for example:
```
       "agentConfig": [
         "_webSocketMaskOverride=1",
         "_coreDumpEnabled=1",
         "skipmaccheck=1",
         "forceUpdate=1",
         "logUpdate=1",
         "remoteMouseRender=0"
       ],
```
But previously the agent was installed with the **remoteMouseRender=1** parameter, so how to overwrite it automatically (already installed on many devices)?

Or should this question be asked at https://github.com/Ylianst/MeshAgent ?

Thank you!

**Comment by TerAnYu** [comment]
Is it possible to add this to the "wish list"? I would like to update centrally some of the parameters that are on the server side.

**Comment by JSuenram** [comment]
> Is it possible to add this to the "wish list"? I would like to update centrally some of the parameters that are on the server side.

Would be a nice "Option" to also update the MSH-File when needed from Server-Side....

**Comment by si458** [comment]
i have been working on a feature which extends the `msh` command in the console tab!
what do people thing? its only a start but we can integrate more at a later date
```
Proper usage: msh [get|set|delete]
msh get MeshServer
msh set abc "xyz"
msh delete abc
```
self explanitory really,
get the value meshserver from the msh and tell me what it is
set the value abc in msh to xyz
delete the value abc in msh

you can also just call `msh` still to get the whole `msh` file thats loaded in memory in JSON form

i have also found you need to `service restart` to get things to apply 30% of the time (no idea why?)

also you cannot use JSON in the console `set` command!
so u cant change the `translation` line in msh for example due to the way meshcore phases the console command you send

**Comment by si458** [comment]
i have done my PR, if you wanted to patch it yourself and give it a try for me!

**Comment by arduin0guru** [comment]
Is there any way to run those commands on all agents in a simple way ???
" msh set MeshServer "XXXXXXXXXXXXXXX" "
"service restart "

Not to go to each console to run !

**Comment by si458** [comment]
Use column view then tick ur devices u want or right click the groups and click select all then click actions and select run commands then change the option to meshagent console
