### ISSUE TITLE
Icon problem in agent customization

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4829]
In the previous versions, when I put a PNG icon for the agent, it was transparent on the background, but now in the new version, the background of the icon is white.
![Agent](https://user-images.githubusercontent.com/42680639/205358908-ab3c40f4-33d6-4a5c-93c3-c992841bbc4c.png)

**Comment by krayon007** [comment]
looking at it now

**Comment by PathfinderNetworks** [comment]
Interesting, I just looked at my customized agent installer and am seeing the same thing.  It was definitely transparent on previous versions.

**Comment by bravery-only** [comment]
In the new version, the buttons are compatible with Windows. But the first button is similar to the Windows 98 button!

**Comment by krayon007** [comment]
I figured it out... In the newer version, I added a pragma to use Windows Common Controls 6, instead of the default, because earlier I found a bug in the default implementation of some of the controls, where the msdn documentation said the background color was not applied correctly. MSDN said to add the pragma, which fixed those issues. Looks like a side effect, is that it broke the transparency for this particular dialog control... Let me investigate how to get the transparancy working on this control.

**Comment by krayon007** [comment]
Ok, I fixed it. I had to explicitly add a handler for `WM_CTLCOLORSTATIC` for that dialog item, and explicitly set the background mode to transparent, even tho the rc file already had it set to transparent.. @Ylianst will need to push an update for the windows agent for this to take effect.

**Comment by mbsouth** [comment]
After installing MC 1.1.1 and after MC Agent selfupdate (background) the transparent logo background works perfectly, even when recreating agents.

Great work, many thanks!

**Comment by jobrien2001** [comment]
@krayon007 There is a similar problem with the account avatar.  Upload a transparent PNG and background is black... this shows in the assistant as well.

![image](https://user-images.githubusercontent.com/12868319/207513236-a78cdd38-32b5-47dc-a7c4-a75f46b503c3.png)

**Comment by si458** [comment]
this seems resolved now? 1.1.20
just tried it with a 256x256 png thats transparent, and it seems ok now
