### ISSUE TITLE
Windows Server 2019 freezes on running .exe

### ISSUE THREAD

**Issue by atomjump** [Ylianst/MeshCentral#4837]
So we have our own Ubuntu Raspberry Pi (Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1018-raspi aarch64)) installation of MeshCentral which is connecting to a client's remote Windows 2019 Server. The connection is working fine from within our Ubuntu Firefox browser, until we try to run an .exe file. Then the connection freezes and the cursor rotates but we have lost control of the remote cursor. After a minute or so (presumably when the client software on the Windows 2019 auto-restarts), we can get back onto the screen, but there was no indication of us having run the .exe file.

I managed to complete the operation on a rival service, as a temporary fix, but it would be great if you could look into this. It may be some Windows server setting around firewalls?  We don't have regular access to this server for testing or more detailed analysis, unfortunately.
 
We tried upgrading manually to ver 1.1.0 of MeshCentral on our Raspberry Pi (to see if this fixed the issue.), but the issue appears to still be there. 

Our config.json
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "[clipped]",
    "WANonly": true,
    "_LANonly": true,
    "sessionKey": "[clipped]",
    "port": 3277,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}

**Comment by si458** [comment]
have you installed the agent on the server 2019 (background service) or have you run the assistant (asked user to run the exe)?

the assistant runs as the user thats currently logged in,
so when you run an exe in server 2019 or server 2016, it will load up the Windows UAC panel to continue,
and sadly the UAC isnt visible because its run as admin, so its just times out and returns back to the desktop after 1-2mins

we encounted this with a recent Server 2016 Active directory server, every time we tried to run an exe or anything i would get a prompt on the server to carry on so clicked on it, but with meshcentral its not possible if you run the assistant unless you have the agent installed

to fix this issue you need to enable the admin approval mode then restart the remote device
https://www.tenable.com/audits/items/DISA_STIG_MS_Windows_Vista_V6R41_STIG.audit:ce7133f93809be1c8c96636b662fabf7

**Comment by atomjump** [comment]
Thanks for the suggestion, and that may well have been the issue. So we sent a time limited 'Invite' link (I assume that is the 'assistant'?), and the client installed it - they would have been logged in as an Admin user, although likely not the System user, and they may not have installed the initial client 'as Admin'.

**Comment by si458** [comment]
Yes send a new invite link with the agent and tell them to install the agent which runs as a service in the background which should also help your issue

**Comment by atomjump** [comment]
Thanks, while I can't confirm this on the client's machine, I'm happy to close out the issue.
