### ISSUE TITLE
Push authentication stopped working

### ISSUE THREAD

**Issue by folosleg** [Ylianst/MeshCentral#4844]
**Describe the bug**
Push auth stopped working around v1.1.0 unfortunately not sure exactly, didn't have the time to report bug, sorry.
Defo doesn't work as of 1.1.1

**To Reproduce**
1. Go to 'My Account'
2. Click on 'Manage push authentication'
3. Select Nothing Phone (1) device
4. Nothing happenes
5. Trace log: 
```
"1:54:51 PM","email","Failed auth addition push message to device Nothing phone (1), error: undefined"
"1:54:50 PM","email","Firebase-sending"
"1:54:50 PM","email","Firebase-sendToDevice-httpPost"
```

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Virtualization: none
 - Network: LAN/WAN, reverse proxy, ssl offload via HAproxy
 - Version: 1.1.1
 - Node: v16.18.1

**Remote Device (please complete the following information):**
 - Device: phone
 - OS: Android 12
 - Network: Local to Meshcentral or Remote over WAN as well
 - Current Core Version (if known): Android Agent v1.0.15

**Your config.json file**
no change in config.json since push auth was working properly, but
```
"publicPushNotifications": true,
```

**Comment by Ylianst** [comment]
Hi. Yes, I saw the problem and just fixed it. Thanks for reporting it. Let me know if it works now.

**Comment by folosleg** [comment]
Thanks a lot! It does work now as intended.

**Comment by Blackhazard2012** [comment]
Hi Ylianst,

with version 1.1.10 the above mentioned problem unfortunately occurs again

> Failed auth addition push message to device Blackmobile, error: undefined

. Is there any way to do it yourself and fix it?

**Comment by si458** [comment]
@Blackhazard2012 can you open a new issue (use bug report) and fill in all the details?
ive never been able to get push notification to work, so ill look at it when i can during the next week for you 👍

**Comment by si458** [comment]
@Blackhazard2012 ahh we might have an issue, because this setting is using the meshcentral.com server which i believe was switched off as @Ylianst explained about the other day! https://github.com/Ylianst/MeshCentral/discussions/5290
so i dont think the is anything we can do at the moment, until @Ylianst releases the sourcecode for the pushnotification stuff he used, OR you build your own apps using the sourcecode and edit the server stuff for your own pushnotification server
https://github.com/Ylianst/MeshCentral/blob/b1d2d1aea96c5de48be210e89961347cb6b8b72b/meshcentral-config-schema.json#L582-L586

**Comment by smartekIT** [comment]
@si458 hope you doing well.
do we have a guide about starting our own firebase? content of firebaserelay.aspx ?
also any recommendation how to custom build the android agent and publish our own?
Thanks
