### ISSUE TITLE
Send Notification upon sensors

### ISSUE THREAD

**Issue by levyalon** [Ylianst/MeshCentral#4877]
I wonder if there a way to automatically, use sensors (cpuinfo for temperature/Usage ect) to set rules (agent side perhaps?) 
to send email if sensor is out of predefined value

For instance, CPU Temp and SSD S.M.A.R.T (which is not reporting at the moment), in case if exceeding temperature, or SMART reports malfunction - trigger an email alert 

i assume that as console commands has cpuinfo and email commands, perhaps it can be set as script to run every certain amount of time and trigger email ?

**Comment by si458** [comment]
no the isnt

your question is more of a remote monitoring and management question, than a remote control question

you should look into tactialrmm https://github.com/amidaware/tacticalrmm

**Comment by PathfinderNetworks** [comment]
I don't see why this couldn't be done.  And I truly don't understand why, whenever there is a request like this, the answer is that MeshCentral is not an RMM tool and to look at TacticalRMM instead. Please stop doing this.  MeshCentral IS a RMM tool.  Sure, it's not as full featured as, say, a tool like Atera or Tactical, but it is still a RMM platform none the less.  In fact it's even in the very description for MeshCentral: "Connect to your home or office devices from anywhere in the world using MeshCentral, the open source, remote monitoring and management server. "
I, for one, would love to see more RMM type features added to MeshCentral.  I did try Tactical at one point. Frankly, it's way too clunky and difficult to set up and is a bit tough to figure out how to use and make work.  I had tried it before deciding upon Atera instead.  It was easier to just pay for Atera.  Right now I'm  using both MeshCentral and Atera.  I use MeshCerntral because of the extreme ease and immediate connection it allows to the devices I manage.  Atera just fills in the areas that MeshCentral doesn't cover- like managing Windows Updates and more advanced alerting.  I'd LOVE to see these features in MeshCentral though.  I'd dump Atera if they were.  But not at the expense of the convoluted setup and management of something like Tactical.

**Comment by si458** [comment]
@PathfinderNetworks please remember that @Ylianst has other priorities at the moment
https://github.com/Ylianst/MeshCentral/discussions/4795
The won't be any new features this year and maybe next year too,
If u want to implement it yourself and submit PRs then by all means do...

**Comment by silversword411** [comment]
I beg to differ, Mesh is not a RMM tool.

Scheduling, scripting, automation, taking actions on statuses are the job of an RMM.

Mesh is first and foremost a remote access tool: remote control, file transfer, remote terminal, amt etc.

@PathfinderNetworks your post even says why you revert to atera...for all the rmm features you can't find in mesh.

Now not liking tactical is fine, it's definitely not a simple technology to implement. If you want to provide alternatives go for it. Don't criticize people for telling people about a tool that will provide the functionality requested.

Expecting someone else to build more functionality into mesh because you want it at someone else's efforts is inappropriate. Definitely if you want the functionality your options are:
- build it yourself
- pay Ylian a consulting fee for the dev work
- hire someone to build it for you (and optionally commit the efforts back to the project).
Crowd funding is an option too.

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
closing as this will possibly wont be implemented
