### ISSUE TITLE
Using the hotkeys control + c, control + v and etc ...

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#489]
Hello guys,

Can you help me? I'm not able to use shortchut keys i mentioned in the subject, do you have any settings i can use?

**Comment by geanferrani123** [comment]
Follow screen print that i try to do the process

![image](https://user-images.githubusercontent.com/55212206/65042441-38bb4c80-d92f-11e9-895d-531fda01d8fa.png)

Is exactly during remote connection

**Comment by penguinthingie** [comment]
> Follow screen print that i try to do the process
> 
> ![image](https://user-images.githubusercontent.com/55212206/65042441-38bb4c80-d92f-11e9-895d-531fda01d8fa.png)
> 
> Is exactly during remote connection

Are you trying to copy text between your host machine and the remote machine? Have you tried the "Clipboard" button at the bottom of your screen, next to the keyboard shortcuts and "Type" button?

**Comment by geanferrani123** [comment]
No, i am trying copy text between in host machine.

**Comment by MailYouLater** [comment]
<kbd>Ctrl</kbd>+<kbd>C</kbd> & <kbd>Ctrl</kbd>+<kbd>V</kbd> seem to be forwarded to the remote system as expected for me.  I can select some text on the remote computer, press <kbd>Ctrl</kbd>+<kbd>C</kbd>, switch to a different program (also on the remote computer) and press <kbd>Ctrl</kbd>+<kbd>V</kbd>, and it pastes normally.

Note: What @penguinthingie was saying is that the clipboard on your local machine and the clipboard on the remote machine are _not synchronized_.  If you want to copy something from your local machine and paste it on the remote machine (or vice-versa) you need to click the "Clipboard" button, then use the "Get Clipboard" and "Set Clipboard" buttons to retrieve or set the remote computer's clipboard contents.

![image](https://user-images.githubusercontent.com/1279475/65264696-068f2380-dac4-11e9-8392-2eb051c244ba.png)
![image](https://user-images.githubusercontent.com/1279475/65264760-2d4d5a00-dac4-11e9-95a0-5b7fbe9ca1e1.png)

**Comment by Ylianst** [comment]
@MailYouLater Thank you so much for helping with these. This support is very much appreciated.

**Comment by TNQ22** [comment]
[Resolved] - _This is due to enabling the "Fn" and "Ctrl" key swap feature on Lenovo laptops._

I've tried searching but found almost no reports of similar errors.

I'm using the latest version (over Agent). Everything works perfectly except for the issue with the frequently used shortcuts Ctrl-C and Ctrl-V not working. It only sends "v" or "c" to the remote machine.
I also tried "Use Remote Keyboard Map" but nothing changed.

From what I've learned, and as explained by [MailYouLater](https://github.com/MailYouLater) above, it used to work.
Other keyboard shortcuts like Alt-Tab work (in Full Screen mode), except for Ctrl-"".

I only copy and paste content directly on the remote machine (not copying or pasting from the local machine to the remote machine or vice versa - the clipboard feature works in this case).

I'm currently using custom keyboard shortcuts for the Send feature, but it's quite annoying because I have to constantly switch back and forth between them before I can press the Send button.

Thank you for this wonderful project.
