### ISSUE TITLE
Offline installer or Portable version please 

### ISSUE THREAD

**Issue by Rayyyy0** [Ylianst/MeshCentral#4916]
Can you please make an completely  offline installer i want to install MeshCentral on a server that has no internet connection .

is it possible if you can make a portable version for  MeshCentral ? 

*node.js have offline installer i just need MeshCentral 

....thank you

**Comment by supra36** [comment]
I don't understand. Can't you just use another machine to copy node app? This way you can make your own, portable version of mesh.

**Comment by knkumar93** [comment]
> I don't understand. Can't you just use another machine to copy node app? This way you can make your own, portable version of mesh.

Good suggestion. If some detailed steps available as documentation, that will be better. Because, after taking the folder from another installed machine, still we may need to run mesh central as service, which requires meshcentral.js install command. That time, will it try to check dependency again against npm? this area is little unclear.

**Comment by knkumar93** [comment]
It works.

Initially when I installed mesh central in different machine (which has internet access), I have used below commands.
```
node node_modules\meshcentral --install
node node_modules\meshcentral --uninstall
```

When I took this package and placed it in actual machine (which doesn't have internet access), this was not working when I tried to install. It was still expecting the dependencies. Later I realized that I should have used / instead of \ symbol in above command (in internet available machine). After correcting the slashes, it worked fine as offline package.

So below would be the steps:

1. Download and install Mesh Central in a machine which has internet connection.
2. Place the needed configuration (in config.json), sometimes based on configured parameters dependencies will be optionally installed (example mongodb).
3. Open command prompt with Run as Administrator and navigate to downloaded mesh central folder.
4. Execute below command (This is required to download node-windows dependency).

```
node node_modules/meshcentral --install
```
5. Now use below command to uninstall mesh central in this current machine as you no longer need it (it is fine, if you want to keep it installed).
```
node node_modules/meshcentral --uninstall
```
6. Zip the meshcentral parent folder (which has meshcentral-data, node_modules, WinService, package.json, etc., ) and transfer to the machine which doesn't have internet connectivity.
7. Extract the zip file.
8. Open command prompt with Run as Administrator and navigate to the extracted folder.
9. Execute below install command
```
node node_modules/meshcentral --install
```

I have used it in Windows environment, as I am not comfortable working with Linux environment. Feel free to correct if anything wrong in above.

**Comment by KenMunk** [comment]
If you want to create an offline installer a potential idea would be to pack the node installation of meshcentral into a tar file and then run a node installation on your offline machine with that file.

http://www.leanpro.cn/docs/leanrunner/en/shared/npm_offline

I'd have to give this a test before making any assurances though.

**Comment by dinger1986** [comment]
Sounds like it's dealt with @si458
