### ISSUE TITLE
Local devices will not connect to server locally after routing server through NGINX proxy

### ISSUE THREAD

**Issue by iRaven4522** [Ylianst/MeshCentral#4950]
**Describe your issue**
I've recently tunneled a local MC server through an NGINX proxy (run on a cloud VPS - using a WireGuard tunnel to communicate, as my ISP runs a CGNAT) to be able to manage devices when not on the local network. The proxy works well so far. The MC server worked flawlessly before as a lanOnly server managing local devices, however after configuring a proxy no local agent will connect to the server locally.
The local devices used to use multicast to find the MC server IP and connect to it from there, however with any way I've tried (modifying the MeshAgent.msh file to connect to the server's local IP or a modified DNS A/CNAME record with the external domain pointing to the server's local address instead of the proxy's (when discovering with multicast, this was set to "local")).
Additionally, I can access the web interface through the proxy with the correct port 443 like before, however locally I'm only able to access it via HTTP using 8443, even with a local CNAME or A record set to the external domain. This also causes local agents to refuse to connect to the server due to the connection not being HTTPS.

**Screenshots**

Mesh agent failing to connect to server using modified DNS A and/or CNAME record with external domain:
![Clipboard153e](https://user-images.githubusercontent.com/44326347/216023045-d6c9e425-13b8-495a-9cdb-d704b38ff58f.png)

Mesh agent failing to connect to server using multicast discovery method (local) or IP:
![Clipboard158](https://user-images.githubusercontent.com/44326347/216023387-7c591a32-9159-40b2-b1fa-bbb3a9928d45.png)

**Server Software (please complete the following information):**
 - OS: Debian 11
 - Virtualization: N/A
 - Network: LAN
 - Version: 1.1.2
 - Node: 16.19.0

**Client Device (please complete the following information):**
 - Device: Virtual Machine
 - OS: Windows 10
 - Network: Local to MC server
 - Browser: Firefox
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: Virtual Machine
 - OS: Windows 10
 - Network: Local to MC server
 - Current Core Version (if known): N/A

**Your config.json file**
```
{
   "settings": {
      "cert": "backchannel.domain.net",
      "port": 8443,
      "_agentPort": 1337,
      "aliasPort": 443,
      "_mpsport": 44330,
      "_mpsaliasport": 4334,
      "redirport": 800,
      "tlsOffload": "10.1.1.5",
      "_ignoreAgentHashCheck": "10.0.1.0/24",
      "agentAliasDNS": "backchannel.domain.net",
      "agentPong": 300,
      "lanonly": false,
      "_minify": true,
      "localdiscovery": {
         "name": "mesh01",
         "info": "MeshCentral (mesh01)"
      },
      "_authLog": "/home/mesh/auth.log"
   },
   "domains": {
      "": {
         "title": "MeshCentral",
         "footer": "Powered by MeshCentral",
         "newaccounts": false,
         "certUrl": "https://backchannel.domain.net:443/"
      }
   }
}
```

**Comment by nzalev** [comment]
You should post your Nginx configuration, since these kinds of issues can be caused by your proxy config. Additionally, you want to be running in WAN-only mode (this will prevent the server address from being set to "local").

You mention that you have set your DNS record to the server IP instead of the proxy IP. Don't do this. Your server is not listening on port 443. `aliasport` is used to set the port number to a specific value in things like meshagent.msh, when they are served by MeshCentral.

Additionally, `tlsoffload` causes MeshCentral to only serve HTTP traffic and not HTTPS - it is expecting Nginx to terminate the TLS session. This is what is meant by "TLS Offloading". So even if you did send traffic directly to the server, the protocols will not match (client is expecting to use TLS, but server is only serving on plain text).

You can have your internal clients communicate with the external proxy using the public IP and treat MeshCentral as though it's running on a WAN, which is probably the easiest thing to do. (Rather than having the public DNS return a private IP?)

There are a few other ways you could resolve this without hair-pinning traffic from your LAN. Probably the easiest is to spin up a second Nginx proxy on the same server as MeshCentral and give it the same SSL Certificates as your remote proxy. You can then use split DNS to have queries inside your LAN return the internal proxy address and public DNS queries return the IP of the public proxy. This way, both internal and external clients have their TLS connections terminated properly.

**Comment by iRaven4522** [comment]
I use NGINX Proxy Manager which has worked well so far. Here's the configuration I have that works:
![image](https://user-images.githubusercontent.com/44326347/216527128-4b308c2d-1ee5-4955-9227-94bc3f791134.png)
![Clipboard05e](https://user-images.githubusercontent.com/44326347/216527387-35365992-70ec-42a7-aefb-bfcbca1baadf.png)

TIL that aliasPort doesn't actually set MC to actually listen on said port. I noticed this when downloading a new signed copy of the agent where the wss:// url pointed to a set agentPort (which wouldn't have worked in my setup). 

I would have local clients just connect to the external public proxy, however with a somewhat unreliable internet connection this may not work as well as connecting locally and I prefer a local connection where possible to reduce load/connections through the proxy server when it isn't necessary.

Just yesterday I set up a local NGINX proxy (same MC server) with the same certificates/similar configuration as you mentioned and it works really well so far. A modified DNS A/CNAME record pointing to the MC servers IP now works correctly (to no surprise, as it now listens on 443 properly, as like the external proxy with the correct domain name), so if I'm right clients/agents should dynamically switch with the local/external proxy servers when necessary.

Does the certificate on both the local and external proxy servers have to be the same for agents to connect? Back whenever the MC server was local only it used a self-signed certificate (no Let's Encrypt/other service) and agents had no problem connecting with it, regardless of certificate CN, as MC used multicast to announce it's local IP to local agents for them to discover/connect.

**Comment by nzalev** [comment]
I am glad it is working.


> TIL that aliasPort doesn't actually set MC to actually listen on said port. I noticed this when downloading a new signed copy of the agent where the wss:// url pointed to a set agentPort (which wouldn't have worked in my setup).

Correct. The ports MeshCentral listens on are determined by the `port` and `agentPort` json keys. `aliasPort` and `agentAliasPort` set the port number in the config of things which are expected to connect to MeshCentral (like agents) when there is a reverse proxy. This way, if your server listens on 8443 (`port`), agents still know to connect to the reverse proxy on 443 (`aliasPort`).

> Does the certificate on both the local and external proxy servers have to be the same for agents to connect? 

The SSL Certificates on the proxies do not need to be the same, but they should be valid. If you are using LetsEncrypt then there are some logistical problems that can make it harder to have both servers obtain certs independently, so it will likely be easier to just sync the certificates with a cron job.

**Comment by iRaven4522** [comment]
Got it, thanks so much for your help!
