### ISSUE TITLE
Need help in meshcore.js file to use external modules

### ISSUE THREAD

**Issue by nodminger** [Ylianst/MeshCentral#5059]
I have installed NPM modules, such as MySQL, in the Meshcentral project, but I am unable to use them in the **meshcore.js** file located in the 'agent' folder. I tried using 'var mysql = require('mysql')'. All the external modules are only functioning outside the 'agent' folder.

**Comment by nzalev** [comment]
What are you trying to do with the mesh core file?

The Mesh core files are sent to the MeshAgent, which uses [DukTape](https://duktape.org/) to execute them.

So if you install modules at the server (in the Meshcentral project), there would be no access to them because the mesh core files are executed by the Agent.

**Comment by nodminger** [comment]
Thank you for your response. I would like to use MySQL to retrieve data from a database via Meshconsole. Is it possible to install the MySQL npm module in the Duktape engine?

**Comment by jsastriawan** [comment]
Duktape may not be compatible to typical NodeJS library. 

I would recommend to use Meshcentral relay capability to connect to MySql at the device. You could initiate TCP connection relay using a json command over control.ashx and then establish a websocket relay to a target TCP port at device. You can then use nodejs mysql library to connect via that webrelay. See mc2router-electron in my repo to see how it is done.

**Comment by nodminger** [comment]
Sure, I will look into it.
