### ISSUE TITLE
create login token (Embedding MeshCentral)

### ISSUE THREAD

**Issue by GreenAir** [Ylianst/MeshCentral#51]
I can make a token with '--logintoken' and extract the token key with '--logintokenkey'.

But how do I use the key to create a valid token, do I have to implement 'encodeCookie' method on the business server?

Would be nice if I could just make a REST call from the business server to MeshCentral to get a token:
?user=admin&password=1234

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.4-y. You can now do "?user=admin&pass=1234". However placing credentials in the URL is probably not secure and not advisable. There is a good chance that URL's will be logged and now, you get everyone's passwords in your logs. The best is to implement your own "encodeCookie" in your business server and have a pre-shared key that only the two servers know. You also want to keep the server clocks in sync because the login cookies are time limited.

Regardless, feel free to use what makes sense for your situation.

**Comment by Ylianst** [comment]
I will close this one. Feel free to open again if there are any issues.
