### ISSUE TITLE
Performing Authentication Over Websocket via C#

### ISSUE THREAD

**Issue by sourcex** [Ylianst/MeshCentral#510]
I'm attempting to follow the pattern of mc2router to connect to MeshCentral over a websocket connection from C#.  I'm able to connect, but getting the message:
> {"action":"close","cause":"noauth","msg":"noauth-4"}

Am I correct in interpreting mc2router as sending the authentication info as a part of every http(s) request in the body instead of how I'm specifying the credentials?

Here is my code:
`       
     
            var uri = new Uri(url);
            var websocket = new ClientWebSocket();
            websocket.Options.Credentials = new NetworkCredential(username, password);
            await websocket.ConnectAsync(uri, CancellationToken.None);
            var msg = "{ \"action\": \"nodes\" }";
            var bytesToSend = new ArraySegment<byte>(Encoding.UTF8.GetBytes(msg));

            await websocket.SendAsync(bytesToSend, WebSocketMessageType.Text, true, CancellationToken.None);
            ArraySegment<byte> bytesReceived = new ArraySegment<byte>(new byte[1024]);
            WebSocketReceiveResult result = await websocket.ReceiveAsync(bytesReceived, CancellationToken.None);
            Console.WriteLine(Encoding.UTF8.GetString(bytesReceived.Array, 0, result.Count));`

**Comment by Ylianst** [comment]
So, you are connecting a web socket. Once connected, you will be able to send/receive a lot of data before closing it, so you only need to authenticate once. You need to add the following header to your web socket HTTP request:

`x-meshauth: Base64Encode(user) + "," + Base64Encode(pass) + "," + Base64Encode(token)`

Note that the token is optional, it's for 2 factor authentication. You can't use "websocket.Options.Credentials".

You can also use the "MeshCentralRouter.cs" file to do the connection for you. In that found, I implement my own web socket code since event with .NET 4.x, you need Windows 8 or higher for web socket support. I also get to do my own HTTP proxy code.

Hope it helps,
Ylian

**Comment by sourcex** [comment]
Thank you- That's perfect.  I set the header and got a successful connection with my existing code.  I don't see anything in the .NET ClientWebSocket that let's me do server certificate pinning.  I'll test to make sure it is validating that I have a valid certificate for the specified hostname before proceeding and use MeshCentralRouter if I find it lacking.  My code above is purely a PoC.
