### ISSUE TITLE
Device groups show up after delete when restarting the server

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#512]
Hello Ylianst, Good Morning!

I am noticing that when i restart meshcentral, the groups i delete appear again, can you help me?

**Comment by darryl-h** [comment]
The only way I've been able to reproduce this was with odd NeDB permissions issues like so:

OS: Ubuntu 18x
MeshCentral Version: 0.4.1-j

1) Start meshcentral (*.db files are owned by correct user)
2) Create group (call it test123)
3) change permissions on DB (chown root:root *.db)
4) Delete group, observe "Delete Group" confirmation popup, and observe that functionally the group is gone.
5) Reset permissions to correct user (chown meshcentral:meshcentral *.db)
6) Restart meshcentral
7) Observe that the group test123 has returned

NOTE: No error is generated in mesherrors.txt when this write attempt in step 4 fails.

@geanferrani123 You may want to ensure that you have the correct access to the database (Before and after you delete the group, if your using the default DB, check the file permissions, if not, you may have to examine the actual database to see if the entry exists or not)

**Comment by geanferrani123** [comment]
i am using MongoDB, my version of ubuntu is the 18.x, Should I perform the procedure you mentioned?

**Comment by Ylianst** [comment]
When you delete a device group, MeshCentral will just mark it for deletion but will not remove it from the database. in the future, if a device connects to this deleted group, the group is "undeleted" and the device will show up in your account. Make sure to uninstall the MeshAgent.exe from group devices before you delete the device group.

I had to do this because users would delete groups and device would then connect and would not know to which account they belong.

There is a hidden "uninstallagent" command in the device agent console you can use to uninstall.

Hope this helps,
Ylian

**Comment by geanferrani123** [comment]
Got it, could you tell me where I find this hidden command?

**Comment by Ylianst** [comment]
The hidden command is in the agent "console" tab.

![x](https://user-images.githubusercontent.com/1319013/65800067-68860380-e12a-11e9-8790-b2b7142ca91e.png)

**Comment by geanferrani123** [comment]
Oh right, thank you!
