### ISSUE TITLE
"Desktop" remote tab does not appear in meshcentral

### ISSUE THREAD

**Issue by routerino** [Ylianst/MeshCentral#524]
**Affected Clients**: Ubuntu 18.04 LTS server, Raspbian Lite Buster
**Server Version:**: 0.4.1-q

There appears to be an issue where if I restart any of my linux kiosk clients, the desktop tab doesn't come back (as if the meshagent believes the client is running headless). This might be indirectly due to the fact that I start x on user login (who auto logs in on startup) as opposed to a system service. I believe there is a race condition where if the meshagent starts before the x server starts, it never bothers checking for the x session.

I can go into the terminal and manually restart the meshagent service and this fixes it. However, doing that after every restart manually is cumbersome. Shouldn't the meshagent periodically check if a x session is avialable and attach to it?

**Comment by Ylianst** [comment]
One thing to take a look at is to type "info" in the agent console. It will show you if X11 is detected. Can you give it a try and see if that values starts false and changes to true? The problem now is that we look at this value fairly early and only re-check every 20 minutes.

![MC2-X11](https://user-images.githubusercontent.com/1319013/66084870-89809700-e524-11e9-8d10-f3ac3a7f1ec3.png)

**Comment by routerino** [comment]
Thanks for the quick response,
I've restarted my raspberry pi, at let it sit for 30 mins, still hasn't shown the desktop tab:
![image](https://user-images.githubusercontent.com/45954722/66086827-ba121080-e5b8-11e9-804e-6bf5a540a3cf.png)

what the console says:
![image](https://user-images.githubusercontent.com/45954722/66086865-d8780c00-e5b8-11e9-8f55-04ebb847f868.png)

restarting the service after this test did bring back the desktop tab (as expected).

**Comment by MailYouLater** [comment]
Can you see what happens if you use "Soft disconnect agent" or "Hard disconnect agent" options under "Agent Action", and if neither of those works, what happens if you first use the "Clear the core" option, then one of those?
![image](https://user-images.githubusercontent.com/1279475/66091347-3e727e00-e53c-11e9-86ea-f87ce9bbf488.png)

**Comment by routerino** [comment]
Soft Disconnect: No change
Hard Disconnect: No change
Clear core and soft disconnect: takes a little while, but does fix the problem
Clear core and hard disconnect: did not test, but assuming same result as soft disconnect

**Comment by krayon007** [comment]
Currently the agent does not try to redetect X. It checks once and then caches the result, so that it doesn't need to poke the OS again, as I didn't anticipate the configuration changing.

Are you saying you start X on user login ? Do you stop it when the user logs out? If so, I can try to watch dbus for login/logoff events and recheck, rather then periodically polling, because I don't want to show the desktop tab if X was stopped, as then it may appear to the user as being broken.

**Comment by routerino** [comment]
> 
> 
> Currently the agent does not try to redetect X. It checks once and then caches the result, so that it doesn't need to poke the OS again, as I didn't anticipate the configuration changing.
> 
> Are you saying you start X on user login ? Do you stop it when the user logs out? If so, I can try to watch dbus for login/logoff events and recheck, rather then periodically polling, because I don't want to show the desktop tab if X was stopped, as then it may appear to the user as being broken.

Currently I am setting up kiosks using [this script I wrote](https://github.com/routerino/Install-Kiosk). 

Getty auto logs in the kiosk user, and then the kiosk user starts x in the .bash_profile script upon login:
`if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    startx
fi`

I would just literally restart the meshagent at this stage, but this is all running in (non-privelaged) user context, so that profile can't restart the service.

The user never logs out, it's just a very locked down kiosk environment that behaves as either a RDP thin client or a locked down web client. There is no desktop environment, it just launches the desired application full screen and auto relaunches if it closes.

**Comment by routerino** [comment]
Alright, I've added a command to the affected kiosks:
`mkdir /etc/systemd/system/meshagent.service.d; echo -e "[Service]\nExecStartPre=/bin/sleep 30" > /etc/systemd/system/meshagent.service.d/override.conf`

which solves the problem for now. it's a bit of a hack solution, but a 30 second delay on the agent isn't really an issue to me. I can think of other scenarios where the x session may not start immediately (or crash?) so maybe this should be a low priority fix for the future?

**Comment by krayon007** [comment]
I'll do some testing. I know normally if X crashes, the user is kicked out of the local session, so I'll see if that is captured in dbus. If so, it may be best for me to watch dbus for login/logoff events and to recheck for the presence of X at that time.

**Comment by MailYouLater** [comment]
Is it possible to see in (e.g. in dbus) when a process starts or stops? Could you maybe see when the X11 server launches and/or dies?
Also, would it be possible to keep the "Desktop" tab without X11, capturing the framebuffer (`/dev/fb0`) when there's no GUI?

**Comment by Hemmingen** [comment]
This issue still exists on Raspbian Buster as of today. Can we provide any further information to help fix the agent? Thanks for your work. (For now I reupload the core everytime I need to access the desktop.)

**Comment by routerino** [comment]
I am still having this issue as well. Unlike before, cannot get the desktop tab to load in any circumstance.

To give you context, I install raspbian as per normal. I then change to CLI mode (via raspbian config), and set X to start on login. This is because I have the PI launch a custom i3wm environment, not PIXEL.

No matter how often I reupload the core, I still do not get the desktop. I suspect that maybe the meshagent has a hardcoded check for raspbian's CLI mode, and doesn't bother checking after that.

**Comment by krayon007** [comment]
I'll have to do some digging to try to solve this one... The issue is that I normally only check the presence of the X on startup, becuase it normally doesn't change... A while ago somebody had a scenario where X was loaded only on login, so suggested I could watch for login/logoff events, and do the check there...

However, I know on the raspberry pi that we have, none of those images have dbus, which is what I use to watch for login/logoff events... So I'll have to figure out a better way to figure out on those platforms... I'm open to suggestions...

**Comment by routerino** [comment]
so, just to be clear (at least in my circumstance) X will not load, even if I restart the meshagent service. So it's not just the startup check that's causing me issues. I'll see if I can create a reproducible scenario for you.

Aside from that, is it not possible to parse the list of processes and just look for Xorg periodically?

**Comment by krayon007** [comment]
Yeah, I can periodically check, I was just hoping to avoid polling... But I suppose if I only do that if I can't connect to dbus, and I can't find an X instance at startup, should be an ok case...

But yeah, if you restarted the agent after X was loaded, and it still didn't work, then I'll have to investigate that. On the console tab, is X11 support being reported as false?

What happens if you run the following command from the mesh folder?

./meshagent -exec "console.log(JSON.stringify(require('monitor-info').getLibInfo('libX11'),null,1));process.exit();"

**Comment by routerino** [comment]
Output is the following:
[
 {
  "lib": "libX11.so.6",
  "path": "/usr/lib/i386-linux-gnu/libX11.so.6",
  "hwcap": "0",
  "libc": "libc6"
 },
 {
  "lib": "libX11.so",
  "path": "/usr/lib/i386-linux-gnu/libX11.so",
  "hwcap": "0",
  "libc": "libc6"
 }
]

Actually, on running this, I realized that this particular unit is not a pi. It's an x86 computer running raspbian 10. I'm going to see if I can recreate this same fault on a pi set up the same way.

**Comment by krayon007** [comment]
Do you have a link to where I can get raspbian 10? If I can set it up in a VM, maybe I can try to recreate this issue and figure out a solution...

**Comment by routerino** [comment]
Hi Krayon007,

You can download here:
https://www.raspberrypi.org/downloads/raspberry-pi-desktop/

I use it in situations where there is existing hardware, or a pi isn't appropriate for some reason (so I don't have to create my scripts for two separate distros).

I have just tested on a raspberry pi 2 using the same config. It does not bring up desktop initially, but a meshagent restart fixes it on the pi. Meaning that this is a raspbian 10 specific issue. Let me see if a stock standard raspbian 10 install has the same problem.

**Comment by routerino** [comment]
@krayon007 , did you have a chance to test raspbian yourself? If you just want to write it off as a not-supported distro, I can work around that, but it'll be good to know.

**Comment by krayon007** [comment]
I got the Raspian 10 x86 VM working. X on the vanilla build seems to run the same as all the other distros, so KVM worked fine. But I did update my dbus parser so that it can read system events, as on the Raspian 10 system, I found a system dbus signal that I can use to detect log on and log off, so that I can check for the presence of the X server on those signals. 

I'm going to test it on other distros, as the signal/interface name looks generic such that it may work on other distros too... The dbus change requires an agent update, but we're planning on that anyways, since the next agent update has remote cursor rendering support for Linux and FreeBSD.

Once that agent is updated, I can make the necessary javascript changes to hook the signal, and work the magic that needs to be done.

By any chance are you able to share how you modified your Raspian 10 image to not start X until client logon? If you can, that will enable me to test that my proposed dbus solution actually works for that case.

**Comment by krayon007** [comment]
By the way, what issues were you seeing with Raspian Desktop? When I setup the VM, it seemed to work with Mesh Central out of the box...

**Comment by routerino** [comment]
Hi @krayon007 . Just to make sure I'm not going crazy, I've created a fresh vm myself. Steps I've followed:

- Created Gen1 Hyper V VM in windows
- Installed raspbian x86 (buster)
- Set locale to australia/melbourne in initial setup
- skip update
- enable ssh
- Install meshcentral

At this stage, I can't even get the agent to appear in meshcentral. I've tried both my self hosted instance and meshcentral.com. systemctl status shows an error (203?)

![image](https://user-images.githubusercontent.com/45954722/78306153-6647aa80-758e-11ea-849f-7a1c873b420e.png)

**Comment by krayon007** [comment]
That's interesting... The only difference between your VM and mine, is that I used VMWare instead of HyperV, and I did not set the locale.

That 203 exit code is interesting, that means that exec failed because a file was not found. I'd be curious to know what it was trying to exec that it couldn't find.  IIRC, the only thing it should be trying to exec is /bin/sh

If you open a terminal, and go to the installed folder where the agent is, and run the agent in console mode, and let me know if it exits the same way? To run it in console mode, just directly execute the meshagent binary, from the installed folder. 

I'm not sure if my use of VMWare vs HyperV makes any difference, and I really doubt the locale makes a difference...

I'll do a quick test with the install script on raspian desktop, as I didn't use that to install the agent, I used my new installer to do it (which is included in the latest agent, but I don't think it was released yet)

Is there an msh and db file in the agent install folder? I want to try to determine if the agent ran, but exited with code 203, or if the install failed, and systemd is actually returning a 203.

**Comment by krayon007** [comment]
Nevermind, I reproduced your scenario... It happens when I use the install script... I'll try to see if I can figure out what happened...

**Comment by krayon007** [comment]
ok, I figured it out... The script detected Raspian 10 as 64 bit, and tried to install the 64bit agent instead of the 32 bit agent...

**Comment by krayon007** [comment]
It's wierd that with Raspian 10, uname -m returns x86-64 on my VM, but on other 32 bit distros it does not.

**Comment by routerino** [comment]
That is weird. I actually did think it was 64 bit. uname -a even says it's a 64 bit kernel.

**Comment by routerino** [comment]
@krayon007 , I can confirm that manually installing the 32 bit agent does solve the problem (albeit we're still back at the "initializing display too late" issue, which I've since solved by putting a delay in starting the service).

So if you're curious, this is the remaining steps to get my running environment:

- Start menu --> accessories --> raspberry pi configuration --> Boot: To CLI
- apt update && apt install i3
- create a .bash_profile script that runs the following:
`if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    startx
fi`
- create a .xinitrc script that runs the following: `exec i3`
- Reboot
- Create a root user and demote sudo from the pi user

So on boot, the machine automatically logs into the "pi" account, then starts x, and then runs the i3 window manager (which I then config to lock down and run a full screen display, whether that be a browser, RDP windows, etc.).

**Comment by krayon007** [comment]
I fixed the install script, so when it detects 64 bit, like Raspian 10 did, it also checks LONG_BIT on the platform. Raspian 10 has LONG_BIT set to 32, as well as other actual 32 bit distros...

**Comment by krayon007** [comment]
I just updated the KVM detection logic on linux, so if it detected the X11 libraries on the platform, but cannot find the X server, it will retry every 10 seconds for up to 3 minutes. I also made it emit an event when it does find it, so now the agent will update the server as soon as KVM support is detected.... This feature should be live when the linux agent is next updated, which should be soon.

**Comment by krayon007** [comment]
As a side note, I noticed this issue happens when I rebooted some of my linux machines... On some of my machines, the agent comes up really early, while the machine was still in text mode, before the graphical desktop appeared... That means it probably couldn't find the X server, because it wasn't started yet... And the results were cached, so it never tried again.... So I fixed all that...

**Comment by krayon007** [comment]
The change is live in Mesh Central v0.5.14
It currently will retry for up to 3 minutes, before giving up. If this isn't sufficient, let me know... I can put a filesystem watcher on utmp, which gets modified on login/logoff, and retry at that time as well...

**Comment by Hemmingen** [comment]
My problems are fixed. Thank you :)
