### ISSUE TITLE
agent features: "Run after reboot", "change the UI language",...

### ISSUE THREAD

**Issue by jalil1408** [Ylianst/MeshCentral#5266]
- a "Run after reboot" checkbox to run the agent after the OS rebooted 
- change the UI language
- customize the "Click the buttons below to install or uninstall the mesh agent..." text or change it when in the interactive mode (no installation)

**Comment by si458** [comment]
> * a "Run after reboot" checkbox to run the agent after the OS rebooted

you install the 'meshagent' instead of using the 'mesh assistant' and run it as admin and this install the background service

> * change the UI language

you can change the UI language on the website by clicking the 'Welcome (USER)' on the top right then clicking 'Localization Settings', set you language then refreshing the webpage

> * customize the "Click the buttons below to install or uninstall the mesh agent..." text or change it when in the interactive mode (no installation)

the is already a bit of customization for the agent - https://www.youtube.com/watch?v=xUZ1w9RSKpQ
