### ISSUE TITLE
client not shown after install meshagent

### ISSUE THREAD

**Issue by changchichung** [Ylianst/MeshCentral#53]
I just install a meshcentral2 server .
here is the server info
![](https://i.imgur.com/MbnRkWf.png)

install and start meshagent service in client
![](http://i.imgur.com/wgVPEBs.png)
But I can not find any agent in "my devices"
both server and client were reboot

any suggestions ? I see no log in client , and no error log in server

**Comment by jsastriawan** [comment]
First thing:
- is your server address/FQDN resolvable to IP address?
- is there any log message on meshagent folder?
- is there any connection made to meshcentral server?

Other method of debugging, please add --debug when starting the server?

**Comment by Ylianst** [comment]
A common problem is that the server name is not set right and so, agents try to connect back to the server and the name does not resolve. If you used "--cert (servername)" or used "cert" in the settings section of the config.json, or used the Windows installer, please check it and change it to a valid name.

Another way to see what is going on it to run the MeshAgent manually.

- On windows, open a command prompt and go into "program files\meshagent" and run "MeshAgent.exe run".
- On Linux, stop the service or agent process, go in /user/local/mesh and run the agent as root.

In both cases, you will see exactly what the agent is doing and it should be pretty obvious what is going on. Hope it helps. Please send more information if it still does not work.

**Comment by changchichung** [comment]
thanks , I solve the problem now.

**Comment by si458** [comment]
@pvssrikanth that message basically means MeshAgent could start because it is already being run in the background as a service
you need top exit the terminal window and control MeshAgent from the windows services, by restarting the MeshAgent

**Comment by pvssrikanth** [comment]
Hi sir,
As per you suggestion i stopped closed the terminal and restarted the meshagent from windows services restarted,
It started however the agent is still not showing on meshcentral dashboard server running on ubuntu.
since i am running as docker in ubuntu 
Is it a must to create sample.json configuration file and then run in docker ?
I am just executing this command in terminal 
sudo docker run -p 80:80 -p 443:443 [ghcr.io/gurucomputing/meshcentral-docker](http://ghcr.io/gurucomputing/meshcentral-docker)
and installed agent in windows and restarted the meshagent service but its NOT shown on dashboard meshcentral.

Please guide 

Thanks 
pvssrikanth

**Comment by si458** [comment]
@pvssrikanth yes you need a config.json of some more,
so you can use the is sample-config.json to get you started, 
but that will only work in LAN mode, with devices on the same network as your meshcentral server to connect
you should check out the docs to help you
https://ylianst.github.io/MeshCentral/meshcentral/
