### ISSUE TITLE
PUP/RnkBend -> RemoteAdmin.Win32 by Virustotal.com - we use Panda not possible to install...

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#545]
good morning - https://www.virustotal.com/gui/file/30d94433762827d8ad7ed2b3a48e20ef51d9fe442bd9e69a398ce8e82f5b4b4d/detection i know - not a virus - but panda adaptive devense, Trendmicro and Kaspersky clean the client bevor setup... when i stop the av engine and setup - at the time when i start the av engine it cleans everything... i have setup in panda that the folder are not controlled.... cleans also... any idea?

thanks a lot and best regards

am

**Comment by PathfinderNetworks** [comment]
I suspect this happens because the agent installer is using a self signed certificate- so Windows and antivirus apps automatically don't trust it.  I know, at least for Avast CloudCare, it flags the installer every time I try to run it.  I have to disable CloudCare briefly for the installer to run.  Then, once it's installed, I can turn Avast back on and the exceptions I have in place will allow the Mesh agent to run without being removed.  I know, for certain, Avast is flagging the installer with its File Reputation scanner.  If the installer were signed with a valid certificate then I think Avast (and others) would allow it.

**Comment by Ylianst** [comment]
In the past I used to sign the agent and my certificate got revoked because [virustotal.com](https://www.virustotal.com) reported that I was signing malware. So, I could sign it again using a real certificate, but I could get revoked again. If it gets revoked, Microsoft auto-removes the agent for computers causing a huge problem. So, I am not tempted to sign the agent with a real certificate anymore. I would sign other executable that [virustotal.com](https://www.virustotal.com) shows as completely ok.

**Comment by PathfinderNetworks** [comment]
If there is a possibility, even if remote, of the agent being removed by Windows- then definitely we can't go down that road.  For obvious reasons.  ;-)  The agent installer being unsigned, at least for me, is just a nuisance- but not something I can't work around fairly simply. Really, the worst part about it is the popup from Microsoft stating the program may not be safe.  It looks bad when having a user install the agent on their own device.

**Comment by Ylianst** [comment]
Agreed. One thing I could look into is allowing others to sign the agent for their own server but, the agent would be signed to only connect back to the signer's server so the agent could not be used generically. This way, important organizations could get their own cert and sign the agent.

**Comment by MailYouLater** [comment]
@Ylianst: Can't any user who wants to spend the time, money & effort to get a cert already sign the agent and place it where the MeshCentral server will see it, then all computers using the agent will be automatically updated to use that signed version?
While I can see why you might think programming something into the agent that prevents it from connecting to arbitrary servers when signed by someone specific is a good idea, I'm not sure it's feasible, as you'd have to come up with a way of doing so without tying the code signing cert directly to the cert of the webserver, as generally, people who have a cert that qualifies under Microsoft's new rules for code-signing won't have it associated with whatever server they plan to run MeshCentral on, but rather they're main customer-facing website.

**Comment by Ylianst** [comment]
So yes, anyone can sign the agent an place it in the /node_modules/meshcentral/agents folder. In fact, that folder contains the unsigned agent, so it's easy to sign it. Of course, if someone where to do this, anyone else could possibly download their signed agent and put it in their own MeshCentral server for their own use. I imagine users would expect a agent signed by "XYZ Corp" to only be used for connecting to "XYZ Corp" servers. The code signing cert would not be tied to the TLS cert on the web site, but one would imagine you would have to sign an agent with a hard coded target server.

**Comment by MailYouLater** [comment]
I guess that makes sense, though it would be nice to not have to individually sign the exe for each & every server if your using MeshCentral in multiple capacities. (e.g. for your company's own devices, and for other customer's devices.) Perhaps there should be a way to add a list of several domains (should wildcard subdomains be allowed?) to allow before signing.

**Comment by dinger1986** [comment]
detected as virus isnt anything new @si458 maybe needs added to docs but can close

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
the is a video explaining the new code-signing method which happens when you first start meshcentral or customise it
https://ylianst.github.io/MeshCentral/meshcentral/codesigning/
but sadly the is NOTHING we can do about public antiviruses deleting the exe because they think its a virus!
you just have to keep reporting your exes to them as a false positive!
