### ISSUE TITLE
Question: MeshCommander setup.bin editor; possible values for Manageability Feature Selection

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#557]
Hey guys,

I created a setup.bin file for AMT provisioning via USB key and it works fine with one exception:
The "KVM Remote Port" and "Redirection Port" features are not enabled.

I suppose that one needs to add the "Manageability Feature Selection" variable in the setup.bin profile, but it accepts only a string instead of offering a selection list and I was unable to find documentation on this topic.

The desired configuration is all features enabled (Redirection Port, KVM Remote Desktop, IDE-Redirection, Serial-over-LAN). What is the correct value for this setting? Is there documentation available?

Thanks in advance and best regards,
// Veit

**Comment by Ylianst** [comment]
Good request, I need to look into this.

**Comment by Ylianst** [comment]
Just uploaded an updated MeshCommander v0.7.9 with improved setup.bin editor. [You can get it here](https://www.meshcommander.com/meshcommander). Because I did not change the version number, you will need to uninstall/download/install this new MeshCommander.

I get my documentation about the setup.bin format from the "usbfile.exe" source code in the Intel AMT SDK. I added the "Manageability Feature Selection" which can only be set to "Intel AMT" and improved the "SOL/IDER Redirection Configuration". Hopefully this should now work. FYI. I am traveling a lot in the next 3 weeks. Hope this helps.

![MeshCommander-ImprovedSetupBinEditor](https://user-images.githubusercontent.com/1319013/67641681-2f73b700-f8c1-11e9-813a-11aeab75f25a.png)

**Comment by Ylianst** [comment]
Closing this as I am pretty sure it's fixed. Open a new issue if needed.
