### ISSUE TITLE
Telegram 2FA bug, when connection drops and comes back

### ISSUE THREAD

**Issue by mikeleblank** [Ylianst/MeshCentral#5587]
The moment I lose the Telegram service it tries to send me a notification and it remains in a queue, when the service returns it does not send it. The login 2FA is not sent until restarting.

In this case it is resolved by restarting the meshcentral server or service.

**Comment by si458** [comment]
ok found a work around for you to try
the is a hidden value for telegram which isnt documented (will add it in)
`connectionRetries` which is a default value of 5 retries, every 1 second (so only tries for 5 seconds then gives up)
set `connectionRetries` to a high value say 60 (this should retry every 1 seconds for 60 seconds)
you can set it to a higher value but the docs recommend against this!
https://gram.js.org/beta/interfaces/client.telegramBaseClient.TelegramClientParams.html#connectionRetries

might also add another value `retryDelay` into the `config.json` which will allow you to try specify how often to try reconnecting rather than every 1 second by default!
https://gram.js.org/beta/interfaces/client.telegramBaseClient.TelegramClientParams.html#retryDelay

**Comment by mikeleblank** [comment]
I don't have the error log, I checked and I have the path "meshErrorLogPath" set correctly. If I have the login logs

Activate error logs to see them directly from the mesh, when it happens again I will review it.

**Comment by mikeleblank** [comment]
> ok found a work around for you to try the is a hidden value for telegram which isnt documented (will add it in) `connectionRetries` which is a default value of 5 retries, every 1 second (so only tries for 5 seconds then gives up) set `connectionRetries` to a high value say 60 (this should retry every 1 seconds for 60 seconds) you can set it to a higher value but the docs recommend against this! https://gram.js.org/beta/interfaces/client.telegramBaseClient.TelegramClientParams.html#connectionRetries
> 
> might also add another value `retryDelay` into the `config.json` which will allow you to try specify how often to try reconnecting rather than every 1 second by default! https://gram.js.org/beta/interfaces/client.telegramBaseClient.TelegramClientParams.html#retryDelay

I test and report

**Comment by si458** [comment]
OOO just re-read the docs 
**How many times the reconnection should retry, either on the initial connection or when Telegram disconnects us.
May be set to a negative or undefined value for infinite retries, but this is not recommended, since the program can get stuck in an infinite loop. defaults to 5**
you should be able to set the value of `connectionRetries` to say `-1` and it will always retry

**Comment by mikeleblank** [comment]
> OOO just re-read the docs **How many times the reconnection should retry, either on the initial connection or when Telegram disconnects us. May be set to a negative or undefined value for infinite retries, but this is not recommended, since the program can get stuck in an infinite loop. defaults to 5** you should be able to set the value of `connectionRetries` to say `-1` and it will always retry

i set value -1 but service telegram bot not started

**Comment by si458** [comment]
> > OOO just re-read the docs **How many times the reconnection should retry, either on the initial connection or when Telegram disconnects us. May be set to a negative or undefined value for infinite retries, but this is not recommended, since the program can get stuck in an infinite loop. defaults to 5** you should be able to set the value of `connectionRetries` to say `-1` and it will always retry
> 
> i set value -1 but service telegram bot not started

bummer! what about a high value then like say 300 (which would be 300 sec/5mins) ?

**Comment by mikeleblank** [comment]
"messaging": {
    "telegram": {
      "apiid": XX,
      "apihash": "XX",
      "bottoken": "XX",
      "connectionRetries": 6000,
      "retryDelay":3000
    }
  }
  
  working perfectly
