### ISSUE TITLE
Server crash in 1.1.16 with sessionRecording option enabled

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#5595]
**Describe the bug**
I suspect this is due to the included session recordings. In the process of studying the problem, I want to check different settings on different versions.
The config looks like this:

```
       "sessionRecording": {
         "index": true
         "maxRecordingDays": 90,
         "protocols": [1,2,5]
       }
```

**To Reproduce**
1. Update to version 1.1.16
2. Connect to any computer (Desktop for sure) and disconnect. Server crashes after session disconnected
3. An error appears in the mesherrors.txt file
```
-------- 11/30/2023, 5:51:08 AM ---- 1.1.16 --------

/root/node_modules/meshcentral/mcrec.js:16
function log2() { if (directRun) { console.log(...arguments); } else { process.send(...arguments); } /*else { if (worker != null) { worker.parentPort.postMessage({ msg: arguments[0] }); } } */ }
                                                                                ^

TypeError: process.send is not a function
     at log2 (/root/node_modules/meshcentral/mcrec.js:16:80)
     at /root/node_modules/meshcentral/mcrec.js:68:17
     at /root/node_modules/graceful-fs/graceful-fs.js:61:14
     at FSReqCallback.oncomplete (node:fs:198:23)
```
4. Comment out the "_sessionRecording" settings section, the server no longer crashes.
5. Rolling back to version 1.1.15 also solves the problem without commenting "sessionRecording"

**Server Software (please complete the following information):**
 - OS: Debian 11
 - Virtualization: No
 - Network: Hybrid (LAN + WAN) mode, reverse proxy Nginx, ssl offloed on proxy
 - Version: 1.1.16
 - Node: 18.16.1

**Client Device (please complete the following information):**
 - Device: Windows 10
 - OS: [e.g. Ubuntu]
 - Network: Remote over WAN
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: any
 - OS: any Windows (Linux not checked)
 - Network: Remote over WAN
 - Current Core Version (if known): Dec 9 2022, 200256441

**Comment by si458** [comment]
`
The process.send() method is an inbuilt application programming interface of the process module which is used by the child process to communicate with the parent process. This method does not work for the root process because it does not have any parent process.
`
so it thinks the parent process `meshaccelerator.js` didnt call the `mcrec.js` but it was called directly?

**Comment by fernandogobah** [comment]
are you using the meshcentral as a service /etc/system.d/system/meshcentral.service?
yes, following file.
[Unit]
Description=MeshCentral Server

[Service]
Type=simple
LimitNOFILE=1000000
ExecStart=/usr/bin/node /opt/node_modules/meshcentral
WorkingDirectory=/opt
Environment=NODE_ENV=production
User=mesh
Group=mesh
Restart=always
# Restart service after 10 seconds if node service crashes
RestartSec=10
# Set port permissions capability
AmbientCapabilities=cap_net_bind_service

[Install]
WantedBy=multi-user.target

**Comment by si458** [comment]
Thanks,
I know what the issue is, but I just can't replicate the issue over n over,

Because if we don't use `process.send` then the mcrec.js file which runs the session recording then indexing, won't see the output, so it won't know its finished

A work around is to set `index: false` inside `sessionRecording` so it still does recordings, it just won't do the indexing every 10secs of the file!

**Comment by fernandogobah** [comment]
Just for context, I did a test using docker according to the documentation and the error occurred too.
Reporting the index directive to false resolved the problem temporarily.

**Comment by si458** [comment]
Can u replicate this error every single time at all?

Like do this, do that, wait for so long, use this node version, use this os, connect to this os?

I physically can't duplicate the issue but I know what the issue is and why it's happening, I just need to replicate it so I can fix it properly

**Comment by si458** [comment]
can any of yours share ur config.json file? do you have multiplexer enabled at all?

**Comment by si458** [comment]
are you still having this issue at all?

**Comment by fernandogobah** [comment]
You mentioned not being able to replicate the environment. Can I provide you with access data to my testing environment so that you can evaluate in the best way?
It is an ephemeral environment, so there is no real data or data that can be used for production.
Tell me your email and I will forward you the access data.

**Comment by si458** [comment]
@fernandogobah sure!
my email address should be on my github page
OR
visit my [donation link](https://www.si458.co.uk/2024/01/05/donation/) and leave comment and ill get yours that way 👍

**Comment by si458** [comment]
found the issue! thank you @fernandogobah for dontating a machine that had the issue
if the machine has a single core, it was calling the meshaccelerator directly rather than forking it,
so in turn mcrec.js (the indexer) wasnt a child but part of the parent, so hense the error
ive since removed the checker if its single core and instead let it use the accelerator,
so now it will push the mcrec.js into the background for indexing and carry,
it also means if meshcentral crashed while the indexer is running, meshcentral can restart and carry on while the mcrec will also carry on, and not corrupt the mcrec files !
