### ISSUE TITLE
multiple active sessions in mc -> and a overview for open sessions...

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#566]
why is a connected desktop disconnected if you want to remotely service another computer in between? because we are all technicians and don't like to wait ;-) wouldn't it be helpful if the active session remains open to a computer which is currently doing an avscan while helping another customer with a completely different problem? - but for this you would also need a kind of overview of which sessions are currently active... you could quickly switch back and forth between these 3-6 open sessions...

Translated with www.DeepL.com/Translator

**Comment by PathfinderNetworks** [comment]
You can soft of do this now.  All you have to do is select the devices you want to see (by clicking the check box to the left of the device icon).  Select as many as you want.  Then, in the top right corner of the page, click the right most box (in that line of three boxes).  It is labeled 'Desktops'. 
![desktops](https://user-images.githubusercontent.com/48607498/66709738-83ff2a00-ed38-11e9-9e65-a2e15e33601e.JPG)
Then, under size, select Large (otherwise you probably can't see them).  Then click Conenct All. 
You'll probably also need to click the Settings button and change the quality, scaling, and frame rate to what makes sense for your needs.  I leave mine set at 30% quality, 50% scaling, and slow for frame rate.  Whichever device you want to actively control you just click on.  To go back to the multi-desktop view just click the Back button that is immediately to the left of the device name.  
Hope that all makes sense. This is great for those situations where you have a bunch of devices you are working on (like doing Windows Updates, AV scans, etc) and just have to sit and wait for some task to complete on them.

**Comment by wvt-adm** [comment]
is true - it works, but is anything but comfortable... i would like to leave my question unanswered. why are sessions closed when you switch from one computer to another? is there an option to leave them open / connected?

**Comment by MailYouLater** [comment]
Actually, it's only limiting you to one Desktop session per _window_. So you can hold <kbd>Shift</kbd> while you click one computer and it will open it in a new window, then if you connect to that computer's desktop _inside_ that window, you can <kbd>Shift</kbd>+Click another computer to open it in _another_ new window, and when you connect to its desktop, it won't disconnect you from the first, because it's in a separate window.
![Two desktop sessions open at the same time, in separate windows](https://user-images.githubusercontent.com/1279475/66769656-81045680-ee6a-11e9-8b88-163d2e477e2a.png)
Note: Computer B has a second monitor above the first, that's black in the screenshot, this is not a bug.
