### ISSUE TITLE
Bug in version 0.4.2-p

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#573]
Guys, Good Morning!

I detected that when performing remote access, the connection is not being made, is the same as the screen below:

![image](https://user-images.githubusercontent.com/55212206/66923656-9e1e5e00-efff-11e9-9f1d-6401560cf60e.png)

This happens both for desktop connection as well as for terminal connection and file connection.

**Comment by johnczer** [comment]
I have also verified that this is the case.

**Comment by geanferrani123** [comment]
This print is from my homologation base, is with all original files, so neither it nor my production base works correctly.

**Comment by Ylianst** [comment]
Fixed in MeshCentral v0.4.2-q. I added a new security protection, but the .js files are set to 1 hour cache and so, you got the old script with the new server which caused issues. I renamed the important file to force cache reload. The file that got changed was "agent-redir-ws-0.1.0.js".

Let me know if this works.

**Comment by pmoncho99** [comment]
I just updated and I can confirm it fixed my issue.

**Comment by geanferrani123** [comment]
I will be able to validate only tomorrow, I will update today at the end of the day and see tomorrow the calls of the technicians.

**Comment by johnczer** [comment]
I can confirm that this issue is fixed here as well.

**Comment by Ylianst** [comment]
Thanks. I will close this one. I am pretty sure it's fixed too. Please re-open an issue if you see any problem.
