### ISSUE TITLE
Numlock changes the arrow keys' function in RDP and shouldn't

### ISSUE THREAD

**Issue by sammyke007** [Ylianst/MeshCentral#5732]
**Describe the bug**

Numlock ON changes the behaviour of the "normal" arrow keys while using RDP. That's wrong.
It should keep sending 37, 38, 39, 40 for the arrow keys instead of 98, 100, 102 and 104 (JS keycodes).

**While using Agent Connect** everything works as it should:

Numlock ON:
Up Arrow = Key 38 = Up
Down Arrow = Key 40 = Down
Left Arrow = Key 37 = Left
Right Arrow = Key 39 = Right
Numpad 8 = UnicodeKey 56 = 8
Numpad 2 = UnicodeKey 50 = 2
Numpad 4 = UnicodeKey 52 = 4
Numpad 6 = UnicodeKey 54 = 6

Numlock OFF:
Up Arrow = Key 38 = Up
Down Arrow = Key 40 = Down
Left Arrow = Key 37 = Left
Right Arrow = Key 39 = Right
Numpad 8 = Key 38 = Up
Numpad 2 = Key 40 = Down
Numpad 4 = Key 37 = Left
Numpad 6 = Key 39 = Right

**While using RDP or Web-RDP:**

Numlock ON: 
Arrow keys don't work anymore, they write 2, 4, 6 and 8 instead of up, down, left, right
Numpad works like it should with Numlock ON (numbers)

Numlock OFF:
Arrow keys work (up, down, left, right)
Numpad works like it should with Numlock OFF (arrows, home, end, ...)

This happens both in RDP Connect (via Desktop) and in Web RDP.
This is not a browser issue. Tested on multiple computers, multiple instances, Chrome and Firefox.
I'm using a Belgian AZERTY keyboard. On my remote Windows PC's, Belgian (period) is selected as input language.

**To Reproduce**
Connect with RDP to a remote computer.
Try Arrows and Numpad, toggle Numlock and try again

**Expected behavior**
Numlock status shouldn't change how ArrowKeys are handled.

**Server Software (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Network: Reverse proxy
 - Version: 1.1.19
 - Node: 20.11.0

**Client Device (please complete the following information):**
 - Device: multiple devices
 - OS: Windows
 - Network: ---
 - Browser: Google Chrome
 - MeshCentralRouter Version: ---

**Remote Device (please complete the following information):**
 - Device: multiple devices
 - OS: Windows
 - Network: ---

**Comment by sammyke007** [comment]
I've found in MeshCentral/public/mstsc/keyboard.js that the arrowkeys are mapped to the same keys as the numpad. That's incorrect I guess...

**Comment by si458** [comment]
i will look into this as i confirm the same
NUM LOCK ON, arrow keys type numbers instead of moving
NUM LOCK OFF, arrow keys move as expected

**Comment by si458** [comment]
ok ive found the issue! https://github.com/Ylianst/MeshCentral/blob/c331eca679e2edbb326c283315f19240bd617876/apprelays.js#L1039-L1049

basically IF the key you press is an EXTENDED KEY you need to send 'EXTENDEDKEY' with rdp packet
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/7acaec9f-c8a6-4ee9-87d6-d9b89cf56489?redirectedfrom=MSDN

but this wasnt happening because `sendKeyEventScancode` should have 3 arguments, and the last argument is `extended` (so the code was there to do this but it was just sending every key as a normal key instead)

so, i do need some help...
i need a FULL LIST of keys that we would class as EXTENDED KEYS,
`
 For enhanced 101-key and 102-key keyboards, extended keys include the right ALT and right CTRL keys on the main section of the keyboard; the INS, DEL, HOME, END, PAGE UP, PAGE DOWN and ARROW keys in the clusters to the left of the numeric keypad; and the Divide ("/") and ENTER keys in the numeric keypad.
`
are they just basically saying the usual keys?

**Comment by si458** [comment]
ok all fixed if you wanted to copy+paste and try yourself! before i merge
code was already built into the Remote part to handle extended keys, but not for the RDP part
so just a little bit of copy+paste 👍

**Comment by sammyke007** [comment]
One more question / test. Everytime I start an RDP session with MeshCentral, Numlock is disabled on the remote PC. However when I RDP using Microsoft RDP or Apache Guacamole, Numlock is enabled like configured default on all of my PCs. Can you confirm this?

**Comment by si458** [comment]
I have noticed when I was testing the num lock, sometimes it wouldn't match what was on the remote device by rdp, so I enabled num lock locally, but it would then disable num lock on the remote device and vica versa? It seems as though it doesn't remember the previous state of the num lock when you connect so it gets itself confused, but I think that is for another github bug report rather than this one

**Comment by sammyke007** [comment]
On my host it's always enabled (so it is on my remote) but as soon as I start an RDP from MeshCentral, the remote gets Numlock OFF while my host is still Numlock ON.
Would oyu like me to create a new issue for this? I'm looking into the code where RDP is initialized, but can't seem to find it.

**Comment by si458** [comment]
Yes plz open a separate issue for that, I will look into it tomorrow :)
