### ISSUE TITLE
@ylianst Documents can't be found there

### ISSUE THREAD

**Issue by Jarli01** [Ylianst/MeshCentral#579]
@Ylianst those documents can't be found there. ;)

**Comment by Ylianst** [comment]
Apologies, here is the correct link: [http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralDocs.zip](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralDocs.zip). This is the MeshCentral documentation in .docx format. Please enable change tracking if you make changes. Thanks.

**Comment by Jarli01** [comment]
Confirmed, that link works, out of curiosity would it be worth posting directly to this GH so the community can create edits.

**Comment by Ylianst** [comment]
Adding the documents to GitHub is a good idea. Let me see about this.

**Comment by MailYouLater** [comment]
What do you think of [Read the Docs](https://readthedocs.org/)?

**Comment by Jarli01** [comment]
I personally think that keeping everything to one location would be _better_. Documents can files can be uploaded to GH, they just need to be enabled.

**Comment by Ylianst** [comment]
Ok, just added a ["docs" folder with all the documents on GitHub](https://github.com/Ylianst/MeshCentral/tree/master/docs). We will see how this goes. Let me know what you mean by "just need to be enabled"?

I have not looked at [Read the Docs](https://readthedocs.org/). Could be interesting, I like that you can output many different formats. If someone has time to prototype taking one of the smallest documents and place it on Read The Docs. I would love to see what it would look like. Especially the pictures, etc. I am a bit over worked these days, I need to see if I team can get me a tech writer at some point.

**Comment by MailYouLater** [comment]
I think the 'just need to be enabled' comment was regarding the way many GitHub projects use GitHub's built in Wiki function for documentation, but honestly I wouldn't recommend using that, especially considering the quality of your current documentation, as GitHub Wiki's are based on GitHub flavored MarkDown, which is missing a lot of features, most projects I know that do use them end up with broken links throughout their wiki's quickly, and they don't get versioning control.
Another option GitHub has which less projects use because the initial setup is a little more complicated than 'just enable it' is gh-pages, which is basically a second branch in your repository without any shared history, and GitHub will serve it's content to visitors at a subdomain.github.io address, there's several 'static website generators' that can be used to parse whatever you put in the gh-pages branch and turn it into a website instead of being stuck with MarkDown.

Which document would you recommend someone think about converting for a smaller, sample Read the Docs project?
