### ISSUE TITLE
Change the skipmaccheck of clients from the server remotely

### ISSUE THREAD

**Issue by trmdi** [Ylianst/MeshCentral#5845]
Nowadays laptops often randomize their MAC, this results agent entries are duplicated over time. A workaround is to use skipmaccheck. But it requires to regenerate the .msh file on all clients one by one manually, which is not an interesting job to do. So it would be great if we can somehow change it from the server side more conveniently.

> You can add the value into `agentConfig` under `domains` in `config.json` BUT this will only apply to new installs/setups!?
> ![Screenshot_20240211_134458_Firefox](https://github.com/Ylianst/MeshCentral/assets/765314/d977bb0f-9c29-47c5-9355-0bd94f25c7fe)
> So you have to manually edit the `.msh` file on each machine and add the value in urself afterwards.
> I think you would have to open an enhancement issue for us to look into pushing this value into the `.msh` value afterwards
> Also u must restart the meshagent after u add the value too

_Originally posted by @si458 in https://github.com/Ylianst/MeshCentral/issues/5049#issuecomment-1941246700_

**Comment by silversword411** [comment]
The MAC randomized feature is a software implementation. There should be some kind of query to be able to get the physical MAC for dupe checking instead of the TCP stacks randomized MAC.

**Comment by si458** [comment]
i have been working on a feature which extends the `msh` command in the console tab!
what do people thing? its only a start but we can integrate more at a later date
```
Proper usage: msh [get|set|delete]
msh get MeshServer
msh set abc "xyz"
msh delete abc
```
self explanitory really,
get the value meshserver from the msh and tell me what it is
set the value abc in msh to xyz
delete the value abc in msh

you can also just call `msh` still to get the whole `msh` file thats loaded in memory in JSON form

i have also found you need to `service restart` to get things to apply 30% of the time (no idea why?)

also you cannot use JSON in the console `set` command!
so u cant change the `translation` line in msh for example due to the way meshcore phases the console command you send

**Comment by si458** [comment]
ive done the PR if you wanted to give it a try for me!
