### ISSUE TITLE
Hiding the multi-desktop view in the web application

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#585]
Hello Ylianst, good afternoon!

Can you help me? I am trying to disable the type of visualization below without harming the system but I am not getting it, could you help me? Is it possible to make "optional" the existence or not of this feature? Follow print:

![image](https://user-images.githubusercontent.com/55212206/67126164-d32bdb80-f1cc-11e9-8b0a-54b2661bc630.png)

**Comment by MailYouLater** [comment]
Same method as [last time you asked this question](https://github.com/Ylianst/MeshCentral/issues/570#issuecomment-542294037) except you want to add `style="display: none;"` to the element with `id="devViewButton3"` instead of the one with `id="autoConnectDesktopCheckbox"`.

@Ylianst: Could a custom `.css` file be loaded from the `meshcentral-data` folder to make this kind of change a little easier, as well as to allow it to survive updates? Then this element could be hidden just by adding this to the `.css` file:

    #devViewButton3 {
        display: none;
    }

**Comment by Ylianst** [comment]
@MailYouLater Thank for answering this and your help in general. I am been heads down coding multi-language support.

**Comment by geanferrani123** [comment]
Guys, good morning!

At first the suggestion of MailYouLater answered, but I noticed that the system was a little slow, but it is nothing serious. If this slowness makes any impact I will make the third view visible again. Thank you all for your attention!

**Comment by Ylianst** [comment]
I will close this issue since it seems solved. I will note that hiding the multi-desktop button should have no impact on performance.
