### ISSUE TITLE
login token 

### ISSUE THREAD

**Issue by GreenAir** [Ylianst/MeshCentral#59]
I missed the opportunity to respond on issue #51 before it was closed ;-)

Thanks for implementing my request!
But as you mentioned using username and password in url is not very nice.
My idea was to get a logintoken from business server with username and password and then using the logintoken in the iframe.

I did this in webserver.js handleRootRequestEx after domain check (maybe would be better in handleRootRequest like you did)

```
        if (req.query.user && req.query.pass) {
            obj.authenticate(req.query.user, req.query.pass, domain, function (err, userid, passhint) {
                if (userid) {
                    var token = obj.parent.encodeCookie({ u: userid, a: 3 }, obj.parent.loginCookieEncryptionKey)
                    res.send(token)
                }
                else res.send('login error')
            })
            return
        }
```

**Comment by Ylianst** [comment]
Not sure I understand. Your supposed to generate the cookie on the business server using a preshared key that only the two servers know. If you ask MeshCentral to generate the cookie by placing the user/pass in the URL, it's no better than just using user/pass in the URL for any other requests.

In what language is your business server made it? Maybe I can write the cookie generator for your business server?

**Comment by GreenAir** [comment]
I'm using a remote-desktop iframe on my business server.

when I use username+password to login the iframe url is:
`?user=admin&pass=1234&viewmode=11&hide=15&node=JXaICd....`

with the "token-response-system", the business server gets a token from MeshCentral with:
`?user=admin&pass=1234`
and uses the token in the response for the iframe url:
`?login=kz6e....&viewmode=11&hide=15&node=JXaICd....`

It is true that a user could login to MeshCentral with the token, but that is not different from creating the token on the business server and only as long as the token is valid.

The business server runs ASP.net/C# and I looked into creating the token myself but I had trouble implementing "obj.encodeCookie", specifically the "aes-256-gcm" encryption.

To be blunt: I'd rather prefer getting the token from MeshCentral to make sure it works, maybe the token will change in the future or as you mentioned there is some time/format issue between business-server and MeshCentral.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.5-f with improvements in the login token area. First, you can now do: 

`https://localhost/createLoginToken.ashx?user=admin&pass=admin `

This will return a login token. Again, not recommended because placing credentials in the URL is not generally a good idea... but here it is. Also, I just noticed that C# .NET still has no support for AES-GCM, that is pretty sad. I could have tried to hack together a big C# solution, but instead I opted to add support for AES128/HMAC-SHA256 tokens in MeshCentral. So now, the attached C# code and sample will work.

[MeshCentralTokenEncode.txt](https://github.com/Ylianst/MeshCentral/files/2716091/MeshCentralTokenEncode.txt)

Enjoy! Feedback appreciated.
Ylian

**Comment by Ylianst** [comment]
One more update on this. Since I am making the claim that MeshCentral2 is "Quantum computer resistant", using AES124-HMACSHA256 would not cut it, so I changed the alternate login token encoding to AES256-HMACSHA384. It's published in v0.2.5-g. The default encoding is still AES256-GCM which is much more efficient. Here is the updated C# code (old one above will no longer work):

[MeshCentralTokenEncode.txt](https://github.com/Ylianst/MeshCentral/files/2716678/MeshCentralTokenEncode.txt)

**Comment by Ylianst** [comment]
I will presume this is fixed. Feel free to reopen if it does not work.

**Comment by marco-vogt** [comment]
Hey there,

is there code already for generating a login token in python? As my business server is running python, this would come in very handy.

[This](https://pastebin.com/Giu54DfAv) is what i got for now but doesnt work and im not sure why.
Can somebody maybe help me out here?

**Comment by marco-vogt** [comment]
If anybody has the same problem as i have, [here](https://pastebin.com/wX1fWVqd) is the code to generate a login token from the --logintokenkey in python.

@Ylianst Feel free to add this in the docs somewhere if you want.
