### ISSUE TITLE
Windows Safe Mode support

### ISSUE THREAD

**Issue by GnaXi** [Ylianst/MeshCentral#591]
Currently the agent doesn't start when booting Windows to Safe Mode.
Being able to still access the devices when they are in Safe Mode could potentially safe System Administrators a lot of work! :)
Also being able to not just perform a normal reboot, but a reboot to Safe Mode from the console would be a greatly appreciated addition.

Both of the above are achievable with TeamViewer. I have no idea how they do it, but I know that it is possible :P

**Comment by PathfinderNetworks** [comment]
I agree, this would be a VERY nice feature.  The Premium Remote tool used by Avast CloudCare can also reboot a device to Safe Mode and automatically reconnect.

**Comment by Ylianst** [comment]
Bryan took note of this suggestion and looks like he got an early version working. However, will need to hold on for the next agent release to give it a try.

**Comment by MailYouLater** [comment]
If you want to make the mesh agent run when the computer is booted into Safe Mode, it looks like all you have to do is add a registry key with the name of the service (in this case "Mesh Agent") to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SafeBoot\Minimal`.

If you want to make it so you can reboot a remote computer into Safe Mode, then continue to access it, it looks like the agent needs to be able to execute `bcdedit /set {current} safeboot Network`, but if you want it to boot normally the next time the computer is rebooted, it also need to add a registry value in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce` where the name of the value starts with an asterix (`*`) so that it'll actually run when booting in Safe Mode, and have it execute `bcdedit /deletevalue {current} safeboot`.

Source: https://stackoverflow.com/q/13276147

**Comment by krayon007** [comment]
I actually already got it all working :) it should be in the next update when we release this week.

**Comment by GnaXi** [comment]
Wow guys! In less than 48 hours from request to implementation.
I'm impressed! :D

**Comment by Ylianst** [comment]
The new agent is taking a bit longer than expected. Of course, it has to be tested well, I don't want to mess up an agent release. At first, this new feature will be in the agent console and will be added to the server user interface later on.

I am traveling a lot the first half of November, so the fast pace will slow down for a bit.

**Comment by MailYouLater** [comment]
I booted a computer into safemode earlier today, and the Mesh Agent wouldn't run in it.
Has the update that adds safemode support not been published yet?

**Comment by krayon007** [comment]
It has, but safe mode support isn't enabled by default. You just need to go to the console tab, and type safemode on.

I forget the exact command, but if you type safemode, it'll tell you what to pass. It's either on or enable, or something like that. That will cause it to boot into safemode on next boot. You can set it to normal, by setting either off or disable. But either way, when you enable it, it sets the registry key to allow the agent to run in safe mode.

**Comment by krayon007** [comment]
I can modify the meshcore, so that it checks if the key is set, and set it if it's not, to always allow the agent to run in safe mode. I didn't do that, cus I just left it to the user to decide if they wanted that, hence the console command.

**Comment by TitovLab** [comment]
IMHO, the ability to centrally enable MeshAgent service in safe mode is very necessary in MeshCentral. For example, if Windows itself has already booted in safe mode and we receive a call from the user, but do not see the computer in MeshCentral.

**Comment by MailYouLater** [comment]
What TitovLab described is exactly what I meant.  I had a computer's file system get corrupted when a power outage occurred, and Windows wasn't able to boot normally.  Once booted into safemode, I figured I'd be able to connect remotely via Mesh Central and do my diagnostics/repairs but the Mesh Agent service wouldn't start because it was in safemode.  I like the concept of being able to reboot a computer into safemode, but it's more important to me that if the computer is already booted in safemode, it is accessible.

**Comment by krayon007** [comment]
ok, I'll modify meshcore, to check/update the registry to make sure the mesh agent will run if the computer were to boot into safe mode. I'm assuming when you talk about safe mode, it is booted into safe mode with networking? Because if it's booted into regular safemode without networking there is no way for the agent to connect to the server... I haven't looked into seeing if there's a way to make safemode with networking the default safemode, when the computer is unable to boot. If someone knows the answer to that, I can integrate that too...

**Comment by MailYouLater** [comment]
Yes, I meant safe mode with networking.  I'm not too worried about making it default to safemode with networking, except when initiating a reboot into safemode via MeshCentral.

**Comment by CCWTech** [comment]
Has this feature been added yet?

**Comment by krayon007** [comment]
Thanks for nudging this topic, I'll make the meshcore changes to enable this by default.

**Comment by si458** [comment]
this fully works now 2023
go into safe mode manually (make sure u select with networking) and you have control
OR
use can use the console tab and type `safemode status` to check if its safemode or not
then use `safemode on` and restart to boot into safe mode
then use `safemode off` to switch off booting into safe mode next time round!
