### ISSUE TITLE
Join a new agent using a short code or simple link

### ISSUE THREAD

**Issue by zaggynl** [Ylianst/MeshCentral#593]
Current add Agent link looks like this: https://192.168.122.109/meshagents?id=4&meshid=VJfGjWEWuULYYxM6Y9GAdguY4Z8QGpfWaYZiuOnYy6llMZlb9QpdiQ9@cicw5Z3e&installflags=2

Could this be shortened to something like: https://meshcentralserver/addagent, where the user adds a session code provide by admin?

In addition, would it be possible to change the add agent links to easy links like those generated on imgur or jitsi-meet? 
Example: https://meshcentralserver/addagent?id=CalmBearsLaughBrightly

**Comment by Ylianst** [comment]
I see. A device group identifier is long, I could work on shortening it. Will take time and I am traveling the first 2 weeks of November. However, this is a good idea.

**Comment by MailYouLater** [comment]
The current workaround which @Ylianst has suggested in previous GitHub issues, and which I currently use is to generate one unlimited invitation, copy the URL it creates, and set up a shorter redirect in the `config.json` that goes to it.

**Comment by Ylianst** [comment]
That is a good solution, using the "Redirects" section in the config.json. I guess a proper solution would be to generate a short code and save it in the database with a time limit. The nice thing about the current approach is that it's stateless, I encrypt a cookie with a timestamp... however, the encrypted cookie is long.

**Comment by Ylianst** [comment]
By the way, I will also post this on Twitter: I am going on vacation (Flying to Australia) for the first two weeks of November. @krayon007 will still be working on the agent but I will be offline a lot more during that time. A new agent should be released this week after that, I will focus more on smaller bug fixes.

**Comment by MailYouLater** [comment]
An advantage of using the database is that you can have an overview page that shows which invites are active, and you can extend or revoke an invite, and switch the type between connect only, install only, or both after sending it out.

**Comment by Ylianst** [comment]
Yes, exactly. I like this. I could also track how many times a code accessed.

**Comment by zaggynl** [comment]
Does anyone have an example for the redirects?

I tried the below but it results in a 404:

  "redirects": {
      "invite": "https://hostname.tld/agentinvite?c=LONGIDEHERE
  },

The URL should be accessible at https://hostname.tld/invite right?

**Comment by MailYouLater** [comment]
@zaggynl That should work, though I'd recommend to use a relative URL instead of an absolute one, e.g.:
```
    "redirects": {
      "invite": "/agentinvite?c=LongStringGoesHere"
    },
```
My guess would be that you have your `redirects` settings in the wrong place in your config file.  Look at the `sample-config-advanced.json` file for a reference for where to put this, and note that there two places it could go.  I believe which one is the right place to put it depends on some other configuration settings, but I'm uncertain if that's accurate off the top of my head since it's been a while since I've played with these settings.
https://github.com/Ylianst/MeshCentral/blob/25fb245185619494fdd83c087476290fe39d35ff/sample-config-advanced.json#L103-L105 https://github.com/Ylianst/MeshCentral/blob/25fb245185619494fdd83c087476290fe39d35ff/sample-config-advanced.json#L241-L243

**Comment by si458** [comment]
as described above, you can use the redirects method in `config.json` for this
OR 
you can use the agent invite codes https://www.youtube.com/watch?v=HMQndnzreGI
