### ISSUE TITLE
MeshCommander disconnects attempting to image workstations via WDS.  

### ISSUE THREAD

**Issue by patricksalter** [Ylianst/MeshCentral#597]
The issue is sort of strange, and I cant seem to work my way through it.  Im able to connect to remote workstations without issue using MeshCommander.  Everything works pretty well with one big exception.  If I attempt to boot to a Windows Deployment Server, just before the WDS server requests an F12 input from the user to proceed to windows deployment services, Meshcommander disconnects from the workstation until the required F12 input times out.  I've tested this on multiple workstations, although they are all identical Dell workstations.  It seems very strange that it always disconnects at that exact same point in the boot process.  I am able to use meshcommander without any further issues on the workstations: I can see system details, connect the KVM for use in windows and even get into the bios of the computers.  I simply get disconnected at that precise moment before being prompted to press F12 to boot to WDS.  Which makes me wonder: is this by design or is there an actual issue here?  These are brand new dell precision 3431 desktops, running AMT v12.0.39.

**Comment by patricksalter** [comment]
Just wondering if you had any thoughts on this one.

**Comment by Ylianst** [comment]
Hi. Sorry for the delay. I don't have this exact machine, but the behavior you are describing is probably by design. For example, you can't enter MEBx while a hardware KVM connection is active because this could cause someone with more limited KVM access to gain full Intel AMT rights. I suspect the same could be happening here but I am not sure why or any of the details. I just know, they sometimes do design it this way.

You could try a different tool to make sure it's not specific to MeshCommander, but I suspect the BIOS is explicitly doing this to prevent the KVM session from doing something. If this is not expected, a bug needs to be filed with the OEM/BIOS vendor.

**Comment by patricksalter** [comment]
Hey thanks for getting back to me.  I will try some of the alternatives.  I had suspected this behavior was intentional.  But I’d love to find out if it is or not.  I will investigate further and report back if you like.

**Comment by MailYouLater** [comment]
@Ylianst: Does MeshCommander have a way of capturing (and displaying) the Connection Closed Reason String when it gets disconnected?
https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=WordDocuments%2Fconnectionclosedreasonstrings.htm

**Comment by Ylianst** [comment]
Sadly, MeshCommander implements RFB 3.8 which does not support the disconnect reason string. So, MeshCommander can't show this.
