### ISSUE TITLE
NGINX desktop and terminal timeout

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#607]
Hi,
I was wondering if someone else has had this issue before, im on the desktop and maybe around 20 seconds later or more i get disconnected as well on the terminal, Im going on a limb and say its NGINX time out? or is there another way i troubleshoot this?

https://pastebin.com/6xKVX18E 

Thank you

**Comment by Ylianst** [comment]
Good question. You can take a look at section Section 16 of the [MeshCentral User's Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf) for guidance on this. I am not an NGINX expert, but here are my recommendations:

In the HTTP section, remove these 2 lines:

> proxy_send_timeout 999999s;
> proxy_read_timeout 999999s;

The default timeout for these values is 60 seconds and for the HTTP server on port 80, MeshCentral does not keep long standing connections, so long timeouts are not needed. I also noticed that putting very long values will cause NGINX to never free resources and cause it to be unstable after a while. So, for HTTP, keep the defaults.

In the HTTPS section, remove this line:

> ssl_session_timeout 999999s;

Add these lines instead:

> proxy_send_timeout 330s;
> proxy_read_timeout 330s;

The default for the ssl_session_timeout is 5 minutes which is plenty, this value in not a factor. However, for HTTPS send/read default timeout values of 60 seconds are too short. Try 330s, which is a bit above 5 minutes. WebSockets does have keep alive traffic even when idle, so you should not need to go much beyond this value. Again, I don't recommend using 999999 because it will cause NGINX to not free resources and be unstable after a long time.

Let me know if that works.
Ylian

**Comment by killmasta93** [comment]
Thank you for the reply, this is the change i did https://pastebin.com/nDFZqYz8
im going to post backup and see how it goes
thank you again

**Comment by killmasta93** [comment]
so far so good today im going to close it thank you again
