### ISSUE TITLE
If I prepare one PC which have Meshagent and create disk image 

### ISSUE THREAD

**Issue by AnjaniKumar15** [Ylianst/MeshCentral#608]
If I prepare one Ubuntu OS PC which have Meshagent installed then I create disk image of this PC and create few more PC with the same disk image. That case, Does Meshcentral & Meshagent able to work without any issue?

**Comment by Ylianst** [comment]
If you create a master image with a MeshAgent, the best is to remove the "meshagent.db" file from "/usr/local/mesh". This way, when the agent runs for the first time on the new computer, it will generate a new identity and connect to the server.

If you do not delete the meshagent.db, it should still be ok because the meshagent will look at the MAC addresses of the computer. If they are all different, it will automatically reset the "meshagent.db".

Hope it helps.

**Comment by Ylianst** [comment]
Closing this one since I think it's answered. Please re-open if needed.

**Comment by AnjaniKumar15** [comment]
Thank you
