### ISSUE TITLE
Feature Request: Reconnect automatically after reboot.

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#613]
Some programs like TeamViewer and others reconnect automatically after reboot.  Be amazing to have that.
Shane

**Comment by MailYouLater** [comment]
If you install the Mesh Agent using the "Install / Update" button, it should automatically reconnect after the computer has been rebooted.  There is a known issue at the moment where if you're running in LAN mode it may fail to connect after a reboot, which seems to be due to the network connection it needs not being ready yet when the service starts.  I'm using a workaround [posted](https://github.com/Ylianst/MeshCentral/issues/514#issuecomment-536328834) by @pbo10 in #514, where I open `services.msc` as an administrator, find the "Mesh Agent" service, and set its Startup type to "Automatic (Delayed Start)".

![](https://user-images.githubusercontent.com/1279475/66596967-c830d580-eb52-11e9-8393-a026b769e524.png)

**Comment by Ylianst** [comment]
So... when the MeshAgent is installed as a background service, it will auto-reconnect to the server. However, if you are in a remote desktop session, you will have to hit "Connect" again to get the desktop back. Is the question about the agent reconnecting to the server? Of remote desktop auto-reconnecting?

**Comment by southeasterntech** [comment]
Sorry, auto desktop reconnecting....  it's nice to not have to keep punching Connect hoping it is ready.... it just reconnects automatically as soon as it is ready

**Comment by southeasterntech** [comment]
first world problems... I know,  haha... just icing on the cake

**Comment by MailYouLater** [comment]
The Connect button should be disabled ('greyed out') until the agent reconnects, so you can at least tell if it's connected or not without actually clicking the Connect button.
Also, you can enable notifications upon agent connection, then you'll get a little sound and balloon popup at the top right of the page to tell you when it's connected again.  To enable this, you need to enable notifications in your user preferences, and enable the specific notifications you want (e.g. Agent Connection) in the Features setting for the specific Device Group.

**Comment by MailYouLater** [comment]
I will admit this would be handy when remotely doing something that requires a reboot (e.g. installing software or updating Windows).

Unless I'm mistaken, the auto-reconnect would have to be initiated by logic in the browser, so I'm imagining it looking something like this:
![image](https://user-images.githubusercontent.com/1279475/68413287-d1f22c80-0142-11ea-8d9f-28812b9380a9.png)

It would also be very inconvenient if consent didn't persist through the reboot, so that would require the agent to be able to store the fact that consent was given (and for security reasons, it would need to know which user that consent was for), and once the agent starts up and connects to the server, it should accept a connection from that user if it's initiated within a certain amount of time, but this 'implied consent' should only occur when this feature is triggered, and shouldn't last too long because in certain situations that could defeat the purpose of having it ask for consent in the first place.

Finally there would need to be some kind of detection system to know when a computer is rebooting and should be expected to reconnect.  Should it only happen when the reboot is initiated by the agent? or should the agent detect when the computer starts a reboot (not a shutdown) while the remote desktop feature is in use? The former would be easier to program, but the latter would be much more convenient, as it would allow you to install something, and when it says "Click finish to restart the computer." you can click Finish and wait for it to reconnect.
