### ISSUE TITLE
Star is in my Devices List view in front of the Device Description

### ISSUE THREAD

**Issue by tobias9931** [Ylianst/MeshCentral#6174]
**Describe the bug**
The star is in the “My device” view when you switch to the list directly on the text of the device description.
You cannot read the device description in this manner.

**To Reproduce**
1. Mark a device as a favorite. (Toggle Star)
2. Go to my devices
3. Filter to starred
4. Switch the view to list
5. Enable under Device View Columns "Device Description"

**Expected behavior**
The star should not cover the text of the device description

**Screenshots**

**Comment by tobias9931** [comment]
Github doesn't let me upload a screenshot?! :(

**Comment by si458** [comment]
like this i got you 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/b1aa9366-39b8-47f9-8962-e37dbabc9a9b)

**Comment by si458** [comment]
better?
![image](https://github.com/Ylianst/MeshCentral/assets/765314/7ba00296-596e-41ee-8b8f-97bda4e20027)

**Comment by tobias9931** [comment]
> better? ![image](https://private-user-images.githubusercontent.com/765314/338980927-7ba00296-596e-41ee-8b8f-97bda4e20027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTg1OTgsIm5iZiI6MTcxODE5ODI5OCwicGF0aCI6Ii83NjUzMTQvMzM4OTgwOTI3LTdiYTAwMjk2LTU5NmUtNDFlZS04YjhmLTk3YmRhNGUyMDAyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxMzE4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzY2YTk3NWZkYzNhNTU1MzdkMWE2YWQ3OGIzMWZiNGY0YTMyNmI4ODM5Y2NkNjJhYmFmZjc5NzA5NTNmYzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uTXZXzMyx7LOMEFgeN9UdtX9pFLWieinG1qOIomuw88)

Oh yes much better!
Thanks for that very quick answer

**Comment by tobias9931** [comment]
@si458 how can we get this fix on our Server?
We have installed MeshCentral on a Windows VM, current with Version 1.1.22.
Can we search for updates an just you know install version 1.1.23?

Or how is this regulated here?

**Comment by si458** [comment]
You have to wait for a new release.

Or

The fix is actually a single line.

So edit the default.handlebars and paste in the patch https://github.com/Ylianst/MeshCentral/commit/c053c14dd0a08cf625a1211f1f346645e54b8e3f

**Comment by si458** [comment]
the latest version is actually 1.1.24 so u are 2 versions behind but this fix will be be included in the next release (1.1.25)

I try to ask @Ylianst to do releases once a month as its his NPM package so he has control over it.

also if you have docker you can use the `master` image to get new features/bug fixes instantly
(its build every time we push a commit) `ghcr.io/ylianst/meshcentral:master`

also if you are happy you can do an `npm install Ylianst/MeshCentral` which will download the github master repo rather than from NPM but it has all the new features/bug fixes just sadly missing all the translations

but remember the `master/github repo` might have bugs so dont use in production unless you are 110% happy

**Comment by tobias9931** [comment]
All right, thank you very much, we will now do the normal update from 1.2.22 to 1.2.24 and then I will change the one line manually as you described. This manual change should then not be lost during the normal update to 1.2.25.

Thanks for the quick change and the quick answers, I think you are really doing a great job here.
@si458 @Ylianst
