### ISSUE TITLE
Right click no longer works in Microsoft Edge Version 126.0.2592.87 (Official build) (64-bit)

### ISSUE THREAD

**Issue by jonbrekhusvt** [Ylianst/MeshCentral#6222]
When right click in Edge on Desktop or Terminal connection gettings Edge right click menu

1. Connect to Terminal
2. Right Click to paste
3. No Paste Option

I am guessing this is more of and Edge issue as this used to work. 
Using Firefox as solution for now.

MeshCentral  1.1.24

The picture shall shows the issue.
![git](https://github.com/Ylianst/MeshCentral/assets/128832465/32da73f9-f516-4b88-bd08-fdd834960d1d)

**Comment by si458** [comment]
im not having this issue here? same version, have you tried turning your computer off and on again?
also making sure you have actually copied some text?
i just opened notepad typed `ps aux` then highlighting it and right clicked then copy
![image](https://github.com/Ylianst/MeshCentral/assets/765314/a8e87826-13a1-4f48-9cbf-e12efbecc268)

**Comment by PathfinderNetworks** [comment]
I am also running Edge version 126.0.2592.87 and checked this.  Just as si458 mentioned, I also cannot replicate this.  My right-click menu options in the terminal (as well as other areas of MeshCentral) are working properly.

**Comment by si458** [comment]
@jonbrekhusvt is this still an issue as i still cant replicate the issue?

**Comment by si458** [comment]
closing as stale and unable to replicate, 
please try the latest 1.1.25 and if you still have issues
please reply back
