### ISSUE TITLE
Remote Application Management via MC2 Web Site

### ISSUE THREAD

**Issue by parky-t** [Ylianst/MeshCentral#6326]
Hi Team,

I was looking through the feature requests to see if I could find something similar but drew a blank (so apologies if this has already been submitted).

It would be really handy to be able to see a list of "Installed" applications on client machines (Servers and Workstations). Personally I am looking for Windows Devices, however it would be handy for the small number of Linux Machines I manage. It would also be handy if we could "remotely" install Packages like MSI/EXE and packages from a Package Manager.

_Ideal Solution_

- Clear List of Installed Applications (if possible with application icon)
- Remote Installation of applications via the MeshAgent
  - Installation packages to be uploaded to the MeshServer, and downloaded to the local machine when needed for installation
  - Reporting back if Installation was successful / failed, ideally with the exit code or the log file being uploaded
- Remote Uninstallation via the MeshAgent

I hope that the above is something that is possible and that could be implemented to the solution.

**Comment by si458** [comment]
yes this has already been asked for here #6110

you can already get a list of installed apps in JSON format
if you open up the console tab of a device and type `installedapps`
it will return installed apps it can find from the registry in a json format
you can also use the command with meshcmd for automation purposes

but what you are after is more of a remote management feature rather than a remote support feature
you should look into [tacticalrmm](https://docs.tacticalrmm.com/)
