### ISSUE TITLE
The agent does not work on Microsoft Windows 11 IoT Enterprise LTSC 24H2

### ISSUE THREAD

**Issue by AKAAZMS** [Ylianst/MeshCentral#6383]
The agent does not install on Microsoft Windows 11 IoT Enterprise LTSC 24H2 (10.0.26100 Build 26100)

At the same time, everything works great and installs on Microsoft Windows 10 Enterprise LTSC 21H2 (10.0.19044 Build 19044)

Workstations are located on the same local network.

**MeshCentral Version 1.1.29**

**Comment by AKAAZMS** [comment]
Many thanks!

**Comment by AKAAZMS** [comment]
Many thanks!

**Comment by si458** [comment]
i have an updated agent for people to test if they want!i have a new agent for people to try if they want!
fully compiled with all the bug fixes in the repo including replacing wmic with the `win-wmi` we already had

1. download zip and extract zip [MeshService64.exe.zip](https://github.com/user-attachments/files/17649745/MeshService64.exe.zip)
2. backup the `MeshService64.exe` from inside `node_modules/meshcentral/agents/` (or rename to something else)
3. place the new `MeshService64.exe` back in `node_modules/meshcentral/agents/`
4. stop meshcentral
5. **IMPORTANT: DISABLE AUTO AGENT UPDATE OTHERWISE ALL AGENTS WILL GET AUTO UPDATED!!!**
set `"noAgentUpdate": 1` inside of `settings` in your `config.json`
7. start meshcentral
8. **IMPORTANT: LET MESHCENTRAL RESIGN/RECUSTOMISE THE SINGLE FILE!**
9. **skip this step if you dont code-sign yourself** 
copy the new signed agent from inside `signed-agents` located inside of `meshcentral-data` to your machine,
code-sign the exe however you want/do it,
put the new code-signed exe back into `agents` replacing the old `MeshService64.exe`
(backing up the old code-signed version of yours first),
restart meshcentral
10. pick a device and go into its `Console` tab and run `agentupdate`
11. you should see the device go offline and then back online, and in theory the date/version will of changed!

edit: you can also then download a new meshagent from the 'addagent' tab and it should work on 24h2 machines for install/run
