### ISSUE TITLE
Send Commands not working in peering environment

### ISSUE THREAD

**Issue by ijustw0rkhere** [Ylianst/MeshCentral#6404]
**Describe the bug**
Send commands doesn't seem to be working in a peering environment. If I try to invoke sendcommands to a device connected on another peer, it doesn't work. However, if I attempt the same thing on a device connected to the same host, the invocation will work.

**To Reproduce**
1. connect device to Peer1
2. connect to webui on Peer2
3. attempt send command from Peer2 to device connected to Peer1

**Expected behavior**
send commands should reach the end device no matter which host it is connected to in a peering configuration

**Server Software (please complete the following information):**
 - OS: Win Server 20
 - Version: 1.0.30
 - Node: v22.6.0

**Additional context**

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mesh.url",
    "MongoDb": "mongodb://meshdb:27017/?replicaSet=rs0",
    "mongoDbChangeStream": true,
    "mongoDbBulkOperations": true,
    "sessionKey": "MyReallySecretPassword1",
    "WANonly": true,
    "port": 443,
    "redirPort": 0,
    "mpsPort": 0,
    "exactPorts": true
  },
  "peers": {
    "servers": {
      "mesh01": { "url": "wss://10.10.22.101/" },
      "mesh02": { "url": "wss://10.10.22.102/" },
      "mesh03": { "url": "wss://10.10.22.103/" }
    }
  },
  "domains": {
    "": {
      "title": "Mesh",
      "title2": "mesh01",
      "maxDeviceView": 300,
    }
  }
}
```

**Comment by kubamaruszczak** [comment]
I encounter exactly the same issue in my peering setup. I have two peers connected and sending command work only for agents which are connected to the peer from which command is being sent. Otherwise it says that agent is not connected. To reproduce the issue I first run one of my peers and wait for all agents to connect to it. Then I turn on second peer.

When executing command from first peer I get following:
`[ec2-user@ip-10-3-80-101 ~]$ node /home/ec2-user/meshcentral/node_modules/meshcentral/meshctrl --loginuser $NAME --loginkey $LoginTokenKey --url ws://localhost:443 RunCommand --id 'node//vCgyHmO$lqTsvaMfSRoHs20mUbg4FDNQu20TwafgOBFnSvYjEvCNFZcEEYbqiK@p' --run 'touch /tmp/test.txt'
OK`

When executing command on the exactly same agent from second peer I get:
`[ec2-user@ip-10-3-80-102 ~]$ node /home/ec2-user/meshcentral/node_modules/meshcentral/meshctrl --loginuser $NAME --loginkey $LoginTokenKey --url ws://localhost:443 RunCommand --id 'node//vCgyHmO$lqTsvaMfSRoHs20mUbg4FDNQu20TwafgOBFnSvYjEvCNFZcEEYbqiK@p' --run 'touch /tmp/test.txt'
Agent not connected`

**Comment by si458** [comment]
I will have a look when I get chance

**Comment by si458** [comment]
can confirm issue,
and after quickly checking the code,
the run commands feature was never designed to run with server peering in mind,
so im going to have to add the code in for this!
might take me awhile but leave it with me 👍

**Comment by si458** [comment]
all done! https://github.com/Ylianst/MeshCentral/commit/df64c750cc8c0dcfad18478165f91bf60b1facd0
will be in docker `master` image in 15mins for you to test
or wait until next release
or patch yourself from the commit!

**Comment by ijustw0rkhere** [comment]
> all done! [df64c75](https://github.com/Ylianst/MeshCentral/commit/df64c750cc8c0dcfad18478165f91bf60b1facd0) will be in docker `master` image in 15mins for you to test or wait until next release or patch yourself from the commit!

I have confirmed the fix as well as its support of the somewhat recent 'reply' feature (which i can use to great effect). I really appreciate your support of the peering configuration.

**Comment by si458** [comment]
dont forget to donate to keep me active ❤️  https://www.si458.co.uk/2024/01/05/donation/
