### ISSUE TITLE
Improvement suggestion - automatic deletion of machines

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#648]
Guys, Good Morning!

I would suggest (if possible of course) that every time you uninstall the meshcentral agent directly from the workstation, the meshcentral console will automatically remove the machine from there. Is this kind of implementation possible?

**Comment by Ylianst** [comment]
Question on this: In general, you don't want uninstalling the agent leading to the server removing the audit/event logs for a given device unless this is an authorized behavior. So, I imagine you would need to also have a policy on the server approving this. Even if not approved, the server could log that the agent indicated it's been uninstalled (and maybe that what user).

**Comment by geanferrani123** [comment]
Ylianst, let me see if I can understand you. What are you saying is that this suggestion would remove the audit logs? If so, would it be optional? Something that would give each one the power to define?

**Comment by MailYouLater** [comment]
I think having the server log that the agent has been uninstalled is good, then when someone looks at that computer in the web UI there could be some indicator that the agent has been uninstalled (maybe a red 'x' in the bottom right corner of the device's icon?) so people know why the computer's not coming back online. Of course, if the computer does reconnect later (e.g. if someone backed up the computer before uninstalling the agent, and then restored to their backup) the indicator should be removed once the device has connected again.

**Comment by geanferrani123** [comment]
Oh my god, very good idea.

I think the idea of the "X" is not a good one, a simple registry of "removed computer" I think serveria, otherwise I am in full agreement with MailYouLater.

**Comment by PathfinderNetworks** [comment]
My $.02 here- I don't want the devices to be removed from my MeshCentral server if the agent is uninstalled.  Reason being- I don't want an end user uninstalling the agent and me not realizing their device is no longer showing up on my MeshCentral server.  I'd prefer, like MailYouLater mentioned, that there just be an indicator of some sort showing that the agent was uninstalled from a device- like the red X he mentioned.  I need to be able to investigate why an agent was uninstalled.  For me, when I remove a device, I uninstall the agent then manually remove the device from my MeshCentral server.  It's a checks and balances thing.  Speaking of the agent being uninstalled- I'm going to start a new suggestion thread to see if we can password protect the uninstallation process for the agent so that an end user can't uninstall it without said password.

**Comment by krayon007** [comment]
If the user has admin privileges on their machines they could just use the windows service manager to uninstall the agent tho. Is there a way to password protect the windows service manager to prevent uninstallation? Ive never looked into that...

**Comment by PathfinderNetworks** [comment]
That is true, but I'm not too worried about that.  The end users I deal with are not technical at all. In my case, if just the Windows uninstaller portion were able to be password protected that would suffice.  If they can figure out how to use the service manager then I have bigger issues to deal with... ;-)

**Comment by desarrollocdb** [comment]
Hello, I am in a great conflict. Some machines are no longer interested in having them connected to the server, the moment I try to delete the device it appears as active again. Is there any way to remove / disable it from the panel without having to uninstall it on the computer?

**Comment by MailYouLater** [comment]
If you 'delete' a device in MeshCentral, the server disconnects from it and removes it from the database, but since the agent is still installed on the device, it will reconnect to the server, and the server will add it to the database and shows it.  If you don't want to have access to it via MeshCentral any more, then presumably you don't want the agent running on the machine any more, as that would be an unnecessary program running in the background all the time, wasting resources on the machine, and potentially acting as a vector for attack if someone were to find a security issue in the version of the agent operating on that machine.  If you really want to remove the device from MeshCentral you should (and kind of need to) uninstall the agent from the computer.  The only option where you leave the agent operating on the machine, and don't have it visible, is if it's placed in a device group which your current user doesn't have access to.  Then if you log in as a user that does have access to that device group you'll be able to access it again.

**Comment by si458** [comment]
this feature exists now, you can set 'features' inside a certain group to 'auto-delete' the clients if they are disconnected or uninstalled
![image](https://github.com/Ylianst/MeshCentral/assets/765314/d12fd89c-1c24-412d-b7ab-153b41d5309e)
