### ISSUE TITLE
Bootstrap Dark-Mode (Black on Black colours)

### ISSUE THREAD

**Issue by DaanSelen** [Ylianst/MeshCentral#6496]
Hello MeshCentral developers.

I want to make an inquiry if its wanted that the 7-Day power state should be dark color on dark color?

![image](https://github.com/user-attachments/assets/7e357467-26f9-4ebf-8516-3d3caedf67d5)

It is not terrible, but it could be improved. What is your opinion?

**Comment by DaanSelen** [comment]
I checked, and this is also because my Browser is by default in dark mode.

**Comment by si458** [comment]
ah right yes black on black is bad! must of missed that!
on day mode is looks great!
![image](https://github.com/user-attachments/assets/661e3edf-5971-4f68-865f-56e279808e30)
what colour did you want the bars then if the rows for days are alternativing greys

**Comment by DaanSelen** [comment]
> ah right yes black on black is bad! must of missed that! on day mode is looks great! ![image](https://private-user-images.githubusercontent.com/765314/382723573-661e3edf-5971-4f68-865f-56e279808e30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTcxOTksIm5iZiI6MTczMDcxNjg5OSwicGF0aCI6Ii83NjUzMTQvMzgyNzIzNTczLTY2MWUzZWRmLTU5NzEtNGY2OC04NjVmLTU2ZTI3OTgwOGUzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMDQxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTQ5MDBmYzQwYjRmMTNhOGZlMDE5ZWM5MWNiYzk4YWFlOGZkZjY0NjI5YjYxNDUzZDhkM2UzYjcxMTg1NmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k9WcVRaYE03MCGR-e_cpc5UR1RdJqbTCxfTvRxQu1no) what colour did you want the bars then if the rows for days are alternativing greys

Yeah I saw that as well and thought it must be a oversight. If you are going to look at this issue - look for more instances like this if you must. I can also list a couple running through this!

Overal, I like the new UI!

**Comment by si458** [comment]
That's fine, what colour did u want for dark mode on graph? 
U can tag onto this where darkmode looks bad like the graph :)

**Comment by DaanSelen** [comment]
> That's fine, what colour did u want for dark mode on graph? U can tag onto this where darkmode looks bad like the graph :)

I will tag onto this then. I was thinking something like light-grey. A bit like how dark and light mode are often opposites of eachother. And just bright white seems too bright for a dark mode, especially when the point is to not burn your eyes out at night.

**Comment by si458** [comment]
find a colour and give us the hex haha

**Comment by DaanSelen** [comment]
![image](https://github.com/user-attachments/assets/d9013468-4885-42e5-8dec-a173b65739d4)
![image](https://github.com/user-attachments/assets/2d013238-3d95-40d4-a2a2-3b74c2f2d7a1)
![image](https://github.com/user-attachments/assets/2ff80d8d-632f-4e3b-831d-f23a9230fdca)
![image](https://github.com/user-attachments/assets/9c385b5f-3490-4e27-84a8-64d1aadbfa2a)

A couple examples

**Comment by DaanSelen** [comment]
> find a colour and give us the hex haha

Something like: #a6a6a6

**Comment by si458** [comment]
![image](https://github.com/user-attachments/assets/dd9068c0-84bd-4134-bf62-e1e742177ccb)

**Comment by DaanSelen** [comment]
> ![image](https://private-user-images.githubusercontent.com/765314/383195177-dd9068c0-84bd-4134-bf62-e1e742177ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTkzMTAsIm5iZiI6MTczMDgxOTAxMCwicGF0aCI6Ii83NjUzMTQvMzgzMTk1MTc3LWRkOTA2OGMwLTg0YmQtNDEzNC1iZjYyLWUxZTc0MjE3N2NjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNTAzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTRjZjc4M2VhMjM0MmRiZmQ0ZWQyYWVhOTNmNTRjY2E4MWUxNWVmYmVmZmFjYWU4OWExMWQxYmE0MTQ3YmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.v7KibPN9yxm0hWfCua61Rf22y3URuytu76mLHNn5XOs)

Better... But I would like feedback from the community.

**Comment by marclaporte** [comment]
> Something like: #a6a6a6

A benefit of Bootstrap is that we can have variables for this.

@gary-c-l @luciash: any wisdom?

**Comment by si458** [comment]
in theory from my testing today,
because we use the new bootstrap 5.3, we can use the new color and dark mode features
then basically inside the main css (style-bootstrap.css)
we set values like`background-color: var(--bs-body-bg)`
https://getbootstrap.com/docs/5.3/customize/color-modes/#custom-color-modes
and it would use the body background colour thats built into bootstrap
BUT
we can also use `[data-bs-theme="blue"]` inside our own bespoke css
and then allow fully customise values of `--bs-body-bg` to say `blue`
then when you toggle a theme switcher it will load that theme up instead!
https://getbootstrap.com/docs/5.3/customize/color-modes/#javascript

this is how its done with the 'dark' mode at the moment with bootstrap
the is however another class call `.night` which lets u customise colours for night mode
which needs replacing with the bootstrap dark mode

so it will take some time but at least its a start at rhe moment!

**Comment by DaanSelen** [comment]
Also:
![image](https://github.com/user-attachments/assets/ae079b41-8b89-44bd-a61c-9dfd738158b5)

Letters seem to clip against the bottom border, but everywhere.

**Comment by gary-c-l** [comment]
Hi marclaporte and all,

I'm not sure exactly what the status of the MeshCentral code is, regarding color modes, so I hope this comment is useful, as a little overview. We implemented Bootstrap color modes in Tiki 26, released in July 2023 (https://doc.tiki.org/Tiki26), and Bootstrap has been adding new CSS variables with each release, and the Tiki team has been enhancing the color modes functionality.

Basically, there needs to be a declaration of the data-bs-theme attribute on the HTML tag to specify the color mode for the page (or can be just for a specific page element), and then element color properties are determined by CSS variables according to which data-bs-theme selector is active.

A little JavaScript places the attribute on the HTML tag and implements the UI switch and recognizes the browser color theme preference when the switch is set to "auto".

This can be seen in the Bootstrap color modes page source (https://getbootstrap.com/docs/5.3/customize/color-modes/).

About specifying the colors of page elements, if the project uses SCSS compiling to produce the final stylesheets, there is a set of SCSS variables that are defined by the author for light and dark themes. This file - https://github.com/twbs/bootstrap/blob/main/scss/_variables-dark.scss - shows the dark versions, and the corresponding variables in _variables.scss define the light versions. When compiled, these create the sections in the final CSS file for the `:root, [data-bs-theme=light] { }` and `[data-bs-theme=dark] { }` selectors. For a project or site that isn't compiling the Bootstrap SCSS files, these sections could be created manually to produce the final CSS.

So, some page elements will "automatically" switch colors and have good contrast in both color modes because they are covered by the CSS variables that define their color in each mode, such as the body color and background color (as shown by lines 43 - 57 in the _variables-dark.scss file).

Other page elements will likely need to have a new class or classes added in order to be responsive to color mode switching, to avoid things like the dark-on-dark text mentioned in this thread. Bootstrap provides some foreground and background color classes and CSS variables for that kind of situation (https://getbootstrap.com/docs/5.3/customize/color/). So adding the appropriate class (like https://getbootstrap.com/docs/5.3/customize/color/#using-the-new-colors) and maybe using the Bootstrap color values as defaults should give good results. I don't think we needed to redefine these colors when fixing some color contrast issues in Bootswatch themes in Tiki generally speaking; the Bootstrap values worked fine.

-- Gary

**Comment by si458** [comment]
@gary-c-l this is exactually what we are in the process of doing :)
currently it switches between light and dark mode, yipee! (apart from a few area which need fixing but thats ok)
the is already javascript code ready to switch between the color modes!
we just need to merge them together, for example let end users pick the color scheme from the My Account page

**Comment by DaanSelen** [comment]
More :)

![image](https://github.com/user-attachments/assets/a9065994-465e-43a6-b2c8-1d61459dcd74)

**Comment by si458** [comment]
just done load more bug fixes and icon changes and dark mode fixes, now off to bed! 💤 
https://github.com/Ylianst/MeshCentral/commit/b398cb7fa95100b63623d43a4f9db5eb3e1b80e9
https://github.com/Ylianst/MeshCentral/commit/727080ab6812ac3bf024a7d0ff0276a0f1e6f480
https://github.com/Ylianst/MeshCentral/commit/911d987a84cf431065f473447ff82f06b420d063
https://github.com/Ylianst/MeshCentral/commit/d44faed29eeecc58aa8363a6df501e831805b98c
https://github.com/Ylianst/MeshCentral/commit/54170c44a0f860e21848112013bc07934be689c9

**Comment by DaanSelen** [comment]
Adding more:

Desktop
![image](https://github.com/user-attachments/assets/19353741-0fad-4216-994b-f292a94b5a33)

Terminal
![image](https://github.com/user-attachments/assets/ea7e85e8-3cb5-49c8-a58b-f91ced94d95b)

Files:
![image](https://github.com/user-attachments/assets/7b1a3efe-1abd-460d-90a9-be1f643deb0b)

All 3 have different margins (in dark mode)

**Comment by Otsegox** [comment]
Ugly white bars in dark mode.  Just adding our examples. Thanks for your work on this!

![image](https://github.com/user-attachments/assets/07b687e0-201d-4760-aa29-e1fd5c3dee31)


![image](https://github.com/user-attachments/assets/52343e58-0213-493e-ad6e-c1f6e7616f77)


![image](https://github.com/user-attachments/assets/f131f66c-554c-4980-8341-99213c2f1f4a)

**Comment by si458** [comment]
load more fixes and new mouse cursor hehe
![image](https://github.com/user-attachments/assets/d18bf5bd-2e70-444c-8dd4-186bae790a8e)
![image](https://github.com/user-attachments/assets/7f2f8593-8100-424d-92a4-98819450acff)
![image](https://github.com/user-attachments/assets/f597feee-4689-47e7-a5f7-e92531030e8f)
https://github.com/user-attachments/assets/9326788f-6902-4b52-a991-c9ee1f7d4f3d

**Comment by DaanSelen** [comment]
Looks good

**Comment by si458** [comment]
![Screenshot 2024-12-22 at 00-24-37 MyRemoteAgent](https://github.com/user-attachments/assets/c8b3f8c7-4b85-45ef-b2f0-1b11e6e40fe6)
![Screenshot 2024-12-22 at 00-24-24 MyRemoteAgent](https://github.com/user-attachments/assets/277070ed-0780-4933-af4b-4b8b58ca3036)
![Screenshot 2024-12-21 at 23-19-16 DESKTOP-LTSAD3V - myothergroup - MyRemoteAgent](https://github.com/user-attachments/assets/fcc95390-978a-4930-8876-f2ade76116f6)
![Screenshot 2024-12-21 at 23-13-39 DESKTOP-LTSAD3V - myothergroup - MyRemoteAgent](https://github.com/user-attachments/assets/ca83cc3e-e187-47f2-87d0-ecde935477a4)
![Screenshot 2024-12-22 at 01-24-23 MyRemoteAgent](https://github.com/user-attachments/assets/916c426b-fb3d-4ec3-b066-fb4253408642)

**Comment by si458** [comment]
theme switcher implemented here now 👍  https://github.com/Ylianst/MeshCentral/issues/6202#issuecomment-2561015587
