### ISSUE TITLE
Running Mesh agent on XP returns a "not valid Win32 application" tried both 64 bit and 32 bit

### ISSUE THREAD

**Issue by marklonardo** [Ylianst/MeshCentral#650]

**Comment by jsastriawan** [comment]
XP is not supported. Please close this issue.

**Comment by marklonardo** [comment]
thank you , great product.

    On Wednesday, November 13, 2019, 9:48:56 AM EST, jsastriawan <notifications@github.com> wrote:  
 
 
XP is not supported. Please close this issue.

**Comment by MailYouLater** [comment]
@jsastriawan Is there any particular reason Windows XP isn't supported?

My guess is that it's just because you guys are using a newer compiler that no longer supports XP to build the Mesh Agent, and that the code doesn't actually use anything that prevents someone from compiling the same source with an older compiler and having it work just fine with XP.  Am I wrong? is there something that the Mesh Agent does, or uses, which can't work on XP? or could @marklonardo and I use it on XP if we build it ourselves using an older compiler?

Note: I'm also very curious about using it with ReactOS, an open source, reverse engineered Windows-like operating system, which is currently mostly compatible with Windows Server 2003 and Windows XP.

**Comment by jsastriawan** [comment]
I am not sure if certain API are available on XP. @krayon007 can explain. If you wish to work on it, the source code is available on Ylian repo next to Meshcentral.

**Comment by krayon007** [comment]
Actually, it's a technical issue. For example, one major issue is that we need to  disable HANDLE inheritance on our socket descriptors, so that spawned processes do not inherit it. Otherwise if you do a KVM session or terminal session, (or the myriad of other things that could spawn a process), you'll have a mess with your handles. The common solution is to just close the handle before spawning a child process, but that is a non-starter because the child process can be spawned from JavaScript code that has no knowledge of what HANDLES are floating around.

We use 'WSA_FLAG_NO_HANDLE_INHERIT' to disable inheritance at creation, because if you try to set SOCK_CLOEXEC after creation, you'll have  race condition, if a child is spawned before you are able to set it. The 'WSA_FLAG_NO_HANDLE_INHERIT' flag is only supported on Windows 7 SP1 and above.

**Comment by krayon007** [comment]
The other issue, is the executable file format. We implement a solution, where we are able to parse the executable, to embed data and such, but the PE File Format is different for Windows XP than Windows 7 and above.

**Comment by MailYouLater** [comment]
> Another issue, is the executable file format. We implement a solution, where we are able to parse the executable, to embed data and such, but the PE File Format is different for Windows XP than Windows 7 and above.

What? Really? How? Can you direct me to documentation about the differences? or maybe point me to the parts of the MeshAgent code that make use of these differences?

Regarding the HANDLE issue(s), I bet there's a way to work around this, but ... I understand that even if it is possible, it may not be worth it to put in the extra R&D time and effort to get this working on XP.  On the other hand, I'm glad you guys have a technical reason for not supporting XP and aren't just artificially removing support for XP like so many other projects are these days.

Now I wonder if the forward compatibility shims ReactOS has so far are able to make it work anyway or not. 🤔
