### ISSUE TITLE
Node 23 crashing meshcentral startup

### ISSUE THREAD

**Issue by alevoski** [Ylianst/MeshCentral#6503]
**Describe the bug**
After a fresh install from scrach, when I attempt to run MeshCentral for the first time, it failed in loop with the message :
"ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds..."

**To Reproduce**
1. Install MeshCentral : npm install meshcentral
2. Run it : node ./node_modules/meshcentral
3. See error

**Expected behavior**
MeshCentral should runs with no errors.

**Server Software (please complete the following information):**
 - OS: Debian 12
 - Virtualization: VirtualBox 7
 - Network: LAN
 - Version: 1.1.33
 - Node: 23.1.0

**Content of mesherrors.txt**
See attached file
[20241105_mesherrors.txt](https://github.com/user-attachments/files/17638110/20241105_mesherrors.txt)

**Additional context**

**Your config.json file**
This is the default configuration

**Comment by si458** [comment]
Oh dear! Node 23 broke meshcentral!!!
Don't use node 23!
Try using node 22

**Comment by PTR-inc** [comment]
This seems to be caused primarily by NeDB, as it's using deprecated functions. Did a quicktest with node 23 with other db's and those work. Maybe it is a signal to put NeDB to rest? See #4398 for an earlier discussion about this.
Possibly for now put a node versioncheck/warning in place?

**Comment by si458** [comment]
@PTR-inc I have already asked @Ylianst on his opinion on the matter, just awaiting his reply

I was thinking of making sqlite the default, but it would mean a single sqlite file, and the size can grow dramatically,

I also didn't want to set like mysql/mongodb etc the default because otherwise the meshcentralinstaller would need a complete change to install/setup those apps, where as sqlite can be included as part of nodejs

If I remember, we can put a check inside the package.json to say that nodejs must be above 16 and below 23, will check tomorrow

**Comment by PTR-inc** [comment]
Sqlite seems like the logical candidate indeed, also given that nodejs has an internal sqlite api in the experimental phase, so in the future no need even for an external module.

What do you mean exactly with single sqlite file?

And the excessive growth issue as discussed in #5532 has been tempered with the addition of the maintenancefunction for sqlite.

**Comment by alevoski** [comment]
> Oh dear! Node 23 broke meshcentral!!! Don't use node 23! Try using node 22

Hi, it works with Node 22. Thanks !

**Comment by si458** [comment]
Glad it works!
We are going to have to think what's we do as nedb is indeed no longer maintained and really outdated
