### ISSUE TITLE
MeshCentral creates duplicate Agent when agent switches between networks.

### ISSUE THREAD

**Issue by DaanSelen** [Ylianst/MeshCentral#6641]
Perhaps a bit of a bad description, but I have a test situation: We have a switch that some MeshCentral agents connect to (test machines). But the network this switch is the downstream from often changes. And I have noticed that MeshCentral sometimes creates a duplicate node in the dashboard of this device.

I already cleaned it up, but still wanted to report this. Perhaps if it happens again I can post some screenshots.

All software is latest, MeshCentral, Operating System (Linux), etc.

**Comment by DaanSelen** [comment]
To add upon this, the node it is happening to has a variable Ethernet network but a stable Wifi, so perhaps its switching from where it navigates to the MeshCentral server. (It is a raspberry Pi 5)

**Comment by si458** [comment]
This isn't a bug

Meshagent gets its unique identifier based on various things including mac addresses of the devices.

One thing that happens is for example when a remote device uses a vpn, a new network interface is created and hense a new identifier is created because a new hardware mac is added in meshagents eyes

One fix is to add `skipmaccheck=1` into your .msh file
https://github.com/ylianst/meshagent?tab=readme-ov-file#msh-format

This will then stop the meshagent monitoring mac addresses and creating a new identifier if mac addresses are added or removed

**Comment by DaanSelen** [comment]
> This isn't a bug
> 
> Meshagent gets its unique identifier based on various things including mac addresses of the devices.
> 
> One thing that happens is for example when a remote device uses a vpn, a new network interface is created and hense a new identifier is created because a new hardware mac is added in meshagents eyes
> 
> One fix is to add `skipmaccheck=1` into your .msh file https://github.com/ylianst/meshagent?tab=readme-ov-file#msh-format
> 
> This will then stop the meshagent monitoring mac addresses and creating a new identifier if mac addresses are added or removed

Okay, can this be set in the config.json somehow?

**Comment by si458** [comment]
Yes under domains, u set `agentConfig: ['skipmaccheck=1']` this will then add the value to every NEW install of meshagent

Unfortunately the only way to add it with every existing device is modify the .msh file manually

I did implement a feature under the console tab of each device called `msh` and it let u modify the msh file, however it's hit and miss if it saves it and loads it, due to the way the meshagent loads/saves the msh file in memory and on disk :(
