### ISSUE TITLE
Hardware Server Configuration Min/Max Checking

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#668]
Hi Ylianst and team,

What about having an option to enable server checker that would in essence check server configuration against a manifest that when the MeshCentral code steps the manifest would then be changed over to show the fully supported of each item from OS, Node, etc.

Then in the server page we can see if our configuration is on par with your manifests, if not then we can ssh in and change as needed.

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
So I can understand right, this is config.json file validation? The server will not run at all if the config.json can't be parsed. I guess you can have a valid config.json, but with incorrect values and want to show such errors?

**Comment by SomeGuru** [comment]
Hi Ylian,

No more of a configuration of the server matching to your specifications... Such as the collateral installs needed for MeshCentral to run smoothly. Something that would tell the Server Administrators to update their distributions to match the minimum/maximum requirements. If you need additional information let me know. 

Thanks,
SomeGuru.

**Comment by MailYouLater** [comment]
So you're asking for a built in "Minimum System Requirements" verification system...

**Comment by Ylianst** [comment]
Well, you can run MeshCentral on a first generation Raspberry Pi and MeshCentral already checks that NodeJS 6.0 or above is installed (NodeJS 10.12 or above if using Let's Encrypt) or it will fail and indicate you need better NodeJS. I can't really check disk space since you can configure a database to be on a different drive or server. If anything else is needed, let me know.
