### ISSUE TITLE
Windows 10 1903 Internet Explorer in box build, and Chrome Latest Save Button Issue

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#671]
Hi MeshCentral team,

I noticed today when walking a new user through the process on his Windows machine that he didn't have Save button in IE, but the save button was present in Chrome. So my question is can IE be blocked or can this be fixed? User access level was set to Administrator for this verification.

Thanks,
SomeGuru

**Comment by MailYouLater** [comment]
Can you provide screenshots with and without this button please?

**Comment by PathfinderNetworks** [comment]
Can you describe what process you were having the user do?  Was this for a new MeshAgent invite or something along those lines?

**Comment by Ylianst** [comment]
Same questions as above. Screenshots and a way to replicate the issue would be appreciated.

**Comment by SomeGuru** [comment]
![image](https://user-images.githubusercontent.com/48393851/71152254-b9b60880-21ea-11ea-92b4-9537346950e8.png)
Chrome 78.0.3904.108

![image](https://user-images.githubusercontent.com/48393851/71152375-16192800-21eb-11ea-8281-6f4734109c0f.png)
Edge & IE (Edge 18362) IE (11.535.18362.0)

**Comment by MailYouLater** [comment]
Interesting, I am able to reproduce this, and using the "Elements" tab of the "DevTools" included in both Edge and Chrome I found that the element representing the Save... button is present in Edge's DOM, but is different.  I'm not sure why all the attributes are in a different order and if that's related, or a concern or what, but the key difference is that in Edge this element includes this: `style="display: none;"` which is obviously going to hide it.

Microsoft Edge 44.17763.831.0 Microsoft EdgeHTML 18.17763
    <input title="Save a screenshot of the remote desktop" disabled="" class="mR" id="deskSaveBtn" style="display: none;" onkeydown="return false" onkeypress="return false" onclick="deskSaveImage()" type="button" value="Save...">

Google Chrome | 79.0.3945.88 (Official Build) (64-bit) (cohort: 79_Win_88)
    <input id="deskSaveBtn" type="button" title="Save a screenshot of the remote desktop" onkeypress="return false" onkeydown="return false" value="Save..." onclick="deskSaveImage()" class="mR" disabled="">

Also interesting however is that if I remove the `style` attribute from that element it appears and gets enabled and disabled appropriately when connecting and disconnecting from the remote computer, however clicking on it while connected doesn't seem to actually save a screenshot like it does in Chrome, so I'm tempted to say that this button was intentionally hidden in IE/Edge because the feature doesn't work in IE/Edge.  @Ylianst, is this accurate?

**Comment by Ylianst** [comment]
@MailYouLater is 100% exactly correct. The feature to save the HTML canvas to an image file is not supported in IE/Edge and so, I hide that button. I will check again and see if support was added recently. If so, I will try to detect and enable to save button.
