### ISSUE TITLE
Allow non-admin terminal access on Windows

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#675]
I've been wanting to ask for this for a while, but hadn't got around to posting an issue about it till now.  I was prompted to bring it up because of certain similarities to #670, but it should be a separate issue, even if you may decide to make this available on other OSes too.

Basically, I noticed that right clicking on the "Connect" button in the Terminal tab brings up two options "Normal Connect" and "PowerShell Connect":
![image](https://user-images.githubusercontent.com/1279475/69457155-47542480-0d21-11ea-8e30-3e65b6396796.png)
First, I feel like the way that's worded could be improved by switching it to "Command Prompt" and "PowerShell", and I think it might also be a good idea to borrow the concept of making the option that would have occurred by default if you had left clicked instead bold, as is used in context menus in Windows, but my main request is that I'd like to be able to connect to the Command Prompt as the currently logged in user.  I'm imagining it looking like this, where each of the non-admin ones will be launched as the currently logged in user:
![image](https://user-images.githubusercontent.com/1279475/69458008-41f7d980-0d23-11ea-8d45-8b8d7b9ab4aa.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.4-v. For Linux computers, you can now launch a shell under the currently logged in user (instead of root) by right clicking on the connect button or, holding shift and clicking connect. Same feature will be on Windows when @krayon007 adds support for it in the agent. Feedback welcome.

![MC2-LinuxUserShell](https://user-images.githubusercontent.com/1319013/69589170-074ea500-0fa0-11ea-8c47-c15d2e47a22c.png)

**Comment by MailYouLater** [comment]
I thought the agent was already supposed to be able to launch things as the currently logged in user because it was necessary to be able to make the chat window open on the currently logged in user's desktop.  Is this not working? (That would explain why that feature still doesn't work for me.)

**Comment by krayon007** [comment]
The agent does support launching things as the logged in user. (If the chat thing still doesn't work for you, that is a separate issue). But this is separate from the terminal. I'm working to add this functionality to the terminal. The terminal is a special case, because processes are spawned differently for the terminal then they are for other things, because it needs to be attached to a console.

**Comment by MailYouLater** [comment]
Thanks for the info, I look forward to seeing all the work you guys have been doing to the agent when the new version is ready.

Regarding the chat issue, I'm not too worried about it (at least for now) as I don't use that feature very often (yet?) and I can work around it by going to the URL from the window it opens on my side on the remote computer.  If I have some extra time in the future I may try to look into it more, as it would be nice to have that feature work properly.

**Comment by MailYouLater** [comment]
Sorry, just noticed this issue was still open.  I would prefer using the "Command Prompt" term instead of "Shell", since that's what Windows users are used to it being called, but hey, it works. Thanks guys.
![image](https://user-images.githubusercontent.com/1279475/72762623-267b4480-3b95-11ea-97c2-a45d93d0cced.png)
