### ISSUE TITLE
EU Guidance on form collection practices (Cookies!)

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#685]
Hi MeshCentral Team,

I am looking but blind as a bat I am sure, is there a config line to enable acknowledgement of a cookie for form processing and data collection? I ask this because of needing to comply with the EU guidelines on such practices and wanting to actually use MeshCentral with those users.

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
This is an interesting ask, it's not available now and can be added. However, MeshCentral should work correctly even if the browser rejects all cookies. The only difference will be that if you leave the page and come back, you will not be logged in anymore and will have to re-authenticate.

I would be interested is getting a more precise ask in this area.

**Comment by SomeGuru** [comment]
Hi Ylianst,

This is in regards to the GDPR guidance... Do we have to disclose data collection or risk fines if we are not up front with the users to the regards... I am not a lawyer, but I am wondering if we would be against that regulation not to have the initial Cookie/data request acknowledged and flagged for keeping.

[https://ec.europa.eu/info/law/law-topic/data-protection/reform/rules-business-and-organisations/principles-gdpr_en](url)

**Comment by PathfinderNetworks** [comment]
I think that would only apply if you have users in the EU that are logging in to the MeshCentral website itself.  Nothing to do with the MeshAgent (from what I understand anyway).

**Comment by ryanblenis** [comment]
As someone who's developed websites (10 years ago), the basic premise is that you need to let the user know you've placed a cookie/data on their system or are retaining data about them.

Something as simple as showing the message:

>MeshCentral uses technology to gather information and enhance the user experience. By continuing to use this website, you consent to this usage in accordance with our privacy policy (link to policy).

with a "Close" link to get rid of the message is usually enough to comply. Then set set a cookie to "gdpr_shown" = "yes" and then just check for that cookie to display/not display the message.


In MeshCentral's case, the privacy policy is really just keeping the user logged in and possibly tracking the users IP address.

Since MeshCentral is usually self-hosted, the onus of data protection and compliance of data deletion/right to be forgotten is on the operator.

I personally don't see the need for GDPR compliance in that only authenticated users have access to the interface. I've only seen it on public websites, but I also do not live in the EU.

With regard to the data collected from endpoints, I don't know how the GDPR comes into play (if at all) as they've already opted into a service by installing the agent.

**Comment by MailYouLater** [comment]
Basically, MeshCentral.com (and any similar product being offered to the public) should probably have some message about what data it stores about its users for GDPR compliance, but the MeshCentral project probably doesn't need a GDPR notice because the onus is on the people setting up a public service to provide the information about how they collect and/or use their users' data, not on the MeshCentral project owners/maintainers, because the MeshCentral project owners/maintainers aren't gathering any data from the MeshCentral servers that people are setting up.

It might be nice though if a simple GDPR compliance notification system with a template GDPR compliance message (that can be changed in the `meshcentral-data` folder) was added to the MeshCentral project so that anyone who wanted to host a public MeshCentral server (like MeshCentral.com) would be able to simply enable that instead of having to edit the source directly to add it (and thus have to manually recreate their changes every time they update).

**Comment by ryanblenis** [comment]
A subset of users may need/want it... Hmmm... Sounds like a great application of a plugin! =D

I half-heartily kid. I'm not sure how that would work as a plugin since it modifies the login page instead of the logged-in interface (which I've paid most attention to for obvious reasons), but I'm sure it's possible!

**Comment by SomeGuru** [comment]
GDPR can be handled by the parent domain if need be and MeshCentral can be nested as a page within a page if need be.

-SomeGuru
