### ISSUE TITLE
Multi-domain Admin

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#724]
Hi team:

I've got a feature request that would be super handy in some cases. I'm rolling out a second domain for a client to use so they can add their clients for remote access. Is there a way for me to administer this domain using my admin account from my top level domain (administer customer.mesh.domain.ca from mesh.domain.ca)? This just saves me from having to create an account for each domain we create.

In addition, and this is a much bigger ask, it would be nice to make device groups available on a per domain basis (add "device group 1" to 3 different domains) for specific use cases.

**Comment by darryl-h** [comment]
+1 for this, for us, because we use 2FA and multiple instances of Mesh Central (Local, Development, Integration, Testing, UAT and Production) 2FA can become difficult to manage in Gauth without some kind of system. We are renaming the entries to `[INSTANCE]-[DOMAIN]-[USER]` which is working, but a global admin account would be solve this. 

Would also be nice to have generally "global users" that have the same permissions (and 2FA) across all domains.

**Comment by MailYouLater** [comment]
Or perhaps cross-domain users, so you can add them to some but not all domains (or make them global) as desired.

**Comment by OutbackMatt** [comment]
I use groups for this
Assign rights to the group for each client

Only issue is branding is all the same...

**Comment by asasin114** [comment]
> I use groups for this
> Assign rights to the group for each client
> 
> Only issue is branding is all the same...

I understand what you're saying but this will not work for what I'm trying to do. I'm very specifically adding a domain for a client that they can use for their clients. I don't want to or need to see their clients devices but I do need to see their devices.

**Comment by vitko-bg** [comment]
@asasin114 - How did you resolved that issue? 
I still cannot get done #974 
I would like to see all users, domain and agents in MC, but my regional support guys have to have only access their subdomains .....
