### ISSUE TITLE
after translation no centralpage

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#739]
I have translated meshcentral into dutch, using the arabic code. (server website translation)
after an restart of the server, i can login but when the page loads an blank page is shown.
I made it possible to login internet explorer, i changed the localisation to english again and now im able to logon again in goog chrome.

the serverconfig; ubuntu server 18.04 lts, loaded on an qnap nas with an virtual os.
meshcentral is 0.4.5-w
nodejs version: 10.17.0
npm version: 6.11.13

no log errors to be found

**Comment by petervanv** [comment]
after updating to the latest version 0.4.5-x my problem is solved

**Comment by petervanv** [comment]
Solved

**Comment by Ylianst** [comment]
Thanks. In the background, Peter sent me this translate.json file. I added Dutch (nl) support in the online translation tool, switch "ar" to "nl" in this file and got it integrated. There was a few places with quote escaping was not quite right, like \\ \" instead of \\\" which caused the web page not to load. I went thru and fixed the few issues and it seems to work well.

Thanks Peter for this work. If you see any issues with the translation, please don't hesitate to send over corrections.

![MC2-Dutch](https://user-images.githubusercontent.com/1319013/71039826-f1815b00-20d9-11ea-9c4f-21535947f2e7.png)

**Comment by Ylianst** [comment]
Just posted it on [Twitter](https://twitter.com/meshcentral).

**Comment by petervanv** [comment]
again after translation of some strings my meshcentral is offline again (blank page) every other possible way to restore is not working, how to restore previous state? without losing my database

**Comment by petervanv** [comment]
i managed to repair the installation, and also made an other topic about the language problem.
