### ISSUE TITLE
Enhancement: Tags via drop down list

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#748]
It would be really useful to save a list of tags, that can be selected either jointly or separately.
At the moment I need to copy and paste text to avoid spelling differences (mistakes) and it looks like I can ONLY add tags from the 'information' page for each device individually.

Being able to group devices, then tag them all, would be useful,
As would being able to have default tags per device group.

**Comment by ryanblenis** [comment]
Just to add to this, one way other RMM's seem to handle something like this is with "Views" where you can create a new View, then choose what qualifies- e.g. OS is Windows/MacOS/Linux, OS version contains/starts with/end with/equals/does not equal X, Currently Online/Offline, etc.
A couple screenshots for reference. I know it's a bigger initial ask than @OutbackMatt's original, but offers a great amount of flexibility.

<img width="583" alt="Screen Shot 2019-12-21 at 11 06 33 PM" src="https://user-images.githubusercontent.com/1929277/71316915-dcdcf400-2446-11ea-9134-f155215ff202.png">
<img width="503" alt="Screen Shot 2019-12-21 at 11 07 27 PM" src="https://user-images.githubusercontent.com/1929277/71316916-dcdcf400-2446-11ea-9aee-369b28eb2907.png">

**Comment by MailYouLater** [comment]
I think the way JIRA handles tags would probably be the best solution to @OutbackMatt's issue.  In JIRA, it has a text box for tags, and when you start typing it populates a dropdown list filtered by what you've typed so that you can click on one (or use <kbd>↑</kbd>, <kbd>↑</kbd> & <kbd>Enter</kbd>) to select any existing tag.  This ensures you didn't misspell them.

One thing to be careful of when using JIRA's tag handling system however is to be careful with how you handle capitalization, as JIRA's tag handling has had a few bugs due to mishandling of capitalization for a number of years.  (I haven't used it in quite a while, so I don't know if they've fixed those bugs or not.)

**Comment by OutbackMatt** [comment]
Mesh Central does it already when you add a user to a device group, much like the JIRA method mentioned above. Start to type and options appear that you can select.

**Comment by MailYouLater** [comment]
Oh yeah, I'm doing most of my testing as the sole user, and thus have full admin privileges, and don't find myself adding users to device groups, since I usually don't have other users.  I just took a look at that, and that looks like it would be perfect for this, so it should theoretically be fairly straight forward to duplicate that functionality for tags.  My one issue with the current implementation where it lists users, is that it doesn't seem to be keyboard accessible.  It would be really nice if you could use the <kbd>↑</kbd>, <kbd>↓</kbd> and <kbd>Enter</kbd> keys to select one of the items shown instead of having to continue typing, or grab the mouse.  It's useful as it is, as you can see what users (or tags in the suggested use case) there are, and thus see how exactly they're written so you can make sure you don't mistype them, but it would be nice to be able to type the first few letters, and press the down arrow a few times to complete the rest of one of the displayed tags.

**Comment by Ylianst** [comment]
Somewhat related to this, published MeshCentral v0.4.6-m. In this version, you can put "t:(tagname)" or "tag:(tagname)" in the "My Devices" filter box and it will show only devices with that tag.

**Comment by Ylianst** [comment]
FYI. In the next version of MeshCentral, if you only type "t:" or "tag:" in the filter box, it will show you all devices with no tags. I forget which issue we were discussion this on, but that should improve the filtering.

**Comment by si458** [comment]
this has been implemented as such,
as you build tags, it now displays ALL them underneath, so you can click which ones to add
![image](https://github.com/Ylianst/MeshCentral/assets/765314/d312ab0e-3ef6-4289-90d9-fdf6d93aec79)
