### ISSUE TITLE
Error nodemailer

### ISSUE THREAD

**Issue by VM-2020** [Ylianst/MeshCentral#768]
-------- 12/27/2019, 2:40:54 PM ---- 0.4.6-j --------

/var/www/html/**********************/node_modules/meshcentral/meshmail.js:223
                console.log('SMTP mail server ' + parent.config.smtp.host + ' failed: ' + JSON.stringify(err));
                                                                                               ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'issuerCertificate' closes the circle
    at JSON.stringify ()
    at /var/www/html/**********************/node_modules/meshcentral/meshmail.js:223:96
    at SMTPConnection. (/var/www/html/**********************/node_modules/nodemailer/lib/smtp-transport/index.js:346:24)
    at Object.onceWrapper (events.js:300:26)
    at SMTPConnection.emit (events.js:210:5)
    at SMTPConnection._onError (/var/www/html/**********************/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)
    at TLSSocket.SMTPConnection._onSocketError (/var/www/html/**********************/node_modules/nodemailer/lib/smtp-connection/index.js:196:45)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

**Comment by VM-2020** [comment]
When using email verification - the user doesn't receive any and the password reset has the same issue.

**Comment by Ylianst** [comment]
Arg. I will look into this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.6-s with a fix for displaying the error. With this version, the proper error should show up. If you can try it and report back, that would be great. Thanks.

**Comment by visualwritings** [comment]
I promised my colleague (@VM-2020 ) I would complement this issue with some background (and confirmation it now works).

We were trying to configure the SMTP connection with tls: false in config.json, so it would communicate over 587/STARTTLS with our own mailserver (because reasons). This should work in nodemailer but my guess is whatever was the bug you found prevented the setting from coming through correctly. It did mention a notice on startup: **ssl3_get_record: wrong version number**, which I guess is to be expected when you're trying to connect using SSL/TLS over a STARTTLS port.

With version 0.4.6-s the setting seems to come through to nodemailer which in turn accepts STARTTLS, and now mail is working. So I was indeed expecting to get a more proper error describing why there was no connection to the mailserver, but your change actually fixed the issue itself (thanks for that by the way).

**Comment by VM-2020** [comment]
Issue is solved.. thanks!
