### ISSUE TITLE
Duplicate agents on MeshCentral

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#774]
Hi. There are duplicate agents in MeshCentral. Once public IP of client is changed, it is adding additional agent in MeshCentral.
Is there a way to merge them?
See screenshot.
![mc1](https://user-images.githubusercontent.com/59362521/71580767-ea0a7a80-2af9-11ea-98d1-eed58c8160f6.jpg)

**Comment by Ylianst** [comment]
Hi. The "public ip" of the agent should have no impact on the agent's identity. Are the MeshAgent's Windows/Linux/MacOS?

When you install an agent, the agent will create a "meshagent.db" file with it's identity, if this file is deleted on each boot, the agent will create a new one and will show up as a different computer. This is a guess, but the first thing to look at is why the meshagent.db seems to not survive a reboot. If you are on Linux, make sure /usr/local/mesh is a folder that is on disk.

Hope that helps. I would need a lot more information to figure out what is going on.

**Comment by OutbackMatt** [comment]
I sometimes get a ghost 'agent' while Antivirus checks the agent installer on the client machine during install, or when it is is run as a once off (as opposed to installed). 

I just delete the inactive one.

**Comment by vitko-bg** [comment]
Hi and thanks for reply.

I think it is related to a public IP, or local one (have not testes it fully yet on local network).

On MeshCentral -> My Devices -> Agent name - all duplicates are with different "Hostname: <IP address> ".
Here are some records for the duplicated host(some numbers are masked by me): 
178.*.90.6
178.*.88.81
178.*.90.60
77.*.52.109
178.*.88.145

There are is no problem to delete duplicates - but when host is offline - not sure if I will delete the working one ..... Also duplicates are not created during installation - they are appearing in time, let's say every 2-3 weeks for some agents(not all of them off course.)

In regards to AV - I have added meshcentral folder as an exclusion - as some AV blocking it ...

**Comment by MailYouLater** [comment]
I don't know enough to say what's going on or even necessarily to help debug it, but I can say that the reason it's showing up as a new device instead of having the existing 'ghost' come back online is that for some reason, it's not recognizing that it's the same device when it connects, and thus it's connecting as a new device.  As such, if you're not worried about keeping the history associated with the device, you can safely 'delete' the device from the server at any time (even when it is connected) as it will simply reconnect and show up as a new device.  This won't solve the _real_ issue, but it's not going to stop your device from reconnecting later.  Also, as a workaround, if you don't mind not being able to see the offline 'ghost' of your devices, you could set the device group to automatically delete devices when they disconnect, then your old 'ghost' devices will automatically be deleted every time the device disconnects.
![image](https://user-images.githubusercontent.com/1279475/71630969-dd019000-2bba-11ea-84a2-5ad3eaa1cc1d.png)

**Comment by vitko-bg** [comment]
I have deleted all grey (inactive agents) yesterday, and today it has happened again .....
Also all history on log-s for connectons and power state are gone.
The strange is - that IP did not changed ....

here are attachments
![inactive](https://user-images.githubusercontent.com/59362521/71731531-e732c100-2e3c-11ea-90e9-8502a5788a71.PNG)
![active](https://user-images.githubusercontent.com/59362521/71731532-e732c100-2e3c-11ea-8740-716518466024.PNG)

**Comment by MailYouLater** [comment]
It really does seem likely that it's something going on on the device itself, not the server, as the device is supposed to remember it's ... um, node id? I think that's what it's called. ... anyway, the server should see that it's the same device based on that identifier saved @Ylianst was saying is saved in the `meshagent.db` file.  My next recommendation for you would be to fully uninstall the MeshAgent, reboot the machine, then download the MeshAgent installer again and run it from a command prompt with the `-fullinstall` parameter. (i.e. if the meshagent installer exe is `meshagent.exe` you run it as `meshagent.exe -fullinstall`)

**Comment by vitko-bg** [comment]
OK, thanks for suggestion. will try it and will post an update on it.

**Comment by vitko-bg** [comment]
Looks like this issue never came back, so closing it now.
Thanks to all for help.

**Comment by amoljagdalepucsd** [comment]
Hi @si458  , I tried adding `skipmaccheck=1` in `meshagent.msh`, but a new record with new node id was still created.

# Scenario: Wi-Fi MAC Address Change

Note: The Ethernet adapter was disabled to isolate changes to the Wi-Fi MAC address.

### Method 1: Using TMAC Application

Step 1:
Checked the active Wi-Fi MAC: `02-26-2F-AC-5C-8C`

Step 2:
Changed the Wi-Fi MAC via TMAC and assigned a random MAC address.

Step 3:
Rebooted the system twice.

Step 4:
A duplicate record was created for the same asset with a new Node ID.

---

### Method 2: Without TMAC Application

Step 1:
Connected to the office network.
Pressed `Win + I` → Selected the connected Wi-Fi network → Enabled "Random Hardware Addresses"

Step 2:
Restored the original MAC address using TMAC.

Step 3:
Confirmed the current MAC is: `D2-A8-56-8B-B9-98`

Step 4:
Rebooted the system.

Step 5:
Switched to a mobile network.

Step 6:
A new MAC address was assigned: `4C-03-4F-FB-B4-04`, but the agent did not connect to the server.

Step 7:
Rebooted the system twice with the new MAC.

Step 8:
A duplicate record was created for the same asset with a new Node ID.

**Comment by amoljagdalepucsd** [comment]
++ ## Scenario: Ethernet MAC Address Change

### Connected to a Mobile Wi-Fi Network

Step 1:
Press `Win + I` → Go to the connected Wi-Fi network → Enable "Random Hardware Address"

Step 2:
Press `Win + X` → Open Device Manager → Go to Network Adapters
Right-click on the Ethernet connection → Select Properties
Go to the Advanced tab → Select Locally Administered Address
Update the value with a random MAC address.

Step 3:
Disconnect from the mobile network.

Step 4:
Reboot the system.

Step 5:
Connect to Ethernet.

Step 6:
At this point, the agent does not connect and no duplicate record is created yet (possibly due to delayed update).

Step 7:
Reboot the system again.

Step 8:
A duplicate record is created for the same asset with a new Node ID, due to MAC address mismatch.

**Comment by si458** [comment]
@amoljagdalepucsd chances are the mac addresses you are using are invalid because you state `does not connect` multiple times
you shouldnt need to change any mac addresses or anything
just simply add `skipmaccheck=1` to the .msh file and restart,
you MIGHT get 1 duplicate after restart but then afterwards it shouldnt create new devices.

if its still creating new devices, then its not storing information correctly on the machine in its .db file correctly
make sure the .db file isnt being deleted or wiped or anything

**Comment by amoljagdalepucsd** [comment]
Hi @si458 ,

1. I am not using incorrect MAC addresses — the agent is connecting to the server with a new MAC address the next time on its own. For your information, sometimes it doesn’t connect to the server after the first reboot because the agent may not have restarted properly. In such cases, if you manually restart the agent, it connects to the server immediately and creates a duplicate record with a new node ID.

2. I intentionally changed the MAC address to reproduce the issue, as I need to implement a fix for this scenario since it can occur in real-world environments.

3. I tried adding skipmaccheck=1 to the .msh file and restarted the agent, but every time it still creates a duplicate record when the MAC address changes after the restart.

4. I don't believe the .db file is being deleted, wiped, or modified in any way.

**Please suggest a solution to fix this issue.**
