### ISSUE TITLE
Bad web certificate log

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#796]
Hi, I want to know how I detect which client has the following problem:

![Selección_001](https://user-images.githubusercontent.com/26174637/71949286-ef725f80-31a0-11ea-8058-6a81e6008cc4.png)

thanks

**Comment by Ylianst** [comment]
So, this is a bit tricky because the connection to this agent was rejected, so, MeshCentral does not know that agent did this or even if the agent was valid. I could in the future log the public IP address of traffic that causes these issues.

One thing to note is that, if you are using a reverse proxy in front of MeshCentral and switched the certificate that is presented on port 443, you will get this error once but if you configured MeshCentral to a "CertUrl", this error will cause MeshCentral will fetch the updated certificate and everything will work again. Let me know if this is your case.

**Comment by desarrollocdb** [comment]
Hello, thanks for the answer.


This counter has only been submitted once. I wanted to know what was causing it but according to what you indicate it is somewhat complicated. Currently all clients work well.
