### ISSUE TITLE
Clipboard -Copy - Paste

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#802]
Is it going to be a proper clipboard use with keyboard keys in the future ???  :)

**Comment by MailYouLater** [comment]
In case anyone's reading this and wondering what coolwormgit means, I'm pretty sure the 'drag and drop files instead of upload' is a request to be able to Drag & Drop to a remote computer via the Desktop tab, presumably detecting where to place the file based on where on the remote computer you 'dropped' the file, and I think 'proper clipboard use with keyboard keys' is a request for real-time clipboard synchronization, so that you can copy text on your local computer and paste on the remote computer (or vice-versa) without having to open the Clipboard dialog and use the Get/Set Clipboard buttons.
@coolwormgit: These two feature requests are not really related enough to be put in one GitHub issue.  Please consider separating one of them out into it's own GitHub Issue.

Also, while both of these would be nice for ease of use, both of them also seem like they may be rather difficult to implement, so don't expect either of them to be available any time soon.

**Comment by coolwormgit** [comment]
thanks for the detailed explanation! i know that they are difficult features but at least the real time clipboard is a must have feature (in my opinion of course)

**Comment by Ylianst** [comment]
@MailYouLater Thanks, your exactly right on the splitting these into two issues and the difficultly.

For clipboard, you can use the "Clipboard" button to pull/push text into the remote clipboard. Because of limitations with browsers, there is no way to generically sync the clipboards. That would require a native application and that is not planned now (of course, if someone in the community makes one, I will certainly accept it).

![MC2-Clipboard](https://user-images.githubusercontent.com/1319013/72013192-47957a00-3212-11ea-8d38-fd0afea70f29.png)

If both sides are Windows, you could use IE/Edge and try the "RDP" button to control a computer remotely using RDP-over-MeshCentral. In that case, you get full clipboard sync.

For the drag & drop on the desktop... that would be a requested feature, but I would have to prompt where on the remote computer would the file be uploaded. it would be a bit like the "Files" tab, but in the desktop tab. I am a bit swamped right now, but I can see how that would be a nice feature.
