### ISSUE TITLE
About the future of MeshCentral licensing

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#82]
I'm currently self-employed and have my own small business (LLC) that I own together with a friend. We offer IT consulting and SaaS to businesses and would like to incorporate MeshCentral into our software portfolio. We are big fans of this software and we're wondering what your plans for the future of MeshCentral's licensing looks like. Are you planning to change the license from Apache 2.0 to something else once it leaves beta or is it going to be free for commercial use in the future as well?

**Comment by Ylianst** [comment]
Hi. Licensing will stay Apache 2.0 so going forward so you can and will continue to be able to use MeshCentral for commercial projects. In fact, I try to make it easy to rebrand it, etc. Let me know if there are things I can add that will help. Because this project is sponsored by Intel Active Management Technology (Intel AMT) it would be nice if you also demo what Intel AMT can do with your commercial project. This is a win for everyone as some customers will like the fact that you can remotely reboot a computer over the internet and take control of it regardless of OS/Power state. My favorite demo is to remotely boot a computer into the BIOS and change BIOS settings.

**Comment by jsastriawan** [comment]
@whalehub, please drop a note to joko(dot)sastriawan(at)intel(dot)com if once you think your project is mature enough. Let's discuss some strategy separately. Your business idea is definitely interesting.

**Comment by jcam7044** [comment]
@Ylianst Google Authenticator is exactly what I was talking about.  That's fantastic news. This will be a great news for a lot of people. I will be sharing.

**Comment by whalehub** [comment]
@jsastriawan I just sent you and @Ylianst an e-mail. Let's talk more via that channel.

**Comment by whalehub** [comment]
@Ylianst @jsastriawan I showcased MeshCentral a little bit in my new server tour video @ 23:25 and shared it in my Discord server with 1500 members: https://www.youtube.com/watch?v=pOaMAVyy0_0

**Comment by Ylianst** [comment]
Nice. Looks good! If you have any issues or suggestions, please don't hesitate to file them.
