### ISSUE TITLE
terminal broken with latest release

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#84]
Just updated to 0.2.7-c and terminal breaks on all agents. Tested on node v8 and 10.
Terminal connects but as soon as you type 1 character, terminal freezes.

I tried running the agent manually "MeshAgent.exe run" to see what's going on and other features work (remote desktop, files) but as soon as I connect to terminal on the web, the console window on the client closes, however meshagent remains running in task manager with high cpu usage.
Edit: on windows agents, not sure about linux.

**Comment by Ylianst** [comment]
Your right... heading to work now to fix it.

**Comment by krayon007** [comment]
The console window disappearing is normal, it's a side effect of spawning the console as hidden, when you launch the terminal... But I fixed the bug that broke the terminal... Previously I fixed a bug in the polyfill for stream, where _write was ignoring the return value... Terminal uses that object, but it wasn't returning a value... I fixed it, by having it return the correct value... Ylian will let you know when it goes live...

**Comment by krayon007** [comment]
I'll see if I can get the console window to not disappear tho, when you run in console mode... The reason I had to make it disappear, is because I had to set the console window, so that the terminal could scrape it. But when I did that, if you exited the terminal, the console was still there, which would make it so if you tried to exit the agent, it would hang, becuase of the terminal. If I made the terminal hidden, it would correctly close when you disconnect. However, because I grabbed the console context to scrape, when I make it hidden, the console window you launched the agent in dissappears too...

**Comment by Ylianst** [comment]
MeshCentral 0.2.7-f has Bryan's fix for the terminal on Windows. I also noticed that the server self-update code was broken and I fixed it in this version. So, if you have 0.2.7-a to 0.2.7-e, you need to do a manual update using "npm install meshcentral".

**Comment by Ylianst** [comment]
I will close this one as it's been fixed in MeshCentral 0.2.7-f. Please re-open if needed.
