### ISSUE TITLE
0.4.7-I - When using the Desktops / Thumbail view, multiple monitors are not displayed.

### ISSUE THREAD

**Issue by knk90** [Ylianst/MeshCentral#846]
If using 'auto' or using 'connect all' from the desktop view, when opening up a client and going to desktop, the multiple screen option is not present.

Thanks again, let me know if you need any testing to be done.

![image](https://user-images.githubusercontent.com/60167430/72865068-91aa4f80-3d2a-11ea-8cee-251d7d509940.png)

**Comment by MailYouLater** [comment]
Just to point out the known history of this issue so far:
This issue was also [pointed out](https://github.com/Ylianst/MeshCentral/issues/577#issue-508443754) by GoodComputerGuy in issue #577, and I [pointed out](https://github.com/Ylianst/MeshCentral/issues/577#issuecomment-546664445) that it occurs when initiating the desktop connection through the 'multi-device' view.  GoodComputerGuy indicated that he would open a new issue for this, but never did.  Thanks for keeping the scope of this issue to a single problem grumpystrayan.

**Comment by GusevVictor** [comment]
Can confirm that problem.
