### ISSUE TITLE
Add ability to skip around in session recordings with MeshCentral Session Player

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#901]
The ability to record remote control sessions for auditing purposes is quite nice. My only issue with the implementation of this feature is that the built-in player at `/player.htm` lacks the ability to skip around in session recordings.

If you have a 30 minute recording, for example, and you want to watch something that happens 15 minutes into the recording, your only options are to either wait 15 minutes or play back the recording at 10x speed and hope that you can change the playback speed quickly enough to get where you want to go.

It would be very useful if you could skip forward or backward to any place in the recording the way you can do it in any video player application (e.g. VLC).

![vlc](https://user-images.githubusercontent.com/44198148/73599465-1162c600-4544-11ea-8a39-1ea9258d5a92.jpg)

**Comment by Ylianst** [comment]
Good ask. It's more difficult to do that you may think since remote desktop protocols send only changes in the desktop and so, you can't really start the stream in the middle without having most of the desktop being black, etc. There is a way to do this but it will require the recording file to be pre-processed to "index" the file so to speak.

Not sure when I will get a chance to do this.

**Comment by whalehub** [comment]
Added in https://github.com/Ylianst/MeshCentral/issues/902#issuecomment-586086128.
