### ISSUE TITLE
Question: update 0.2.3-r to latest safe?

### ISSUE THREAD

**Issue by edlins** [Ylianst/MeshCentral#924]
Hi, sorry if this is covered already but it seems a quick question with a "do it" "don't do it" type answer.  I'm wondering if such a big jump in versions to 0.4.8-q could impact the agent connections, database, user logins, etc.  So, is it safe to just update to latest?  We have a bunch of agents connected to the 0.2.3-r instance and I don't want to have to touch them all.

**Comment by Ylianst** [comment]
This is a bug jump. It should work just fine. Of course, I would backup everything before doing an update. I can also perform a test later today to revert my test server to 0.2.3-r and upgrade it back and make sure everything works.

Also, let me know what database are you using? Build-in NeDB or did you configure MongoDB?

**Comment by edlins** [comment]
This server is running NeDB.  Thanks!

**Comment by Ylianst** [comment]
Just tried it with NeDB and it worked for me. Going backwards was difficult since there are new settings, etc. But once I had my server at 0.2.3-r, I updated back and all the agents updated correctly. The way I did all this is to install MeshCentral is a different folder, copy "meshcentral-data" over, stop the old one and start the new one. I did not use the built-in update system.

You can do like me or at least, backup "meshcentral-data", "meshcentral-files" and "node_modules", you then rename "node_modules" to "node_modules_old" and do "npm install meshcentral" to re-install all of the fresh dependencies. v0.2.3-r is super old, there are lots of old dependencies in the "node_modules" that need updating.

Note that all of the power tracking and events used to be in "meshcentral.db" but they are now in separate files (meshcentral-power.db, meshcentral-evets.db). When you update, you will loose all the power history and events. This said, the new events and power state will start being collected moving forward in the new files.

Hope that helps. Let me know once you update.

**Comment by edlins** [comment]
Thank you for the detailed instructions!  I'm not sure if we're going to try this or just start migrating agents to our newer installation so I'll close this for now and revisit if we decide to do the upgrade.
