### ISSUE TITLE
Permission & Device Group Structure

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#925]
Now that I've started to work on using MeshCentral full time for my whole team it has become clear that I have misunderstood how the permissions work.

I assumed that each instance of mesh central was treated as one organisation with device groups belonging to that organisation so if you created a new user and made them a full administrator they would be able to see all the devices however it is now clear that devices groups created by a user are owned by that user and each device group has to be shared to any other user or user group regardless of whether or not they hold the Full Administrator server role.

This works well in some respects but also creates a few administration issues. I think two things are needed to resolve this.

1. Be able to see and change the Device Group owner.
2. Be able to make a User Group an owner of a Device Group.

**Comment by ghplw** [comment]
Looking at this further, we also need to be able to clear the 2FA options for another user. If an employee has a bunch of device groups for customers created and they get hit by a bus before sharing or changing the owner on those groups, we would have to go out and setup every single device again in person.

**Comment by treicadani** [comment]
I think an option to make a group public (visible to other administrators) / private (available only to you) would be better, per say if i add my home / work PCs to access it from anywhere i wouldn't want another administrator to come and change the group ownership or remove any security to access my PC and i think is better rather than be allowed to tamper with another administrator account by any means. 

Admin accounts should only be accessible by 1 and only person the account is intended for under ISO 27001 certification, and our company follows that standard (UK), unless you die or lose job and your account is removed from the system not accessed.

**Comment by ghplw** [comment]
There are lots of circumstances where you will need to access another administrators account. As long as the audit logs track the impersonation, password resets etc and which administrator did it then it is not an issue.

At teh end of the day the majority of installations are going to be on company assets and if you link your personal devices in to that infrastruture it should be the employee who takes the risk of doing that and not the company paying for the infrastructure.

**Comment by Ylianst** [comment]
So, I am willing to make changes to the server for this sort of thing as long as it's configurable. Looking at the original post:

`I assumed that each instance of mesh central was treated as one organization` -  In this case, are you talking about MeshCentral domains? You can have a single server with many domains, each domain will have separate users/devices/groups.

`Be able to see and change the Device Group owner.` - There is no "Device Group owner", you can have many different users with administrator permissions on a group. Did you intend to say, that you want to change user permissions of a device group even if you are no permissions on that group?

`Be able to make a User Group an owner of a Device Group.` - Same as above, you are asking to be able to make changes even if you don't have permissions on the device group?

**Comment by ghplw** [comment]
Yes I am talking about domains, I assumed that if I made a person a full administrator within a domain that they would be able to see all the device groups added in to that domain, instead each group still has to be shared to them.

Regarding the device group owner, the creator of each gropu must be the owner. Even using the original adminstrator account that should have global permissions, I cannot see a group another user has created unless they share it to me. Full server administrators should have a way to do this.

As above, the person who created the group is the one that "owns" it and controls who else can see it. If we had the abiliy to make a group an owner then anyone in that group would be able to change the sharing permissions and easily delete old administrators etc without worring about losing a whole group of devices.

Think of it like assigning a security group with full permissions on a folder in a Windows environment. The security groups are the meshcentral User Groups and the folders are the meshcentral Device Groups.

My head is a bit fuzzy at the moment so hopefully I have made the issues/suggested solutions clear enough.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.9-h with a new option to make one or more accounts manage all device groups. You will need to add this line to the domain section of config.json:

`"ManageAllDeviceGroups": [ "admin" ]`

You may need to replace "admin" with the account name that will have all device group rights. Also, that account much have full server rights for this to work, otherwise it's ignored. Let me know how this works.

As for your note above, I don't use the word "owner" or "ownership" in the user interface. One or more users can have full rights on a device group, no specific added privileges are granted to the user that creates the group.

**Comment by MailYouLater** [comment]
Can a user group be set to have access to all device groups?

**Comment by Ylianst** [comment]
@MailYouLater Not currently. Right now, you can only specify one or more users and they have to be site administrators. Feedback appreciated.

**Comment by vitko-bg** [comment]
I am a bit confused - fix me if I am wrong:
What are user levels on the MeshCentral - Global administrator, administrator, manager and user?!?! Or just administrator, manager and user. 
I am asking because until now I was using MeshCentral as Administrator and was managing all users and devices. Now I need to create another user with administrator rights, but with a bit lower priority than Global Administrator.
Will try to clarify what I am trying to achieve:
Let's say: 
Access level 0 - Full(global) administrator, can do everithing with everithing.
Access level 1 - Administrator - Normal administrator, can add devices, groups, users, etc - without option to see or change user accounts from Access level 0.
Manager - Can access and manage all exclude above 2
User - Can access and manage all exclude above 3
Sorry for ugly visualisation :)

**Comment by ghplw** [comment]
Thanks will test tonight.

**Comment by MatinatorX** [comment]
Gave this a try today, but enabling the option didn't seem to do anything. Tried it with my normal username (I'm the admin of course) and just using "admin", rebooting server each time, but saw no change. I'm on 0.5.7.

**Comment by Ylianst** [comment]
Make sure you put

**Comment by MatinatorX** [comment]
I got it working, the issue was that I was putting in my username as I would when logging in, which included capital letters, but it needed to be all lowercase in config.json. Thanks for the help!

**Comment by Ylianst** [comment]
I am going to close this one as the original issue have been resolved. If there are any problems, please feel free to open a new issue.
