### ISSUE TITLE
Is it possible to sync Meshagents date time with MeshCentral server time?

### ISSUE THREAD

**Issue by AnjaniKumar15** [Ylianst/MeshCentral#935]
Is it possible to sync Meshagents date time with MeshCentral server time? So that all machines time in-sync with server.

**Comment by GusevVictor** [comment]
Why you don't want to use ntp servers for that puprose..?

**Comment by Ylianst** [comment]
It's not currently possible. As @GusevVictor indicated, NTP is the right tool for this.

**Comment by MailYouLater** [comment]
Although GusevVictor and Ylianst have a point, I would also find this useful, as there are a couple of computers I have to deal with that have a strange issue where their clocks seem to stop randomly until the time is manually reset.

Using NTP failed in my case, I think because the local computer counts the time until the next sync and sometimes it stops counting before it gets to the next sync, so it might work for me to have the external server push the correct time to the computer every so often, which would (hopefully) start it counting again.

**Comment by Ylianst** [comment]
Can you detail "counting until the next sync"? That sync are you talking about?

**Comment by MailYouLater** [comment]
I mean that NTP clock synchronization is initiated by the client, so if the clock on the client stops counting, the client will never think that it's time for it to sync with the NTP server again, so it will remain stopped.  Anyway, this is a nice-to-have feature that doesn't necessarily make sense for you guys to invest your time and effort into developing, but if you do develop it, it may come in very handy for some of us.
