### ISSUE TITLE
MeshCommander display Error #500 and can't connect to target system via SOL reset to diagnostic.

### ISSUE THREAD

**Issue by kunhung-lin** [Ylianst/MeshCentral#955]
Hi Yilan,

Currently we occur MeshCommander can't connect stably and display Error #500 while we are trying to reset to diagnostic via SOL. 

Once this situation has be happened, we can't connect to target system via meshCommander and it will keep display Error #500, but Intel AMT webUI and Putty console still can connect to target system normally.

Could you help to check this issue? May I know what does Error #500 mean?

Thanks.

Sincerely,
Kun-hung_Lin

**Comment by Ylianst** [comment]
This is interesting, is this a new issue? You can try the older version of [MeshCommander v0.7.9 here](info.meshcentral.com/downloads/mdtk/MeshCommander-0.7.9.msi). I am on vacation for the next week, but if you get a chance, you can run MeshCommander like this:

`nw.exe -wsmantrace` or `nw.exe -redirtrace`.

It will display a trace of what is going on internally and point to the problem. If the trace contains private information, you may need to blank some things and/or send me the [trace privately](https://www.meshcommander.com/contact-information).

**Comment by kunhung-lin** [comment]
Hi Yilan,

I can't download meshCommander v0.7.9 from the link, it return "Not Found".
Could you help provide it again?

Thanks for your help.

Sincerely,
Kun-hung Lin

**Comment by Ylianst** [comment]
Apologies, I fixed the link above. It is: [http://info.meshcentral.com/downloads/mdtk/MeshCommander-0.7.9.msi](http://info.meshcentral.com/downloads/mdtk/MeshCommander-0.7.9.msi)

**Comment by kunhung-lin** [comment]
Hi Yilan,

thanks for your help,
but I think that is not properly to discuss this issue on the Github,
if I still have question, I will try more appropriate way to consult you.

Thank you.

**Comment by MailYouLater** [comment]
I don't see why this project's GitHub issues isn't an acceptable place to discuss this problem.  If there was a GitHub repository for MeshCommander that project's issues would be a better place for this, but since there isn't, and Ylian has accepted a number of other bug reports for MeshCommander in the MeshCentral GitHub issues, this appears to be as appropriate a place as any for this discussion unless there's confidential information involved, in which case you should contact Ylian via the email address and (optionally) PGP key (if sending sensitive information) posted at https://www.meshcommander.com/contact-information.

**Comment by Ylianst** [comment]
Closing this since I am taking care of is separately.

**Comment by Ylianst** [comment]
Note that [MeshCommander is now on GitHub](https://github.com/Ylianst/MeshCommander).
