### ISSUE TITLE
can't connect to client

### ISSUE THREAD

**Issue by olivier37520** [Ylianst/MeshCentral#962]
I had a very strange bug today,
An agent on W10 Home is online but can't connect to Desktop, folders or terminal but I can use console panel.
The only error i had is on terminal connect try showing this quickly :
`{"action":"close","cause":"noauth",msg":noauth-2"}`

Server version : 0.4.9-k
Agent : Windows 10 Home edition x64

**Comment by Ylianst** [comment]
Weird. A few things you can try:

- Try adding `"SessionKey": "MyReallySecretPassword"` to the settings section of the config.json. Make sure to use a really crazy random string for your password since this will secure all of the session cookies.
- Try adding `"CookieEncoding": "hex"` to the settings section of the config.json. This will fix problems where the base64 encoding of the cookie is a problem in some cases.
- If you go in the "My Server" / "Tracing" tab, you can enable tracing for "cookie" and try to connect to remote desktop on a different browser tab, you should see the exact problem.

Hope this helps, let me know what fixes it.

**Comment by olivier37520** [comment]
i had perform a logout/login, and bug is gone for now.
This bug is very strange, can't remote connect (it says noauth, means not logged in i think) but can explore all.

Next time it happens i'll take a look to server trace log

**Comment by ryanblenis** [comment]
I also ran across this one today adding an agent to a Windows 10 Pro 1903 x64 client. Confirming that logging out/in in the MeshCentral interface fixed the issue.
