### ISSUE TITLE
Minimum Linux environment requirement for Mesh client?

### ISSUE THREAD

**Issue by b8two** [Ylianst/MeshCentral#965]
I have some Linux based modem/routers, I was wondering if it was possible to install the Mesh client on to them. 
I've tried the linux install script on one but it failed with a Bash error.

**Comment by krayon007** [comment]
I'm actually working on updating the installer, to make it uniform across platforms, so that you can do a -fullinstall on any platform.

The install script is a little convoluted because it tries to determine what platform, OS, and cpu you are using, so it can fetch the appropriate binary. But if you already know which binary you need, you'll be able to just run the binary directly to install it. (When I'm done with the update that is)

**Comment by krayon007** [comment]
Do you know what soc your router uses? Was the bash error related to not knowing which soc you have?

**Comment by b8two** [comment]
Hi Kryon007,

While you are working on the "meshinstall.sh", the Script is called with wget parameter --no-check-certificate, however internal to the script, this parameter is not used. When I was installing on our Proxmox Linux package (Debian based), I needed to modify the script to add in --no-check-certificate for each wget command.

The two devices we use are NTC-140 and now RUT240. 

But I only tried the NTC-140 so far which results with;

2020-02-22 13:49:35 (58.2 KB/s) - './meshinstall.sh' saved [9596/9596]
-sh: sudo: not found
env: can't execute 'bash': No such file or directory
root:~#

Hence the script didn't start to run at all.

**Comment by Ylianst** [comment]
You can get a list of the available MeshAgents by going to "/meshagents" on your server. For example you can get the list here: [https://meshcentral.com/meshagents](https://meshcentral.com/meshagents). You can see a list of binaries and download links.

Basically, you could try to download the agent that matches the architecture and OS or your device and see if it runs.

If there is no agent that run on your device, the agent will need to be cross-compiled on it.

**Comment by b8two** [comment]
Hi Ylianst,
Thanks for the URL for the MeshAgents, it has moved me a step further. 

Hi Kryon007,

I have found that I don't have BASH shell scripting, however SH shell scripting is avaliable. This is using buzybox.
I have an ARMv7 CPU, hence I started testing with the  [ARMv5 ](https://stackoverflow.com/questions/6771941/how-to-find-out-if-cpu-is-arm-v5-cpu-instructions-compatible) binarary.
After downloading this binrary I was able to launch it, after which I loose control of the shell. On another instance of the shell I check with ps and can see that it is still launched. Disconnecting the first shell also closes the mesh process.

I've tried following the meshinstall.sh manually, however when I try the wget command for meshsettings?id={ID}     It throws the error of "Unauthorized". (after also needing the --no-check-certificate switch).  (ID taken from the installation script from Mesh)
I repeat this step on my computer after authenticating to the web browser and get the same response.

**Comment by krayon007** [comment]
When you launched the binary directly, were any messages displayed on the terminal? You weren't able to Ctrl-c out of whatever it was doing?

**Comment by b8two** [comment]
No Messages, Ctrl-c didn't respond

**Comment by b8two** [comment]
I tried the following Agents in the ARM7 processor.
Linux ARM5 & Linux ARM PogoPlug Hang.
Linux ARM - HardFloat & Linux ARMv8-64 throw a scripting error?

**Comment by krayon007** [comment]
What's the scripting error you encountered?

**Comment by Ylianst** [comment]
I have an original Pogo Plug in the lab, I could give this a try.

![pogoplug](https://user-images.githubusercontent.com/1319013/75750715-a2f75c00-5cd9-11ea-8623-2ffd9b903095.jpg)

**Comment by darryl-h** [comment]
I'm not sure if this belongs here, or if I should file a new issue (_Please let me know!_) our use case is slightly different, but the title of this issue seems fitting.

**Problem Description:** What supporting libraries or packages are required for the Linux Mesh Agent?

For example, when you are in the GUI and click on the Device Group, then click "**Add Agent**" and select "**Linux / BSD**" the resulting command provides a command which calls wget. Additionally we can see that the installer ( https://github.com/Ylianst/MeshCentral/blob/master/agents/meshinstall-linux.sh ) will try and use wget to download the meshagent binary ( https://github.com/Ylianst/MeshCentral/blob/master/agents/meshagent_x86-64 ) in the DownloadAgent() function. 

In Linux, are there any other libraries or packages required for the installation or ongoing use of the agent?

**Use Case 1:** RHEL 7 doesn't come with wget installed by default. Trying to install the MeshAgent fails with 
> bash: wget: command not found

**Use Case 2:** We are looking to use the agent in various hardened environments, as such, we would like to know which packages or libraries are absolutely required (All others may be removed). We have looked through the user documentation ( http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.7.pdf ) , but are unable to find any software packages/libraries requirements for the agent.

**Comment by b8two** [comment]
Hi @darryl-h 

The "Add Agent" and select "Linux / BSD" Provides a link to try with wget and upon failure wget again but with --no-proxy, (removed full URL).
`(wget "https://mesh/meshagents?script=1" --no-check-certificate -O ./meshinstall.sh || wget "https://mesh/meshagents?script=1" --no-proxy --no-check-certificate -O ./meshinstall.sh) 
`

However if you download the script https://mesh/meshagents?script=1
you can see that it is written to try wget and upon failure to use curl;
`wget $url/meshagents?id=$machineid -O /usr/local/mesh/meshagent || curl -L --output /usr/local/mesh/meshagent $url/meshagents?id=$machineid
`

@Ylianst I think that both parts of the "Linux / BSD" option need to be modified to help more users make use of this option;
The install link should try using curl, not just wget (This is inconsistant with the script)
`(wget "https://mesh/meshagents?script=1" --no-check-certificate -O ./meshinstall.sh || curl ./meshinstall.sh -L -k --output "https://mesh/meshagents?script=1" || wget "https://mesh/meshagents?script=1" --no-proxy --no-check-certificate -O ./meshinstall.sh) 
`
^ I don't know if the 2nd Pipe would work or not. Perhaps have a Web Tick Box regarding the use of a proxy or not, I have not looked up the no proxy option for curl.

The downloaded script should be changed to ignore the certificates; (This is inconsistant with the download link)
wget: **--no-check-certificate**  
curl: **-k**
`wget $url/meshagents?id=$machineid --no-check-certificate -O /usr/local/mesh/meshagent || curl -L -k --output /usr/local/mesh/meshagent $url/meshagents?id=$machineid
`

Regarding the "Linux / BSD / macOS Binary Installer" option, perhaps it would be suitiable to also have the curl syntax option and both use the ignore the certificates switches.
