### ISSUE TITLE
0.4.9-k can't scroll back in terminal

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#972]
I don't know if this started with version 0.4.9-k or not but it's the version I'm currently on. 
I'm using the terminal but cannot find any way to scroll back to see previous contents of the terminal. For example, I'm running ipconfig /all (on a Windows 10 box) and there is more data than what can fit in the standard terminal window. I'm all but certain we could scroll back up to see the data that has scrolled past (just like you would in a command prompt on a Windows box directly).  Or am I missing something?

**Comment by krayon007** [comment]
if you go to the console tab, and type osinfo
does it say ConPTY: NO?

I just noticed that on Windows Systems with the new terminal (ConPTY: YES), scrollback works fine, but older Windows that doesn't have it, scrollback doesn't work...

@Ylianst , xterm.js is probably expecting something that the legacy terminal wasn't, for the scrollback to work. You'll probably have to look at the vt100 codes to verify...

**Comment by Ylianst** [comment]
Interesting, I will take a look at this. Back from vacation tomorrow.

**Comment by PathfinderNetworks** [comment]
Hi Bryan, on this particular device it does report back with ConPTY: NO   I thought this was a Windows 10 box but it's actually a Windows 7 box.  I connected to a Windows 10 box and that reports back with ConPTY: YES.  Terminal scrolling does work correctly with that.

**Comment by Ylianst** [comment]
I took a quick look at this and it's unlikely we can fix this. First, you can use the old terminal bu adding "?xterm=0" to the URL (or adding &xterm=0 is other values are already present in the URL).

We can't fix this because the old Windows console is not really a VT100 console, it's more like a fixed size frame of characters that we attempt to copy to the VT100 terminal. If you type "dir" and have a very long list of files, the Windows console may skip to the bottom and not give us the entire list of files if that makes sense. Really, the best is to update to the latest Windows where a real VT100 console is present (like Linux and MacOS). An alternative would be to use the agent console, we could implement some commands there.

**Comment by PathfinderNetworks** [comment]
No problem. Almost all the devices I support are Windows 10 (or Server 2016 on up) so it shouldn't be an issue. If I can use the old terminal when needed with that custom URL then that will work for my needs.

**Comment by Ylianst** [comment]
Note that the old terminal also does not have scroll back on older Windows versions, so I don't think there is much of a benefit in using the old terminal. I only use the old terminal for Intel AMT Serial-over-LAN feature now since that terminal was built for that usage.
