### ISSUE TITLE
MeshCMD LMS MeshCommander fails with "No Upgrade Listener" on Windows 10

### ISSUE THREAD

**Issue by matt-primrose** [Ylianst/MeshCentral#976]
Running the latest (as of 2/26/20) MeshCMD when running meshcmd microLMS  and try to connect to localhost:16994 with browser, MeshCMD emits message "No Upgrade Listener" and MeshCommander page has "MicroLMS disconnected" message.

Issue seen on Windows 10 with AMT FW 8.x and 11.x versions.

**Comment by krayon007** [comment]
Are you able to pull the latest agent from GIT and use that? I actually found this bug a few days ago and pushed the fix into the agent repo.

**Comment by MailYouLater** [comment]
> Are you able to pull the latest agent from GIT and use that?

Please inform on how to do this.  I would really like to do this to try out the changes you made recently for issue 968.

**Comment by krayon007** [comment]
Here's the easy way:

clone the git repository for the agent, and build the solution file, using either: Debug, Debug64, Release, or Release64.

(You may have to build twice, because I have a pre-build event that tries to pull in the commit hash and date into the source code, to expose as metadata, but if you build the Console and Service at the same time, sometimes the prebuild script freaks out because it's building the two projects in parallel, so sometimes the write for one of them fails.)

After done, copy the MeshService64.exe (or MeshService.exe for 32 bit), into the same same folder where your service is installed, and name it the same, which should be MeshAgent.exe. Before you copy, youll have to stop the service. From an admin console, just issue the command:

wmic service "Mesh Agent" call stopservice

This will stop the service. Then after you copy over the binary,  run the agent in console mode, with the following command: MeshService64 run --disableUpdate=1

This will run the agent in console mode, and temporarily disable auto update, so the server wont try to downgrade the agent. This will get the agent running, so you can test the new feature you were talking about.  In the meantime, we are going to work on an agent update...

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-m with Bryan's latest agent. [MeshCMD was also updated](https://www.meshcommander.com/meshcommander/meshcmd) on the web site, download the new version and let us know if it works.

**Comment by MailYouLater** [comment]
Thanks for the info.  What version of Visual Studio would you recommend?

I realise I took too long to get to this and you guys have already released a new version that has both the feature mentioned here and the other feature I was interested in, but this is still good info for the future.  Perhaps this should be added to the docs?

**Comment by krayon007** [comment]
I currently build everything on Visual Studio 2015. I've started getting things ready to upgrade VS, but I haven't had time to officially migrate away from 2015 yet.
